### ISSUE TITLE
Multi-paged Webpart Property Panes - Pagination doesn't work as expected, stopping users from accessing pages

### ISSUE THREAD

**Issue by tandrasi** [SharePoint/sp-dev-docs#8483] opened 2022-10-06 03:23 UTC
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

**Hi, I was told by a contributor of the PnP Modern Search repo (https://github.com/microsoft-search/pnp-modern-search) to duplicate a bug we found here as they suspect it is an SPFx issue.**

### Describe the bug / error

Hi, I was told by a contributor of the PnP Modern Search repo (https://github.com/microsoft-search/pnp-modern-search) to duplicate a bug we found here as they suspect it is an SPFx issue.

The bug in question is the following: https://github.com/microsoft-search/pnp-modern-search/issues/2405. It has gained a lot of traction in the last couple of days as it seems to only have started occurring this week - regardless of version of the PnP Modern Search web parts used.

Here is the original post that started it all by user **twodul**

> Describe the bug
>
>On the search result web part configuration property pane,
>1 of 4 : next button working so can see the 2nd page
>2 of 4 : when I click next button it go to "1 of 4" page not "3 of 4" page.
>I can't set up available connection from 3rd page configuration.
>
>It works fine with my test tenant environment and this issue happens only on our production environments.
>
>I got below JavaScript error when I click next button.
>![image](https://user-images.githubusercontent.com/72114492/194206250-a0b6fcc2-5edf-4dfd-b0e2-4097e0591413.png)
>
>I attached the console log messages. [SearchResultsPropertyPannelErrorLog.txt](https://github.com/SharePoint/sp-dev-docs/files/9720863/SearchResultsPropertyPannelErrorLog.txt)
>
>![image](https://user-images.githubusercontent.com/72114492/194206358-438f4de7-b91f-4f6c-b4d8-aa44bab06daf.png)

### Steps to reproduce

1. Add PnP Modern Search "Search Results" or "Search Filters" web parts to a page.
2. Edit the web part and try access page 3 or 4 of the property pane.
3. Pages 3 or 4 are not accessible on those web parts -> clicking on "next" on Page 2, will loop back to Page 1.

### Expected behavior

1. Panel page should increment to page 3 and 4 when required.

**Comment by Georg-Trixl** [comment] 2022-10-06 06:29
I got the same problem, with Chrome, Egde and Firefox - all in latest stable Version

**Comment by Kanamo** [comment] 2022-10-06 07:20
I got the same problem in three diferent tenants

**Comment by FranckyC** [comment] 2022-10-06 12:31
@AJIXuMuK FYI, this specific page is all about SPFx dynamic data, listing available data sources and retrieving existing connections if it can help to identify the cause.

**Comment by ekdegerman** [comment] 2022-10-06 15:22
This recently started happening to us too. After another issue we faced today, I realized that it seems the common denominator for the tenants it happens in is that SharePoint is now using React 17. Tenants still using 16.13.1 still work fine. Hope this can help give a clue...
![image](https://user-images.githubusercontent.com/56835119/194352854-64fcc794-c70e-4617-b6d7-fc1ff7b10087.png)

**Comment by AJIXuMuK** [comment] 2022-10-10 15:34
The fix has been done and should roll out in the next 2 weeks.

**Comment by KuotingChiu** [comment] 2022-10-13 23:29
@AJIXuMuK , how is this fix being rolled out?  It is a SharePoint Online release update?   Any client side alternative possible ?

**Comment by AJIXuMuK** [comment] 2022-10-13 23:56
@KuotingChiu - this is service-side update. 
We will roll out new version 100% next Monday. 
You won't need to do any changes.

**Comment by KuotingChiu** [comment] 2022-10-17 13:31
@AJIXuMuK , our developer's initial confirmation is positive, Thanks a lot!!!  May I ask if this type of changes to break and fix the issue was announced such as using the M365 message center at all?  We have a support incident opened for this issue and the assigned support person as well as the incident escalation manager were not helpful at all.

**Comment by rogbac** [comment] 2022-10-18 08:52
@AJIXuMuK "Next Monday", does that mean Monday October 24th to be clear? We have customers with applications that down due to this so they need to be informed.

**Comment by AJIXuMuK** [comment] 2022-10-18 12:12
@rogbac - next Monday is yesterday

**Comment by rogbac** [comment] 2022-10-18 13:26
Ok thanks, then we hope to see a change to the positive anytime soon. Still same in the customer tenants experiencing this.

**Comment by AJIXuMuK** [comment] 2022-10-18 13:43
@rogbac - that should be already there.
I would try opening the browser page in incognito (Private) mode to see if the error is there.
Also - is that the same error as described in this issue? Or some other kind of error?

**Comment by KuotingChiu** [comment] 2022-10-18 14:08
Our tenant seems to be fine now.  Isn't this change applied to all tenants?

**Comment by AJIXuMuK** [comment] 2022-10-18 15:03
@KuotingChiu - it is applied to all tenants.
I strongly believe @rogbac has some other type of the issue.
I will close this one.
@rogbac  - feel free to create a new issue with detailed description of what's happening for you.

**Closed by AJIXuMuK** 2022-10-18 15:03 UTC
Labels: type:bug-suspected, area:spfx, status:fixed-next-drop, react-17

**Comment by FranckyC** [comment] 2022-10-18 15:22
Thanks for the fix BTW @AJIXuMuK !

**Comment by rogbac** [comment] 2022-10-20 19:00
Just som feedback in this thread. NOW it works for us again, we noticed it today in several tenants that it just started work. Previously today we still had the error described in this thread, but sometime the last hours it fixed it itself. So the rollout/rollback has not been global on the same day for everyone as feedback. Happy it works again though!

**Comment by AJIXuMuK** [comment] 2022-10-20 19:33
@rogbac - the rollout was global.
The thing here that _potentially_ you could have cache (most probably service worker) that loaded old modules.
