### ISSUE TITLE
sp-client-preview package is present in the RC0 package.json file

### ISSUE THREAD

**Issue by vman** [SharePoint/sp-dev-docs#367] opened 2017-01-20 11:54 UTC
#### Category
- [ X] Bug

#### Expected or Desired Behavior
sp-client-preview package should not be present in the RC0 package.json file

#### Observed Behavior
The docs for RC0 state that _you should no longer be referencing sp-client-preview, and there is a new @types/webpack-env package._ but the sp-client-preview package is still being referenced in the package.json

#### Steps to Reproduce

1. get latest version of SPFx with `npm i -g @microsoft/generator-sharepoint@latest`
2. create a new webpart project with `yo @microsoft/sharepoint`
3. observe the package.json file

Node version is 6.9.4

![image](https://cloud.githubusercontent.com/assets/173794/22148760/e9e817ba-df07-11e6-8325-98f1fa2dac4d.png)

**Comment by patmill** [comment] 2017-01-20 18:55
Thanks @vman .Issue logged.

**Comment by manishgarg1** [comment] 2017-01-23 04:33
@vman, we are still working on removing the last remnants sp-client-preview. The recommendation in the documentation implies that third party developers should not take a dependency on the sp-client-preview package as it is going away.

**Comment by manishgarg1** [comment] 2017-01-29 22:05
Hi @vman, I am resolving this issue as by design at the current time. sp-client-preview should get removed from the code in a soon to come build. thanx.

**Closed by manishgarg1** 2017-01-29 22:05 UTC
Labels: status:tracked, type:bug
