### ISSUE TITLE
AadHttpClient constructor removed from 1.5 plusbeta release

### ISSUE THREAD

**Issue by OliverZeiser** [SharePoint/sp-dev-docs#2001] opened 2018-06-10 10:01 UTC
#### Category
- [X] Question
- [X] Bug

#### Expected or Desired Behavior
We should be able to use the AadHttpClient in 1.5 plusbeta. Thats what the beta is for, right?

#### Observed Behavior
The Typescript Definition file states     **Excluded from this release type: __constructor** 
So how should we use the AadHttpClient?

**Comment by qrown** [comment] 2018-06-11 08:31
Possible duplicate of https://github.com/SharePoint/sp-dev-docs/issues/1964

**Comment by VesaJuvonen** [comment] 2018-06-12 06:05
We are working on fixing this with updated npm packages within upcoming days. Sorry for the inconvenience.

**Comment by muradaliyev** [comment] 2018-06-12 15:14
This is what I use and it works:
let _client = new (AadHttpClient as any)(this.context.serviceScope, '<aad app id>')

**Comment by vsoderholm** [comment] 2018-06-22 04:36
Solution here #2093

**Comment by pbjorklund** [comment] 2018-07-03 15:57
Is it just my lack of understanding or did 1.5.1 remove the export of a bunch of stuff @VesaJuvonen ?

In 1.5.1 index-internal.d.ts (which is referenced from index.d.ts) there is ```/* Excluded from this release type: AadHttpClient */``` as well as a bunch of other things.

Seems like there was quite a bit of change in the pipeline from 1.4.1 to 1.5.1 no? At least 
the below seems to indicate that to me :)

```// THIS FILE IS PART OF THE TEST-API PATTERN.
//
// It is copied by a rule from config/post-copy.json during the build.
// You should not add it to Git.
//
// For documentation, please see sp-core-library/etc/test-api-pattern/README.md

export * from './index-internal';```

**Comment by patmill** [comment] 2021-09-02 19:54
Sorry - this should have been closed a long time ago.

**Closed by patmill** 2021-09-02 19:54 UTC
Labels: area:spfx, status:tracked
