### ISSUE TITLE
SPFX ms graph not working in SharePoint Mobile App #7421

### ISSUE THREAD

**Issue by harshdamaniahd** [SharePoint/sp-dev-docs#7470] opened 2021-11-02 12:37 UTC
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### What browser(s) / client(s) have you tested

- [X] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [X] 💥 Safari
- [X] mobile (iOS/iPadOS)
- [X] mobile (Android)
- [X] not applicable
- [X] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Describe the bug / error

I have a webpart , which is built using SPFX  but contains graph api.
It seems that it doesnt work now in production release, but works in targetted release.

### Steps to reproduce

1. First Create the Webpart using SPFX, and add a graph query
2.Add the webpart on sharepoint page
3.Download sharepoint mobile app and open the page in the app. nothing happends

### Expected behavior

The webpart should load with data from microsoft graph

**Comment by patmill** [comment] 2021-11-02 18:30
Closing as a duplicate of #7468

**Closed** 2021-11-02 18:30 UTC
Labels: type:bug-suspected, status:duplicate, area:spfx
