### ISSUE TITLE
Doesn't trigger "Apply" button for non-reactive property panes

### ISSUE THREAD

**Issue by randompixel** [SharePoint/sp-dev-docs#2806] opened 2018-10-23 09:50 UTC
I've followed this documentation through, but the property pane is non-reactive. When you change the drop-down item the Apply button doesn't become enabled.

Piecing together other bits of bug reports, it seems the main component needs a render signature that has a `changeCallback` function, but this is incompatible with the Interfaces defined in this documentation.

It would be good if this documentation covered both reactive and non-reactive property panes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c1d71f2-3508-56e2-6ea7-461591498d19
* Version Independent ID: 0546c161-74c4-fb37-ce89-f7cf0e49cf91
* Content: [Build custom controls for the property pane](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/build-custom-property-pane-controls)
* Content Source: [docs/spfx/web-parts/guidance/build-custom-property-pane-controls.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/guidance/build-custom-property-pane-controls.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by TheMiao** [comment] 2018-10-31 03:37
@randompixel  David

Could you zip your project and sent to me pls?

I would like test your project from my end.

**Comment by randompixel** [comment] 2018-10-31 08:34
@TheMiao I can't I'm afraid to the whole thing - working under confidentiality for a client. However, I can share the `controls` folder as it is basically the tutorial but renamed - nothing confidential in there.

[controls.zip](https://github.com/SharePoint/sp-dev-docs/files/2533319/controls.zip)

In the main webpart file I have:
```
protected get disableReactivePropertyChanges(): boolean {
    return true;
}

protected onAfterPropertyPaneChangesApplied(): void {
    ReactDom.unmountComponentAtNode(this.domElement);
    this.render();
  }

/**
   * Handle event for dynamic property pane field
   * @param propertyPath 
   * @param newValue
   */
  private onReportSelectorChange(propertyPath: string, newValue: any): void {
    const oldValue: any = get(this.properties, propertyPath);
    // store new value in web part properties
    update(this.properties, propertyPath, (): any => { return newValue; });
  }

protected getPropertyPaneConfiguration(): IPropertyPaneConfiguration {
    return {
      pages: [
        {
          groups: [
            {
              groupName: strings.BasicGroupName,
              groupFields: [
                new PropertyPaneAsyncReportSelector('reportId', {
                    label: strings.ReportNameLabel,
                    loadOptions: this.loadAvailableReports.bind(this),
                    onPropertyChange: this.onReportSelectorChange.bind(this),
                    selectedKey: this.properties.reportId
                }),
                PropertyPaneTextField('limitToRoles', {
                  label: strings.LimitToRolesLabel,
                  description: strings.LimitToRolesDescription,
                }),
              ]
            },
.... // more properties
}

private loadAvailableReports(): Promise<IDropdownOption[]> {
    return new Promise<IDropdownOption[]>((resolve: (options: IDropdownOption[]) => void, reject: (error: any) => void) => {
        // XMLHTTPRequest to get options from API.
  }
}
```

**Comment by TheMiao** [comment] 2018-11-02 09:32
@randompixel  David

I've tested from my end.
It seems like the apply button (disableReactivePropertyChanges) will only handle textbox's changes.

I guess this is by design.

If you add a textbox into custom panel, and make some changes, apply button will become clickable. 

![image](https://user-images.githubusercontent.com/11746477/47906721-d303d480-dec4-11e8-8075-c4069ac97a13.png)

**Comment by randompixel** [comment] 2018-11-02 09:36
Yes, it's a workaround in that our users can edit a different field. But it's still a workaround. The only stuff on the web I could find was to do with this https://github.com/SharePoint/sp-dev-docs/issues/356 but I could work out how to tie up the different method signatures added in that issue with the above documentation.

**Comment by MayurSorthiya** [comment] 2019-09-04 09:49
@randompixel David
how to implement custom property control with angular 2+?

**Comment by andrewconnell** [comment] 2019-10-21 10:12
@MayurSorthiya This question is unrelated to this issue thread. Please don't hijack existing issues like this, please create new issues for new topics.

**Comment by andrewconnell** [comment] 2019-10-21 10:15
@randompixel & @TheMiao I'm following up on old & still open issues... can you clarify what you're saying, that the property pane, when set to non-reactive mode, will only display the **Apply** button when the textbox is dirty, not when other controls are dirty?

**Comment by randompixel** [comment] 2019-10-21 10:36
HI @andrewconnell, this was with SPFX 1.7. Not been able to test any further as client didn't want further development on it.

There was a property pane that had a <select> style box populated by AJAX depending on which of 3 radio buttons are selected. The [Apply] button is initially available to select. You can click it and changes happen, but the pane stays open (correctly I think). However, if you then pick a different item in the <select> box the [Apply] button doesn't re-enable. All the other controls do make it re-enable. I think it's something to do with the `render` function of the custom control not being right, but I followed the docs to the letter.

**Comment by andrewconnell** [comment] 2019-10-21 13:40
Well, since it was with a very old version of SPFx, the first thing I'd say is the issue needs to be repro'd using the latest SPFx version, v1.9.1, so an issue that's already resolved is being chased.

I haven't seen other reports of this, so for now, I'm going to close this.

**Closed by andrewconnell** 2019-10-21 13:40 UTC
Labels: Needs: Attention :wave:, area:docs-comment, area:framework-general
