### ISSUE TITLE
SharePoint Add-In ClientWebPart iFrame not resizing in Modern pages

### ISSUE THREAD

**Issue by butchmarshall** [SharePoint/sp-dev-docs#1653] opened 2018-04-12 20:10 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

The add-ins clientwebpart iframe to resize to the desired height via postmessage

`<message senderId=79A219AE0>resize(289,713)</message>`

#### Observed Behavior

The postmessage is being sent but the iframe is not resizing (parent page is either broken or not listening).

#### Steps to Reproduce

Install a sharepoint add-in with a clientwebpart you want to add to a modern-ui page.

**Comment by VesaJuvonen** [comment] 2018-04-19 18:03
There is currently no support for resizing app parts (iFrames) in modern UIs, so this is currently by design. We are potentially looking into this in future, but no promises. Closing for now as "by design".

**Closed by VesaJuvonen** 2018-04-19 18:03 UTC
Labels: area:add-ins, area:framework, status:by-design, type:bug
