### ISSUE TITLE
Add link to "See also" section

### ISSUE THREAD

**Issue by LostMarbals** [SharePoint/sp-dev-docs#5713] opened 2020-05-11 15:17 UTC
Please consider adding this link as well to the See Also section:
https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/implement-a-sharepoint-site-classification-solution

This page speaks to HOW to manage Site Classifications, but not really WHY (with only a small reference: "Based on the classification value of a site, you can define automation and custom policy rules."

Linking to the article I reference actually speaks to the quote and is the next logical step one might take once learning how to create and manage these labels.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27643fd2-8059-f411-224b-bd0815aacc8f
* Version Independent ID: bd410f9a-a3f2-9222-7d4a-2271d7f6161d
* Content: [SharePoint ](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/modern-experience-site-classification#feedback)
* Content Source: [docs/solution-guidance/modern-experience-site-classification.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/modern-experience-site-classification.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by PrasadKasireddy** [comment] 2020-05-11 19:20
Thanks - duplicate of https://github.com/SharePoint/sp-dev-docs/issues/5712
Sure, we will add this

**Comment by LostMarbals** [comment] 2020-05-11 20:26
Thanks, yes my friend apparently thought to make the same request as we were discussing it together earlier in the day 😊

Respectfully,

Martin Ballard
Sr. Premier Field Engineer
425-705-4832
[A picture containing drawing, woman, red, blue  Description automatically generated]

Your feedback helps me grow. Please feel free to reach out to me or my manager Heather Gatewood<mailto:hegatewo@microsoft.com> anytime.

**Closed** 2020-05-12 10:49 UTC
Labels: area:docs, area:docs-comment, status:fixed-next-drop
