### ISSUE TITLE
The solution does not work if the app is deployed to Microsoft Team Android or iOS

### ISSUE THREAD

**Issue by mkokabi** [SharePoint/sp-dev-docs#7666] opened 2022-01-21 19:38 UTC
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

macOS

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [X] mobile (iOS/iPadOS)
- [X] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Describe the bug / error

There is no response when the application is deployed to MS Team app (Android and iOS).

### Steps to reproduce

1. Follow the steps mentioned in this page to build the app
2. Follow the steps in [this page](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab)
3. Test the app in MS Team in mobile (either Android or iOS)

### Expected behavior

Expect to return the output shown in this article.

**Comment by AJIXuMuK** [comment] 2022-01-24 20:51
Dupe of #7646

**Closed** 2022-01-24 20:52 UTC
Labels: type:bug-suspected, status:duplicate, Needs: Triage :mag:
