### ISSUE TITLE
Debug cannot hit breakpoint

### ISSUE THREAD

**Issue by stone12379** [SharePoint/sp-dev-docs#2831] opened 2018-10-26 03:24 UTC
OS: macOS Mojave 10.14
VS Code: 1.28.2
Chrome: 70.0.3538.77
yo @microsoft/generator-sharepoint: 1.6.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 959a8968-baa1-e94c-10af-a52604aef21e
* Version Independent ID: cecd4be2-5717-d282-587e-7a93910a03a3
* Content: [Debug SharePoint Framework solutions in Visual Studio Code](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/debug-in-vscode)
* Content Source: [docs/spfx/debug-in-vscode.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/debug-in-vscode.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Seiyasu** [comment] 2018-10-27 08:16
Please provide your reproducible sample and more other information, such as screenshot. If you **run gulp server --nobrowser** and then try to use local workbench, you need to run the https://localhost:5432 first.

**Comment by stone12379** [comment] 2018-10-29 04:07
Thank for Seiyasu. Actually, I have lanched https://localhost:5432/workbench for the first time to debug. However, I still cannot hit the break point, even when the log shows that the line of code has been executed. Screens in below.

**Comment by stone12379** [comment] 2018-10-29 04:09
![2018-10-29 12 03 50](https://user-images.githubusercontent.com/10493864/47628955-724a6400-db73-11e8-81d3-83b9f2bb2185.png)
![2018-10-29 12 04 36](https://user-images.githubusercontent.com/10493864/47628956-724a6400-db73-11e8-8a1a-3021fba00ca6.png)
![2018-10-29 12 05 07](https://user-images.githubusercontent.com/10493864/47628957-724a6400-db73-11e8-93f1-415d2a491892.png)
![2018-10-29 12 05 39](https://user-images.githubusercontent.com/10493864/47628958-72e2fa80-db73-11e8-8a0f-7062a482df7c.png)

**Comment by Seiyasu** [comment] 2018-10-29 05:02
Due to you use local workbench, you should run **gulp serve** but not **gulp serve --nobrowser**. The latter is mainly for hosted workbench but not the local. 

You can refer to the related issues:
 https://github.com/SharePoint/sp-dev-docs/issues/2772
https://github.com/Microsoft/vscode-react-native/issues/625

**Comment by stone12379** [comment] 2018-10-29 05:50
used 'gulp serve' instead but still not working.
<img width="1680" alt="2018-10-29 1 45 24" src="https://user-images.githubusercontent.com/10493864/47631560-7f6e4f80-db81-11e8-9d5d-c59dcd005c87.png">
![Uploading 屏幕快照 2018-10-29 下午1.46.13.png…]()

**Comment by stone12379** [comment] 2018-10-29 06:05
<img width="1680" alt="2018-10-29 1 46 13" src="https://user-images.githubusercontent.com/10493864/47632074-826a3f80-db83-11e8-81f8-24edc5470739.png">

**Comment by phillipharding** [comment] 2018-10-31 02:16
I have the same issue
[Debugging SPFX Web Part With VS Code Issue](https://techcommunity.microsoft.com/t5/SharePoint-Developer/Debugging-SPFX-Web-Part-With-VS-Code-Issue/m-p/279429#M5868)

**Comment by tsekityam** [comment] 2018-11-21 09:49
Adding statement `debugger;` as https://github.com/SharePoint/sp-dev-docs/issues/2772#issuecomment-433277028 suggested breaks the code.

However, it breaks the code in a new read-only file, and the break point set in VS Code still don't activated.

With spfx v1.4.1, the break point is broke at the editing file, and after that version, none of the break point set in VS Code breaks. Perhaps spfx v1.5.0 introduced the bug.

**Comment by RihardsVla** [comment] 2018-11-26 09:01
I have the same issue, all latest updates are installed. 
You can activate breakpoints only after setting the brakepoint on the same line in Chrome as set in vscode . Setting breakpoints in VSCode has no effect. However the debuging actualy happens in VS Code.

**Comment by andrewconnell** [comment] 2018-11-27 09:49
Seems something changed in the code generated by the SPFx Yeoman generator and now the hint paths in the **launch.json** file is not valid.

Add the following path and it should be working:

`"webpack:///.././src/*": "${webRoot}/src/*",`

**Comment by nero120** [comment] 2018-11-27 13:47
Thanks @andrewconnell, that sorted it for me.

**Comment by phillipharding** [comment] 2018-11-27 18:15
Brilliant, cheers @andrewconnell that fixed it

**Comment by mike-morr** [comment] 2018-12-01 03:46
@VesaJuvonen can we get the line provided by @andrewconnell to the launch.json?  This is still broken in the latest generator.

**Comment by andrewconnell** [comment] 2019-02-14 14:22
This was fixed in current SPFx v1.7.1

**Closed by andrewconnell** 2019-02-14 14:22 UTC
Labels: area:community, area:docs, area:framework, status:fixed
