### ISSUE TITLE
CSOM: cannot ensure multiple users at once

### ISSUE THREAD

**Issue by baywet** [SharePoint/sp-dev-docs#3191] opened 2018-12-31 16:32 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Being able to ensure multiple users in a single execute query via the CSOM.

#### Observed Behavior
Each ensure user needs it's own execute query in order to work properly. This adds unecessary roundtrips which impacts performance.

#### Steps to Reproduce
Using CSOM (online) : 16.1.8412.1200 
```CS
// initialize your context here
var missingUsers = new List<string> { "user1@contoso.com", "user2@contoso.com"}; //replace by valid users in your tenant
// this doesn't work, accessing something like the email property will give you a prop not initialized exception
var ensuredUsers = missingUsers.Select(x => siteCollContext.Web.EnsureUser(x));
ensuredUsers.ToList().ForEach(x => siteCollContext.Load(x));
await siteCollContext.ExecuteQueryRetryAsync();
// this works
var ensuredUsers = new List<User>();
foreach(var missingUser in missingUsers)
{
 var user = siteCollContext.Web.EnsureUser(missingUser);
 siteCollContext.Load(user);
 await siteCollContext.ExecuteQueryRetryAsync();
 ensuredUsers.Add(user);
}
```

**Comment by VesaJuvonen** [comment] 2019-01-24 18:54
Hi @baywet, You are correct that the API design is not optimal, but technically this is not a bug, so closing it from here.

**Closed by VesaJuvonen** 2019-01-24 18:54 UTC
Labels: Needs: Triage :mag:, type:uservoice-request

**Comment by baywet** [comment] 2019-01-24 19:04
thanks, moved it there, I'm not hoping for too much traction but we never know… https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/36623038-sharepoint-csom-rest-ensureuser-multiple-users-per
