### ISSUE TITLE
Classic Webpart page getting refreshed after configuring the SPFx webpart.

### ISSUE THREAD

**Issue by Savan12791** [SharePoint/sp-dev-docs#497] opened 2017-03-17 13:36 UTC
My spfx webpart is running fine at modern page but at classic webpart page it get refreshed and data is not getting stored.

When i clicked on apply my webpart for 4-5 second showing the rssfeed but my page getting refreshed after doing this and i become like newly added webpart.

![image](https://cloud.githubusercontent.com/assets/26480786/24044907/3c601e40-0b43-11e7-9f8f-517388b1d578.png)

![image](https://cloud.githubusercontent.com/assets/26480786/24045225/575e8cf8-0b44-11e7-901f-fd395c1d6bed.png)

**But after this page gets refreshed and its become like-**

![image](https://cloud.githubusercontent.com/assets/26480786/24045302/98382c16-0b44-11e7-8666-095f8804b33a.png)

**Comment by patmill** [comment] 2017-03-17 18:28
A couple of quick questions - Have you done anything different with you save pipeline?  Ie, do you have custom field handlers that persist the data differently, etc?
Second, on a modern page, if you hit refresh (not just save), are your changes persisted?

**Comment by Savan12791** [comment] 2017-03-20 05:07
No i don't have custom field.
On modern page changes are persist.

**Comment by patmill** [comment] 2017-03-20 05:10
@manishgarg1 - any ideas?  @Savan12791 - you are hitting "save" after apply I assume.

**Comment by Savan12791** [comment] 2017-03-20 05:12
@patmill - No i am not hitting save.

**Comment by suz7777** [comment] 2017-03-20 05:18
@patmill  - when i do the following on a classic page:
-- edit the page
-- edit the web part
-- click on the properties button
-- change the properties
-- click SPFx Apply
-- click Web part pane Apply
the page will refresh - it doesn't hurt the changes or the page that i can see.

suz

**Comment by patmill** [comment] 2017-03-20 05:22
Right. On classic, everything is a post and a refresh.  But the data should stick around. A full refresh of the URL without a save could result in data "loss", but that should throw up a warning.

________________________________

**Comment by Savan12791** [comment] 2017-03-20 05:28
the data which i have configured in SPFx pane setting dialogue are not getting save on classic page, so we do we need to do changes in code for this because  modern page handles this automatically.

**Comment by suz7777** [comment] 2017-03-20 05:30
are you on chrome or IE - windows 10 or windows 7... we find everything works perfect in chrome and Windows 10, but i have a windows 7 / IE11 user who is reporting this issue.  I am curious if there is something to the IE/windows version

**Comment by Savan12791** [comment] 2017-03-20 05:31
@suz7777  I am using windows 7 and Chrome.

**Comment by suz7777** [comment] 2017-03-20 05:32
hmmmm.... i will ask our user to try that out and report back

**Comment by Savan12791** [comment] 2017-03-20 05:33
Ok @suz7777

**Comment by Savan12791** [comment] 2017-03-21 16:58
No i have checked again and issue are still there.

**Comment by Savan12791** [comment] 2017-03-21 17:00
i you want i can share the solution.

**Comment by jonathanhotono** [comment] 2017-03-22 10:17
This could be caused by the Button element doesn't have the `type="button"` attribute which will cause a refresh on classic page.

**Comment by manishgarg1** [comment] 2017-03-22 16:15
Hi @Savan12791, please note, in classic pages you always need to click on the OK/Apply button on the classic page toolpart after you have completed configuring the web part with the modern PropertyPane. If you do not click on the OK/Apply button, the changes will not get saved.

**Comment by Savan12791** [comment] 2017-03-23 06:18
Hi @manishgarg1 , As you can see in screen shot ,page getting refreshed before click to ok or apply.

When i click on apply on spfx page-setting pane, its getting refresh and data got lost ,so after page refresh there is no meaning to click on web part proprieties's Ok/Apply button.

**Comment by Savan12791** [comment] 2017-03-23 06:21
Hi @jonathanhotono, i dont have any button element on the page.

**Comment by Savan12791** [comment] 2017-04-01 15:14
Any Update?, I am still facing this issue.

**Comment by manishgarg1** [comment] 2017-04-18 00:40
@Savan12791, not sure how to get this resolved. We are unable to repro this inhouse. What browser are you using? Is there a way for us to see the repro?

**Comment by cwdata** [comment] 2017-06-21 10:55
2 months later - still not working. Property pane settings are not persisted on classic pages. No matter if the pane is set to reactive or non-reactive mode. It only works on modern pages.
Tested on Windows 10 build 1703 using IE 11 and Firefox 53.0.3. O365 first release tenant, German language.
No errors regarding this in the console.

**Comment by manishgarg1** [comment] 2017-08-14 19:21
Hi @Savan12791, aplogies for the delay on the responses. Here are some more steps to help you debug the issue.

- Switch web part to edit mode in the Chrome browser
- Edit web part and change properties on modern property pane
- Make the changes.
- Start the chrome debugger and clear all network requests and enable the "Preserve log" feature
- Close the modern property pane and click on the OK button on classic Toolpart
- Go back to the chrome debugger and look for a POST request at the top of the requests for the page you were viewing. e.g. in my case the request URL looks something like this "https://msft.spoppe.com/sites/ClassicPageTeamSite/SitePages/Test.aspx?PageView=Shared&InitialTabId=Ribbon.WebPartPage&VisibilityContext=WSSWebPartPage".

- Now inspect the "Request Payload" of the request
- It should be from POST data.
- In this data look for an entry with "clientSideToolPartData" as the name of the MIME content. See if you changes are in there. If yes, then there is some problem in persisting the changes on the server. If NO, then there is a client bug.

Content-Disposition: form-data; name="ClientSideToolPartData"

<div data-sp-webpart="" data-sp-webpartdataversion="1.0" data-sp-webpartdata="{&quot;id&quot;:&quot;490d7c76-1824-45b2-9de3-676421c997fa&quot;,&quot;instanceId&quot;:&quot;g_1d686e2a_55ef_4074_8d98_16f39cf3c251&quot;,&quot;title&quot;:&quot;Embed&quot;,&quot;description&quot;:&quot;Embed content from other sites such as Sway, YouTube, Vimeo, and more.&quot;,&quot;dataVersion&quot;:&quot;1.0&quot;,&quot;properties&quot;:{&quot;shouldScaleWidth&quot;:true,&quot;embedCode&quot;:&quot;<iframe width=\&quot;563\&quot; height=\&quot;315\&quot; src=\&quot;https://www.youtube.com/embed/hpDHwfXbpfg\&quot; frameborder=\&quot;0\&quot; allowfullscreen=\&quot;\&quot;></iframe>&quot;}}"><div data-sp-componentid="">490d7c76-1824-45b2-9de3-676421c997fa</div><div data-sp-htmlproperties=""></div></div>

**Comment by cwdata** [comment] 2017-08-15 07:41
Seems the fix provided for issue #596 fixed this one too. The properties are persisted now.

**Comment by BigEaseGueldi** [comment] 2017-08-15 08:40
Yep - works for me, too.

**Comment by andrewconnell** [comment] 2018-12-14 18:08
@VesaJuvonen seems like this can be closed as fixes in other issues seems to have resolved this one.

**Closed** 2019-04-25 21:22 UTC
Labels: status:tracked, type:discussion
