### ISSUE TITLE
Lazy load doesnot work when we make tile like view using rowFormatter in View Formatter JSON

### ISSUE THREAD

**Issue by deepikakaur** [SharePoint/sp-dev-docs#5464] opened 2020-03-17 09:45 UTC
## Category
- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

Lazy load doesnot work when we make tile like view using rowFormatter.
We can see only 30 items after that the items are not getting loaded in the view created.

Is there a way to set Tile view as default i.e. the view which we create using tileProps?

## Environment details (if applicable)

- OS: Windows 10
- Browser(s): chrome , edge 
- Tooling: VS Code

**Comment by shagra-ms** [comment] 2020-03-24 09:57
Thanks for reaching out @deepikakaur.

Using rowFormatter to show tiles like view has limitations, as you have mentioned in your comments. The recommended way for tiles is to use tileProps. 

Ability to land directly on tiles layout for a View is in our backlog.

**Comment by shagra-ms** [comment] 2020-03-24 10:45
Marking this as duplicate of #4763 which is tracking this issue.

**Closed by shagra-ms** 2020-03-24 10:45 UTC
Labels: area:list-formatting, status:answered, type:question
