### ISSUE TITLE
JavaScript error after changing display language

### ISSUE THREAD

**Issue by mihmbox** [SharePoint/sp-dev-docs#552] opened 2017-04-19 12:41 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Observed Behavior
JavaScript error on page

#### Steps to Reproduce
1. Change your language to e.g. Russian (but I think it can be reproduced  with some other languages too)
2. Open page with Spfx webpart

![image](https://cloud.githubusercontent.com/assets/7473764/25180344/4f735e06-2516-11e7-9f50-8e50b5766c5f.png)

**Comment by Sotna** [comment] 2017-04-19 13:33
Same for German
![image](https://cloud.githubusercontent.com/assets/27772512/25182557/aa40d334-251d-11e7-86de-3987a4771a9e.png)

But works fine for Spanish
![image](https://cloud.githubusercontent.com/assets/27772512/25182587/cab1e2ca-251d-11e7-9810-d524397c2b15.png)

**Comment by manishgarg1** [comment] 2017-04-19 16:47
@iclanton ?

**Comment by iclanton** [comment] 2017-04-20 01:53
This is an issue with how the page boot code is generated by the server on the classic page. It looks like the strings aren't being escaped correctly.

**Comment by manishgarg1** [comment] 2017-04-20 03:17
Got it. I will get that fixed.

**Comment by paulewert** [comment] 2017-04-20 20:09
Thank you @manishgarg1! I've ran into the same issue with German. Spanish is fine and will have to shift to that language until the issue is resolved.

**Comment by Sotna** [comment] 2017-05-02 08:04
Hi guys.
We're about to go live soon. Is it possible to provide date when this will be fixed?

**Comment by mihmbox** [comment] 2017-08-07 07:36
Hi guys,
@manishgarg1 any updates?

**Comment by BigEaseGueldi** [comment] 2017-08-14 15:57
Hi, after having tested this on two tenants it seems to be fixed.

@manishgarg1 , @srideshpande 
-> Would make sense to review and possibly close the following issues: 
https://github.com/SharePoint/sp-dev-fx-webparts/issues/234; #587; #596 and #552

**Comment by srideshpande** [comment] 2017-08-14 18:43
@BigEaseGueldi  - Thank you for confirming. I will go ahead and close the issue.

Thanks,
Srikanth

**Closed by srideshpande** 2017-08-14 18:43 UTC
