### ISSUE TITLE
Install the developer certificate step is missing important details

### ISSUE THREAD

**Issue by sharepointland** [SharePoint/sp-dev-docs#2433] opened 2018-08-28 20:39 UTC
Before you can run the "gulp trust-dev-cert" command you must first create a project ("yo @microsoft/sharepoint") and then in a command window or PowerShell window you can run the "gulp trust-dev-cert" command from the root of the project folder created. Also, I got the error "local gulp not found" on Windows 10 after installing gulp if I don't reboot first. The error I get when running the trust-dev-cert command in a folder without the gulpfile.js is "no gulpfile found".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bee09a8-022e-1b5a-4aab-d6e7c6216808
* Version Independent ID: 49edce1e-f2be-e989-917f-c6b389363e2f
* Content: [Set up your SharePoint Framework development environment](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment)
* Content Source: [docs/spfx/set-up-your-development-environment.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/set-up-your-development-environment.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by deepikatyagi** [comment] 2018-11-26 11:07
The issue is fixed by running npm i command in the directory where your webpart is installed.

**Comment by bblasingame** [comment] 2018-11-29 19:20
Running npm i seems to have fixed the problem. Still had different errors running gulp trust-dev-cert after going back to version 8.

**Closed** 2019-01-11 12:50 UTC
Labels: area:docs, area:framework
