### ISSUE TITLE
Request to support --no-install or --skip-install for yeoman generator

### ISSUE THREAD

**Issue by gavinbarron** [SharePoint/sp-dev-docs#235] opened 2016-10-12 18:12 UTC
#### Category
- [ ] Question
- [ ] Typo
- [ ] Bug
- [x ] Enhancement / Suggestion
- [ ] Additional article idea
#### Expected or Desired Behavior

If I run `yo @microsoft/sharepoint --skip-install` no dependencies from bower or npm are installed
#### Observed Behavior

If I run `yo @microsoft/sharepoint --help`
I'm told that there is a --skip-install option. That's part of the base set of options that come with yeoman it turns out.
I would suggest that this command line option is used rather than the `--no-install` that has been discussed on here previously (and isn't working)
#### Steps to Reproduce

run `yo @microsoft/sharepoint --skip-install` 
You will see that the npm dependencies are installed

**Comment by waldekmastykarz** [comment] 2016-10-13 08:22
This is caused by how the options are passed into the subgenerators. Instead of passing the options object from the parent a new set of options is created in the `./generators/app/index.js` file on line 36. That way all options passed to the main generator are lost. Instead of creating a new options object it would be better if the existing object was cloned and extended with the properties required by the specific subgenerators.

**Comment by chakkaradeep** [comment] 2016-10-20 05:33
@gavinbarron can you gives us more information on where this scenario is applicable?

@nickpape-msft do we have this command?

**Comment by waldekmastykarz** [comment] 2016-10-20 05:36
@chakkaradeep image an organization would have a standardized set of dependencies they have tested and approved for their projects. They would have a Docker image with these dependencies installed. When creating a new project they would create it without dependencies and run a Docker container based on the standard image to run the project.

**Comment by chakkaradeep** [comment] 2016-10-20 05:44
@waldekmastykarz Thanks! We are working to make these scenarios better but totally see the use for this command.

**Comment by andrewconnell** [comment] 2016-12-08 15:24
Here's another reason why we want this @chakkaradeep - NPM shouldn't be forced as the only game in town. Using Yarn, you can speed up dependency acquisition by 70% and even support full offline dev (after the first web part you create). 

See this for more info & demos: http://www.andrewconnell.com/blog/speed-up-every-new-spfx-web-part-creation-by-up-to-70-with-yarn

**Comment by gavinbarron** [comment] 2016-12-08 15:37
Yarn is what I was actually playing with when I discovered that these flags
do nothing.

**Comment by chakkaradeep** [comment] 2016-12-08 18:03
@andrewconnell We are keeping an eye on Yarn. There are few issues we have identified internally that needs to be addressed either in the toolchain or in the yarn system itself. 

However, this is not about `forcing npm`. Node/NPM is widely used and many have bet against it for their systems. That said, improvements and innovations come by. Yarn is certainly interesting and has its use. SPFx tool chain will evolve as we progress to evaluate and incorporate such improvements for sure. That is indeed our goal. 

Now, tech aside:
- What is the key question(s) we are trying to answer? 
- What is the key scenario(s) we are trying to enable here?

**Comment by andrewconnell** [comment] 2016-12-08 20:32
So I'm not trying to push Yarn, I'm simply saying that users should have an option to bypass the step of downloading all packages. Using Yarn instead of NPM was simply a scenario as to why we want this flag... just responding to [your request above](https://github.com/SharePoint/sp-dev-docs/issues/235#issuecomment-255013045).

What key question / scenario you're trying to enable: to let developers work the way they want to work and not forcing specific path that isn't configurable unless you hit `CTRL+C` to abort what's going on. 

Not to mention it also seems you intend on supporting it as the flag is in the code, it's just not being respected when the step of running `npm install` by the generator.

**Comment by CharlieDLee** [comment] 2017-01-03 21:17
This gets my vote.  Anything that gives me options and does not tie me to one technology component in the stack can only be a good thing regardless of why you might choose to do it.  We currently do use NPM as our package manager, but who can say that we won't want to use something else tomorrow!

**Comment by chakkaradeep** [comment] 2017-01-10 20:21
All,

This should be fixed in the RC0 release. You can now use the option as follows:

```
yo @microsoft/sharepoint --skip-install
```

Please let us know if you still find issues.

Thanks!

**Comment by patmill** [comment] 2017-02-25 01:36
Closing...

**Closed by patmill** 2017-02-25 01:36 UTC
