### ISSUE TITLE
Either a bug in SPFx 1.12 or documentation needs to be updated

### ISSUE THREAD

**Issue by s-KaiNet** [SharePoint/sp-dev-docs#6837] opened 2021-03-19 16:16 UTC
Steps to reproduce: 

1. Create a new React-based web part using SPFx 1.12. 
2. Add `nl-nl.js` to apply localization. 
3. Run `gulp serve --locale=nl-nl` 
4. Add web part with localized labels to a page - labels still use the default `en-us` locale. 

I created a sample repo [here](https://github.com/s-KaiNet/spfx12-locale-bug). I have identical code in `spfx11` (1.11) and `spfx12` (1.12) folders. When I run `gulp serve --locale=nl-nl` in `spfx12`, it doesn't display labels in `nl` locale. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33394188-10be-0875-025d-9ffff6618df9
* Version Independent ID: ca9875f8-4f6a-21d3-8483-66ced7c2d55c
* Content: [Localize SharePoint Framework client-side web parts](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/localize-web-parts)
* Content Source: [docs/spfx/web-parts/guidance/localize-web-parts.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/guidance/localize-web-parts.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by VesaJuvonen** [comment] 2021-03-22 10:38
Thanks @s-KaiNet for the detailed work on this issue. Having repro from1.12 and matching experience from 1.11 will certainly help to fix this as fast as possible. Based on quick review, looks like an unfortunate regressions from 1.12. Engineering will be looking on this more closely within upcoming hours.

**Comment by KevinTCoughlin** [comment] 2021-03-23 15:33
This will be fixed in next patch release. Thanks for reporting. It was a regression in tooling.

**Comment by VesaJuvonen** [comment] 2021-03-24 12:28
This issue is intended to be part of the 1.2.1 patch release. Currently we recommend to keep on using 1.11 until further notice. We do apologize the inconvenience.

**Comment by KevinTCoughlin** [comment] 2021-04-12 19:01
@s-KaiNet can you confirm this "--locale" issue is fixed in `1.12.1-rc.0` suite of packages e.g. https://www.npmjs.com/package/@microsoft/generator-sharepoint/v/1.12.1-rc.0?

**Comment by s-KaiNet** [comment] 2021-04-12 21:47
Tested on `node@14.16` & `npm@7.7.6` - the issue is resolved for me.

**Closed** 2021-04-13 00:20 UTC
Labels: 1.12.x, area:docs-comment, area:spfx-general, status:fixed, status:tracked, type:bug-confirmed

**Comment by VesaJuvonen** [comment] 2021-04-13 07:17
Thanks @s-KaiNet for the help on validating this and confirming that fix is included in the RC bits.

**Comment by andrewconnell** [comment] 2021-07-01 13:40
@s-KaiNet Did you test this with the final GA version of SPFx v1.12.1? Looking at the timestamps, it appears this was tested with RC's as GA came out on April 28. 

From my exp in two different projects with SPFx v1.12.1 & Node v14.16.1, the `--locale` argument isn't being respected & tested with both the local & hosted workbench.
