### ISSUE TITLE
Property Pane Groups in Accordion Mode: expand only one group at a time.

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-docs#781] opened 2017-08-14 23:28 UTC
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Reference to [UserVoice](https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/20543812-sharepoint-framework-property-pane-enhancements)

For now we can render Property Pane groups as accordion using `displayGroupsAsAccordion: true`.
The thing is that usually in accordion controls only ONE group can be expanded. It means that if user tries to expand some other group, the one that was previously expanded will collapse.

So, the question is if it's a bug that it works in other way in Property Pane or it is by design?
If by design, do you plan to add an option to implement described behavior?

**Comment by mcmynn83** [comment] 2017-08-15 16:58
Thanks for your feedback.  Your request in user voice to change the feature is the right way to give feedback like this.  I am closing this issue as it is by design (according to our current design).

**Closed by mcmynn83** 2017-08-15 16:58 UTC
