### ISSUE TITLE
Single Part App Page never receives onDisplayModeChanged when Save is clicked - Regression

### ISSUE THREAD

**Issue by rgarita** [SharePoint/sp-dev-docs#4896] opened 2019-11-13 18:56 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
On a Single Part App Page (web part targeting `supportedHosts.SharePointFullPage`), when in Edit mode and the user clicks the "Save" button on the property pane, the `onDisplayModeChanged` is fired and the `webpart.displayMode` is updated to `DisplayMode.Read`.

#### Observed Behavior
When the user clicks the Save button, the `onDisplayModeChanged` function is not called, and the `displayMode` remains as `DisplayMode.Edit`.
 
Regression of  #4456 

#### Steps to Reproduce
1. On a Single Part App Page, click the Edit button to open the property pane. Notice the `onDisplayModeChanged` function is fired, and the webpart's displayMode has changed from DisplayMode.Read to DisplayMode.Edit.
2. (probably optional step) Modify a property, such as changing the page title (built-in field).
3. Click the "Save" button. Notice the `onDisplayModeChanged` function is not fired, and the web part's displayMode remains as DisplayMode.Edit.
 
#### Additional Info
 This issue relates to #4456 and is created to improve visibility. The content was partially copied to make it easy to review.

**Comment by andrewconnell** [comment] 2019-11-13 20:22
Context? What types of tenants (TR/SR) have you verified this in?

**Comment by rgarita** [comment] 2019-11-13 23:57
Hello @andrewconnell . We have verified this on the MS tenant (microsoft.sharepoint.com), And we already reported internally, we just created this bug here for tracking purposes. 

Raul G (v-raugar)

**Comment by rgarita** [comment] 2019-11-14 00:05
Env: SP Online, Node Version 10.16.0
CC @GrahamMcMynn,

**Comment by rgarita** [comment] 2019-11-14 00:07
Sorry clicked the wrong button

**Comment by rgarita** [comment] 2019-11-25 22:59
Hello @andrewconnell , any update on this item?

**Comment by andrewconnell** [comment] 2019-12-07 15:30
Yeah... regression... going to close this as a dupe. See https://github.com/SharePoint/sp-dev-docs/issues/4456#issuecomment-562253434 for details....

**Closed** 2019-12-07 15:31 UTC
Labels: area:framework-general, status:duplicate
