### ISSUE TITLE
Custom web parts (spfx) are not available from subsites without installing the add-in.

### ISSUE THREAD

**Issue by theepan18** [SharePoint/sp-dev-docs#518] opened 2017-03-25 00:15 UTC
Custom web parts (spfx) are not available from subsites without installing the add-in.
Is there any way to install add-in with CSOM?
Or any behavior changes on the way ?

**Comment by zplume** [comment] 2017-04-28 09:59
It's not possible currently - see:
https://github.com/SharePoint/sp-dev-docs/issues/483#issuecomment-287767613
https://github.com/SharePoint/sp-dev-docs/issues/344#issuecomment-273271576

Hopefully tenant-scoped deployment (SPFx equivalent described by Pat in the 2nd link above) will be implemented soon to resolve this...

**Comment by mpasarin** [comment] 2017-12-22 12:07
Today you have available both ALM API ( https://docs.microsoft.com/en-us/sharepoint/dev/apis/alm-api-for-spfx-add-ins ) and tenant-scope deployment.
I will close the issue as the problem is now resolved.

**Closed by mpasarin** 2017-12-22 12:07 UTC
Labels: type:discussion

**Comment by RaspeR87** [comment] 2018-04-26 18:10
If you want to install spfx web parts to subsites for on-prem too please take a look at my blog post -> [https://rasper87.wordpress.com/2018/04/26/provision-spfx-web-parts-to-classic-sites-part-3-install-spfx-web-part-to-sharepoint-site-web/](https://rasper87.wordpress.com/2018/04/26/provision-spfx-web-parts-to-classic-sites-part-3-install-spfx-web-part-to-sharepoint-site-web/)
