### ISSUE TITLE
"teams" folder is missing when project is created in a subfolder with 1.7.1 --plusbeta

### ISSUE THREAD

**Issue by vman** [SharePoint/sp-dev-docs#3423] opened 2019-02-08 14:12 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When default scaffolding is created with the 1.7.1 --plusbeta version of the generator and select "Create a subfolder",  the "teams" folder should be present as described in this article:
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab

#### Observed Behavior

If you create the scaffolding with `1.7.1 --plusbeta`, and select "Create a subfolder" the "teams" folder is absent.

#### Steps to Reproduce
1) Make sure SPFx v1.7.1 is installed
2) `yo @microsoft/sharepoint --plusbeta --skip-install`
3) During the initial setup wizart, select "Create a subfolder"
4) Observe that the teams folder is absent

**Comment by andrewconnell** [comment] 2019-02-10 20:21
What's your installed environment look like (_Node, NPM, Yeoman versions_)? Just did the same with v1.7.1 and it is present... so I can't repro...

![image](https://user-images.githubusercontent.com/2068657/52538977-2d73c300-2d47-11e9-89ad-8db136a2b715.png)

There was an issue with v1.7.0 where it was adding the `teams` subfolder all the time, regardless if you used `--plusbeta` or not. The v1.7.1 fixed this so it should only appear when you include the beta flag.

**Comment by vman** [comment] 2019-02-10 23:26
Here is my environment:

![image](https://user-images.githubusercontent.com/173794/52541265-e8718000-2d8a-11e9-904d-d01e86ba8665.png)

I noticed you are on a mac and I am on windows. I don't have a mac handy to test if that's the difference.

**Comment by andrewconnell** [comment] 2019-02-11 11:34
It's not a Mac / Windows thing... I have the same expected behavior on Windows:

![image](https://user-images.githubusercontent.com/2068657/52560557-b54ce200-2dc6-11e9-847e-ad308d71980e.png)

So it's something else local to your machine I think... still can't repro your experience...

*BTW... as I said in my last post, you will **always** see the `teams` folder get created in v1.7.0 because of a bug in the generator. Regardless of the presence of the `--plusbeta` switch, the v1.7.0 generator will ALWAYS add that folder. v1.7.1 fixed this behavior so you only see it when adding the flag.*

**Comment by vman** [comment] 2019-02-11 14:32
Thanks for your help on this @andrewconnell! I think I know whats wrong. The teams folder is missing when I select "Create a subfolder" in the initial wizard. I also don't get the question which determines the `isDomainIsolated` setting
![image](https://user-images.githubusercontent.com/173794/52569490-375dfa80-2e09-11e9-8381-e08373cb6791.png)

However, if I select "Use the current folder", I get the teams folder as well as the `isDomainIsolated` setting:
![image](https://user-images.githubusercontent.com/173794/52569757-d2ef6b00-2e09-11e9-880a-0b57db5e24a7.png)

Are you able to reproduce this?

**Comment by andrewconnell** [comment] 2019-02-11 14:53
Good find... yes, I can confirm that when you select **"create a subfolder with a solution name"**, it's like the `--plusbeta` is not respected. Will raise this with engineering too...

**Comment by vman** [comment] 2019-02-11 15:03
Although the `package.json` does have all the `1.7.1-plusbeta` versions of the SPFx packages. That's what I used to confirm that I wasn't going mad and was indeed using the `--plusbeta` flag.

**Comment by VesaJuvonen** [comment] 2019-02-11 15:15
Clearly a bug, which we'll be checking to fix for the 1.8 release. Thx @vman for reporting.

**Comment by VesaJuvonen** [comment] 2019-03-07 18:51
Fixed in 1.8, which is coming out soon.

**Comment by andrewconnell** [comment] 2019-03-07 19:00
![](https://media.giphy.com/media/5totXGbmSkkaz9QxFi/giphy.gif)

**Closed** 2019-06-19 12:32 UTC
Labels: area:framework-general, status:fixed, type:bug
