### ISSUE TITLE
Following build logic is very difficult

### ISSUE THREAD

**Issue by bpkennedy** [SharePoint/sp-dev-docs#1046] opened 2017-11-13 17:37 UTC
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Using `gulp` task management should allow client-side developers to see and understand what tasks are happening.

UPDATE:  On further reflection, I want to clarify exactly what i expect.  If we are using `gulp` as the build system I expect to be able to easily find a place where the standard API usage of Gulp is used to create tasks.  As in the [Gulp readme](https://github.com/gulpjs/gulp), I expect to find some code like

```
var gulp = require('gulp');
gulp.task('scripts', ['clean'], function() {
  return //do some stuff
});
```

This is how Gulp is used, and **this is what a developer who uses Gulp would expect**.  Instead (see below), there is a convoluted Build/Rig system where the Gulp tasks are injected through the various dependency chain.

#### Observed Behavior
The current build system is all over the place.  What is the expectation here - what are you trying to provide to developers? For example, I need to trace down how `tslint` and `typescript` tasks are being implemented in the build process so that i can make adjustments.  I am not simply doing a before/after build task - I need to turn OFF or Overwrite with NULL/Undefined the `tslint` and `typescript` tasks.  Here's an example of trying to follow the code from the point of execution on my client.

* Start at `gulpfile.js`.
* See `const build = require('@microsoft/sp-build-web');`
* Into node_modules, see `sp-build-web` > `index.d.ts` > see this:

```
export * from '@microsoft/sp-build-common';
export * from '@microsoft/gulp-core-build-sass';
export { reload, trustDevCert, untrustDevCert } from '@microsoft/gulp-core-build-serve';
export * from '@microsoft/gulp-core-build-webpack';
export * from '@microsoft/gulp-core-build-karma';
export * from '@microsoft/sp-build-core-tasks';
export * from './SPWebBuildRig';
export * from './WebBuildRigConstants';
import { SPWebBuildRig } from './SPWebBuildRig';
import * as Gulp from 'gulp';
export declare const rig: SPWebBuildRig;
export declare const initialize: (gulp: typeof Gulp) => SPWebBuildRig;
```

Follow what next?  `@microsoft/sp-build-core-tasks`?  Ok, let's do that.
* node_modules > see `sp-build-core-tasks' > see `index.d.ts` > see this:

```
import { ConfigureWebpackTask } from './configureWebpack/ConfigureWebpackTask';
import { ConfigureExternalBundlingWebpackTask } from './configureWebpack/ConfigureExternalBundlingWebpackTask';
import { CopyAssetsTask } from './copyAssets/CopyAssetsTask';
import { WriteManifestsTask } from './writeManifests/WriteManifestsTask';
import { CasperJSTask } from './casperJs/CasperJSTask';
import { CollectLocalizedResourcesTask } from './collectLocalizedResources/CollectLocalizedResourcesTask';
import { PackageSolutionTask } from './packageSolution/PackageSolutionTask';
import { DeployAzureStorageTask } from './deployAzureStorage/DeployAzureStorageTask';
import { DevDeployTask } from './devDeploy/DevDeployTask';
import { ConfigureRigTask } from './configJson/ConfigureRigTask';
import { SpfxServeTask } from './spfxServe/SpfxServeTask';
```

Ok, now follow what next?  I must have missed something, so let's back up to the `index.d.ts` file in my editor....oh, which one?  **Yes, do you see my pain here?**  :P
* Back in `sp-build-web/index.d.ts` > maybe we should have seen `SpWebBuildRig.d.ts` > ok, so now I see some .... well some `getTasks()` and `getTestTask()` and getOtherTasks, etc.  Well...where are the Tasks!?

I undertand the need for modularity and separation of concerns, but this isn't even the end of the story.  Following any one of those down the chain leads me through a trail of `imports` with confusing names and at one point I was about 6 or 7 deep and totally lost/confused.

Why is this put together in this way?  Can this be made better?  And at the end of the day - how in the heck do I control the `gulp` tasks?  Microsoft says that I don't have to use Typescript but the Typescript tasks in your build chain are buried so deeply that I can't get to them to turn them off.

Please HELP!

#### Steps to Reproduce
This is a question.

**Comment by russgove** [comment] 2017-11-14 00:42
+1

**Comment by pgonzal** [comment] 2017-11-22 19:32
> The current build system is all over the place. What is the expectation here - what
> are you trying to provide to developers? 

The design goal of Gulp is for your build tools to be an ordinary computer program (called `gulpfile.js`), versus a pattern matching engine (like Make), or versus a giant pluggable config file (like Grunt).  Gulp's model does add a little more to this idea -- some "task" entry points, a way to pipe files through asynchronous streams, and the idea that each tool should be wrapped up as a Gulp stream transformer -- but the essence of Gulp is the idea that you can step through the Gulpfile using a debugger, and if you need any special functionality, you open up `gulpfile.js` and start coding.  We adopted Gulp because of its popularity.

Internally we have hundreds of projects that we build every day.  We quickly realized that we don't want to maintain hundreds of copies of `gulpfile.js`, each with its own quirks and bugs (and no TypeScript compiler validation).  When `gulpfile.js` has bugs, the errors can be unintelligible, and it causes lots of headaches for our automated builds.

The rigs/tasks model was introduced to reduce our gulpfiles to a set of standard "rigs" whose behavior is customized using config files, which conform to well-defined JSON schemas.  Each rig represents a project stereotype such as "internal web project", "third party web project", "tools project", etc.  The rig is actually a combination of reusable "tasks" that get wired together.  (Gulp's definition of a "task" cannot be wired in this way, because its dependencies are predetermined, so we had to abstract the "task" concept a little.)

As you bluntly pointed out :-) , the implementation we ended up shipping carries a lot of baggage due to the changing requirements and realizations that happened after the initial design.  Also, the challenges that we face internally may be different from the individual developer who's just trying to make a simple web part.  Compared to when we started work on SharePoint Framework, the way you bundle a web project is a lot more standardized today, and people's expect it to be simple.

We get it.  We want to make the SPFx tools simpler and easier to understand.  There isn't a quick fix however, since there's a *lot* of projects that depend on the current model, and it works very well in practice despite its shortcomings.  We're working on it.

> I am not simply doing a before/after build task - I need to turn OFF or Overwrite
> with NULL/Undefined the tslint and typescript tasks.

Let me see if I can find a recipe for this.  I'll follow up.

**Comment by pgonzal** [comment] 2017-11-22 19:35
#1039 is a duplicate of this issue.

**Comment by qz2017** [comment] 2017-12-04 23:56
We are closing this issue. @pgonzal  has answered your question and @nickpape-msft has posted a solution in the mentioned related issue #1039 . If you have any questions, please feel free to open an issue.

**Closed by qz2017** 2017-12-04 23:56 UTC
Labels: area:tooling, type:question
