### ISSUE TITLE
Modern Webpart built using latest spfx version not working on the classic page 

### ISSUE THREAD

**Issue by Masood10** [SharePoint/sp-dev-docs#1917] opened 2018-05-29 10:38 UTC
- [X] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

 Expected or Desired Behavior

I have built an angular 1.x webpart application using the spfx 1.4 version. The webpart works in the modern sites pages. It should also work in the classic site pages.    

 Observed Behavior

The webpart is not working on the classic site pages and I am getting the following error. 

> [SPWebPartErrorCode.IncorrectBoostrapModule]:
> 
> Bootstrap module for web part WebPart.CsTaskBoardWebPart.g_76cddb14_eed9_4284_81a4_b8db3ff64e8c not of the correct type. Make sure to export your web part as 'export default WebPartName'.
> ***CALLSTACK:
> 
> t@https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-05-18.011/sp-classic-page-assembly_en-us_9bd26145452b8a6a140c7ec7a2b736fb.js:201:15770
> t@https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-05-18.011/sp-classic-page-assembly_en-us_9bd26145452b8a6a140c7ec7a2b736fb.js:301:9108
> ......

package.json 
```
  "dependencies": {
    "@microsoft/generator-sharepoint": "^1.4.1",
    "@microsoft/sp-build-web": "^1.4.1",
    "@microsoft/sp-core-library": "^1.4.1",
    "@microsoft/sp-lodash-subset": "^1.4.1",
    "@microsoft/sp-office-ui-fabric-core": "^1.4.1",
    "@microsoft/sp-webpart-base": "^1.4.1",
    "@microsoft/sp-webpart-workbench": "^1.4.1",
    "@types/jquery": "^2.0.48",
    "@types/jqueryui": "^1.12.2",
    "@types/react": "0.14.46",
    "@types/react-addons-shallow-compare": "0.14.17",
    "@types/react-addons-test-utils": "0.14.15",
    "@types/react-addons-update": "0.14.14",
    "@types/react-dom": "0.14.18",
    "@types/webpack-env": ">=1.12.1 <1.14.0",
    "angular": "^1.6.10",
    "react": "15.4.2",
    "react-dom": "15.4.2"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "~1.4.1",
    "@microsoft/sp-module-interfaces": "~1.4.1",
    "@microsoft/sp-webpart-workbench": "~1.4.1",
    "@types/angular": "^1.6.43",
    "@types/chai": ">=3.4.34 <3.6.0",
    "@types/mocha": ">=2.2.33 <2.6.0",
    "ajv": "~5.2.2",
    "gulp": "~3.9.1"
  }
```

Can it be because
I was using the 1.4 version for development but the "includeClientSideAssets": true, property was not working in package-solution.json file and was giving error like "not available etc". So I updated all the modules starting with sp including generator sharepoint and the includeClientSideAssets property worked.  

I never tested it on classic site pages before so I am not sure updating should cause any problems instead it should solve the issue. 

Please tell me how to make the webpart work on the classic site pages.

**Comment by alvi40000** [comment] 2018-10-11 22:04
Masood10, did you figure out a root cause for this issue.  I'm seeing similar issues with a react app on multiple tenants.

**Comment by Masood10** [comment] 2018-10-15 08:41
there was a custom extension in the classic page and it was loading the jQuery as global and was causing the problem. I also had I duplicate entries in the resources.en.txt file. on removing duplicates it worked.

**Comment by andrewconnell** [comment] 2019-02-20 20:47
Closing as OP implies it was fixed.

**Closed by andrewconnell** 2019-02-20 20:47 UTC
