### ISSUE TITLE
Footer not showing up at all

### ISSUE THREAD

**Issue by coxwagner** [SharePoint/sp-dev-docs#3973] opened 2019-05-16 16:44 UTC
Hello,

My environment is on SharePoint Online with GCC G3 license.
After reviewing the new features (navigation, footer, etc), I created a test communication site collection to try the new features, but the footer never appeared on the site. I though it could be disabled, so I went to PowerShell and used the code below:

Connect-PnPOnline -Url "<SiteURL>" –Credentials (Get-Credential) 
$web = Get-PnPWeb 
$web.FooterEnabled = $true 
$web.Update() 
Invoke-PnPQuery 

After run the script above, nothing happened. No footer at all. Is there another way I can turn the footer on?

Thanks! I appreciate it.
-Wagner

**Comment by mcmynn83** [comment] 2019-05-16 18:01
We will fix this issue so it no longer happens.  That being said, to workaround the issue until such time you can run the following in tenant admin powershell:

Run "Set-SPOTenant -ShowEveryoneClaim $true"
Go to the the appcatalog components manifest list (appcatalog/lists/componentmanifests)
Click list permissions
Add Everyone to the viewers group
Run "Set-SPOTenant -ShowEveryoneClaim $false" from the tenant admin console

The issue is being tracked via #2099 so I am closing this.

**Comment by mcmynn83** [comment] 2019-05-16 18:02
Closed the wrong bug, sorry.

**Comment by patmill** [comment] 2019-05-16 22:01
What does your code look like?  There's not a lot to go on here.

**Comment by coxwagner** [comment] 2019-05-17 00:16
For this purpose, I’m not using any code. Only the PowerShell script above. I thought the footer was going to show up by default on communication sites as Microsoft reported, but since it did not show up on a new communication site, I thought I could use the PowerShell Script above to turn on the footer. But no luck. Footer does not show up eider way.

**Comment by ramyaitech** [comment] 2019-06-03 22:53
same in my case.. any help will be appreciated..

**Comment by intelogymartin** [comment] 2019-06-04 12:14
Same here. I'm seeing blogs state this hasn't been fully rolled out yet. Is that true?

**Closed** 2020-01-22 21:32 UTC
Labels: area:other, listmaintenance-oldissues-untracked
