### ISSUE TITLE
Cannot populate the list with some initial data. You do this by adding the following Data element markup as a child element of the ListInstance element

### ISSUE THREAD

**Issue by duncanspeidel** [SharePoint/sp-dev-docs#4474] opened 2019-08-14 18:27 UTC
When I add the following to my ListInstance element it fails.
&lt;Data&gt;
  &lt;Rows&gt;
    &lt;Row&gt;
      &lt;Field Name="Title"&gt;Tom Higginbotham&lt;/Field&gt;
    &lt;/Row&gt;
    &lt;Row&gt;
      &lt;Field Name="Title"&gt;Satomi Hayakawa&lt;/Field&gt;
    &lt;/Row&gt;
    &lt;Row&gt;
      &lt;Field Name="Title"&gt;Cassi Hicks&lt;/Field&gt;
    &lt;/Row&gt;
    &lt;Row&gt;
      &lt;Field Name="Title"&gt;Lertchai Treetawatchaiwong&lt;/Field&gt;
    &lt;/Row&gt;
  &lt;/Rows&gt;
&lt;/Data&gt;
It fails with:
Severity	Code	Description	Project	File	Line	Suppression State
Error		Error occurred in deployment step 'Install SharePoint Add-in': Feature definition with Id 3d9f595f-0f21-4a70-a5b8-214fcf87ad8e failed validation, file 'TQM_TQM New Employee Orientation\NewEmployeeOrientation\Elements.xml', line 16, character 4: The element 'Elements' in namespace 'http://schemas.microsoft.com/sharepoint/' has invalid child element 'Data' in namespace 'http://schemas.microsoft.com/sharepoint/'. List of possible elements expected: 'ContentType, ContentTypeBinding, Field, CustomAction, Module, ListInstance, ListTemplate, Receivers, Workflow, WebTemplate, WorkflowAssociation, PropertyBag, ClientWebPart, BdcModel' in namespace 'http://schemas.microsoft.com/sharepoint/'.	TQM		0	

What am I missing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7795f659-9cc4-310b-1ea6-9842a6a2930a
* Version Independent ID: cfc98572-f913-6f48-cfe4-1b9dd526d7fc
* Content: [Get started creating SharePoint-hosted SharePoint Add-ins](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/get-started-creating-sharepoint-hosted-sharepoint-add-ins#feedback)
* Content Source: [docs/sp-add-ins/get-started-creating-sharepoint-hosted-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/get-started-creating-sharepoint-hosted-sharepoint-add-ins.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by duncanspeidel** [comment] 2019-08-14 18:28
Running studio 2019.

**Comment by bcameron1231** [comment] 2019-08-14 20:05
Can you share your full ListInstance Elements.xml

**Comment by duncanspeidel** [comment] 2019-08-15 14:43
I opened Elements.xml in 'TQM_TQM New Employee Orientation\NewEmployeeOrientation\NewEmployeeSeattle\Elements.xml' (see attachment named shot1) and added the <data> fields and it failed with the same error.  I also tried 
![Shot1](https://user-images.githubusercontent.com/16256174/63098936-0b4f3d80-bf42-11e9-81af-5ae1000ff6a7.png).  I also tried editing NewEmployeeOrientation\Elements.xml (see attachment named shot2).  
![shot2](https://user-images.githubusercontent.com/16256174/63099121-6da83e00-bf42-11e9-905f-0e3ed9796d93.png).

Screenshot called choices shows what I see when  enter a '<'.
![Choices](https://user-images.githubusercontent.com/16256174/63099548-469e3c00-bf43-11e9-9ced-c9879cd29096.png).

The Elements.xml that is sub to NewEmployeeInSeattle contians:
<?xml version="1.0" encoding="utf-8"?>
<Elements xmlns="http://schemas.microsoft.com/sharepoint/">
  <ListInstance Title="New Employees in Seattle" OnQuickLaunch="TRUE" TemplateType="100" Url="Lists/NewEmployeesInSeattle" Description="The new employees in Seattle"></ListInstance>

</Elements>

The Elements.xml that is for NewEmployeeOrientation contains:
<?xml version="1.0" encoding="utf-8"?>
<Elements xmlns="http://schemas.microsoft.com/sharepoint/">
    
    
    <ListTemplate
        Name="NewEmployeeOrientation"
        Type="100"
        BaseType="0"
        OnQuickLaunch="TRUE"
        SecurityBits="11"
        Sequence="410"
        DisplayName="NewEmployeeOrientation"
        Description="My List Definition"
        Image="/_layouts/15/images/itgen.png"/>

</Elements>

Both have the same auto-complete options.

**Comment by bcameron1231** [comment] 2019-08-15 16:45
The Elemements.xml for your NewEmployeeInSeattle didn't show up. Can you re-add it please?

**Comment by duncanspeidel** [comment] 2019-08-15 16:57
<?xml version="1.0" encoding="utf-8"?>
<Elements xmlns="http://schemas.microsoft.com/sharepoint/">
  <ListInstance Title="New Employees in Seattle" OnQuickLaunch="TRUE" TemplateType="100" Url="Lists/NewEmployeesInSeattle" Description="The new employees in Seattle"></ListInstance>

</Elements>

**Comment by bcameron1231** [comment] 2019-08-15 16:58
Please take a picture or wrap your XML in Code Tags, or else it wont show up. Thanks!

**Comment by duncanspeidel** [comment] 2019-08-15 17:45
```
<?xml version="1.0" encoding="utf-8"?>
<Elements xmlns="http://schemas.microsoft.com/sharepoint/">
  <ListInstance Title="New Employees in Seattle" OnQuickLaunch="TRUE" TemplateType="100" Url="Lists/NewEmployeesInSeattle" Description="The new employees in Seattle"></ListInstance>

</Elements>
```

**Comment by bcameron1231** [comment] 2019-08-15 17:46
I would like to see your Elements.xml with the Data (of which you say isn't working)

**Comment by duncanspeidel** [comment] 2019-08-15 17:50
```
<?xml version="1.0" encoding="utf-8"?>
<Elements xmlns="http://schemas.microsoft.com/sharepoint/">
  <ListInstance Title="New Employees in Seattle" OnQuickLaunch="TRUE" TemplateType="100" Url="Lists/NewEmployeesInSeattle" Description="The new employees in Seattle"></ListInstance>
  <Data>
    <Rows>
      <Row>
        <Field Name="Title">Tom Higginbotham</Field>
      </Row>
      <Row>
        <Field Name="Title">Satomi Hayakawa</Field>
      </Row>
      <Row>
        <Field Name="Title">Cassi Hicks</Field>
      </Row>
      <Row>
        <Field Name="Title">Lertchai Treetawatchaiwong</Field>
      </Row>
    </Rows>
  </Data>
  
</Elements>
![error](https://user-images.githubusercontent.com/16256174/63114761-9987eb80-bf63-11e9-979c-70befb6d68f5.png)

```

**Comment by bcameron1231** [comment] 2019-08-15 17:52
Great Thank you. So the problem is, you have not followed the Tutorial directions correctly. 

> 24. In this file, populate the list with some initial data. You do this by adding the following Data element markup as a child element of the ListInstance element.

Your data needs to be a child element of the ListInstance Element, not a sibling.

```
<?xml version="1.0" encoding="utf-8"?>
<Elements xmlns="http://schemas.microsoft.com/sharepoint/">
  <ListInstance Title="New Employees in Seattle" OnQuickLaunch="TRUE" TemplateType="100" Url="Lists/NewEmployeesInSeattle" Description="The new employees in Seattle">
  <Data>
    <Rows>
      <Row>
        <Field Name="Title">Tom Higginbotham</Field>
      </Row>
      <Row>
        <Field Name="Title">Satomi Hayakawa</Field>
      </Row>
      <Row>
        <Field Name="Title">Cassi Hicks</Field>
      </Row>
      <Row>
        <Field Name="Title">Lertchai Treetawatchaiwong</Field>
      </Row>
    </Rows>
  </Data>

</ListInstance>
</Elements>

```

**Comment by bcameron1231** [comment] 2019-08-16 13:09
@duncanspeidel Are we able to close this ticket?

**Comment by duncanspeidel** [comment] 2019-08-16 13:19
Thank you for your help.  I had the </ListInstance> in the wrong place.  Everything works now.

**Comment by duncanspeidel** [comment] 2019-08-16 13:19
I had the 
`</ListInstance>` in the wrong place.  You can close the ticket.

**Comment by bcameron1231** [comment] 2019-08-16 13:20
@andrewconnell This ticket can be closed

**Comment by andrewconnell** [comment] 2019-08-16 13:29
Thanks @bcameron1231 In the future, you can use #please-close when you tag me.

**Closed by andrewconnell** 2019-08-16 13:29 UTC
Labels: Needs: Attention :wave:, area:docs-comment, area:other, type:question
