### ISSUE TITLE
Sp dialog component can't open twice

### ISSUE THREAD

**Issue by sadrultoaha** [SharePoint/sp-dev-docs#8744] opened 2023-02-02 08:12 UTC
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version - Chrome v109.0.5414.120 
- SPFx version - v1.11.0
- Node.js version - v10.18.1
- Npm: 6.13.4
- @microsoft/generator-sharepoint: 1.11.0

### Describe the bug / error

I get blank modal while trying to open second time the list view option. First time it works perfectly, but as soon as close it once then can't open it again until refreshing or loading the page.

* CommandSet Execution method
```
 @override
  public onExecute(event: IListViewCommandSetExecuteEventParameters): void {
    switch (event.itemId) {
      case 'COMMAND_1':
        let doc = new MainDialog();
        doc.show()
        break;
      
      default:
        throw new Error('Unknown command');
    }
```

* MainDialog Component:
```
import { BaseDialog, IDialogConfiguration } from "@microsoft/sp-dialog";
import * as React from "react";
import * as ReactDOM from "react-dom";
import App from "./App";

export default class MainDialog extends BaseDialog {

  public render(): void {
    let app = <App close={this.close} />;
     
    let interval = setInterval(() => {
      if (this.domElement) {
        ReactDOM.render(app, this.domElement);
        clearInterval(interval);
      }
    });
  }

  public getConfig(): IDialogConfiguration {
    return {
      isBlocking: true,
    };
  }

  protected onAfterClose(): void {
    super.onAfterClose();

    // Clean up the element for the next dialog
    ReactDOM.unmountComponentAtNode(this.domElement);
  }
}
```
* App component 
```
import * as React from "react";
import { Fabric } from 'office-ui-fabric-react/lib/Fabric'
import {
  DialogContent,
  MessageBar,
  MessageBarType,
  Dialog
} from "office-ui-fabric-react";

interface Props {
  close: () => Promise<any>;
}

const App = ({ close }: Props): React.ReactElement => {
  return (

    <DialogContent
      title={"test"}
      onDismiss={close}
    >
      <p>Hello World!</p>
    </DialogContent>

  );
};

export default App;

```
 SS - 
 
![image](https://user-images.githubusercontent.com/16709991/216267075-b594fa7b-5878-4c44-aa9d-6ce96cb6deb3.png)

### Steps to reproduce

1. Open the ListView Command item 'COMMAND_1'
2. Close it.
3. Then try to open it again. 

### Expected behavior

ListView Command item should be executed properly, even if try to open after closing it.

**Comment by anditee** [comment] 2023-02-02 15:02
I've got the same problem even though i followed the instructions on: https://learn.microsoft.com/en-us/sharepoint/dev/spfx/extensions/guidance/using-custom-dialogs-with-spfx

**Comment by AJIXuMuK** [comment] 2023-02-02 16:27
Seems like a dupe of #8736.

Could you please explicitly specify the version of React and ReactDOM in your dependencies?

**Comment by AJIXuMuK** [comment] 2023-02-02 16:46
@sadrultoaha - do you have them listed as `dependencies` in the `package.json` or they are installed as sub dependencies from other dependecies?

**Comment by sadrultoaha** [comment] 2023-02-02 16:51
@AJIXuMuK - They are installed as sub dependencies. So React and React-dom not listed in in the `package.json` file.

**Comment by sadrultoaha** [comment] 2023-02-02 16:58
Everything was alright till last Tuesday. Suddenly this issue appeared into all the running extension app in production.

**Comment by JurajSlavik** [comment] 2023-02-02 17:15
Hello everyone, I can confirm the same behavior issue here too. First observed on the 31-th of January 2023 in the PROD environment. On 30-th of January 2023, the dialogues used to work as expected.

Used dependencies versions in this case (taken from package.json):
  "@microsoft/sp-core-library": "1.15.2",
  "react": "16.13.1",
  "react-dom": "16.13.1"

I tried to debug it, and the render function on the dialog is called correctly even on the second time, but none output is rendered, so that the placeholder div remains empty - there is nothing from the output of the render function:

&lt;div data-automation-id="sp-dialog-content-div"&gt;&lt;/div&gt;

I suspect some relation with this issue: https://github.com/SharePoint/sp-dev-docs/issues/8736.

**Comment by JurajSlavik** [comment] 2023-02-02 17:46
Adding some console errors, but AFAIK, they are unrelated to the issue and were there even if the dialogues worked:

![CustomDialog issue - 2023-02-02 173122](https://user-images.githubusercontent.com/124240729/216400982-86a1e175-f84f-41ac-8472-1062824ea63e.png)

**Comment by omarelanis** [comment] 2023-02-03 08:45
I have this same exact problem, there are no errors shown in the console and debugging the application through to the re-render of the dialog shows no indication of where the issue is. This is happening on a list view command set which has been in production for over a year now without any issues until a few days ago.

I can replicate the issue on my dev environment too, nothing has changed on either environments so unsure what is causing it.

Trying with and without disposing of the dom element has had no effect either;

  protected onAfterClose(): void {
    super.onAfterClose();

    // Clean up the element for the next dialog
    ReactDOM.unmountComponentAtNode(this.domElement);
  }

**Comment by PaoloPia** [comment] 2023-02-03 13:50
Hi,
Since yesterday, we're experiencing exactly the same issue with some of our customers (all of them EU based, so far). We are using various versions of SPFx (like 1.15.0 + React 16.13.1, 1.9.1 + React 16.8.5, etc.). All of the dialogs were working as expected until yesterday afternoon.

Thanks.

**Comment by anditee** [comment] 2023-02-03 15:32
Hi,

we implemented a little quickfix for those in need it may be a bit quick and dirty but it meets our needs. If you are looking for a quick fix for it to be working again and till we get some feedback.

To fix it we just added a reload after the close and the unmount of the component in the onAfterClose method.

`protected onAfterClose(): void {
    super.onAfterClose();

    // Clean up the element for the next dialog
    ReactDOM.unmountComponentAtNode(this.domElement);
    window.location.reload();
  }`

This will reload the page and enables the rendering of the dialog again.

Have a good day.

**Comment by sadrultoaha** [comment] 2023-02-03 15:35
@anditee I did the same 😅

**Comment by JurajSlavik** [comment] 2023-02-03 17:22
This ‚workaround’ is not feasible for us, we have different scenarios used – after first dialog is confirmed, another one is shown, demanding required data.

Besides that, I don`s see any reason to make modification in all existing projects which were running successfully without any problems, just because some error occurred in the cloud. I expect that the change in O365 which caused the malfunction will be detected and reverted (or fixed) and all dialogs will start to work again, without the need to involve all teams to make changes in all custom solutions which are using dialogs.

**Comment by PaoloPia** [comment] 2023-02-06 09:05
Just a quick note. Upgrading to SPFx 1.16.1 dialogs work as expected.

**Comment by JurajSlavik** [comment] 2023-02-06 09:25
Just finished the same workaroud few minutes ago (upgrade to SPFx 1.16.1) and I confirm that the the dialogs works after update to newer version.

**Comment by pappukumarsinghext** [comment] 2023-02-06 12:10
Hello, I too have same issue. Need a proper stable fix

**Comment by svenkonings** [comment] 2023-02-06 14:01
Upgrading to SPFx v1.16.1 solves the issue of opening the dialog multiple times from the command menu, but the issue persists if you open a dialog from another dialog, e.g.:
```
this.close().then(() => newDialog.show());
```
After this the new dialog is just a blank rectangle again

**Comment by PaoloPia** [comment] 2023-02-06 15:14
Actually, if you need to open a dialog from another dialog, you should rely on the [secondaryDialogProvider](https://learn.microsoft.com/en-us/javascript/api/sp-dialog/basedialog?view=sp-typescript-latest#@microsoft-sp-dialog-basedialog-secondarydialogprovider-member).

**Comment by MortenGuldbaek** [comment] 2023-02-07 07:55
We are also experiencing this for all implementations of sp-dialog.

We are running:

- SharePoint Framework v. 1.12.1
- React 16.9.0

**Comment by araLT** [comment] 2023-02-08 09:57
We are also seeing same issue, but I can find the following working workaround: it is needed to override onBeforeOpen method in your dialog class inherited from BaseDialog class and resolve the promise asynchronously via window.setTimeout (even 0ms delay working), i.e. the overridden method must look like this (which also can contain your needed custom operations):

```
@override
protected onBeforeOpen(): Promise<void> {
    return new Promise((resolve, reject) => {
        window.setTimeout(() => resolve(), 0);  
    });
}
````

**Comment by tandrasi** [comment] 2023-02-08 14:49
Same issue here. **ONLY** works (without workarounds) on our latest project utilising SPFx 1.16.1, which uses React 17 by default.

Can confirm applications in production on various client tenancies ranging from SPFx 1.9.1 - 1.15.2 are all experiencing the same issue.

Current app I'm debugging using SPFx 1.15.2 has React and DOM at version 16.13.1, and even with sp-dialog@1.16.1 does not fix the issue. Only thing that helps is the fix above posed by @araLT (THANK YOU!)

**Comment by JoelBool** [comment] 2023-02-08 14:58
We are also seeing the same issue. Experienced in multiple environments with apps using spfx 1.14.0

**Comment by ShivGuitHub** [comment] 2023-02-09 06:36
Such issues must be taken on the highest priority. _I can see the thread problem has also been reported on the production environment._

Dear **Microsoft**, It is critical. Align some resources to look into this as it can impact multiple clients.

**Comment by martinlingstuyl** [comment] 2023-02-09 09:35
Same here, I've upgrade one package to 1.16.1, after which it started working correctly again.

Another package did not work out of the box after upgrading. I removed the package-lock.json file and the node_modules folder, reinstalled everything. After that it started working correctly again.

**Comment by omarelanis** [comment] 2023-02-09 09:35
I've upgraded my affected solutions to SPFx 1.16.1 using React 17 and that has fixed the issue - note you must use React 17

**Comment by anditee** [comment] 2023-02-09 10:18
Anyone else facing a  "Manifest not found" error on gulp serve? Occured after upgrade. Even setting up a new project with 1.16.1 this error occures. 

It only occures if we use a Dialog the base custom listview context menu shows the new options without the dialog. Followed the instructions on [how to set up a custom](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/guidance/using-custom-dialogs-with-spfx.md) dialog with spfx

**Comment by PaoloPia** [comment] 2023-02-10 12:03
> I've upgraded my affected solutions to SPFx 1.16.1 using React 17 and that has fixed the issue - note you must use React 17

I confirm the requirement of both SPFx 1.16.1 **and** React 17 (here we're using 17.0.1).

However, the dialog issue is still there if you use a _secondaryDialogProvider_ to open a secondary dialog. In fact, when you do that, the secondary dialog opens correctly, but when you close it the parent one becomes completely white. This was already an issue #1771, which was closed a while ago. Most likely this is a regression. Thanks.

**Comment by AJIXuMuK** [comment] 2023-03-01 15:36
the fix for the issue should be rolled out to 100% by now.

**Closed by AJIXuMuK** 2023-03-01 15:36 UTC
Labels: type:bug-suspected, area:spfx, Needs: Attention :wave:
