### ISSUE TITLE
A warning is causing the production build of a extension to fail on a build agent

### ISSUE THREAD

**Issue by RazorSPoint** [SharePoint/sp-dev-docs#1058] opened 2017-11-18 22:59 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
When using the shipping command
`gulp package-solution --ship`
and having the flag "skipFeatureDeployment" set to true, the returned warning should not cause a build agent on VSTS to fail

#### Observed Behavior
I have documented the behavior in detail with the code [on my blog](https://www.razorspoint.com/2017/11/18/espc17-discussions-in-between/) (headline: Why is a warning causing the build to fail?), but in general, the problem is that the flag "skipFeatureDeployment" is set equal to the "--ship" flag in the module "@microsoft/sp-build-common" in the BuildRig.js in line 43. But when you want to ship the extension to production with the named flag, you are never able to have a successful production-build with the "skipFeatureDeployment" set to "true"

#### Steps to Reproduce
when packaging a solution with the "--ship" flag, having "skipFeatureDeployment" set to true and trying to build an extension on an build agent on VSTS.

**Comment by garlino** [comment] 2017-11-28 09:58
Ran into the same issue, build is failing. Needing it to be set to true so that it can be available at all sites.
Warnings shouldnt cause the build to fail :)

**Comment by nickpape-msft** [comment] 2018-02-13 21:05
Duplicate of https://github.com/SharePoint/sp-dev-docs/issues/1058

Please follow that issue for now.

**Closed by nickpape-msft** 2018-02-13 21:05 UTC
Labels: area:tooling, status:to-be-reviewed, type:bug, type:enhancement
