### ISSUE TITLE
SPFX dev environment installation instructions for Yeoman may need to specify version 4.x

### ISSUE THREAD

**Issue by joshmcrty** [SharePoint/sp-dev-docs#9331] opened 2023-11-15 17:04 UTC
As of today I created a fresh dev environment for SPFx and followed the commands to install gulp-cli, yeoman, etc.. This installed`yo` version 5, which was [just released](https://www.npmjs.com/package/yo?activeTab=versions). When I tried to run the sharepoint generator I received an error message:

```
Error

Current environment doesn't provides some necessary feature this generator needs
```

I uninstalled `yo` and then installed the latest v4 using `npm install -g yo@"4.x"`. After this I was able to run the generator successfully.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5bee09a8-022e-1b5a-4aab-d6e7c6216808
* Version Independent ID: 49edce1e-f2be-e989-917f-c6b389363e2f
* Content: [Set up your SharePoint Framework development environment](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment)
* Content Source: [docs/spfx/set-up-your-development-environment.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/set-up-your-development-environment.md)
* Service: **sharepoint**
* Sub-service: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by VesaJuvonen** [comment] 2023-11-16 10:57
Hi @joshmcrty, 
thanks for flagging this. This is a duplicate of #9328. We've updated the docs to specifically reference the latest supported Yeoman generator version (4.3.1) and we are internally working on solving the issue with the v5. This is most likely related on some version checking which should be a quick fix - but will require new packages to get released.

I'll close this one and let's continue discussion in the 9328 issue. Sorry for the inconvenience and challenges this caused. Version dependencies are always tricky and as we did not reference specific 4.x version in the default scripts/documentation - this came as an unexpected issue.

**Closed by VesaJuvonen** 2023-11-16 10:57 UTC
Labels: status:duplicate, area:spfx
