### ISSUE TITLE
SPComponentLoader error in SPFx application extension - http://requirejs.org/docs/errors.html#nodefine

### ISSUE THREAD

**Issue by agamadrid** [SharePoint/sp-dev-docs#2505] opened 2018-09-10 15:23 UTC
#### Category
- [ ] Question
- [ ] Typo
- [X ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I'm using SPComponentLoader to load an external js file for a footer. It works fine in the home page and in the site pages but it does not work when you are in site contents page or in any library page.

#### Observed Behavior

When debugging I see the below error

Error: No define call for https://xxxx/sites/xxx/SiteAssets/MyJS.js
http://requirejs.org/docs/errors.html#nodefine
    at makeError (require-951f856e.js:1)
    at Object.completeLoad (require-951f856e.js:1)
    at HTMLScriptElement.onScriptLoad (require-951f856e.js:1)

I've seen this issue was something similar [1180](https://github.com/SharePoint/sp-dev-docs/issues/1180) but couldn't find the solution.

thanks & kind Regards

**Comment by VesaJuvonen** [comment] 2018-10-04 18:03
Any chance you can provide us simple repro application so that we can investigate the issue to ensure that we have a repro for the issue. Thx.

**Comment by VesaJuvonen** [comment] 2018-10-09 16:45
Just to follow up on the question of getting a solution which has the issue. We really cannot solve this if we cannot reproduce the issue and therefore we'll need to close this issue soon if reproducible sample is not available.

**Comment by VesaJuvonen** [comment] 2018-10-25 17:53
Closing due to no response.

**Closed by VesaJuvonen** 2018-10-25 17:53 UTC
Labels: area:framework, status:waiting-for-clarification, type:bug
