### ISSUE TITLE
Webpart not coming in specified group.

### ISSUE THREAD

**Issue by craghavendra21** [SharePoint/sp-dev-docs#1048] opened 2017-11-14 06:47 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
If we specify the Unique group id and different group name webpart should appear in the specified group name.

#### Observed Behavior
Even if you give unique group name and group id, still webpart is appearing in the "Other" group.

#### Steps to Reproduce
Create a tenant scoped SPFx webpart,
Deploy to Environment,
Webpart will be available in "Others" Group.
Edit Webpart manifest file,
Change the Group ID and Group Name (unique group id, name something like "SPFx Webparts")
Bundle and Deploy again
Now Webpart should appear under group SPFx Webparts, but still, it's coming under "Other" group.

**Comment by manishgarg1** [comment] 2017-11-21 00:59
Hi @craghavendra21 , thanx for reporting the issue. Can you please confirm if this is still happening or has it been resolved ?

**Comment by craghavendra21** [comment] 2017-11-21 05:33
Hi, still this issue is not resolved. Please help me with this issue ASAP.

**Comment by rgylesbedford** [comment] 2017-11-21 15:43
We are seeing this in our tenant as well.

**Comment by craghavendra21** [comment] 2017-11-27 10:36
Anyone looking into this issue? Please fix this ASAP. My client asking for this.

**Comment by manishgarg1** [comment] 2017-11-30 16:18
Hi, we apologize for the delay. There was a mistake that caused this fix to be delayed. Can folks confirm if this is fixed now?

**Comment by manishgarg1** [comment] 2017-11-30 16:41
This is a duplicate of issue 1024 and folks have confirmed it is now resolved. Hence resolving this issue also.

**Closed by manishgarg1** 2017-11-30 16:41 UTC
