### ISSUE TITLE
Deploying through Site Collection App Catalog requires access to Tenant App Catalog

### ISSUE THREAD

**Issue by bcameron1231** [SharePoint/sp-dev-docs#2882] opened 2018-11-05 19:35 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
When using a Site Collection App Catalog to add and deploy add-ins/apps to a Site Collection... Site Collection admins should not be required to have access to the tenant level app catalog site (sites/appcatalog) in order to deploy add-ins in their site collection.

#### Observed Behavior
_Due to a complex tenant and previous limitations of the App Catalog (pre site collection app catalog), customer chose to modify permissions that were granted on the tenant level app catalog (removed access for some users)._ 

When the new Site Collection app catalog went to GA, customer made a switch to add/deploy apps through a Site Collection app catalog, instead of the tenant catalog. Site Collection Admins were able to deploy add-ins in the "Apps for SharePoint" list. However, when trying to add an add-in through "add an app", no apps were visible to be added even though they were just deployed.

Upon granting the SCA access back (read permissions) to the tenant app catalog (/sites/appcatalog) the SCA was now able to see a list of apps available from the organization from their site collection.

#### Steps to Reproduce

- Remove access to the Tenant App Catalog Apps for SharePoint List for a Site Collection Admin Account.
- Create a new site collection app catalog in a site collection
- Add new add-in (SPFx or Add-in) to the "Apps for SharePoint" list in the Site Collection.
- Use the same SCA that had permissions removed from Tenant App Catalog and try to add the add-in through "Add an app" and it will be empty.

Add permissions back to sites/appcatalog list, and the apps will re-appear.

**Comment by jspiew** [comment] 2018-11-05 20:12
This is similar to a scenario I've experienced with external users. I have a site collection that has several spfx webparts added via Site Collection app catalogue. External users invited to that site collection (it's a single site within site collection scenario) could not see the webparts. The only thing that helped was giving them explicit read rights to tenant app catalogue.

**Comment by strausykumc** [comment] 2018-11-05 22:52
Specifically this occurred when I broke permission inheritance on the Apps for SharePoint library within the tenant app catalog so that only owners could access it. This was done to prevent an organization we share the tenant with from deploying our custom add-ins or adding new ones to the tenant without a proper governance plan. The site collection app catalog greatly improved our governance, but was not aware there is a parent/child relationship with tenant and site collection app catalogs.

**Comment by mcmynn83** [comment] 2019-01-08 23:30
@strausykumc - This indeed was a bug.  We have now fixed the issue and it should roll out around January 27th.  That being said, in the meantime to work around the issue we by default give everybody read access to the tenant app catalog.  With read access you don't run into this issue and you cannot add new add-ins.  However, it does not prevent the case you were talking about where people can use your custom add-ins.  I will close this and if the issue is still occurring in February please let me know (sorry for the slow roll out, it was just bad timing for making the fix).

**Closed by mcmynn83** 2019-01-08 23:30 UTC
Labels: area:other, internal:unclear
