### ISSUE TITLE
Properties of ClientObject not initialized (PropertyOrFieldNotInitializedException) even after a successful retry during throttling

### ISSUE THREAD

**Issue by justviswa** [SharePoint/sp-dev-docs#5297] opened 2020-02-06 14:35 UTC
## Category

- [x] Bug

## Describe the bug

We're making multiple **threaded** CSOM requests (Maximum Concurrent Requests = 12). And we are facing throttling errors (429 or 503) during which we retry as suggested in the docs (given below). However, sometimes, **even if the retry is successful, properties of the client object (for example, ListItem) are not initialized**. Because of this, **PropertyOrFieldNotInitializedException** is thrown.

**Important Note:** This occurs rarely & only after long-running continuous (more than 20 hours) CSOM requests.

## Retry Handling (Code)
```
while (true)
{
    try
    {
        if (!retry)
        {
            clientContext.ExecuteQuery();
            return;
        }
        else
        {
            if (wrapper != null && wrapper.Value != null)
            {
                clientContext.RetryQuery(wrapper.Value);
            }
            else
            {
                clientContext.ExecuteQuery();
            }
            return;
        }
    }
    catch (Exception ex)
    {
        if(canRetry(out wrapper))
        {
            Sleep(...);
        }
        else
        {
           throw new Exception(...);
        }
        retry = true;
    }
}
```
> editted by @andrewconnell for added readability

## Developer environment
- OS: Windows 10
- Framework: .NET 4.5, Microsoft.SharePointOnline.CSOM 16.1.19724.12000

### Additional context

We're following all the standards such as: using User-Agent header, ConnectionGroupName, DisableReturnValueCache (true).

**Comment by justviswa** [comment] 2020-02-13 05:37
Team, Guess this a related or similar issue: 
[https://github.com/SharePoint/sp-dev-docs/issues/1412](https://github.com/SharePoint/sp-dev-docs/issues/1412)

**Comment by nathan-swannet** [comment] 2020-02-13 10:33
We're also facing this issue.
Most of the time the retry succeeds but in very rare cases the succesful retry is followed by a NotInitialized exception when we try to use the property/collection that has just been requested...

**Comment by andrewconnell** [comment] 2020-02-13 11:53
@justviswa appears to be correct, this looks like a dupe of #1412 which is a tracked bug...

**Closed** 2020-02-13 11:53 UTC
Labels: area:csom/rest, status:duplicate
