### ISSUE TITLE
Tab doesn't show up in mobile devices

### ISSUE THREAD

**Issue by bhishma** [SharePoint/sp-dev-docs#3833] opened 2019-04-24 09:56 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I expected the tab to show up in the mobile devices as it does in the web app or Teams client in PC.
#### Observed Behavior

SharePoint framework Tab does not show up at all in the under More in a channel in a mobile device

#### Steps to Reproduce

Follow the guide and build a spfx webpart: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab
Add webpart to Teams
Go to the channel in mobile device> Click on More.

**Comment by patmill** [comment] 2019-04-24 17:34
My understanding is that the teams mobile experience doesn't fully support tabs at the moment.  Let me see if I can find someone to confirm.

**Comment by lucabandMSFT** [comment] 2019-05-09 20:03
@bhishma , thanks for reporting this issue. as Pat correctly said, this capability is not yet supported in the Teams Mobile client. we hope we can have any Tab enabled in Teams Mobile soon.

I'm now closing this issue as, for now, this is a by design behavior

**Closed by lucabandMSFT** 2019-05-09 20:03 UTC
Labels: Needs: Triage :mag:
