### ISSUE TITLE
SPFx FieldCustomizer fails to render after switching view with 'Manifest not found' error

### ISSUE THREAD

**Issue by zplume** [SharePoint/sp-dev-docs#2316] opened 2018-08-06 16:28 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When viewing a list in SharePoint Online where a field has an associated field customizer, the field customizer renders successfully in both of the following scenarios:
* A user navigates directly to the list view that includes the field (either where this is the default view or the user navigated directly to a view via the browser address bar, e.g. Lists/ListName/ViewName.aspx)
* A user navigates first to a list view that does not include the field and then switches to a view that *does* include the field

#### Observed Behavior

When viewing a list where a field has an associated field customizer, the field customizer renders successfully when navigating directly to a list view that includes the field.

When navigating first to a view that does not include the field and then switching to a view that *does* include the field via the view selection drop-down, the field customizer fails to load and the following error is shown in the browser developer console:

`Fail to load customizer for column: Booking, componentId: b30e0f53-8dc2-41ae-ba00-281a253d57a5, error: ***Manifest not found for componentId "b30e0f53-8dc2-41ae-ba00-281a253d57a5".`

#### Steps to Reproduce

* Create production build of a SPFx (version 1.5.1) field customizer with `skipFeatureDeployment: true`
* Deploy field customizer to tenant app catalog at tenant scope
* Associate field customizer with a list content type field by updating the `ClientSideComponentId` and `ClientSideComponentProperties` properties of the field with PnP PowerShell/CSOM
* Navigate directly to a list view that not include the field with the associated field customizer using the browser address bar (e.g. /Lists/ListName/ViewName.aspx) - not using the list view selection drop-down
* Now change to a view that does contain the field with the associated field customizer using the list view selection drop-down
* Note that the URL path stays the same (e.g. /Lists/ListName/ViewName.aspx), but a query parameter `viewId` is added, with the GUID of the selected view
* See error message detailed above in browser developer tools

Bug observed in the following browsers on Windows 10 (no other browsers tested):
* Edge 42.17134.1.0
* Chrome 68.0.3440.84 (Official Build) (64-bit)

Thanks!

**Comment by jekeblad** [comment] 2019-08-13 13:26
Hi, Has this issue been addressed somewhere else or is it still unresolved?

Best Regards
//Joakim

**Comment by jekeblad** [comment] 2019-08-16 16:22
Seems like this is a duplicate of #2244 Maybe this should be closed?

**Closed** 2020-01-22 21:23 UTC
Labels: listmaintenance-oldissues-nolabels
