### ISSUE TITLE
Cannot add SPFx Webpart to German SiteCollection in Sharepoint Online

### ISSUE THREAD

**Issue by LeopoldLerch** [SharePoint/sp-dev-docs#596] opened 2017-05-23 06:58 UTC
As stated, I am not able to add my SPFx Webpart to a SiteCollection in Sharepoint Online, which was created in German. 
As the developer tools tell me, there is a Syntax error in the automatically embedded Javascript. The error Message in German is enclosed in double quotes, altough in the text itself double quotes appear again, therefore causing a parameter error.

`console.error("Der Webpart-Wrapper auf dieser Seite kann nicht geladen werden. Verwenden Sie die Schaltfläche "Zurück" im Browser, um es noch mal zu versuchen. Wenn das Problem weiterhin besteht, wenden Sie sich an den Administrator der Website.");`

(You see the double quotes inside the double quoted string? Thats the js-code embedded when using an SPFx webpart)
 
I used the default SPFx webpart generated with the react-framework, no adjustments. It works well on English SiteCollections as well as in the workbench.
 
Our Sites are all in German so we cannot switch to English Sites, but we want to build our new Project on the new Framework Infrastructure. Could you double-check this issue and if possible tell me, when  or how this could be solved? (I guess there is just the need to update som ressource-files)
 
thanx and Regards
Leo

**Comment by VesaJuvonen** [comment] 2017-05-23 11:02
Thank you @LeopoldLerch for submitting this in here. This seems to be a bug in the platform, which certainly should be resolved asap. Seems to be a duplicate with #587.

**Comment by derCiamas** [comment] 2017-05-23 14:54
In case you are in a hurry, you can take just this code part:

`window.moduleLoaderPromise.then(function(application) {
	 application.loadWebPart(...);
});`

and add it to the SharePoint page as a script. Not the best and most flexible solution but it worked when we had to do a presentation for the customer;)

**Comment by cwdata** [comment] 2017-06-21 11:09
Seems the workaround with the code part doesn't work in Edge if there is more than one SPFx Webpart on the page. It works in IE and Firefox though. Will this bug be fixed in the foreseeable future or is there a workaround which works for multiple Webparts in Edge?

**Comment by srideshpande** [comment] 2017-06-27 19:59
I will take a look at it and update the thread with my findings.

**Comment by michel-weber** [comment] 2017-07-17 15:14
@srideshpande What is the current state here? Any updates?

**Comment by BigEaseGueldi** [comment] 2017-07-20 11:03
Any info on the timeline (it's a showstopper in more than one project ...)? Thanks!

**Comment by BigEaseGueldi** [comment] 2017-07-27 12:10
Just to explain why I'm checking back on a weekly basis:

It's not only that go-live dates come closer: 
- From my point of view there are not too many arguments for building "classic" Web Parts when you can use client-side Web Parts on classic pages.
- Enterprise customers tend to decide for a certain strategies at certain points in time.

(I did not make this up)
Me: "You should start building client-side Web Parts." -> Customer: "But you said they currently don't work on German classic pages." -> Me: "That's right, but they will." -> Customer: "How long have you been waiting for a fix?" -> Me: "Right now - um - 2 months." -> Customer: "We'll think about it - in 2018."

I really appreciate the SPFX team's work and progress! There's no need for an overnight fix - all I'm asking for is a realistic timeline.

Thanks again! Dirk

**Comment by jbgeesink** [comment] 2017-07-27 14:30
We're facing the same problem. We want to use SPFx Webparts on display forms of a list item so we can't use modern pages. Any updates would be great. Thanks!

**Comment by BigEaseGueldi** [comment] 2017-08-02 14:05
As mentioned in https://github.com/SharePoint/sp-dev-docs/issues/497, properties are not persisted on German pages. This is still the case when you use the workaround @derCiamas mentioned above.

-> You currently cannot have SPFx Web Part properties on German classic pages.

Anyone?

**Comment by srideshpande** [comment] 2017-08-14 19:25
@BigEaseGueldi - this issue is about `Cannot add SPFx Webpart to German SiteCollection in Sharepoint Online` and this should be fixed now. Properties not being persisted seems like a different issue. Can you please open a separate issue for this problem, if an issue is not already open against it?

I will close this issue as the reported problem is fixed. Feel free to re-open it if you think the issue is not fixed.

Thanks,
Srikanth

**Closed by srideshpande** 2017-08-14 19:25 UTC
Labels: area:framework, status:tracked, type:bug

**Comment by cwdata** [comment] 2017-08-15 07:39
I can confirm that this works now in different browsers (including Edge) on german classic pages.
Also the properties are now being persisted.
