### ISSUE TITLE
Can't initialize MSGraphClient

### ISSUE THREAD

**Issue by aslanovsergey** [SharePoint/sp-dev-docs#2028] opened 2018-06-13 14:05 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Observed Behavior
I can't initialize MSGraphClient in online workbench, I have also this solution installed on my site and when try to test on a real page I work with installed version, not the the one i want to test

```
Uncaught TypeError: sp_http_._AadTokenProviders.getConfigurable is not a function
    at MSGraphClient.js:12
    at e._processPendingCallbacks (sp-webpart-workbench-assembly_en-us_4b86d9f21969ea009ecdbcd8fff24f1d.js:283)
    at e.consume (sp-webpart-workbench-assembly_en-us_4b86d9f21969ea009ecdbcd8fff24f1d.js:283)
    at e.consume (sp-webpart-workbench-assembly_en-us_4b86d9f21969ea009ecdbcd8fff24f1d.js:283)
    at e.consume (sp-webpart-workbench-assembly_en-us_4b86d9f21969ea009ecdbcd8fff24f1d.js:283)
    at EmployeeSelector.componentDidMount (EmployeeSelector.tsx:85)
    at e.window.spModuleLoader.e.notifyAll (sp-webpart-workbench-assembly_en-us_4b86d9f21969ea009ecdbcd8fff24f1d.js:200)
    at r.close (sp-webpart-workbench-assembly_en-us_4b86d9f21969ea009ecdbcd8fff24f1d.js:214)
    at r.closeAll (sp-webpart-workbench-assembly_en-us_4b86d9f21969ea009ecdbcd8fff24f1d.js:200)
    at r.perform (sp-webpart-workbench-assembly_en-us_4b86d9f21969ea009ecdbcd8fff24f1d.js:200)
```

**Comment by andrewconnell** [comment] 2018-06-13 14:30
Known issue ATM... there's a regression in 1.5 that's breaking the Graph & AAD APIs... stay tuned...

**Comment by aslanovsergey** [comment] 2018-06-13 14:57
Thanks Andrew,

Workaround in my case can be this https://docs.microsoft.com/en-us/sharepoint/dev/spfx/debug-modern-pages

**Comment by VesaJuvonen** [comment] 2018-06-14 17:53
Duplicate of #1964, so closing this one.

**Closed by VesaJuvonen** 2018-06-14 17:53 UTC
Labels: area:framework, type:bug
