### ISSUE TITLE
Intermittent error "Fail to load customizer for column"

### ISSUE THREAD

**Issue by roldengarm** [SharePoint/sp-dev-docs#9008] opened 2023-06-12 19:59 UTC
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version: 114.0.1823.43 (64 bit) Edge
- SPFx version: 1.16.1
- Node.js version 16.20.0

### Describe the bug / error

I've created a field customizer to override the rendering of a text field. It works fine when deployed and running locally. 
The app package is deployed to the site catalog and besides the field customizer also contains a web part.

With Powershell I've set the ClientSideComponentId of the Title field to the ID of the field customizer. When I go to the site for the first time, the title field is empty, and the console shows this error:

`Fail to load customizer for column: Title, error: Manifest not found for componentId`

When I hard refresh once or twice, the field becomes visible most of the times, but not always. From that moment on it works, until I close the browser. 
It has been replicated consistently across multiple users.

I've also tried to create a new column instead of using the title field, but the same problem occurs.

Whenever the problem occurs, I noticed that in the dev console => sources => the bundle for the field customizer hasn't been loaded. When it works, I can see a bundle there containing the field customizer. 
So my guess is that somehow SharePoint doesn't load my app javascript for some reason.

### Steps to reproduce

1. Create field extension with yeoman
2. Create app package and deploy to site app catalog
3. With powershell, set the ClientSideComponentId of the title field
4. Notice that the title field is empty and a message is shown in the console that the field extension couldn't be found.

### Expected behavior

The field extension shows every time.

**Comment by anthonywhite** [comment] 2023-08-01 14:48
Also getting this behaviour with a field customizer built with `1.13.1` and using latest Chrome (115.0.5790.110). The F12 Console has an **info** message for `splistwebpack.js`:

`"Fail to load customizer for column: <fieldname>, componentId: 699096e5-97d5-4024-a72c-ef7d4bdde998, error: Manifest not found for componentId "699096e5-97d5-4024-a72c-ef7d4bdde998"`

**Comment by roldengarm** [comment] 2023-08-04 06:51
Hi @anthonywhite yep, I could also reproduce it with the default generated customizer. We also raised a ticket with MS who confirmed the issue, and they could replicate it. After internal escalation we have received the disappointing response from the product team that this is by design and won't be fixed any time soon...

**Comment by anthonywhite** [comment] 2023-08-04 08:17
@roldengarm I really hope I have misunderstood. You _seem_ to be saying that the product group (SharePoint product group?) is basically saying "yeah customizers don't work and we're not going to fix them" !

I don't understand how something not working can be "by design"

Please tell me I'm wrong...

**Comment by roldengarm** [comment] 2023-08-04 10:43
@anthonywhite no, you haven't misunderstood.

**Comment by anthonywhite** [comment] 2023-08-04 10:55
@VesaJuvonen any comment on the above?

**Comment by AJIXuMuK** [comment] 2023-08-04 19:27
@roldengarm - I believe there is a misunderstanding.
I don't know the details of the support ticket. 
But most probably the response was that it may happen due to caching when some Web Front Ends are not getting updated right away.
And on some tenants it might take a while while the cache is updated.
We have a fix rolling out to decrease the time for cache update. When it's propagated (I would give it a few weeks) all the cache should be up to date in 10 minutes.
Meaning if you upload an SPFx app in 10 minutes it MUST be available (same for new versions of the app).

If in a few weeks you're still experiencing the issue - please mention me in this issue. I will not be closing it.

**Comment by roldengarm** [comment] 2023-08-04 20:13
@AJIXuMuK the response from the SP team was indeed it would be caching. However, the problem also happens weeks after the last deployment, so it doesn't seem like a caching issue. 
We replied that to the product team, after which we got the response that it was by design.

**Comment by anthonywhite** [comment] 2023-08-04 20:26
@roldengarm @AJIXuMuK I can also confirm we see this issue with packages deployed days or weeks ago.

**Comment by AJIXuMuK** [comment] 2023-08-05 01:58
Let's wait while the change is propagated. 

If you see the issue in two weeks from now - let me know.

**Comment by Scottlis26** [comment] 2023-08-07 14:58
I understand this issue is with the field customizer, but could it be related to the Application extension's partial page issue discussed here, as well as a several other places: https://github.com/SharePoint/sp-dev-docs/issues/1971 "OnInit is called when the extension is loaded (onDispose when it is unloaded). If you have the same extension on multiple site collections / lists / etc. then the design is that onInit is not called when you do a partial navigate between them. This keeps them working fast." How do we assure stability/consistency if these are only fired some of the time -- especially since each library may need some special look or behavior, ,i.e. ribbon/menu controls, etc.? What can we do to provide a more consistent experience/display?

**Comment by anthonywhite** [comment] 2023-08-11 07:41
@roldengarm @Scottlis26 I have just discovered that the issue (at least for us) is that the field we have a customizer for was not in the ***default*** view of the list, just in other views. Adding it to the default view makes it load and work consistently in the other views.

@AJIXuMuK interested to know if this makes sense and is it a bug to fix?

**Comment by roldengarm** [comment] 2023-08-11 08:01
@anthonywhite I think I discovered that as well, and it seemed to help, but then the problem came back.
I'll give it another try though, thanks.

We got a response again on our support ticket that a fix is underway without an ETA.

**Comment by AJIXuMuK** [comment] 2023-08-11 14:22
@anthonywhite - you are referencing another issue #8571.
For the default/non default view - we are rolling out the fix. It should be on 100% prod next week.
However, the issue described here is different. In the scenario with non-default view the field customizer is just not loaded.
But here the manifest of the customizer is not found.

**Comment by joliq** [comment] 2023-08-14 11:18
We are also experiencing this issue with field customizers built with version `1.4.1` since a few weeks back.
It occurs in 2 of 3 tenants with the same package deployed.
It does not help to include the field in the default view. 
The following js error also pops up in the console when the issue occurs - `plt.odsp-common.js`:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at e.collectSPClientFlights (plt.odsp-common.js:1:165108)
    at t._logWindowVariables (splistwebpack.js:2:208734)
    at splistwebpack.js:2:203159
```

**Comment by remconsultancy** [comment] 2023-08-21 20:36
Hi @AJIXuMuK, 

I'm having the exact same issue.

The error 'Fail to load customizer for column: MyTestColumn, error: Manifest not found for componentId [guid]'
I'm getting the same errors in the console as @joliq 
I've tested this with version 1.16.1 and 1.17.4

The field customizers used to load correctly and now only show after a CTRL+F5 unfortunately.

Is there any update regarding a fix for this?

Many thanks,

Remco

**Comment by EA12** [comment] 2023-08-22 10:03
Hi all,
I am getting the same error with version 1.16.1
The same package is installed on several site app catalogs and working. The latest one installed is not working.
Of course, I doublechecked the componentId, urls, field- and library names.

I can see following errors right before: Fail to load customizer for column:... Manifest not found for componentId...

error loading spfx preloaded data with spfxPageContext
error parsing pageContextJson for manifests
from plt.items-view.js

Uncaught (in promise) SyntaxError: Unexpected token 'J', "JSON.parse"... is not valid JSON
    at JSON.parse (<anonymous>)
    at plt.items-view.js:1:885271

This is a big pain now, as we cannot roll out a new process.

Is there any update regarding a fix for this?

Many thanks, Ronny

**Comment by roldengarm** [comment] 2023-08-23 01:24
Still the same issue here. Just got a response from support that they could reproduce the issue still as well and would reach out to the product team.

It's two weeks ago now @AJIXuMuK and still not fixed.

**Comment by EA12** [comment] 2023-08-23 07:24
Sorry folks, what a damn mistake. I added the package to the site app catalog, but didn't added the app. This solved "Fail to load customizer for column:... Manifest not found for componentId..." for me.

**Comment by joliq** [comment] 2023-08-24 07:37
> Still the same issue here. Just got a response from support that they could reproduce the issue still as well and would reach out to the product team.
> 
> It's two weeks ago now @AJIXuMuK and still not fixed.

Still the same issue for us as well - now in all our 3 tenants.

**Comment by AJIXuMuK** [comment] 2023-08-24 16:10
@roldengarm - are you using custom CDN or deployment of assets to the app catalog?
If the latter - there is a known issue that was there for a while that repros when you have a default view without SPFx extensions and another view WITH extensions.
If you navigate from one to another - the extensions will not work.
But you should see errors like that in this case:
```
Refused to load the script '<URL>' because it violates the following Content Security Policy directive: "script-src 'self' <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> *.cdn.office.net *.fluidpreview.office.net <URL> <URL> <URL> <URL> <URL> <URL> <URL> 'unsafe-eval' 'nonce-'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```

**Comment by roldengarm** [comment] 2023-08-24 20:26
Hi @AJIXuMuK  we're using the app catalog, not a CDN.

We've investigated that default view issue in the past, and added the field with the extension to the default view, but that didn't solve the issue either.

So it doesn't look like the caching changes have fixed the issue?

**Comment by AJIXuMuK** [comment] 2023-08-24 20:39
@roldengarm - there are "types" different issues I'd say:
- cache issue: when a new version of a package is installed it was not available for users for a while. It should have been fixed and the new version should be there in ~10 minutes.
- custom CDN: the one that I described above
- non default view without custom CDN: this should have been fixed last week
- something else I'm not aware about.

If the support team can repro - it will come to us and we'll figure it out.
For now, without a repro, I can't tell what issue is there.

**Comment by roldengarm** [comment] 2023-08-24 21:26
Yep, it's something else. The support team can reproduce and should have already contacted you / the product team. @AJIXuMuK

**Comment by roldengarm** [comment] 2023-08-29 21:33
> @roldengarm - are you using custom CDN or deployment of assets to the app catalog? If the latter - there is a known issue that was there for a while that repros when you have a default view without SPFx extensions and another view WITH extensions. If you navigate from one to another - the extensions will not work. But you should see errors like that in this case:
> 
> ```
> Refused to load the script '<URL>' because it violates the following Content Security Policy directive: "script-src 'self' <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> *.cdn.office.net *.fluidpreview.office.net <URL> <URL> <URL> <URL> <URL> <URL> <URL> 'unsafe-eval' 'nonce-'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
> ```

Hi @AJIXuMuK  it just happened to me again. I went to the site, then to one list with the custom field extension (worked fine), then to another list with the same field extension => empty.

I don't see the CSP error you describe. What I do see is that it tried to load a JS file from <site>/ClientSideAssets/<guid>/details-link-field-customizer_<guid>.js which does not exist. When I go to that folder, I see a JS file with another guid.

We did do a deployment yesterday; which is now about 16 hours ago. You mentioned it should be present within 10 minutes, which is acceptable. It's not acceptable what I'm seeing.

Hope this helps.

**Comment by AJIXuMuK** [comment] 2023-08-30 13:07
@roldengarm - is this infor provided in the support ticket?
The issue with caching is hard to repro and can be a cross-org effort to address.
For that reason I would like to have a support ticket with all the info provided in there.
Thanks for understanding.

**Comment by joliq** [comment] 2023-08-30 14:01
> I only have the issue in a new tab when I open the list using Quicklink or Quick Launch Bar. Do you have the same behaviour?

@KienbMi 
We have the same behaviour. It does not work when when you first visit the site home page and then click a "standard" quicklaunch link that points to the default view. 
I have noticed a workaround - it works if you add a list web part on the site start page.

**Comment by roldengarm** [comment] 2023-08-30 23:57
> @roldengarm - is this infor provided in the support ticket?
> The issue with caching is hard to repro and can be a cross-org effort to address.
> For that reason I would like to have a support ticket with all the info provided in there.
> Thanks for understanding.

Yes, I have provided all information in the support ticket, see ticket number 2306140030005503
The support person could reproduce the issue relatively easily. @AJIXuMuK

**Comment by roldengarm** [comment] 2023-09-13 05:09
> @roldengarm - I believe there is a misunderstanding. I don't know the details of the support ticket. But most probably the response was that it may happen due to caching when some Web Front Ends are not getting updated right away. And on some tenants it might take a while while the cache is updated. We have a fix rolling out to decrease the time for cache update. When it's propagated (I would give it a few weeks) all the cache should be up to date in 10 minutes. Meaning if you upload an SPFx app in 10 minutes it MUST be available (same for new versions of the app).
> 
> If in a few weeks you're still experiencing the issue - please mention me in this issue. I will not be closing it.

A month later and the issue still persists, multiple days after a deployment. Our ticket with Microsoft has been open for almost three months now. The support person has supplied additional logs & screenshots to the PG this week. Any ideas?  @AJIXuMuK

**Comment by AJIXuMuK** [comment] 2023-09-13 13:27
@roldengarm - unfortunately, I don't have any information on the support ticket.

**Comment by AJIXuMuK** [comment] 2023-10-11 13:38
Update on the initial topic.
There were some additional fixes needed that are still rolling out.
The issue should be fixed by end of the next week.

**Comment by roldengarm** [comment] 2023-10-11 20:06
@AJIXuMuK  thanks for the update. We've also gotten word that it has been fixed, and that seems to have arrived to our tenant finally. It still is empty for about 10 minutes after deployment, which is not ideal, but much better than previously. I think this issue can be closed.

**Comment by AJIXuMuK** [comment] 2023-10-11 21:16
@roldengarm - thanks for the confirmation!
10 mins is our internal time for cache update.

**Closed** 2023-10-12 12:26 UTC
Labels: type:bug-suspected, area:spfx

**Comment by pkrsingh86** [comment] 2023-10-16 13:58
Hello,
We are too facing an intermitted issue related to "Field Customizer". It does not load sometime. We need to refresh the page to make it work.

**Comment by roldengarm** [comment] 2023-10-18 19:28
That seems like a different bug @pkrsingh86 . Please click the link after "visit" as it seems like an error in your code.

**Comment by pkrsingh86** [comment] 2023-10-18 19:52
@roldengarm : Thanks for your response. It seems version compatibility issue. Ref link: https://github.com/SharePoint/sp-dev-docs/issues/9270
