### ISSUE TITLE
SPFx Command set extension onListViewUpdated event is not fired while opening/traversing a folder inside document library

### ISSUE THREAD

**Issue by sankarkumar23** [SharePoint/sp-dev-docs#6967] opened 2021-05-02 11:15 UTC
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Describe the bug / error

There are many other tickets on the same issue and they say the issue is fixed.

I am still facing the issue. "onListViewUpdatedevent" is not fired when I select a folder from root level and traverse back to document library.
Here is the one of previous issue. https://github.com/SharePoint/sp-dev-docs/issues/4870#issue-519069281

### Steps to reproduce

Open document library and open any folder or traverse back to root folder. It will never invoke onListViewUpdated event.

### Expected behavior

onListViewUpdated should be triggered when you traverse back and forth between root folder and folder.

**Comment by sankarkumar23** [comment] 2021-05-16 10:49
Would there be a chance to get this resolved soon? This is blocking my project. Appreciate your response soonest.

**Comment by AJIXuMuK** [comment] 2021-09-07 17:12
Seems like a duplicate of #6252

**Comment by patmill** [comment] 2021-09-07 18:48
Closing as dupe, will follow up on #6252

**Closed by patmill** 2021-09-07 18:48 UTC
Labels: type:bug-suspected, area:spfx, status:to-be-reviewed, area:spfx-extensions
