### ISSUE TITLE
(New Teams) SPFX WebPart in teams tab turns black after loading 

### ISSUE THREAD

**Issue by doxic012** [SharePoint/sp-dev-docs#9186] opened 2023-09-06 11:45 UTC
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [x] 💥 Microsoft Edge
- [x] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [X] other (enter in the "Additional environment details" area below)

### Additional environment details

- Teams version: 23217.806.2340.1703 (2023-09-06)
- Teams client version: 49/23082000931
- SPFx version: 1.14.0
- Node.js version: 14.17.6
- React 16.9.56
- Tab Manifest Version: 1.16

The app is deployed via apps for sharepoint from the app catalog website and synced to teams with the "Sync to teams" button inside the list.

This is the manifest (obscured):

```json
{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.16/MicrosoftTeams.schema.json",
  "manifestVersion": "1.16",
  "packageName": "com.MyApp.Employees",
  "id": "c0595f02-80da-4653-975c-02b03e28a9aa",
  "version": "1.10.0",
  "developer": {
    "name": "doxic",
    "websiteUrl": "https://myApp.com/",
    "privacyUrl": "https://privacy.microsoft.com/en-us/privacystatement",
    "termsOfUseUrl": "https://www.microsoft.com/en-us/servicesagreement"
  },
  "name": {
    "short": "Employees",
    "full": "Employees"
  },
  "description": {
    "short": "Teams-Integrated application for Employees",
    "full": "Teams-Integrated application for Employees."
  },
  "icons": {
    "outline": "c0595f02-80da-4653-975c-02b03e28a9aa_outline.png",
    "color": "c0595f02-80da-4653-975c-02b03e28a9aa_color.png"
  },
  "accentColor": "#203e4a",
  "staticTabs": [
    {
      "contentUrl": "https://{teamSiteDomain}{teamSitePath}/_layouts/15/TeamsLogon.aspx?SPFX=true&dest={teamSitePath}/_layouts/15/teamshostedapp.aspx%3Fteams%26personal%26componentId=c0595f02-80da-4653-975c-02b03e28a9aa%26forceLocale={locale}%26subEntityId={subEntityId}",
      "name": "Employees",
      "entityId": "MyApp.Employees",
      "scopes": [
        "personal"
      ]
    }
  ],
  "validDomains": [
    "*.login.microsoftonline.com",
    "*.sharepoint.com",
    "*.sharepoint-df.com",
    "spoppe-a.akamaihd.net",
    "spoprod-a.akamaihd.net",
    "resourceseng.blob.core.windows.net",
    "msft.spoppe.com"
  ],
  "localizationInfo": {
    "defaultLanguageTag": "en-us",
    "additionalLanguages": [
      {
        "languageTag": "de-de",
        "file": "de-de.json"
      }
    ]
  },
  "permissions": [
    "identity"
  ],
  "isFullScreen": false,
  "devicePermissions": ["notifications", "media"],
  "webApplicationInfo": {
    "resource": "https://{teamSiteDomain}",
    "id": "00000003-0000-0ff1-ce00-000000000000"
  }
}

``` 

### Describe the bug / error

I created an spfx webpart for a teams static tab that is running fine in the old teams, browser, mobile (android), but since adopting the new teams client, the webpart loads, displays the content it's supposed to and then turns the whole app turns black.
(PnP logs with ctrl +F12 work until the app turns black).
The app is using graph api to get user data, sending mails and stores data in sharePoint lists which are accessed via PnPjs with odata queries.

To me it seems like an error coming from the sharepoint framework itself. I tried using try/catch wrappers in the `BaseClientSideWebpart` methods to display a possible Exception without any success:
- `render`
- `renderError`
- `onInit`

The weird thing is, my laptop is the only device where this occurs, every other User has no problems displaying the webpart in the teams tab.
I've been using teams 2.0 preview since the beginning with 3-4 accounts registered at the same time.

Since teams 2.0 does not provide any possibility to display the browser console or viewing error logs via a devmode similar to the old teams, I'm struggling to find the cause of this problem (If there is, please enlighten me).
It must be something with the content of the app, graph api access, etc. but I have no more ideas how to get the content of the error.

Here's a video of the tab loading and "crashing" to a blackscreen:
![2023-09-06-13-43-28](https://github.com/SharePoint/sp-dev-docs/assets/3975568/91fcfadc-f8f3-4ff4-b765-dcc3006ded9b)

### Steps to reproduce

1. Open Teams
2. Click the application tab
3. Wait until the app has loaded
4. Crash

### Expected behavior

The spfx webpart loading properly (as it does) and not crashing to a blackscreen

**Comment by AJIXuMuK** [comment] 2023-09-06 13:28
seems like a dupe of #9178

**Comment by nick-pape** [comment] 2023-09-14 14:26
Closing this issue as a dupe. Please refer to our wiki for more details: [Issue List Labels: status:duplicate](https://github.com/SharePoint/sp-dev-docs/wiki/Issue-List-Labels#statusduplicate)

**Closed by nick-pape** 2023-09-14 14:26 UTC
Labels: type:bug-suspected, status:duplicate
