### ISSUE TITLE
Issues when adding FieldCustomizer and CommandSet with the same name

### ISSUE THREAD

**Issue by wictorwilen** [SharePoint/sp-dev-docs#830] opened 2017-09-03 16:03 UTC
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
I should be able to add a FieldCustomizer and CommandSet with the same name, for instance  `Foo` and have it build nicely. I expect to be able to have the same name for these features, or at least a warning that files are being overwritten.

#### Observed Behavior
When adding first a FieldCustomizer with the name `Foo` and then add a CommandSet with the same name `Foo`  a few files are overwritten (more specifically `myStrings.d.ts` and `en-us.js`) which causes the build to fail with the following:
```
[17:58:59] Error - typescript - src\extensions\foo\FooFieldCustomizer.ts(7,25): error TS2307: Cannot find module 'FooFieldCustomizerStrings'.
[17:58:59] Error - 'typescript' sub task errored after 1.77 s
 TypeScript error(s) occurred.
[17:58:59] 'build' errored after 3.29 s
[17:58:59]
[17:59:00] ==================[ Finished ]==================
Error - typescript - src/extensions/foo/FooFieldCustomizer.ts(7,25): error TS2307: Cannot find module 'FooFieldCustomizerStrings'.
Error - 'typescript' sub task errored after 1.77 s
 TypeScript error(s) occurred.
```

#### Steps to Reproduce
Create a new SPFx project with FieldCustomizer named `Foo`, then run the Yeoman generator again and add a CommandSet with the same name (ie `Foo`). Then run `gulp build`.

**Comment by nickpape-msft** [comment] 2017-09-05 20:10
Closing as a duplicate of #757

**Closed by nickpape-msft** 2017-09-05 20:10 UTC
