### ISSUE TITLE
SPFx webpart is deployed to MSTeam - Does not work in Android mobile

### ISSUE THREAD

**Issue by mkokabi** [SharePoint/sp-dev-docs#7651] opened 2022-01-17 06:07 UTC
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

macOS

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [X] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

SharePoint Client-side Generator@1.13.1
node --version v14.18.2

### Describe the bug / error

I am following this page and my webpart CAN connect to my Azure Function, however when I deploy it to MS Team following [this article](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab) it DOESN'T work anymore.

### Steps to reproduce

1. Follow this article 
2. Test the web part local and it can connect to Azure
3. Follow another article from Microsoft ([ref](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab)) 
4. Test it in MS Team desktop it works.
5. Test it in MS Team Android and it can NOT connect
6. Test it in MS Team Edge browser in Android and it works.

### Expected behavior

I was expecting the Web version of MS Team and MS Team app should be similar.

**Comment by AJIXuMuK** [comment] 2022-01-24 20:54
Dupe of #7646

**Closed** 2022-01-24 20:55 UTC
Labels: type:bug-suspected, status:duplicate, area:spfx
