### ISSUE TITLE
Clearing loading indicator removes web part

### ISSUE THREAD

**Issue by katjones23** [SharePoint/sp-dev-docs#6982] opened 2021-05-04 16:18 UTC
Using the code provided in **Use cascading dropdowns in web part properties** > **Populate the dropdown with SharePoint lists to choose from** > **Show available lists in the list dropdown**.  When _this.context.statusRenderer.clearLoadingIndicator(this.domElement)_ is called, it removes the web part and the following error is received: "Warning: render(...): It looks like the React-rendered content of this container was removed without using React. This is not supported and will cause errors. Instead, call ReactDOM.unmountComponentAtNode to empty a container."

[Show available lists in the list dropdown](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/use-cascading-dropdowns-in-web-part-properties#show-available-lists-in-the-list-dropdown)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8fe85ee-ede7-1cac-d524-d448051dfc45
* Version Independent ID: 1ee793b9-d693-4967-988f-53c3657b5970
* Content: [Use cascading dropdowns in web part properties](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/use-cascading-dropdowns-in-web-part-properties)
* Content Source: [docs/spfx/web-parts/guidance/use-cascading-dropdowns-in-web-part-properties.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/guidance/use-cascading-dropdowns-in-web-part-properties.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by AJIXuMuK** [comment] 2022-01-04 14:38
Dupe of #6854

**Closed** 2022-01-04 14:38 UTC
Labels: status:duplicate, type:question, area:docs, area:spfx, area:docs-comment
