### ISSUE TITLE
Performance Information - SPFx WebParts

### ISSUE THREAD

**Issue by suz7777** [SharePoint/sp-dev-docs#473] opened 2017-03-07 18:21 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x ] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
I am pressing Ctrl-F12 on an Office Groups New Modern Page, and the performance tab does not show the first web part on the page.

#### Steps to Reproduce
Go to an office group and create a new modern page.  Add one web part on the page.  
Press CTRL F12 and click on the performance tab
note the web part is not displayed.  
Add another webpart on the page.
Refresh / Repeat
The second web part is displayed
![image](https://cloud.githubusercontent.com/assets/9094896/23671367/964f23e4-0330-11e7-9524-32ff1908fa4d.png)

**Comment by patmill** [comment] 2017-03-08 18:33
Hi @suz7777 - Is the comment that after a full render, that adding a webpart doesn't update the perf tab, or that adding/saving the webpart, then refreshing, the new part isn't added?

The perf data is generated at page render time, so it won't show updates made after the render.

**Comment by suz7777** [comment] 2017-03-09 06:27
@patmill the issue is that the first web part on the page never seems to display in the performance tab... if you have only one web part on the page, you don't see the web part in the above image... 
if you add two or more web parts you will see the  second / third / etc web parts on the page - in the image above the "image web part" was on the page, but does not show up in the Trace tab - just the second and third web parts.. make sense?

**Comment by amishra0909** [comment] 2017-05-09 23:28
@suz7777, please make sure that after adding the webpart, for it to show on the performance dashboard, you need to refresh the page. I am unable to reproduce this issue and so I am closing it. If you find that the issue is not resolved please reopen it and we will track it then.

**Closed by amishra0909** 2017-05-09 23:28 UTC
