### ISSUE TITLE
SPFx authorization error on calling graph api with graphClient

### ISSUE THREAD

**Issue by canturan** [SharePoint/sp-dev-docs#7275] opened 2021-08-25 11:21 UTC
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version: Edge: Version 92.0.902.78, Chrome: Version 92.0.4515.159
- SPFx version: 1.11
- Node.js version: 10.16

### Describe the bug / error

Starting from today the authorization flow is broken for SPFX web part while calling graph api. I cannot get any graph token with my SPFx web part. The behavior is the same on all platforms, in SP as a web part, in teams as a tab or personal app. The moment I call the graph api with the client ( graphClient.api(xxxx).get() ) in the code, I am seeing the following error messages in the console 

![image](https://user-images.githubusercontent.com/13345587/130782021-795ccea8-af9a-4a18-8a50-73bbc93b71c4.png)

At the moment I am seeing this behavior only on my DEV tenant, which is a targeted release tenant. 

### Steps to reproduce

1. call graphClient.api(xxxx).get() in the code (ex: https://graph.microsoft.com/v1.0/me)

### Expected behavior

I need to be able to call the graph api from a SPFX web part.

**Comment by umaknow-joel** [comment] 2021-08-25 13:49
We are having the exact same problem.  It started yesterday morning and doesn't affect all users.

**Comment by umaknow-pierre** [comment] 2021-08-25 13:51
Same here!

**Comment by OliverZeiser** [comment] 2021-08-25 14:36
We are seeing the same thing!

**Comment by GrahamMcMynn** [comment] 2021-08-31 01:16
This issue has now been resolved.

**Comment by VesaJuvonen** [comment] 2021-08-31 08:30
@GrahamMcMynn was a bit on the point and indeed - issue has been fixed. Let me elaborate this a bit and thank everyone for providing details on this issue, so that we get the right level of attention on this internally.

Cause of the issue was a regression caused by future development topics related on the auth model, impacting unfortunately also SharePoint Framework auth models (MSAL), impacting specifically scenarios in the Microsoft Teams model. Super unfortunate mistake caused by change done by a developer without realizing the implications within the dependency pipeline.

Thanks everyone for reporting this and for adding additional comments and details on the issue. Issue has been now resolved by rolling back the change, which was impacting this. Persons who caused the issue are award and are now one regression more experienced on avoiding similar issues in future.

**Closed** 2021-08-31 08:41 UTC
Labels: area:spfx, status:fixed
