### ISSUE TITLE
Question: Sharepoint online Checked Out files are not visible with App-only context

### ISSUE THREAD

**Issue by Svet24** [SharePoint/sp-dev-docs#3267] opened 2019-01-15 08:59 UTC
I've create app-only context for Sharepoint Online using GetAzureADAppOnlyAuthenticatedContext method (SharePointPnPCoreOnline.3.5.1901). Azure app has 'Have full control of all site collections' application permission for Office 365 SharePoint Online API. 

However checked out files are not visible despite Draft Item Security in Versioning Settings.
The current value of versioning settings:  Who should see draft items in this library? -  Any user who can read items.

How to make these documents visible for app-only authenticated context without taking ownership?

**Comment by VesaJuvonen** [comment] 2019-02-07 18:40
When a file is checked out, the major version is visible, if it has been checked in at least for once. If it's a minor version without major version, it is by design not to be visible for app-only or any other user.

**Closed by VesaJuvonen** 2019-02-07 18:40 UTC
Labels: status:answered
