### ISSUE TITLE
ApplicationCustomizer navigated event not firing when creating a new page

### ISSUE THREAD

**Issue by clarktozer** [SharePoint/sp-dev-docs#5029] opened 2019-12-18 03:51 UTC
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When a user is on a Site Page and clicks to add a new page via the command bar drop down or via "Add a page" in the settings panel the navigatedEvent should fire as the URL changes to:

- "SitePages/newpage.aspx?Mode=Edit" 
- Then to a generated page URL e.g "SitePages/nmorjnzr.aspx?Mode=Edit"
- Then to whatever title you have set in the page e.g "SitePages/addedpage.aspx"

This should then update the context object with the correct list item id of the newly created page in the application customizer (context.pageContext.listItem.id). 

#### Observed Behavior

Navigated event is not fired on new page creation. The user is on the new page that was created but the current context is incorrect. 

#### Steps to Reproduce

SharePoint Environment: SharePoint Online
SPFx Version: 1.9.1
Browser: Chrome

Create an application customizer that logs to the console each time the navigatedEvent fires.
It will not log when creating a new page from the command bar drop down or via "Add a page" in the settings panel. I'll provide a repo if necessary.

![image](https://user-images.githubusercontent.com/9270883/71054089-bac44700-21a4-11ea-82dc-993914c674b2.png)

![image](https://user-images.githubusercontent.com/9270883/71054077-b26c0c00-21a4-11ea-8949-eef7d090ba20.png)

**Comment by andrewconnell** [comment] 2019-12-18 10:53
Known issues with this event, this is a dupe of #4054 & #3210... as such can you consolidate any additional feedback to those issues for tracking? Thanks!

**Closed** 2019-12-18 10:54 UTC
Labels: area:framework-extensions, area:framework-general, status:duplicate

**Comment by clarktozer** [comment] 2019-12-18 22:10
Thanks. I'll add the description of this to #4054
