### ISSUE TITLE
Cannot find module '@microsoft/sp-property-pane'.

### ISSUE THREAD

**Issue by pmeripe** [SharePoint/sp-dev-docs#3658] opened 2019-03-22 00:57 UTC
> Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Category
- [ ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

> For the above list, an empty checkbox is [ ] as in <kbd>[</kbd><kbd>SPACE</kbd><kbd>]</kbd>. A checked checkbox is [x] with no space between the brackets. Use the `PREVIEW` tab at the top right to preview the rendering before submitting your issue.
>
> If you are planning to share a new feature request (enhancement / suggestion), please use SP Dev UserVoice at http://aka.ms/sp-dev-uservoice. (DELETE THIS PARAGRAPH AFTER READING)
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Expected or Desired Behavior

> If you are reporting a bug, please describe the expected behavior. If you are suggesting an enhancement please describe thoroughly the enhancement, how it can be achieved, and expected benefit.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Observed Behavior

> If you are reporting a bug, please describe the behavior you expected to occur when performing the action. If you are making a suggestion, you can delete this section.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Steps to Reproduce

> If you are reporting a bug please describe the steps to reproduce the bug in sufficient detail to allow testing. Only way to fix things properly, is to have sufficient details to reproduce it. If you are making a suggestion, you can delete this section.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Submission Guidelines

> - All suggestions or bugs are welcome, please let us know what's on your mind.
> - If you are reporting an issue around any of the documents or articles, please ensure that you have clear > reference on the specific file or URL, which should be fixed.
> - If you have technical questions about the framework, we’ll be monitoring #spfx, #spfx-webparts, and > #spfx-tooling on (SharePoint StackExchange)[http://sharepoint.stackexchange.com/]. You can also > alternatively submit your question to (SharePoint Developer group)> [https://network.office.com/t5/SharePoint-Developer/bd-p/SharePointDev] at Office Network.
> - Remember to include sufficient details and context.
> - If you have multiple suggestions or bugs please submit them in separate bugs so we can track resolution.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

Thanks for your contribution! Sharing is caring.

**Comment by pmeripe** [comment] 2019-03-22 01:41
![Capture](https://user-images.githubusercontent.com/38794321/54795309-02bc3a80-4c22-11e9-8ced-4dd93d95d84c.PNG)

**Comment by bcameron1231** [comment] 2019-03-22 14:16
Can you provide more information, like what SharePoint Version and SPFx Version you are using. In SPFx 1.8, the property pane code was moved from  sp-webpart-base to sp-property-pane, however it wasn't handled properly in the on-premises solution. 

If you are using on-premises, can you update the reference from sp-property-pane to sp-webpart-base?

Related Issue #3621

**Comment by pmeripe** [comment] 2019-03-22 14:25
We use SP Online only, but I selected 2016/2019/SP Online while creating SPFx webpart to support in future if we may use 2019 on perm for hybrid. If I select "SP Online" only, gulp serve works fine without any issues. Sometimes I get frustrated with these many packages and different versions and we have to update manually every time.

**Comment by bcameron1231** [comment] 2019-03-22 14:30
Ya understood. So this onPrem version of the generator is incorrectly handling the change. So you should be able to re-reference to sp-webpart-base for the time being, and it should work.

**Comment by pmeripe** [comment] 2019-03-22 14:38
Thanks Beau. That error gone, but I get below errors.
![image](https://user-images.githubusercontent.com/38794321/54830289-9f1c2680-4c8e-11e9-8296-d6a8d706cfa4.png)

**Comment by patmill** [comment] 2019-03-22 16:48
Correct.  We've got a bug tracking this, and will release a patch for the generator soon.  For now, changing the references back to sp-webpart-base will fix the issue.  I will resolve this as a dupe of the other github bug tracking this.

**Closed** 2019-03-22 16:52 UTC
Labels: Needs: Triage :mag:, status:duplicate
