### ISSUE TITLE
SPFx apps does not working on the mobile MS Teams clients (iOS / Android)

### ISSUE THREAD

**Issue by canturan** [SharePoint/sp-dev-docs#7468] opened 2021-11-02 08:36 UTC
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [X] mobile (iOS/iPadOS)
- [X] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Describe the bug / error

Starting from a couple of day ago the SPFx apps does not work on the mobile MS Teams app. I tried to debug the Android Teams app and I am seeing the following error messages: 

The app tries to get a token from the `Microsoft.SharePoint.Internal.ClientSideComponent.Token.AcquireOBOToken` endpoint but gets a 400 response back with the error message: 

`{"odata.error":{"code":"10009","message":{"lang":"en-US","value":"AADSTS500011: The resource principal named https://microsoft.spfx3rdparty.com was not found in the tenant named xxx. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.\r\nTrace ID: 88681487-bde9-4435-9ad4-95f53f7b8800\r\nCorrelation ID: fc1dff9f-50d9-3000-5527-47fe6eac9c39\r\nTimestamp: 2021-11-02 08:10:20Z"}}}`

It happens on the point, where the app calls MSGraph API. 

I have also seen that the endpoint is changed on the SharePoint Online Client Extensibility Web Application Principal app in the Azure AD to api://7eab93b5-92a0-4f10-9fdd-30687a49ad6d/microsoft.spfx3rdparty.com. 

There is also a similar issue [https://github.com/SharePoint/sp-dev-docs/issues/7453](url), but in our case the desktop client still works. 

### Steps to reproduce

1. Open the Teams app on the mobile client (iOS / Android)
2. Navigate to a SPFx personal app 
3. The app won't load

### Expected behavior

The SPFx apps can get a token without an error and loads.

**Comment by VesaJuvonen** [comment] 2021-11-02 08:39
Thanks for reporting this @canturan - we will jump on this asap. We'll follow up on this later today for sure.

**Comment by GrahamMcMynn** [comment] 2021-11-02 15:04
Hi @canturan - This was a regression that was rolled out and since been reverted.  The issue is exactly as you said, that the endpoint URI changed and had a resolution error on the call to AcquireOboToken.  If you visit the web api access page again in tenant admin the endpoint URI will revert back to the previous value and things will continue to work.  We are deploying a fix for the new URI which will roll out in about 2 weeks.  This issue affected the subset of customers who had to change rolled out to them and had visited the web api access page while the change was rolled out (and that regression was shut off on Oct 27th).

**Comment by lucabandMSFT** [comment] 2021-11-02 15:17
@GrahamMcMynn , thanks for the quick replu here.
@canturan : make sure that the account you are using to visit the API Access page in SPO tenant admin has Global Admin role.

**Comment by harshdamaniahd** [comment] 2021-11-02 18:32
the issue which i am facing is for SharePoint mobile app. is this issue connected to teams mobile app as well?

**Comment by lucabandMSFT** [comment] 2021-11-02 18:57
yes, that should affect both.

**Comment by czullu** [comment] 2021-11-03 09:20
Can confirm that a click on https://[tenant]-admin.sharepoint.com/_layouts/15/online/AdminHome.aspx#/webApiPermissionManagement as Global Admin does fix the End-Point on "SharePoint Online Client Extensibility Web Application Principal" on both tenants i have tried.

**Comment by harshdamaniahd** [comment] 2021-11-03 10:40
has something rolled out?
i removed the permission from SharePoint web api principal and re deployed yesterday...and today it started working in standard release environment

**Comment by czullu** [comment] 2021-11-03 10:48
> has something rolled out? i removed the permission from SharePoint web api principal and re deployed yesterday...and today it started working in standard release environment

Not quite sure i understand what exactly you did - but from the answer of @GrahamMcMynn  i understand that going to SharePoint Admincenter ->Advanced->API Accesss as Global Admin does trigger the fix and the End-Point of "SharePoint Online Client Extensibility Web Application Principal" gets reverted from "api://[your tenantid]/microsoft.spfx3rdparty.com" to "https://microsoft.spfx3rdparty.com". With End-Point "https://microsoft.spfx3rdparty.com" your spfx mobile apps should work again - atleast after user log-out/log-in in mobile teams client.

**Comment by canturan** [comment] 2021-11-03 12:27
@lucabandMSFT : I can also confirm that it is working again now.

**Comment by lucabandMSFT** [comment] 2021-11-03 13:55
@canturan , wonderful news! Thanks for have confirmed it. 
Yes: as Graham mentioned, we did roll out a fix for that specific scenario. I'm going to close this issue now. Thanks again for your patience and the feedback that helped us fixing this scenario!

**Closed by lucabandMSFT** 2021-11-03 13:55 UTC
Labels: type:bug-suspected, area:spfx, status:fixed-next-drop, Needs: Attention :wave:
