### ISSUE TITLE
CellFormatter is undefined in Field Customizer

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-docs#874] opened 2017-09-21 04:31 UTC
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Is `CellFormatter` still available?
I'm getting `undefined` in runtime in `onRenderCell` method of Field Customizer

#### Steps to Reproduce
- scaffold field customizer
- import `CellFormatter` definition from `@microsoft/sp-listview-extensibility`
- in `onRenderCell` add `const text: string = CellFormatter.renderAsText(this.context.field, event.fieldValue);`

**Comment by rriopel432** [comment] 2017-09-22 17:07
I see the same thing.  I also see that event.cellValue is now event.fieldValue.

**Comment by AJIXuMuK** [comment] 2017-09-22 18:02
@rriopel432 right, thanks! Updated the code in the question.

**Comment by AJIXuMuK** [comment] 2017-09-26 21:07
Why is it clised? Could you provide the explanation?

**Comment by mcmynn83** [comment] 2017-09-26 21:36
@AJIXuMuK - Sorry about that.  I was going through the issues and read that you "Updated the code in question" and thought somebody had provided you an answer.  My mistake.

**Comment by AJIXuMuK** [comment] 2017-09-26 21:48
No worries :)
The comment was about fieldValue, not CellFormatter

**Comment by mpasarin** [comment] 2017-10-23 22:01
CellFormatter was only present in pre-release versions of SPFx extensions. Considering that the only thing that it did was set the input value inside of the div, as is, with no additional processing, we decided to remove that. In order to do the same, you can just inject the code there.
If we find a good use case that's necessary we'll implement some utility classes to help on that.
I'm going to close this issue as this is by design.

**Closed by mpasarin** 2017-10-23 22:01 UTC
