### ISSUE TITLE
Unable to silently modify package.json in custom Yeoman generator

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-docs#2155] opened 2018-07-01 21:27 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

It is possible to modify/extend package.json using `this.fs.extendJSON(this.destinationPath('package.json'), customJSON);` in custom yeoman generator

#### Observed Behavior

- if the above call is used in `writing` then all the modifications are simply ingored.
- if the above call is used in `install` then the **conflict** statement appears while scaffolding the project

Most probably this behavior depends on `PackageJsonManager` module.
BTW, I've tried to use this module as well like that:
```javascript
install() {
// ...
// copied from the spfx generator
if (PackageJsonManager.PackageJsonManager.instance) {
            PackageJsonManager.PackageJsonManager.load(this.destinationPath('package.json'), this.fs);
        }

// custom code
const packageManager = PackageJsonManager.PackageJsonManager.instance;
packageManager.merge(customJSON);
packageManager.save();
}
```

It fires conflict as well. If you remove `packageManager.save()` then all the modifications will be ignored.

#### Steps to Reproduce

- create custom yeoman generator
- compose with generator-sharepoint
- try to modify package.json as described above.

**Comment by AJIXuMuK** [comment] 2018-07-01 21:30
Currently because of that issue it's impossible to add additional modules just updating package.json. You need to call `this.installNpm`, `this.installYarn` or implementing custom pnpm installation function.

**Comment by AJIXuMuK** [comment] 2018-07-01 23:03
workaround:
```javascript
const packageJsonContent = this.fs.readJSON(this.destinationPath('package.json'));
const newPackageJsonContent = _.merge(packageJsonContent, pkgJson);
fs.writeFileSync(this.destinationPath('package.json'), JSON.stringify(newPackageJsonContent, null, 4));
```

**Comment by StfBauer** [comment] 2018-07-02 11:28
PackageJsonManager.PackageJsonManager is an internal SPFx object and function you should not use in your code.

```this.fs.extendJson``` is not able to work because to do now own or produce the ```package.json``` generated by SPFx.

The workaround the only official way to do it, just like other Yeoman official generator does that need to extend the package.json.

This is not a bug in the generator it is an expected and expectable behaviour.

There are more problems with your approach too. The files physically only exists after all write methods were executed. Before that a virtual file system gets generated in the memory.

**Comment by AJIXuMuK** [comment] 2018-07-02 16:08
Discussed with @StfBauer.

I have created this bug because of the Yeoman documentation: [http://yeoman.io/authoring/dependencies.html](http://yeoman.io/authoring/dependencies.html).

It is said **"You can programatically create or extend your package.json file if you don’t want to use a template but like to have fixed versions of your dependencies. Yeomans file system tools can help you to get this job done."**
and example:
```javascript
writing() {
    // ...
    // Extend or create package.json file in destination path
    this.fs.extendJSON(this.destinationPath('package.json'), pkgJson);
}
```

Probably, this approach doesn't work when composing generators.
What I'll do I'll look into custom generators, not SPFx, and composability to be 100% sure that this behavior doesn't work in other generators.

For now you can close the issue if it's critical for some reports.

I'll comment on that if I find any new related information.

**Comment by VesaJuvonen** [comment] 2018-08-09 18:17
Closing for now. Let's work together with @StfBauer and @AJIXuMuK on coming up with a standard solution for extensions. I'll set up a call with you guys sooner or later.

**Closed by VesaJuvonen** 2018-08-09 18:17 UTC

**Comment by dantman** [comment] 2020-01-16 22:40
Was this issue ever revisited and solved? It's the first thing that comes up in Google when you look for "yeoman edit package.json", instead of any information on how to do so.

**Comment by AJIXuMuK** [comment] 2020-01-16 23:47
@dantman this issue was mostly related to SharePoint Yeoman generator in context of creation [PnP Yeoman Generator](https://github.com/pnp/generator-spfx).
And we used approach similar to the one described above as a workaround:
```javascript
const packageJsonContent = this.fs.readJSON(this.destinationPath('package.json'));
const newPackageJsonContent = _.merge(packageJsonContent, pkgJson);
fs.writeFileSync(this.destinationPath('package.json'), JSON.stringify(newPackageJsonContent, null, 4));
```

**Comment by terenceodonoghue** [comment] 2020-01-21 23:33
Running into this same issue myself; I'm attempting to compose generators, and the workaround above isn't updating my package.json, or it is but then the changes get overwritten upon file creation.

**Comment by terenceodonoghue** [comment] 2020-01-21 23:40
Came here from Google with the exact same issue; I'm trying to compose generators, and any changes I make to the package.json are getting ignored or overwritten somewhere. The workaround above doesn't appear to work for me.

**Comment by AJIXuMuK** [comment] 2020-01-22 00:36
Please, take a look at the repo I mentioned in my previous comment. It's a "wrapper" generator on top of SharePoint Framework Yeoman generator and it actually modifies package.json that has been generated by sub-generator.
