### ISSUE TITLE
SPFx WebParts don't render in Internet Explorer

### ISSUE THREAD

**Issue by lacstefanov** [SharePoint/sp-dev-docs#3148] opened 2018-12-19 14:15 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Only in Internet Explorer the most generic error message, related to SPFx webaprt not rendering is being displayed. The error has been observed on many other occasions.
The webpart is getting rendered completely fine in Chrome, Firefox and Edge.

#### Observed Behavior

[SPLoaderError.loadComponentError]:
***Failed to load component "58c4fb68-60f1-45ac-b057-ba7cc51c3ec2" (WebPartName).
Original error: ***Failed to load URL 'https://publiccdn.sharepointonline.com/tenantname.sharepoint.com/sites/AppCatalogName/ClientSideAssets/ca2eacd0-4645-4306-a335-e5d9aa919578/web-part-name_e437798e9f3bcfff6ee74118a0bf73ed.js' for resource 'web-part-name' in component '58c4fb68-60f1-45ac-b057-ba7cc51c3ec2' (WebPartName). There was a network problem.
This may be a problem with a HTTPS certificate. Make sure you have the right certificate.

#### Steps to Reproduce

Try to load the webpart within IE 11.

**Comment by andrewconnell** [comment] 2018-12-20 10:42
Looks like a dupe of #2892 & a known issue with IE11... if you agree, you can close this and monitor that issue for status updates.

**Comment by lacstefanov** [comment] 2018-12-20 10:52
Hello Andrew,

No, the issue is not related to the local workbench, but to a fully
production deployment of a webpart.

Best regards,
Lachezar

На чт, 20.12.2018 г. в 12:42 ч. Andrew Connell <notifications@github.com>
написа:

**Comment by nick-gaudreau** [comment] 2019-02-07 15:56
@lacstefanov I had a similar issue. Since your assets are included in your solution package. Make sure the user accessing your web parts has permissions to read appcatalog.

**Comment by lacstefanov** [comment] 2019-02-10 17:34
@nick-gaudreau , the issue is reproducible with an App Catalog admin user; in addition, I experimented with assigning it to both the Reader and Member groups of the App catalog site collection; didn't make any difference.

**Comment by archie-n** [comment] 2019-04-08 05:34
Hi everyone, 

I 'm getting the same issue. Basically, I have uploaded modern web parts, on a classic share point page. The web parts are not loading on IE11.  

Are there any updates on this issue?

Regards,
Archana

**Comment by archie-n** [comment] 2019-04-12 05:14
Hi everyone,

The issue of web parts not loading on IE 11 is now resolved, the problem was due to an npm package that we were using which was not compatible to IE 11. 
We used another package and web parts are now loading in IE 11.

Thanks.

**Comment by andrewconnell** [comment] 2019-08-09 20:19
Have you reviewed the recently published supported browsers docs here: https://support.office.com/en-us/article/Which-Browsers-Work-With-Office-Online-AD1303E0-A318-47AA-B409-D3A5EB44E452

Pay special attention to the IE11 node for the modern experience & IE's document mode.

If you continue to have the issue, please comment back with some additional context. Thanks!

**Closed** 2019-08-23 22:00 UTC
Labels: Needs: Author Feedback, area:framework-general, no-recent-activity, status:tracked
