### ISSUE TITLE
SPFX library solution cannot be added to site collection

### ISSUE THREAD

**Issue by arunakshi** [SharePoint/sp-dev-docs#6902] opened 2021-04-12 07:43 UTC
## Category

- [x] Bug

## Describe the bug

I am getting “Sorry, something went wrong with adding the app. Click to retry.” when adding a SPFx library component to a site.

## Steps to reproduce

1. Created a SPFX library component.
2. Deployed the library package solution tenant wide. 
3. Install the library component while adding app to site.
4. Library component is always installing and error can be seen in the site contents of classic view.

## Expected behavior

SPFX Library component solution app should be successfully added to the site.

## Environment details (*development & target environment*)

SharePoint online
SPFX v1.10.0

### Additional context

Found some posts with the same reason. We are trying to find official statement that library component is not supported to install in site collection by adding as App.

**Comment by andrewconnell** [comment] 2021-04-13 10:40
Couple things:

- you say you deploy the solution tenant-wide, but then you're saying you install it to the site... are you doing both as that's not necessary
- providing a repro of this will help in troubleshooting

**Comment by AJIXuMuK** [comment] 2022-01-10 17:16
Sorry @arunakshi for the long delay.
This issue seems like a dupe of #6496. And, as mentioned there, the issue is fixed by now.
Please, feel free to open a new issue if you're still experiencing any problems with Library Components install.

**Closed** 2022-01-10 17:16 UTC
Labels: status:duplicate, area:spfx, status:unclear, Needs: Reproduce Steps, Needs: Attention :wave:
