### ISSUE TITLE
new web parts on classic pages

### ISSUE THREAD

**Issue by suz7777** [SharePoint/sp-dev-docs#380] opened 2017-01-23 18:49 UTC
#### Category
- [ x] Bug

#### Expected or Desired Behavior
web parts should load all the time on classic pages.

#### Observed Behavior
On classic pages we have an interesting phenomenon in that sometimes – often the first time the page loads we get the attached error.  If you refresh the page, it loads just fine.  This happens with all sorts of users – not admins, contributors, read-only.   We also find that often the web parts don’t load at all, without error – they just don’t appear.  We refresh the page – all is fine…

#### Steps to Reproduce
Add a new framework web part on a classic page.  close browser go to the page.  or hit the refresh button.  most of the time we go to the URL bar and press enter to reload page and it works every time.

![l_2dcb tmp](https://cloud.githubusercontent.com/assets/9094896/22217909/64cc027a-e16a-11e6-9d91-9b8c4605271c.png)

**Comment by patmill** [comment] 2017-01-23 23:41
Digging in - thanks @suz7777

**Comment by manishgarg1** [comment] 2017-01-23 23:45
Hi @suz7777,  looks like this chrome. When this error happens, do you see any errors in the browser dev console?

**Comment by suz7777** [comment] 2017-01-27 06:16
see attachment
[framework1.pdf](https://github.com/SharePoint/sp-dev-docs/files/734502/framework1.pdf)

**Comment by suz7777** [comment] 2017-01-27 06:18
see attachment 1
[framework1a.pdf](https://github.com/SharePoint/sp-dev-docs/files/734506/framework1a.pdf)

**Comment by mihmbox** [comment] 2017-01-27 12:15
Hi,
I also can reproduce this problem in Chrome.
Sometimes I get "JavaScript" error in web part: 
`sp-webpart-base_en-us_8d0a284….js:48 Uncaught (in promise) undefined
(anonymous) @ sp-webpart-base_en-us_8d0a284….js:48`
Error from page: `[SPWebPartErrorCode.IncorrectBoostrapModule]:: Bootstrap module for web part WebPart.FeatureBoxWebPart.g_bf08e990_ac74_4bc8_9c00_7f34006fd66d not of the correct type. Make sure to export your web part as 'export default WebPartName'. CALLSTACK:: Error
    at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-01-16.005/sp-loader_en-us_4ec28636b0f9b465bd02537852aebf16.js:57:16731)
    at new t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-01-16.005/sp-webpart-base_en-us_8d0a284d4d0d8e404879f4b5fcc7cc99.js:47:22096)
    at Function.t.createWithLogProperties (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-01-16.005/sp-webpart-base_en-us_8d0a284d4d0d8e404879f4b5fcc7cc99.js:47:22635)
    at https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-01-16.005/sp-webpart-base_en-us_8d0a284d4d0d8e404879f4b5fcc7cc99.js:47:31315 LOGPROPERTIES:: {"actualType":"object","wp":{}}`



And sometimes it redirects to Error page (please find attached screenshot)
![error-1](https://cloud.githubusercontent.com/assets/7473764/22370593/3b6e2fde-e4a3-11e6-9259-6771f18ff0fa.PNG)
![error-2](https://cloud.githubusercontent.com/assets/7473764/22370592/3b699f00-e4a3-11e6-97d0-4cddd9f62872.png)

**Comment by manishgarg1** [comment] 2017-02-27 21:02
Hi @suz7777, @mihmbox, do you still repro these issues. We have made a concerted effort to fix these in classic pages.

**Comment by manishgarg1** [comment] 2017-02-28 05:23
Closing at this time. If the issue still repros, please reactivate.

**Closed by manishgarg1** 2017-02-28 05:23 UTC
Labels: type:discussion

**Comment by Masood10** [comment] 2018-05-29 08:21
I have the same problem. Did anyone manged to resolve the issue?
