### ISSUE TITLE
spfx not working in some mobile browsers

### ISSUE THREAD

**Issue by ste123456** [SharePoint/sp-dev-docs#5372] opened 2020-02-20 11:59 UTC
## Category
- [X] Question
- [ ] Typo
- [ ] Additional article idea

## Question

I have an spfx App running in Sharepoint Online. If I use some browsers (like Chrome, Firefox) the App is running normally, with others (Opera, Edge) I got this error.

![Screenshot_20200220_125050_com opera browser](https://user-images.githubusercontent.com/61276202/74931544-16e35b80-53e0-11ea-96e7-5a4f7ae24b0a.jpg)

The details are:

[SPLoaderError.loadComponentError]:

Failed to load component "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX" (MyWebPart). Original error: Failed to load path dependency "MyWebPartStrings" from component "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX" (DigitalDocumentsWebPart). Original
error: Script error for:XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX_0.0.1/MyWebPartStrings

It seems that the file MyWebPartStrings.js can't be loaded.
Even more strange is the behavior on Edge, if I browse the page in Desktop Mode i see the App, instead if I browse in Mobile Mode i get the error.

## Environment details

 - OS: [Android]
 - Framework: [vue v2.6.10]
 - Browser(s): [Chrome v80, Opera v56, Edge v44]
 - Tooling: [VS Code, SPFx v1.10.0]

**Comment by andrewconnell** [comment] 2020-02-26 23:13
Believe this is a dupe of #4968 ... known issues with SPFx on mobile. A fix is rolling out. Please monitor that issue. 

FYI - Opera is not a supported browser on SPO: https://support.office.com/en-us/article/which-browsers-work-with-office-for-the-web-ad1303e0-a318-47aa-b409-d3a5eb44e452

**Closed** 2020-02-26 23:13 UTC
Labels: Needs: Triage :mag:, status:duplicate
