### ISSUE TITLE
"gulp serve" failing on a clean yeoman project

### ISSUE THREAD

**Issue by cgronseth** [SharePoint/sp-dev-docs#246] opened 2016-10-18 16:53 UTC
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea
#### Expected or Desired Behavior

gulp serve should finish without errors on new and clean generated project
#### Observed Behavior

gulp / gulp serve gives this output:

```
christo@mint18-VirtualBox ~/Code/HolaMundo $ gulp
Build target: DEBUG
[17:56:41] Using gulpfile ~/Code/HolaMundo/gulpfile.js
[17:56:41] Starting gulp
[17:56:41] Starting 'default'...
[17:56:41] Starting subtask 'pre-copy'...
[17:56:41] Finished subtask 'pre-copy' after 21 ms
[17:56:41] Starting subtask 'tslint'...
[17:56:41] Starting subtask 'copyStaticAssets'...
[17:56:41] Starting subtask 'sass'...
[17:56:43] Error - 'tslint' sub task errored after 1.11 s 
 Error in plugin 'gulp-cache'
Message:
    Cannot find module './h6'
Details:
    code: MODULE_NOT_FOUND
[17:56:43] 'default' errored after 1.15 s
[17:56:43] 
[17:56:43] Finished subtask 'sass' after 1.29 s
[17:56:43] Starting subtask 'typescript'...
[17:56:43] [typescript] Using custom version: 2.0.3
[17:56:43] Finished subtask 'copyStaticAssets' after 1.37 s
[17:56:50] ==================[ Finished ]==================
Error - 'tslint' sub task errored after 1.11 s 
 Error in plugin 'gulp-cache'
Message:
    Cannot find module './h6'
Details:
    code: MODULE_NOT_FOUND
[17:56:50] Finished subtask 'typescript' after 6.93 s
[17:56:50] Starting subtask 'ts-npm-lint'...
[17:56:50] Finished subtask 'ts-npm-lint' after 97 ms
[17:56:50] Project hola-mundo version: 0.0.1
[17:56:50] Build tools version: 0.11.1
[17:56:50] Node version: v6.8.1
[17:56:50] Total duration: 12 s
[17:56:50] Task errors: 1
```
#### Steps to Reproduce

This is running on Mint Cinnamon 18 under VirtualBox virtual machine. Host OS is Windows 7.
NodeJS installed using package manager,
Yeoman installed by npm, and using the latest generator version 0.2.1

Steps to reproduce:

```
mkdir HolaMundo
cd HolaMundo
yo @microsoft/sharepoint

Selected default values, except name of webpart which I set to HolaMundo.

gulp serve -> Error.

```

Issue #144 seems to be related but couldn't find a fix.

**Comment by patmill** [comment] 2016-10-18 17:03
As a starting point, can you switch to the LTS version of node (4.6.0)?

**Comment by cgronseth** [comment] 2016-10-18 17:42
Ok, switched to 4.6.0, but still get the same error, plus the "rimraf" one also.
Started all over again, rm -rf the directory.

```

    _=+#####!       
   ###########|       .-----------------------------------.
   ###/    (##|(@)    |          Congratulations!         |
   ###  ######|   \   |  Solution hola-mundo is created.  |
   ###/   /###|   (@) |  Run gulp serve to play with it!  |
   #######  ##|   /   '-----------------------------------'
   ###     /##|(@)    
   ###########|       
      **=+####!       


     _-----_     ╭───────────────────────╮
    |       |    │      Bye from us!     │
    |--(o)--|    │       Chat soon.      │
   `---------´   │      Yeoman team      │
    ( _´U`_ )    │    http://yeoman.io   │
    /___A___\   /╰───────────────────────╯
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

christo@mint18-VirtualBox ~/Code/HolaMundo $ gulp serve
[19:34:26] Error - Unknown 
 Cannot find module 'rimraf'
[19:34:26] ==================[ Finished ]==================
[19:34:27] Project hola-mundo version: 0.0.1
[19:34:27] Build tools version: 0.11.1
[19:34:27] Node version: v4.6.0
[19:34:27] Total duration: 1.18 s
[19:34:27] Task errors: 2
christo@mint18-VirtualBox ~/Code/HolaMundo $ npm install rimraf
rimraf@2.5.4 node_modules/rimraf
└── glob@7.1.1 (path-is-absolute@1.0.1, inherits@2.0.3, fs.realpath@1.0.0, inflight@1.0.6, once@1.4.0, minimatch@3.0.3)
christo@mint18-VirtualBox ~/Code/HolaMundo $ npm i
christo@mint18-VirtualBox ~/Code/HolaMundo $ gulp serve
Build target: DEBUG
[19:36:32] Using gulpfile ~/Code/HolaMundo/gulpfile.js
[19:36:32] Starting gulp
[19:36:32] Starting 'serve'...
[19:36:32] Starting subtask 'pre-copy'...
[19:36:32] Finished subtask 'pre-copy' after 539 ms
[19:36:32] Starting subtask 'tslint'...
[19:36:32] Starting subtask 'copyStaticAssets'...
[19:36:32] Starting subtask 'sass'...
[19:36:48] Error - 'tslint' sub task errored after 16 s 
 Error in plugin 'gulp-cache'
Message:
    Cannot find module './h6'
Details:
    code: MODULE_NOT_FOUND
[19:36:48] 'serve' errored after 17 s
[19:36:48] 
[19:36:49] Finished subtask 'sass' after 16 s
[19:36:49] Starting subtask 'typescript'...
[19:36:49] [typescript] Using custom version: 2.0.3
[19:36:49] Finished subtask 'copyStaticAssets' after 16 s
[19:36:56] ==================[ Finished ]==================
Error - 'tslint' sub task errored after 16 s 
 Error in plugin 'gulp-cache'
Message:
    Cannot find module './h6'
Details:
    code: MODULE_NOT_FOUND
[19:36:56] Finished subtask 'typescript' after 7.63 s
[19:36:56] Starting subtask 'ts-npm-lint'...
[19:36:56] Finished subtask 'ts-npm-lint' after 112 ms
[19:36:57] Project hola-mundo version: 0.0.1
[19:36:57] Build tools version: 0.11.1
[19:36:57] Node version: v4.6.0
[19:36:57] Total duration: 57 s
[19:36:57] Task errors: 1
christo@mint18-VirtualBox ~/Code/HolaMundo $ 

```

**Comment by patmill** [comment] 2016-10-18 17:45
OK, thanks.  @nickpape-msft, @iclanton, @chakkaradeep - any ideas?  Note that this is running a linux build environment.

Is there another workaround similar to these - 
If you are using Ubuntu
You need to install compiler tools using the following command:
sudo apt-get install build-essential
If you are using fedora
You need to install compiler tools using the following command:
sudo yum install make automake gcc gcc-c++ kernel-devel

**Comment by cgronseth** [comment] 2016-10-18 17:52
Yeah, build-essential is installed because I tried to see if the compiled version of npm would work... but doesn't.
 
Anyway tried but same:

```
christo@mint18-VirtualBox ~/Code/HolaMundo $ sudo apt-get install build-essential
[sudo] password for christo: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version (12.1ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
christo@mint18-VirtualBox ~/Code/HolaMundo $ gulp serve
Build target: DEBUG
[19:48:33] Using gulpfile ~/Code/HolaMundo/gulpfile.js
[19:48:33] Starting gulp
[19:48:33] Starting 'serve'...
[19:48:33] Starting subtask 'pre-copy'...
[19:48:34] Finished subtask 'pre-copy' after 74 ms
[19:48:34] Starting subtask 'tslint'...
[19:48:34] Starting subtask 'copyStaticAssets'...
[19:48:34] Starting subtask 'sass'...
[19:48:35] Error - 'tslint' sub task errored after 1.98 s 
 Error in plugin 'gulp-cache'
Message:
    Cannot find module './h6'
Details:
    code: MODULE_NOT_FOUND
[. . .] 

```

**Comment by chakkaradeep** [comment] 2016-10-20 04:45
I don't think our packages use the rimraf package. @cgronseth can you confirm the fix in #144 did not work? Did you replace the tslint.config with this [one](https://gist.github.com/nickpape-msft/b3a0e0a4d64c029794eb4d2318d54308) and then try out?

Also, are you getting this error in a new project?

**Comment by patmill** [comment] 2016-10-20 04:52
rimraf is a dependency far down the stack I believe.  I haven't hit this myself, but it was mentioned by another person (@davros85) .  David - are you running a linux distro for your dev environment by any chance?

**Comment by davros85** [comment] 2016-10-20 06:58
Sorry I'm on Windows 10

**Comment by waldekmastykarz** [comment] 2016-10-21 07:17
@patmill I stumbled upon this issue as well, when running SPFx in a Docker container based on linux. Looking at the sp-tslint-rules package (@microsoft/sp-tslint-rules/lib/util
s/implicitRoles), it seems like H6 is the only rule written in uppercase. Renaming the file to lowercase fixes the bug.

**Comment by cgronseth** [comment] 2016-10-21 09:45
Hello, @chakkaradeep yes, I tried that first while seeking help for this error, but didn't work.

@waldekmastykarz Yes, just tried renaming all H6.* in my project folder and works perfectly, WorkBench up and running!

Thanks everybody for your help.

**Comment by chakkaradeep** [comment] 2016-10-25 00:56
@nickpape-msft can you look into this issues? Looks like we need fix this in the tslint package.

**Comment by iclanton** [comment] 2016-10-25 23:21
This will be fixed in the next drop. The a11y rules have been moved out of our package and into the [tslint-microsoft-contrib](https://github.com/Microsoft/tslint-microsoft-contrib/) package, and as part of that move, the root cause was fixed.

**Comment by iclanton** [comment] 2016-12-01 20:39
This should be fixed now. I'm going to close this issue. Please reopen if this happens again.

**Closed by iclanton** 2016-12-01 20:39 UTC
Labels: status:fixed-next-drop, status:tracked
