### ISSUE TITLE
Unable to browse the workbench when running SPFx project from docker container. 

### ISSUE THREAD

**Issue by frankchen76** [SharePoint/sp-dev-docs#3695] opened 2019-03-27 21:34 UTC
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
when use docker created image for SPFx1.8 deveopment, after we execute `docker run -it --rm --name spfx-mo --mount type=bind,source=c:/dockerprojects,destination=/usr/app/spfx -p 5432:5432 -p 4321:4321 -p 35729:35729 [image]:[SPFx1.8-Node8.15.0]` to start a container, we should be able to browser to https://localhost:4321/temp/workbench.html to start a local bench. When you browser to https://sposite/_layouts/15/workbench.aspx. the SPO workbench cannot pick up the web part you hosted from container. 
#### Observed Behavior
the browser always showed they cannot resolve  https://localhost:4321/temp/workbench.html. and spo workbench cannot load manifest file for web part. 
#### Steps to Reproduce
* create a Dockerfile to include the following
```
FROM node:8.15.0

EXPOSE 5432 4321 35729

RUN npm i -g gulp yo @microsoft/generator-sharepoint@1.8 @pnp/office365-cli

VOLUME /usr/app/spfx
WORKDIR /usr/app/spfx
RUN useradd --create-home --shell /bin/bash spfx && \
    usermod -aG sudo spfx && \
    chown -R spfx:spfx /usr/app/spfx

USER spfx

CMD /bin/bash
```
* run 'docker build -t imagefile . ' to create a docker image
* run 'docker run -it --rm --name spfx-mo --mount type=bind,source=c:/dockerprojects,destination=/usr/app/spfx -p 5432:5432 -p 4321:4321 -p 35729:35729 [imagefile]' to start a container. 
* run yo @microsoft/sharepoint to create spfx 1.8 project. 
* run 'gulp serve'
#### Submission Guidelines

@waldekmastykarz had his own docker repository and also mentioned walk around at his [know issue session](https://github.com/waldekmastykarz/docker-spfx#known-issues). I also created a [issues ](https://github.com/nodejs/docker-node/issues/1011)at nodejs/docker-node. it seems like they are questioning about if the process running on docker container is actually listening those ports. I am just wondering if this is a known issue from SPFX. if it's, any plan you can share with us?

**Comment by andrewconnell** [comment] 2019-03-30 10:34
Appears there's a PR in the @waldekmastykarz 's [repo](https://github.com/waldekmastykarz/docker-spfx/issues) that they are working on upgrading the image to support v1.8... might be best to [post your issue there](https://github.com/waldekmastykarz/docker-spfx/issues) as using Docker isn't the MSFT official way of developing SPFx...

**Comment by PopWarner** [comment] 2019-03-30 14:06
+1 to @andrewconnell.

@frankchen76, I can confirm, I'm experiencing the same issue you are. No doubt there will be further guidance that comes out from the community to best accomplish using SPFx 1.8 with Docker, but here is some info I was able to find while testing for you:

I got the exact same 'npm ERR! code ELIFECYCLE' error you received in your linked issue over at 'nodejs/docker-node'. In fact if you create another Docker image, removing the npm install of the SPFx modules and then simply execute 'npm install node-sass', it will still fail with the same error.

That being said, I was able to find an extremely less then elegant workaround that did work for me. In another windows partition, where I have node installed directly, I was able to scaffold out an SPFx 1.8 web part successfully. 

I then copied the "node_modules" folder from that partition, into my solution folder where my Docker Container SPFx solution was located. I had to then execute an "npm rebuild node-sass" and from there was able to perform a gulp serve or another "npm install" of another module and was able to proceed with normal development.

This is by no means a best practice work around. It could easily be considered a hacky coincidence and not one I would rely on long term, but it might work for you in the short term until the best option for Docker & SPFx 1.8 comes available?

As @andrewconnell  mentioned though, since using Docker isn't the official development pattern, posting the issue into Waldek's repo might be the best way to keep an eye on this. :)

**Comment by frankchen76** [comment] 2019-04-01 06:00
@PopWarner and @andrewconnell thanks for your guys comments. 
Based on what [Developing using Docker](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/team-based-development-on-sharepoint-framework#developing-using-docker) mentioned in
 [Team-based development on the SharePoint Framework](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/team-based-development-on-sharepoint-framework), the docker container is one of development environment approaches recommended by MSFT. I also tried SPFx 1.4 version running on docker with nodejs 6.11, it worked fine with same Docker for Windows. If there wasn't a change, it should be working for SPFx 1.8 and nodejs 8.x. As I mentioned in my question, even though @waldekmastykarz mentioned work around in his repro, I think we should be able to get clarification from MSFT if this is a designed change or not. I also raised this issue to nodejs/docker-node and was told that the issue might be caused by no listener inside the container. I hope someone from MSFT can clarify this. Thanks

**Comment by andrewconnell** [comment] 2019-04-01 10:16
@frankchen76 said:
> the docker container is one of development environment approaches recommended by MSFT

I think using the word *recommended* isn't accurate. There are options listed there, but as you can see in the docs, it redirects you off the MSFT docs to learn how to use Docker. This isn't a use case they test for or officially recommend. Their guidance & what they test for is to install the generator globally on your local environment.

@frankchen76 said:
> If there wasn't a change, it should be working for SPFx 1.8 and nodejs 8.x.

But clearly, something *did* change... it's not working :). No docker image is provided by Microsoft... the community is using the one created by @waldekmastykarz. As I said in my last response, this is something that appears others are hitting when you look at @waldekmastykarz's repo... so I'll reiterate it's more likely the best place to raise this question is over in his repo.

**Comment by andrewconnell** [comment] 2019-04-01 11:01
BTW, confirmed with @waldekmastykarz that posting issues specific to this docker image are more suited in the issue list in his repo... so I'll close this issue for now but recommend you post to his issue list linked above.

**Closed by andrewconnell** 2019-04-01 11:01 UTC
Labels: Needs: Author Feedback, area:framework, area:tooling
