### ISSUE TITLE
Publishing a new version of the sppkg doesn't take changes

### ISSUE THREAD

**Issue by shaipetel** [SharePoint/sp-dev-docs#550] opened 2017-04-17 21:56 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
I change the solution version in package-solution.json and build a new solution.
Had version 1.0.0.1 deployed to my catalog.
It had web part JSON that had the bundle point to my CDN file: "data-view-plus.1.0.0.1.js"
(I use teh solution version instead of the hash for the JS file).
Version 1.0.0.2 is pointing to "data-view-plus.1.0.0.2.js".

I dragged version 1.0.0.2 to replace 1.0.0.1 in the catalog, clicked replace.
Pages now sometimes load 1.0.0.1 and other times 1.0.0.2.
It is very random.

The only way to fix it, is to remove the package and add it to the catalog.
This problem ONLY happens when I replace an existing package.

I had mentioned it during the last dev kitchen and I was told this issue should be fixed, I can confirm it still happens to me now.

The web part is running from CDN on classic and on moden page with the same behavior.

Something appears to be broken in the update/replace feature, probably some logic trying to be efficient and only take changes - and somehow this change is being missed.

#### Observed Behavior
The replace process of a sppkg does not seem to pick up all changes from the package. It creates a strange situation where every refresh of the page I will get a different version loaded.

#### Steps to Reproduce
Publish web part to CDN, with these changes:
after running gulp --ship, and before running gulp package-solution --ship:
go to temp/deploy folder.
rename the bundle js file, remove the hash and replace it with the solution version number.

publish version 1.0.0.1
add a few web parts to your pages
publish version 1.0.0.2 by dragging it to the catalog and choosing "replace"
refresh those pages, or add the web part to new pages
--- you will notice, the CDN loads your 1.0.0.1 JS file most of the times, only some times your 1.0.0.2
to resolve the issue:
delete it from the catalog.
upload 1.0.0.2
--- you will notice now everything works properly.

**Comment by manishgarg1** [comment] 2017-05-01 15:09
@mcmynn83 ?

**Comment by mcmynn83** [comment] 2017-05-01 17:15
Hi Shai,
Couple of questions, a request, and some information:
Did you have the Trust Dialog pop up when replacing your solution?  This dialog actually sets a cookie (see below) which is needed to get the latest manifests... if you didn't have this dialog pop up there is no way you will have the cookie set.

Could you do me a favour and grab the SPRequestGuid from the response headers of both the working and non working versions if you see it happen again?

Just so you understand what we expect, here is the actual design of the feature.  When you replace a solution in the app catalog it will overwrite what is stored for the manifests.  However, we cache the manifests and will NOT update them for ~20 minutes.  To end users we deemed this delay acceptable, however, to the person who uploaded the solution, they probably want to verify that their updated solution is working so we place a cookie in their browser which tells the server not to use the cached values.  If you clear your cookies before 20 minutes is up you will go back to using the cached values (or conversely if somehow you don't get the cookie loaded).  Anyways, all this info was just so you understand what I'm trying to diagnose in your requests... one of 3 things is happening:
1.  You don't have the cookie (didn't get it, it got cleared, or it expired)
2.  Our cache is not updating
3.  Our logic with the cookie is not working

I believe the issue is most likely 1 since that would ensure that you see the trust dialog again (it is not trusted)... I will look into this either way, but just want to confirm you're not seeing some other bug.

Thanks,
Graham

**Comment by shaipetel** [comment] 2017-05-01 21:32
No, when doing the replace I don't see a trust dialog. Only a message confirming I want to replace the existing package/file.

So, it seems like it might be the cookie issue.

I can reproduce it anytime, it is no trouble at all. Simply drag a new package over an existing one. I am prompted to replace the file, and that's it. No trust dialog or any other dialog comes up.

I agree 20 minutes might be good for end-users, but you should probably mention it in the UI. Imagine an admin deploys a new package, see the bug is fixed. Tell his users to try it and they report it is still not fixed. <-- this right here will cause our support a huge headache!

For developers too, I am usually testing on 2-3 browsers at the same time. Setting a cookie on the one I used to upload the package will just confuse me as to why the fix was not applied to my other browsers...

I cannot say if it corrects itself for me after 20 minutes, I never tried to wait. I can only confirm one I upload and replace the package it doesn't take the changes.

**Comment by mcmynn83** [comment] 2017-05-01 21:39
Thanks for reporting the issue to us, I was able to repro it (should have responded earlier).  It is currently being worked on to actually have the cookie set properly.  As for the issue with multiple browsers and other users not seeing the fix right away, I have heard the feedback and we'll determine if a warning message is the best way to fix that or not.  Lastly, 20 minutes is the worst case scenario (basically it's a 20 minute window when that cache gets populated, if you happen to update at minute 1 you're going to wait a while, if it happened to be at minute 19 you will see the fix sooner. However, it's per front end machine, so over the course of 20 minutes you will slowly have al your front ends using the latest).

**Comment by sidjustsid** [comment] 2017-05-02 08:48
@shaipetel 
I am facing this issue when i delete the package and add a new package as well.
Could you tell me when this is working fine ? So that i will try at my End.

Many Thanks

**Comment by shaipetel** [comment] 2017-05-02 15:33
For me, if I first delete the package and then upload the new version I never had a problem. Even when not changing the version number.

Also noticed: If the package file name was changed, uploading it while still having the older file name in the catalog will take the new version and work properly.

So, the problem seems isolated for me to when the "replace existing file" prompt appears.

**Comment by mcmynn83** [comment] 2017-05-02 17:15
@shaipetel - you are correct about the scenarios you are seeing this... it is because any time the trust dialog pops up you get a cookie placed on your browser which tells the server to disable the cache for you for the next 20 minutes.  If you delete the package and add a new one the trust dialog pops up, same with if you upload the file with a different name.  

Just as an FYI - please don't upload a different version with a different name, you should use the same name.  We will be blocking different names for the same solutions soon (it just has not rolled out yet).

**Comment by shaipetel** [comment] 2017-05-02 23:22
@mcmynn83 Yeah - I wouldn't change the package name in production.
I only did it during my dev exploration, and honestly I was surprised it didn't block me from doing it.

I am checking all end-cases now so if/when we encounter them in production with our customers I will have a better understanding on how things work.

It is good to know you will be blocking same package with different file name soon.

**Comment by mcmynn83** [comment] 2017-07-25 22:42
Around next Wednesday a change should roll out preventing you from changing the package name.  Since the actual issue here (the trust dialog) is understood, I'm closing this issue.

**Closed by mcmynn83** 2017-07-25 22:42 UTC

**Comment by shaipetel** [comment] 2017-07-26 14:01
Hi @mcmynn83 , the issue with trust dialog is understood - what does that mean exactly? Will it be fixed?
I am still instructing everyone I know not to override packages but to delete and upload.

Thanks.

**Comment by mcmynn83** [comment] 2017-07-26 16:09
@shaipetel - Sorry, I meant that it has been fixed ages ago, close to the time you opened this up.  When you upload a new version with the same file name the trust dialog should appear again.  You should then get the option to either deploy (which rolls out the new version), or cancel (which will leave the old version deployed).  Either way, you will get the cookie put on your machine.  If you are not seeing this behavior it is a bug and I'd like to hear about it.  However, deleting and reuploading is completely unnecessary and actually causes a short outage for your users (deleting will make the webparts not work until you upload the new package).

Please let me know if you are not seeing this behavior.

Thanks,
Graham

**Comment by shaipetel** [comment] 2017-07-26 16:11
Thanks, I will try. That is great news.
