### ISSUE TITLE
Orchestration Aborted Error while doing gulp build

### ISSUE THREAD

**Issue by ymihir** [SharePoint/sp-dev-docs#4701] opened 2019-10-01 10:58 UTC
I am getting below error when I do `gulp build` command. I took this solution from my colleague and did `npm install`. What is the reason for this?
![image](https://user-images.githubusercontent.com/7568187/65956593-5816a700-e410-11e9-9d5b-505e8074500e.png)

**Comment by andrewconnell** [comment] 2019-10-01 12:39
In addition to the above, is this a clean/new project with no changes? Share your **package.json**? Not enough information provided to help much at this point...

**Comment by ymihir** [comment] 2019-10-01 14:05
@andrewconnell below is my package.json file.
This solution is for SP2019.
```
{
  "name": "aamvasp-fx-solutions-v-1-0",
  "version": "0.0.1",
  "private": true,
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@microsoft/sp-core-library": "1.4.0",
    "@microsoft/sp-lodash-subset": "1.4.0",
    "@microsoft/sp-office-ui-fabric-core": "1.4.0",
    "@microsoft/sp-webpart-base": "1.4.0",
    "@types/es6-promise": "0.0.33",
    "@types/react": "15.6.6",
    "@types/react-dom": "15.5.6",
    "@types/webpack-env": ">=1.12.1 <1.14.0",
    "react": "15.6.2",
    "react-awesome-modal": "^2.0.5",
    "react-dom": "15.6.2",
    "tippy.js": "^4.3.5"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "1.4.1",
    "@microsoft/sp-module-interfaces": "1.4.1",
    "@microsoft/sp-webpart-workbench": "1.4.1",
    "gulp": "~3.9.1",
    "@types/chai": ">=3.4.34 <3.6.0",
    "@types/mocha": ">=2.2.33 <2.6.0",
    "ajv": "~5.2.2"
  },
  "resolutions": {
    "@types/react": "16.4.2"
  }
}

```
Below with `npm list -g --depth=0`
![image](https://user-images.githubusercontent.com/7568187/65969560-991bb500-e42a-11e9-83a8-baf986c7c072.png)

**Comment by ymihir** [comment] 2019-10-01 15:49
@andrewconnell I have added my solution to visual studio online. If I download that package and run the 'npm i` then `gulp build` then it is throwing this error.

**Comment by andrewconnell** [comment] 2019-10-01 15:58
Can't tell what the issue is based on the provided information. Clearly something to do with TypeScript... that could be because of dependencies. 

Have you created a brand new SPFx project for SP2019, with no edits, and tried building it? If that works, it's something wrong with your project. If it doesn't work, it's something wrong with your workstation.

I notice you're running old versions of the following

- @microsoft/generator-sharepoint (but upgrading this won't make much of a difference)
- Node (you're on v8... you should be able to use Node v10, the current LTS version even though you're using SPFx v1.4.1) <<< this could very well be the root of the issue... 
- npm (full major version behind)

**Comment by ymihir** [comment] 2019-10-01 16:04
Strange thing is I have created this solution in my machine and worked perfectly. Then I have pushed this to Visual Studio online. I have shared this solution to client. Client is trying to build from his end which is failing. Now I have downloaded, from VS online to another folder then executed `npm i ` then `gulp build` which is giving error, but same solution i have pushed from another folder which is working.

**Comment by andrewconnell** [comment] 2019-10-01 16:58
Well, something is clearly different between the two projects on your machine if one works & one doesn't. Use a diff tool to examine the two **package.json** files, examine the lock files for the package manager you use, use a diff tool to do a deep comparison of the two folders, etc ... something is definitely different.

I'm going to close this as resolved as you have one working so there's action to take...

**Closed by andrewconnell** 2019-10-01 16:58 UTC
Labels: Needs: Attention :wave:, area:tooling
