### ISSUE TITLE
People search API does not work on SharePoint Online anymore

### ISSUE THREAD

**Issue by ltdu** [SharePoint/sp-dev-docs#9500] opened 2024-02-05 10:42 UTC
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

SharePoint REST API

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

any browser

### Describe the bug / error

We have developed several SPFx based web parts, which retrieve user information from SharePoint User Profile Services (UPS) using search API (we have mapped some managed search properties to UPS properties)

It used to work without problem for long time, however, now none of the search queries return any results. They do not return error messages either. Just structure with 0 result rows.

We use sourceId=```B09A7990-05EA-4AF9-81EF-EDFAB16C4E31```

### Steps to reproduce

You can try simple REST API (just search for some employee in your organization):

```
https://___.sharepoint.com/_api/search/query?querytext='user'&sourceid='b09a7990-05ea-4af9-81ef-edfab16c4e31'
```

### Expected behavior

We expect people search results to be returned. As they used to.

**Comment by Rafaelki** [comment] 2024-02-05 12:04
This is a very critical issue for us as well, and it affects every one of our clients.

**Comment by vspinelli** [comment] 2024-02-05 12:14
We have the same issue on several customers environments. Due to this issue, many of our production solutions were stopped working. We need a quick solution.
Thanks.

**Comment by ltdu** [comment] 2024-02-05 12:24
This could be related to https://admin.microsoft.com/#/servicehealth/:/alerts/SP709902

**Comment by benjacernuda** [comment] 2024-02-05 13:22
Same issue here affecting internal environments and all of our clients

**Comment by VesaJuvonen** [comment] 2024-02-08 08:42
Thanks everyone for your input on the issue. Great to see the discussion and also sharing the latest status when it was fixed. This was an unfortunate regression which has been fixed. 

Closing issue as issue has been resolved.

**Closed by VesaJuvonen** 2024-02-08 08:42 UTC
Labels: type:bug-suspected, status:fixed, area:search
