### ISSUE TITLE
Application customizer breaks on events pages in communication sites

### ISSUE THREAD

**Issue by estruyf** [SharePoint/sp-dev-docs#1263] opened 2018-01-23 16:04 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When creating an application customizer that shows a header or footer, the expected behavior should be that it is loaded on every modern page.

#### Observed Behavior

It appears that on communication sites, when you create, edit, or display an event. The application customizer is not rendered. When opening the browser console, you get the following error:

```
sp-pages-assembly_en-us_18b206dbf5ea8a9da3221367da049861.js:547 

Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined
    at e._scrollEventHandler (sp-pages-assembly_en-us_18b206dbf5ea8a9da3221367da049861.js:547)
    at e (sp-pages-assembly_en-us_18b206dbf5ea8a9da3221367da049861.js:312)
    at u (sp-pages-assembly_en-us_18b206dbf5ea8a9da3221367da049861.js:312)
    at e.s (sp-pages-assembly_en-us_18b206dbf5ea8a9da3221367da049861.js:312)
```

When you refresh the page, the error is gone and your app. custom. appears again.

Here you can see the process of what happens:

![large gif 1080x844](https://user-images.githubusercontent.com/2900833/35286140-792ae640-005f-11e8-9b07-3571eaa916c8.gif)

#### Steps to Reproduce

I tried this by following the guide: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/using-page-placeholder-with-extensions

**Comment by patrickabel** [comment] 2018-03-12 19:00
@VesaJuvonen @estruyf any status update on resolving this bug? I'm running into this issue as well.

**Comment by mpasarin** [comment] 2018-03-19 22:49
This issue is a duplicate of #1042 
I'll close this issue so we can track it on a single issue.

**Closed by mpasarin** 2018-03-19 22:49 UTC
Labels: area:framework, status:duplicate, status:tracked, type:bug
