### ISSUE TITLE
SP2016 SPFx deployed webparts not showing in Apps you can add

### ISSUE THREAD

**Issue by christopher-walker** [SharePoint/sp-dev-docs#1016] opened 2017-11-02 12:45 UTC
[ ] Question
[ ] Typo
[?] Bug
[ ] Additional article idea

I have created some webparts for SP2016 using the "@microsoft/generator-sharepoint@1.0.2" compiled the webpart (using --ship) uploaded to the package to my app catalog. I now want to add my webpart to a page but when I go to add an app, it does not show up in any of my site collections. I also tried creating a developer site with no luck.

I originally installed the September 2017 update have now updated to October 2017.

Having looked through the ULS logs I cant find any related errors, any advice on where to look to resolve this would be super.

Thanks

Chris

**Comment by christopher-walker** [comment] 2017-11-02 15:21
Forgot to mention I have also ensured that users have permissions on both the site collection they are adding the application and the site collection hosting the application catalogue.

I have noticed something strange with the application catalogue though. The column that should have the title "deployed" actually has its resource file name (so it seems that the resource file is missing). I have checked this on my test environment, development environment and production environments and it seems to be consistent (showing the resource file name). I have therefore deleted the app catalogue on my development image and created a new one ... I have the same issue.

**Comment by christopher-walker** [comment] 2017-11-05 22:30
Ok for anyone who is interested I finally managed to get this going and I suspect that there is an issue with SharePoint 2016 September 2017 CU (FP2). To make use of the role improvements I installed SharePoint then the Sep 2017 CU then configured SharePoint all the service apps and created the app catalogue deployed the app and tried to add it at site level ... no luck just the before mentioned error (previous post). Here are all the steps I did:

Ok,
 I think I have a solution to my problem at least and if true it points to an issue with SharePoint 2016 FP2 (September 2017 CU).
 My original installs were as follows:
Install SharePoint 2017
Install FP2
Run the installation wizard setup SharePoint
Configure all the service applications
Configure apps
Create the app catalog
Add the app to the app catalog
Try to add the app site level
… App does not appear to see an error in the ULS :

No matter what I tried I simply could not deploy those applications.
What I did:
Removed SharePoint 2016 and deleted all databases
Install SharePoint 2017
Run the installation wizard setup SharePoint
Configure all the service applications
Configure apps
Create the app catalog
Install FP2
Add the app to the app catalog
Try to add the app site level ….
The app was available
It would be good if someone at Microsoft could test this and confirm that it is an issue or not, in my Quality and Production environments I need to deploy with at least FP1 level to so that I can make use of the multi-roles, so will be testing that this week. Hopefully, it does not cause the same issue as FP2.

**Comment by Ofer-Gal** [comment] 2017-11-08 18:38
Install SharePoint 2017? where did you find it to install?

**Comment by christopher-walker** [comment] 2017-11-08 19:02
Typo ... SharePoint 2016,

Also, I found the issue I didn't realise that you **must** install the "language dependent fixes", I made the assumption that this was only required if you had a language pack installed. However, this is not so.

Once I had installed the language dependent fixes I needed to delete the app catalog and create a new one.

**Comment by Ofer-Gal** [comment] 2017-11-08 19:25
Were you able to deploy the example from https://docs.microsoft.com/en-us/sharepoint/dev/spfx/sharepoint-2016-support ? 
I have trouble with this one.
Knows any good example to follow?

**Comment by christopher-walker** [comment] 2017-11-08 19:42
Is that the HelloWorld one? ... yes, I managed to deploy that one, however, i built it with version 1.0.2 of the SharePoint generator. Apparently, the 1.3.4 one works also but I haven't tried that.

**Comment by moyali** [comment] 2017-11-28 18:32
Hello @christopher-walker,

I'm glad the issue is resolved. Thanks for keeping the thread updated with your progress. I'm closing the issue. Feel free to reopen if the original issue comes back.

Thanks

**Closed by moyali** 2017-11-28 18:32 UTC

**Comment by christopher-walker** [comment] 2019-01-08 09:34
You need to install the latest available language update then. So in your case, you should ensure that the October 2018 language dependent update is installed:
https://blogs.technet.microsoft.com/stefan_gossner/2018/10/09/october-2018-cu-for-sharepoint-server-2016-is-available-for-download/

**Comment by kbkotresh** [comment] 2019-01-08 11:48
> You need to install the latest available language update then. So in your case, you should ensure that the October 2018 language dependent update is installed:
> https://blogs.technet.microsoft.com/stefan_gossner/2018/10/09/october-2018-cu-for-sharepoint-server-2016-is-available-for-download/
hi 
Thanks  for you reply, 
Currently we have installed DEC 2018 CU updates , Which do not have language Dependent files. 
If I install the Oct 2018 Cu updates Language dependent , Will be there any impact on the existing configuration? Please suggest

**Comment by christopher-walker** [comment] 2019-01-08 12:08
You need to have the latest language pack that goes with the CU. But dont trust me :) trust Stefan Gossner see the comment at the bottom of the page:

```
Koen Zomers
December 2, 2018 at 2:03 pm
Sanity check on this one Stefan: to install a NEW SharePoint 2016 farm at this moment and get it fully up to date, I would install the October 2018 language dependent update and the November 2018 language independent update, can you confirm?

Stefan Goßner
December 2, 2018 at 10:04 pm
Hi Koen,
that is correct.
Cheers,
Stefan
```

https://blogs.technet.microsoft.com/stefan_gossner/2018/11/13/november-2018-cu-for-sharepoint-server-2016-is-available-for-download/

**Comment by kbkotresh** [comment] 2019-01-10 13:31
> > You need to install the latest available language update then. So in your case, you should ensure that the October 2018 language dependent update is installed:
> > https://blogs.technet.microsoft.com/stefan_gossner/2018/10/09/october-2018-cu-for-sharepoint-server-2016-is-available-for-download/
> > hi
> > Thanks  for you reply,
> > Currently we have installed DEC 2018 CU updates , Which do not have language Dependent files.
> > If I install the Oct 2018 Cu updates Language dependent , Will be there any impact on the existing configuration? Please suggest

I have resolved this issue by Updating the Language Dependent Fixed from October 2018 updates.
and delete and recreate the App Catalog 
This worked for me in SharePoint 2016 On premise environment.
