### ISSUE TITLE
Extension - Application Customizer footer is rendered incorrectly on mobile (SP App and browsers on mobile)

### ISSUE THREAD

**Issue by ahessami** [SharePoint/sp-dev-docs#5439] opened 2020-03-10 17:33 UTC
## Category

- [x] Bug

## Describe the bug

This bug is about the bottom placeholder that is made available through the Application Customizer Extension.  The bottom placeholder does not remain at the bottom of the page when the page is scrolled on a mobile device.  This issue occurs on the SharePoint mobile app, mobile browsers, and when debugging on a desktop using the browser's dev tools and using the toggle device toolbar option to mimic a mobile device.

Below is a screenshot of the issue along with a gif:

![bottom-placeholder-bug](https://user-images.githubusercontent.com/3638514/76336160-9b304c80-62c3-11ea-911d-dcc04e14f76f.gif)

![image](https://user-images.githubusercontent.com/3638514/76336257-bb600b80-62c3-11ea-8d7d-b3fe4bbd79c2.png)

 
## Steps to reproduce

Essentially, I was able to reproduce this issue by going through the SPFx Extension HelloWorld articles thinking at first the issue was with my own custom Extension.. but actually the issue is also prevalent with a simple extension made using the official Microsoft articles.

1. Followed these two articles on how to create a new Application Customizer extension:
a. https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/build-a-hello-world-extension
b. https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/using-page-placeholder-with-extensions

2. Bundled, and built the package.  Then deployed to my development tenant's app catalog.

3. Created a modern team site and added this extension to it.

4. Once the app is installed on the team site, go to the home page and you'll see that the top and bottom placeholder content is showing properly on the desktop.

![image](https://user-images.githubusercontent.com/3638514/76338679-062f5280-62c7-11ea-84af-5d545179be97.png)

5. Open your browser's developer tools, and toggle device toolbar to emulate the page using a mobile device and refresh the page.  It's important to refresh the page because now the SharePoint page will recognize your browser as a mobile device and render the page as it would on an actual mobile device.

6.  Upon refresh, you'll notice that the bottom placeholder is now gone.  However, the place holder is there but is hidden behind the page content.. see screen shot below:

![image](https://user-images.githubusercontent.com/3638514/76339086-a1c0c300-62c7-11ea-9797-ac7e1614d791.png)

7. You'll need to add a z-index to the div container for the bottom placeholder to have it be shown on the page:

![image](https://user-images.githubusercontent.com/3638514/76339245-cfa60780-62c7-11ea-8c90-b7ccbea6e684.png)

8.  Even if you navigate between pages, the issue is still there... the bottom placeholder does not remain at the bottom of the page when scroll the page.

  

## Expected behavior

The expected behavior should be the bottom placeholder being positioned at the bottom of the page instead of in the middle of the page when scrolling on a mobile device.

### Additional context

Links to similar bugs that were reported before but were marked as solved can be found below: 
https://github.com/SharePoint/sp-dev-docs/issues/4163
https://github.com/SharePoint/sp-dev-docs/issues/2257

Here is what I noticed when the page is rendered for a mobile device.  The "article" html element that wraps the content of the page is missing an "overflow-y" css attribute which it's desktop counter part has... see below gifs:

![bottom-placeholder-bug-fix-questionmark](https://user-images.githubusercontent.com/3638514/76340871-404e2380-62ca-11ea-8ace-8f9de88b0f97.gif)

Or add the "overflow-y:auto" attribute to the inner div within the "article" html element like the desktop version:

![bottom-placeholder-bug-fix-questionmark2](https://user-images.githubusercontent.com/3638514/76341144-a20e8d80-62ca-11ea-919b-aaa1f4bb6490.gif)

Here is how the article container inner div looks like on desktop:

![bottom-placeholder-desktop](https://user-images.githubusercontent.com/3638514/76341561-3a0c7700-62cb-11ea-92c7-f9dc2b916442.gif)

I'd rather not deploy my own CSS hack and instead your team at Microsoft could fix this issue please.  Thanks!

**Comment by rayanvga** [comment] 2020-03-12 10:33
Observing the same issue here. Even the background color is not being considered for me.

**Comment by rayanvga** [comment] 2020-03-23 08:14
Any update on this issue? 

We've fixed this for now using position: fixed. However, some update on SPO last weekend has broken something else now. Would prefer to see this fix coming from Microsoft rather than we making adjustments in our solution.

**Comment by corriespondent** [comment] 2020-03-25 22:23
We are noticing this issue as well. 

In desktop, this div has data-is-scrollable="true" etc.:
![image](https://user-images.githubusercontent.com/23064475/77591083-75eb3300-6eac-11ea-98ca-54644b3e1bc3.png)

But in mobile (and this works in Chrome's responsive mobile view mode), the <div> has no classes or attributes.
![image](https://user-images.githubusercontent.com/23064475/77591016-53f1b080-6eac-11ea-98b8-bb9e71fe1db6.png)

**Comment by c-eiser13** [comment] 2020-04-06 14:21
We are seeing the same issue with footers on mobile devices in 3 tenants I've tested. I created a new 1.10 project to verify it was not something else going on with a long standing project we have been using a footer in. 

![footer1](https://user-images.githubusercontent.com/42096464/78568164-537be280-77e7-11ea-88d0-a4932580e83f.PNG)

When switched to mobile, after refresh, issue occurs:

![footer2](https://user-images.githubusercontent.com/42096464/78568537-dd2bb000-77e7-11ea-9581-075a91ac6392.png)

As others have mentioned, adding a z-index to the bottom placeholder makes it visible, but still out of place with scrolling.

![footer3](https://user-images.githubusercontent.com/42096464/78568408-b1a8c580-77e7-11ea-8385-41b15a622669.PNG)

**Comment by atripathi2020** [comment] 2020-04-12 12:40
Hi,

Any update on this issue. 

Or anyone have workaround for this?

**Comment by atripathi2020** [comment] 2020-04-12 12:41
> Any update on this issue?
> 
> We've fixed this for now using position: fixed. However, some update on SPO last weekend has broken something else now. Would prefer to see this fix coming from Microsoft rather than we making adjustments in our solution.

what was the workaround for this?

**Comment by rayanvga** [comment] 2020-04-12 12:45
@atripathi2020 We've done the same thing for now on our production. But `position :fixed;` makes the bottom part of the scrollbar and some out of the box items hidden.

Still waiting for a fix on this issue.

@VesaJuvonen Thoughts, please? This issue is making it difficult to use the footer at all since it breaks on mobile devices.

**Comment by rayanvga** [comment] 2020-04-28 15:32
Do you have any update on this issue @andrewconnell ?

**Comment by JamesHForsytheIV** [comment] 2020-06-22 13:31
Is there any update or timeline on this issue.  After much development and refinement we are finally getting ready to launch our portal, this will cause us to have to reevaluate the footer?

**Comment by atripathi2020** [comment] 2020-07-16 01:11
Hi All,

anyone have any workaround solution for this issue?

**Comment by c-eiser13** [comment] 2020-07-16 14:22
@atripathi2020 I noticed yesterday in 2 of 3 tenants I use, the footer is working properly. All 3 tenants are set to first release and are all in same region, so not sure why one is not yet fixed.

**Comment by AJIXuMuK** [comment] 2021-09-07 14:52
Can't reproduce on my end.
Is that still an issue @ahessami  @atripathi2020 ?

**Comment by corriespondent** [comment] 2021-09-07 15:26
@AJIXuMuK Just checked our tenants again and the issue seems to be resolved!

**Comment by c-eiser13** [comment] 2021-09-07 20:28
@AJIXuMuK it is working properly on our end as well.

**Comment by AJIXuMuK** [comment] 2021-09-07 20:39
Thank you for the confirmation @corriespondent and @c-eiser13!
I am closing this one as fixed.

**Closed by AJIXuMuK** 2021-09-07 20:39 UTC
Labels: type:bug-suspected, area:spfx-extensions
