### ISSUE TITLE
ListViewCommand: not updated when list changes 

### ISSUE THREAD

**Issue by henningeiben** [SharePoint/sp-dev-docs#5335] opened 2020-02-12 20:47 UTC
## Category

- [x] Bug

## Describe the bug

When I'm switching between lists neither the `onListViewUpdated` nor the `onInit` methodes get executed.

## Steps to reproduce

1. create a new commandset
2. log the `onInit` as well as the `onListViewUpdated` method execution
3. switch to another list/library
4. see no logging of either method execution

## Expected behavior

I would expect both methods to be fired when switching lists, but at least the `onListViewUpdated` 
 method.
> **DELETE THIS LINE BEFORE SUBMITTING** - Provide clear & concise description of what you expected to happen.

## Developer environment

- OS: Windows 10
- Browser(s): Chrome v80
- Tooling:SPFx v1.9.1

**Comment by andrewconnell** [comment] 2020-02-13 11:08
There are [multiple open issues](https://github.com/SharePoint/sp-dev-docs/issues?q=is%3Aissue+is%3Aopen+label%3A%22Needs%3A+Triage+%3Amag%3A%22) related to the `onListViewUpdated` event... 

This appears to be a dupe of #4882...

**Comment by henningeiben** [comment] 2020-02-13 19:59
woohoo - there is a lot of issues open around this topic - what's the best way to stay up-to-date with what's happening around this issue? I would raise some kind of "+1" but I'm uncertain on how to express that - so opening (yet) another issue to raise awareness that this is a serious blocking issues ...

**Comment by andrewconnell** [comment] 2020-02-13 20:35
@henningeiben I suspect that response means you agree... so I'll tag this as a dupe.

To monitor issues, use the **notifications** option to subscribe to updates to issues. This is in the right-hand column under the labels. Just go to that issue and subscribe to get email updates.

![image](https://user-images.githubusercontent.com/2068657/74475996-830d0f00-4e76-11ea-9a3d-59aa7f1fca8b.png)

**Closed** 2020-02-13 20:36 UTC
Labels: area:spfx-extensions, status:duplicate
