### ISSUE TITLE
Command set for custom library in subsite

### ISSUE THREAD

**Issue by ccasas87** [SharePoint/sp-dev-docs#1168] opened 2017-12-20 10:02 UTC
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [X] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Command set in production enviroment should appear in custom document library "Invoices" after it has been installed and registered. This library is in subiste.
This command set should show some logs in the browser console, telling the developer if the library is or is not named "Invoices". If it is, it shows in the command bar and users can use it.

#### Observed Behavior
1. After installed in a site collection, any other library (like "Documents") shows log traces in the browser console that the current library is not "Invoices". That is an expected behavior.
2. After registration of command set as a custom action for the "Invoices" library, the command set doesn't show in the library, but apparently it loads according to the console log trace: "**Client-side host application loaded on SPO app**"
3. In the console appears warnings/errors after the mentioned log trace:
![image](https://user-images.githubusercontent.com/26117194/34201398-a3a3f41c-e574-11e7-9b13-cf9eb02ceac4.png)
![image](https://user-images.githubusercontent.com/26117194/34201407-abf752ee-e574-11e7-998b-e2c81e6c8385.png)
![image](https://user-images.githubusercontent.com/26117194/34201414-b146d382-e574-11e7-9b30-21324f95adac.png)

#### Steps to Reproduce
1. Follow SPFx Extension tutorial to create a command set. 
2. `"skipFeatureDeployment": false` was used in package-solution.json
3. in elements.xml, the RegistrationId was changed to "101" to target document libraries.
4. Follow the turorials that include testing the local hosted extension, SharePoint hosted and Office 365 CDN hosted extension steps. 
2. Install command set extension package in site collection (Site contents > Add app)
3. Register the command set in custom document library using the following script:
`$credentials = Get-Credential`
`Connect-PnPOnline "https://domain.sharepoint.com/sites/sitecol/subsite" -Credentials $credentials`
`$context = Get-PnPContext`
`$web = Get-PnPWeb`
`$list = $web.Lists.GetByTitle("DocumentLibraryName")`
`$context.Load($list)`
`Execute-PnPQuery`
`$ca = $list.UserCustomActions.Add()`
`$ca.ClientSideComponentId = "clientsidecomponentid"`
`$ca.Location = "ClientSideExtension.ListViewCommandSet"`
`$ca.Name = "CommandSetName"`
`$ca.Title = "CommandSetName"`
`$ca.Description = "Command Set Description"`
`$ca.Update()`
`Execute-PnPQuery`
4. Check log traces on desired document library. using browser console. It shows errors and command set doesn't appear in command bar

**Comment by mpasarin** [comment] 2017-12-20 12:33
Hola @ccasas87 ,
It seems the command set is not loading properly. Could you can press Ctrl+F12 in the page to open the Trace log? Please copy here any errors you may be seeing there. Also, double check that the manifest for your command set shows in the Manifests tab.

**Comment by ccasas87** [comment] 2017-12-20 12:53
> Hola @ccasas87 ,
It seems the command set is not loading properly. Could you can press Ctrl+F12 in the page to open the Trace log? Please copy here any errors you may be seeing there. Also, double check that the manifest for your command set shows in the Manifests tab.

Hi  @mpasarin ,
The pictures I posted captured the trace log you are asking me.

Though, I could finally make it work. But it's quite weird.

I did the following:
1. Installed extension app in site collection https://domain.sharepoint.com/sites/sitecol, and check on any document library to see the log traces. These appeared telling me that that library is not "Invoices". So far, that's okay.
2. Installed extension app in a subsite, child of the site collection I installed the app previously: https://domain.sharepoint.com/sites/sitecol/subsite1. It now appears in my document library "Invoices" (https://domain.sharepoint.com/sites/sitecol/subsite1/Invoices) correctly and works just fine.

My doubt here is if the steps I followed are correct... I remember when I tried to install the extension app in a subsite it wouldn't allow me to do it, but now I could do it (previously installing it in the parent site).

If you or someone knows if it is actually necessary to install the extension app to the parent site so it could work in child subsites (installing also the same app), then it's probably that the documentation may need an update regarding this fact.

**Comment by ccasas87** [comment] 2017-12-20 14:26
I have tried again installing the extension app only in the subsite and it was successfully installed and also worked well showing in the document library, without the need to install it in the parent site.

Thanks a lot for the attention!
Even though I don't know what I was doing wrong, it seems to work now. I will stick to the steps above mentioned and the script for the registration only and not any other scripts I've found in the way... Hopefully I won't have any other issue, and if so I will share it with you :)

**Comment by mpasarin** [comment] 2017-12-20 14:45
I'm glad you got the problem solved.
The app needs to be installed in the same site that it's used. It is not necessary that it is installed in the root site though.
An alternative to that is to use tenant-wide deployment so all the extensions are available. In that case you just need to add the custom actions manually to the lists where you want to use the extension.

For the logs, Ctrl+F12 (as opposed to just F12) opens a different area where we store the trace logs for SPFx, those can be very verbose and they are not logged in the console to avoid noise, but sometimes they can help debug these problems.

As the problem is solved by installing the app in the subsite, I will close the issue.

**Closed by mpasarin** 2017-12-20 14:45 UTC

**Comment by ccasas87** [comment] 2017-12-20 14:59
@mpasarin ,

Oh I get it. I've just tried Ctrl+F12 to see the logs you were talking about. I didn't know about this option :) 
Next time I will look at those too for more information.
Thanks a lot!
