### ISSUE TITLE
Property 'microsoftTeams' does not exist on type 'WebPartContext'.

### ISSUE THREAD

**Issue by labbruzzesi** [SharePoint/sp-dev-docs#3845] opened 2019-04-26 01:34 UTC
I have SPFX 1.8, and when I build this project I get the error in the subject line

When I look in 'node_modules\@microsoft\sp-webpart-base\dist\index-internal.d.ts' I see the following line (instead of a declaration for 'microsoftteams')

/* Excluded from this release type: microsoftTeams */

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4521ae6c-2ac6-8898-4731-0a5a50349d76
* Version Independent ID: 49edacf9-9538-079b-24ab-3ce17017ba77
* Content: [Building Microsoft Teams tab using SharePoint Framework - Tutorial](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab#feedback)
* Content Source: [docs/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Languafe** [comment] 2019-04-26 10:53
Same error seen with SPFX 1.8.1

**Comment by Languafe** [comment] 2019-04-26 10:58
Duplicate of #3826

**Comment by patmill** [comment] 2019-04-29 20:56
Yup.  I'll close this one.  Temp workaround is in the duplicate, but a fix will be coming shortly.

**Closed by patmill** 2019-04-29 20:56 UTC
Labels: Needs: Triage :mag:
