### ISSUE TITLE
yo @microsoft/sharepoint installs office-ui-fabric-react-0.69.0

### ISSUE THREAD

**Issue by ujavai2s** [SharePoint/sp-dev-docs#422] opened 2017-02-12 21:42 UTC
Dear all,

I  am using command yo @microsoft/sharepoint to create webpart, which installs office-ui-fabric-react package version  0.69.0. But office-ui-fabric-react package version 0.69.0 is not a latest version. But we need version at least 1.20.0. Is it possible to get latest version of office.ui-fabric react with sahrepoint framework?

Regards

Umer Javaid

**Comment by chakkaradeep** [comment] 2017-02-13 04:34
Please see this issue #384 

Due to SharePoint adopting the Office UI Fabric React to the core, right now we recommend running the version that ships with SPFx. As you know, Office UI Fabric React and Office UI Fabric are independant projects with different roadmaps. However, SPFx & SharePoint depends on specific Fabric versions that is in sync with SharePoint Online which is what you get with the Yeoman generator. We will be updating the generator regularly if we do up the dependant versions.

**Comment by chakkaradeep** [comment] 2017-02-13 06:53
I have updated the doc with the right guidance for the SharePoint Framework preview with this PR #424 .

Thanks!

**Comment by amishra0909** [comment] 2017-05-09 01:22
As @chakkaradeep mentioned this is by design and the right guidance is provided in the doc, I am closing this issue.

**Closed by amishra0909** 2017-05-09 01:22 UTC
