### ISSUE TITLE
SyntaxError: Unexpected token =

### ISSUE THREAD

**Issue by mores** [SharePoint/sp-dev-docs#1583] opened 2018-04-03 19:49 UTC
$ yo @microsoft/sharepoint
/usr/local/lib/node_modules/@microsoft/generator-sharepoint/lib/common/BaseGenerator.js:65
    writing(shouldCopy = true) {
                       ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/@microsoft/generator-sharepoint/lib/generators/app/index.js:7:25)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c25a90e-829c-b436-d8ab-f9c010588ee1
* Version Independent ID: 768fa9a1-2375-fb5a-be58-cb66320cc789
* Content: [Build your first SharePoint client-side web part (Hello World part 1)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part)
* Content Source: [docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by mores** [comment] 2018-04-03 20:16
Upgrading nodejs to version 8 resolved this issue.
Is there a way to check for minimum version ?

**Comment by VesaJuvonen** [comment] 2018-04-04 05:55
This issue seems to be caused by Yeoman, which is used for the project scaffolding, but we do not control how it checks the versions on the SharePoint side, as it's 3rd party tooling. Good that you thought got this resolved, so closing this issue.

**Closed by VesaJuvonen** 2018-04-04 05:55 UTC
Labels: area:docs
