### ISSUE TITLE
Field Customizer: Field Customizer can't be applied to Name column in Document Library

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-docs#1207] opened 2018-01-05 20:14 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Field Customizer can be applied to Name column in Document Library

#### Observed Behavior
Field Customizer can't be applied to Name column in Document Library

#### Steps to Reproduce

- Create simple Field Customizer
- try to apply it to the `FileLeafRef` or `LinkFilename` field in any document library with CSOM/JSOM/REST:
```
var ctx = new ClientContext("https://contoso.sharepoint.com");
ctx.Credentials = new SharePointOnlineCredentials(username, password);
var web = ctx.Web;
var docLib = web.Lists.GetByTitle("Documents");
var field = docLib.Fields.GetByInternalNameOrTitle("FileLeafRef");
ctx.Load(field);
ctx.ExecuteQuery();

if (field.ClientSideComponentId != clientSideComponentId)
{
  field.ClientSideComponentId = clientSideComponentId;
  field.Update();
  ctx.ExecuteQuery();
}
```
- **no luck**

**Note:** the customizer is applied if you use debug url to apply it.

**Comment by mcmynn83** [comment] 2018-01-18 18:51
@AJIXuMuK - This is by design as the name field is marked as a nocustomize field.  If you believe you need the name field to have a field customizer on it please open up a new request in user voice to request this feature.

**Closed by mcmynn83** 2018-01-18 18:51 UTC
Labels: area:framework, type:bug

**Comment by AJIXuMuK** [comment] 2018-01-18 20:32
@mcmynn83 it is so weird!
1. If it is noncustomizable why Column Formatting **can** be applied and Field Customizer - no?
2. What is so special in it? Why Title column in list is customizable but this one - not?
3. Why the field customizer **is applied** in debug mode?

Why did you actually decide to do it noncustomizable?

**Comment by wobba** [comment] 2018-07-31 09:08
@mcmynn83 `FileLeafRef` is not marked as neither not-deleteable, read-only, nor sealed.

So I don't see why we should not be able to have a field customizer working on this field - as it works fine in debug mode. `Name` is read-only, but it's `FileLeafRef` which is used as `Name` in a library view.

**Comment by JLRishe** [comment] 2018-07-31 11:12
@AJIXuMuK  This looks like it might be a duplicate of my issue #906 and it seems like the situation has changed since. I am able to apply a field customizer to a name column without issue now.

**Comment by wobba** [comment] 2018-07-31 14:38
@JLRishe do you have some information on how you managed to get this working?

**Comment by wobba** [comment] 2018-08-01 09:27
It works for `Modifed` and `DocIcon` fields, but not for FileLeafRef.

FileLeafRef works fine in debug mode though.
