### ISSUE TITLE
Comments and likes count updated after a long time when using graph

### ISSUE THREAD

**Issue by MRuimerman** [SharePoint/sp-dev-docs#3374] opened 2019-02-01 09:39 UTC
We want to use graph to collect the views, likes and comment for news. 
However, since a couple of days it takes a long time before for instance the likecount gets updated. The footer of the page immeadiately shows the correct number but using graph it takes hours.
The graph call appears to be correct because it worked up unto a couple of days before.

The call we use is: https://graph.microsoft.com/v1.0/sites/{siteID}/lists/{listId}/items/{listItemId} 

#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

To see the updated number of likes and comments.

#### Observed Behavior

The number was updated the next day when using graph.

#### Steps to Reproduce

- Like or comment a news post
- Check the number of comments in the footer of the page
- Compare this number to the graph results:  https://graph.microsoft.com/v1.0/sites/{siteID}/lists/{listId}/items/{listItemId}

**Comment by andrewconnell** [comment] 2019-02-01 11:11
The MSGraph is using the SharePoint v2 REST API to get SharePoint data. Can you check the underlying SharePoint REST API to see if it's returning the correct data to isolate where the issue is?

Ref: https://www.techmikael.com/2019/01/introducing-sharepoint-rest-api-v20.html

**Comment by MRuimerman** [comment] 2019-02-01 12:09
Thanks Andrew!

The graph call returns different results than the REST API.
I liked a post and the REST API was almost immediately updated, and Graph is not updated yet.

**Comment by andrewconnell** [comment] 2019-02-01 12:11
OK... then that should be posted as a bug to the Graph team as it's not something the SharePoint side can address... agreed? If so, prob best to submit to them & close this issue...

**Comment by MRuimerman** [comment] 2019-02-01 12:45
Yes, you are absolutely right, this is a graph issue. I will try to contact the graph team.

Thanks for your help!

**Closed** 2019-02-01 13:55 UTC
Labels: Needs: Attention :wave:, area:csom/rest
