### ISSUE TITLE
MSGraphClient Error: Login popup failed to redirect to the designated redirect uri.

### ISSUE THREAD

**Issue by aslanovsergey** [SharePoint/sp-dev-docs#1643] opened 2018-04-12 07:15 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Observed Behavior
Sometime after authentication window of MSGraphClient I get this error
```

Error: Login popup failed to redirect to the designated redirect uri.
    at sp-pages-assembly_en-us_325b8f8982f9db16bb747bf1b7651f15.js:688

```
Next tries are successful

**Comment by VesaJuvonen** [comment] 2018-04-12 17:08
Seems to be a duplicate of #1640. Let's trace the issue with 1640 and close this one as the 1640 has more details to support repro

**Closed by VesaJuvonen** 2018-04-12 17:08 UTC
Labels: area:framework, type:bug
