### ISSUE TITLE
Approved permission in API Management page not visible

### ISSUE THREAD

**Issue by wictorwilen** [SharePoint/sp-dev-docs#1397] opened 2018-02-23 19:15 UTC
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
I expect to see all approved API's in the API management page

#### Observed Behavior
After approving two API's, one by one, the first one disappeared from the view and only the second one is shown.
![image](https://user-images.githubusercontent.com/5854279/36612193-21445b70-18d6-11e8-9d6d-e671489dbb85.png)
Image above should also contain the Mail.Read permission which was the first one I approved. 

But, the permission is still granted to my SPFx web part. And in this case I would not be able to reject the permission.

**Comment by waldekmastykarz** [comment] 2018-02-26 11:21
The UI is confusing but I suspect it's by design.

When you're approving a permission request, once approved, it becomes a grant and its information is attached to a service principal in AAD. At that point, the request doesn't exist anymore and you can only work on the grant, which is specific to the resource and combines all scopes. The UI reflects what's in AAD which is why you see the scopes combined.
In the UI and PowerShell you can only remove the whole grant rather than specific permissions. At this moment specific permissions can be removed only through AAD REST API or using the [Office 365 CLI](https://sharepoint.github.io/office365-cli/cmd/aad/oauth2grant/oauth2grant-set/).

With that said, it makes perfect sense to be able to manage the different scopes separately rather than complete grants.

**Comment by VesaJuvonen** [comment] 2018-03-01 18:50
Waldek is 100% correct on this, so closing this one. Thx for the help and good to get the answer logged also for others.

**Closed by VesaJuvonen** 2018-03-01 18:50 UTC
