### ISSUE TITLE
CommandSet extensions stopped working

### ISSUE THREAD

**Issue by RoelVB** [SharePoint/sp-dev-docs#3703] opened 2019-03-29 08:17 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Observed Behavior

A CommandSet extension which was working fine a couple of days ago stopped working yesterday.
The console logs:
`Uncaught Error: There is no operation handler registered for '{"operation_3":["getItems_1","spField_296"]}'.`
Error source: `https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-03-15-sts_20190326.002/splistitemsscope-is-mini-8f54d6ff.js`

I've tried it on 3 different tenants, all throwing this error.

#### Steps to Reproduce

Even a newly generated extension throws this error en doesn't do anything. A `console.log()` in the `onInit` method doesn't even appear in the console.

**Comment by PooLP** [comment] 2019-03-29 13:52
I have the same error since this morning.

**Comment by RoelVB** [comment] 2019-03-29 14:14
It looks like the problem got resolved. For me the extension started working again.

**Comment by RoelVB** [comment] 2019-03-29 14:18
Correction. Looks like extension in debug mode are still not working.

**Comment by cwdata** [comment] 2019-03-29 14:48
Same problem here. Started about one hour ago. 
CommandSets suddenly show up on the wrong list or are output twice. Clicking on them does not execute them. Browser console shows the above mentioned error.

**Comment by PiotrekKrakowiak** [comment] 2019-03-29 15:20
Are your tenants on First (targeted) Release?

**Comment by cwdata** [comment] 2019-03-29 15:21
Mine is on targeted release.

**Comment by PiotrekKrakowiak** [comment] 2019-03-29 15:36
I can only repro on TR(FR) - no repro on standard release. Anybody with a Repro on SR? :-)

**Comment by RoelVB** [comment] 2019-03-29 15:42
Same here. Problem only exists on **targeted release**!

**Comment by westleyMS** [comment] 2019-03-29 17:23
The PG is rolling back a feature they deployed recently, they said it should be rolled back in about 20 min. If it was the cause, the issue should disappear when it rolls back.

**Comment by cwdata** [comment] 2019-03-29 18:12
Still nearly the same error at 19:12 (Utc +1)
The only thing that changed: The CommandSet now executes when clicking on the link. But it is still shown twice, has no Icon and the error in the console is also still there.

**Comment by westleyMS** [comment] 2019-03-29 19:06
did you clear the browser cache? ctrl+F5?

**Comment by cwdata** [comment] 2019-03-29 20:13
Yes I even cleared it through the browser settings. Still not working.

**Comment by westleyMS** [comment] 2019-03-29 22:29
Please use the F12 tools to see the sp-client-prod or odsp-next-prod file versions. Just get the full file names and post them here.

**Comment by PooLP** [comment] 2019-03-30 06:59
it still does not work this morning, cache is completely cleared.

@westleyMS : on site collection I have only odsp-next-prod files directory name :
ex : https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-03-15-sts_20190328.001/require-a19851d1.js

**Comment by RoelVB** [comment] 2019-04-02 07:30
Deployed extensions seems to work fine now, but debug mode still doesn't work.

Something strange happen when appending only `?loadSPFX=true` to the URL. A button get added to the commandbar, this button has the name of the (deployed) extension, but does nothing when clicking it. And of cause I don't have a button like this defined in the extension.

**Comment by cwdata** [comment] 2019-04-02 07:34
For us it worked yesterday, but today the error is back like it was on Friday.

**Comment by harshdamaniahd** [comment] 2019-04-02 09:35
Yes, I can confirm extensions have stopped working :-)
Spent whole morning trying to figure out what went wrong.
Thanks for raising the issue otherwise i would have spent the whole day..haha

![image](https://user-images.githubusercontent.com/11780473/55392231-285b1500-553b-11e9-8ed9-bcfc84781c0d.png)

**Comment by statto1974** [comment] 2019-04-02 10:18
Stopped working for me when using gulp serve (Works OK for deployed version) on a Target Release tenant

Uncaught Error: There is no operation handler registered for '{"operation_3":["getItems_1","spField_296"]}'.
    at e.r (splistitemsscope-is-mini-a9a8d6f1.js:1)
    at new e (splistitemsscope-is-mini-a9a8d6f1.js:1)
    at splistitemsscope-is-mini-a9a8d6f1.js:1
    at splistitemsscope-is-mini-a9a8d6f1.js:1
    at splistitemsscope-is-mini-a9a8d6f1.js:1
    at splistitemsscope-is-mini-a9a8d6f1.js:1
    at dispatch (splistitemsscope-is-mini-a9a8d6f1.js:1)
    at Object.<anonymous> (splistitemsscope-is-mini-a9a8d6f1.js:1)
    at listviewdataprefetch-mini-97237397.js:15
    at Object.next (listviewdataprefetch-mini-97237397.js:15)

**Comment by harshdamaniahd** [comment] 2019-04-02 11:25
For me base64 image stopped working ,  can anyone confirm this ?
![image](https://user-images.githubusercontent.com/11780473/55399197-bf7b9900-554a-11e9-9ad3-8cc45677b213.png)

**Comment by kwilsson** [comment] 2019-04-02 11:41
> Yes, I can confirm extensions have stopped working :-)
> Spent whole morning trying to figure out what went wrong.
> Thanks for raising the issue otherwise i would have spent the whole day..haha
> 
> ![image](https://user-images.githubusercontent.com/11780473/55392231-285b1500-553b-11e9-8ed9-bcfc84781c0d.png)

I also have this issue on one of my tenants, is it something i should do to get it fixed?

**Comment by harshdamaniahd** [comment] 2019-04-02 12:09
@kwilsson I guess something is wrong in targeted release.I will suggest dont spend time for now.Lets wait.
Many users are facing this issue.

**Comment by majidali** [comment] 2019-04-03 13:38
same issue here with base64 image. Extension is sort of working fine but images are not appearing...

![image](https://user-images.githubusercontent.com/1583717/55483281-2e75f200-561e-11e9-8779-264df8ab4b0b.png)

**Comment by spdavid** [comment] 2019-04-04 07:57
I got the same error here. On targeted release. My command extension does not work at all. Reverting to standard release for now. 

![image](https://user-images.githubusercontent.com/11256585/55538988-ec04f180-56bf-11e9-9bdc-76618a7c2594.png)

**Comment by Louren** [comment] 2019-04-04 08:24
Same error here; targeted release. Both when using gulp serve and deployed version.

> Stopped working for me when using gulp serve (Works OK for deployed version) on a Target Release tenant

**Comment by JovitaLipkiene** [comment] 2019-04-04 08:35
The same problems for us. I also noticed that this issue appears randomly, but much more often column extensions and view commands do not load correctly than loads as expected, when refreshing page several times in a row.

![image](https://user-images.githubusercontent.com/44869145/55539636-cda3f380-56c9-11e9-910d-57ba344701a8.png)

**Comment by JJungbluth** [comment] 2019-04-04 08:48
I have this issue too. Sorry if there is an obvious answer to this question but what exactly do you mean by "targeted release"?

**Comment by PooLP** [comment] 2019-04-04 09:05
@andrewconnell @VesaJuvonen you have any news for this bug, it becomes very blocker. Thanks.

**Comment by spdavid** [comment] 2019-04-04 10:56
> I have this issue too. Sorry if there is an obvious answer to this question but what exactly do you mean by "targeted release"?

in Office 365 admin under organization profile you can set your Release Preferences to be targeted release which means you get early updates.

**Comment by andrewconnell** [comment] 2019-04-04 11:36
@JJungbluth said:
> ... what exactly do you mean by "targeted release"?
https://docs.microsoft.com/en-us/office365/admin/manage/release-options-in-office-365?view=o365-worldwide

**Comment by VesaJuvonen** [comment] 2019-04-04 11:47
We are currently actively investigating this.

**Comment by EdwKro** [comment] 2019-04-04 14:38
Same problem here!

Hope you guys can figure it out

**Comment by VesaJuvonen** [comment] 2019-04-04 19:18
This issue is actively being worked on. Hopefully will get sorted out soon.

**Comment by VesaJuvonen** [comment] 2019-04-04 21:23
Fix has been now applied and situation should be reverted to normal. This was an unfortunate regression which got passed the testing. Please confirm the situation from our side as well, but based on the tenants we use for validation, we cannot anymore see this one. Thanks for confirmation advance.

**Comment by patrikhellgren** [comment] 2019-04-04 21:48
It seems the issue with the Command Set Extensions is gone in my tenant but I also lost all new library features that I received around the same time that I started noticing the issue. These include Bulk Check-out/in, Signals, the Shimmer background and the new status indicator when uploading/checking out etc files.

**Comment by cwdata** [comment] 2019-04-05 07:20
In our tenant extensions are also back to normal operation.

**Comment by harshdamaniahd** [comment] 2019-04-05 07:46
Everything is back to normal  :-) 
1. image not showing up in extension - fixed
2. Not working in debug mode or when gulp serve - fixed ("Execute function not executing") - fixed

**Comment by JovitaLipkiene** [comment] 2019-04-05 08:15
I also confirming that issues gone.

**Closed** 2019-04-08 20:50 UTC
Labels: area:framework, internal:priority, status:fixed, type:bug

**Comment by VesaJuvonen** [comment] 2019-04-08 20:54
Thx everyone for confirming the status. Sorry for the inconvenience. Planned features which might have been there for a while, will come back after the regression has been fixed.

**Comment by csgkeith** [comment] 2019-04-17 01:24
We were affected by this issue when it first occurred. The fix worked as the error message went away and our SPFX command bar extension started working again.

I noticed this morning that it has come back on one of our tenants. I get the below error when I select an item in the site pages library and click the delete button in the command bar:

`splistitemsscope-is-mini-dc133da0.js:1 Uncaught Error: There is no operation handler registered for '{"operation_3":["getItems_1","progress-deleteItems_509"]}'.
    at e.n (spofiles-mini-6714dbfb.js:1)
    at new e (splistitemsscope-is-mini-dc133da0.js:1)
    at splistitemsscope-is-mini-dc133da0.js:1
    at splistitemsscope-is-mini-dc133da0.js:1
    at splistitemsscope-is-mini-dc133da0.js:1
    at splistitemsscope-is-mini-dc133da0.js:1
    at dispatch (splistitemsscope-is-mini-dc133da0.js:1)
    at Object.<anonymous> (splistitemsscope-is-mini-dc133da0.js:1)
    at listviewdataprefetch-mini-bfd20981.js:15
    at Object.next (listviewdataprefetch-mini-bfd20981.js:15)`

Also I'm noticing that our SPFX add-in is not loading in this tenant (using gulp serve) but it is in others.

**Comment by statto1974** [comment] 2019-04-17 14:22
@VesaJuvonen @andrewconnell 

Not getting the error anymore, but gulp serve isn't working. My Command Set isn't being loaded into the library I have set up in serve.json

Have cleared history and cache

Have set up a series of Console logs and it does not even initiate the command set.

Not sure if it's relevant, but these are the only error messages showing in the console.

Refused to get unsafe header "SPClientServiceRequestDuration"
Refused to get unsafe header "SPRequestGuid"
Refused to get unsafe header "SPRequestGuid"
Refused to get unsafe header "X-SERVICEWORKER-DATA-SOURCE"

If I package and deploy through the app catalog it works correctly.

**Comment by gagan2singh** [comment] 2019-06-30 20:19
The issue has started appearing again, @VesaJuvonen can you please validate if there were any update done on the List Field customizer.

Please see the error below:
Uncaught Error: There is no operation handler registered for '{"operation_4":["getItems_16","spColumnAdapter_222"]}'.
    at e.n (spofiles-mini-be65a0bf.js:1)
    at new e (splistitemsscope-is-mini-8ce35f12.js:1)
    at splistitemsscope-is-mini-8ce35f12.js:1
    at splistitemsscope-is-mini-8ce35f12.js:1
    at splistitemsscope-is-mini-8ce35f12.js:1
    at splistitemsscope-is-mini-8ce35f12.js:1
    at dispatch (splistitemsscope-is-mini-8ce35f12.js:1)
    at Object.<anonymous> (splistitemsscope-is-mini-8ce35f12.js:1)
    at listviewdataprefetch-mini-f46dba5c.js:15
    at Object.next (listviewdataprefetch-mini-f46dba5c.js:15)

**Comment by cwdata** [comment] 2019-07-01 07:30
Hi @gagan2singh,
this is a closed issue. If you want somebody to help you then it's recommended to open a new issue. 
You can refer to this one if you think it is related.

**Comment by gagan2singh** [comment] 2019-07-07 19:58
Thanks opened a new issue https://github.com/SharePoint/sp-dev-docs/issues/4219
