### ISSUE TITLE
Workbench in 1.6.0 and in IE11 is broken.

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#2892] opened 2018-11-07 19:41 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Open workbench for local testing in IE11 since some customer still uses this browser.

#### Observed Behavior
Currently, the workbench cannot be opened because of the following error message on the console.

<img width="677" alt="screenshot 2018-11-07 at 20 38 35" src="https://user-images.githubusercontent.com/5503835/48156209-2e6f0180-e2cd-11e8-8530-f0e27270d985.png">

The problem comes from a for loop where a const instead of let or var was used:

<img width="693" alt="screenshot 2018-11-07 at 20 28 18" src="https://user-images.githubusercontent.com/5503835/48156249-48a8df80-e2cd-11e8-9b23-26bf3d27e863.png">

While other browsers ignore that IE11 show a more strict behaviour and avoid to init.

#### Steps to Reproduce
Create a new project, `gulp serve`, open Workbench in IE11.

**Comment by phawrylak** [comment] 2018-11-08 22:49
Not working in new SPFx 1.7.0 too.

**Comment by s-KaiNet** [comment] 2018-11-21 16:53
Any ETA for the fix? Some big companies still use IE11 and even have it in the list of supported corporate browsers.

**Comment by andrewconnell** [comment] 2018-12-20 11:08
Is this limited to just the workbench, or SPFx in general?

**Comment by SeanCMrsh** [comment] 2019-02-28 13:59
This is happening to me also (IE11 - WB1.7.1) only seems to happen on workbench - I've added pnp polyfills as suggested by some sites but with no joy.
Any ideas

npm install --save @pnp/polyfill-ie11

(index.d.ts in polyfill dir)
import "core-js/es6/array";
import "core-js/modules/es6.promise";
import "core-js/modules/es6.array.iterator.js";
import "core-js/modules/es6.array.from.js";
import "core-js/modules/es6.array.fill.js";
import "core-js/modules/es6.array.find";
import "es6-map/implement";
import "whatwg-fetch";

**Comment by andrewconnell** [comment] 2019-08-09 20:00
Please refer to the recently published IE11 support doc here: https://support.office.com/en-us/article/Which-Browsers-Work-With-Office-Online-AD1303E0-A318-47AA-B409-D3A5EB44E452

After reviewing the above doc, can you please verify the issue is still present in the lastest SPFx version (1.8.2)?

**Comment by AchimFeser** [comment] 2019-08-12 09:20
const manifests = spfxWindow.debugManifests.getManifests();
const manifestIds = [];
for (const manifest of manifests) {
    manifestIds.push(manifest.id.toUpperCase());
}

SCRIPT1053: "const" muss initialisiert sein.
workbenchInit.js (10,21)
SCRIPT5007: Objekt erwartet
sp-loader-assembly_default.js (5190,13)


Von: Andrew Connell <notifications@github.com>
Gesendet: Freitag, 9. August 2019 22:01
An: SharePoint/sp-dev-docs <sp-dev-docs@noreply.github.com>
Cc: Feser, Achim <Achim.Feser@tge-gas.com>; Manual <manual@noreply.github.com>
Betreff: Re: [SharePoint/sp-dev-docs] Workbench in 1.6.0 and in IE11 is broken. (#2892)


Please refer to the recently published IE11 support doc here: https://support.office.com/en-us/article/Which-Browsers-Work-With-Office-Online-AD1303E0-A318-47AA-B409-D3A5EB44E452<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsupport.office.com%2Fen-us%2Farticle%2FWhich-Browsers-Work-With-Office-Online-AD1303E0-A318-47AA-B409-D3A5EB44E452&data=02%7C01%7Cachim.feser%40tge-gas.com%7Ce797c06deeb242de89bb08d71d0449cc%7Ceeb159ae2c594dbb94ecf6357c614854%7C0%7C0%7C637009776578966444&sdata=lScv0AEFdxLFO8OdcZhz0bcuroCIE44hYCi1jhrSjRU%3D&reserved=0>

After reviewing the above doc, can you please verify the issue is still present in the lastest SPFx version (1.8.2)?

**Comment by euvin3582** [comment] 2019-08-20 17:56
Can someone post a fix for this. I am still having issues and the links posted do not say how to fix it.

**Comment by srideshpande** [comment] 2019-09-27 18:35
Thanks for raising the concern. Yes, we're aware of this issue. It is a browser compatibility issue and the fix will take more effort than required. Also, this is developer only scenario and not a end user scenario. Here are some of the workarounds you can try:

1. Use any other browser for this scenario?
2. Use hosted workbench

I'm closing the issue.

Thanks for understanding,
Sri

**Closed by srideshpande** 2019-09-27 18:35 UTC
Labels: area:framework-general, status:tracked, type:bug-confirmed
