### ISSUE TITLE
A web part is not rendered on a Single Web Part page in a mobile device

### ISSUE THREAD

**Issue by jusper-dk** [SharePoint/sp-dev-docs#4968] opened 2019-12-02 13:08 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
An SPFx web part is rendered properly in a Single Web Part page in a mobile device

#### Observed Behavior
A web part is rendered properly in desktop mode but the page remains empty in mobile view. No constructor, nor onInit are executed.

#### Steps to Reproduce
- Create a Single Web Part Page with a web part
- Open it Chrome browser
- Expand the Dev Tools (F12) and emulate a mobile device, ex iPhone 6/7/8
- Refresh the page - no web part is rendered

**Comment by andrewconnell** [comment] 2019-12-06 16:36
Repro'd... 

Desktop view:
![image](https://user-images.githubusercontent.com/2068657/70339208-b9168d00-184e-11ea-9008-7f4cdac77659.png)

Mobile view when resized via emulator:
![image](https://user-images.githubusercontent.com/2068657/70339239-c9c70300-184e-11ea-9c9b-ab0061f4be1b.png)

After refreshing mobile view via emulator:
![image](https://user-images.githubusercontent.com/2068657/70339273-d8adb580-184e-11ea-8997-d47349cee80b.png)

**Comment by AndyBolam** [comment] 2019-12-10 08:59
Same here, was able to reproduce in the same way as Andrew C did.  This issue is affecting Single Page App Web Parts in our tenant, I have raised a ticket, will report back here if I get anywhere.

**Comment by AndyBolam** [comment] 2020-01-22 13:28
Hi, any movement on this?  I've been told that changing from Targeted release to Standard in the tenant will resolve, however that doesn't really help me!!

**Comment by lucs17** [comment] 2020-01-27 11:08
Unfortunately, this bug is already rolled out to the Standard release in some tenants. So the solution to switch from Targeted to Standard release won't work anymore. We really need a fast bug fix from MS!

**Comment by AndyBolam** [comment] 2020-01-27 11:38
Well that's torn it.  Come on MS you are supposed to be seeing these bugs in preview before they are get to Standard, this has been a visible problem since 5 December!!

So another support ticket it is explaining exactly the same thing as before!!!!!  As I don't seem to be able to reopen the one you closed without resolving.  So frustrating.

Anyone else suffering with this, raise another ticket please :)

**Comment by idboyd01** [comment] 2020-01-27 11:39
Hi, this is an issue for us too. A blank page loads when viewing Single Web Part pages on Android (Chrome) or iOS (Safari). Using the "Request Desktop Site" option on either browser loads the page correctly, but unfortunately this isn't a viable workaround for our end users.

I tested it with a completely default "Hello World" wepbart (v1.10, React Framework) and had the same issue.

**Comment by AndyBolam** [comment] 2020-01-27 14:39
Hi idboyd01, yes Andrew Connell and myself have both also tested this and there is a proven issue.  I am using Plumsail Forms which provides dedicated mobile forms using this type of page, it has led to several clients reporting broken business processes that rely on these.  Plus, I'm unable to deploy any new projects that use these.  

Highly frustrating and should be resolved asap.  If MS want us to work within the confines of the spFX framework in Modern (which in the main is amazing), then they darn well ought to make sure tools that are used at the production level actually work before they deploy them into General release.

**Comment by Pietschik** [comment] 2020-02-12 14:37
Any news here?

**Comment by miguelisidoro** [comment] 2020-02-13 23:28
Any news about this issue? Will the update be made by MS without the need for developers to make changes on development side and redeploy the web part?
If development changes are necessary, which changes must be made on dev side?

Thanks

**Comment by andrewconnell** [comment] 2020-02-14 10:47
MSFT SP engineering is aware of this and is investigatingI'll share updates if/when there's something I to share.

**Comment by miguelisidoro** [comment] 2020-02-15 00:19
Thanks @andrewconnell, will wait for the update.

**Comment by cangot** [comment] 2020-02-18 09:49
Thanks @andrewconnell : This is really critically for many important customers. We asked them to create support ticket referring to this thread to speed up the process if possible.

**Comment by andrewconnell** [comment] 2020-02-18 11:28
@cangot understood... I can't fix it, I just help with the issue list & make them aware of a possible issue. They are investigating, but I need to defer to Microsoft to share updates, plans, timelines, etc.

**Comment by KevinTCoughlin** [comment] 2020-02-18 22:02
We've identified the bug and are rolling out a fix.

**Comment by cangot** [comment] 2020-02-21 10:55
FYI : Microsoft Premier Support is telling me the fix deployment should take up to 3 weeks, but it could also be next week. Anyone can confirm ?

**Comment by andrewconnell** [comment] 2020-02-21 11:09
@cangot If that's what MPS is saying, that's confirmation. :)

**Comment by KevinTCoughlin** [comment] 2020-03-12 21:12
FYI - This was fixed in 2/21 build forward.

**Closed** 2020-03-13 10:50 UTC
Labels: Needs: Microsoft Review 👓, area:spfx-general, status:fixed, type:bug-confirmed
