### ISSUE TITLE
gulp bundle/serve webpack error when external resources are present in config.json externals

### ISSUE THREAD

**Issue by joepenland** [SharePoint/sp-dev-docs#6833] opened 2021-03-18 19:34 UTC
## Category

- [x] Bug

## Describe the bug

I am getting the following error when running `gulp serve` or `gulp bundle` commands when there is a jQuery reference in the externals section of the config.json file.
```
Error - [webpack] 'dist':
Did not find linked external "jquery" for bundle "test-web-part".
```

### Create a new web part.
1. `yo @microsoft/sharepoint`
2. Solution name
3. `SharePoint Online only (latest)`
4. `Use the current folder`
5. `No`
6. `No`
7. `WebPart`
8. Web part name
9. Web part description
10. `No JavaScript framework`

### Install jQuery and types.

I followed the instructions at [Add jQueryUI Accordion to your SharePoint client-side web part](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/add-jqueryui-accordion-to-web-part#install-jquery-and-jquery-ui-npm-packages), but only installed jQuery and not jQuery UI.  I have followed this process before and never had an issue.
- `npm install jquery`
- `npm install @types/jquery`
(I also tried using jquery@2 for each of those with the same result)

### Add jQuery to the "externals" section of the config/config.json file.

OOTB externals:
```
  "externals": {},
```
Updated externals:
```
  "externals": {
    "jquery": "node_modules/jquery/dist/jquery.min.js"
  },
```

### Use jQuery in the project.

TestWebPart.ts:
```
import * as jQuery from 'jquery';
...
export default class TestWebPart extends BaseClientSideWebPart<ITestWebPartProps> {

  public render(): void {
    this.domElement.innerHTML = `
      <div class="${ styles.test }">
        <div class="${ styles.container }">
          <div class="${ styles.row }">
            <div class="${ styles.column }">
              <span class="${ styles.title }">Welcome to SharePoint!</span>
              <p class="${ styles.subTitle }">Customize SharePoint experiences using Web Parts.</p>
              <p class="${ styles.description }">${escape(this.properties.description)}</p>
              <a href="https://aka.ms/spfx" class="${ styles.button }">
                <span class="${ styles.label }">Learn more</span>
              </a>
            </div>
          </div>
        </div>
      </div>`;

    const newElement = jQuery('<div />');
  }
...
```

### Run gulp serve or gulp bundle (with or without --ship).

Here is the output, including the error:
```
PS C:\Local Development\test> gulp bundle
Build target: DEBUG
[14:54:37] Using gulpfile C:\Local Development\test\gulpfile.js
[14:54:37] Starting 'bundle'...
[14:54:37] Starting gulp
[14:54:37] Starting subtask 'configure-sp-build-rig'...
[14:54:37] Finished subtask 'configure-sp-build-rig' after 3.47 ms
[14:54:37] Starting subtask 'pre-copy'...
[14:54:37] Finished subtask 'pre-copy' after 50 ms
[14:54:37] Starting subtask 'sass'...
[14:54:37] Finished subtask 'copy-static-assets' after 29 ms
[14:54:37] Finished subtask 'sass' after 136 ms
[14:54:37] Starting subtask 'tslint'...
[14:54:38] [tslint] tslint version: 5.12.1
[14:54:38] Starting subtask 'tsc'...
[14:54:38] [tsc] typescript version: 3.7.7
[14:54:40] Finished subtask 'tsc' after 2.67 s
[14:54:41] Finished subtask 'tslint' after 3.69 s
[14:54:41] Starting subtask 'post-copy'...
[14:54:41] Finished subtask 'post-copy' after 220 μs
[14:54:41] Starting subtask 'configure-webpack'...
[14:54:41] Starting subtask 'webpack'...
[14:54:42] Error - [webpack] 'dist':
Did not find linked external "jquery" for bundle "test-web-part".

[14:54:42] Finished subtask 'webpack' after 893 ms
[14:54:42] Finished 'bundle' after 5.19 s
[14:54:43] ==================[ Finished ]==================
Error - [webpack] 'dist':
Did not find linked external "jquery" for bundle "test-web-part".

[14:54:43] Project test version:0.0.1
[14:54:43] Build tools version:3.17.11
[14:54:43] Node version:v10.23.3
[14:54:43] Total duration:8.47 s
[14:54:43] Task errors:1
```

## Expected behavior

gulp serve, gulp bundle, or gulp bundle --ship should complete without issue.

## Environment details (*development & target environment*)

- **Your Developer Environment**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: Node.js v10.23.3; Gulp CLI version: 2.3.0, Local version: 4.0.2; Yeoman 
- **Browser(s)**: Not relevant.  Chrome, Edge, Brave, Firefox.
- **Tooling**: VS Code | SPFx v1.12.0
- **Additional details**: The issue happens before getting to the browser.  It happens in CLI.

### Additional context

If I remove the jQuery reference from the "externals" section of the config/config.json file the commands run successfully (gulp serve, gulp bundle).

*Thanks for your contribution! Sharing is caring.*

**Comment by patrikhellgren** [comment] 2021-03-18 20:05
I am seeing the exact same thing after upgrading from 1.10 to 1.12, but with SignalR and jQuery.

The error from gulp bundle --ship is: 
Error - [webpack] 'dist':
Did not find linked external "signalr" for bundle "<bundle name>"

This is the externals section in my config.json:

  "externals": {
    "jquery": {
      "path": "https://code.jquery.com/jquery-2.2.4.min.js",
      "globalName": "$"
    },
    "signalr": {
      "path": "https://cdnjs.cloudflare.com/ajax/libs/signalr.js/2.4.1/jquery.signalR.min.js",
      "globalName": "signalr",
      "globalDependencies": ["jquery"]
    }
  }

**Comment by meany** [comment] 2021-03-20 21:44
Same issue here. Downgraded `@microsoft/generator-sharepoint@1.11.0` and node v10.24.0 so I can use externals.

**Comment by joepenland** [comment] 2021-03-23 19:37
While double-checking myself I saw here [Set up your SharePoint Framework development environment](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment) that Node.js v12 is now recommended so I upgraded to v12 and made sure everything else was updated as well.  The issue is still present though.

**Comment by KevinTCoughlin** [comment] 2021-03-23 22:15
The issue here is unrelated to Node version. We are investigating and will report back. Thanks.

**Comment by VesaJuvonen** [comment] 2021-03-24 12:28
This issue is intended to be part of the upcoming 1.2.1 patch release. Currently we recommend to keep on using 1.11 until further notice. We do apologize the inconvenience.

**Comment by joepenland** [comment] 2021-03-24 12:59
Thanks @VesaJuvonen, @KevinTCoughlin, and @andrewconnell for looking into this and confirming the bug.  Is there an article you could point me to which shows how to downgrade the SPFx version in an already existing project, or will I need to set up a new project and copy my work to the new one?  My project is more complex than the example given to open this issue.  I just used the simplest example to clearly illustrate the issue with the fewest customizations possible.

I can migrate to a new project, but if there is a good way to downgrade an existing project successfully it would be a good process to have documented.  I haven't been able to find the process clearly explained in my searching so far.

**Comment by joepenland** [comment] 2021-03-24 13:22
It looks like I will also need to downgrade node back to v10 from v12 according to this article [SharePoint Framework development tools and libraries compatibility](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/compatibility#spfx-development-environment-compatibility), is this the case or is v12 supported in SPFx 1.11 (although it is not documented)?

In addition, according to the "Install Gulp" section of the article I sent in an earlier post [Set up your SharePoint Framework development environment](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment#install-gulp), it seems I may need to downgrade Gulp.  According to the article:
> Gulp v3 was used as the target for all Gulp tasks in the SPFx build toolchain prior to SPFx v1.12.

Will I also need to downgrade Gulp to v3?

**Comment by andrewconnell** [comment] 2021-03-24 21:56
@joepenland Couple things... to get your env setup for SPFx v1.11, you need the following installed:

- Node.js v10.*.* .... Node.js v12 is not supported with SPFx v1.11
- Gulp v3 (installed globally)... Gulp v3 only works up through Node.js v10, while Gulp v4 works for Node.js v12+

@joepenland said:
> I can migrate to a new project, but if there is a good way to downgrade an existing project successfully it would be a good process to have documented. I haven't been able to find the process clearly explained in my searching so far.

No... there's no documented way to do this, nor do I expect there to be. This is a very unique edge case situation. With that being said, you *may* have success by doing the following: 

1. in **package.json**, replace the instances of `1.12.0` on all SPFx related packages `1.11.0`
2. delete the **package-lock.json**
3. delete **node_modules**
4. reinstall all dependencies with **npm install**

To be clear, this isn't supported or recommended by Microsoft... it's simply my recommendation of something to try that might save time.

**Comment by joepenland** [comment] 2021-03-25 17:02
@andrewconnell, thanks for replying.  I appreciate your response.  Since the project in question is for production within my company, and there isn't a documented way to downgrade an existing project, I think it's probably best if I just rebuild it in a fresh project using SPFx 1.11.0.  I would rather not have to troubleshoot any unexpected results due to an unsupported method, but I do appreciate you providing me with an answer to the question I was asking.

One thing to note for anyone who comes across this answer is that the command `npm install @microsoft/generator-sharepoint@1.11.0 -g` is case sensitive to some extent at least.  It failed on me when I had a capital **M** for Microsoft.

Thanks again for the help.

**Comment by andrewconnell** [comment] 2021-03-26 09:39
@joepenland I got around to publishing a blog post on some steps if it helps:
https://www.voitanos.io/blog/sharepoint-framework-v1-12-deprecated/

I agree with your approach though... better & safer to redo it with SPFx v1.11.

**Comment by joepenland** [comment] 2021-03-26 17:18
@andrewconnell thanks for sharing the blog post!  It was helpful in clarifying things.  I honestly didn't realize I had upgraded to the brand new framework release at first - because I only got there while trying to troubleshoot some other strange issue I had with my project.  To fix what was going on (can't remember the original issue now) I had updated my environment and created a new project, then copied over my code.  That's when I found this bug.

I've copied my code to a new project using SPFx v1.11 and have been able to move forward now.  Thanks again for the guidance.

**Comment by KevinTCoughlin** [comment] 2021-03-26 20:35
That blog post is slightly misleading w.r.t root causes but overall decent advice.

BTW we have a fix for the issue tracked here and are evaluating the patch release internally. Thanks.

**Comment by andrewconnell** [comment] 2021-03-26 21:21
Thanks for the clarification @KevinTCoughlin ... updated the blog post with your explanation. I must have misunderstood the root cause as it was explained to me that it was directly related to #6847

**Comment by KevinTCoughlin** [comment] 2021-04-12 18:55
This "externals" issue is completely unrelated to upload to Azure CDN issue that you linked.

@joepenland can you confirm this "externals" issue is fixed in `1.12.1-rc.0` suite of packages e.g. https://www.npmjs.com/package/@microsoft/generator-sharepoint/v/1.12.1-rc.0?

**Comment by joepenland** [comment] 2021-04-14 16:26
@KevinTCoughlin I have been in the middle of development and haven't had a chance to change up my environment to test out the fix.  I plan to test it out, but need to wrap up my current project first.

**Comment by KevinTCoughlin** [comment] 2021-04-14 17:05
> @KevinTCoughlin I have been in the middle of development and haven't had a chance to change up my environment to test out the fix. I plan to test it out, but need to wrap up my current project first.

No worries. Thanks for volunteering to check.

**Comment by joepenland** [comment] 2021-04-19 17:06
@KevinTCoughlin I am ready to test this out, but do I need Node.js v12 or v10?

**Comment by KevinTCoughlin** [comment] 2021-04-19 18:31
> @KevinTCoughlin I am ready to test this out, but do I need Node.js v12 or v10?

Please use Node v12 or 14 LTS since Node 10 is EOL.

**Comment by joepenland** [comment] 2021-04-19 20:13
> @joepenland please use Node v12 or 14 LTS since Node 10 is EOL.

@KevinTCoughlin which one will be officially supported/recommended for use with SPFx 1.12.1?

**Comment by andrewconnell** [comment] 2021-04-19 20:15
@joepenland Both v12 & v14 will be supported:

https://docs.microsoft.com/en-us/sharepoint/dev/spfx/release-1.12.1

**Comment by joepenland** [comment] 2021-04-20 15:16
Thank you @andrewconnell.  I also appreciate how in your blog post you linked to above, you provided information (and a further link for guidance) on using a node version manager.

> @joepenland I got around to publishing a blog post on some steps if it helps:
> [https://www.voitanos.io/blog/sharepoint-framework-v1-12-deprecated/](https://www.voitanos.io/blog/sharepoint-framework-v1-12-deprecated/)

That allowed me to set up the environment to test out the fix while being able to also have a dedicated environment for SPFx 1.11 so I can keep developing.  Very helpful!

@KevinTCoughlin I repeated my simple test which I explained when I opened this issue and externals seem to be working properly.  Looks like this bug has been addressed.  Thanks!

**Comment by joepenland** [comment] 2021-04-20 15:22
Environment used for the test:

```
C:\Local Development\test_v1.12>node -v
v14.15.5

C:\Local Development\test_v1.12>npm list -g -depth=0
C:\Program Files\nodejs
+-- @microsoft/generator-sharepoint@1.12.1-rc.0
+-- gulp@4.0.2
+-- npm@6.14.11
`-- yo@3.1.1
```

**Comment by andrewconnell** [comment] 2021-04-20 21:03
@joepenland FYI - there've been two newer RC's released since you installed the preview... might want to update to latest (rc2) and try again.

**Comment by joepenland** [comment] 2021-04-21 12:28
@andrewconnell - tested again this morning and everything worked again.  Updated environment:

```
PS C:\Local Development\SPFx_1-12-1-rc-2> node -v
v14.15.5
PS C:\Local Development\SPFx_1-12-1-rc-2> npm list -g -depth=0
C:\Program Files\nodejs
+-- @microsoft/generator-sharepoint@1.12.1-rc.2
+-- gulp@4.0.2
+-- npm@6.14.11
`-- yo@3.1.1
```

**Comment by KevinTCoughlin** [comment] 2021-04-21 18:37
Cool. Thanks for confirming @joepenland!

**Closed** 2021-04-21 18:38 UTC
Labels: 1.12.x, area:spfx-general, area:tooling, status:fixed, status:tracked, type:bug-confirmed
