### ISSUE TITLE
Sync to teams 403 forbidden

### ISSUE THREAD

**Issue by mdanielcristian** [SharePoint/sp-dev-docs#5425] opened 2020-03-05 10:35 UTC
Select the SPfx solution in the app catalog, click Sync to Teams -> error message "Failed to sync solution to Teams", further investigation in dev tools reveals the following error message:` {"error":{"code":"-1, System.Net.WebException","message":{"lang":"en-US","value":"The remote server returned an error: (403) Forbidden."}}}`

Some additional details:
-The user is a global admin
-The same solution with the same user was syncing successfully yesterday
-Tried new solution on different tenants, same issue
-I think it has something to do with the new teams admin portal, the old 'Allow sideloading of external apps' in the o365 admin center is off and disabled
![sideloading](https://user-images.githubusercontent.com/30260770/75973001-246b0c00-5edd-11ea-904d-8b17d2c078ff.JPG)
and you are directed to the new Teams Admin portal, but everything there is enabled as well
![org wide](https://user-images.githubusercontent.com/30260770/75973171-685e1100-5edd-11ea-8a21-4bfe99e8f272.JPG)
![global](https://user-images.githubusercontent.com/30260770/75973180-6c8a2e80-5edd-11ea-8750-f60c47623d06.JPG)

## Steps to reproduce

1. Create a new SPfx solution for a Teams Tab following the steps here: [https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab](url)
2. Click Sync to Teams, error occurs instead of the success message

## Expected behavior

Sync to teams successfully

## Developer environment

- OS: Windows 10, SharePoint Onine
- Framework: SPfx 1.10.0
- Browser(s): any
- Tooling: VS Code

**Comment by OliverZeiser** [comment] 2020-03-05 15:16
I am seeing the same error. It was working a few days ago, now it seems to be broken on all tenants....

**Comment by canturan** [comment] 2020-03-05 15:18
I have also the same issue. To test it i have created a complete new solution with the SPFx 1.10 solution, deployed it and tried to sync it to the teams. It get the same error message. If i create the manifest manually and upload the app to teams, then everything works without any problem. 

Same behavior on all tenants.

**Comment by arunkumarperumal** [comment] 2020-03-06 09:53
same issue even with SPFx version 1.9.1, sync to teams was working fine few days ago.

**Comment by VesaJuvonen** [comment] 2020-03-06 12:49
Closed #5428 as a duplicate and we have continued investigation on this internally. Thanks everyone for reporting this and other reports also welcome.

**Comment by VesaJuvonen** [comment] 2020-03-09 09:54
We have identified the root cause of this issue and are expecting it to get resolved within next 24 hours. We do apologize the issue and delay on getting it fully resolved.

**Comment by VesaJuvonen** [comment] 2020-03-09 19:42
We just fixed the issue on the Azure AD side - certainly not optimal, but a mistake in the permissions between the services. My repro environment works without any issues now - which was broken before the fix - but would love few confirmations from you as well.

Notice that if you still get the 403 immediately when I sent this message - give it 30 min and try again... this should be now rolling gradually worldwide as setting is replicated. 

Thanks for your confirmation advance.

**Comment by OliverZeiser** [comment] 2020-03-09 20:02
Thanks @VesaJuvonen I can confirm the sync is working again.
As always, mistakes can happen. The communication is what makes the difference. And this time it was excellent. Thanks to you and the team👍

**Comment by RyanHealy** [comment] 2020-03-09 21:17
Fixed for me too. Thanks.

**Comment by sortegamartin** [comment] 2020-03-10 08:22
Hi @VesaJuvonen In my tenant it continues to give me an error, but now the error code is a 500 "UnknownError":

![image](https://user-images.githubusercontent.com/33054287/76293028-9b731c80-62b0-11ea-9f5f-59b9c77f737c.png)

**Comment by mdanielcristian** [comment] 2020-03-10 09:05
It's working for me too, thanks.

**Comment by VesaJuvonen** [comment] 2020-03-10 09:37
Thanks everyone for confirming the status with the 403 - closing this based on your input. 

On the @sortegamartin case, as that's a new issue, please submit details as a new issue... and double check that you do not have previous version already available in the Teams for the solution.

**Closed by VesaJuvonen** 2020-03-10 09:37 UTC
Labels: area:spfx-general, area:spfx-msteams, status:fixed, type:bug-suspected
