### ISSUE TITLE
Generator v1.3 Onpremise TypeScript Error

### ISSUE THREAD

**Issue by raclettierer** [SharePoint/sp-dev-docs#892] opened 2017-09-30 04:17 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Default project with Version 1.3 for onpremise without changes can build successfully.

#### Observed Behavior
![errorgulpserve_onprem](https://user-images.githubusercontent.com/32407069/31042236-2f83507a-a571-11e7-9a2c-a5da40a4138a.PNG)
....
![errorgulpserve_onprem_end](https://user-images.githubusercontent.com/32407069/31042328-5eddf83c-a573-11e7-9246-2b2c572b20b0.PNG)

If I try with online option, no error shown and all works as expected.

#### Steps to Reproduce
USING 1.3 SharePoint Generator: 
- Create a folder
- generate project: yo @microsoft/SharePoint
- Select OnPremise and React 
- gulp serve

**Comment by VesaJuvonen** [comment] 2017-10-03 06:34
Hi @raclettierer, just to let you know that the issue has been acknowledged and we are working on getting this resolved asap. It's related to a mismatch of the TypeScript and React version in the on-prem selection case. We should have an update available relatively soon.

**Comment by jlongshore** [comment] 2017-10-05 16:15
Any ETA on this issue by chance? Im running into the same issue. Thanks!

**Comment by waldekmastykarz** [comment] 2017-10-05 16:56
The latest version of the generator v1.3.2 has this issue solved.

**Comment by jlongshore** [comment] 2017-10-05 17:05
I can confirm this works for me now. Thank you!

**Comment by VesaJuvonen** [comment] 2017-10-05 17:41
thx Jeff for confirming. I'll close this one now.

**Closed by VesaJuvonen** 2017-10-05 17:41 UTC
Labels: area:generator, status:fixed-next-drop, type:bug
