### ISSUE TITLE
SingleWebPartAppPage navigation

### ISSUE THREAD

**Issue by ng-marcus** [SharePoint/sp-dev-docs#3168] opened 2018-12-26 12:56 UTC
#### Category
- [x ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

When we have multiple SingleWebPartAppPage pages, navigation using links in the Quick Launch don't work as expected.  On first click of a link, the browser navigates as normal.  However, to then move to another page, the user has to click the link twice, and the navigation only occurs on the second click.

It looks like on the first click, the browser makes a call for the page with ?as=json added.    

I saw similar issues before SingleWebPartAppPage came out in preview when we used to use Home rather than Article layouts for our app pages to remove the header.

Is there any guide to how SharePoint navigation works or how to make SingleWebPartAppPage work properly with Quick Launch?

**Comment by AlinaLishh** [comment] 2018-12-27 05:33
Maybe these links will help for you:

[ng-marcusNavigating from a page to another page causes SPFX web part on secondary page to not load #2398](https://github.com/SharePoint/sp-dev-docs/issues/2398)

[Navigating from a page to another page causes application state issues #1700](https://github.com/SharePoint/sp-dev-docs/issues/1700)

**Comment by ng-marcus** [comment] 2018-12-27 08:09
Thanks,

#2398 looks the same issue, but it seems the cause of that was already fixed, unless that rollback was on a per-tenant basis?

**Comment by VesaJuvonen** [comment] 2019-01-24 18:50
Single page apps is still in preview status, but we will be checking this by GA. Thanks for reporting.

**Comment by mcmynn83** [comment] 2019-03-04 23:53
As Vesa mentioned, this is fixed in the GA bits.  I am closing this now, if after the GA of 1.8 it still has issues please respond (I validated it works though).

**Comment by ng-marcus** [comment] 2019-03-18 08:22
I built with 1.8 and see no change in behaviour.    We also see the issue reported here:

https://github.com/SharePoint/sp-dev-docs/issues/3566

**Comment by ng-marcus** [comment] 2019-03-18 08:24
> As Vesa mentioned, this is fixed in the GA bits. I am closing this now, if after the GA of 1.8 it still has issues please respond (I validated it works though).

Hello, I'm seeing no change in behaviour unfortunately when building with 1.8

**Comment by mcmynn83** [comment] 2019-03-18 17:00
@ng-marcus - Sorry that looks like the patching of our bits has not rolled out yet.  By next Monday that fix should be visible.  If you would like I can verify that is the issue if you send me a fiddler trace to grahamc at my Microsoft account.

**Comment by ng-marcus** [comment] 2019-03-18 17:08
Thanks for the update.

I think the problem is generic, as I made two SingleWebPartAppPages with just a code preview element, and I see the same issue.   Happy to hear the fix is still coming, so I'll give it some time.  I'll try and get a fiddler trace in the meantime.  Many thanks!

**Comment by beyasu** [comment] 2019-03-19 14:51
I opened #3566 related to this issue. @ng-marcus referred me to this thread. I have completed upgrading to SharePoint framework 1.8 and build package solution. The issue reported isn't resolved yet. I will look forward for the fix coming by next Monday.

**Comment by ng-marcus** [comment] 2019-03-24 09:29
Very happy to report this issue is now resolved for me.   Single clicks of the quick links lead to an immediate navigation to the target page.

**Comment by beyasu** [comment] 2019-03-24 15:12
@ng-marcus great to see this issue is resolved. What has changed since last time to resolve it? Have you done anything different from your side recently? Thanks.

**Comment by ng-marcus** [comment] 2019-03-24 15:38
We rebuilt our app with spfx 1.8.  I think you need both the server side and client site update for this to be fixed.

**Comment by beyasu** [comment] 2019-03-24 20:26
@ng-marcus how do you update server side to spfx 1.8? I have followed release notes to 1.8, https://github.com/SharePoint/sp-dev-docs/wiki/SharePoint-Framework-v1.8-release-notes.

**Comment by ng-marcus** [comment] 2019-03-25 06:05
The only thing you should need to do is rebuild your app with the 1.8 version of the framework and deploy it (we use the AppCatalog).

The server update is being taken care of by Microsoft, and should have hit their servers by today (Monday).  We saw our sites update on Saturday night.

**Comment by mcmynn83** [comment] 2019-03-25 16:35
Thanks for confirming it is fixed.  

@beyasu - you actually don't even have to upgrade to 1.8.  The fix will just roll out and you will automatically get it.  I am closing this issue as it is now confirmed fixed.  However, if you are still seeing this issue please send a fiddler trace to grahamc at my microsoft.com address and I will confirm whether the issue is that you are still not upgraded or if there is another issue.

**Closed by mcmynn83** 2019-03-25 16:35 UTC
Labels: area:framework, status:tracked

**Comment by beyasu** [comment] 2019-03-25 19:07
@mcmynn83 I just checked our sites and this issue is resolved from from our side too. Thanks!!

**Comment by mcmynn83** [comment] 2019-03-25 20:24
Excellent glad to hear the issue is fixed.

**Comment by KEMiCZA** [comment] 2019-07-09 05:40
We're having a similar issue currently. Using a SPFx 1.7.0 webpart, when we force the PageLayoutType to "SingleWebPartAppPage" ([doc](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/single-part-app-pages#changing-page-layout-using-javascript-in-browser-console)), the onDispose() method is never called resulting in weird behaviour when switching between pages. @VesaJuvonen @GrahamMcMynn 

Perhaps SingleWebPartAppPages are not supported for 1.7.0 webparts? Do we need to upgrade to 1.8.x?

Kind regards
