### ISSUE TITLE
Suppressing SharePoint REST metadata using odata=nometadata fails

### ISSUE THREAD

**Issue by waldekmastykarz** [SharePoint/sp-dev-docs#644] opened 2017-06-14 13:55 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Originally, whenever you wanted to suppress the metadata in the JSON response of SharePoint REST APIs, you would include the `Accept: application/json;odata=nometadata` request header.

#### Observed Behavior
If you add the `Accept: application/json;odata=nometadata` request header to a request to the SharePoint REST API, the request will fail with a 406 Not Acceptable response. Instead you have to use the `Accept: application/json;odata.metadata=none` header. This has to do with the SPHttpClient using the `odata-version: 4.0` request header. Without this header, or with the odata version being set to `2.0` you can use `odata=nometadata` to suppress metadata. In the previous versions of the SharePoint Framework you could use `odata=nometadata` but in the latest version it fails. It could be that this is caused not by a change in the SharePoint Framework but in how SharePoint REST API handles the `data-version: 4.0` request header.

#### Steps to Reproduce
```ts
import { SPHttpClient, SPHttpClientResponse } from '@microsoft/sp-http';

export default class HelloWorldWebPart extends BaseClientSideWebPart<IHelloWorldWebPartProps> {
  public render(): void {
    this.domElement.innerHTML = `
      <div class="${styles.helloWorld}">...</div>`;

    this.context.spHttpClient.get(`${this.context.pageContext.web.serverRelativeUrl}/_api/web?$select=Title`, SPHttpClient.configurations.v1, {
      headers: {
        'Accept': 'application/json;odata=nometadata'
      }
    })
    .then((response: SPHttpClientResponse) => {
      return response.json();
    })
    .then((data) => {
      alert(data.Title);
    });
  }
  // ...
}
```

**Comment by pgonzal** [comment] 2017-06-26 22:45
@chackman FYI

**Comment by pgonzal** [comment] 2017-06-26 23:02
> It could be that this is caused not by a change in the SharePoint Framework but in how SharePoint REST API handles the data-version: 4.0 request header.

Hey @waldekmastykarz, I don't know of any changes made to SPHttpClient since the 1.0 release.  It seems likely that this was a server change.  Do you happen to have an example of code that used to work before?

**Comment by pgonzal** [comment] 2017-06-27 01:58
From what we can tell, the server code has not changed either.

Looking at the standards docs, [ODATA V4](http://docs.oasis-open.org/odata/odata-json-format/v4.0/os/odata-json-format-v4.0-os.html) uses a different notation `odata.metadata=none`.  The `odata=` notation is from [ODATA V3](http://www.odata.org/documentation/odata-version-3-0/json-verbose-format/).  The JSON Light `odata=nometadata` setting itself is not mentioned in that doc (maybe it is specific to Microsoft's implementation?).

The server certainly supported it prior to ODATA_V4:

```C#
#if ODATA_V4
                    if (contentType.IndexOf("none", StringComparison.OrdinalIgnoreCase) >= 0)
#else
                    if (contentType.IndexOf("nometadata", StringComparison.OrdinalIgnoreCase) >= 0)
#endif
                    {
                        return ODataMetadataLevel.NoMetadata;
                    }
```

@waldekmastykarz based on this, I am resolving this bug as "by design".  Please reopen it if you can find a counterexample. Thanks!

**Closed** 2017-06-27 01:59 UTC
Labels: status:by-design, type:bug

**Comment by waldekmastykarz** [comment] 2017-06-27 06:40
@pgonzal as far as I can tell it was exactly the same code. Not sure at which point it changed (ie. v1.0.0, v1.0.2 or v1.1.x) but in the latest release I noticed that what used to work in the past, isn't working anymore. Totally understood if this is by design, but in that case the documentation should reflect it.
