### ISSUE TITLE
Footer placeholder sometimes not positioned correctly

### ISSUE THREAD

**Issue by O365Tycho** [SharePoint/sp-dev-docs#2257] opened 2018-07-19 14:42 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

> Footer/bottom placeholder is supposed to be rendered in a fixed position at the bottom of the screen (wish it was the bottem of the page) and stay there

#### Observed Behavior
Sometimes on pages that require scrolling the footer/bottom placeholder is rendered and then stays at the initial position. See the attached screenshot.
Happens in the SharePoint app on IOS & Android and with smaller screensizes in desktop browsers.
 
![image](https://user-images.githubusercontent.com/10546703/42949627-753dbe9c-8b72-11e8-815c-7e7c6479627e.png)

#### Steps to Reproduce

Happens intermittendly, not always on the same pages. Haven't found anything specific that triggers this so keep trying and you'll probably run into this. Sorry....

**Comment by mschaefer85** [comment] 2018-09-25 19:18
Yes, same here (SharePoint App as well as mobile browsers).

It always helps to refresh the page - then the footer does not get stuck. But often when navigating via links, the footer gets stuck "behind" a web part.

Any ideas so far?

**Comment by sparkitect** [comment] 2018-09-25 19:45
we've pulled in a CSS file which sets the position of the placeholder to **fixed** and that seems to help, for the most part.


The difficulty lies in getting the SharePoint Mobile App to 'uncache' our CSS file when we change it.

**Comment by mschaefer85** [comment] 2018-09-27 19:42
Thanks for that update! I'm wondering whether this behaviour occurs only for us - it seems like this is something that is somehow broken on Microsoft's side ...

**Comment by dochen88** [comment] 2019-06-13 16:21
I am also experiencing this similar issue on iOS and Android mobile devices via the device's browser and on the device's respective SharePoint Mobile app. This issue seems to be occurring consistently after when landing on a modern page where the footer renders properly and then navigating to different modern page such as a news article on the site.

My workaround so far has been to refresh the page each time so that the page re-inits and resets the footer placeholder to the bottom.  We also experimented with forcing the footer to a fixed position with bottom 0 using CSS. However this causes the footer to cut off content at the bottom such as the "like" count on modern article pages.

Any idea on a better solution or when I can expect a fix for this?

**Comment by corriespondent** [comment] 2019-07-09 17:23
This appears to be because on first load, a "mobile" class is applied to the body tag. But when you navigate to a page that doesn't require a full page refresh, the class doesn't get carried across so the style gets lost.

1.png - initial load, .mobile class added
![1](https://user-images.githubusercontent.com/23064475/60909612-86328380-a233-11e9-859e-7280b982ec49.png)

2.png - .mobile class affects positioning of the footer placeholder
![2](https://user-images.githubusercontent.com/23064475/60909613-86328380-a233-11e9-8d4d-d7e19f01d88a.png)

3.png - after navigating to another page, .mobile class is lost
![3](https://user-images.githubusercontent.com/23064475/60909614-86328380-a233-11e9-80ac-8f0d3db6f0c4.png)

**Comment by sparkitect** [comment] 2019-07-09 18:55
Take a note, folks. This is what genius looks like 👆

**Comment by kemesfun** [comment] 2020-01-24 01:05
Is this still occurring? If so what page do you navigate when this issue occurs? @corriespondent

**Comment by kemesfun** [comment] 2020-01-27 23:48
@O365Tycho Does this issue still occur?

**Comment by O365Tycho** [comment] 2020-01-28 06:33
I don't know and honestly don't care. Last time I checked it was still
there but It's now 2020 and I gave up on it and the SharePoint app

**Comment by kemesfun** [comment] 2020-01-28 21:13
Because there are not

**Comment by kemesfun** [comment] 2020-01-28 21:15
I wasn't able to reproduce this issue, so I am closing it for now. If this issue occurs and affects more customers then another issue will be opened.

**Comment by corriespondent** [comment] 2020-01-29 00:40
@kemesfun It has been quite a while and I am not sure I have access to the same environment to check this issue. I looked on a different site, and while it seems like the mobile class is sticking around this time, I found that the bottom placeholder did not render when I went into a news page, and the "events" page had improper styling or structure on the main content area so that it wasn't scrolling properly, keeping the footer fixed and floating in the middle of the page as I scrolled down.

**Comment by corriespondent** [comment] 2020-01-29 00:49
@kemesfun I think the event page is a totally separate issue, after looking into it more. It seems like the event page container doesn't allow for scrolling the way that most other pages do. The top is the event page, and there is no height or overflow-y styling, while the main page (bottom) allows for scrolling. If you have a footer rendering in the bottom placeholder, it becomes very evident that this is a problem.
 
![image](https://user-images.githubusercontent.com/23064475/73318348-f7488100-41ed-11ea-88a9-531885cd589a.png)

**Comment by corriespondent** [comment] 2020-01-29 02:05
@kemesfun This seems specific to the event page. I will open a new Github issue and retest the original mobile issue tomorrow.

**Comment by corriespondent** [comment] 2020-01-29 02:12
@kemesfun  https://github.com/SharePoint/sp-dev-docs/issues/5246

**Comment by corriespondent** [comment] 2020-01-29 15:31
@kemesfun I cannot duplicate the original error either. Looks like it might be fixed.

**Comment by kemesfun** [comment] 2020-01-29 16:33
Closing this issue since it can't be duplicated.

**Closed by kemesfun** 2020-01-29 16:33 UTC
Labels: area:spfx-general, status:tracked, type:bug-confirmed
