### ISSUE TITLE
Yeoman Freeze on Windows 10

### ISSUE THREAD

**Issue by marcorocca1973** [SharePoint/sp-dev-docs#4179] opened 2019-06-20 12:59 UTC
Hi All
my dev environment is based on Windows 10 (64bit) client, with installed
- node js 10.16.0
- latest version of yeoman, gulp and SharePoint generator (1.8.2)

But when i create new project for SharePoint online, yeoman "freeze" and nothing happens (see picture). I can only close window.

![spfx](https://user-images.githubusercontent.com/22641502/59850856-85f94380-936b-11e9-9d4a-100d01d7b7c1.png)

I try with other machine with Windows Server 2012 R2 and Windows Server 2016 but results is the same.
Same results when i try to clean npm cache and reinstall all components.

Could you help me?
Thanks
Marco

**Comment by andrewconnell** [comment] 2019-06-20 14:01
A few followup questions:

- Is that (the screenshot) where it freezes?
- Can you run `npm list -g --depth=0`
- Are you running any type of antivirus that could be blocking scripts from running?

**Comment by Edzgarl** [comment] 2019-06-20 15:33
Same here, and I tried to execute the command with parameters but it still freeze.

![image](https://user-images.githubusercontent.com/33093411/59861648-87356b00-9381-11e9-9182-f3beec755bbe.png)

**Comment by rob-windsor** [comment] 2019-06-20 15:55
I can reproduce. I completely refreshed a VM (i.e. reinstalled Node, Yeoman, Gulp, and the SPFx generator) and the generator is freezing when accepting input on the question "Do you want to allow the tenant admin the choice of being able to deploy the solution to all sites immediately without running any feature deployment or adding apps in sites?"

**Comment by cimares** [comment] 2019-06-20 15:55
I'm seeing the same issue.. when I run Yo @microsoft/Sharepoint, it takes around 3 minutes for the Yeoman symbol to show. With the YO Debug variable set, this still takes 3 minutes to show the Debug messages.

Once the generator does display, it stops for a while after the File location choice, then stops completely at the Admin deploy choice.., No keyboard entry seems to do anything.

I've left this one running for about 20 minutes so far.

**Comment by cimares** [comment] 2019-06-20 15:58
npm list -g --depth=0 returns:
+-- @microsoft/generator-sharepoint@1.8.2
+-- gulp@4.0.2
`-- yo@2.0.6

Running yo --version returns the version quickly, but running Yo on it's own to trigger the generator picker takes forever as well. (Although I'm not sure how quick this is usually!)

**Comment by Edzgarl** [comment] 2019-06-20 16:24
Same with Linux ..
♥ Microdobe ♥

**Comment by andrewconnell** [comment] 2019-06-20 17:14
@patmill Seems multiple reports all the sudden coming in about the Yeoman SPFx generator freezing up... aware of this?

**Comment by andrewconnell** [comment] 2019-06-20 17:41
Think we've isolated to the latest version of Yeoman (2.0.6) on Windows. 

Can you guys downgrade and try again?

`npm install -g yo@2.0.2`

**Comment by jefmeyer** [comment] 2019-06-20 17:45
I have the same issue with 2.0.2

**Comment by andrewconnell** [comment] 2019-06-20 17:51
@jefmeyer did you upgrade to a version > 2.0.2, then downgrade to 2.0.2? Or have you never had a version above 2.0.2 installed?

**Comment by jefmeyer** [comment] 2019-06-20 17:55
I just installed Yo 2.0.6 this morning, ran into the issue, saw this thread and then downgraded to 2.0.2

**Comment by andrewconnell** [comment] 2019-06-20 18:06
now starting to smell like a downstream dependency in Yeoman... check this out: https://github.com/yeoman/yeoman/issues/1714

Check all global installs: `npm list -g`
Search for **inquirer** ... check the version. If >= 6.4.0, try installing 6.3.1: `npm i -g inquirer@6.3.1`

I'm on macOS and not having this issue so hard for me to replicate...

**Comment by Tanddant** [comment] 2019-06-20 18:30
Even after a `npm i -g inquirer@6.3.1` i still get the freeze

**Comment by jefmeyer** [comment] 2019-06-20 18:31
@andrewconnell I cleared all the NPM packages, went through the "Setup development" guide again, rolled back yo to 2.0.2 and also the inquire version, but still same freeze issue, checking after each rollback.

**Comment by rob-windsor** [comment] 2019-06-20 18:34
@andrewconnell I installed inquirer@6.3.1 but 6.4.0 is still there as a dependency of Yeoman.

![image](https://user-images.githubusercontent.com/5740654/59872805-922fd180-9368-11e9-9fe1-3b9a5e7c9ad3.png)

**Comment by rob-windsor** [comment] 2019-06-20 18:55
@andrewconnell I dropped down to yo@2.0.2 but inquirer@6.4.0 is still in the dependencies.

![image](https://user-images.githubusercontent.com/5740654/59874071-6b26cf00-936b-11e9-9b6e-c98a9c58f801.png)

**Comment by StfBauer** [comment] 2019-06-20 19:45
@rob-windsor no matter which version 2.0.0 you use this won't work because how yeoman has defined their versions of inquirer in package.json. You have to move back to version 1.x.x.

The easiest way to accomplish this is to execute the following command:

```sh
npm install @microsoft/generator-sharepoint@1 -g
```

This should then installed an older version of the inquirer package and the generator is working again:

<img width="678" alt="Screenshot 2019-06-20 at 21 43 07" src="https://user-images.githubusercontent.com/5503835/59876636-72b69a00-93a4-11e9-9d78-c93e5a41b5bd.png">

SPFx anyway uses a really old version of yeoman so no need to worry or update to the latest version.

**Comment by MickNabewata** [comment] 2019-06-21 06:05
After installing yeoman v1.8.5, spfx generator v1.8.2 has worked.
`npm install yo@1 -g`

thank you for everyone of this thread !

**Comment by MickNabewata** [comment] 2019-06-21 07:08
After installing yeoman v1.8.5, spfx generator v1.8.2 has worked.
`npm install yo@1 -g`

But I saw the another freeze when I run the following command.
`yo @microsoft/sharepoint`

Instead, when I run yo and choose @microsoft/sharepoint, it's work.
![image](https://user-images.githubusercontent.com/43107994/59904392-57986880-943e-11e9-989e-d36f708d0b9c.png)

![image](https://user-images.githubusercontent.com/43107994/59904513-b1992e00-943e-11e9-9333-50bd2ddda03a.png)

thank you for everyone of this thread !

**Comment by marcorocca1973** [comment] 2019-06-21 08:22
@MickNabewata I confirm your test
Command 
yo @microsoft/SharePoint
still not working :(

But working if I choose yo and select:
@microsoft/SharePoint

**Comment by StfBauer** [comment] 2019-06-21 09:23
@marcorocca1973 and @MickNabewata can you please share the output of:

```sh
npm ls inquirer -g
```

Thank you!

It could be that you have to install the generator again after downgrading to 1.8.5.

**Comment by marcorocca1973** [comment] 2019-06-21 09:32
@StfBauer 
this is my output
![inquirer](https://user-images.githubusercontent.com/22641502/59913293-2f960e80-9418-11e9-8140-25a76b45489b.png)

**Comment by cimares** [comment] 2019-06-21 09:54
My home PC has the old generator on it and it's working fine..

![image](https://user-images.githubusercontent.com/7425644/59914780-fc04b580-9412-11e9-9a8e-ad5a324b366d.png)

**Comment by StfBauer** [comment] 2019-06-21 12:45
The mentioned issue with the inquirer package [SBoudrias/Inquirer.js#811](https://github.com/SBoudrias/Inquirer.js/issues/811) is now fixed and closed on their repo. 

To verify it does not affect the @microsoft/generator-sharepoint anymore and it is really fixed I tested it on the following systems:

* Windows 2012 R2
* Windows 2016
* Windows 10

Using the following command line tool:

* cmd
* PowerShell

The way to get it running again should work with the following steps:

**Step 1: uninstall current version (optional)**

This is optional because in general step 2 should update everything to the latest version too.

```sh
npm uninstall -g yo @microsoft/generator-sharepoint
```

**Step 2: Install @latest versions**

```sh
npm install -g yo@latest @microsoft/generator-sharepoint@latest
```

**Step 3: verify inquirer version 6.4.1**

```sh
npm ls inquirer -g
```

This should produce an output like this:

<img width="426" alt="Screenshot 2019-06-21 at 14 41 34" src="https://user-images.githubusercontent.com/5503835/59923061-b48e2180-9432-11e9-94d6-70370d99429e.png">

The key part here is that inquirer version 6.4.0 is not referenced anywhere. This is the faulty version and the root cause of the issue you are facing.

**Comment by marcorocca1973** [comment] 2019-06-21 13:10
Great!
@StfBauer I follow your step and now everything works!
Marco

**Comment by cimares** [comment] 2019-06-21 13:13
Excellent, that should fix it for people following the "set up your development environment for SPFx" guide too then!

**Comment by andrewconnell** [comment] 2019-06-21 13:37
Nice work @StfBauer ... looks like this only affects people who installed / upgraded Yeoman for a specific period of time. New installs starting today won’t have this issue, and if they were affected by it, reinstalling will fix. 

For those new finding this issue, this is not an issue rooted in SPFx / SharePoint’s Yeoman generator. The issue is with a Yeoman dependency (Inquirer) which has since been fixed.

**Closed** 2019-06-21 13:37 UTC
Labels: area:generator, status:fixed

**Comment by roberteisenberg** [comment] 2019-06-21 20:07
I started with the problem mentioned above with the generator freezing on the tenant input question. I then ran npm install @microsoft/generator-sharepoint@1 -g and it started to freeze on the web part name. 
I uninstalled the 10.16.0 node version with NVM. Installed it again. Then followed the instructions to uninstall and reinstall the generator and now the problem is that it only asks me a subset of the questions and does not produce any output.  See current node/npm version info, followed byYeomen generator output, and then Followed by the Inquirer details.
![Node-Info](https://user-images.githubusercontent.com/9244979/59948464-fc0db100-9424-11e9-839a-82838cb0a7ad.PNG)

![Yeoman](https://user-images.githubusercontent.com/9244979/59948419-d97b9800-9424-11e9-8ca8-9b69dcab3ce7.PNG)

![Inquirer](https://user-images.githubusercontent.com/9244979/59948499-1182db00-9425-11e9-901c-0f7148d38ed9.PNG)

**Comment by StfBauer** [comment] 2019-06-21 22:09
@roberteisenberg This only happens when you have a `.yo-rc` file in the folder or above the folder you executed the generator on and is the default behaviour. You basically add a web part or extension to an existing project.

Try it on a clean folder where neither in the folder or above is a `.yo-rc` file.

**Comment by mauricework** [comment] 2019-06-24 15:30
> The mentioned issue with the inquirer package SBoudrias/Inquirer.js#811 is now fixed and closed on their repo.
> To verify it does not affect the @microsoft/generator-sharepoint anymore and it is really fixed I tested it on the following systems:
> 
> Windows 2012 R2
> Windows 2016
> Windows 10
> 
> Using the following command line tool:
> 
> cmd
> PowerShell
> 
> The way to get it running again should work with the following steps:
> Step 1: uninstall current version (optional)
> This is optional because in general step 2 should update everything to the latest version too.
> npm uninstall -g yo @microsoft/generator-sharepoint
> Step 2: Install @latest versions
> npm install -g yo@latest @microsoft/generator-sharepoint@latest
> Step 3: verify inquirer version 6.4.1
> npm ls inquirer -g
> This should produce an output like this:
> 
> The key part here is that inquirer version 6.4.0 is not referenced anywhere. This is the faulty version and the root cause of the issue you are facing.

Thanks a bunch for that.  Was a frustrating day when I decided to try out the instructions for the hello world web part and it hung up.  Monday is going much better...:)

**Comment by andrewconnell** [comment] 2019-06-24 16:02
@mauricework said:
> Monday is going much better

Usually, you follow this statement with _"...said no one ever"_, but you have broken the internet. Nice... :P
