### ISSUE TITLE
[SPLoaderError.loadComponentError]:

### ISSUE THREAD

**Issue by Eyerusalme90** [SharePoint/sp-dev-docs#4257] opened 2019-07-08 14:48 UTC

**Comment by andrewconnell** [comment] 2019-07-08 14:57
Unfortunately, this issue does not have enough detail for us to investigate it & therefore we are closing it. If the issue is still valid, please provide a sufficient amount of detail with some context, repro steps, screen captures, etc... otherwise, there's not much we can do to help you.

**Closed by andrewconnell** 2019-07-08 14:57 UTC
Labels: type:invalid
