### ISSUE TITLE
Webpart missing,Vanishes 1.17/1.17.1/1.17.2

### ISSUE THREAD

**Issue by patrik033** [SharePoint/sp-dev-docs#8966] opened 2023-05-15 06:15 UTC
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [X] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version 1.17-1.17.2
- Node.js version 16.18.1
- etc

### Describe the bug / error

As of last week we can no longer test our webparts. Initially it shows in the workbench but after initially config and reloading the page it "vanishes". No error message is displayed in the console.

We have tryed with a fresh scaffolded project and also any existing project with same result.
As a side note I refreshed the dev cert and that made it work for a brief moment.

### Steps to reproduce

1. Create a new or use an existing project 
2. Run gulp serve
3. Refresh the page

### Expected behavior

To be able to see,use and test the webpart.

**Comment by AJIXuMuK** [comment] 2023-05-15 15:44
Dupe of #8967

**Closed by AJIXuMuK** 2023-05-15 15:44 UTC
Labels: type:bug-suspected, status:duplicate, area:spfx
