### ISSUE TITLE
Do not see my webpart in "Insert" or "Add Webpart" part-picker dialog 

### ISSUE THREAD

**Issue by waltsully** [SharePoint/sp-dev-docs#1399] opened 2018-02-23 20:46 UTC
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ ] Question
- [ ] Typo
- [ x] Bug
- [ ] Additional article idea

> If you are planning to share a new feature request (enhancement / suggestion), please use SP Dev UserVoice at http://aka.ms/sp-dev-uservoice.

#### Expected or Desired Behavior
https://github.com/SharePoint/sp-dev-docs/issues/1188 Walter Sully

#### Observed Behavior
_If you are reporting a bug, please describe the behavior you expected to occur when performing the action. If you are making a suggestion, you can delete this section._

#### Steps to Reproduce
code SPFx TypeScript webpart & tested with SP Pnline Workbench. Packaged & deployed successfully, i.e., part in App Catalog without errors "Deployed" part installed on Site, just no show in par-picker when trying to add to page.

#### Submission Guidelines
![appcatalog](https://user-images.githubusercontent.com/33215029/36616148-ba15c83c-18b0-11e8-80f7-b1cf23819287.png)
![appsfromyourorg](https://user-images.githubusercontent.com/33215029/36616149-ba22f70a-18b0-11e8-93e3-63e2840a9852.png)
![partpicker](https://user-images.githubusercontent.com/33215029/36616150-ba2d32ce-18b0-11e8-923d-6d541ab0dc7c.PNG)
![partproperties](https://user-images.githubusercontent.com/33215029/36616151-ba3b02f0-18b0-11e8-8892-9fcbcf7e8d6a.PNG)
![sitecontents](https://user-images.githubusercontent.com/33215029/36616152-ba48de0c-18b0-11e8-89f1-738c16c45924.PNG)

**Comment by waldekmastykarz** [comment] 2018-02-26 11:13
What version of SPFx did you use to create your solution? Did you include the script files (assets) inside the .sppkg file or are they loaded from some other location (like Azure CDN)?

**Comment by waltsully** [comment] 2018-02-26 13:48
Waldek,

Here’s what I’m seeing:
used :   gulp package-solution –ship


[cid:image001.png@01D3AEDE.7EF0A830]



[cid:image002.png@01D3AEDE.7EF0A830]




[cid:image003.png@01D3AEDE.7EF0A830]



Walter Sully
Progressive Home
2 ASI Way
St. Petersburg, FL 33702


[logo]<https://www.americanstrategic.com/>
(866) 511-0793 x326  wsully@e-ins.net<mailto:wsully@e-ins.net>

**Comment by waltsully** [comment] 2018-02-26 13:48
No CDNs used

**Comment by waltsully** [comment] 2018-02-26 13:55
[cid:image001.png@01D3AEDF.946E4130]

**Comment by waldekmastykarz** [comment] 2018-02-26 14:08
@waltsully I'm afraid your images didn't come through

**Comment by waltsully** [comment] 2018-02-26 14:10
Okay I’ll re-do  as attachments… meanwhile, I’m using npm to get latest basis this Feb 2018 article https://docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/update-latest-packages

**Comment by waltsully** [comment] 2018-02-26 14:13
Waldek, find screen shots as attachments…

**Comment by waltsully** [comment] 2018-02-26 14:14
One more…

**Comment by waldekmastykarz** [comment] 2018-02-26 14:16
@waltsully I'm afraid GitHub doesn't show e-mail attachments

**Comment by waltsully** [comment] 2018-02-26 15:18
https://waltsully.wimi.pro

able to see this shared folder?

**Comment by waldekmastykarz** [comment] 2018-02-26 15:56
Nope, login prompt.

**Comment by waltsully** [comment] 2018-02-26 16:05
Waldek,

The screen shots were of version numbers. Given that there were some “Installed” – “Wanted” -- “Latest” inconsistencies I’ve gone through npm –save updating process so that currently “npm outdate” comes back with no listing.

… at 11:01am ET I’m trying to sort through these errors below which did not appear before the updates

-Walt

TypeScript error(s) occurred.
[11:00:24] 'bundle' errored after 2.64 s
[11:00:24]
[11:00:24] ==================[ Finished ]==================
Error - typescript - src/webparts/workOrder/WorkOrderWebPart.ts(75,8): error TS90010: Type 'SPHttpClient' is not assignable to type 'SPHttpClient'. Two different types with this name exist, but they are unrelated.
Error - typescript - src/webparts/workOrder/WorkOrderWebPart.ts(93,78): error TS2345: Argument of type 'SPHttpClientConfiguration' is not assignable to parameter of type 'SPHttpClientConfiguration'.
Error - typescript - src/webparts/workOrder/WorkOrderWebPart.ts(103,71): error TS2345: Argument of type 'GraphHttpClientConfiguration' is not assignable to parameter of type 'GraphHttpClientConfiguration'.
Error - typescript - src/webparts/workOrder/WorkOrderWebPart.ts(144,99): error TS2345: Argument of type 'HttpClientConfiguration' is not assignable to parameter of type 'HttpClientConfiguration'.
Error - 'typescript' sub task errored after 1.18 s
TypeScript error(s) occurred.
[11:00:25] Project workorder-webpart version: 0.0.1
[11:00:25] Build tools version: 3.2.7
[11:00:25] Node version: v6.11.5
[11:00:25] Total duration: 5.49 s
[11:00:25] Task errors: 5
PS C:\Workspace\workorder-webpart>

**Comment by waltsully** [comment] 2018-02-26 18:49
Waldek,

Well, I have done the SPFx updates and ran  gulp clean and ultimately had to zap node-modules and nmp -install

Now able to  Build, Package and Deploy to SP Online App Catalog. My hosting site let me know “a new version available” and I had it upgrade. All of that to end with the same result of not seeing the part-picker listing my webpart. Btw, I was careful to increment the latest version number and it was reflected in the site contents.

☹
Walt

[13:35:14] Created file: sharepoint\solution\workorder-webpart.sppkg
[13:35:14] Done!
[13:35:14]
[13:35:14] ALL DONE!
[13:35:14]
[13:35:14] Finished subtask 'package-solution' after 123 ms
[13:35:14] Finished 'package-solution' after 130 ms
[13:35:14] ==================[ Finished ]==================
[13:35:15] Project workorder-webpart version: 0.0.1
[13:35:15] Build tools version: 3.2.7
[13:35:15] Node version: v6.11.5
[13:35:15] Total duration: 2.93 s
PS C:\Workspace\workorder-webpart>

**Comment by mcmynn83** [comment] 2018-03-01 18:43
This was resolved yesterday.  It was a duplicate of #775

**Closed by mcmynn83** 2018-03-01 18:43 UTC
