### ISSUE TITLE
Package icon no longer works in 1.12

### ISSUE THREAD

**Issue by weshackett** [SharePoint/sp-dev-docs#6852] opened 2021-03-23 12:52 UTC
## Category

- [x] Bug

## Describe the bug

In 1.11 release it was possible to package an icon for your SP package in the app catalog. Now with 1.12 this fails and doesn't package correctly.

## Steps to reproduce

Basically Chris Kents article https://thechriskent.com/2017/06/19/sharepoint-framework-app-icon/

1) run Yo and create a ReactJS webpart
2) Modify the package-solution.js to add the "icon-path" attribute
3) copy a png icon into 'sharepoint/images/icon.png'
4) gulp bundle
5) gulp package-solution
6) upload to app catalog

ERROR happens

message:
Invalid SharePoint App package. Error: Specified part does not exist in the package.

Packaging an icon for the app is still possible

## Environment details (*development & target environment*)

- **Your Developer Environment**: Windows 10
- **Target Environment**:  SharePoint Online]
- **Framework**:  | Node.js v12]
- **Browser(s)**: [e.g. Chrome v79 | Safari v22 | FireFox v31 | IE v11 | Edge | Chromium Edge v79]
- **Tooling**: [e.g. VS Code | SPFx v1.12.0 
- **Additional details**: *The more context you can provide, the easier it is (and therefore quicker) to help.*

**Comment by VesaJuvonen** [comment] 2021-03-24 12:28
This issue is intended to be part of the upcoming 1.2.1 patch release. Currently we recommend to keep on using 1.11 until further notice. We do apologize the inconvenience.

**Comment by KevinTCoughlin** [comment] 2021-04-06 23:03
Thanks for the report @weshackett. We've identified the regression in tooling and are validating a fix.

**Comment by KevinTCoughlin** [comment] 2021-04-12 18:54
@weshackett can you confirm this issue is fixed in `1.12.1-rc.0` suite of packages e.g. https://www.npmjs.com/package/@microsoft/generator-sharepoint/v/1.12.1-rc.0?

**Comment by KevinTCoughlin** [comment] 2021-04-19 18:32
Ping for external validation this issue has been resolved.

**Comment by weshackett** [comment] 2021-04-23 07:26
Happy for this to be closed

**Closed** 2021-04-23 18:33 UTC
Labels: 1.12.x, Needs: Attention :wave:, area:spfx-general, area:tooling, status:fixed, status:tracked, type:bug-confirmed
