### ISSUE TITLE
Fabric Icon not Rendering in Modern OOB SharePoint Online Document Library web part  (iconName)

### ISSUE THREAD

**Issue by Freddy-Crypto** [SharePoint/sp-dev-docs#4344] opened 2019-07-23 18:31 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Consistent behavior in rendering of icon when used in the library itself and when rendered via the document library webpart.
When i use the OOB list formatting tools and format a list view that contains a Fabric Icon (e.g.: 'PinnedSolid') i expect to see the icon referenced in the 'iconName' in both:

1. List hosting the view and 
2. When that view is rendered on that site's Site Pages when using the OOB Document Library webpart configured to display my formatted view.  

#### Observed Behavior
Observed on 2 x Modern Communication sites (SharePoint Online)a. (1 with app customizer applied and 1 w/o app customizer).
Everything _other_ than the desired icon is rendered correctly in the web part on my site page.

### List View Format in situ (in the library itself):
_**(This is how it should look in both locations)**_
![image](https://user-images.githubusercontent.com/53233826/61737511-fbcb4300-ad4d-11e9-85e4-64ceaee425d6.png)

### List View Format when rendered via OOB modern document library web part on a Site Page in a Communications Site:
![image](https://user-images.githubusercontent.com/53233826/61737587-261d0080-ad4e-11e9-98a3-bff943998a97.png)

View Formatting JSON:

```
{
  "schema": "https://developer.microsoft.com/json-schemas/sp/view-formatting.schema.json",
  "hideSelection": true,
  "hideColumnHeader": true,
  "rowFormatter": {
    "elmType": "div",
    "attributes": {
      "class": "ms-fontSize-l ms-fontWeight-lighter ms-fontColor-themePrimary ms-fontColor-themeDarker--hover"
    },
    "style": {
      "flex-grow": "1",
      "display": "flex",
      "flex-direction": "row",
      "flex-wrap": "nowrap",
      "align-items": "stretch",
      "max-width": "90%",
      "margin-top": "12px",
      "padding": "0px 10px 0px 0px",
      "background-color": "=(if([$isPinned] == true,'#f3f3f3','transparent')"
    },
    "children": [
      {
        "elmType": "div",
        "style": {
          "flex": "1 0 100%",
          "align-items": "stretch",
          "vertical-align": "top",
          "flex-wrap": "nowrap",
          "padding": "0px 0px 0px 0px"
        },
        "children": [
          {
            "elmType": "span",
            "style": {
              "display": "block",
              "height": "100%",
              "float": "left",
              "vertical-align": "top",
              "padding": "5px",
              "width": "17px"
            },
            "attributes": {
              "iconName": "=(if([$isPinned] == true,'PinnedSolid',if([$ContentType] == 'CEO Corner','Glimmer',if([$ContentType] == 'Whats Happening','','CRMCustomerInsightsApp'))))",
              "class": "ms-fontWeight-lighter"
            }
            
          },
          {
            "elmType": "a",
            "style": {
              "color": "#000",
              "font-face": "'Segoe UI', -apple-system, sans-serif",
              "text-align": "left",
              "margin": "0px",
              "text-decoration": "none"
            },
            "attributes": {
              "class": "ms-fontSize-l ms-fontWeight-lighter inherited",
              "href": "[$FileRef]",
              "target": "self",
              "title": "[$Title]"
            },
            "txtContent": "[$Title]"
          }
        ]
      }
    ]
  }
}
```

**Comment by thechriskent** [comment] 2019-08-16 19:45
I am able to reproduce what you are seeing.

The issue is with that specific icon. If you switch your icon to `Cat` for example, you'll find that it renders correctly both in the list view and the webpart. It appears the listview is supporting a more recent version of the UIFabric icon font than the webpart. As a result, certain icons will not work in the webpart.

This needs to be addressed by the author of the webpart (Microsoft). In the meantime, I've verified that `Pin` and `Pinned` both work and might be good alternatives until this is corrected.

**Comment by GrahamMcMynn** [comment] 2019-09-13 23:03
Thank you for your submission. This GitHub issue list is targeted only for developer issues. As your issue is related on out-of-the-box capabilities or features, we cannot unfortunately process is through this channel. Please submit your finding using the Tenant administrator support channels in your tenant or using Premier support, if that’s available for you. Sorry for the inconvenience.

**Closed by GrahamMcMynn** 2019-09-13 23:03 UTC
Labels: Needs: Microsoft Review 👓, area:list-formatting
