### ISSUE TITLE
Variable name mismatch in the last piece of code.

### ISSUE THREAD

**Issue by piotr-kasprzyk** [SharePoint/sp-dev-docs#3949] opened 2019-05-15 10:53 UTC
In the last piece of code given as an example, variable  selectedLocalEmployee is used. Its name should be localEmployee, as it is declared before and used after the using scope.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79010e96-c26f-6d27-8ddc-a6ac79c2935e
* Version Independent ID: 4860a3a9-ab1a-da03-f50c-221dd2049aca
* Content: [Get a quick overview of the SharePoint object model](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/get-a-quick-overview-of-the-sharepoint-object-model)
* Content Source: [docs/sp-add-ins/get-a-quick-overview-of-the-sharepoint-object-model.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/get-a-quick-overview-of-the-sharepoint-object-model.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by nanddeepn** [comment] 2019-05-17 17:49
Hi @piotr-kasprzyk , @andrewconnell , @VesaJuvonen 
The issue is fixed in pull request https://github.com/SharePoint/sp-dev-docs/pull/3984
Please review. Thank you.

**Closed** 2019-05-17 17:55 UTC
Labels: Good First Issue 🏆, area:add-ins, area:docs, help wanted
