### ISSUE TITLE
Requires Premium Flow License 

### ISSUE THREAD

**Issue by kylepdx** [SharePoint/sp-dev-docs#4466] opened 2019-08-14 00:47 UTC
From my (limited) understanding of the Flow licensing, calling Flow from a site design will require a Premium License (P1/P2) because the flow uses the HTTP trigger.    I feel that this should be called out in this document so users are aware that they are going to have a per/user charge in order to use this feature.  

Actually the right answer is to exempt this scenario from requiring a premium connector since this is really just communicating between two O365 applications; but that is another battle. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1afac891-6cf5-1746-6392-8cb61a441770
* Version Independent ID: b5d1f95b-f40b-8d0c-7334-7608a3add9ff
* Content: [Using site designs and Microsoft Flow to track site creation requests](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-trigger-flow-tutorial#feedback)
* Content Source: [docs/declarative-customization/site-design-trigger-flow-tutorial.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-trigger-flow-tutorial.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment] 2019-08-14 15:22
Dupe of #4467

**Closed by andrewconnell** 2019-08-14 15:22 UTC
Labels: status:duplicate
