### ISSUE TITLE
Navigation and edit experience issue when using a full-width zone

### ISSUE THREAD

**Issue by estruyf** [SharePoint/sp-dev-docs#3686] opened 2019-03-26 17:04 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I'm are currently running into the issue that when I navigate to a page which uses a full-bleed web part and put it in edit mode, it will show blank web parts.

It's a bit hard to explain, but here you can see what is happening (using a custom web part):

![edit-wp-issue](https://user-images.githubusercontent.com/2900833/55017517-349e1a00-4ff1-11e9-9823-0328d88931cd.gif)

I'm also able to reproduce it by using only first web parts (hero web part + snippet web part):

![edit-wp-issue-firstparty](https://user-images.githubusercontent.com/2900833/55017590-55ff0600-4ff1-11e9-9dba-2142bd2d04e2.gif)

When opening the developer console, I see the following error:

![Screenshot 2019-03-26 16 32 47](https://user-images.githubusercontent.com/2900833/55017686-85ae0e00-4ff1-11e9-82c2-0def4dac02fa.png)

When removing the full-width zone and web part, it doesn't give this issue.

#### Steps to Reproduce

These are the steps to reproduce it:
- Open a page in you hub
- Do a full page refresh to be sure
- Navigate to a page with a full-bleed zone and web part defined on it
- Edit the page, and you will see that the web parts are rendered blank

**Comment by sebastienlevert** [comment] 2019-03-26 17:32
Adding to this thread a version using 100% OOTB components.

![2019-03-26_13-31-10](https://user-images.githubusercontent.com/7620955/55019584-921f7000-4fcb-11e9-9b70-65f82141ceee.gif)

Thanks!

**Comment by lucabandMSFT** [comment] 2019-05-07 21:31
We think we know where the problem is and we believe we just released a fix that address the issue.
@estruyf  (Elio), can you please check and let us know if the problem still occurs?

Thanks a lot

**Comment by estruyf** [comment] 2019-05-08 01:53
Still seems to occur.

![Screenshot 2019-05-08 11 53 09](https://user-images.githubusercontent.com/2900833/57343755-ec455080-7187-11e9-9587-921926c99fef.png)

**Comment by lucabandMSFT** [comment] 2019-05-08 04:04
k, thanks @estruyf . Mind sharing tenant information? you can do that in the private channel if you want.

**Comment by MRuimerman** [comment] 2019-05-10 06:21
Same problem here, in IE, Edge and Chrome.

**Comment by estruyf** [comment] 2019-05-13 07:35
@lucabandMSFT was mixing up things. This one is not resolved and don't think the other issue is related.

**Comment by estruyf** [comment] 2019-05-13 07:44
@lucabandMSFT this issue seems to be solved. I'm unable to reproduce it.

**Comment by MRuimerman** [comment] 2019-05-13 09:00
@estruyf Yes, it is fixed in the default SharePoint webparts. 
(Not in our own custom webparts but that is probably our problem.)

**Comment by lucabandMSFT** [comment] 2019-05-13 13:54
@estruyf , you guys ok to close this one? also, to be clear, you said that this is a different issue of #3856 , yes?

**Comment by estruyf** [comment] 2019-05-14 10:49
This issue is about the blank web parts when having a full-width zone and that seems to be fixed. So it can be closed. 

Issue #3856 is about some styling which automatically gets applied to web parts in a full width zone. That's not solved yet. I mixed both before, as I was checking the status and replied in the wrong issue.

**Comment by lucabandMSFT** [comment] 2019-05-24 23:51
perfect. closing it. thanks a lot.

**Closed by lucabandMSFT** 2019-05-24 23:51 UTC
Labels: Needs: Attention :wave:, area:framework, area:other, internal:priority, status:tracked, type:bug
