### ISSUE TITLE
Query strings attached to font files cause webpack loader errors

### ISSUE THREAD

**Issue by SteveCurran** [SharePoint/sp-dev-docs#54] opened 2016-08-22 03:52 UTC
I am using a third party plug-in with css files that point to font files that use query strings for versioning and to prevent caching. The "cased-file-loader" that is configured in the ConfiguredWebPackTask.js in the odsp-build-tasks npm package has a regular expression for validating resource files:
 test: /\.(jpg|png|woff|eot|ttf|svg|gif)$/

This expression does not allow for query strings at the end of TTF, EOT or WOFF files. Removing the end of the line restriction $ fixes this.

The task should allow these types of fonts to be loaded into the bundle.

**Comment by iclanton** [comment] 2016-08-22 04:19
If your CSS file is referencing local fonts (i.e. - on your local filesystem) and you expect these files to be re-bundled by Webpack, you shouldn't need cachebreaker querystrings.

The reason we include the end character (`$`) in the regex is to make sure we don't accidentally match something that isn't intended to be an image or font. If a JavaScript file is being referenced and somewhere in the path is one of those extensions, we wouldn't want a `require('./path.png/to/script.js')` to be loaded as if it was an image instead of as a script file.

Are you unable to modify your CSS files? There are ways to get around this, but they're nontrivial. They'll be documented better soon hopefully.

**Comment by StfBauer** [comment] 2016-08-22 12:14
I think this don't refer to the cache breaker breaker because nearly any fail safe web font definition has those query string in their CSS definiton. Those query strings are mostly required for Internet Explorer to render fonts correctly.
If you take a look at the Office 365 Icon font for example you will find those query strings there too.
```
@font-face {
    font-family: 'o365Icons';
    src: url('shelleoticons_e628f1c5.eot?#iefix') format('embedded-opentype'), url('shellwofficons_ff7ed0de.woff') format('woff'), url('shellttficons_2d466a9f.ttf') format('truetype'), url('shellsvgicons_5a84b1c8.svg#web') format('svg');
    font-weight: normal;
    font-style: normal
}
```
The first font definiton has a query string with the value #iefix.
This #iefix is required for [IE Version 6-8](http://blog.fontspring.com/2011/04/best-practices-for-serving-webfonts-to-ie9/) and sometimes for IE9 too.
If you are not targeting those legacy browsers anymore I think it is save to remove this query strings.
The problem is that this needs to be done whenever you add a custom web font to your project.
The web font support in browser are really old and even IE4 supported custom web fonts there was just a long battle between the vendors for the right format.

**Comment by SteveCurran** [comment] 2016-08-22 13:49
These are third party npm packages that contain the fonts. Not a great solution having to go in and modify  the package font file names every time I create a new solution or update the npm package. The additional query string information is standard practice. Surely the regex expression can be modified to handle this scenario just for woff, ttf and eot files?

**Comment by StfBauer** [comment] 2016-08-22 14:17
@SteveCurran Sure especially if they are NPM packages. I wouldn't recommend to rename it especially in case of node_modules. 
Those will not be checked in the source code management system and you need to rename it all the time manually then.
As I said before those query string are an unwritten web standard that should be handled properly be web pack and SPFx from my point of view.

**Comment by iclanton** [comment] 2016-08-23 00:17
This will be fixed in the next drop.

**Comment by nickpape-msft** [comment] 2016-09-02 23:29
Closing this issue as it was addressed in [Drop 2](https://github.com/SharePoint/sp-dev-docs/wiki/Release-Notes-Drop-2). Please re-open if necessary.

**Closed by nickpape-msft** 2016-09-02 23:29 UTC
Labels: Tooling
