### ISSUE TITLE
extensions are not loading properly

### ISSUE THREAD

**Issue by srinutamada** [SharePoint/sp-dev-docs#5006] opened 2019-12-10 10:57 UTC
I am having 2 packages with different command sets. Each command set targeted to one specific document library. When I am accessing the document libraries for the first time, command set are loading properly. But when move back and forth then these commands are not showing propertly.

Steps to reproduce:
1. Create Command-1 for document library Document1
2. Create Command-2 for document library Document2 (Both different solutions)
3. Install both solutions in the app catalog and add respect apps to the targeted site
4. Navigate to Document1 library and you will see Command-1 button
5. Navigate to Document2 library using quick links and you will see Command-2 button
6. Navigate to Document1 library using quick links and you will see Command-2 button. But you supposed to see Command1.

When you run the debug, I noticed that at step 6, Command-1 related logic is not executed. But if I refresh the page then it starts executing it. 

Let me know how to handle it.

**Comment by andrewconnell** [comment] 2019-12-10 12:02
Appears to be a dupe of a known issue that MSFT is working on https://github.com/SharePoint/sp-dev-docs/issues/4054#issuecomment-539724437. We try to limit dupes, so closing per our process.

**Closed** 2019-12-10 12:02 UTC
Labels: area:framework-extensions, status:duplicate

**Comment by srinutamada** [comment] 2019-12-11 04:03
Thanks for update. The reference issue number which you provided is closed. But my extensions are not working. Can you please what needs to be done from my side?

**Comment by andrewconnell** [comment] 2019-12-11 11:39
The issue I referenced is not closed, it is still open.
