### ISSUE TITLE
SPFx sync to teams not working : 403 forbidden error

### ISSUE THREAD

**Issue by arunkumarperumal** [SharePoint/sp-dev-docs#5428] opened 2020-03-06 08:49 UTC
## Category

- [x] Bug

## Describe the bug
Expected or Desired Behavior
I should be able to install an SPFx app in MS Teams on a any tenant.

Observed Behavior
Sync to Teams
After installing a Teams Tab supported app in the tenant App Catalog and clicking the Sync to Teams button in the ribbon, I receive a Failed to sync solution to teams message.

Here's the response via dev tools:

POST <My Tenant App Catalog>/_api/web/tenantappcatalog/SyncSolutionToTeams 400 (Bad Request)

If I dig into the response, I can see that it is actually returning a 403 - Forbidden:

{"error":{"code":"-1, System.Net.WebException","message":{"lang":"en-US","value":"The remote server returned an error: (403) Forbidden."}}}

Steps to Reproduce
Create an SPFx app with "TeamsTab" as a supported host, must be version 1.8(?) or above.
Deploy to tenant app catalog.
Attempt to sync app to Teams.

*Thanks for your contribution! Sharing is caring.*

**Comment by arunkumarperumal** [comment] 2020-03-06 09:05
Seems like the issue started today, yesterday we were able to sync the same app to Teams. @VesaJuvonen can you please help with this issue.

**Comment by PrasadKasireddy** [comment] 2020-03-06 09:27
It seems to be Duplicate of #https://github.com/SharePoint/sp-dev-docs/issues/5425

**Comment by VesaJuvonen** [comment] 2020-03-06 12:48
Let's close this one and use #5425 as the primary one to avoid duplicates.

**Closed by VesaJuvonen** 2020-03-06 12:48 UTC
Labels: Needs: Triage :mag:
