### ISSUE TITLE
Fabric UI - Borders added to controls, ShimmeredDetailsList loading broken

### ISSUE THREAD

**Issue by Encodian** [SharePoint/sp-dev-docs#5780] opened 2020-05-21 17:58 UTC
## Category

- [x] Bug

## Describe the bug

Two issues have appeared on an existing SPFX solution. 
1) Previously transparent borders are now appearing with colour, this is affecting the CommandBar and OverflowSet controls. Noting the class applying the style is sealed within the control.

![image](https://user-images.githubusercontent.com/45834050/82589360-f029f200-9b93-11ea-9882-da790bac0103.png)

2) The ShimmeredDetailsList control loads fine initially but is not displaying the shimmer as you scroll and is randomly rendering items. 

![image](https://user-images.githubusercontent.com/45834050/82589627-544cb600-9b94-11ea-8849-0af3cdb90631.png)

These issues have appeared where the code hasn't been updated. Neither of these issues occurs within the workbench, only once served or deployed to an SPO site.

Have upgraded the project to SPFX 1.10.0... same issue. 

## Expected behaviour
1) The borders should be transparent
2) The shimmer should render and items as you scroll

## Environment details
Tested in Firefox, Chrome and Edge (Latest versions)
SharePoint Online

![image](https://user-images.githubusercontent.com/45834050/82590065-f66c9e00-9b94-11ea-85f6-019f6ffd511c.png)

Thanks in advance

**Comment by Encodian** [comment] 2020-05-26 05:35
Update: The shimmer issue seems to have resolved itself... but the borders are still an issue. The error can be reproduced by creating a brand new project and just adding an affected control to the web part.
Thanks again

**Comment by KevinTCoughlin** [comment] 2020-05-26 19:07
@Encodian asking the same question as in https://github.com/SharePoint/sp-dev-docs/issues/5764#issuecomment-634217688.

- Can you provide the isolated HTML to repro? Is it just a Fabric `<Button />` that will exhibit this problem?
- Does the problem remain after following this guidance to load legacy Fabric core styles? https://github.com/microsoft/fluentui/issues/13112#issuecomment-627632927

**Comment by Encodian** [comment] 2020-05-27 08:22
I just scaffolded a new 1.10.0 solution... relevant code below, where I've just added the CommandBar control and some data:
![image](https://user-images.githubusercontent.com/45834050/82995495-8ed2aa80-9ffb-11ea-922f-6571ab113ef0.png)
Via the workbench:
![image](https://user-images.githubusercontent.com/45834050/82995512-942ff500-9ffb-11ea-9202-5fbbf15d4465.png)
Via SharePoint post packaging and deployment:
![image](https://user-images.githubusercontent.com/45834050/82995529-9a25d600-9ffb-11ea-9b16-9309cc524f89.png)

I will check the questions/suggestions and update shortly.

**Comment by Encodian** [comment] 2020-05-27 09:37
@KevinTCoughlin 
I have tried the suggested amendments which do not fix the issue.

1. Added '"loadLegacyFabricCss": true' to the webpart manifest
2. And then added the following to the render method:
 SPComponentLoader.loadCss('https://static2.sharepointonline.com/files/fabric/office-ui-fabric-core/11.0.0/css/fabric.min.css');

No change, issue persists.

**Comment by AJIXuMuK** [comment] 2020-06-24 04:30
The only workaround that helped me is to add CSS overrides like:
```CSS
.commandBar {
  :global {
    .ms-Button--commandBar {
      border: 0 none transparent;
    }
  }
}
```

**Comment by Encodian** [comment] 2020-07-02 06:57
@KevinTCoughlin @andrewconnell Sorry to chase both, I realise this isn't a major issue but it'd be great to get an update if possible?

**Comment by tstojecki** [comment] 2020-07-07 19:27
Same story here, this became an issue back in 1.9.1, upgrading to 1.10.0 and adding the import for "office-ui-fabric-core/dist/css/fabric.min.css" did not help

![image](https://user-images.githubusercontent.com/1306272/86832562-9e342180-c098-11ea-9663-8b303d1b31b4.png)

**Comment by yukumura** [comment] 2020-07-13 12:33
Same problem. Any suggestion?

**Comment by StfBauer** [comment] 2020-09-07 20:53
Microsoft has recently upgraded the Office UI Fabric version on SharePoint Online to Fluent UI. For future and a current project that shows this issue, I would recommend considering upgrading to a newer version.

Checking the code on the local workbench might not show this issue because the workbench still used Office UI Fabric version 6.0.

**Comment by patmill** [comment] 2021-11-16 19:53
With the shimmer issue fixed, I'm marking this as a dupe of https://github.com/SharePoint/sp-dev-docs/issues/5764

**Closed by patmill** 2021-11-16 19:53 UTC
Labels: area:spfx, status:to-be-reviewed, area:fluent-ui, Needs: Attention :wave:
