### ISSUE TITLE
Following documentation generates an error: Cannot find external "jqueryui"

### ISSUE THREAD

**Issue by metkhoo** [SharePoint/sp-dev-docs#6857] opened 2021-03-24 11:40 UTC
## Category

- [x] Bug

## Describe the bug
Following the exact steps in the documentation throws up an error when running "gulp serve"

**Error - [webpack] 'dist':
Did not find linked external "jqueryui" for bundle "j-query-web-part"**

consequently the web part does not show to be added to the local workbench. 

## Steps to reproduce
Follow exact steps in documentation:

https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/add-jqueryui-accordion-to-web-part.md

## Expected behavior
I expected that following the exact instructions in the document to work as described.

## Environment details (*development & target environment*)
- Local OS = Windows 10
- For SharePoint online
- Framework = 64 bit node.js v12.21.0
- Browser = Google Chrome Version 89.0.4389.90 
- Tooling = VS Code v1.54.3
- SharePoint framework = 1.12.0

### Additional context
The content of my files is as follows:

**config.json**
```
{
  "$schema": "https://developer.microsoft.com/json-schemas/spfx-build/config.2.0.schema.json",
  "version": "2.0",
  "bundles": {
    "j-query-web-part": {
      "components": [
        {
          "entrypoint": "./lib/webparts/jQuery/JQueryWebPart.js",
          "manifest": "./src/webparts/jQuery/JQueryWebPart.manifest.json"
        }
      ]
    }
  },
  "externals": {
    "jquery": "node_modules/jquery/dist/jquery.min.js",
    "jqueryui": "node_modules/jqueryui/jquery-ui.min.js"
  },
  "localizedResources": {
    "JQueryWebPartStrings": "lib/webparts/jQuery/loc/{locale}.js"
  }
}
```

**jQueryWebPart.ts**
```
import { Version } from '@microsoft/sp-core-library';
import {
  IPropertyPaneConfiguration,
  PropertyPaneTextField
} from '@microsoft/sp-property-pane';
import { BaseClientSideWebPart } from '@microsoft/sp-webpart-base';
import { escape } from '@microsoft/sp-lodash-subset';

import styles from './JQueryWebPart.module.scss';
import * as strings from 'JQueryWebPartStrings';

import MyAccordionTemplate from './MyAccordionTemplate';
import * as jQuery from 'jquery';
import 'jqueryui';
import { SPComponentLoader } from '@microsoft/sp-loader';

export interface IJQueryWebPartProps {
  description: string;
}

export default class JQueryWebPart extends BaseClientSideWebPart<IJQueryWebPartProps> {
  public constructor() {
    super();
  
    SPComponentLoader.loadCss('//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css');
  }

  public render(): void {
    this.domElement.innerHTML = MyAccordionTemplate.templateHtml;
    
    const accordionOptions: JQueryUI.AccordionOptions = {
      animate: true,
      collapsible: false,
      icons: {
        header: 'ui-icon-circle-arrow-e',
        activeHeader: 'ui-icon-circle-arrow-s'
      }
    };
    jQuery('.accordion', this.domElement).accordion(accordionOptions);
  }

  protected get dataVersion(): Version {
    return Version.parse('1.0');
  }

  protected getPropertyPaneConfiguration(): IPropertyPaneConfiguration {
    return {
      pages: [
        {
          header: {
            description: strings.PropertyPaneDescription
          },
          groups: [
            {
              groupName: strings.BasicGroupName,
              groupFields: [
                PropertyPaneTextField('description', {
                  label: strings.DescriptionFieldLabel
                })
              ]
            }
          ]
        }
      ]
    };
  }
}
```
**package.json**
```
{
  "name": "jquery-webpart",
  "version": "0.0.1",
  "private": true,
  "main": "lib/index.js",
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@microsoft/sp-core-library": "1.12.0",
    "@microsoft/sp-lodash-subset": "1.12.0",
    "@microsoft/sp-office-ui-fabric-core": "1.12.0",
    "@microsoft/sp-property-pane": "1.12.0",
    "@microsoft/sp-webpart-base": "1.12.0",
    "jquery": "^2.2.4",
    "jqueryui": "^1.11.1"
  },
  "devDependencies": {
    "@microsoft/rush-stack-compiler-3.7": "0.2.3",
    "@microsoft/sp-build-web": "1.12.0",
    "@microsoft/sp-module-interfaces": "1.12.0",
    "@microsoft/sp-tslint-rules": "1.12.0",
    "@microsoft/sp-webpart-workbench": "1.12.0",
    "@types/jquery": "^2.0.56",
    "@types/jqueryui": "^1.12.15",
    "@types/webpack-env": "1.13.1",
    "ajv": "~5.2.2",
    "gulp": "~4.0.2"
  }
}
```

*Thanks for your contribution! Sharing is caring.*

**Comment by bcameron1231** [comment] 2021-03-24 14:59
Hi, thank you for submitting this! Can you confirm if this is happening in SPFx 1.11? 

Currently, as there have been multiple issues, the recommendation from Microsoft is to roll back SPFx 1.12 and continue using 1.11.

**Comment by metkhoo** [comment] 2021-03-24 17:34
Hi, I tried it with 1.11.0.
followed documentation exactly 
C>gulp serve 
gives the following error:
```
ReferenceError: primordials is not defined
    at fs.js:36:5
    at req_ (C:\devext\jquery-webpart\node_modules\natives\index.js:143:24)
    at Object.req [as require] (C:\devext\jquery-webpart\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (C:\devext\jquery-webpart\node_modules\gulp\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\devext\jquery-webpart\node_modules\gulp\node_modules\graceful-fs\graceful-fs.js:3:27)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
```
**package.json file**
(to prove I am using 1.11.0)
```
{
  "name": "jquery-webpart",
  "version": "0.0.1",
  "private": true,
  "main": "lib/index.js",
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@microsoft/sp-core-library": "1.11.0",
    "@microsoft/sp-lodash-subset": "1.11.0",
    "@microsoft/sp-office-ui-fabric-core": "1.11.0",
    "@microsoft/sp-property-pane": "1.11.0",
    "@microsoft/sp-webpart-base": "1.11.0",
    "jquery": "^2.2.4",
    "jqueryui": "^1.11.1"
  },
  "devDependencies": {
    "@microsoft/rush-stack-compiler-3.3": "0.3.5",
    "@microsoft/sp-build-web": "1.11.0",
    "@microsoft/sp-module-interfaces": "1.11.0",
    "@microsoft/sp-tslint-rules": "1.11.0",
    "@microsoft/sp-webpart-workbench": "1.11.0",
    "@types/chai": "3.4.34",
    "@types/es6-promise": "0.0.33",
    "@types/jquery": "^2.0.56",
    "@types/jqueryui": "^1.12.15",
    "@types/mocha": "2.2.38",
    "@types/webpack-env": "1.13.1",
    "ajv": "~5.2.2",
    "gulp": "~3.9.1"
  }
}

```

**Comment by KevinTCoughlin** [comment] 2021-03-24 18:36
Duplicate of https://github.com/SharePoint/sp-dev-docs/issues/6833. Rollback to `1.11.0` until the linked issue is fixed in next release.

**Closed** 2021-03-24 18:37 UTC
Labels: status:duplicate
