### ISSUE TITLE
Provider Hosted AddIn has incorrect reference of AppForSharePointOnlineWebToolkit with Visual Studio 2019

### ISSUE THREAD

**Issue by ravick4u** [SharePoint/sp-dev-docs#5683] opened 2020-05-07 17:58 UTC
Hello,

So I have created a test provider hosted app with Visual Studio 2019 and it adds below list of packages in "packages.config"

    &lt;?xml version="1.0" encoding="utf-8"?&gt;
    &lt;packages&gt;
      &lt;package id="AppForSharePointOnlineWebToolkit" version="4.0.0" targetFramework="net472" /&gt;
      &lt;package id="jQuery" version="3.4.1" targetFramework="net472" /&gt;
      &lt;package id="Microsoft.CodeDom.Providers.DotNetCompilerPlatform" version="2.0.1" targetFramework="net472" /&gt;
      &lt;package id="Microsoft.IdentityModel.JsonWebTokens" version="5.3.0" targetFramework="net472" /&gt;
      &lt;package id="Microsoft.IdentityModel.Logging" version="5.3.0" targetFramework="net472" /&gt;
      &lt;package id="Microsoft.IdentityModel.Tokens" version="5.3.0" targetFramework="net472" /&gt;
      &lt;package id="Microsoft.SharePointOnline.CSOM" version="16.1.9021.1200" targetFramework="net472" /&gt;
      &lt;package id="Newtonsoft.Json" version="10.0.1" targetFramework="net472" /&gt;
      &lt;package id="System.IdentityModel.Tokens.Jwt" version="5.3.0" targetFramework="net472" /&gt;
    &lt;/packages&gt;

After I checked in my code another developer started working on the same solution. In order for him to work on this solution, he tried to restore the package. But restore failed for "AppForSharePointOnlineWebToolkit". In our investigation, we found that the latest version for this is the package is "3.1.5" and not "4.0.0". We haven't made any changes with the template and this one came with Visual Studio 2019. See below lin of NuGet package

https://www.nuget.org/packages/AppForSharePointOnlineWebToolkit/

I also performed the same test with Visual Studio 2017 and the version for "AppForSharePointOnlineWebToolkit" is "3.1.5". On top of that, there are fewer references for the packages.

    &lt;?xml version="1.0" encoding="utf-8"?&gt;
    &lt;packages&gt;
      &lt;package id="AppForSharePointOnlineWebToolkit" version="3.1.5" targetFramework="net472" /&gt;
      &lt;package id="jQuery" version="1.9.1" targetFramework="net472" /&gt;
      &lt;package id="Microsoft.CodeDom.Providers.DotNetCompilerPlatform" version="2.0.0" targetFramework="net472" /&gt;
      &lt;package id="Microsoft.SharePointOnline.CSOM" version="16.1.5903.1200" targetFramework="net472" /&gt;
    &lt;/packages&gt;

 - Does anyone has faced this issue? If yes can you let me know what was the fix you have gone with?
 - Is changing version from "4.0.0" to "3.1.5" is ok?
 - Is this a bug with the template that comes with Visual Studio 2019?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ceb8bf6d-8d2b-d206-1e13-abe801b09894
* Version Independent ID: 79012988-7caa-a0ba-d7de-91f514550bb3
* Content: [Get started creating provider-hosted SharePoint Add-ins](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/get-started-creating-provider-hosted-sharepoint-add-ins)
* Content Source: [docs/sp-add-ins/get-started-creating-provider-hosted-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/get-started-creating-provider-hosted-sharepoint-add-ins.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment] 2020-05-08 15:21
Duplicate of #5468

**Closed** 2020-05-09 12:27 UTC
Labels: area:docs-comment, status:duplicate
