### ISSUE TITLE
SPFx v1.4 Asset Bundle Externals

### ISSUE THREAD

**Issue by WhereCodeGoesToDie** [SharePoint/sp-dev-docs#1169] opened 2017-12-20 14:38 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Add jquery to externals but still be able to use use Asset Packaging

#### Observed Behavior
When adding jQuery to a package via the externals in config.json the package while it creates when added to SharePoint App Catalog and then in a site the Web Part does not appear.

#### Steps to Reproduce
1. Create Web Part using SPFx v1.4
2. Add Jquery to externals in config.json
   "externals": {
        "jquery": "https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"
    },
3. Add import to the HelloWorldWebPart.ts
    import 'jquery';
4. Run the command gulp bundle --ship
5. Run the command gulp package-solution --ship
6. Upload the package to the App Catalog
  Presented with the following in the dialog (Screenshot attached)
   This client side solution will get content from the following domains:
     HTTPS://SPCLIENTSIDEASSETLIBRARY/;
     https://ajax.googleapis.com
  Instead of the expected: 
     This client side solution will get content from the following domains:
     SharePoint Online
[XML Bundles.txt](https://github.com/SharePoint/sp-dev-docs/files/1575851/XML.Bundles.txt)

7. The package will be added and can be deployed on a site however the web part does not appear to 
    be added.

![image](https://user-images.githubusercontent.com/16688354/34211888-711ff0fe-e592-11e7-8495-d369e99c61b1.png)

Attached are the created XML files

[XML Bundles.txt](https://github.com/SharePoint/sp-dev-docs/files/1575875/XML.Bundles.txt)

**Comment by joelfmrodrigues** [comment] 2017-12-20 23:41
@WhereCodeGoesToDie  try to use jQuery in the same way as described on the [documentation](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/add-jqueryui-accordion-to-web-part)
I have done this last week and was working fine for me, so it could be down to how you are setting things up (maybe the "externals" configuration?)

**Comment by waldekmastykarz** [comment] 2017-12-21 12:07
@joelfmrodrigues still, it should be possible to load jQuery from a CDN.

**Comment by dgaeta** [comment] 2018-08-16 21:15
@waldekmastykarz just trying to diagonse where the problem is:

- Did you add the app to your site? (i.e. click the gears icon, click add an app, click your webpart - this will add the webpart to your site)
- Does the webpart not show in the toolbox?
- Does the webpart show in the toolbox, but not in the canvas when you add it?

Thanks!

**Comment by waldekmastykarz** [comment] 2018-08-17 05:02
Ping @WhereCodeGoesToDie ☝️

**Comment by dgaeta** [comment] 2018-08-20 16:52
Closing this issue since it appears to no longer be a problem. Feel free to reopen if you are still experiencing a bug.

**Closed by dgaeta** 2018-08-20 16:52 UTC
Labels: area:framework, area:tooling, status:tracked, type:bug
