### ISSUE TITLE
List View web part is not rendering Json Formatting properly in pages

### ISSUE THREAD

**Issue by asifahmeds** [SharePoint/sp-dev-docs#5213] opened 2020-01-24 09:24 UTC
## JSON Formatting and List view web part

# Issue with tiles view when using json formatting in List view web part.

## The tiles view with json formatting is all scattered with List View web part when it is used in modern page. Also the view headers are not hiding (hideColumnHeader is not working).

This is issue occurring again and again. This is reference to recently closed issue which is related. https://github.com/SharePoint/sp-dev-docs/issues/3537

**Comment by Abenold** [comment] 2020-01-24 09:34
it's back again, that was a "short" working fix ;(

**Comment by PrasadKasireddy** [comment] 2020-01-24 09:37
#3537

**Comment by harshdamaniahd** [comment] 2020-01-24 09:38
> Yesterday :
> ![image](https://user-images.githubusercontent.com/11780473/73055081-427c3000-3e8c-11ea-959b-b144244a1119.png)
> Today:
> ![image](https://user-images.githubusercontent.com/11780473/73055183-79eadc80-3e8c-11ea-8699-552de85b192d.png)
> 
> Additionally the column header is not not hiding
> `{ "hideListHeader": true, "hideSelection": true, "hideColumnHeader":true "rowFormatter": { "elmType": "div", "attributes": { "class": "ms-bgColor-white ms-borderColor-themePrimary--hover" }, "style": { "margin": "0px 0", "padding": "3PX", "border": "none", "cursor": "pointer", "float": "left" }, "children": [ { "elmType": "a", "attributes": { "href": "[$Link]", "target": "_blank" }, "style": { "width": "100%", "background-color": "transparent", "display": "inline-flex", "text-decoration": "none" }, "children": [ { "elmType": "div", "attributes": { "class": "ms-borderColor-themePrimary ms-bgColor-neutralLighter" }, "style": { "min-width": "75px", "display": "flex", "border-width": "1px", "border-style": "solid", "box-sizing": "border-box", "align-items": "center" }, "children": [ { "elmType": "div", "attributes": { "iconName": "Link12", "class": "ms-fontSize-32 ms-fontWeight-regular ms-fontColor-black" }, "style": { "flex": "none", "padding-top": "13px", "padding-left": "22px", "height": "30px", "font-size": "28px", "padding-bottom": "9px" } } ] }, { "elmType": "div", "attributes": { "class": "ms-fontColor-themePrimary ms-borderColor-themePrimary ms-fontSize-m" }, "style": { "border-width": "1px", "border-style": "solid", "box-sizing": "border-box", "width": "300px", "text-align": "left", "HEIGHT": "28PX", "color": "black", "overflow": "hidden", "padding-left": "10px", "padding-top": "6px" }, "children": [ { "elmType": "div", "txtContent": "[$Link.desc]", "style": { "height": "24px" }, "attributes": { "title": "[$Link.desc]" } } ] } ] } ] } }`

**Comment by PrasadKasireddy** [comment] 2020-01-24 10:37
@andrewconnell  - it is related to list-formatting area  , This is a previously opened issue that was closed (https://github.com/SharePoint/sp-dev-list-formatting/issues/204) but it is still an issue and needs to be tracked/fixed by the team

**Comment by andrewconnell** [comment] 2020-01-24 10:39
@PrasadKasireddy thanks... it doesn't help when all the default sections were removed from this issue when it was submitted making it unclear what this is (bug/question/discussion/etc).

**Comment by harshdamaniahd** [comment] 2020-01-24 10:41
> @PrasadKasireddy thanks... it doesn't help when all the default sections were removed from this issue when it was submitted making it unclear what this is (bug/question/discussion/etc).

https://github.com/SharePoint/sp-dev-list-formatting/issues/123

This is where it started.It was fixed before

**Comment by asifahmeds** [comment] 2020-01-24 12:38
> @PrasadKasireddy thanks... it doesn't help when all the default sections were removed from this issue when it was submitted making it unclear what this is (bug/question/discussion/etc).

Hello

**Comment by asifahmeds** [comment] 2020-01-24 12:47
> @PrasadKasireddy thanks... it doesn't help when all the default sections were removed from this issue when it was submitted making it unclear what this is (bug/question/discussion/etc).

Hello @andrewconnell , I have  this issue from my mobile. That is why I couldn't type properly.
But this is new not completely new issue. This issue occured in last year and 2 days ago too. 
 The reference issue I have added gives clear information.
I think this issue should be given high priority as the earlier fix is not working and team might know the route cause already. Our users are loosing confidence on SharePoint design due to this.

**Comment by asifahmeds** [comment] 2020-01-24 13:00
The issue seems to be fixed now. Can any one from Ms SharePoint team confirm that a permanent fix is applied? Or Should we wait and see for stability?

**Comment by harshdamaniahd** [comment] 2020-01-24 13:02
Yes confirmed....fixed...

**Comment by PrasadKasireddy** [comment] 2020-01-24 13:15
> The issue seems to be fixed now. Can any one from Microsoft support team confirm that a permanent fix is applied before closing this? Or Should we wait and see for stability?
Agree @asifahmeds as it issue is not stable, it was happen yesterday as well. it is happening intermittently.

**Comment by Abenold** [comment] 2020-01-24 13:24
seems to work again (for now) hope it keeps working.

**Comment by andrewconnell** [comment] 2020-01-24 15:15
As you say it's working, there's nothing to investigate... thus closing. Feel free to open a new issue if it happens again.

@all - In the future, please consider the following points. These things make it easier to help (1) identify, (2) triage, (3) research, and (4) troubleshoot if there is a real error going on.

As @VesaJuvonen commented in the other issue https://github.com/SharePoint/sp-dev-docs/issues/3537#issuecomment-577335878, the more detail, formatting code, etc you can provide, the easier it is to help. But that was never shared in the referenced issue nor has it been fully included in this one either.

@harshdamaniahd above in your reply, https://github.com/SharePoint/sp-dev-docs/issues/5213#issuecomment-578058323, you have a blob of JSON... please refer to our wiki page on [How to create a good issue: Use code formatting (inline & blocks)](https://github.com/SharePoint/sp-dev-docs/wiki/How-to-Create-Good-Issues#use-code-formatting-inline--blocks) on how to properly format the JSON. As you pasted it, it's near impossible to read.

@asifahmeds said:
> I have submitted this issue from my mobile. That is why I couldn't type properly.

Understood, but that doesn't change the fact that without that detail, not enough detail/context was shared making it near impossible to move forward on this.

**Closed by andrewconnell** 2020-01-24 15:15 UTC
Labels: area:list-formatting

**Comment by asifahmeds** [comment] 2020-01-27 09:29
Issue is back again :( . I don't understand why no celar information is being given about this issue.

**Comment by PrasadKasireddy** [comment] 2020-01-27 09:36
@harshdamaniahd  - Is this issue back again today please confirm.

**Comment by PrasadKasireddy** [comment] 2020-01-27 09:38
https://github.com/SharePoint/sp-dev-list-formatting/issues/123#issuecomment-578656667

**Comment by harshdamaniahd** [comment] 2020-01-27 10:00
> @harshdamaniahd - Is this issue back again today please confirm.

Yes.

**Comment by andrew-lott** [comment] 2020-01-27 10:16
This issue has appeared on my tenant.

**Comment by FredrikEkstroem** [comment] 2020-01-27 10:28
Confirm, issue is back.
[Related issue with simple reproduction steps ](https://github.com/SharePoint/sp-dev-list-formatting/issues/208)

**Comment by andrewconnell** [comment] 2020-01-27 11:53
@FredrikEkstroem https://github.com/SharePoint/sp-dev-docs/wiki/Issue-List#our-approach-to-closed-issues

**Comment by furler** [comment] 2020-01-28 21:34
> @FredrikEkstroem https://github.com/SharePoint/sp-dev-docs/wiki/Issue-List#our-approach-to-closed-issues

That's all very well, but this issue has had multiple posts, all getting prematurely closed. Perhaps leave the dust to settle so that people can confirm it's been fixed for more than a day before troubles appear again?

**Comment by Divyeshkotadia** [comment] 2020-02-04 19:59
@andrewconnell Let me clear the air, the header issue is still reproducible on my tenant. Please guide team to fix it.

**Comment by VesaJuvonen** [comment] 2020-02-05 07:08
@Divyeshkotadia https://github.com/SharePoint/sp-dev-docs/wiki/Issue-List#our-approach-to-closed-issues

**Comment by FredrikEkstroem** [comment] 2020-02-06 10:18
Looks like there is a fix coming in 2-3 weeks #5251
