### ISSUE TITLE
SPFX ListView Command Set Extension not loading

### ISSUE THREAD

**Issue by veerasekarmeiyappan** [SharePoint/sp-dev-docs#4394] opened 2019-07-30 16:31 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
On "Gulp serve" SPFX ListView Command Set should redirect to SP Site list view page and should render a new button named "Command Two" on the list view command tool bar

#### Observed Behavior
On "Gulp serve" SPFX ListView Command Set redirected to SP Site list view page as expected but didn't render the new button "Command Two" on the list view command tool bar. No errors or warnings found in page and VS code Terminal window

#### Steps to Reproduce

1. Created a new SPFX ListView Command Set as in Microsoft site
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api 
2. Opened in VS code
4. Updated the PageURL in "serve.json". No extra code added.
5. Ran "Gulp serve" in cmd
6. Browser will open the SP Online site list view "allitems.aspx". Click "Load Debug Scripts" in the "Allow debug scripts" pop up window
7. The list view will load as in OOTB view but the expected button "Command Two" was not available

#### Submission Guidelines
Sure this is not a big bug as it has worked earlier for many users, may be a regression bug.
But blocked in creating such extension at all. 
SPFX extension also didn't work here is the open issue https://github.com/SharePoint/sp-dev-docs/issues/4374 

Thanks for your contribution! Sharing is caring.

**Comment by veerasekarmeiyappan** [comment] 2019-07-30 23:15
Here is the spfx listviewcommandset project code I used. I have removed the nodemodules folder due to space.
https://github.com/veerasekarmeiyappan/SPFXIssues/invitations

**Comment by JonathanJourdan** [comment] 2019-07-31 11:50
Same problem here https://github.com/SharePoint/sp-dev-docs/issues/4338 and here https://github.com/SharePoint/sp-dev-docs/issues/4219
I wait a fix about microsoft.... causing some development issue...

**Comment by GrahamMcMynn** [comment] 2019-08-21 17:30
Root cause is fixed, and there is still an Edge issue opened, closing this bug.

**Closed by GrahamMcMynn** 2019-08-21 17:30 UTC
Labels: area:framework-extensions
