### ISSUE TITLE
Microsoft Graph is not work in SPFx web part when enabling Multi-Geo capabilities

### ISSUE THREAD

**Issue by karamem0** [SharePoint/sp-dev-docs#5731] opened 2020-05-14 04:52 UTC
## Category

- [x] Bug

## Describe the bug

Deploy an SPFx web part that uses the Microsoft Graph API to a SharePoint Online tenant with Multi-Geo enabled. There is no response when calling the Microsoft Graph API.

## Steps to reproduce

1. Enable Multi-Geo feature in SharePoint Online
1. Deploy an SPFx web part using Microsoft Graph API
1. Approve Microsoft Graph API at SharePoint admin center
1. Add the SPFx web part to a site page

## Expected behavior

There is an Azure AD Application called "SharePoint Online Client Extensibility Web Application Principal" for calling APIs in SPFx. The SharePoint URLs configured as Multi-Geo are not set as the redirect URIs in the application. If Adding Multi-Geo URLs, it works.

## Environment details (*development & target environment*)

- **Target Environment**: SharePoint Online
- **Tooling**: SPFx v1.10.0
- **Additional details**: Multi-Geo is enabled

**Comment by MrTantum** [comment] 2020-05-15 10:14
I observed the same behaviour at #5688

**Comment by andrewconnell** [comment] 2020-05-29 18:52
Agreed with @MrTantum ... this appears to be a dupe of #5688

**Closed** 2020-05-29 18:52 UTC
Labels: status:duplicate
