### ISSUE TITLE
Tenant properties API GetStorageEntity not authorized to External Users

### ISSUE THREAD

**Issue by luismanez** [SharePoint/sp-dev-docs#1137] opened 2017-12-11 16:10 UTC
#### Category
- [ ] Question
- [ ] Typo
- [ X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
You can get a tenant property value using REST API (GetStorageEntity) even when the user is an external user.

#### Observed Behavior
I´m getting an _UnauthorizedAccessException_ 

#### Steps to Reproduce
- Add a tenant property
- Share a site with an external user, and log into the site
- From an spfx webpart, do a REST call to: 
```ps
.../sites/SITE/_api/web/GetStorageEntity('PROPERTY_KEY')
```

you will get an _UnauthorizedAccessException_
Same steps with a "normal" user works as expected.

I guess this is because the Tenant properties are stored in the App Catalog site, where the external user has no access. I think it shouldn´t be the case, as a developers, we want to get Tenant properties from code, even if the user is an external user. Anyway, if this is by design, you should add the documentation and specify it

Thanks!

**Comment by VesaJuvonen** [comment] 2017-12-15 15:03
Thx Luis, this is clearly a bug in the API caused by lack of elevation. The issue has been logged and scheduled to be addressed in a relatively fast timeline. Due SPO freeze period during holiday season, you can expect this to get fixed during January.

**Comment by luismanez** [comment] 2017-12-16 18:58
Thanks for the detailed info Vesa, very appreciate it!

**Comment by mcmynn83** [comment] 2018-03-07 00:36
@luismanez - sorry to take so long to fix this.  A fix is now being made and it should start rolling out to servers around the 26th of March.

**Comment by luismanez** [comment] 2018-03-08 20:15
Thanks @mcmynn83, great news!

**Comment by mcmynn83** [comment] 2018-03-08 20:59
I am closing this issue, however, if it still doesn't work after the 26th please send me a message and I will re-open it. It has been validated in our test environments.

**Comment by sortegamartin** [comment] 2018-04-26 12:26
@mcmynn83 - This problem keeps happening. When trying to recover a tenant property with an external user, the call returns an error 403. Is there a date planned to solve this bug?

**Comment by VesaJuvonen** [comment] 2018-04-26 15:39
Reopen based on Graham's comment.

**Comment by mcmynn83** [comment] 2019-05-10 21:13
Sorry this got lost and I didn't look at it.  That being said, I just revalidated teh scenario and I am able to get tenant storage properties as an external user.  Could you please let me know in what scenario this is not working?   

As a logged in external user I just called _api/web/getstorageentity('Test') and I get that data returned to me.

**Closed** 2019-05-24 23:00 UTC
Labels: Needs: Author Feedback, area:framework, no-recent-activity, status:tracked, type:bug

**Comment by heinrich-ulbricht** [comment] 2019-07-10 09:11
Tested this successfully as well:
* tenant-scoped tenant property
* accessing it via REST with guest accounts works (tested organizational guest and guest with Microsoft account)
