### ISSUE TITLE
The target attribute of <a> elements seem to get ignored

### ISSUE THREAD

**Issue by estruyf** [SharePoint/sp-dev-docs#1582] opened 2018-04-03 14:57 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When creating an <a> element with a target set to `_blank` to open in a new tab is ignored. When clicking on the link, it opens the page in the current window.

#### Steps to Reproduce

- Create a link: `<a href="https://..." target="_blank">Link</a>`
- Click on the link and it will open in the current page.

**Comment by VesaJuvonen** [comment] 2018-04-03 17:11
Hi Elio, can you provide slightly more information on where this was done. Was this a page or a custom web part or something else? Classic / modern etc? Currently that looks like a browser issue but assuming that there's something else behind, which simply was not shared. Thx.

**Comment by estruyf** [comment] 2018-04-05 15:38
Sure @VesaJuvonen, my links are created in a web part as follows:

```
<a href="https://tenant.sharepoint.com/sites/sitename/SitePages/Test-page-1.aspx" target="_blank">Test page 1</a>
<a href="https://tenant.sharepoint.com/sites/sitename/SitePages/Test-page-2.aspx" target="_blank">Test page 2</a>
```

If the web part renders and I click on the link, it does not open the page in a new tab, instead, it will open it in the current one. Here is an example of what I see:

![show-target-prob1](https://user-images.githubusercontent.com/2900833/38375989-d0d897fe-38f7-11e8-8291-e85eabd88230.gif)

In the above GIF you can see that target="_blank" is configured on the link, and when I click on it it opens the second page in the same window. Here is another example where I use a dialog which shows it even better:

![show-target-prob2](https://user-images.githubusercontent.com/2900833/38376052-036753ea-38f8-11e8-9694-5e1ed20bec94.gif)

You see that the page gets loaded in the background, but the dialog stays in the front.

**Comment by wobba** [comment] 2018-06-26 14:33
This only occurs on hosts equal to the tenant. If you put www.foo.org it opens in a new window. Seems it's the modern smart loading hooking into links with the same tenant.

**Comment by lworkman** [comment] 2018-07-04 16:02
I'm also running into this issue. If I have two sites that are both children to the same hub site, the `target` property on the anchor tag is ignored when I click on it to navigate from one to another. However, if I'm navigating to another site that is unrelated, it respects the `target` property.

**Comment by Zhephyr54** [comment] 2018-10-03 14:51
@VesaJuvonen 
It seems to be an issue directly related with SharePoint because it's not only happening with SPFX web parts but also with native web parts such as the "Quick Links" one.

You can also reproduce this behavior by editing directly the DOM of a SharePoint page in your browser and adding a link (e.g. on a SharePoint Online modern page https://XXX.sharepoint.com/sites/XXX/SitePages/page.aspx add a link to another page : `<a href="https://XXX.sharepoint.com/sites/XXX/SitePages/page2.aspx" target="_blank">test</a>`) and if you follow it, it will open the new page in the same tab.

**Comment by joelfmrodrigues** [comment] 2018-11-02 16:50
I'm experiencing the same issue. Adding a anchor tag to a custom web part with target="_blank" seems to always open on the same tab when pointing to an internal url.

**Comment by wobba** [comment] 2018-11-02 18:17
See
https://julieturner.net/2018/08/spfx-anchor-tags-hitting-the-target/ for a
solution.

-mikael

fre. 2. nov. 2018 kl. 19:07 skrev Joel Rodrigues <notifications@github.com>:

**Comment by wobba** [comment] 2018-11-03 07:47
We use the workaround and you only need it on target=_blank, so no impact on load times.

**Comment by joelfmrodrigues** [comment] 2018-11-03 09:59
I mean when navigating to the target page. But feels like you are not experiencing any slowdown, so may give it a try. Thanks a lot for that Mikael

**Comment by wobba** [comment] 2018-11-03 10:07
When opening a new page in a tab it will load all elements always - no smart loading in a new tab. You can only smartload in the existing tab.

**Comment by JonasBjerke89** [comment] 2019-04-12 08:06
You can just add the following attribute to the anchor tag: data-interception='off'
This is ignore the smart loading done by modern SharePoint.

This is the same way the text webpart works with anchor tags:
![image](https://user-images.githubusercontent.com/21952399/56021804-a624da80-5d0a-11e9-8b8d-75019480aa68.png)

**Comment by wobba** [comment] 2019-04-12 08:11
@VesaJuvonen @estruyf maybe we can close this as "by design" as adding the `data-interception` attribute is the way to solve this one?

**Comment by KEMiCZA** [comment] 2019-06-17 08:28
Thanks for the workaround/fix all!
We just implemented this for one of our clients. 
@VesaJuvonen Can we rely on the data-interception fix?

Kind regards

**Comment by lworkman** [comment] 2019-11-19 17:32
Any updates on this? Still hesitant to add `data-interception` unless it's been officially documented at this point.

**Closed** 2019-11-26 17:22 UTC
Labels: area:framework-general, status:tracked, type:bug-confirmed
