### ISSUE TITLE
Old version(s) of SpFx Extension Code Displays Intermittently 

### ISSUE THREAD

**Issue by pdemro** [SharePoint/sp-dev-docs#864] opened 2017-09-19 15:09 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Sites will display the latest version of a SpFx extension after the latest version is deployed and the app is updated on the site.

#### Observed Behavior
Functionality intermittently changes between the latest versions and prior versions of the SpFx extension.  Clearing local browser cache does not seem to have an effect.  Clearing the session may fix the issue temporarily.  Navigating through contents of the modern site almost always causes the extension to regress to a previous version

I figured this was a CDN caching issue at first.  After several days with no changes to the SpFx extension we are still seeing an old version intermittently 

#### Steps to Reproduce
1. Start with a Modern site collection which has multiple pages/libraries
2. Deploy a SpFx Application extension to SharePoint using the CDN instructions at https://dev.office.com/sharepoint/docs/spfx/extensions/get-started/hosting-extension-from-office365-cdn.  In this case my application displays some content in the "Top" placeholder
3. Make updates to the code base and deploy a new version of the SpFx app.  Update the version of the app on the site
4. Click through the site and watch the extension change functionality between different versions of the SpFx app.  Clear browser cache and experience the same
5. Wait several days (or a weekend) for the CDN to presumably flush the cache.  Experience the same issue.

**Comment by mcmynn83** [comment] 2017-09-20 17:22
Can you include a fiddler trace of a working and non working request (ie 1 where you get an old version and one where you get a new version)?  If you would like to email it to grahamc at Microsoft we'll be able to take a look at this.

**Comment by pdemro** [comment] 2017-09-20 22:19
@mcmynn83 I sent the traces your way.  Thanks for your response.

**Comment by tavikukko** [comment] 2017-09-25 07:38
This might be related [876](https://github.com/SharePoint/sp-dev-docs/issues/876). In this case, office CDN is not even used, SP is serving randomly old published versions of the JS file stored in Style Library. Also recorded video about it.

**Comment by pdemro** [comment] 2017-09-26 13:41
This week we are getting intermittent 406 errors on SpFx Extension loading (below). 

{"HttpStatus":"NotAcceptable","ErrorMessage":"Requested asset is not found or is not located in the Public CDN enabled location","ErrorCode":406012}

**Comment by dsteinweg** [comment] 2017-09-26 18:55
@mcmynn83 Any status update?  In the meantime, do you have any suggestions for workarounds?

**Comment by eschrader** [comment] 2018-01-29 22:44
Strange, I think @tavikukko is onto something about local browser caching. 
I updated a new web part I created last week with some pretty big TS code changes deleted my /sharepoint/ and /temp/ folders and repackaged it (gulp bundle --ship and gulp package-solution --ship), uploaded it to my CDN and app catalog. I tried adding the web part to the page and had to delete the zone and re-add it since its a full width web part to get it to appear.

When I add the web part I get "we're sorry.... blah" and the F12 trace shows a 406 not found. But my other SPFX extension on the page loads from the same CDN so I knew my paths were right.

**Solution/workaround:** I cleared my cache, opened private browsing and was able to add my web part to the page without an error.

**Comment by tavikukko** [comment] 2018-01-30 08:12
@eschrader this is still occurring in some of my tenants. For some reason, not all frontend servers of the o365 tenant node update/sync the cache information correctly, or it can take several minutes/hours. I think it is something to do with the O365 CDN settings (a wild quess). In some tenant where I have enabled and disabled the O365 CDN, the caching problem has disappeared.

**Comment by o-utofbounds** [comment] 2018-03-09 10:41
had a similar error message "No 'Access-Control-Allow-Origin' header is present" a full browser cache reset fixed the issue in my case

**Comment by dgaeta** [comment] 2018-08-13 21:41
@pdemro Are you still experiencing this issue?

**Comment by SharePickle** [comment] 2018-09-14 14:07
Recently experienced the same issue.
Hitting F5 sometimes loads old scripts from CDN and sometimes from app catalog (we changed CDN base url to app catalog client assets library). Sometimes it's not loading at all - error 406.
We've discovered it was caused by "*" in webpart manifest version.

```
{
    "$schema": "https://developer.microsoft.com/json-schemas/spfx/client-side-web-part-manifest.schema.json",
    "id": "<Your_Id>",
    "alias": "<Your_Alias>",
    "componentType": "WebPart",
    "version": "1.0.1", // used to be * (star)
    "manifestVersion": 2,
    "requiresCustomScript": false,
    ...
}
```

Can anybody confirm this actually causes it? Thanks.

**Comment by nikskhubani** [comment] 2019-01-16 10:56
Hi There,

We faced exactly same issue and this is not related to cache. Here is the detailed information

https://github.com/SharePoint/sp-dev-docs/issues/3079

**How it was fixed**

I had multiple features in my solution and each feature was referencing the element file of the Extension. I had merged all feature in package-solution to single feature and it stopped creating issues.

**What to do with existing deployed apps where multiple component manifests deployed**

Steps are:

1. Delete the existing app from app catalog (This is the key, this will clear junk entries from component manifest)
2. Add it or the new version again (Doesn't matter).

**Closed** 2019-01-30 12:00 UTC
Labels: Needs: Author Feedback, area:cdn, area:framework, no-recent-activity, status:duplicate
