### ISSUE TITLE
Setting an webpart icon to an image instead of a fabric UI icon with supportsFullBleed being true results in image not showing

### ISSUE THREAD

**Issue by TheInvoker** [SharePoint/sp-dev-docs#6303] opened 2020-09-22 03:33 UTC
## Category

- [x] Bug

## Describe the bug

When you create a webpart with supportsFullBleed : true and set the iconImageUrl to an image path (not a fabric icon name), and then edit a page with a empty full width zone and see the options to add a webpart. Typically its Hero Widget, Image, Countdown Timer, then the custom webpart. I find that the icon image doesn't show and it looks buggy, like the square div wrapper is causing it to appear higher than the other 3. If I instead choose a fabric icon, it looks perfect. See attached image.

![Capture](https://user-images.githubusercontent.com/5560751/93841733-86fddc80-fc62-11ea-84c4-b35bbd9eff63.PNG)

## Steps to reproduce

1. create web part and set supportsFullBleed : true and set the iconImageUrl to an image path
2. on a blank full width zone you will see the bug

## Expected behavior

Custom icon image should show.

## Environment details (*development & target environment*)

Windows 10 
SharePoint Online
Node 10
Chrome v79 
VS Code | SPFx v1.10.0

**Comment by kongmengfei** [comment] 2020-09-29 02:36
Hi TheInvoker,

I am able to reproduce this error with below demo:

- https://github.com/kongmengfei/SharedSPFx/blob/master/myimagegallery/README.md

![image](https://user-images.githubusercontent.com/57654821/94505362-7e4a6f00-023d-11eb-88c0-71095ab21b4b.png)

In fact i found that the image has already loaded but wraped with incorrect CSS/Html elements, which makes it invisiable. I changed something using F12 then it could display well.

![image](https://user-images.githubusercontent.com/57654821/94505843-8f47b000-023e-11eb-91a9-02b08cbc9c04.png)

So this should be a tiny bug, it won't affect the functionality. So i suggest you continue using font icon before it gets fixed. 

Baker Kong
Microsoft SharePoint Community Support

**Comment by quantrpeter** [comment] 2021-03-05 03:05
this issue still exist

**Comment by AJIXuMuK** [comment] 2021-12-01 22:41
Dupe of #6102

**Closed** 2021-12-01 22:41 UTC
Labels: status:duplicate, type:question, area:spfx
