### ISSUE TITLE
Application Customizer extension not loading for External Users

### ISSUE THREAD

**Issue by tchagan** [SharePoint/sp-dev-docs#3868] opened 2019-05-01 10:18 UTC
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Application Customizer extension is loaded for all users including External users.

#### Observed Behavior
Application Customizer extension is not loaded for External users.

#### Steps to Reproduce
Create and deploy a simple Application Customizer extension to the tenant app catalog and then install on site.
Go to site as a normal (member) user, note that the extension is loaded.
Go to the site as an external user, note that the extension is not loaded and there is an error in the browser console.

Error:
Uncaught (in promise) Error: Failed to create application customizer 'ClientSideExtension.ApplicationCustomizer.2ec4f56a-0f76-4720-b529-250c622291f3'. Error information is '***Extension failed to load for componentId "2ec4f56a-0f76-4720-b529-250c622291f3".'.
    at sp-pages-assembly_en-us_98e223b7476f1d73674342a0397c79e7.js:2354

#### Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by patmill** [comment] 2019-05-01 22:44
If you wouldn't mind looking into a few more places.

If you look at the network tab, are you getting any 403's when making requests (possibly for the js files)?  If you are, what are the URLs - are they for the app catalog site, or are they for the public CDN?

**Comment by mcmynn83** [comment] 2019-05-16 18:03
This is a dupe of #2099.  You can follow the workaround given there until we fix the problem.

**Closed by mcmynn83** 2019-05-16 18:03 UTC
Labels: area:framework, status:working-on-it
