### ISSUE TITLE
Gulp webpack slow build

### ISSUE THREAD

**Issue by ssvinciak** [SharePoint/sp-dev-docs#3540] opened 2019-03-04 13:15 UTC
#### Category
- [X] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Whenever I save source code(small change in one webpart), the build should be fast or at the most several seconds. 

#### Observed Behavior

Each build on save(ctrl+s) takes more than minute. Webpack is especially slow. Below is ouput from `gulp serve --no-browser`. Performance without no browser option is the same. 
![gulp-build](https://user-images.githubusercontent.com/18068307/53734868-88e82b00-3e85-11e9-8971-4a58351a4b0f.png)

Waiting for each build is unbearable. 

#### Steps to Reproduce

I have a simple webpart that displays form with several fields and table. Below is screen with used packages. I have not added any custom tasks in gulpfile.js. 

![packages](https://user-images.githubusercontent.com/18068307/53735120-43782d80-3e86-11e9-83df-e848f3721cdb.png)

1. `npm install`
2. `gulp serve --no-broswer`
3. After minute everything is ready
4. Save small changes 
5. Another minute on build

I have also seen other slow build issues, but with no success (https://github.com/SharePoint/sp-dev-docs/issues/3355). I don't why gulp rebuilds whole project after small change as it would be fresh start.

Thanks in advance

**Comment by andrewconnell** [comment] 2019-03-12 14:24
There's not much that can be done here... that's how the build system works. The gulp task `serve` reruns the entire build process that includes linting, transpiling, bundling & regenerating the manifest files. It's not a bug, it's just how they've decided to do it.

As you referenced another issue posting about the same topic, I'm going to close this one as a dupe issue. MSFT has tagged that issue as a bug & tracked which implies could be looking into it... better to keep things consolidated to one issue if there's no new info...

**Closed by andrewconnell** 2019-03-12 14:24 UTC
Labels: area:framework, area:tooling, status:duplicate
