### ISSUE TITLE
Detect navigation change in SPFX Application customizer

### ISSUE THREAD

**Issue by pmatthews05** [SharePoint/sp-dev-docs#1254] opened 2018-01-19 09:13 UTC
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
I have a SPFX customizer that displays a banner in the topPlaceholder. When the page loads, if it's a list, then it performs a calculation and then displays the banner.

When I move from one library to another, because the page isn't performing a full load, I found out I need use the navigatedEvent. This fires when the navigation changes.

However, I need to display the banner differently depending on what folder I'm in within a single document library. When navigating from one folder to another in a document library the navigatedEvent doesn't seem to fire, even though I am navigating to a different location.

Is this a bug with the navigatedEvent, or should I be using a different event?

#### Observed Behavior
When navigating from one folder to another, the navigatedEvent doesn't fire.

#### Steps to Reproduce
Have the following code running on a document libraries. Have a document library with folders. View the debug console of the browser. If you navigate between the folders, you will discover that the renderControl doesn't fire again. It only fires on changes between libraries (if deployed to app catalog, not running through debug localhost session)

` public onInit(): Promise<void> {
      this.context.application.navigatedEvent.add(this,  this.renderControl);  
      return Promise.resolve<void>();
  }

    private renderControl(){
   console.log("Rendering control');
    Log.info(LOG_SOURCE, `Available placeholders: ${this.context.placeholderProvider.placeholderNames.map(name => PlaceholderName[name]).join(', ')}`);

    //handling the top placeholder
    if(!this._topPlaceholder){
      this._topPlaceholder = this.context.placeholderProvider.tryCreateContent(
          PlaceholderName.Top, 
          {onDispose: this._onDispose});

      if(!this._topPlaceholder){
        console.error(`The expected placholder (Top) was not found.`);
        return;
      }  
    }

    if(this._topPlaceholder.domElement){
        const element : React.ReactElement<IInfoBarMainProps> = React.createElement(
          MainBar,{
                context: this.context
          }
        );
        ReactDom.render(element, this._topPlaceholder.domElement);
    }
  }

  private _onDispose(){
    Log.info(LOG_SOURCE, `[IInfoBarApplicationCustomizer._onDispose] Disposed custom top placeholders`);
  }`

Is there a different event I should be using? Also, if I navigated inside a folder, is there a way to work out which folder with a URL?

**Comment by VesaJuvonen** [comment] 2018-01-25 17:43
Potential duplicate as #1265.

**Comment by pmatthews05** [comment] 2018-01-25 20:31
@VesaJuvonen although my issue similar to #1265, it not quite the same. My issue is that navigatedevent doesn't fire when you navigate inside folders that are in the document library. The other issue seems to be about the placeholders not available when switching pages.

**Comment by VesaJuvonen** [comment] 2018-01-26 13:49
yes - we do get that, but root cause or the issue is similar to the internal event handling in the Framework, which is why we cross-linked this in GitHub and in VSO. Obviously, we'll need to ensure that we have all of these fixed properly asap and the issue is being looked at by our engineering.

**Comment by ahackettms** [comment] 2018-03-20 17:14
@pmatthews05 we are working on providing a solution to provide folder information in page context when navigate into a folder, and fire the navigation event.

**Comment by OmniFace** [comment] 2018-04-04 16:46
The navigatedEvent also do not fire if performing a search or returning to the home page, unless you started on the search page (refresh or bookmark) and then move to the home page.

Is this a bug as well?  Is navigatedEvent supposed to fire with all page transitions that don't reload the DOM?

**Comment by VesaJuvonen** [comment] 2018-04-23 06:31
We have now changed our eventing model related on fix with #1042. This should be solving this issue as well, so closing this. If you still have issues around this, please do let us know. Thx.

**Closed by VesaJuvonen** 2018-04-23 06:31 UTC
Labels: area:framework, status:tracked, type:bug

**Comment by dhruvp29** [comment] 2019-08-29 05:53
I am still facing this issue.  When navigating from one folder to another, the navigatedEvent doesn't fire.

**Comment by dhruvp29** [comment] 2019-08-29 06:03
I am still facing this issue, Kindly check #4557
