### ISSUE TITLE
SPComponentLoader.loadComponentById only works on hard reload

### ISSUE THREAD

**Issue by ajoosten** [SharePoint/sp-dev-docs#7685] opened 2022-01-31 12:10 UTC
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx version: 1.10
- Node.js version: 10.24.1
- Edge version: 97.0.1072.76 
- Chrome version:  97.0.4692.99

### Describe the bug / error

We created a search solution based on the PnP Search V3 solution. In this solution we load a seperate SPFx library with web components that can then be used in the template section of the Search Results webpart. We load this library with the following code: 
const extensibilityLibraryComponent: any = await SPComponentLoader.loadComponentById(ExtensibilityService_LibraryComponentId);

Till last Friday (Jan, 27th) this was working smoothly. But since last Friday this stopped working. The only remedy is loading the hosting page with a hard reload <ctrl>-<F5>. 

The error shown when we browse to the page without hard reload is: TypeError: Cannot read properties of undefined (reading 'isInternal') at e.loadComponent (https://modernb.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_aa02684fe246dc3a8d293413f9c42cd7.js:71:57126)

When the error is shown we can see our custom web component in the source of the page. It is not rendered as the browser has no idea how to render this custom element. After the hard reload the correct rendering is applied and the page looks as expected. But even when we then just press enter in the url section of the browser, the error occurs again and the data isn't shown.

### Steps to reproduce

1. Enter the url of the page where our search result webpart is hosted
2. The data isn't shown,
3. Press Ctrl-F5 in the current window
4. The data is shown

### Expected behavior

We except that there is no difference in the component loading mechanism if we refresh the cache or not.

**Comment by AJIXuMuK** [comment] 2022-01-31 14:17
Dupe of #7664

**Closed** 2022-01-31 14:17 UTC
Labels: type:bug-suspected, status:duplicate, Needs: Triage :mag:
