### ISSUE TITLE
@microsoft/generator-sharepoint v1.7.1 React version not supported using React template and targeting Sharepoint 2019 onwards

### ISSUE THREAD

**Issue by niceberg** [SharePoint/sp-dev-docs#3422] opened 2019-02-08 13:24 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Web part generated with React template targeting 'SharePoint 2019 onwards, including SharePoint Online' successfully runs in SharePoint 2019 without changing the generated code.

#### Observed Behavior

After generating a web part using React template targeting 'SharePoint 2019 onwards, including SharePoint Online', adding it to a page in local workbench everything works, but when adding it to a page in SharePoint context the following error occours inside the web part :
[SPLoaderError.loadComponentError]
...
Original error: ***Failed to load URL 'https://localhost:4321/node_modules/react/dist/react.js' for resource 'react' in component '0b4a6ef4-c538-4c41-96e3-17a31ad253d8' (HelloWorldWebPart). The file was not found in the server.
Make sure that you are running 'gulp serve'.

![sploaderror loadcomponenterror](https://user-images.githubusercontent.com/11358133/52479619-873e8680-2ba9-11e9-9c7e-de8ff2ab364e.png)

My observation is that the installed SharePoint Framework version is 1.4.1 and React version is 16.x. The problem could be that React 16 support came with SharePoint Framework version 1.7.1 and SharePoint 2019 is shipped with SharePoint Framework version 1.4.1.

#### Steps to Reproduce

Setup:
- Install Node at v8
- `npm install -g gulp` - at the time of writing this issue, the latest version is 4.0.0
- `npm install -g yo` - at the time of writint this issue, tha latest version is v2.0.5
- `npm install -g @microsoft/generator-sharepoint` - at the time of writing this issue, the latest version is 1.7.1

- Start generating template using `yo @microsoft/sharepoint`
  - Accept the default solution name
  - Select SharePoint 2019 onwards, including SharePoint Online as target
  - Select Use the current folder for where to place the files
  - Select 'N' for 'Do you want to allow the tenant admin the choice...'
  - Select WebPart to create
  - Select default name for the Web part
  - Select default description for the Web part
  - Select React as the framework to be used

- After generating the template run `gulp serve`
- Open the workbench in a SharePoint context and add this web part to a page

>Note: SharePoint 2019 (on-prem) is needed to reproduce the issue

**Comment by andrewconnell** [comment] 2019-02-10 12:21
Pretty sure this is a dupe of #3145 which is being tracked do closing this as a dupe.

**Closed by andrewconnell** 2019-02-10 12:21 UTC
Labels: area:framework, area:on-prem, status:duplicate
