### ISSUE TITLE
SPFX Client WebPart with Angularjs and OfficeUiFabric

### ISSUE THREAD

**Issue by gonadn** [SharePoint/sp-dev-docs#578] opened 2017-05-07 13:17 UTC
Iam strugling to use OfficeUIFbric in my Client WebPart with AngularJS. I first created the webpart as "No javaScript web framework", and then i added angularJS as described in this article , webpart is working fine but without any OfficeUIFaberic design on the button. 

![skjermbilde](https://cloud.githubusercontent.com/assets/3224441/25781277/fe38c352-3337-11e7-967f-bbb9df4c2e1c.PNG)

these two ways shown in articles is not working: import 'ng-office-ui-fabric' OR require('ng-office-ui-fabric')

iam adding these lines in my webpart.ts file....

and my config.js i have added angularjs and officeuifabric:
`"externals": {
"angular": {
  "path": "https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular.min.js",
  "globalName": "angular"
},
"ng-office-ui-fabric": "https://cdnjs.cloudflare.com/ajax/libs/ngOfficeUiFabric/0.12.3/ngOfficeUiFabric.js"`

Problom is when iam adding this line of code in my webpart.ts file:

import 'ng-office-ui-fabric';

When i remove the line above, webpart works fine....

I get this error in WorkBench: 
![workbench](https://cloud.githubusercontent.com/assets/3224441/25781291/4d11f53e-3338-11e7-8746-4c408af0ed12.PNG)

**Comment by waldekmastykarz** [comment] 2017-05-09 05:43
Could it be that you're not using angular anywhere in your web part and it's being removed from the generated bundle? I could reproduce your issue when not using angular, but once I added `angular.module('helloWorld', [])` in the web part, the error disappeared.

**Comment by rahulrai1980** [comment] 2018-03-29 17:55
Hey for me, icons are not appearing for
Any control .. uif icon not displaying anything .. can you give me some hint what could be wrong?? Using ng office
Fabric 0.16.0 nd fabric css 2.6.3 thanks in advance

**Comment by gonadn** [comment] 2018-05-31 14:48
To be honest #rahulrai1980, iam so SICK of googling for SPFX solution that works with AngularJS and OfficeUIFabric. And there are alot of solutions refering to how to use OfficeUIFabric with AngularJS f.eks ToDo app, and FileUpload webpart in examples of SPFX on GitHub.
When you download the solution and run it works fine. 
But when you try to set up custom SPFX solution, its literally FUCKED UP SHITT. 
There are no straight forward tutorials or description how to do it....you get one after another issue/challange with components that are not working, missing icons and so on. 

And if you think you can get an answer witch helps you, forget it...

its like finding needle in the sea....

Some of the components have there icons and some of them not. And its so confusing to google for a solution, and there NO description on HowToDo.

**Comment by gonadn** [comment] 2018-05-31 15:50
My experience with SPFX solution so far have been really messed up, even using Angular Material, Bootstrap , or OfficeUIFabric, there an no way to find any good solution. So iam still developing SP Add-In provider hoster or SP hosted, Because i dont want to use 3 weeks on just finding out how SPFX with OfficeUIFabric works, or Angular Material. 

But using OfficeUIFabric in SP Add-In have been working fine, and as expected....

I just cant figure out why they put up so many different solutions ToDo examples, when this shitt is not working when u setup the solution.....

**Comment by andrewconnell** [comment] 2018-12-14 18:07
As the original maintainer of the **ngOfficeUIFabric** project (which is now archived as it's outdated for various dependencies), I think a reason you're having these rendering issues is because ngOfficeUIFabric uses a very old version of Office UI Fabric's CSS which now conflicts with what is used in SharePoint Online.

Since it was in active dev years ago, the Office UI Fabric team has made many refactorings & class name changes and their current versions are not intended to work well when on the same page with . newer classes. 

I'm going to close this issue as there's no action that can really be taken due... please feel free to open with more detail about the problem.

**Closed by andrewconnell** 2018-12-14 18:07 UTC
Labels: type:question
