### ISSUE TITLE
Unable to approve API permissions for SPFx solutions

### ISSUE THREAD

**Issue by Tanddant** [SharePoint/sp-dev-docs#8738] opened 2023-01-31 08:47 UTC
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

other (enter in the "Additional environment details" area below)

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- Chrome: Version 109.0.5414.120 (Official Build) (64-bit)
- SPFx version: 1.15.2
- Node.js version: v12.22.1
- Both Targeted and non targeted release tenants
- For instance on tenant https://2v8lc2.sharepoint.com/

### Describe the bug / error

When attempting to approve API permissions in the admin center I'm meet with a error:

    We can't display pending and approved requests right now. Try refreshing the page.

No amount of refreshing the page does anything, I've seen this across several tenants - and selecting a request and approving it seemingly does nothing, also no errors in the console or network inspector.

So currently there is no way to approve permissions (other than going through the AAD and granting it to the *SharePoint Online Client Extensibility Web Application Principal* directly - but this obfuscates the granted permissions from SharePoint admins.

![image](https://user-images.githubusercontent.com/6947024/215711517-4093850f-dc8a-4973-a554-2550c61a66fa.png)

### Steps to reproduce

1. Create a new SPFx project - version seems to be unrelated.
2. Add a API Permission request, this can be to Graph or anywhere else, for instance:

``` JSON    
"webApiPermissionRequests": [
      {
        "resource": "Microsoft Graph",
        "scope": "Calendars.Read"
      }
    ]
```

3. Package and deploy your SPFx solution
4. Go to the webApiPermissionManagement page (/_layouts/15/online/AdminHome.aspx#/webApiPermissionManagement)
5. Attempt to approve the request permission.

### Expected behavior

Normally there isn't a big red banner on the page, and approving permissions work.

**Comment by fredupstair** [comment] 2023-01-31 09:50
cdx tenants don't seem affected, but I can see it on more than 20 tenants (production and development).
Let me know if you need more details, just let me know if you need more details and which ones.

**Comment by VesaJuvonen** [comment] 2023-01-31 09:52
thx @fredupstair for the updated scale on this and great insights on the CDX status vs normal production tenants. This is EXACTLY the information which will help engineering to triage the root cause as the CDX tenants have different rings for the new features 👍

**Comment by funzel1** [comment] 2023-01-31 15:02
same issue
We can't display pending and approved requests right now. Try refreshing the page.

**Comment by giorgioprof** [comment] 2023-01-31 15:47
This issue affects all our tenants, ad we can no longer approve permissions from Api Access page. We even got our app rejected from SP Store publishing due to this issue.

**Comment by rmunasinghe** [comment] 2023-01-31 16:57
I'm having this issue on a few of our tenants as well. I cannot approve the permission via the SharePoint Admin UI. PowerShell doesn't work either. I also tried to use the "Approve-SPOTenantServicePrincipalPermissionRequest" PowerShell command, and I get back the following error:

```
Approve-SPOTenantServicePrincipalPermissionRequest : An OAuth permission with the scope
api://<CLIENT ID>/EUM_API could not be found.
Parameter name: scope
```

I have validated that the scope I'm requesting exists in the same Azure AD as my SharePoint Online.

**Comment by AJIXuMuK** [comment] 2023-01-31 22:39
We have identified the cause of the issue and working on the plan of the fix.
Thank you all for the information.

Will update the thread once we have better ETA.

**Comment by AJIXuMuK** [comment] 2023-02-01 02:18
@Tanddant - the page should be fixed.
Could you please confirm?

**Comment by Tanddant** [comment] 2023-02-01 04:42
The request now appears as approved - but I had manually added it through the Azure AD, will confirm approving actually works once I get to the office

**Comment by Tanddant** [comment] 2023-02-01 06:35
Confirmed resolved on several tenants - thanks for the quick resolution 👍

**Closed** 2023-02-01 06:37 UTC
Labels: type:bug-suspected, area:spfx, Needs: Attention :wave:, status:working-on-it

**Comment by funzel1** [comment] 2023-02-01 07:59
I also can confirm it is solved,
we have raised last evening parallel Premier support case for it.
Thanks

**Comment by VesaJuvonen** [comment] 2023-02-01 13:33
Huge thanks for everyone for your engagement here. Input and reports provided through this issue helped to solve the unexpected situation as fast as possible. Thank you and sorry for the inconvenience and challenges this issue might have caused for you 👏👍🧡
