### ISSUE TITLE
yeoman creates .yo-rc.json at current location which leads to unwished behaviour

### ISSUE THREAD

**Issue by EA12** [SharePoint/sp-dev-docs#4194] opened 2019-06-24 18:51 UTC
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

The yeomen generator should not add a .yo-rc.json file to current Location when creating a new SPFx-WebPart to a sub-folder.

#### Observed Behavior

The yeomen generator (version 1.8.2) adds a .yo-rc.json file to current location when creating a new SPFx-WebPart to a sub-folder.

#### Steps to Reproduce

Create a new SPFx-WebPart by
`yo @microsoft/sharepoint`

If you choose the framework and hit return, the file gets created at the current location even if you choosed "Create a subfolder with solution Name"

#### Consider
If you then want to create a new SPFx-WebPart you must delete this file otherwise the scaffolding will take the Settings from this file and you will not be able to choose a different baseline package.

See following issue-comment from @andrewconnell why this behaviour was established.

The yeomen generator should also take the scenario into account which I described under "Consider"

Would that be possible for a future release of yeomen?

**Comment by andrewconnell** [comment] 2019-06-24 19:29
Disagree... the way it works now is ideal. But this behavior is "by design" so we'll close this issue as it falls in the category of a feature request / change. If you want to change how things work, those would go as a user voice request to http://aka.ms/sp-dev-uservoice

My thoughts...

There are two things:
- project (aka: solution)
- component (web parts / extensions)

A project can contain multiple components.

When you run the generator on a brand new folder, it creates the project & the component. If you run it again, it detects (by the presence of the **.yo-rc**) file & skips all the questions global to the project & goes straight to the questions for creating a component.

If you want to create a component with different project settings (different SP environment, tenant scoped deployment options, etc), you create a new project & put the components in there.

And projects are created at the same level on your machine, parallel to each other.

**Closed by andrewconnell** 2019-06-24 19:29 UTC
Labels: area:generator, status:by-design, type:uservoice-request
