### ISSUE TITLE
SPFx v1.5, not able to create Extensions and WebParts as a single solution 

### ISSUE THREAD

**Issue by anupJag** [SharePoint/sp-dev-docs#2054] opened 2018-06-16 18:36 UTC
After recently updated my SPFx framework to v1.5.0 and I wanted to create a solution that has both Extensions (Application Customizer) and Client Side Webparts. Now if I try creating a WebPart first and then try adding an Extension with
(yo @ microsoft/sharepoint), I get prompted asking : 
Add a new Web Part to solution ###### 
?What is your Web part name ? 
The same thing applies for Extensions as well.
Could you please suggest how to proceed.

#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

**Comment by VesaJuvonen** [comment] 2018-06-18 06:58
Duplicate of #1991, so closing this one. We will have a 1.5.1 release in a matter of days to address known issues.

**Closed by VesaJuvonen** 2018-06-18 06:58 UTC

**Comment by anupJag** [comment] 2018-06-18 07:39
Thanks @VesaJuvonen
