### ISSUE TITLE
SPFx Property pane not opening on classic pages

### ISSUE THREAD

**Issue by tocnr** [SharePoint/sp-dev-docs#3345] opened 2019-01-29 11:58 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

SPFx property pane loads as normal

#### Observed Behavior

Just experiencing a pretty strange issue that we first noticed today. On our production SharePoint Online tenancy the SPFx property pane does not always load on classic pages. This has worked previously up until today.

After adding the web part to the page and clicking through to edit the web part you get the usual classic web part settings dialog. At the top you can see the 'Configure' button to open the modern property pane. Clicking this button has no result and the usual dialog does not appear.

It seems that if you move the web part to be the last web part in the zone the property pane then functions as expected. If the web part is the only web part in the zone then it also works correctly.

I have tried this on a blank newly created publishing site with the OOB master page and it still has the same issue. I upgraded my solutions to SPFx 1.7.1 thinking that perhaps it might be an issue with older version of the framework to no avail. This also occurs with another third party SPFx solution. Checking the browser console shows no obvious errors and it also appears to occur in both Chrome and Edge.

Tested on my development tenancy with the same code but could not reproduce the issue.

#### Steps to Reproduce

1. Create a new publishing page using a standard page layout
2. Add a couple of SPFx based web parts to the publishing page into the same web part zone
3. Try to edit the first web part in the zone and notice that the classic web part pane loads
4. Click the SPFx 'Configure' button and the modern property pane does not load
5. Move the same web part to be the last web part in the zone and the SPFx property pane will now open

**Comment by jonathanhotono** [comment] 2019-01-30 04:05
This also happens across all of my tenants on spfx 1.7.1. 
Simply can't click the configure button to open the property pane.

**Comment by atjohns2** [comment] 2019-01-30 14:02
Also happening on all of our classic site pages.

**Comment by SanjivKrSharma1** [comment] 2019-01-31 16:51
We are also facing same issue, none of SPFx WPs Property. Its across my all tennat to.
Can't click the configure button to open the property pane on classic site pages. 

Any update... its urgent.....

**Comment by SanjivKrSharma1** [comment] 2019-01-31 17:21
Experiencing Same issue since yesterday evening. We have custom built SP Online at my tenant with lot of SPfx Webparts.

Clicking through to edit the web part you get the usual classic web part settings dialog. At the top you can see the '**Configure**' button to open the modern property pane. Clicking this button has no result and the usual dialog does not appear.

Also It same behavior that if you move the web part to be the last web part in the zone the property pane then functions as expected. If the web part is the only web part in the zone then it also works correctly.

Using SPFx Version: 1.5.1

Checked the browser console shows no obvious errors and it also appears to occur in both Chrome and Edge.

Any Update

**Comment by paddymccallan** [comment] 2019-02-01 14:58
Also happening in team-tabs Sharepoint apps.

**Comment by shaky0980** [comment] 2019-02-02 12:46
Same issue here.
It works, if there is only one WebPart on the site, but if there is a second, its not.
tested with 1.5.x 1.4.1, also with onPrem solutions

**Comment by jonathanhotono** [comment] 2019-02-04 06:13
@VesaJuvonen is there any ETA on when this critical issue can be fixed? We have around 5 clients raising this issue at the moment. Many thanks!

**Comment by VesaJuvonen** [comment] 2019-02-05 07:02
Fix has been checked in and is currently being rolled out worldwide. Can't provide exact ETA, but the fix should be available soon. This is indeed a duplicate with the #3394, which was mentioned in Twitter, so noticed that from there.

**Comment by jonathanhotono** [comment] 2019-02-05 08:41
@VesaJuvonen great thanks so much!

**Comment by ruslan-s** [comment] 2019-02-06 08:33
> Can confirm that this has started working again for me.

Same on our test tenant

**Comment by SanjivKrSharma1** [comment] 2019-02-07 13:59
The issue is fixed...I have tested in tenant and now I can see the Property pane. Here is another thread on same issue:
https://github.com/SharePoint/sp-dev-docs/issues/3394

**Comment by VesaJuvonen** [comment] 2019-02-08 15:05
Closing this as the issue has been fixed and rolled out worldwide. Thanks, everyone for your input around this one.

**Closed by VesaJuvonen** 2019-02-08 15:05 UTC
Labels: area:framework, status:tracked, type:bug
