### ISSUE TITLE
ListViewCommandSet Extension not loading when navigating from Start page after clearing cache

### ISSUE THREAD

**Issue by HussainRuhullah** [SharePoint/sp-dev-docs#9180] opened 2023-09-05 14:45 UTC
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Linux

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [X] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Describe the bug / error

![caching problem in sp command set](https://github.com/SharePoint/sp-dev-docs/assets/144137924/c726d9b2-deb3-441a-9ff8-b42c7068372b)

The issue was previously reported and closed, but it has resurfaced again. I have included links to the previous issues for reference.

Some of our 365 tenants are experiencing an issue where the command buttons are not loading. 
This issue only occurs after clearing the cache, and only if a user doesn't directly navigate to the list where the button is.

As a result, ListViewCommandSet extensions are unusable and hamper the functionality of our product.

As mentioned by @andrewconnell it's a platform fix (ie: server-side).

Previous issues:
https://github.com/SharePoint/sp-dev-docs/issues/6611
https://github.com/SharePoint/sp-dev-docs/issues/6116
https://github.com/SharePoint/sp-dev-docs/issues/5704

### Steps to reproduce

1. Create a Command Set Extension project with Yeoman SharePoint Generator $yo @microsoft/sharepoint
2. Bundle and upload the button to app catalog
3. clear browser cache and login to your SharePoint Tenant
 example: https://yourTenant.sharepoint.com/sites/hruh-test
4. Navigate to List where the Extension is Installed using the navigation tree
 example: https://yourTenant.sharepoint.com/sites/hruh-test/myList/Forms/AllItems.aspx
 5. The extension does NOT load on first page load
 6. Refresh the page to see the Extension.
 

### Expected behavior

Command Button should be visible on document library without refresh.

**Comment by nick-pape** [comment] 2023-09-05 15:19
This appears to be a duplicate of: https://github.com/SharePoint/sp-dev-docs/issues/9180

Please follow this ticket. Thank you.

**Closed** 2023-09-05 15:19 UTC
Labels: type:bug-suspected, status:duplicate

**Comment by HussainRuhullah** [comment] 2023-09-06 07:09
@nick-pape Thank you for your fast response to my issue. 
However, the link provided is to the this issue. 

As mentioned in the description, this problem was solved by Microsoft in the past, but **it is occurring again now**. 
That is why I have opened this issue with exact steps to reproduce it, as the steps to produce the issue are not as clear in other tickets.

I appreciate your help and would be grateful if you could provide any guidance or suggestions on how to resolve this issue.

**Comment by AJIXuMuK** [comment] 2023-09-06 13:34
@HussainRuhullah  - correct dupe link is #9166
