### ISSUE TITLE
ACE samples seem to have a token issue in Teams mobile client

### ISSUE THREAD

**Issue by Laskewitz** [SharePoint/sp-dev-docs#7693] opened 2022-02-04 14:05 UTC
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [X] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Describe the bug / error

I deployed two of the ACE samples from the PnP sp-dev-fx-aces [repository ](https://github.com/pnp/sp-dev-fx-aces)called "PrimaryTextCard-Graph-UnreadEmails" & "BasicCard-Graph-UpcomingEvents".

In the mobile experience, we have dashboard, feed, and resources tabs. I would like to have the possibility to also show the web parts that we added on our homesite as well. To achieve this, I added a link in the Global Nav to link to the home site.

But then we hit an issue:

In the Viva Connections app, the sample cards work great. 

![MicrosoftTeams-image](https://user-images.githubusercontent.com/3766843/152541463-723b1092-e963-4b26-9f70-4bc96c2d5676.png)

When we move to the resources tab and select a link there to our Portal it doesn’t work well.

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/3766843/152541521-50768911-d7aa-4e62-b770-c17e33de659e.png)

The link that we use in global navigation is: 
https://{tenant}.sharepoint.com/sites/portal/_layouts/15/teamslogon.aspx?spfx=true&dest=/sites/portal 

We use that to make sure it opens correctly in the Teams client.

### Steps to reproduce

1. Deploy the samples from the PnP samples repo
2. Add the ACEs to your home site dashboard
3. Add the dashboard web part to your home site
4. Add a global nav link to your home site
5. Open the Teams mobile client
6. Go to the viva connections app in the Teams mobile client
7. Navigate to the home site via the link in the resources tab

### Expected behavior

I would expect the ACEs (both the out of the box - Shifts ACE doesn't work correctly as well - as the sample aces from the PnP samples) to work the same as in the dashboard tab and not show the error that is displayed above.

**Comment by AJIXuMuK** [comment] 2022-02-04 14:33
Hi @Laskewitz - thank you for reporting this issue. This is a duplicate of #7646. 
We're actively working on making auth work correctly on Teams mobile.
Please, follow the mentioned issue to get info on the progress.

**Closed** 2022-02-04 14:33 UTC
Labels: type:bug-suspected, status:duplicate, area:spfx, area:auth, area:ACE
