### ISSUE TITLE
Field Customizer stops receiving properties after refreshing page

### ISSUE THREAD

**Issue by JLRishe** [SharePoint/sp-dev-docs#7550] opened 2021-11-30 18:26 UTC
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
  - Chrome:  96.0.4664.45
  - Firefox: 94.0.2
  - Edge: 96.0.1054.34
- SPFx version
  - 1.13.1
- Node.js version
  - 14.18.1

### Describe the bug / error

I have developed a field customizer that I have been using for some time.

I apply this field customizer to the Title fields in ordinary lists by setting their `ClientSideComponentId` and `ClientSideComponentProperties` using the REST API.

Around last week, I learned of an issue where the field customizer loads properly on a freshly opened list page, but after refreshing the page a few times, an empty object is passed in as the customizer's properties instead of the values that are specified in `ClientSideComponentProperties`. This seems to continue no matter how many times I refresh the page, but if I open an Incognito window, the customizer yet again works initially, but receives empty properties after refreshing the page.

Some observations:
- This seems to happen in unison across all customizers on the page. Either they all receive their properties, or none do.
- I dug into the internal code a bit, and it looks like at some point a value of `""` (empty string) is being loaded as the `ClientSideComponentProperties` value instead of the actual value.
  - Also, if I inspect the field customizer's `this.context.field` value, it shows a `clientSideComponentProperties` value of `""` instead of the actual value:
![image](https://user-images.githubusercontent.com/6964029/144165232-b1eb6097-ae99-4641-ab1f-e9f2aad3bee3.png)
- I initially observed this on SPFx version 1.4.1, and thought that upgrading to the latest (1.13.1) might remedy the problem, but it doesn't seem to have made any difference.
- This issue does not occur when serving the customizer from a local Dev/Debug server. I can only observe this in published (`--ship`) packages.

Given the symptoms, where it initially works and then stops working, I have to wonder if this isn't happening on account of some race condition, e.g. where some internal code is requesting `ClientSideComponentProperties` before the value is available, and receiving an empty string instead.

### Steps to reproduce

1. Publish a field customizer that is designed to receive properties and use them in an observable way.
2. On an ordinary list, set the Title fields' `ClientSideComponentId` to the ID of the customizer, and their `ClientSideComponentProperties` to a value that the field customizer would recognize.
3. Load the list page, and refresh it a few times.

RESULT: The properties are used the first time the page is loaded, but after a few refreshes, they are not.

### Expected behavior

EXPECTED: The properties are correctly passed into the customizer every time the page is loaded.

**Comment by AJIXuMuK** [comment] 2021-12-07 13:47
Hello @JLRishe - thank you for reporting the issue.

Could you please check one thing - when the properties are missing open the source code of the page and search for `ClientSideComponentProperties`. Does it have the correct value?

**Comment by JLRishe** [comment] 2021-12-13 11:02
@AJIXuMuK thank you for your response.

In the source code of the page, I see one occurrence of `ClientSideComponentProperties` in a variable called `g_clientComponents`. 

That variable contains information for a command bar custom action (which comes from the same .sppkg as the field customizer and that command bar custom action does not have the issue described above - its properties are passed in correctly).

The page source does not seem to contain data for the field customizer, to the answer to your question is that no, `ClientSideComponentProperties` does not have the correct value because the one in question is not there at all.

**Comment by AJIXuMuK** [comment] 2021-12-13 14:44
Thank you @JLRishe for looking at it.
Could you please do one more thing?
Could you check the Network tab when you experiencing the issue? There are should be multiple `RenderListDataAsStream` requests.
Could you check the responses of these requests (`ListSchema` -> `Field`) and verify if the `ClientSideComponentProperties` are set there?

Sorry for using your time on that, but we can't repro the bug and need to understand its nature to perform any next steps.

**Comment by JLRishe** [comment] 2021-12-13 15:05
Thank you very much for your continued assistance.

I've just tried that, and I see two POST requests to that endpoint and one OPTIONS request.

For the first POST, the response contains the correct `ClientSideComponentProperties` value, but for the second one, the field schema is there, but its `ClientSideComponentProperties` property is absent (screenshots below). I can also see that there are some other schema properties that are present in the first but not the second (AutoHyperlink), and vice-versa (Filterable, ReadOnly, Sortable).

I can also observe the same behavior on a different list in a different site collection.

The respective correlation IDs for those two POST requests are 60670ca0-d098-c000-a331-96e5e4ea42ae and 63670ca0-b0b5-c000-a331-9587774e22f6, in case that's useful at all.

First POST:
![image](https://user-images.githubusercontent.com/6964029/145835378-85e3b4b2-ab64-41f5-b7bb-3abfdc9bed70.png)

Second POST:
![image](https://user-images.githubusercontent.com/6964029/145835505-c9696bd5-3556-472d-9e57-49d5a0878617.png)

**Comment by AJIXuMuK** [comment] 2021-12-14 16:44
Hi @JLRishe - thank you for sharing this info.
Could you please PM me your tenant url and the correlation ids (I'd also ask to catch the problem again to have fresh ids) to aterentiev@microsoft.com?

**Comment by JLRishe** [comment] 2021-12-14 17:52
@AJIXuMuK Thank you for all your help. I have just sent e-mail to the address you provided. I've discovered something very odd in the process of drafting that message, which I'll reproduce below:

---------------

After copying out the request URLs, I’ve noticed something very odd.
The second RenderListDataAsStream request seems to be going to http://localhost:42050, and somehow a response is coming back. And unlike yesterday, there is no correlation ID present in the response.
I’ve tried viewing the same page on another machine, and there too, it attempts to make a request to localhost:42050, but the request fails there, and on that machine, I do not experience the issue with properties not being passed in.
I’ve also tried viewing the page in another browser (Edge) to make sure there isn’t some browser extension causing this, but I see the same behavior there.
And as was the case yesterday, the first RenderListDataAsStream request (which seems to be actually going to the tenant) contains the component properties, and the second one (to localhost) doesn’t.

---------------

Given that the properties issue doesn't occur on the other machine where I tried this, it seems that this localhost request, whatever it is, is at the heart of this problem.

**Comment by AJIXuMuK** [comment] 2021-12-15 20:45
Thank you @JLRishe for all the information you've provided! It helped to pinpoint the issue.
The problem is related to Offline Client Availability of the list. 
The fix has been made but will probably appear WW in February timeframe.

Until then you can use a workaround:
1. Disable "Offline Client Availability" for the specific list (Go to List Settings -> Advanced Settings and turn of the setting), or
2. Disable the sync for the whole tenant as described here: https://docs.microsoft.com/en-us/SharePoint/lists-sync-policies

Hope it helps!

**Comment by patmill** [comment] 2022-01-12 19:38
This should be WW now.

**Closed by patmill** 2022-01-12 19:38 UTC
Labels: area:spfx, status:fixed-next-drop, area:spfx-in-lists
