### ISSUE TITLE
O365 CDN Invalid nonce key configuration

### ISSUE THREAD

**Issue by palcheuski** [SharePoint/sp-dev-docs#1731] opened 2018-04-23 12:46 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
SPFx webpart/extension solution package JavaScript scripts loaded successfully on SharePoint modern page from Office 365 CDN default origin (*/CLIENTSIDEASSETS) enabled on a tenant.

Below is a sample from working tenant
![image](https://user-images.githubusercontent.com/12794771/39125585-1b666fd0-4708-11e8-9fa0-e47a3bbeeae7.png)

#### Observed Behavior
SPFx webpart solution package is successfully deployed to AppCatalog and all resources appear in the ClientSideAssets library. Finally, SPFx solution is successfully installed on the target site collection. After adding webpart on the canvas we see the following results. Here on the screenshot you can see that SharePoint tries to access resources from CDN, but it results to 406 error code. 

Below is a sample from NOT working tenant
![image](https://user-images.githubusercontent.com/12794771/39125859-23e0be6c-4709-11e8-8437-a19363849196.png)

Some inspection in Fiddler, here we can see an error message that is not very clear what exactly wrong.
![image](https://user-images.githubusercontent.com/12794771/39126294-9e9d4232-470a-11e8-887b-39f24d0394ab.png)
 

#### Steps to Reproduce
1. Enable O365 CDN using PowerShell Cmdlet, so that we have the final settings as bellow 
![image](https://user-images.githubusercontent.com/12794771/39126540-66d49c8c-470b-11e8-931a-e9b5d2368bc8.png)

2. Deploy SPFx solution package to the AppCatalog, here is what I have in my tenant
![image](https://user-images.githubusercontent.com/12794771/39126657-9db405b2-470b-11e8-9b56-56f485b17c8d.png)

When deployment completed, i could see that resources are added to the ClientSideAssets library. Here is the proof.
![image](https://user-images.githubusercontent.com/12794771/39126759-dadd80b2-470b-11e8-9d11-e9cb81611dce.png)

3. Create a team site (classic or modern, it doesn't matter).
4. Install SPFx solution from the AppCatalog to the target site collection.

When it is added to the site, there is no errors in the App Details page. here is a screenshot
![image](https://user-images.githubusercontent.com/12794771/39127000-72039968-470c-11e8-8272-e15e9fb42499.png)

5. Add custom webpart from the SPFx solution to the modern page, open DevTools in the Chrome and switch to the network tab, from here you can see a lot requests with 406 errors when trying to access resources from the public cdn.

![image](https://user-images.githubusercontent.com/12794771/39127319-5ad63092-470d-11e8-958c-2ae537386f77.png)

**Comment by michelsmit** [comment] 2018-04-26 11:01
Have the same exact error message on my tenant. No solution yet.

{"HttpStatus":"NotAcceptable","ErrorMessage":"Invalid nonce key configuration","ErrorCode":406001}

**Comment by patmill** [comment] 2018-04-26 19:16
Just being super clear - the configuration is for a public CDN, correct?  My understanding was that the nonce for a request to a CDN was only for private configurations.  Is it possible that the configuration was changed in some form?  If you request private configurations, what comes back?

**Comment by palcheuski** [comment] 2018-04-27 07:11
@patmill , yes, that is the configuration for the public CDN, we don't yet have a private CDN configured. As shown in my screenshots, all requests to the CDN start with  the base path https://**publiccdn**.sharepointonline.com/<tenant>/<origin>/<resource_relative_path>. It seems to me, that there are some some problems with the propagation to the public CDN.

**Comment by palcheuski** [comment] 2018-04-27 14:03
@VesaJuvonen , maybe there is some news on this issue?

**Comment by luis-ribeiro** [comment] 2018-04-28 18:26
Are you using a O365 developer account? I had the same issue (the error output was the same) when using a O365 developer account tenant. 
I have repeated the same steps on a fresh regular trial tenant and everything worked as expected.

**Comment by michelsmit** [comment] 2018-05-01 08:41
For me no developer account (production tenant), public cdn. The issue is only with this particular tenant, not other tenants I manage. I created a ticket with MS support.

**Comment by waldekmastykarz** [comment] 2018-05-11 13:31
I'm experiencing the same issue in my tenant:
- Public CDN enabled with default origins
- Assets provisioned from the solution package to ClientSideAssets and accessible via the doc lib URL
- Accessing the same assets via the Public CDN URL results in a 406 and prevents the web part from loading

**Comment by LeemansBE** [comment] 2018-05-16 12:32
Any update on this? We are experiencing the same issue in our newly created tenant.

- Files are accissible through the style library
- Accessing the same files through the public CDN results in 406: "Invalid nonce key configuration"

**Comment by jeslas** [comment] 2018-05-31 11:01
Same issue on newly create dev tenant

**Comment by palcheuski** [comment] 2018-05-31 11:58
I lost hope for an answer, issue is still actual for me.

**Comment by falkin** [comment] 2018-06-05 14:49
Have the same exact error message on my tenant. Nobody found a solution ? it's really really annoying -_- and very blocking.

**Comment by patmill** [comment] 2018-06-06 23:48
Just touching base.  We've got a repro of this with full logs, and see what is happening.  Working on "why" and "how to get it to work".

**Comment by tocnr** [comment] 2018-06-07 04:13
Just started seeing this on our production tenant. The Public CDN has been working for months and is just now having problems. This has a pretty big impact since we have started using SPFx pretty extensively. It also seems pretty inconsistent depending on the network used to access the tenant - in some cases assets will load and in others fails with the above error.

**Comment by VesaJuvonen** [comment] 2018-06-12 07:36
We are investigating this issue. For now - you can make your samples and solutions to work by disabling the CDN as that will then automatically instruct SharePoint to serve the assets from the app catalog. This does NOT require any changes on your sppkg files/solutions as long as you are using the "asset packaging" which was released with SPFx 1.4.

**Comment by BjoernHund** [comment] 2018-06-12 18:14
Same issue on a development tenant. Disabling the public CDN in this tenant worked, but is only a temporary solution.

We have now the first production tenant with the same problem.

**Comment by VesaJuvonen** [comment] 2018-06-20 10:05
We should have this now sorted out in the server side. We do apologize for the massive delay on getting this fully fixed. We would like to get through still confirmation from anyone who had the issue that it's not being resolved. This was only impacting a subset of tenants, so we are having a hard time verifying this end-to-end from our end, so your input would be highly welcome. Thanks for your input advance.

**Comment by BjoernHund** [comment] 2018-06-20 17:44
I will test it on our development tenants on this friday and then report the result.

**Comment by WayneJSawyer** [comment] 2018-06-20 21:13
@VesaJuvonen - Set one of my dev tenants back to CDN enabled, waited for 'configuration pending' to go away on the origins, and confirmed that the JS files are now being served up correctly via publiccdn.sharepointonline.com

Thanks!

**Comment by VesaJuvonen** [comment] 2018-06-21 06:07
As we have got now confirmations on the issue getting fixed, will close this one. We do apologize for the issue and have now made actions to avoid similar issues in future.

**Closed by VesaJuvonen** 2018-06-21 06:07 UTC
Labels: area:cdn, area:other, status:tracked, type:bug
