### ISSUE TITLE
Extension is not triggered going back from search results

### ISSUE THREAD

**Issue by arnas47** [SharePoint/sp-dev-docs#1475] opened 2018-03-15 13:05 UTC
- [x ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Hi,

I just noticed in communication site, that when you go to search results page and then click arrow at the top left corner - "Go back to host application", it goes back to home page, reloads only content area web parts, but not the whole page and it doesn't trigger any extensions. My question - is this how it suppose to work, extensions are triggered only on page load/reload? Pretty much the same issue in when you go from one home layout type page to another - extensions are not triggered.

**Comment by VesaJuvonen** [comment] 2018-03-15 16:13
Seems to be a duplicate of #1178

**Comment by arnas47** [comment] 2018-03-16 07:20
Yes, the exact issue is described in #1042

**Comment by OmniFace** [comment] 2018-04-23 17:55
@VesaJuvonen 

#1042 and subsequently this is closed.  I see that moving **back** to the home page **does** trigger the navigatedEvent.  

However, starting on the home page and moving **to** the search results page, or performing additional searches there does **not** trigger navigatedEvent.  

Is that expected behavior?

**Comment by VesaJuvonen** [comment] 2018-04-23 18:31
Let's reopen and double check things. Thx @OmniFace for coming back on this.

**Comment by OmniFace** [comment] 2018-04-23 20:30
Thanks @VesaJuvonen,

I just double checked my "canary" tenancy and "developer" tenancy to be sure it wasn't just my dev tenancy with the problem.  Both appear to have the same lack of navigatedEvent call when dealing with search results still.  Below are instructions to reproduce for each tenancy type:

Canary tenancy site

1. Open Internet Explorer
2. Open a group site collection home page
3. Open the browser Debugger
4. Select app-extension file
5. Prettify code
6. Set a breakpoint within a navigatedEvent callback
7. Return to browser
8. Type text into search box
9. Hit Enter, or click "See more results for <term>" link
10. Results page loads
11. Note - no navigatedEvent call
12. Change the search scope from the current site collection to All sites
13. Results page loads
14. Note - no navigatedEvent call
15. Click All in Filters
16. Select a filter such as News
17. Results page loads
18. Note - no navigatedEvent call
19. Click "Go back to host application" Arrow in upper left search
20. Home page loads
21. Note - navigatedEvent is called


Developer tenancy site

1. Open Internet Explorer
2. Open a group site collection home page
3. Open the browser Debugger
4. Select app-extension file
5. Prettify code
6. Set a breakpoint within a navigatedEvent callback
7. Return to browser
8. Type text into search box
9. Hit Enter, or click "See more results for <term>" link
10. Results page loads
11. Note - no navigatedEvent call
12. Change the search scope from All to Files
13. Results page loads
14. Note - no navigatedEvent call
15. Click Filters
16. Select a filter
17. Results page loads
18. Note - no navigatedEvent call
19. Click Exit search
20. Home page loads
21. Note - navigatedEvent is called

**Comment by VesaJuvonen** [comment] 2021-11-01 17:53
This issues should be fully solved and fixed, given the work we have done in engineering in this area. To ensure that we clean up the backlog of the issues, we will be closing this one. If you still have issues on this particular area, please open up a new issue so that we can get updated issue description and reproduce steps. We do apologize the non-optimal handling of these old issues and are looking into improving this in future.

**Closed by VesaJuvonen** 2021-11-01 17:53 UTC
Labels: status:tracked, area:other, type:bug-confirmed

**Comment by OmniFace** [comment] 2021-11-08 17:47
> 
> 
> This issues should be fully solved and fixed, given the work we have done in engineering in this area. To ensure that we clean up the backlog of the issues, we will be closing this one. If you still have issues on this particular area, please open up a new issue so that we can get updated issue description and reproduce steps. We do apologize the non-optimal handling of these old issues and are looking into improving this in future.

Moving back and forth from a page to search results does appear to fire a navigatedEvent now.

Using the scope/filter options do not.  Intended behavior on that was never clarified in this issue, so I don't know if that's problem or not.
