### ISSUE TITLE
SPFX 1.12 issue with tslib?

### ISSUE THREAD

**Issue by FredrikEkstroem** [SharePoint/sp-dev-docs#6856] opened 2021-03-23 21:45 UTC
## Category

- [x] Bug

## Describe the bug

It looks like there is an issue with SPFX 1.12 somehow connected to tslib that completely breaks a webpart. I have seen it under a few different scenarios like when upgrading from 1.11 to 1.12, getting the code from git and creating a new webpart. The issue causes an error when loading the webpart on the page, like below.
```javascript
[SPLoaderError.loadComponentError]:
Failed to load component "68a22704-85d9-427e-98cd-1afeb7b83b04" (HelloWorldWebPart). Original error: Manifest not found for component id "01c4df03-e775-48cb-aa14-171ee5199a15" and version "1.14.1".

INNERERROR:
Manifest not found for component id "01c4df03-e775-48cb-aa14-171ee5199a15" and version "1.14.1".
CALLSTACK:
Error
    at t [as constructor] (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_c4afef6428368ce9a00f6228bb686f89.js:65:19890)
    at new t (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_c4afef6428368ce9a00f6228bb686f89.js:65:170290)
    at Function.e.buildErrorWithVerboseLog (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_c4afef6428368ce9a00f6228bb686f89.js:65:207609)
    at Function.e.buildLoadComponentError (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_c4afef6428368ce9a00f6228bb686f89.js:65:203654)
    at https://modern.akamai.odsp.cdn.office.net/files/sp-client/chunk.systemjs-component-loader_en-us_2ebb0419bb86e53022fa.js:1:65977
```
looking at that ID, it is tslib. When the webpart is broken the tslib entries looks like below 
./release/component-dependency-audit/{projectname}.json
```json
{
    "componentId": "01c4df03-e775-48cb-aa14-171ee5199a15",
    "componentName": "tslib",
    "componentVersion": "1.14.1",
    "isDirectDependency": true
  },
  {
    "componentId": "01c4df03-e775-48cb-aa14-171ee5199a15",
    "componentName": "tslib",
    "componentVersion": "1.10.0",
    "isDirectDependency": false
  }
```
./release/manifests/{guid}.json
```json
"tslib": {
    "type": "component",
    "id": "01c4df03-e775-48cb-aa14-171ee5199a15",
    "version": "1.14.1"
  }
```
When it works, the same entry looks like this
./release/component-dependency-audit/{projectname}.json
```json
{
    "componentId": "01c4df03-e775-48cb-aa14-171ee5199a15",
    "componentName": "tslib",
    "componentVersion": "1.10.0",
    "isDirectDependency": true
  },
```
./release/manifests/{guid}.json
```json
"tslib": {
    "type": "component",
    "id": "01c4df03-e775-48cb-aa14-171ee5199a15",
    "version": "1.10.0"
  },
```

After enouncing this issue, I can't roll it back by deleting reference in package.json and deleting package-lock.json and node_modules folders, the only way was to create a completely new project (might have missed some place to do rollback?)

I have seen this issue when using both @microsoft/mgt, @pnp/js, but it feels like it might relate to other libraries with different tslib version dependencies aswell. @patrick-rodgers added a temporary fix (to get around what I suspect is a related issue) in pnp js, but I don't think he found the root cause to the issue yet. [Issue in pnp js](https://github.com/pnp/pnpjs/issues/1654)

Is there something not "honoring" this tslib version specified in the dependencies of the modules?

## Steps to reproduce
After trying a lot of different scenarios I think I have found a simple way to reproduce that works consistently by creating a new project
**Broken example**
- Create new project and skip install
```javascript
yo @microsoft/sharepoint --skip-install
```
- Press yes on all questions
- Select react as library
- manually add "@microsoft/mgt": "^2.1.0" under dependencies in package.json
- run npm install
- Add below to HelloWorldWebPart.ts
```typescript
import {Providers, SharePointProvider} from '@microsoft/mgt';
//in Hello world class
protected async onInit() {
  Providers.globalProvider = new SharePointProvider(this.context);
}
```
- run gulp serve --nobrowser
- Add webpart to page, this will lead to error

**Working example**
- Create new project **do not skip install**
```javascript
yo @microsoft/sharepoint
```
- Press yes on all questions
- Select react as library
- run npm install
- run npm install @microsoft/mgt --save
- Add below to HelloWorldWebPart.ts
```typescript
import {Providers, SharePointProvider} from '@microsoft/mgt';
//in Hello world class
protected async onInit() {
  Providers.globalProvider = new SharePointProvider(this.context);
}
```
- run gulp serve --nobrowser
- The webpart now loads without error

## Expected behavior

It should not create this error and rollback should be simple

## Environment details (*development & target environment*)
- Win 10
- SharePoint Online
- Node.js v12.21
- VS Code
- SPFx v1.12
- @microsoft/generator-sharepoint@1.12.0
- tslib, pnpjs, mgt
- **Additional details**: *The more context you can provide, the easier it is (and therefore quicker) to help.*

**Comment by KevinTCoughlin** [comment] 2021-03-23 22:25
Related: https://github.com/pnp/pnpjs/issues/1654

**Comment by PathToSharePoint** [comment] 2021-03-23 22:30
Side comment here with my own experience.

I originally had the same issue, but I was unable to reproduce it when I tried again yesterday. Not sure if it helped, but I was very careful and only did the minimum required upgrades: SPFx 1.12, Nodejs 10.24.0, TypeScript 3.7.

Here is the package I just posted today, which also uses mgt and mgt-react:
https://github.com/PathToSharePoint/React-PPP-MicrosoftGraphToolkit

For the record, I actually built it to [report a bug with mgt-react](https://github.com/microsoftgraph/microsoft-graph-toolkit/issues/950). But the Web Part itself works fine.

**Comment by FredrikEkstroem** [comment] 2021-03-24 10:09
According to @VesaJuvonen  SPFX 1.12.0 is to be "considered as deprecated", and a fix will be coming later, [see tweet](https://twitter.com/vesajuvonen/status/1374620639080894464).

Is this issue part of that fix?

**Comment by VesaJuvonen** [comment] 2021-03-24 12:27
This issue is intended to be part of the 1.2.1 patch release. Currently we recommend to keep on using 1.11 until further notice. We do apologize the inconvenience.

**Comment by FTAmcmahon** [comment] 2021-03-24 13:09
I had the same issue above with the 2 dependencies for tslib being added to the manifests which failed to find 1.14.1.

Bare minimum repro:
On a fresh new ootb webpart, I noticed that it only started to happen when importing a fabric component from the original package, eg:
```
import { TextField } from "office-ui-fabric-react";
```
If I imported any available component (not all components are exposed here) directly from the bundle it worked fine:
```
import { TextField } from "@microsoft/office-ui-fabric-react-bundle";
```

As it seemed to be a dependency resolution issue with yarn, I managed to get around it by adding a resolution to tslib 1.10.0 in my package.json file:
```
    "resolutions": {
        "tslib": "1.10.0"
    },
```

Not a great solution as yarn install whines about version incompatibilities, but the webpart does load. 👍 

Hopefully that can help someone in the same boat, however it's probably irrelevant now given the above info from @FredrikEkstroem re Vesa's tweet (thanks for the heads up).

**Comment by KevinTCoughlin** [comment] 2021-03-25 22:27
We believe to have identified the root cause using a repro from this issue and will include the fix in `1.12.1` release.

**Comment by KevinTCoughlin** [comment] 2021-04-12 18:53
@FredrikEkstroem can you confirm this tslib issue is fixed in `1.12.1-rc.0` suite of packages e.g. https://www.npmjs.com/package/@microsoft/generator-sharepoint/v/1.12.1-rc.0?

**Comment by FredrikEkstroem** [comment] 2021-04-13 10:35
@KevinTCoughlin I tried the exact scenario I described above using Node v14.16.1 and Generator 1.12.1-rc.0 and that was working now without issues

**Comment by KevinTCoughlin** [comment] 2021-04-13 15:46
> @KevinTCoughlin I tried the exact scenario I described above using Node v14.16.1 and Generator 1.12.1-rc.0 and that was working now without issues

Great to hear. Thanks for confirming!

**Closed** 2021-04-13 15:46 UTC
Labels: 1.12.x, area:tooling, status:fixed, status:tracked, type:bug-confirmed
