### ISSUE TITLE
404 Not Found: @microsoft/sp-search-extensibility@1.10.0

### ISSUE THREAD

**Issue by Scheevel** [SharePoint/sp-dev-docs#5084] opened 2020-01-07 21:02 UTC
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

npm ERR! code E404
npm ERR! 404 Not Found: @microsoft/sp-search-extensibility@1.10.0

steps to replicate in VS-code:
[yo version 6.4.1]
yo
>(a)microsoft/sharepoint
>SharePoint Online only (latest)
>WebPart
>No JavaScript Framework

npm install
npm ERR! code E404
npm ERR! 404 Not Found: @microsoft/sp-search-extensibility@1.10.0

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '@microsoft/sp-search-extensibility@1.10.0' ]
2 info using npm@6.4.1
3 info using node@v10.15.3
4 verbose npm-session e1b19b4e29b67172
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 https://registry.npmjs.org/@microsoft%2fsp-search-extensibility 266ms
8 silly fetchPackageMetaData error for @microsoft/sp-search-extensibility@1.10.0 404 Not Found: @microsoft/sp-search-extensibility@1.10.0

**Comment by patmill** [comment] 2020-01-07 21:39
Thanks Scheevel.  Ran into an issue with the new package.  We're getting the package perms sorted out and should have it published shortly.

**Comment by mikezimm** [comment] 2020-01-07 21:50
Same here....
![image](https://user-images.githubusercontent.com/49648086/71932411-cd131e80-316d-11ea-9bc9-d14cd145047f.png)

**Comment by patmill** [comment] 2020-01-07 21:56
Although a heads up, the search package will only be available in the 'preview' 1.10.0-plusbeta
 version, not the 'standard' 1.10.0 version, as it is still in preview.

**Comment by mikezimm** [comment] 2020-01-07 21:59
Just curious if I did htis right...
I installed, then did info and it looks like a really old modified date.  Is that the problem or is it that I am not checking version correctly?

![image](https://user-images.githubusercontent.com/49648086/71932943-f7b1a700-316e-11ea-8763-68abfd07ae94.png)

**Comment by patmill** [comment] 2020-01-07 22:01
@mikezimm - your npm info was against the non-@microsoft package.  You'll want to run `npm info @microsoft/generator-sharepoint`

**Comment by mikezimm** [comment] 2020-01-07 22:11
@patmill, Thanks for pointing that out... I was trying different things because of the @microsoft/sp-search-extensibility error and must have had that in the clipboard.

Upon running the right command I see the latest info.

I was able to roll back my generator to 1.9.1 and scaffold a new project with that for now.
Thanks!

**Comment by andrewconnell** [comment] 2020-01-08 10:34
Dupe of #5083

**Closed by andrewconnell** 2020-01-08 10:34 UTC
Labels: area:generator, status:duplicate
