### ISSUE TITLE
SPFx 1.16.0 webpart final package size is almost 4x larger compared to 1.15.2

### ISSUE THREAD

**Issue by DmitriyVdE** [SharePoint/sp-dev-docs#8599] opened 2022-11-22 08:35 UTC
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx version: 1.15.2 & 1.16.0
- Node.js version 16.18.1

### Issue description

Hi

Last week SPFx 1.16.0 was released on GA and yesterday I upgraded and built a package from 1.15.2.
I noticed that the final size of the package was 1.921 KB while the 1.15.2 built package was only around 550 KB.

Now I don't know what the final package size is that will be downloaded to the client, but this seems abnormally large.
Is this because of the inclusion of the Teams SDK v2 in SPFx 1.16.0?
Also, is there maybe some logic that filters out only the required data in SPO/Teams/etc... so that clients don't have to download the whole package?

For now we'll hold off on using SPFx 1.16.0 since we have pages containing 10+ webparts and this would increase the required download size substantially.

-D

**Comment by jensotto** [comment] 2022-11-22 13:56
It seems that the sppkg file is not compressed. The actual web part files in my SPFx 1.16.0 test upgrade are smaller than the same files in SPFx 1.15.2. As the sppkg file is not downloaded to the clients I think it's only a minor issue for the file size uploaded to the app catalog. It's the content in the sppkg file that matters for clients.
It should be fixed, but I don't think it's a show stopper.

**Comment by kbeeveer46** [comment] 2022-11-22 15:11
I literally just logged on to post this same issue. My sppkg file went from 8 MB to 32 MB.

**Comment by DmitriyVdE** [comment] 2022-11-23 09:44
> 

Thanks for the insight!

The issue is that we deliver a product containing 40+ packages that we update multiple times per year on quite a few customers. Having the package size increase 4 fold is quite a leap.

We'll just wait and see if this changes in a future .1 or .2 update.

**Comment by AJIXuMuK** [comment] 2022-11-30 16:27
1.16.1 has been released. The issue is fixed.

**Closed by AJIXuMuK** 2022-11-30 16:27 UTC
Labels: area:spfx
