### ISSUE TITLE
SPFx Application Extension with Top or Bottom placeholders don't render on modern Events pages

### ISSUE THREAD

**Issue by mpowney** [SharePoint/sp-dev-docs#1445] opened 2018-03-07 12:18 UTC
#### Category
- [ ] Question
- [ ] Typo
- [ ] Bug
- [x] Additional article idea

#### Expected or Desired Behavior

When an App Customizer with the Top or Bottom placeholder pattern as per documentation here:

[Using Placeholders with Extensions](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/using-page-placeholder-with-extensions)

... is deployed to a modern site, the modern events experience (offered by /_layouts/15/Event.aspx) should re-render the app customizer's Top/Bottom placeholders.
 
#### Observed Behavior

When a Modern comms site is created, the default modern site home page includes an Events web part. When clicking on the "Add Event" button, the browser directs the user to an address like: 

<site collection>/_layouts/15/Event.aspx?ListGuid=9b7b97aa-3a1f-4379-8352-330ab46ca53f&Mode=Edit

However, the new page is only partially rendered, so the pattern described in the [Using Placeholders with Extensions](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/using-page-placeholder-with-extensions) article doesn't allow for the placeholder content to be re-rendered.

When you perform a browser refresh on the same /_layouts/15/Event.aspx page, the placeholders render successfully.

#### Steps to Reproduce

1. Create new modern Comms site
2. Create new SPFx app customizer
3. Update app customizer with steps from: [Using Placeholders with Extensions](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/using-page-placeholder-with-extensions)
4. Deploy the app to the tenant's app catalog
5. Browse to the comms site's home page
6. Add the recently app to the site from the app catalog
7. Click the "Add Event" button that's included on the home page by default
8. The browser's web address will change to /_layouts/15/Event.aspx?ListGuid...  but the page was only partially rendered, i.e. the O365 suite bar remains in place
9. Observe the app customizer's placeholders no longer show
10. Refresh the page, the app customizer's placeholders are now rendered

**Comment by rgylesbedford** [comment] 2018-03-09 16:31
I think this is the same as #1263

**Comment by mpowney** [comment] 2018-03-10 00:12
Yes it seems to be the same bug - perhaps something this is an issue in the prod client side pages code, not a SPFx documentation bug...

Keeping a note for the record, the error observed here and in #1263:

Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined
    at e._scrollEventHandler (sp-pages-assembly_en-us_ec564824dbf6a181d45720395d9a194e.js:formatted:71231)
    at e (sp-pages-assembly_en-us_ec564824dbf6a181d45720395d9a194e.js:formatted:36172)
    at u (sp-pages-assembly_en-us_ec564824dbf6a181d45720395d9a194e.js:formatted:36177)
    at e.s (sp-pages-assembly_en-us_ec564824dbf6a181d45720395d9a194e.js:formatted:36216)

Occurs in the following o365 production bundle:
https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-02-23.006/sp-pages-assembly_en-us_ec564824dbf6a181d45720395d9a194e.js:formatted

**Comment by mpasarin** [comment] 2018-03-19 22:46
This is a duplicate of #1042 , which yes, it's the same as #1263 
I'll close this issue and let's track it on the original one.

**Closed by mpasarin** 2018-03-19 22:46 UTC
Labels: status:duplicate
