### ISSUE TITLE
[SPLoaderError.loadComponentError]: Failed to load component "guid" (web-part-name). Original error: Failed to load URL

### ISSUE THREAD

**Issue by magnusdanielson** [SharePoint/sp-dev-docs#8261] opened 2022-07-02 11:02 UTC
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version 103.0.5060.66 (64-bit)
- SPFx version 1.15.0
- Node.js version 14.19.0
- etc

### Describe the bug / error

Some of our spfx webparts completly broke yesterday.

I have today created a new spfx webpart from scratch. It works fine in the workbench. When I then deploy the spfx-solution to the app catalog and select deploy to all sites. When I add the webpart to any page I get below error:

[SPLoaderError.loadComponentError]:
Failed to load component "3f69a57a-43cb-48b9-96ed-9442865f93d9" (PDualiteInboxWebPart). Original error: Failed to load URL 'https://publiccdn.sharepointonline.com/dunite.sharepoint.com/sites/apps/ClientSideAssets/d213e94e-e127-455c-bdb8-a5136466ac67/PDualiteCaseWebPartStrings_en-us_ab0373b2a20479e31e6fa297c55f351c.js' for resource 'PDualiteCaseWebPartStrings' in component '3f69a57a-43cb-48b9-96ed-9442865f93d9' (PDualiteInboxWebPart). There was a network problem. This may be a problem with a HTTPS certificate. Make sure you have the right certificate.

INNERERROR:
Failed to load URL 'https://publiccdn.sharepointonline.com/dunite.sharepoint.com/sites/apps/ClientSideAssets/d213e94e-e127-455c-bdb8-a5136466ac67/PDualiteCaseWebPartStrings_en-us_ab0373b2a20479e31e6fa297c55f351c.js' for resource 'PDualiteCaseWebPartStrings' in component '3f69a57a-43cb-48b9-96ed-9442865f93d9' (PDualiteInboxWebPart). There was a network problem. This may be a problem with a HTTPS certificate. Make sure you have the right certificate.
CALLSTACK:
Error
    at t [as constructor] (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_sv-se_0f830cb1945ad38b3ca381dc68b15698.js:70:214378)
    at new t (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_sv-se_0f830cb1945ad38b3ca381dc68b15698.js:71:7811)
    at e.buildErrorWithVerboseLog (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_sv-se_0f830cb1945ad38b3ca381dc68b15698.js:71:45088)
    at e.buildLoadComponentError (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_sv-se_0f830cb1945ad38b3ca381dc68b15698.js:71:41179)
    at https://res-1.cdn.office.net/files/sp-client/chunk.systemjs-component-loader_sv-se_dc58eaaa7aaff14eda18.js:1:6012

To me it looks like it is something wrong with the cdn-service.

I have double checked that the "missing file" acutally is part of the solution package.

### Steps to reproduce

1. run yo sharepoint to create a new spfx webpart
2. run gulp bundle --ship
3. run gulp package-solution --ship
4. upload solution to app catalog
5. add webpart to page
6. it now fails to load

### Expected behavior

I expected the webpart to load.

I have tested to upload the same package to one other tenant it works fine there.

**Comment by magnusdanielson** [comment] 2022-07-04 08:06
Today I created a brand new spfx with yeoman according to Microsoft instructions.

I did not change anything in the webpart. I then built and deployed according to instructions and that webparts is also broken.

I deployed the same webpart to another tenant and it works fine there. I took the url to the js file and made a get request from postman with the referrer https://ourdomain.sharepoint.com/ and it get the file properly.

![image](https://user-images.githubusercontent.com/12081481/177110299-f60cda71-d2e7-4fa6-a072-c2119d71def0.png)

If I do the same for our tenant that is broken, I get below response. Is there any way to fix this?

![image](https://user-images.githubusercontent.com/12081481/177110450-4a7fc2cf-41db-4b63-8d80-8cfa6ef65a78.png)

**Comment by marcusroberts** [comment] 2022-07-04 16:34
I think I just created a duplicate of this as #8270 

We see the same, but on just one of our customers' tenancies.   Disabling Public CDN got the app working again for us, but we would prefer to deploy to the CDN if we can.

**Comment by magnusdanielson** [comment] 2022-07-04 21:57
The only thing I can think of that could have caused this was that I was cleaning some default values and changed the solution.name in package-solution.json

`"solution": {
    "name": "i-changed-this-name",`

It is a long shot but when I deployed this package everything broke down. When I reverted the package-solution, updated the version number everything was still broken. So, either me or something else seems to have broken the cdn.

If I turn off the CDN service, and then turn it on again. Will it be deployed to a new clean resource so it will likely work? How long time do we need to wait between disabling the CDN before we turn it on again?

**Comment by marcusroberts** [comment] 2022-07-05 07:21
We tried turning the CDN service off - components loaded.  We left it off for about 8 hours.
As soon as we switched the CDN back on, they failed to load again.

**Comment by dev-a11y** [comment] 2022-07-05 11:11
We have exactly the same problem on our side as well (`Failed to load URL: 'https://publiccdn.sharepointonline.com/... There was an error requesting the file.`). Definitely something bad is happening with Public CDN in SharePoint Online hosting SPFx customizations. Problems started recent 2-3 weeks and are becoming more and more apparent. Please check the infra and let us know the status. In case anyone wonders: '?sw=bypass' flag does not help at all here.

Do you have any stats on failing requests on CDN side?
Do you have any telemetry based indicators of problems customers may be dealing with here?

Great questions and concerns already stated:
'If I turn off the CDN service, and then turn it on again. Will it be deployed to a new clean resource so it will likely work? How long time do we need to wait between disabling the CDN before we turn it on again?' - any insight on this highly appreciated as it is still possible to mess up things even worse I guess (we have users who are not impacted on same tenant).

**Comment by AJIXuMuK** [comment] 2022-07-05 21:19
Thanks for all the details provided here.
Could you please double-check if the issue is still there?
Also, could you please send me the tenants where you're experiencing the issues and correlation id (request-id) for the failing requests? You can send it to aterentiev@microsoft.com

**Comment by dev-a11y** [comment] 2022-07-06 11:13
Yes, the issue remains.

I'm not sure how and if request tracking works in this case.
Below is an example of Public CDN request and selected headers generated by service.
YYY in 'Report-To' header is a tenant id and XXX is a request/correlation id.

Could you please review data collected by Azure Function hosted on 'spo.nel.measure.office.net' and provide any insight for the issue we are facing? Is 'Report-To' header supposed to be interpreted by end user browser or is it interpreted by some intermediate servers in Microsoft or Akamai networks (meaning - _who is supposed to let you know that bad things are happening with CDN_)?

```
Request URL: https://publiccdn.sharepointonline.com/mytenant.sharepoint.com/ClientSideAssets/packagesolutionid/webpartbundle.js
Request Method: GET
Remote Address: 104.66.116.58:443
Accept: */*
Host: publiccdn.sharepointonline.com
Origin: https://mytenant.sharepoint.com
Referer: https://mytenant.sharepoint.com/

HTTP/1.1 406 Not Acceptable
Content-Length: 98
Content-Type: application/json; charset=utf-8
SPRequestGuid: XXX
request-id: XXX
MS-CV: ZZZ
Report-To: {"group":"network-errors","max_age":7200,"endpoints":[{"url":"https://spo.nel.measure.office.net/api/report?tenantId=YYY&destinationEndpoint=Edge-Prod-HEL01&frontEnd=AFD"}]}
NEL: {"report_to":"network-errors","max_age":7200,"success_fraction":0.001,"failure_fraction":1.0}
SPRequestDuration: 26
MicrosoftSharePointTeamServices: 16.0.0.22622

```

**Comment by dev-a11y** [comment] 2022-07-06 11:32
Isn't it same as this one? #1731 (reported on Apr 23, 2018)
one of last responses (on Jun 20, 2018):
_'We should have this now sorted out in the server side. We do apologize for the massive delay on getting this fully fixed. We would like to get through still confirmation from anyone who had the issue that it's not being resolved. This was only impacting a subset of tenants, so we are having a hard time verifying this end-to-end from our end, so your input would be highly welcome. Thanks for your input advance.'_ ~https://github.com/SharePoint/sp-dev-docs/issues/1731#issuecomment-398696072

**Comment by magnusdanielson** [comment] 2022-07-06 12:01
I have sent the request information to the email adress provided above. It is still an issue. If you have not received the info please let me know.

**Comment by marcusroberts** [comment] 2022-07-06 14:44
I'll need to wait to out of hours because it's too disruptive otherwise, but I can then re-enable the CDN and capture the errors and correlation IDs.

**Comment by 2toLeadMike** [comment] 2022-07-11 20:10
Note that we're seeing a similar issue at the moment trying to upgrade a solution last week. It acts exactly like this issue here and most others issues when CDN is enabled, but our client actually _doesn't have_ it enabled (not served from cdn via network tab, CDN off via PnP) . We get this issue on and off, and often will see old code being served. Reverting the solution immediately fixed it, but there is not a clear path forward.

**Comment by magnusdanielson** [comment] 2022-07-11 21:22
@2toLeadMike if CDN is not enabled and you have troubles with either files not properly loaded or it looks like it reverted to an old version, please verify that you have updated the version number of the package. When you upload a package, it accepts the same version number but, at least to us, it looks like occasionally some maintenance job is performed on the SharePoint server and the first package of every version number is left, everything else is gone. You can verify if this is your problem by checking the version history of the package file. You will notice that changes are missing in the version history.

**Comment by AJIXuMuK** [comment] 2022-07-12 13:44
Quick update: we're investigating the CDN issue internally.
We should have a fix in the next couple of days.
Thanks to all who shared their tenant info - it really helped to do investigation.
Will update as soon as there are additional details.

**Comment by AJIXuMuK** [comment] 2022-07-14 01:15
The fix should be propagated to the farms. 
Could you please confirm is the issue is resolved?

Thanks!

**Comment by marcusroberts** [comment] 2022-07-14 07:43
So far so good, I re-enabled CDN and SPFX components are loading normally again.

**Comment by magnusdanielson** [comment] 2022-07-17 18:32
I had my CDN enabled all the time and the SPFX components are loading normally for me too. Excellent work.

Is there anything we can do on our side to avoid this situation again?

**Comment by marcusroberts** [comment] 2022-07-17 18:41
We re-enabled our CDN and the 406 errors have gone away, thank you!

**Comment by AJIXuMuK** [comment] 2022-07-18 13:15
Great to hear the issue is resolved!

@magnusdanielson - unfortunately, this was farms issue with certificates.
So there is nothing you could do to help here. But thanks for asking!

**Closed by AJIXuMuK** 2022-07-18 13:15 UTC
Labels: type:bug-suspected, area:spfx, Needs: Attention :wave:
