### ISSUE TITLE
SPFx solution as Teams Tab (in native client) with Graph : Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by juanmlarios** [SharePoint/sp-dev-docs#4915] opened 2019-11-18 14:42 UTC
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

Expected or Desired Behavior

SPFx Solution with MS Graph works in MS Teams Native Clients.

Observed Behavior

Cannot read property 'match' of undefined

Steps to Reproduce

Create SPFx web part for Teams
add some MS Graph request
Try to run the web part as Teams tab

This Issue is related to issue: #4357
I tried the following instructions and they did not resolve the issue:

Manual Steps
Step 1. Go to -> https://aad.portal.azure.com/#blade/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade/RegisteredAppsPreview
Step 2. Click on SharePoint Online Client Extensibility Web Application Principal
Step 3. Click Manifest on the left menu
Step 4. Remove all entries in the PasswordCredentials section (Should leave a empty array)
Step 5. Save the manifest
Step 6. Visit the new API Permission Management Page on the Tenant Admin Site. This creates a client secret behind the scenes.
Step 7. Wait 10 minutes

**Comment by muradhaider5** [comment] 2019-11-25 07:47
Facing the same issue with Microsoft Teams native client and Graph API Calls and it's not resolved by following the steps mentioned in the question too.

**Comment by muradhaider5** [comment] 2019-11-25 07:48
Any Update on this please?

**Comment by muradhaider5** [comment] 2019-11-28 14:08
@juanmlarios Finally found what the problem was. The fixes that are suggested will work for the webparts that are NOT configured to be hosted in Isolated domain. So according to my understanding 'SharePoint Online Client Extensibility Web Application Principal' serves here and permissions assigned to such webparts/apps are accessible to other (non-isolated) apps in the tenant as well. When webparts are configured to be hosted in an isolated domain, there is a dedicated application created in Azure AD for that webpart and granted permissions are limited to the corresponding webpart(s) only. But problems i.e. Teams Desktop client issue and Teams sdk issue, still persist with such webparts and Microsoft needs to provide solution for that.

**Comment by muradhaider5** [comment] 2019-11-28 14:14
And also there is a weird problem that appears when isolated webparts are installed as a tab in Microsoft Teams (at least this is the case with me). Every time the tab reloads, webpart is initialized/reset and property pane gets opened. while this is not the case with non-isolated webparts.

**Comment by narulasrinivas** [comment] 2019-12-17 16:59
@wobba -  We're experiencing same issue. This issue is happening only in environment which has (Multi Factor Authentication) MFA enabled for user accounts and other environments are running when it is disabled.

Not sure whether MFA enabled accounts have an issue in accessing graph client via Teams Desktop.

This is my observation after spending 2 whole days. ;)

**Comment by joselarios** [comment] 2020-01-14 18:15
This issue still persists. We have followed the advice of @muradhaider5, i.e. configuring the web part to NOT be hosted in an isolated domain, but we are still receiving the same error.

Of note, we have created a demo O365 tenant to test further and found the following: 

- When logging into the Teams Desktop client with the demo's MOD Administrator, the teams tab loads without error
- For other users, e.g. the demo's Megan Bowen, they do receive the error: Cannot ready property 'match' of undefined.

Any suggestions or updates on this issue?

**Comment by VesaJuvonen** [comment] 2020-01-22 16:23
There are unfortunately known issues around this area on hosting the code at the Teams Desktop. Code changes have been now checked in and we are in progress of getting things out gradually after testing them internally. We do understand that this is not really an optimal situation and this issue should have been properly addressed much faster.

I'll keep this issue up to date on the progress as changes are rolling out.

**Comment by juanmlarios** [comment] 2020-01-22 16:37
Thanks @VesaJuvonen ! this is a lifeline as the customer has been waiting for a response for while. I'll keep an eye on the ticket for updates

**Comment by narulasrinivas** [comment] 2020-01-22 19:39
Thanks @VesaJuvonen. Even our customer was waiting for longtime this to be fixed. Hope to see this issue resolved in a couple of weeks.

**Comment by juanmlarios** [comment] 2020-02-13 16:21
Hi @VesaJuvonen  this is still an issue for my customer. Let me know if you need any other info to check into this further.

**Comment by lahuey** [comment] 2020-03-25 20:20
Update:

We found a blocking issue while rolling out the fix. We need to address this issue before moving forward with the rollout. I will return back with an update shortly.

Thank you for you patience.

**Comment by juanmlarios** [comment] 2020-03-26 02:25
Thanks for the update @lahuey , I can't believe it's been almost 5 months since the original issue. I am trying to understand how anyone is having success with the Graph API and Teams/SPFX solutions. Is this tenant-specific? is it only a few partners/customers experiencing this issue? would be nice to understand what the issue is exactly. I know my customer would appreciate an explanation. Any info you can share would be great. Thanks!

**Comment by MistahG** [comment] 2020-04-23 10:59
Is this issue already fixed or is there any update on it?
Currently showing a SharePoint page with an spfx webpart on it on a teams website tab.
The spfx webpart calls the Graph API to get the groups where the currently logged in user is a member of.
This works well for internal users, but not for external users. This is really a blocking issue as we are working with them on a day to day base in Teams.
External users have to use 2 factor authentication by company policy.
If I debug the page in Teams as an external user I also get this message "Cannot read property 'match' of undefined" when calling the Graph API.

**Comment by VesaJuvonen** [comment] 2020-04-23 17:50
@juanmlarios  - this should be absolutely addressed from the SPFx perspective, but it also depends on which API you call, as an example - in the case of @MistahG's question, issue is really on the Graph API side which apparently does not support this call for external users.

We cannot provide support for Graph APIs directly using this channel as their support model is through StackOverflow - and yes - we know that it's really hard for partners and customers to use multiple different location, but for Graph API questions - or issues in Graph API - correct location for questions is at https://stackoverflow.com/questions/tagged/microsoft-graph

If all Graph API calls are blocked in SharePoint Framework, then issue is absolutely on SharePoint Framework side and we'll need to have a look on this. @lahuey  can comment on the exact roll out situation on the issue he has found.

**Comment by juanmlarios** [comment] 2020-04-24 00:27
@VesaJuvonen than you for the work and update on this. I totally understand about the GraphAPI restrictions. I'll test and provide feedback but If there are issues with Graph I'll open up a ticket on the alternate thread. I am not calling Graph graph for external users so I suspect I should be just fine. Thanks again!

**Comment by MistahG** [comment] 2020-04-24 09:44
@VesaJuvonen Thanks for this quick follow up!
I forgot to mention that the page with the SPFx webpart on it that calls the Graph API is working fine if external users open it in SharePoint itself.
If the same page is displayed in Teams, external users get the error message that I mentioned earlier.
With this new information, should I still post this issue on StackOverflow?

**Comment by wobba** [comment] 2020-04-24 11:03
@MistahG are you using cdn on the tenant, in case on/off has an impact here.

**Comment by narulasrinivas** [comment] 2020-04-24 13:38
@MistahG - After struggling for couple of weeks, below steps worked for me.

Manual Steps
Step 1. Go to -> https://aad.portal.azure.com/#blade/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade/RegisteredAppsPreview
Step 2. Click on SharePoint Online Client Extensibility Web Application Principal
Step 3. Click Manifest on the left menu
Step 4. Remove all entries in the PasswordCredentials section (Should leave a empty array)
Step 5. Save the manifest
Step 6. Visit the new API Permission Management Page on the Tenant Admin Site. This creates a client secret behind the scenes.
Step 7. Waited for 1 day.

**Comment by rapowell9** [comment] 2020-05-21 17:32
Is there any update on when this issue will be fixed? I'm experiencing the issue specifically in the desktop app - my tab loads fine for all users on the teams web client, but in the desktop app it only works for the MOD administrator in our demo tenant.

**Comment by lahuey** [comment] 2020-05-21 21:44
The error is an artifact of an exception caused by parsing the error message. The fix has been submitted so it should roll out to customers within the next month.

@rapowell9 can you verify that the preauthorization section of the SPO Client Extensibility Application in the App Registrations (AAd Portal) page is not empty?

**Comment by rapowell9** [comment] 2020-05-22 15:26
@lahuey 

Yes, I populated that section as described in the previous thread, with the given app id and the permissionsId from the OAuth2Permissions array. Thanks for the update, and glad to hear the fix is nearly out

**Comment by maddya** [comment] 2021-04-27 22:41
Was this issue resolved?

**Comment by narulasrinivas** [comment] 2021-04-28 07:31
@maddya  - I followed below steps and issue was resolved.

Manual Steps
Step 1. Go to -> https://aad.portal.azure.com/#blade/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade/RegisteredAppsPreview
Step 2. Click on SharePoint Online Client Extensibility Web Application Principal
Step 3. Click Manifest on the left menu
Step 4. Remove all entries in the PasswordCredentials section (Should leave a empty array)
Step 5. Save the manifest
Step 6. Visit the new API Permission Management Page on the Tenant Admin Site. This creates a client secret behind the scenes.
Step 7. Waited for 1 day.

**Comment by juanmlarios** [comment] 2021-04-29 16:16
> Was this issue resolved?

@maddya  the above steps never worked for me, which is why I think this issue is still open. I gave up on this approach and totally dropped the SPFX model and went straight into Personal Teams APPs that hit the GraphAPI directly and I didn't have to go through SPFX. I assume this is a very complicated problem and a lot of moving pieces but it seems like there is no clear owner of this issue, as the SPFx team says it's fixed, and it's a graph issue, then the Graph team doesn't see an issue so it's tough to get to the bottom of it. I simply couldn't wait anymore as I had business-critical items I had to deliver.

**Comment by magarma** [comment] 2022-02-09 10:32
We are having a very similar issue in a client.
We have two SPFx webparts as tabs in a Channel that make requests to Graph and Custom APIs that are not working in Teams Desktop app but they work perfectly in the web client. Any idea o workaround?

**Comment by srinivasnarula** [comment] 2022-02-09 10:49
Hi @magarma - We had similar issue for our application last week. There is an update in `manifest.json`.

I shared mine here for your reference. Main change happened at static domain name are replaced with `teamSiteDomain` and worked like a charm.

**Earlier :**  `"contentUrl": "https://srinivasnarula.sharepoint.com/_layouts/15/teamslogon.aspx?SPFX=true&dest=/sites/Playground/Test.aspx"`

**Now :**  ` "contentUrl": "https://{teamSiteDomain}/_layouts/15/teamslogon.aspx?SPFX=true&dest=/sites/Playground/Test.aspx"`

here is the entire manifest.json file for your reference.

```
{
    "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.10/MicrosoftTeams.schema.json",
    "manifestVersion": "1.11",
    "packageName": "GraphPersonaWebPart",
    "id": "3bbf7d18-69fa-4ecf-ad34-a0f15d5db19c",
    "version": "0.1",
    "developer": {
      "name": "Srinivas Narula",
      "websiteUrl": "https://products.office.com/en-us/sharepoint/collaboration",
      "privacyUrl": "https://privacy.microsoft.com/en-us/privacystatement",
      "termsOfUseUrl": "https://www.microsoft.com/en-us/servicesagreement"
    },
    "name": {
      "short": "GraphPersona"
    },
    "description": {
      "short": "GraphPersona Description",
      "full": "GraphPersona Description"
    },
    "icons": {
      "outline": "3bbf7d18-69fa-4ecf-ad34-a0f15d5db19c_outline.png",
      "color": "3bbf7d18-69fa-4ecf-ad34-a0f15d5db19c_color.png"
    },
    "accentColor": "#004578",
    "configurableTabs": [
      {
        "configurationUrl": "https://{teamSiteDomain}{teamSitePath}/_layouts/15/TeamsLogon.aspx?SPFX=true&dest={teamSitePath}/_layouts/15/teamshostedapp.aspx%3FopenPropertyPane=true%26teams%26componentId=3bbf7d18-69fa-4ecf-ad34-a0f15d5db19c%26forceLocale={locale}",
        "canUpdateConfiguration": true,
        "scopes": [
          "team"
        ]
      }
    ],
    "staticTabs": [
      {
          "entityId": "Test",
          "name": "Test Hub",
          "contentUrl": "https://{teamSiteDomain}/_layouts/15/teamslogon.aspx?SPFX=true&dest=/sites/Playground/Test.aspx",
          "websiteUrl": "https://{teamSiteDomain}/_layouts/15/teamslogon.aspx?SPFX=true&dest=/sites/Playground/Test.aspx",
          "scopes": [
              "personal"
          ]
      }
    ],
    "validDomains": [
      "*.login.microsoftonline.com",
      "*.sharepoint.com",
      "*.sharepoint-df.com",
      "spoppe-a.akamaihd.net",
      "spoprod-a.akamaihd.net",
      "resourceseng.blob.core.windows.net",
      "msft.spoppe.com"
    ],
    "webApplicationInfo": {
      "resource": "https://{teamSiteDomain}",
      "id": "00000003-0000-0ff1-ce00-000000000000"
    }
  }
```

**Comment by magarma** [comment] 2022-02-09 11:00
Unfortunately, we already have the {teamSiteDomain} in the manifests. And it's working fine for others clients, so I think that there is something else.

**Comment by AJIXuMuK** [comment] 2022-02-09 15:29
Hi @magarma,
There are multiple things you can try here depending on what you are actually experiencing.
I will post some links and suggestions for you to check:
- re-run Sync to Teams
- https://github.com/SharePoint/sp-dev-docs/issues/7642#issuecomment-1011406368
- https://github.com/SharePoint/sp-dev-docs/issues/7640#issuecomment-1021519426

**Comment by lucabandMSFT** [comment] 2022-02-09 17:11
Hey @magarma, one other thing to check: did you hit the API Access page as an user that has both SharePoint admin and Global admin roles? If there're some mismatches in the AAD application principal, by simply doing that action it should fix the majority of those.

**Comment by magarma** [comment] 2022-02-17 06:24
Hi, thanks for the suggestion, we will ask the client to try that.

**Closed** 2022-03-03 14:00 UTC
Labels: area:spfx, status:fixed-next-drop, Needs: Author Feedback, no-recent-activity, type:bug-confirmed
