### ISSUE TITLE
FieldCustomizer not always rendering when it's not on the default view

### ISSUE THREAD

**Issue by martinlingstuyl** [SharePoint/sp-dev-docs#6892] opened 2021-04-07 08:07 UTC
## Category

- [ ] Question
- [ ] Typo
- [ ] Additional article idea
- [x] Bug

## Description

Field Customizers are not always rendering. The situation in which this occurs, is if you have two views and you are redirecting to the non-default view from a new tab. Refreshing the browser fixes the issue. 

The Repro-path is as follows:

1. Create a new modern Teamsite.
2. Create a library named 'Test'.
3. Create a new column.
4. Create a basic Field Customizer and connect it to the new column using the ClientSideComponentId.
5. Hide the column on the default AllItems view.
6. Create a new view named Test and add the new column to the view.
7. Create a link in the quick launch and add a link to [siteurl]/Test/Forms/Test.aspx.

Now you're all set to try it out. 

8. Create a new Tab in your browser and navigate to your [siteurl]
9. Now click the link in the Quick Launch.

Result: The Field Customizer does not render. (When opening the Developer Tools, it's clear that the Field Customizer JavaScript file is not loaded)

10. Press F5, the Field Customizer will now render. (The Field Customizer JavaScript file is now loaded)

N.B.: When opening the view in a new tab ([siteurl]/Test/Forms/Test.aspx), the field customizer will work. The point here is that it doesn't work when opening [siteurl] and navigating to [siteurl]/Test/Forms/Test.aspx. 

## Environment details

Target Environment: SharePoint Online
Browser: Chromium Edge 89.0.774.63
Tooling: SPFx Extension 1.11.0

## Workaround
Adding the column to the default view is the workaround for this issue.

**Comment by AJIXuMuK** [comment] 2021-09-08 13:17
Duplicate of #2244

**Closed** 2021-09-08 13:17 UTC
Labels: status:duplicate, area:spfx, status:to-be-reviewed, area:spfx-extensions
