### ISSUE TITLE
Microsoft Teams spfx webpart - error initializing application error cannot read property id of undefined

### ISSUE THREAD

**Issue by v-prabus** [SharePoint/sp-dev-docs#4419] opened 2019-08-05 09:11 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Microsoft teams and microsoft azure(api's are hosted) authorization should happen successfully using ADAL.

#### Observed Behavior

We are deploying spfx webpart to microsoft teams which uses  adal js to authorize between ms teams and ms azure(api's are hosted) we are getting  "error initializing application error cannot read property id of undefined" and correlation id : 0f54f59e-904c-0000-c171-7dbba631ddbc

Thanks for your contribution! Sharing is caring.

**Comment by andrewconnell** [comment] 2019-08-05 13:30
Suspect this is a dupe of a known issue, with a workaround, that MSFT said would be improved in future version: #4006 #3923 

Can you look and confirm if it's the same? If not, need more detail...

**Closed** 2019-08-20 21:00 UTC
Labels: Needs: Author Feedback, area:auth, area:framework-general, no-recent-activity, status:duplicate
