### ISSUE TITLE
Isolated Web Parts not loading in SharePoint App and Safari on iOS

### ISSUE THREAD

**Issue by spcph** [SharePoint/sp-dev-docs#6315] opened 2020-09-24 19:15 UTC
## Category

- [x] Bug

## Describe the bug

Isolated Web Parts do not display in SharePoint App and Safari on iOS devices. They do work in Edge on iOS.

## Steps to reproduce

1. Scaffold an SPFx solution
2. Choose Isolated feature
3. Build and package solution
4 Deploy and install
5. Add WP to page.
6. Load in SP App og Mobile Safari.

## Expected behavior

Isolated Web Parts appear on page, in SP App and Mobile Safari.

## Environment details (*development & target environment*)

- **Your Developer Environment**: MacOS 11
- **Target Environment**: SharePoint Online
- **Framework**:  Node.js v10
- **Browser(s)**: Mobile Safari, SharePoint App iOS
- **Tooling**:  VS Code | SPFx v1.10.0

### Additional context

*Thanks for your contribution! Sharing is caring.*

**Comment by spcph** [comment] 2020-09-25 10:17
After a bit more research it would appear that the issue is related to the authentication flow. From the console I amble to se the following message:

[Error] Refused to display 'https://login.microsoftonline.com/75c15362-22c1-47b3-a767-a570e4a2c81a/oauth2/authorize?client_id=00.............&popupui=1' in a frame because it set 'X-Frame-Options' to 'DENY'.

I'm running in a private tab in Safari on iPhone, and have made sure that only one profile is logged in or active.

**Comment by andrewconnell** [comment] 2020-09-28 15:20
I believe this is a dupe of existing issues (see #4669 #4892 #4915)... please confirm or add additional details on how this differs from the existing issues...

**Comment by spcph** [comment] 2020-09-28 15:51
@andrewconnell I'm not entirely sure if my issue is a dupe of the 3 you mention. Initially I found the problem with a WP that did in fact use Graph but tested with the plain HelloWorld WP that gets created with a new React project. The problem is the same with both WPs. Both get the DENY X-Frame options error message. 

I just tried to add the page as a tab in Teams Desktop and get the same issue. Loading in Teams Web, and it works fine.

Again the problem is obviously with the authentication flow but not necessarily graph or AadClient related. This seems to be an issue of the isolated web part being loaded in an iframe and being on a diferent domain than the hosting page. Nothing else I think.

**Comment by andrewconnell** [comment] 2020-09-28 17:07
From what you've said, I believe this is a dupe of the others I reference. MSFT is aware of the auth issues with SPFx in Teams non-web clients. As such, I'll label this as a dupe to keep things consolidated...

FWIW: they've shared they are in the midst of working through migrating SPFx from using ADAL.JS => MSAL.js v2 and addressing a lot of these.

**Closed** 2020-09-28 17:07 UTC
Labels: area:auth, area:spfx-msteams, status:duplicate
