### ISSUE TITLE
SPFX - Special characters in description like æøå makes webpart disappear in toolbox

### ISSUE THREAD

**Issue by frnk01** [SharePoint/sp-dev-docs#1044] opened 2017-11-13 14:26 UTC
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
SPFX Web parts should handle special characters in description

#### Observed Behavior
Web part missing from toolbox while adding web parts to page due to special character in description

#### Steps to Reproduce
Add special characters to description like æøå

**Comment by chackman** [comment] 2017-12-06 23:18
Could you please provide more information?
Special characters in the default title and description work fine.

Are you localizing the title or description of the web part?
If so, which language(s) are you localizing?  Does the web part display in locales that do not have 'special characters' in the description?

Finally which language is your site in?

**Comment by mcmynn83** [comment] 2017-12-13 19:06
@frnk01 - I'm resolving this as it is not actionable and we cannot reproduce the issue with the information given.  If you are still seeing this issue please answer Chris's questions from above so we can investigate this further.

**Closed by mcmynn83** 2017-12-13 19:06 UTC
