### ISSUE TITLE
Web part Base 64 icons do not render anymore

### ISSUE THREAD

**Issue by lucmoco** [SharePoint/sp-dev-docs#1124] opened 2017-12-08 08:35 UTC
#### Category

- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Web part icons defined in base 64 as described in the SPFx documentation page [Configure web part icon](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/basics/configure-web-part-icon) (section *Using a base64 encoded image*) are displayed properly.

#### Observed Behavior

Web part icons defined in base 64 as defined in the mentioned article are not displayed at all in the web part picker. They used to be displayed (about one month ago or so), and our existing web parts used to have an `data:image` icon properly displayed, but now they are not displayed anymore.

Icons are still displayed properly in the local workbench, but they are not displayed in the SharePoint workbench.

#### Steps to Reproduce

Define a web part manifest in the following way:

```JSON
{
  "...": "...",
  "preconfiguredEntries": [
    {
      "...": "...",
      "iconImageUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACgAA...<rest omitted>"
    }
  ]
}
```

#### Analysis

When inspecting the source of the web part picker, the value of `src` attribute of the `img` tag is:

> `https://<storage>.blob.core.windows.net/<solution>/data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACgAA...<rest omitted>`

It looks like SharePoint prepends `https://<storage>.blob.core.windows.net/<solution>/` to the value of the `iconImageUrl` property. While this behavior can indeed be advantageous for image files, it should not be applied in the case of `data:image` values.

**Comment by arunakshi** [comment] 2017-12-11 09:09
yes, It worked for me 10 days back and it stopped since 4 days. Is it fixed ?

**Comment by yborghmans** [comment] 2017-12-14 07:32
+1
Same issue over here, loading the image by a specific url (localhost,azure, sharepoint..) it works, but by providing the base64 string it doesn't.

**Comment by VesaJuvonen** [comment] 2017-12-14 08:13
We are looking into this to understand where the issue is caused and how fast we can address this. Since it's impacting potentially production deployments, we do understand that the issue should be sorted out relatively fast.

**Comment by spearconsult** [comment] 2018-01-12 12:12
Hi @VesaJuvonen, any updates on this issue? Otherwise we need to make changes to a ready-for-production deployment, but that feels like a workaround ;-)

**Comment by cwdata** [comment] 2018-01-25 13:26
By the way: "gulp bundle" is also complaining that the URL of a base64 coded image looks like a relative path and that we should take care to deploy the image to the right location. Maybe that could be fixed too, although it's only annoying not blocking like the main issue reported here.

**Comment by nero120** [comment] 2018-01-25 15:07
@VesaJuvonen can we get an update on this please? It's been well over a month.

**Comment by manishgarg1** [comment] 2018-01-26 18:27
Hi, thanx for reporting the issue. We have identified the code that is causing the issue and trying to fix it soon.

**Comment by pedropablo** [comment] 2018-02-13 17:22
the warning @cwdata commented breaks CD with VSTS. I think the warning and the main issue are related and maybe the fix helps that too.

**Comment by MrDrSushi** [comment] 2018-02-14 23:34
I'm still experiencing this issue, has this issue been fixed?

**Comment by frnk01** [comment] 2018-02-23 12:58
Any updated on this issue?

**Comment by spplante** [comment] 2018-02-23 19:44
Also having the same issue here

**Comment by VesaJuvonen** [comment] 2018-03-19 13:15
This is now fixed in all tenants, so closing this issue.

**Closed by VesaJuvonen** 2018-03-19 13:15 UTC
Labels: area:framework, status:tracked, type:bug

**Comment by nero120** [comment] 2018-03-19 13:57
Confirmed, it's fixed in both my tenants. Great stuff, thank you @VesaJuvonen!

**Comment by lucmoco** [comment] 2018-03-19 20:11
I confirm it works again. Thanks !

**Comment by IlyeniaMaksim** [comment] 2018-04-23 12:33
I can't package basic solution. Could you help me?
 
`> gulp bundle --ship

Build target: SHIP
[15:28:34] Starting gulp
[15:28:34] Starting 'bundle'...
[15:28:34] Starting subtask 'configure-sp-build-rig'...
[15:28:34] Finished subtask 'configure-sp-build-rig' after 7.65 ms
[15:28:34] Starting subtask 'pre-copy'...
[15:28:34] Finished subtask 'pre-copy' after 35 ms
[15:28:34] Starting subtask 'copy-static-assets'...
[15:28:34] Starting subtask 'sass'...
[15:28:39] Finished subtask 'copy-static-assets' after 5.26 s
[15:28:39] Finished subtask 'sass' after 5.34 s
[15:28:39] Starting subtask 'tslint'...
[15:28:46] Starting subtask 'typescript'...
[15:28:46] [typescript] TypeScript version: 2.4.2
[15:28:54] Finished subtask 'tslint' after 15 s
[15:29:15] Finished subtask 'typescript' after 29 s
[15:29:15] Starting subtask 'ts-npm-lint'...
[15:29:16] Finished subtask 'ts-npm-lint' after 946 ms
[15:29:16] Starting subtask 'api-extractor'...
[15:29:16] Finished subtask 'api-extractor' after 735 μs
[15:29:16] Starting subtask 'post-copy'...
[15:29:16] Finished subtask 'post-copy' after 208 μs
[15:29:16] Starting subtask 'collectLocalizedResources'...
[15:29:16] Finished subtask 'collectLocalizedResources' after 39 ms
[15:29:16] Starting subtask 'configure-webpack'...
[15:29:17] Finished subtask 'configure-webpack' after 938 ms
[15:29:17] Starting subtask 'webpack'...
[15:29:18] Finished subtask 'webpack' after 434 ms
[15:29:18] Starting subtask 'configure-webpack-external-bundling'...
[15:29:18] Finished subtask 'configure-webpack-external-bundling' after 531 μs
[15:29:18] Starting subtask 'copy-assets'...
[15:29:18] Finished subtask 'copy-assets' after 33 ms
[15:29:18] Starting subtask 'write-manifests'...
[15:29:18] Warning - [write-manifests] The icon path "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACgAAAAcCAYAAAATFf3WAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAOxAAADsQBlSsOGwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAHLSURBVFiF1ZdNLwNBGMf/z3a7CQd6ECeHag+uDg6caEMaHEgkvoGEVKTWF+hZvTRpHHwGTk62DkhInJ2qUTbhIN5LQhttH6d6Cboz3VX1u+3MM/P85mVnZwk/4NMN/qnuNzhZCpFUg1oKVsqlWjX2RrY9CuW7PpYpaun0ODaUcULOCktBM96X9etbIwyeBgAwDtUnLViu9+vGDgMtsom1vKs3tdJ/Y1sQIM4s8Yxf3wITD5RchVBqOfTWcZEw6SKRfj6Tury9l23zia/7gskb2fbY6lQ41zsSIyc247A36ioQFvTpm2MMpcGpxNzkXjejgZxVnPgMEgWJudmW1QdcN88bAJwTPFkMhW0ZVYnyF0llqHtB8ZdkzkiB0epUYuWl2HGcGLqyihMWLBW17gLlHZvx88TgnUicsKAZD9T8DAT+wR6se8GKS1zrS6sU9XJhrfslFhJs15NhgOX+GRxCSFABh/16chXRaM1nXPgcZGCi/aEnfQosAIBv1jgAoa3qxKR1phcD144JAtjX1Nxq+aGkFkZVIumrfpl04+6tSJxogj23mps7mh95LBeYseGLqswkERLMnGWnsDZe/G2Z7xDb9H8kB/yDL8krBkWM519tYT8AAAAASUVORK5CYII=" appears to be a relative web URL. This means that when the is rendered, this URL will be relative to the CDN url for the rest of the package assets. If a relative filesystem path was intended, prepend the path with "./".
[15:29:18] Warning - [write-manifests] The icon path "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACgAAAAcCAYAAAATFf3WAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAOxAAADsQBlSsOGwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAHLSURBVFiF1ZdNLwNBGMf/z3a7CQd6ECeHag+uDg6caEMaHEgkvoGEVKTWF+hZvTRpHHwGTk62DkhInJ2qUTbhIN5LQhttH6d6Cboz3VX1u+3MM/P85mVnZwk/4NMN/qnuNzhZCpFUg1oKVsqlWjX2RrY9CuW7PpYpaun0ODaUcULOCktBM96X9etbIwyeBgAwDtUnLViu9+vGDgMtsom1vKs3tdJ/Y1sQIM4s8Yxf3wITD5RchVBqOfTWcZEw6SKRfj6Tury9l23zia/7gskb2fbY6lQ41zsSIyc247A36ioQFvTpm2MMpcGpxNzkXjejgZxVnPgMEgWJudmW1QdcN88bAJwTPFkMhW0ZVYnyF0llqHtB8ZdkzkiB0epUYuWl2HGcGLqyihMWLBW17gLlHZvx88TgnUicsKAZD9T8DAT+wR6se8GKS1zrS6sU9XJhrfslFhJs15NhgOX+GRxCSFABh/16chXRaM1nXPgcZGCi/aEnfQosAIBv1jgAoa3qxKR1phcD144JAtjX1Nxq+aGkFkZVIumrfpl04+6tSJxogj23mps7mh95LBeYseGLqswkERLMnGWnsDZe/G2Z7xDb9H8kB/yDL8krBkWM519tYT8AAAAASUVORK5CYII=" appears to be a relative web URL. This means that when the is rendered, this URL will be relative to the CDN url for the rest of the package assets. If a relative filesystem path was intended, prepend the path with "./".
[15:29:19] Finished subtask 'write-manifests' after 892 ms
[15:29:19] Finished 'bundle' after 45 s
[15:29:19] ==================[ Finished ]==================
Warning - [write-manifests] The icon path "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACgAAAAcCAYAAAATFf3WAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAOxAAADsQBlSsOGwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAHLSURBVFiF1ZdNLwNBGMf/z3a7CQd6ECeHag+uDg6caEMaHEgkvoGEVKTWF+hZvTRpHHwGTk62DkhInJ2qUTbhIN5LQhttH6d6Cboz3VX1u+3MM/P85mVnZwk/4NMN/qnuNzhZCpFUg1oKVsqlWjX2RrY9CuW7PpYpaun0ODaUcULOCktBM96X9etbIwyeBgAwDtUnLViu9+vGDgMtsom1vKs3tdJ/Y1sQIM4s8Yxf3wITD5RchVBqOfTWcZEw6SKRfj6Tury9l23zia/7gskb2fbY6lQ41zsSIyc247A36ioQFvTpm2MMpcGpxNzkXjejgZxVnPgMEgWJudmW1QdcN88bAJwTPFkMhW0ZVYnyF0llqHtB8ZdkzkiB0epUYuWl2HGcGLqyihMWLBW17gLlHZvx88TgnUicsKAZD9T8DAT+wR6se8GKS1zrS6sU9XJhrfslFhJs15NhgOX+GRxCSFABh/16chXRaM1nXPgcZGCi/aEnfQosAIBv1jgAoa3qxKR1phcD144JAtjX1Nxq+aGkFkZVIumrfpl04+6tSJxogj23mps7mh95LBeYseGLqswkERLMnGWnsDZe/G2Z7xDb9H8kB/yDL8krBkWM519tYT8AAAAASUVORK5CYII=" appears to be a relative web URL. This means that when the is rendered, this URL will be relative to the CDN url for the rest of the package assets. If a relative filesystem path was intended, prepend the path with "./".
Warning - [write-manifests] The icon path "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACgAAAAcCAYAAAATFf3WAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAOxAAADsQBlSsOGwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAHLSURBVFiF1ZdNLwNBGMf/z3a7CQd6ECeHag+uDg6caEMaHEgkvoGEVKTWF+hZvTRpHHwGTk62DkhInJ2qUTbhIN5LQhttH6d6Cboz3VX1u+3MM/P85mVnZwk/4NMN/qnuNzhZCpFUg1oKVsqlWjX2RrY9CuW7PpYpaun0ODaUcULOCktBM96X9etbIwyeBgAwDtUnLViu9+vGDgMtsom1vKs3tdJ/Y1sQIM4s8Yxf3wITD5RchVBqOfTWcZEw6SKRfj6Tury9l23zia/7gskb2fbY6lQ41zsSIyc247A36ioQFvTpm2MMpcGpxNzkXjejgZxVnPgMEgWJudmW1QdcN88bAJwTPFkMhW0ZVYnyF0llqHtB8ZdkzkiB0epUYuWl2HGcGLqyihMWLBW17gLlHZvx88TgnUicsKAZD9T8DAT+wR6se8GKS1zrS6sU9XJhrfslFhJs15NhgOX+GRxCSFABh/16chXRaM1nXPgcZGCi/aEnfQosAIBv1jgAoa3qxKR1phcD144JAtjX1Nxq+aGkFkZVIumrfpl04+6tSJxogj23mps7mh95LBeYseGLqswkERLMnGWnsDZe/G2Z7xDb9H8kB/yDL8krBkWM519tYT8AAAAASUVORK5CYII=" appears to be a relative web URL. This means that when the is rendered, this URL will be relative to the CDN url for the rest of the package assets. If a relative filesystem path was intended, prepend the path with "./".
[15:29:20] Project test-project version: 0.0.4
[15:29:20] Build tools version: 3.2.7
[15:29:20] Node version: v8.9.4
[15:29:20] Total duration: 51 s
[15:29:20] Task warnings: 2
npm ERR! code ELIFECYCLE
npm ERR! errno 1`

**Comment by VesaJuvonen** [comment] 2018-04-23 14:39
hi @IlyeniaMaksim - as this issue is already closed, would suggest to submit a new issue and to provide details on the exact versions what has been used or what you have installed in your environment. Otherwise, your issue can be easily hidden.
