### ISSUE TITLE
ListViewCommandSet (spfx) does not work with ListView webpart on modern page

### ISSUE THREAD

**Issue by magnusdanielson** [SharePoint/sp-dev-docs#2737] opened 2018-10-10 12:02 UTC
#### Category
- [x ] Bug

#### Expected or Desired Behavior
I excpect an extension of type ListViewCommandSet to display my commands on a modern page with the ListView(preview) webpart added.

#### Observed Behavior
The ListView(preview) webpart displays the CustomAction Title in the commandbar and the button is not actionable.

#### Steps to Reproduce
Create a new project with yo
Add a custom extension
Run the gulp commands for bundle and package-solution
gulp bundle --ship
gulp package-solution --ship

Deploy the package to appcatalog and approve the app.
Add the app to any modern site.
Add a list to the start page of the modern site.
Now the command bar appears with a new command with the title of the CustomAction from the elements.xml file

elements.xml file:
`<?xml version="1.0" encoding="utf-8"?>
<Elements xmlns="http://schemas.microsoft.com/sharepoint/">
    <CustomAction
        Title="HelloWorld"
        RegistrationId="100"
        RegistrationType="List"
        Location="ClientSideExtension.ListViewCommandSet.CommandBar"
        ClientSideComponentId="5e4d1a86-8ced-4c69-ae64-9a8651db946e"
        ClientSideComponentProperties="{&quot;sampleTextOne&quot;:&quot;One item is selected in the list.&quot;, &quot;sampleTextTwo&quot;:&quot;This command is always visible.&quot;}">
    </CustomAction>
</Elements>`

Image of startpage with ListView webpart:
![image](https://user-images.githubusercontent.com/12081481/46734843-b3e2a000-cc94-11e8-9b42-3f719b01d98e.png)

Note that the Commandbar works as excpected if you navigate to the list.
Image of list:
![image](https://user-images.githubusercontent.com/12081481/46734772-84cc2e80-cc94-11e8-90e7-aa90e7e6bbe0.png)

Yes, sharing is caring.

**Comment by genteelish** [comment] 2018-10-17 19:20
I concur that this is a bug where the ECB custom action for lists/libraries works in the list/library view, but not in the list/library (preview) webpart. It appears that the custom action title value from the spfx solution sharepoint/assets/elements.xml shows in the webpart, but the command title value frm the src/extensions/{solution}/{solution}.manifest.json is being displayed in the list/library view. Solution code is not being fetched in aspx pages that contain the list/library view webpart outside of a list/library view page. Seems that this customization ability is half baked.

**Comment by Renevdo** [comment] 2018-11-05 13:04
I can confirm this is not working. What is the planning of resolving this? So we can communicate about it. Thanks!

**Comment by JLRishe** [comment] 2018-12-18 10:43
@VesaJuvonen Has #2105 also been routed to the right people? It seems like a similar matter but hasn't had any updates since June.

**Comment by spplante** [comment] 2019-01-14 17:55
I have the exact same issue on my side, the icon is missing from the button, the label isn't the correct title specified in the manifest and the code associated with the button isn't working.

**Comment by magnusdanielson** [comment] 2019-02-23 22:40
This seams to be solved now, at least in our tenant. Feel free to close.

**Comment by maximreynaud** [comment] 2019-03-01 14:44
Hello,

My CommandSet "Command Bar" show only the Title from the elements.xml since 1 week :/

elements.xml : 

`<?xml version="1.0" encoding="utf-8"?>
<Elements xmlns="http://schemas.microsoft.com/sharepoint/">
    <CustomAction
        Title="UserInfo"
        Location="ClientSideExtension.ApplicationCustomizer"
        ClientSideComponentId="b74aa2eb-c7e5-43d0-97e9-0bba2116b3ed"
        ClientSideComponentProperties="{&quot;testMessage&quot;:&quot;Test message&quot;}">
    </CustomAction>
		<CustomAction
        Title="revPrice"
        RegistrationId="101"
        RegistrationType="List"
        Location="ClientSideExtension.ListViewCommandSet.CommandBar"
        ClientSideComponentId="e8b3de2f-3db7-4556-bdfa-56e2ce3c61c3"
        ClientSideComponentProperties="{&quot;sampleTextOne&quot;:&quot;One item is selected in the list.&quot;, &quot;sampleTextTwo&quot;:&quot;This command is always visible.&quot;}">
    </CustomAction>
</Elements>`

![image](https://user-images.githubusercontent.com/40465301/53645293-d885e700-3c38-11e9-91e5-20ef37e0936d.png)

Do you know if I'm missing something ?

**Comment by babaibhat** [comment] 2019-05-16 13:32
Not working in our corporate tenant. Only works on actual list view page, not on any site page

**Comment by magnusdanielson** [comment] 2020-05-29 12:25
Now the button is completly missing from a modern page with the ListView webpart. When the user opens the library the button works properly. We have this issue on several tenants. Note also that the PowerApps button is missing on the home page but displays in the library.

Image with missing button from modern home page.
![image](https://user-images.githubusercontent.com/12081481/83259168-d867f480-a1b7-11ea-97b4-36aae0e72585.png)

Image with working button in library.
![image](https://user-images.githubusercontent.com/12081481/83259347-2c72d900-a1b8-11ea-8cc3-f8bfab292013.png)

**Comment by TazzyMan** [comment] 2020-06-03 19:26
Same here. Our button suddenly disappeared . Our extension logs to the console in the onInit(), and we don't see that log message either. Seems like the extension isn't loaded or at least not activated.

**Comment by AJIXuMuK** [comment] 2021-09-21 16:15
@magnusdanielson @TazzyMan - could you please check if the issue is still there?
Seems like issue with title was a regression bug that is currently fixed.

Please, let me know if you still can repro it on your tenants.

Thanks!

**Closed** 2021-10-05 18:00 UTC
Labels: status:tracked, area:other, Needs: Author Feedback, no-recent-activity, type:bug-confirmed
