### ISSUE TITLE
The provided grant has expired due to it being revoked, a fresh auth token is needed. SPFX graph mobile app

### ISSUE THREAD

**Issue by harshdamaniahd** [SharePoint/sp-dev-docs#7824] opened 2022-03-23 07:10 UTC
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [X] mobile (iOS/iPadOS)
- [X] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Describe the bug / error

Any SPFX Webpart deployed to teams , having graph connections is throwing this error in my tenant

The provided grant has expired due to it being revoked, a fresh auth token is needed. The user might have changed or reset their password. The grant was issued on '{authTime}' and the TokensValidFrom date (before which tokens are not valid) for this user is '{validDate}'.
Additional Details	
Expected part of the token lifecycle - either an admin or a user revoked the tokens for this user, causing subsequent token refreshes to fail and require re-authentication. Have the user sign-in again.

![image](https://user-images.githubusercontent.com/11780473/159658035-010d2836-c3c5-4996-8212-915e515ee8bd.png)
manifest file

### Steps to reproduce

SPFX webpart calling graph api

### Expected behavior

Should refresh the token

**Comment by harshdamaniahd** [comment] 2022-03-23 09:09
Looks like related to this : https://github.com/SharePoint/sp-dev-docs/issues/7646

**Comment by harshdamaniahd** [comment] 2022-03-23 09:12
Plus for another user, i got this message "Token request previously failed"

**Comment by AJIXuMuK** [comment] 2022-03-30 22:56
@harshdamaniahd - can you try the latest thing proposed by @GrahamMcMynn in the issue you've mentioned: https://github.com/SharePoint/sp-dev-docs/issues/7646#issuecomment-1083361447

**Comment by harshdamaniahd** [comment] 2022-04-06 17:55
> @harshdamaniahd - can you try the latest thing proposed by @GrahamMcMynn in the issue you've mentioned: https://github.com/SharePoint/sp-dev-docs/issues/7646#issuecomment-1083361447

@AJIXuMuK Hi sorry i missed your notification. but it works when we sign in to SharePoint from browser. then open teams mobile client. i raised service request to  Microsoft and they have acknowledged this as product bug. i am very afraid to delete the application, until there is some documentation from Microsoft.

**Comment by GrahamMcMynn** [comment] 2022-04-14 16:21
@harshdamaniahd - Deleting the service principal will not help you.  What you are seeing is unfortunately expected behavior right now.  When you are using the mobile client are authentication is based on having previously logged into SharePoint.  This is being fixed and the fix is currently being rolled out to production.  Once it rolls to production your issue will be fixed in the mobile client.

**Comment by harshdamaniahd** [comment] 2022-04-17 16:26
do we have timelines?

**Comment by harshdamaniahd** [comment] 2022-06-02 06:08
Any update?

**Comment by GrahamMcMynn** [comment] 2022-06-02 16:16
Hi @harshdamaniahd - the fixes have been made however, they are still rolling out to production.  Our current estimated delivery is the end of June.

**Comment by AJIXuMuK** [comment] 2022-06-28 21:55
still rolling out

**Comment by bolte04** [comment] 2022-07-06 13:10
We are eagerly waiting for the fix to finish rolling out. Any updates about the full rollout?

**Comment by netti01** [comment] 2022-07-19 11:36
Are there any updates on this issue. This is very urgent because a large number of our customers are still not able to use our applications inside Teams.

**Comment by bolte04** [comment] 2022-07-20 07:31
We are seeing the exact same issue on the teams desktop client as well - will the update also fix the issue on the desktop client?

**Comment by GrahamMcMynn** [comment] 2022-07-20 16:19
@bolte04 - please open up a different issue as it is very unlikely to be the same issue if it is affecting desktop.

**Comment by harshdamaniahd** [comment] 2022-07-22 13:04
> This has just rolled out to prod in IOS on version 4.11.0 and above. Are you still seeing the issue?

a quick update
![image](https://user-images.githubusercontent.com/11780473/180445043-32d2c391-6b72-484e-a76e-74b9d987206a.png)

**Closed** 2022-08-23 13:24 UTC
Labels: type:bug-suspected, area:spfx, status:fixed-next-drop, Needs: Attention :wave:
