### ISSUE TITLE
SPFx Web Part in Teams not working/events not firing?

### ISSUE THREAD

**Issue by poneilcsgp** [SharePoint/sp-dev-docs#8006] opened 2022-06-01 15:18 UTC
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [X] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [X] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
-- works in SharePoint on Edge Version 101.0.1210.53 (Official build) (64-bit)
-- works in SharePoint on Chrome Version 102.0.5005.63 (Official Build) (64-bit)
-- works in SharePoint on Safari 15.1 (17612.2.9.1.20)
-- DOES NOT WORK in Teams (web version) on Edge, Chrome, or Safari (same ver as above) on initial load
-- DOES NOT WORK in Teams Desktop Client on Mac on initial load
-- DOES NOT WORK in Teams Desktop Client on PC on initial load

- SPFx version: 1.13.1

- Node.js version
--14.9.2

### Describe the bug / error

I've developed a webpart that is deployed to my Home Site's home page.   The webpart works without issue when the page is loaded directly from SharePoint in all browsers tested (see browser info above).   

The webpart provides an autosuggest textbox that queries graph for users that match the characters typed and shows the returned users as suggestions.  It uses the React-Autosuggest as part of the solution.     The react-autosuggest component is within a sub-component of my webpart because I re-use it as part of a "basic" webpart and an "advanced" webpart.    

The issue that I'm seeing is that when I open Teams and load the page with the webpart on it (by opening the Teams Viva Connection app we've configured to show our intranet) and then begin typing I can see that the graph api is called and returns the proper results, but the suggestions do not load.   I can observe that the <ul> that the react-autosuggest doesn't appear.   Further, I've inserted a bunch of console.log statements and it appears that my subcomponent (that contains react-autosuggest) never has it's constructor called.   This issue does not happen when the page is loaded directly from SharePoint.

Finally, If I use the search button in my component, which passes info to a search results page via query string as part of a window.location.href change, then the component starts to work as expected.   

My observation is that it's the way that Teams loads viva connections that's making my part work differently, but when I do the page redirect (via window.location.href change) it loads the page differently.     

I'm trying to dig in more because I still have the following unknowns:

- Do my console.logs go to a different console when using DevTools/Teams/Viva Connection (e.g. maybe my constructor is actually executing but I just don't see the log messages)?
- Am I suppposed to build/deploy my webpart differently for Viva Connections?
- Is it possible to use the hosted Workbench when testing Viva Connections?

### Steps to reproduce

1.  Load my webpart onto a page (I can share the WP code/package if it's helpful).  There's nothing proprietary in it and works in my devTenant without any special reconfiguration.
2.  Test in SharePoint site, works.
3.  Set up Viva Connections app to point to Home Site and ensure my webpart is on the home page.
4. Confirm that Suggestions don't appear, console logs don't appear.

### Expected behavior

I would expect that my webpart that works in SharePoint also works in Teams.   I understand that there may be some additional configuration needed to deploy a part that works in Viva Connections, just not sure what that is.

**Comment by AJIXuMuK** [comment] 2022-06-01 15:28
@poneilcsgp - thanks for the updated issue/description.
Could you please share your code with us so we could look into it?
Thanks!

**Comment by poneilcsgp** [comment] 2022-06-01 16:18
[Cynergy Employee Search.zip](https://github.com/SharePoint/sp-dev-docs/files/8815962/Cynergy.Employee.Search.zip)
Attached.  Thanks for your help!

**Comment by poneilcsgp** [comment] 2022-06-01 16:32
[Employee.Search.zip](https://github.com/SharePoint/sp-dev-docs/files/8816062/Employee.Search.zip)
attached, thanks for your help!

**Comment by poneilcsgp** [comment] 2022-06-02 23:25
Continuing to work through this by testing on Teams web client.  I'm struggling to get the workbench to load the right code consistently   Seems like it's holding on to a cached version.   Any suggestions on how we can load the workbench in Teams or clear the web cache so it doesn't load old code?  I've tried clearing local storage,  browser data,  etc.  But it doesn't work consistently.

**Comment by AJIXuMuK** [comment] 2022-06-07 19:11
@poneilcsgp - I would recommend disabling cache in network tab and also "Bypass for network" for the Service workers in the application:
![image](https://user-images.githubusercontent.com/17036219/172462599-e40e5f31-2828-497f-81bf-d887468ae2a1.png)

From other hand, I see the app is loading: I can see the search box.
So it seems the problem is with the auto suggest component you're using inside your app, not SPFx itself.
If you use [PeoplePicker](https://developer.microsoft.com/en-us/fluentui#/controls/web/peoplepicker) instead of your auto-suggest - will that work?

**Comment by AJIXuMuK** [comment] 2022-06-28 20:45
Closing as it doesn't seem to be an SPFx error.

**Closed by AJIXuMuK** 2022-06-28 20:45 UTC
Labels: type:bug-suspected, area:spfx, Needs: Attention :wave:
