### ISSUE TITLE
Library type solutions do not work

### ISSUE THREAD

**Issue by evlo** [SharePoint/sp-dev-docs#6702] opened 2021-02-12 15:43 UTC
## Category

- [x] Bug

## Describe the bug

@microsoft/generator-sharepoint 1.11.0

Crating even tempty library solution produces error when trying to add app to the site, tried on 3 different tenants,
on 3 of them tried to deploy to site app catalog, on two tenants tried to deploy to tenant app catalog also, always produces error
`The value 'Library' is invalid according to its datatype 'http://schemas.microsoft.com/sharepoint/:ClientComponentType'`
when adding app to the site

We also tried creating library solutions on two different dev environments, second one being on mac os, results in the same issue.

## Steps to reproduce

1. Create library solution using `yo` while having **@microsoft/generator-sharepoint** version **1.11.0** installed
2. upload to tenant or site app catalog - in case of tenant deploy the solution
3. add app to the site

## Expected behavior

Library solutions to work, or at least clear description of all requirements to make them work, if it should be currently supported.

## Environment details (*development & target environment*)

- **Your Developer Environment**: [ Windows 10]
- **Target Environment**: [SharePoint Online]
- **Framework**: [ Node.js v10]
- **Browser(s)**: [Chrome v88 ]
- **Tooling**: [VS Code]
- **Additional info**:  @microsoft/generator-sharepoint version 1.11.0

### Additional context

Trying to create pnp search webpart extension in the end.

https://github.com/SharePoint/sp-dev-docs/issues/829 https://github.com/SharePoint/sp-dev-docs/issues/5706

**Update:**
when using

_? Do you want to allow the tenant admin the choice of being able to deploy the solution to all sites immediately without
 running any feature deployment or adding apps in sites? **Yes**<<<<<<<<<<<<<<<<<<<<<<
? Will the components in the solution require permissions to access web APIs that are unique and not shared with other c
omponents in the tenant? **No**_

during creation and then uploading either to app catalog on tenant or site I get no errors, but also no app is shown when I try to add it to the site.
Is this expected behaviour and required settings to create working library using @microsoft/generator-sharepoint?

using

_? Do you want to allow the tenant admin the choice of being able to deploy the solution to all sites immediately without
 running any feature deployment or adding apps in sites? **No** <<<<<<<<<<<<<<<<<<<
? Will the components in the solution require permissions to access web APIs that are unique and not shared with other c
omponents in the tenant? **No**_

results in the described behaviour

**Comment by AJIXuMuK** [comment] 2021-12-15 16:45
dupe of #6496

**Closed** 2021-12-15 16:46 UTC
Labels: status:duplicate, area:spfx, status:to-be-reviewed
