### ISSUE TITLE
MSGraphClient - Redirecting to wrong location

### ISSUE THREAD

**Issue by mikedev8888** [SharePoint/sp-dev-docs#3524] opened 2019-03-01 12:56 UTC
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
When  prompted to authenticate to the Graph API from tenant.sharepoint.com/sites/xxxxx, after successful authentication users should be redirected back to **tenant.sharepoint.com/sites/xxxxx**.

#### Observed Behavior
When prompted to authenticate to the Graph API from tenant.sharepoint.com/sites/xxxxx, after successful authentication users are redirected to **tenant.sharepoint.com/** (i.e. not the original site collection).

#### Steps to Reproduce
1. Login to an SPO site that is under the /sites managed path (e.g. tenant.sharepoint.com/sites/xxxxx) with:
- An SPFX v1.7 solution deployed with a web part making a call to the Graph API using an MSGraphClient instance provided by MSGraphClientFactory
2. The home page of the site should load successfully - i.e. authentication to the Graph API will have occurred transparently and successfully
3. Wait a while - for the MS Graph session to have expired, though the SPO session to still be active
4. Refresh the page - you'll be prompted for authentication to the Graph API... click OK at the popup and then authenticate
5. Upon successful redirection you'll now be at a different site - https://tenant.sharepoint.com/ instead of https://tenant.sharepoint.com/sites/xxxxx

**Comment by andrewconnell** [comment] 2019-05-28 13:51
@mikedev8888 said:
> Wait a while - for the MS Graph session to have expired, though the SPO session to still be active

What is "a while"? Access tokens _(what's used to auth to the Graph)_ are only valid for a specific amount of time and you'll need to request a new one if you are sitting on the page for a long time.

The access token is retrieved from SPO by SPFx's `MSGraphClientFactory.getClient()` method.

This doesn't impact SPO as it isn't using access tokens when you're in the web experience; all auth is cookie based.

If you try to access the MSFT Graph with an invalid (ie: expired) access token, it will prompt you to re-authenticate. A more reliable pattern in your code would be to repeat the process of retrieving the MSGraphClient if the access token has expired to avoid the auth redirect. The auth redirect isn't going to work anyway if you landed at the right site because it will simply re-auth you, but won't re-set the auth token in the `MSGraphClient` that you received from the SPFx API call mentioned above.

At this point seems like it's all by design... unless you have additional details you can provide.

**Closed** 2019-05-31 14:00 UTC
Labels: area:framework, status:answered, status:by-design, type:question
