### ISSUE TITLE
AadHttpClient - Error: Window closed without authenticating

### ISSUE THREAD

**Issue by sortegamartin** [SharePoint/sp-dev-docs#1465] opened 2018-03-14 17:26 UTC
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Version
SharePoint Framework 1.4.1

#### Expected or Desired Behavior
When I add multiple webparts and extensions on the same page and each webpart and extension creates an instance of the AadHttpClient object and then invoke the methods get or post, the following error occurs: "Error: Window closed without authenticating".

![image](https://user-images.githubusercontent.com/33054287/37419453-ce87b4ca-27b4-11e8-9c86-5235365ee4a6.png)

This situation only occurs the first time, when you do not have the token yet, the second time you access the page, as the token is saved in the session storage, the error does not occur.

Do you know if there is any way to control this error or if it is a bug?

Thanks!

**Comment by waldekmastykarz** [comment] 2018-03-15 08:39
Do all these web parts and extensions try to get access token for the same resource (API) or different ones?

**Comment by sortegamartin** [comment] 2018-03-15 11:46
For the same resource (API)

**Comment by waldekmastykarz** [comment] 2018-03-15 12:53
I suspect the issue to be with ADAL which might not be made for this scenario, but it would be good to verify/debug.

**Comment by xdelgado** [comment] 2018-03-15 13:32
I have the same problem. This will cause that the solution won't be workable in case that you add several client webparts in the same page with AadHttpClient.

**Comment by mpasarin** [comment] 2018-03-19 21:30
Thanks for your feedback @sortegamartin 
We are currently investigating the issue and we'll get back to you with updates once it's fixed.

**Comment by calin1611** [comment] 2018-03-23 10:59
I encountered the same issue while having an instance of `AadHttpClient` and an instance of `AadTokenProvider`. Therefore I suspect the issue is at least at the level of `AadTokenProvider` and not `AadHttpClient`, if not lower.

**Comment by dgaeta** [comment] 2018-03-29 21:38
@sortegamartin Thanks for bringing this issue to light. We have checked in the fix where there will no longer be popups for the authentication to avoid this issue. The fix will be rolling out sometime next week. 

Please feel free to reopen this if the problem persists after next week.

**Closed by dgaeta** 2018-03-29 21:38 UTC
Labels: status:tracked, type:bug

**Comment by Nasicus** [comment] 2018-04-09 13:34
@dgaeta  any news on this? Will this result in a new SPFx version?
And will this by any chance, solve the issue, that it doesn't work in IE and edge?
See: https://github.com/SharePoint/sp-dev-docs/issues/1556#issuecomment-379740104

**Comment by Tiliavir** [comment] 2018-04-17 06:30
@dgaeta "Please feel free to reopen this if the problem persists after next week." - so I guess this should be brought back to live? Can neither see it working nor any attempt of a solution so far ...
