### ISSUE TITLE
IDigestCache, DigestCache in SPFx 1.5

### ISSUE THREAD

**Issue by aslanovsergey** [SharePoint/sp-dev-docs#2027] opened 2018-06-13 10:36 UTC
I can't find IDigestCache, DigestCache in '@microsoft/sp-http' in SPFx 1.5

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65fb0645-712c-1b50-238b-7ef99109c1d9
* Version Independent ID: 8ba9ca9e-d68f-4ca0-2e99-a9a86d294faa
* Content: [Work with __REQUESTDIGEST](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/basics/working-with-requestdigest)
* Content Source: [docs/spfx/web-parts/basics/working-with-requestdigest.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/basics/working-with-requestdigest.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by VesaJuvonen** [comment] 2018-06-13 18:23
Thanks for reporting this, we are looking into to the root cause and ways to fix this asap.

**Comment by VesaJuvonen** [comment] 2018-06-25 11:40
We will be addressing this in the 1.5.1 release, which will be released soon.

**Comment by VesaJuvonen** [comment] 2018-06-26 19:20
This should be now addressed with the 1.5.1 release, so would request to validate the situation with following. Here are short release notes for 1.5.1 release - https://twitter.com/SharePoint/status/1011689501213757441.

**Comment by MaartenSundman** [comment] 2018-07-19 21:19
Also broken in some builds of 1.4. To work around it (as taking on trying to upgrade to a new spfx version is more than I wanted to take on to get a digest) I just did this:

let fetchProps:RequestInit = {
      method:"POST",
      headers: { "Accept":"application/json;odata=verbose","cookie":document.cookie},
      credentials:"include"
    };
    fetch(this.context.pageContext.web.absoluteUrl + "/_api/contextinfo",fetchProps).then((response:any) => response.json()).then((responseJson:any) => {
      this.setState({"digest": responseJson.d.GetContextWebInformation.FormDigestValue as string });
    });

**Comment by mcmynn83** [comment] 2018-12-17 21:12
This exists now.

**Closed by mcmynn83** 2018-12-17 21:12 UTC
Labels: area:framework, status:fixed-next-drop, status:tracked, type:bug
