### ISSUE TITLE
Command Set or Field Customizer not visible in Microsoft Teams tab

### ISSUE THREAD

**Issue by florianwachter** [SharePoint/sp-dev-docs#6208] opened 2020-08-27 07:17 UTC
## Category

- [x] Bug

## Describe the bug

If I use the SharePoint app in Microsoft Teams to display a specific SharePoint list in teams and if the list has any SPFx command sets or field customizers, the command sets will not show up and the fields with the field customizer will be empty. If I view the same list/view in SharePoint, everything works as expected.

This was working fine the last few month, but stopped working a few days ago.

## Steps to reproduce

Create a new SPFx project using the Yeoman generator 
yo @microsoft/sharepoint
select Extension and then Command Set

Bundle and package the app using
gulp bundle --ship
gulp package-solution --ship

Upload the app to the app catalog and install it on a SharePoint site.

Now the commands will be visible in all the lists on this SharePoint site.

If you use the SharePoint app in Microsoft teams and you select 'Add page or list from any SharePoint site' and you enter the URL to your list, the list will show up, but not the commands.

The same also happens if you have columns with a field customizer configured. The field renders correctly in SharePoint, but not in Teams.

## Expected behavior

Field Customizer, Command Sets, etc. should also show up in Microsoft Teams if I want to display a SharePoint list in teams.

## Environment details (*development & target environment*)

> **DELETE THIS LINE BEFORE SUBMITTING** - Complete the following (*if ignored you'll be prompted for it before we can address your issue... save the time and provide it in your initial submission*).

- Windows 10
- SharePoint Online
- **Framework**: Node.js v10
- **Browser(s)**: Chrome and Teams client
- **Tooling**:VS Code | SPFx v1.11.0

### Additional context

*Thanks for your contribution! Sharing is caring.*

**Comment by kongmengfei** [comment] 2020-09-04 08:30
Hi florianwachter,

I added a Tab in MS Teams and selected a list, it works fine as well as those associated command set extension.

![1](https://user-images.githubusercontent.com/57654821/92217416-406e5b00-eeca-11ea-8e1e-744508538640.jpg)
![2](https://user-images.githubusercontent.com/57654821/92217432-449a7880-eeca-11ea-9dc4-71173cc56e37.jpg)
![3](https://user-images.githubusercontent.com/57654821/92217444-46643c00-eeca-11ea-9020-12f7b02c752e.jpg)

I suggest you try it on Teams web app, so that we can use F12 to see if the extension has been loaded or not. 

My environment::
![image](https://user-images.githubusercontent.com/57654821/92218491-c9d25d00-eecb-11ea-8be1-0ce68eb0cc21.png)

Baker Kong
Microsoft SharePoint Community Support

**Comment by florianwachter** [comment] 2020-09-04 09:44
@kongmengfei : Thanks for the reply
I already tested it using the Teams web app and the extension has not loaded. It works on some sites, but not on others. 

One more thing i noticed is that in Teams it always displays the default view of the list and not the one I configured.

In SharePoint I can view all the commands and I see that I have the Test View selected and I copy the .../Test View.aspx URL
<img width="912" alt="inSharePoint" src="https://user-images.githubusercontent.com/5690610/92225162-21100780-eea3-11ea-8f09-45ca8be95f7c.png">
If I use this URL in a teams tab...
<img width="371" alt="configureteamstab" src="https://user-images.githubusercontent.com/5690610/92225174-253c2500-eea3-11ea-8b4a-1d15fca3f1b9.png">
... it always reverts back to the list's default view and the commands are not visible
<img width="681" alt="inteams" src="https://user-images.githubusercontent.com/5690610/92225182-2705e880-eea3-11ea-9ec3-c5c66dce03fc.png">

My tenant is also on Target release mode.

I hope this helps you to reproduce the issue in Teams. 

Thanks, Florian

**Comment by florianwachter** [comment] 2020-09-30 07:04
@andrewconnell:
Any news on this issue? 
It's been marked as bug-suspected for a while now. I'm still experiencing this issue and customers are starting to complain.

I appreciate any details you can provide.

Thanks, Florian

**Comment by florianwachter** [comment] 2020-09-30 07:08
@kongmengfei: Can you please try this again. In my previous answer I mentioned that it's working on some sites, but not on others. This is no longer true, now it stopped working on all SharePoint sites.

Thanks, Florian

**Comment by andrewconnell** [comment] 2020-09-30 09:34
@florianwachter I don't work for Microsoft so I won't have "news" to share. I've added a label for their visibility.

**Comment by frnk01** [comment] 2020-11-18 07:32
@VesaJuvonen @patmill  Can anyone of you confirm that spfx field extentions does not work in Teams files tab? I`m kind of facing the same issue now where field extension is loading fine in SharePoint, but not in files tab in Teams.

**Comment by pmeeks** [comment] 2020-12-02 09:06
Here is a similar issue with the context menu. Thread links to a UserVoice requesting this as a feature but it seems more of a bug? I upvoted it anyway.

https://techcommunity.microsoft.com/t5/sharepoint/spfx-extension-listview-command-set-in-microsoft-teams/m-p/1186699

**Comment by johnnycardy** [comment] 2021-01-05 14:45
Just to chime in here, I'm seeing the same issue. I've spent a while trying to get a CommandSet extension to register within a teams tab and can't.

**Comment by schneika** [comment] 2021-02-25 07:24
any updates?

**Comment by florianwachter** [comment] 2021-02-25 07:52
I also discussed this issue with Microsoft Support and they replied last week that: "…this current feature seems to be a bug on Teams that's why users have raised this feature through a Uservioce for it to be available or get fixed..." and "…for sure in the future our Engineering team will find a way to have this fixed completely but not for now...". It looks like it's not a top priority.

I think that this is the user voice entry they referred to: https://microsoftteams.uservoice.com/forums/555103-public/suggestions/40152034-show-sharepoint-custom-command-set-extensions-in-f

The following workaround worked for me:
If I add the viewId to the URL like …/AllItems.aspx?viewId=[the view guid], columns that use a field customizer render just fine in Teams, but I was never able to get the command sets to show up.

I hope this helps.

**Comment by lukju** [comment] 2021-08-11 06:16
This issue still seems to exist. The mentioned fix of adding the viewId didn't work for me. But I figured that as soon as I change the view in the UI of the tab, field customizers get loaded.
Also, If the SharePoint list gets added as Website Tab, field customizers get loaded correctly
The fact that field customizers do not get loaded on initial Tab load but get loaded as soon as we change the view in UI is a bug and should be fixed by Microsoft asap.

**Comment by frnk01** [comment] 2021-08-11 06:25
I can't understand how Microsoft has been able to ignore this issue for over a year. SPFX extensions in Teams does not load and is broken. It should not be necessary to post anything to uservoice imo.

@VesaJuvonen Can someone look into this?

**Comment by NaveenPrasathSS** [comment] 2021-11-17 16:15
Hi Everyone, I too facing the issue. Is there any update on the issue? @VesaJuvonen Can you please assist us on this?

**Comment by AJIXuMuK** [comment] 2021-11-17 17:05
sorry for the delay. It's a dupe of #5438. As Pat mentioned there - the fix has been implemented in Teams. But we don't have an ETA when exactly it will be delivered WW.

**Closed** 2021-11-17 17:05 UTC
Labels: type:bug-suspected, status:duplicate, area:spfx, status:to-be-reviewed
