### ISSUE TITLE
Running SPFX with Cloud 9 IDE browsing to workbench does not work

### ISSUE THREAD

**Issue by jkunle** [SharePoint/sp-dev-docs#533] opened 2017-04-03 11:25 UTC
Not Sure how to Categorise this may be an issue with how cloud 9 IDE resolves URL's. Any help with this would be appreciated.

#### Expected or Desired Behavior
After running gulp trust-dev-cert and gulp serve was expecting to be able to browse to the SPFX developer workbench
#### Observed Behavior
The commands above seem to run successfully however when the generated url is clicked and the open in preview browser selected the browser in cloud 9 IDE opens the URL but nothing happens. Two behaviours have been observed.
- The browser window says the request took too long ( this happens on my home computer)
- The browser window displays make sure you have the right web address (this happens at work)

#### Steps to Reproduce
Follow all the steps as documented on creating your first SPFX webpart in the link below. 
https://dev.office.com/sharepoint/docs/spfx/web-parts/get-started/build-a-hello-world-web-part

Use the cloud 9 IDE, start with the default node template updated with all the prerequisites.

Thanks for your contribution! Sharing is caring.

**Comment by chakkaradeep** [comment] 2017-06-30 22:02
Hi there,

I tried using the Cloud 9 IDE and at this point we are unable to debug where the problem is. We think Cloud9 workspace has some issues with the gulp-connect serve module which basically serves the application in the respective ports. We also upgraded the node to the latest 6.11.0 from 4.7.3 which was available and yet I get the following error when trying to navigate to the workbench.html:

```
ECONNRESET: Request could not be proxied!
There was an error proxying the request.
```

We also had to change the ports to 8081 and 8082 in the config\serve.json to the following:

```
{
  "port": 8081,
  "initialPage": "https://localhost:8082/workbench",
  "https": true,
  "api": {
    "port": 8082,
    "entryPath": "node_modules/@microsoft/sp-webpart-workbench/lib/api/"
  }
}
```

Please contact Cloud9 IDE support and work with them to debug it in their server. If you do find out there is some issue with the SPFx project system, please let us know and open a new issue. 

I am closing this issue for now.

Thanks,
Chaks

**Closed by chakkaradeep** 2017-06-30 22:02 UTC

**Comment by JFLovo** [comment] 2017-12-07 22:51
I'm having the same problem: 

After running gulp trust-dev-cert and gulp serve was expecting to be able to browse to the SPFX developer workbench!

But it does not because it's run for a while and then stop/ hung after: 
[22:34:17] Finished subtask 'write-manifests' after 393 ms
[22:34:17] Starting subtask 'reload'...
[22:34:17] Finished subtask 'reload' after 2.04 ms

Appreciated it, if you let me know how this issue was resolved.

Thank you!
