### ISSUE TITLE
PeoplePicker in SPF'x - SPClientPeoplePicker is undefined

### ISSUE THREAD

**Issue by naveenprasaths** [SharePoint/sp-dev-docs#496] opened 2017-03-17 12:47 UTC
I am developing a SPF'x addin. In this i am populating HTML controls like SP Edit Form. In this i need to create Client people Picker Control. I am not sure how to create a PeoplePicker in SPF'x. I just want to create a ClientPeoplePicker. What i have done is added a div element in my HTML and i tried to make that DIV as PeoplePicker.

```
 <div id='peoplepickerdiv'></div>
private loadPeoplePicker(peoplePickerElementId:string):void  {    
      let schema: ISPClientPeoplePickerSchema = {
      PrincipalAccountType: 'User,DL,SecGroup,SPGroup',
      SearchPrincipalSource: 15,
      ResolvePrincipalSource: 15,
      AllowMultipleValues: true,
      MaximumEntitySuggestions :50,
      Width: 280,
      OnUserResolvedClientScript: this.onUserResolvedClientScript
    }
    SPClientPeoplePicker.InitializeStandalonePeoplePicker(peoplePickerElementId,null,schema);
  }

  private onUserResolvedClientScript(el: string, users: ISPClientPeoplePickerEntity[]) {
        let keys:string = "";
        let userInfo:string = "";
        for (let i = 0; i < users.length; i++) {
            let user:ISPClientPeoplePickerEntity = users[i];
            keys += user.Key + ",";
            for (let userProperty in user) {
                userInfo += userProperty + ':  ' + user[userProperty] + '<br>';
            }
        }
        alert(userInfo);
       alert(keys);
  }
```

My Config.json is looks like: 

```
"externals": {
    "sp-init": {
      "path": "https://innovaopnsuite.sharepoint.com/sites/Innova/Submissions/_layouts/15/init.js",
      "globalName": "$_global_init"
    },
    "microsoft-ajax": {
      "path": "https://innovaopnsuite.sharepoint.com/sites/Innova/Submissions/_layouts/15/MicrosoftAjax.js",
      "globalName": "Sys",
      "globalDependencies": [
        "sp-init"
      ]
    },
    "sp-runtime": {
      "path": "https://innovaopnsuite.sharepoint.com/sites/Innova/Submissions/_layouts/15/SP.Runtime.js",
      "globalName": "SP",
      "globalDependencies": [
        "microsoft-ajax"
      ]
    },
    "sharepoint": {
      "path": "https://innovaopnsuite.sharepoint.com/sites/Innova/Submissions/_layouts/15/SP.js",
      "globalName": "SP",
      "globalDependencies": [
        "sp-runtime"
      ]
    }, 
     "sp-core": {
      "path": "https://innovaopnsuite.sharepoint.com/sites/Innova/Submissions/_layouts/15/core.js",
      "globalName": "SP",
      "globalDependencies": [
        "sp-runtime"
      ]
    }, 
    "clientpeoplepicker": {
      "path": "https://innovaopnsuite.sharepoint.com/sites/Innova/Submissions/_layouts/15/clientpeoplepicker.js",
      "globalName": "clientpeoplepicker",
      "globalDependencies": [
        "sharepoint"
      ]
    }
    , 
    "clienttemplates": {
      "path": "https://innovaopnsuite.sharepoint.com/sites/Innova/Submissions/_layouts/15/clienttemplates.js",
      "globalName": "clienttemplates",
      "globalDependencies": [
        "sharepoint"
      ]
    }
    , 
    "clientforms": {
      "path": "https://innovaopnsuite.sharepoint.com/sites/Innova/Submissions/_layouts/15/clientforms.js",
      "globalName": "clientforms",
      "globalDependencies": [
        "sharepoint"
      ]
    }
    , 
    "autofill": {
      "path": "https://innovaopnsuite.sharepoint.com/sites/Innova/Submissions/_layouts/15/autofill.js",
      "globalName": "autofill",
      "globalDependencies": [
        "sharepoint"
      ]
    }
  }
```

In my .tsx file i added the require section for those js like

```
require('clientpeoplepicker');
require('clientTemplates');
require('clientforms');
require('autofill');
```

Initially it throw "SPClientpeoplePicker" is undefined. so I added a "clientpeoplepicker.js" in Config.json "Externals" section. Now it throws "SPClientPeoplePickerCSRTemplate is not defined"  error. But i cant able to load "clientempletes.js","clientforms.js","autofill.js". How can i load those Js files? 

I am not sure What i missed. Please help me to sort it out. If possible, please give me an example.

Thanks

**Comment by patmill** [comment] 2017-10-24 18:59
This seems like a dupe of your previous bug #478 478

**Closed by patmill** 2017-10-24 18:59 UTC
Labels: status:tracked
