### ISSUE TITLE
SPFx 1.7.0 Dynamic Data - Connections between components randomly 'lost' after a whole page refresh

### ISSUE THREAD

**Issue by FranckyC** [SharePoint/sp-dev-docs#2985] opened 2018-11-20 22:25 UTC
#### Category
- [ X] Question
- [ ] Typo
- [X ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Web Parts connections should still work every time after a whole page refresh according to configuration.

#### Observed Behavior

I use the new dynamic data feature with SPFx 1.7.0 with multiple connected Web Parts on a single page. Sometimes, after reloading the whole page, connections are not made between components as it is supposed to work according the WP configurations. It is like properties and data sources were not wired correctly and depend on the components load order since this issue appears randomly.

If I switch to edit mode, the data sources and properties are still correctly set in Web Parts and works as expected. I also noticed that is doesn't work with IE 11 (11.0.9600.19003) but the issue is also present with Chrome (70.0.3538.102) and Firefox (63.0.3).

When debugging, I can actually see the call from source `this.context.dynamicDataSourceManager.notifyPropertyChanged` but consumers aren't triggered. 

Does a dynamic property 'waits' for the associated data source to be available on the page before making the connection?

#### Steps to Reproduce

Setup a connection between two Web Parts on a page using a dynamic property. The source expose an object type property like this:
```
{
	property: {
		subproperty: string;
	}
}
```

The consumer uses the default property pane fields as pointed out in the [documentation](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/dynamic-data) with following declaration:

```
subpropertyValue: DynamicProperty<string>;
```
```
protected get propertiesMetadata(): IWebPartPropertiesMetadata {
        return {
            'subpropertyValue': {
                dynamicPropertyType: 'string'
            }
        };
    }
```
```
PropertyPaneDynamicFieldSet({
                  label: strings.subProperty,
                  fields: [
                    PropertyPaneDynamicField('subpropertyValue', {
                      label: strings.subProperty
                    })
                  ],
                  sharedConfiguration: {
                    depth: DynamicDataSharedDepth.Source,
                  }
                })
```

**Comment by Seiyasu** [comment] 2018-11-21 05:06
It should be better you can provide the minimal reproducible project directly.

**Comment by FranckyC** [comment] 2018-11-21 14:21
Unfortunately, it is a customer project so I can't share you the source code. I noticed the issue appears only if I hit the page directly in the browser with a full postback. If I hit the page from a navigation link from the site menu, the connections are fine.

**Comment by patmill** [comment] 2018-11-27 16:18
Are you currently binding some of the properties to a multi-value root property?  Ie, the value from getPropertyValue is an array?

**Comment by FranckyC** [comment] 2018-11-28 17:52
The **getPropertyValue** method is defined as follow in the source. Properties are exposed dynamically under certain conditions. And yes, one on them is an array (I've indicated types in parenthesis).

```
public getPropertyValue(propertyId: string) {

	switch (propertyId) {

	case 'searchQuery':

		let property: { [key: string]: any } = {
			[strings.SearchBoxDynamicPropertyInputLabel]: this._searchQuery.inputQuery (STRING)
		};

		if (this.properties.enableQueryOptimization && this.properties.queryOptimizationServiceUrl) {
			property[strings.SearchBoxDynamicPropertyOptimizedQueryLabel] = this._searchQuery.transformedQuery (STRING);
			property[ strings.SearchBoxDynamicPropertyRecognizedTerms] = this._searchQuery.recognizedTermsIds (ARRAY OF STRINGS);
		}

		return property;

	default:
		throw new Error('Bad property id');
	}
}

```
With this setup, I 'm able to bind properties using the default property pane field in consumer WPs. 

![image](https://user-images.githubusercontent.com/5659122/49171346-52da5e80-f30c-11e8-9a3c-09a563c30b0f.png)

Data type is defined as follow for **string properties:**
```
protected get propertiesMetadata(): IWebPartPropertiesMetadata {
	return {
		'queryKeywords': {
			dynamicPropertyType: 'string'
		}
	};
}
```

And this way for the **array property**:
```
protected get propertiesMetadata(): IWebPartPropertiesMetadata {
	return {
		'termIds': {
			dynamicPropertyType: 'array'
		}
	};
}
```

**Comment by thechriskent** [comment] 2018-12-06 03:38
I have also seen this issue a number of times and it seems to be a timing issue.

I've found that if I have a connected webpart, there are times when it fails to get the source on initial page load. I've implemented a retry system (3 times with 100ms between) and this seems to be working just fine (haven't needed to go beyond a single retry yet, but it does happen often).

**From within my `render` method:**
```typescript
    if(!needsConfiguration) {
      //Get the value from our source
      const source: IDynamicDataSource = this.context.dynamicDataProvider.tryGetSource(this.properties.sourceId);
      if(!source) {
        this._sourceAttemptCount += 1;
        if(this._sourceAttemptCount <=3) {
          console.log('retrying...');
          window.setTimeout(this.render,100);
        } else {
          this.context.statusRenderer.renderError(this.domElement, `Unable to connect to the data source (${this.properties.sourceId})`);
        }
        return;
      } else {
        this._sourceAttemptCount = 0;
      }
      try {
        value = source.getPropertyValue(this.properties.propertyId);
        if(typeof value !== "undefined" && this.properties.displayType === 'object') {
          value = value[this.properties.displayObjectProperty === 'manuallyspecified' ? this.properties.displayObjectPropertyManual : this.properties.displayObjectProperty];
        }
      }
      catch(e) {
        const errorMessage = `An error has occurred while retrieving the property value (${this.properties.propertyId}). Details: ${e}`;
        this.context.statusRenderer.renderError(this.domElement, errorMessage);
        return;
      }
    }
```
 
As a result, I've also needed to track initial registration differently (I can't use renderedOnce anymore) because otherwise the source will get attached properly on the 2nd retry, but the registration won't be successful for seemingly the same reasons that the source initially fails).

**Immediately after the code above:**
```typescript
    if (this._registrationComplete === false && !needsConfiguration) {
      try {
        //If the subscription props exist, but we haven't registered yet then we need to register
        // otherwise, the registration will happen with the propertypane as the properties are configured
        this.context.dynamicDataProvider.registerPropertyChanged(this.properties.sourceId, this.properties.propertyId, this.render);
        this._lastSourceId = this.properties.sourceId;
        this._lastPropertyId = this.properties.propertyId;
        this._registrationComplete = true;
      }
      catch(e) {
        const errorMessage = `An error has occurred while connecting to the data source. Details: ${e}`;
        this.context.statusRenderer.renderError(this.domElement, errorMessage);
        return;
      }
    }
```

All of this is working, but I was surprised I would need to handle this plumbing. Is this expected?

**Comment by patmill** [comment] 2018-12-06 16:40
just want to check in here.
If you simply read the property, there can certainly be a timing issue, where the source hasn't been created / initialized before the target.

However, if you are using the dynamicProperty object to handle the property, this should get handled by the changed event firing when the datasource is initialized.

Are you seeing issues where the connection isn't getting made (and thus when the source property changes, the target doesn't get the notification and rerender)?  Or is it that if you simply try and read the property early on in the lifecycle that the property doesn't yet exist (possibly because the source webpart hasn't gotten far enough along in it's lifecycle to inititalize it's datasource)?

**Comment by FranckyC** [comment] 2018-12-07 20:44
@patmill What I'm seeing is more like the first scenario, when debugging, I can actually see the call from source (`this.context.dynamicDataSourceManager.notifyPropertyChanged`) but consumers aren't triggered even if they are initialized on the page.

**Comment by FranckyC** [comment] 2018-12-10 15:04
I've added the following line in the `onInit()` method in the consumer to force a render every time a new source is available on the page:
```
this.context.dynamicDataProvider.registerAvailableSourcesChanged(this.render);
```
However, if I monitor the value of the dynamic property at render time, this one is randomly empty so the connection isn't made:

```
{"__type":"DynamicProperty","value":""}
```

When working fine, the value is as follow:
```
Dynamic Property{"__type":"DynamicProperty","reference":{"_reference":"WebPart.096b96cc-8a44-41fa-9b4d-c0ab2ab2a779.07f5237e-caaa-4069-a6f9-4f73ba854ca0:searchQuery:Input value","_sourceId":"WebPart.096b96cc-8a44-41fa-9b4d-c0ab2ab2a779.07f5237e-caaa-4069-a6f9-4f73ba85
```
The issue seems to be on the property itself that turns empty for unknown reason.

**Comment by FranckyC** [comment] 2018-12-20 22:12
Update: @patmill @thechriskent I found a workaround by using the following method:

First, I create my own WP properties (_sourceId_, _propertyId_ and _propertyPath_) to track data source information before serializing all WP properties:
```
protected onBeforeSerialize() {

	if (this.properties.queryKeywords.reference) {
		this.properties.sourceId = this.properties.queryKeywords["_reference"]._sourceId;
		this.properties.propertyId = this.properties.queryKeywords["_reference"]._property;
		this.properties.propertyPath = this.properties.queryKeywords["_reference"]._propertyPath;
	} else {
		this.properties.sourceId = null;
		this.properties.propertyId = null;
		this.properties.propertyPath = null;
	}
	
	super.onBeforeSerialize();
}
``` 

Then I subscribe to the `registerSourceChanged` event in the `onInit` method. It will trigger the render every time a data source becomes available on the page.
```
protected async onInit(): Promise<void> {
	...
	if (this.properties.sourceId) {
		this.context.dynamicDataProvider.registerSourceChanged(this.properties.sourceId, this.render);
	} 
```

Finally, in the `render` method, I resolve the source manually if the default `tryGetSource()` method from the dynamic property fails but a source is supposed to be connected (I have the information through the `sourceId` property).

```
public render() {
	...
	let dataSourceValue;

	let source = this.properties.queryKeywords.tryGetSource();

	// Try to get the source if a source id is present
	if (!source && this.properties.sourceId) {
		source = this.context.dynamicDataProvider.tryGetSource(this.properties.sourceId);

		if (source && this.properties.propertyId) {
			dataSourceValue = source.getPropertyValue(this.properties.propertyId)[this.properties.propertyPath];
		}

	} else {
		dataSourceValue = this.properties.queryKeywords.tryGetValue();
	}
```

Not the most optimal way I guess, but with this, I don't have the issue anymore. I've implemented it in the [react-search-refiners](https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-search-refiners) SPFx sample.

**Comment by srideshpande** [comment] 2019-09-27 18:45
@FranckyC - Thanks for reporting the issue. Yes this is expected, that when the source is still not loaded on the page, and hence not initialized, the connection will not be established.

To add to what @patmill said earlier, if you're using DynamicProperty, if the source is not available, it waits. When the source, is available, then the DynamicProperty will establish a connection, and calls render on the consumer web part, and then it should refresh the values.

Please re-check. I'm closing the issue. If you still see any discrepancies, from what I said, please feel free to open an issue again.

Thanks,
Sri

**Closed by srideshpande** 2019-09-27 18:45 UTC
Labels: area:framework-dynamicData, area:framework-general, status:tracked
