### ISSUE TITLE
SPFx webparts on OnPrem 2016 intermittently fails with Error "Failed to render client side web part"

### ISSUE THREAD

**Issue by mustaqp** [SharePoint/sp-dev-docs#3586] opened 2019-03-12 18:45 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

Issue: In OnPrem SP 2016, SPFx webparts developed using SPFx-1.4.1, intermittently fails with below error:

ULS Log Errror:
03/07/2019 17:37:38.03 w3wp.exe (0x12B0) 0x1FA4 SharePoint Foundation General blde6 Medium Manifest {44DD20AD-349C-4394-B306-BEED5093E55C} not returned because feature 44dd20ad-349c-4394-b306-beed5093e55c not enabled aec7c69e-810d-5031-4dc4-1fddd88a8c70

Component '{44DD20AD-349C-4394-B306-BEED5093E55C}' doesn't have manifest. Skipping. 

Failed to render client side web part. Id: [44dd20ad-349c-4394-b306-beed5093e55c], Manifest: [<NULL>], Error Details:: [Microsoft.SharePoint.ClientSideComponent.SPClientSideFrameworkException: Web Part 44dd20ad-349c-4394-b306-beed5093e55c failed to render as manifest is not found    

Removing the app from the site and re-adding it again from corp catalog or from the recycle bin fixes the issue and the page will work for couple of weeks and it will break with same error/stack.
Found similar issue on SPO - https://github.com/SharePoint/sp-dev-docs/issues/2764 which seems to be fix. Is this fix in latest SPFx or in SP 2016 CU?

#### Expected or Desired Behavior

Once the app is installed, the SPFx parts added to the Page. Those webparts should render without any exception.

#### Observed Behavior
We see below error in developer tools. The SPFx webparts are not rendered on the page

Failed to render client side web part. Id: [44dd20ad-349c-4394-b306-beed5093e55c], Manifest: [<NULL>], Error Details:: [Microsoft.SharePoint.ClientSideComponent.SPClientSideFrameworkException: Web Part 44dd20ad-349c-4394-b306-beed5093e55c failed to render as manifest is not found
   at Microsoft.SharePoint.WebPartPages.ClientSideWebPart.GetManifest[TManifest](Guid componentId, String& manifestJson)
   at Microsoft.SharePoint.WebPartPages.ClientSideWebPart.<>c__DisplayClass4.<Render>b__0()
   at Microsoft.SharePoint.ClientSideComponent.SPClientSideFrameworkReliabilityHelper.ExecuteInReliabilityMonitoredScope[TException](Action userCodeDelegate, SPReliabilityMonitor monitor, UInt32 expectedFailureTag, Action`1 customErrorHandlerDelegate, Boolean reThrow)]
Web Part framework is not loaded.

Please assist. Thanks.

**Comment by sonicbaz** [comment] 2019-03-24 22:22
Hi I am also getting intermittent error on SP2016 classic 

I can fix by uninstalling and reinstalling in the site collection. 

**This is the 4th time it has happened and I need to get this fixed!**

Failed to render client side web part. Id: [xxxxxx-xxxx-xxxx-xxxxxx], Manifest: [<NULL>], Error Details:: [Microsoft.SharePoint.ClientSideComponent.SPClientSideFrameworkException: Web Part xxxxxx-xxxx-xxxx-xxxxxx failed to render as manifest is not found

   at Microsoft.SharePoint.WebPartPages.ClientSideWebPart.GetManifest[TManifest](Guid componentId, String& manifestJson)

   at Microsoft.SharePoint.WebPartPages.ClientSideWebPart.<>c__DisplayClass4.<Render>b__0()

   at Microsoft.SharePoint.ClientSideComponent.SPClientSideFrameworkReliabilityHelper.ExecuteInReliabilityMonitoredScope[TException](Action userCodeDelegate, SPReliabilityMonitor monitor, UInt32 expectedFailureTag, Action`1 customErrorHandlerDelegate, Boolean reThrow)] default.aspx:635:29
    cswp_WPQ7 https://intranet/sites/asite/Pages/default.aspx:635
    <anonymous> https://intranet/sites/asite/Pages/default.aspx:628
Web Part framework is not loaded. default.aspx:636:29
    cswp_WPQ7 https://intranet/sites/asite/Pages/default.aspx:636
    <anonymous> https://intranet/sites/asite/Pages/default.aspx:628

**Comment by cameronsibbald** [comment] 2019-04-01 22:49
We are also experiencing this issue

**Comment by westleyMS** [comment] 2019-04-03 21:17
@VesaJuvonen This issue was fixed in SPO but still there in 2016 FP2. We may need a port.

**Comment by VesaJuvonen** [comment] 2019-04-04 16:57
@westleyMS - if you have internal insights on what was exactly fix and tracking numbers, those would absolutely help. Based on this comment, I can't really perform additional actions as such.

**Comment by cameronsibbald** [comment] 2019-04-04 17:03
@VesaJuvonen looks like it was fixed for SPO in issue #2764

**Comment by VesaJuvonen** [comment] 2019-04-17 11:07
The original message has the following environmental description: In OnPrem SP 2016, SPFx web parts developed using SPFx-1.4.1. Can you please double check the used version as SharePoint Framework 1.4.1 is NOT supported with SharePoint 2016 Feature Pack 2. Only supported version is SharePoint Framework 1.1. 

There are mentions of Premier support, but unfortunately, I do not have access to what has reported there, so can't comment on the progress of that. Obviously, an issue reported with premier support should not be waiting for triage in this issue list as Premier customers are absolutely getting premier support for their issues.

**Comment by VesaJuvonen** [comment] 2019-04-17 11:17
Also - if someone still has this issue, can you please check the situation of your deployed solutions.

```
Failed to render client side web part. Id: [xxxxxx-xxxx-xxxx-xxxxxx], Manifest: [], Error Details:: [Microsoft.SharePoint.ClientSideComponent.SPClientSideFrameworkException: Web Part xxxxxx-xxxx-xxxx-xxxxxx failed to render as manifest is not found
````
'Would mean that the solution or components are not anymore served from the app catalog. Now - You can actually check this by moving to ComponentManifests folder in the app catalog site collections, so moving to for example to address of `contoso.sharepoint.com/sites/apps/Lists/ComponentManifests`. This is where the installed solutions are available.

One possible cause of the issue is that if you are using old old old version of the Yeoman to generate your solution, feature or component IDs might get changed when you do an update. This would then cause challenges whenever you update the solution package in app catalog as the manifest ID is changed and the existing instances in the pages can no longer be found.

This issue was fixed in the later version of the Yeoman packages, which means that in the best possible scenario - you'd be using 1.8.1 version and then you have targeted the environment to be SP2016... which will result packages.json to reference to 1.1 versions... when you do however do package solution with the later versions, we use new versions of the packaging code... which will then ensure that your identifiers will remain the same.

How to detect this possible issue? Check from the ComponentManifest library what's the ID of the web part which is missing based on the name. If the ID has been changed after a new version of the solution package has been deployed, you are using a problematic version of the SPFx solution packaging.

**Closed** 2019-05-01 13:00 UTC
Labels: Needs: Author Feedback, no-recent-activity
