### ISSUE TITLE
Bloated /dist folder in SPFx 1.12

### ISSUE THREAD

**Issue by s-KaiNet** [SharePoint/sp-dev-docs#6855] opened 2021-03-23 21:26 UTC
SPFx 1.12 introduced a new template for webpack entry point names using `[name]_[hash].js` template. As a result, every time a developer saves any code file in a solution (in a `gulp serve` mode), SPFx build pipeline will generate a new set of files (because on every save the `[hash]` is different) and will put them into the `/dist` folder. This folder is not cleared on a new `gulp serve` command and just aggregates more and more files as you write your code. 

For example: 

- In a brand new HelloWorld solution it's not a big problem. The default size of `/dist` is 60KB and grows by 60KB every time I save a file. It means after 100 saves the `/dist` size will be 6MB
- Things become worse if you add more dependencies to your solution. For example, a solution with [Reusable React controls for your SharePoint Framework](https://pnp.github.io/sp-dev-fx-controls-react/) generates 3.5MB of files in `/dist` folder on every source code file save. After 100 saves it will be 350MB of redundant files. 
- If we consider an average solution with external dependencies and a few web parts, like [PnP Modern Search](https://microsoft-search.github.io/pnp-modern-search/) or [SharePoint Starter Kit](https://github.com/pnp/sp-starter-kit). Then on every save we have 60MB more files in `/dist`. After 100 saves it will be 6GB of trash data.

The only way to get rid of it is to either manually delete `/dist` or run `gulp clean`, which is inconvenient. 

Suggested solutions: 

- Modify SPFx build pipeline to either delete all previous files on every webpack run
- Or at least delete `/dist` folder when running `gulp serve` from scratch.  

Previous SPFx 1.11 uses just `[name].js` file template, thus all files were overwritten and not accumulated. So no problem exists in SPFx 1.11.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d3b5db8-629b-1944-6f62-a333bc447fe3
* Version Independent ID: 207f7df7-4ddd-1c94-d4b4-207a87db07cb
* Content: [SharePoint Framework v1.12 release notes](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/release-1.12.0)
* Content Source: [docs/spfx/release-1.12.0.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/release-1.12.0.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by KevinTCoughlin** [comment] 2021-03-23 22:24
Duplicate of https://github.com/SharePoint/sp-dev-docs/issues/6838

**Closed** 2021-03-24 05:53 UTC
Labels: Needs: Triage :mag:, area:docs-comment
