### ISSUE TITLE
JSON too long for a site design?

### ISSUE THREAD

**Issue by trillian74** [SharePoint/sp-dev-docs#2974] opened 2018-11-19 10:33 UTC
#### Category
- [x] Question
- [x] Bug

#### Expected or Desired Behavior

I have a somewhat large json file that i read into a variable
$site_script_cts = Get-Content -Path .\contenttypes.json | Out-String
$sitescript_cts = Add-SPOSiteScript -Title "Add Custom content types" -Content $site_script_cts -Description "Creates custom content types for hub"
$sitedesign_cts = Add-SPOSiteDesign -Title "Custom content types"  -WebTemplate "64"  -SiteScripts $sitescript_cts.Id -Description "Creates Custom content types"
$null = Grant-SPOSiteDesignRights -Identity $sitedesign_cts.Id -Principals ("Special Projects") -Rights View
Invoke-SPOSiteDesign -Identity $sitedesign_cts.Id -WebUrl "https://firstcloud.sharepoint.com/sites/specialprojects"

This should start producing out put. The content of the json has been verified.

#### Observed Behavior

When i try to run the complete json i do not get any output, but when i split the script in let's say two and invoke them the produce the output

![image](https://user-images.githubusercontent.com/1140066/48701271-5e33d880-ebee-11e8-910c-744a2686bb72.png)

#### Steps to Reproduce
Have a json thats 350 lines long does not produce any output, but a lets say 140 lines long do.

Thanks for your contribution! Sharing is caring.

**Comment by trillian74** [comment] 2018-11-19 10:37
When i read the documentation that says (Invoke-SPOSiteDesign is limited to 30 actions and subactions). I guess i would need to create using Add-SPOSiteDesignTask ?

**Comment by bcameron1231** [comment] 2018-12-13 15:54
@trillian74 Correct, Invoke-SPOSiteDesign is limited to 30 actions. Add-SPOSiteDesignTask is the replacement for Invoke-SPOSiteDesign for longer scripts.  

Eventually the 30 action limit will also be removed from the UI Site Creation Flow as well.

**Comment by VesaJuvonen** [comment] 2019-01-08 18:34
This is indeed by design, but we should have more action space soon. Closing as answered.

**Closed by VesaJuvonen** 2019-01-08 18:34 UTC
Labels: area:site-design, type:question
