### ISSUE TITLE
Web Part Property Pane Content is Overlapped by Apply Button Panel

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-docs#762] opened 2017-08-03 21:36 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Web Part Property Pane content is fully visible in non-reactive mode

#### Observed Behavior
Web Part Property Pane content is partially overlapped by Apply Button Panel
#### Steps to Reproduce

- scaffold default web part
- disable reactive mode
```
protected get disableReactivePropertyChanges(): boolean {
    return true;
  }
```
- add such amount property pane fields to make scroll appear (in my test I duplicated 'description' text field 13 times)
- run the code
- open property pane
- scroll down the content of property pane
- content is overlapped

<img width="389" alt="screen shot 2017-08-03 at 2 35 14 pm" src="https://user-images.githubusercontent.com/17036219/28944857-015bb614-7859-11e7-8c99-3c2291099be2.png">

**Comment by srideshpande** [comment] 2017-08-11 22:38
Hello, @AJIXuMuK - Thanks for raising the concern. This is now fixed and will be available in the next release. I am closing the issue now but feel free to re-open it if the issue is not fixed in the next release.

Thanks,
Srikanth

**Closed by srideshpande** 2017-08-11 22:38 UTC
