### ISSUE TITLE
Error approving Graph SPFx solutions in admin centre

### ISSUE THREAD

**Issue by CloudDesignBox** [SharePoint/sp-dev-docs#2480] opened 2018-09-06 12:11 UTC
When uploading a Graph API consuming SPFx 1.6 solution, the admin centre preview API Management page is erroring.

First errors with a pop-up 
![error1](https://user-images.githubusercontent.com/17725046/45156428-0fbd9300-b1d6-11e8-8ebd-8887feed1266.JPG)
Access to Azure Active Directory resources using the SharePoint Framework will be available soon.

Then errors with correlation ids:
![error2](https://user-images.githubusercontent.com/17725046/45156459-29f77100-b1d6-11e8-92c4-33521514d94a.JPG)
A null value was found with expected type 'Edm.String[Nullable=False]. The expected type does not allow null values.

I had tested preview features on this tenancy using this admin centre fine previously. Maybe a bug?

**Comment by Nasicus** [comment] 2018-09-06 15:08
I wonder if it's not just that these tenants were not yet fully updated.

We migrated our solution to 1.6 today.
And on some tenants it worked ,by doing something similar to this https://github.com/SharePoint/sp-dev-docs/issues/2473#issuecomment-419111117 .

However on other tenants I have the same exception.
The only thing I can think of at the moment is that 1.6 is not fully rolled out yet....

**Comment by eoverfield** [comment] 2018-09-06 15:14
@Nasicus that seems reasonable. When I read the release notes for SPFx 1.6 https://github.com/SharePoint/sp-dev-docs/wiki/SharePoint-Framework-v1.6-release-notes, I see this line: 
"On a related note, any permissions that were granted previous to the 1.6.0 release will need to be re-granted, as we have changed which AAD application is used."
When I look at my aad applications, I see the "old" one, SharePoint Online Client Extensibility, but I do not yet see a new aad app. Athough I do not yet know the name of the new one.

Hopefully this will fix itself quickly.

**Comment by CloudDesignBox** [comment] 2018-09-06 15:20
I have tried this on another tenancy. Still getting the coming soon message but the red messages appear to be related to old Apps using preview graph access as they don't appear on the other tenancy....
My app requests do come through on the other tenancy! So maybe related to tenancies with old app permissions that were granted...
![error3](https://user-images.githubusercontent.com/17725046/45167318-d34b6080-b1f0-11e8-961f-87fab9550d4b.JPG)

**Comment by Nasicus** [comment] 2018-09-06 15:30
I don't think it's related to old granted permissions.
We also successfully "migrated" tenants today where we had permissions from 1.4.1 approved.

**Comment by eoverfield** [comment] 2018-09-06 16:44
A bit of chatter on this issue on Twitter as well. My understanding is that the PG is now well aware of the issue and they will sort it all out quickly. My current understanding is there is an app principle issue on some tenants with the rollout to SPFx 1.6. I have seen at least one hack to get around the issue, I recommend we all sit tight, this will get sorted out as quickly as the PG can make it happen.

**Comment by CloudDesignBox** [comment] 2018-09-06 16:50
Yes let's hope it gets looked at soon, certainly seems to be the case.

**Comment by eoverfield** [comment] 2018-09-06 19:08
I suggest redirecting this issue to https://github.com/SharePoint/sp-dev-docs/issues/2472 as they are related.

**Comment by patmill** [comment] 2018-09-06 21:00
Duplicate of https://github.com/SharePoint/sp-dev-docs/issues/2472

**Closed by patmill** 2018-09-06 21:00 UTC
Labels: status:duplicate

**Comment by iainl** [comment] 2018-09-10 08:18
I dont know if this is realted to the above but still getting this error
![image](https://user-images.githubusercontent.com/38407636/45285195-801c2b00-b4da-11e8-98ac-65da731e6696.png)
Any suggestions ? thanks
