### ISSUE TITLE
 Argument of type 'HttpClientConfiguration' is not assignable to parameter of type 'HttpClientConfiguration'

### ISSUE THREAD

**Issue by aslanovsergey** [SharePoint/sp-dev-docs#1637] opened 2018-04-11 09:48 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Observed Behavior

error TS2345: Argument of type 'HttpClientConfiguration' is not assignable to parameter of type 'HttpClientConfiguration'.

#### Steps to Reproduce
SPFx 1.4.1

        this.context.httpClient.post(
            endpoint,
            HttpClient.configurations.v1,
            httpClientOptions
        )

**Comment by wictorwilen** [comment] 2018-04-11 10:44
Try removing your `node_modules` folder and then run `npm install` again. Is this an upgraded project?

**Comment by aslanovsergey** [comment] 2018-04-11 10:49
Yep, this is an updated project from 1.4.0 to 1.4.1
And removing and installing modules didn't help

**Comment by aslanovsergey** [comment] 2018-04-11 10:50
This is my package.json if it will help

{
  "name": "dotg-purchase-requisition-webpart",
  "version": "0.0.1",
  "private": true,
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@microsoft/sp-core-library": "^1.4.1",
    "@microsoft/sp-lodash-subset": "^1.4.1",
    "@microsoft/sp-office-ui-fabric-core": "^1.4.1",
    "@microsoft/sp-webpart-base": "^1.4.1",
    "@types/react": "15.6.6",
    "@types/react-dom": "15.5.6",
    "@types/webpack-env": ">=1.12.1 <1.14.0",
    "react": "15.6.2",
    "react-dom": "15.6.2",
    "sp-pnp-js": "^3.0.5"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "^1.4.1",
    "@microsoft/sp-module-interfaces": "^1.4.1",
    "@microsoft/sp-webpart-workbench": "^1.4.1",
    "@types/chai": ">=3.4.34 <3.6.0",
    "@types/mocha": ">=2.2.33 <2.6.0",
    "ajv": "~5.2.2",
    "gulp": "~3.9.1"
  }
}

**Comment by waldekmastykarz** [comment] 2018-04-11 17:24
What is the import statement that you use to reference the `HttpClient` class?

**Comment by pdemro** [comment] 2018-04-11 21:13
@aslanovsergey I am noticing a similar issue.  A tagged version of our SpFx project was building a few days ago and is no longer building with a fresh node_modules folder. 

With your guidance I took a look at the delta with a new SpFx project and noticed that they've upgrade @types/react to 15.6.6 (was 15.6.2).  Not sure when but at some point they moved these types dependencies from the devdependencies object into dependencies.

Here is an example of code that no longer compiles without updating @types/react dependency:
```typescript
import TaxonomyPicker, { ITaxonomyValue, ITaxonomyPickerProps } from "react-taxonomypicker";

...

private silly(): JSX.Element {
    let taxonomyPickerProps: ITaxonomyPickerProps = {
        name: "Hello",
        multi: false
    };

    return <TaxonomyPicker
        {...taxonomyPickerProps}
    />

}
```

And the error..

```
[ts]
Type '{ name: string; multi: boolean; displayName?: string; termSetGuid?: string; termSetName?: string;...' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<TaxonomyPicker> & Readonly<{ children?: ReactNode;...'.
  Type '{ name: string; multi: boolean; displayName?: string; termSetGuid?: string; termSetName?: string;...' is not assignable to type 'IntrinsicClassAttributes<TaxonomyPicker>'.
    Types of property 'ref' are incompatible.
      Type 'Ref<ReactSelectClass>' is not assignable to type 'Ref<TaxonomyPicker>'.
        Type 'RefObject<ReactSelectClass>' is not assignable to type 'Ref<TaxonomyPicker>'.
```

**Comment by wictorwilen** [comment] 2018-04-12 09:13
Do you have a `package-lock.json` file that messes with your dependecies?

**Comment by VesaJuvonen** [comment] 2018-04-12 17:14
Apparently, the issue was then due to the mismatch in the node_modules, which could be caused by a failure of the upgrade steps etc. Without having access to the solution, we can only speculate what is the root cause of the original package. Therefore closing this for now. @pdemro - would report that as a separate issue to avoid secondary issues just in the comments on another issue.

**Closed by VesaJuvonen** 2018-04-12 17:14 UTC
Labels: area:framework, type:bug

**Comment by aslanovsergey** [comment] 2018-06-08 10:18
Deletion of npm-shrinkwrap has helped

**Comment by KathiaRieser** [comment] 2019-10-10 13:14
I have the same issue and nothing works. Any help?
