### ISSUE TITLE
List View Command not visible on Document Library after giving RegID 101

### ISSUE THREAD

**Issue by shivdk7** [SharePoint/sp-dev-docs#4343] opened 2019-07-23 12:50 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x ] Bug
- [ ] Additional article idea

Expected or Desired Behavior
For Listview Command set, if RegID is 101, the command set should be deployed in document library.

Observed Behavior
Command set visible in List and not on Document Library
@VesaJuvonen

Steps to Reproduce
Followed instructions on MS tutorial:
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api

Submission Guidelines
Command set is getting deployed in list but not in library plus i am not able to debug it locally as well.

Thanks for your contribution! Sharing is caring.

**Comment by andrewconnell** [comment] 2019-07-29 13:50
I think this is a dupe of https://github.com/SharePoint/sp-dev-docs/issues/3914#issuecomment-498751448 ... there's an issue (either by design / bug... yet to be determined) with using registering with doc libraries...

**Closed** 2019-08-01 14:00 UTC
Labels: area:framework-extensions, status:answered, status:duplicate, type:question
