### ISSUE TITLE
ADAL Invalid_state after getting access token while using API's in SPFX web part

### ISSUE THREAD

**Issue by michelsmit** [SharePoint/sp-dev-docs#5928] opened 2020-06-23 14:41 UTC
## Category

- [x] Bug

## Describe the bug

We have developed several SPFX web parts which make use of external API's (e.g. Graph, PowerBI and Windows Virtual Desktop). To obtain an access token we're using the aadTokenProviderFactory's provider getToken method. Most of the time this works, but once in a while getToken returns nothing, and all other web parts are not returning any data.

When inpecting the sessionStorage there are some adal entries, one of them contains the following error:

Invalid_state. state: 28742357-17ed-4ec3-9ccc-32b7f6c22aba|https://analysis.windows.net/powerbi/api

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/4091377/85422013-65af2680-b575-11ea-974c-2aebd7eeb1e7.png)

[src.zip](https://github.com/SharePoint/sp-dev-docs/files/4820305/src.zip)

Furthermore, NO errors or other messagers appear in the console, and also no network traffic occurs once it seems broken.

## Steps to reproduce

See attached web part code. Place it on a page and refresh the page until pressing one of the buttons in the web part don't deliver any result.

## Expected behavior

Obtaining an access token without problems ;)

## Environment details (*development & target environment*)

- **Your Developer Environment**: Windows 10
- **Target Environment**: SharePoint Online]
- **Framework**: SPFX
- **Browser(s)**: Chromium Edge
- **Tooling**: SPFx v1.10.0
- **Additional details**: *The more context you can provide, the easier it is (and therefore quicker) to help.*

### Additional context

*Thanks for your contribution! Sharing is caring.*

**Comment by michelsmit** [comment] 2020-06-23 14:48
[src.zip](https://github.com/SharePoint/sp-dev-docs/files/4820131/src.zip)
Web part source

**Comment by andrewconnell** [comment] 2020-06-23 18:27
Possible dupe of #4892? You say it returns nothing... sounds similar to a known issue...

**Comment by michelsmit** [comment] 2020-06-30 13:41
@andrewconnell seems the same issue, close this one?

**Closed** 2020-06-30 13:43 UTC
Labels: area:auth, status:duplicate, type:bug-suspected
