### ISSUE TITLE
Using Fluent UI icons in Command Set

### ISSUE THREAD

**Issue by mayo589** [SharePoint/sp-dev-docs#7565] opened 2021-12-07 10:44 UTC
Is there any chance, that ListView Command Set will support official Fluent UI Icons, through CSS classes, like mentioned here (from 2017) https://github.com/SharePoint/sp-dev-docs/issues/642 

It was one of the most up-voted problems on SharePoint Online User Voice (that has been shut down...)

Thanks on any comment

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38ba7b1f-b77a-0076-ed6c-dd84bbc104ea
* Version Independent ID: d7cc472b-1c5b-fd7b-f7dc-6add54dd0886
* Content: [Configure extension icon in SharePoint Framework (SPFx) Extensions](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/basics/configure-extension-icon)
* Content Source: [docs/spfx/extensions/basics/configure-extension-icon.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/extensions/basics/configure-extension-icon.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by AJIXuMuK** [comment] 2021-12-07 13:38
Hello @mayo589  - thank yoi for the suggestion.
It is a dupe of #642.
Additionally, we're currently collecting the proposals for command sets here: https://github.com/SharePoint/sp-dev-docs/discussions/7375.
Please, feel free to add any additional thoughts in there.

**Closed** 2021-12-07 13:38 UTC
Labels: status:duplicate, area:docs-comment
