### ISSUE TITLE
🐞 Broken package-solution for Application customiser extension - case-sensitive-os

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#4988] opened 2019-12-06 09:26 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Create a development package of an application customizer that loads sources from localhost. This worked in the past for web parts and extensions.

#### Observed Behavior
When creating a new application customizer in SPFx 1.9.1 and run development to create a package the following error is shown.

<img width="921" alt="Screenshot 2019-12-06 at 09 41 21" src="https://user-images.githubusercontent.com/5503835/70308922-9a8fa200-180c-11ea-90bb-79da412df7a5.png">

> Could not find Element Manifest: sharepoint/assets/clientsideinstance.xml

This is strange because the 'clientsideinstance.xml' exists in the folder.

<img width="337" alt="Screenshot 2019-12-06 at 09 43 22" src="https://user-images.githubusercontent.com/5503835/70309040-e0e50100-180c-11ea-9dfd-f770e284c436.png">

In my case, it is explainable because my file system is case sensitive and the reference in not CamelCased.

<img width="583" alt="Screenshot 2019-12-06 at 09 47 16" src="https://user-images.githubusercontent.com/5503835/70309429-cf502900-180d-11ea-8896-30d8c1731c62.png">

#### Intermediate Fix

Changing the assets to CamelCase in the Element manifest.

<img width="522" alt="Screenshot 2019-12-06 at 10 23 14" src="https://user-images.githubusercontent.com/5503835/70311716-79ca4b00-1812-11ea-85ac-013337b9ebfb.png">

Package solution works then without any issue.

#### Steps to Reproduce

Create a new application customizer and run:
* gulp build
* gulp bundle
* gulp package-solution

or as a production build.

**Comment by andrewconnell** [comment] 2019-12-06 10:15
Good catch... confirmed. I can dupe this locally as well.

**Comment by KevinTCoughlin** [comment] 2020-01-24 00:50
This case-sensitive issue was fixed in SPFx 1.10 release.

**Comment by StfBauer** [comment] 2020-01-24 09:32
@KevinTCoughlin Thank you. Will try it and will close the issue then.

**Closed** 2020-01-24 10:35 UTC
Labels: area:generator, status:fixed, type:bug-confirmed
