### ISSUE TITLE
View Formatting causing issues when added using list view webpart on modern page

### ISSUE THREAD

**Issue by harshdamaniahd** [SharePoint/sp-dev-docs#5251] opened 2019-02-06 13:40 UTC
Do we still have these kinds of issue ?
Is there a way to fix them ?
Currently i am trying to something like this : 
![image](https://user-images.githubusercontent.com/11780473/52345159-c55a6f80-2a1c-11e9-96f8-c2937532a5f8.png)
But when i add this to modern page, it doesnt work 
![image](https://user-images.githubusercontent.com/11780473/52345203-ddca8a00-2a1c-11e9-9e78-107b9bf2410a.png)

When i investigated, i came to know that this is because of the following CSS
![image](https://user-images.githubusercontent.com/11780473/52345265-081c4780-2a1d-11e9-8fc1-4c65b660dbf4.png)

What should i do in such scenario ? .

**Comment by VesaJuvonen** [comment] 2020-01-29 17:01
Moving the issue to centralized SP Dev issue list as this is not an issue related on any list formatting sample, so issue should be in sp-dev-docs repository.

**Comment by marissasinai** [comment] 2020-01-29 19:56
@svaibhav  This is happening in multiple tenant solutions right now and I need it to be fixed ASAP. Is there a specific time frame that this fix is going to be pushed out?

<img width="872" alt="Annotation 2020-01-29 135543" src="https://user-images.githubusercontent.com/49072908/73392279-17844880-429f-11ea-8c27-b5bb45164ec4.png">

**Comment by furler** [comment] 2020-01-29 22:40
> @asifahmeds `tileProps` should work with all the site. You have to make sure that you choose the tiles layout once you have applied the JSON with the `tileProps`. Once the `tileProps` are applied, you'll see a new option as Tiles in the dropdown. Please choose that and verify again.
> 
> ![image](https://user-images.githubusercontent.com/6286818/73242982-6dd48700-41cc-11ea-8352-283cbc3fd7c8.png)

tileProps is a great development, and allows for a "proper" flexbox layout - the problem is it doesn't work reliably when the list is embedded via the web part. From my testing I 'think' it works only if the view is set to tiles on the list proper, then that view is edited and saved to be the default view.  If any of that changes then it breaks on the page and reverts to a list view. 

So, that means as well as it being unreliable, you can only have one view per list that uses tileProp if you want the list to sit on a SharePoint page.

@VesaJuvonen  - This is probably a different bug, I know, but the tileProp property keeps on getting thrown around as a solution, but until either the web part gets a setting to force "tile view" - or the list itself can be saved to default to tile view - it's just not ready for production to be embedded onto SharePoint Online pages via the list web part.

**Comment by asifahmeds** [comment] 2020-01-30 06:49
@furler - Yes, tileProps is not a workaround for this issue.

**Comment by svaibhav** [comment] 2020-01-30 08:26
Update: We are working on the issue. And it is working fine (or has been fixed) on some of the internal development environment. Since this is a recent regression, we are trying to find out how exactly it regressed in the first place.

**Comment by asifahmeds** [comment] 2020-01-30 08:37
@svaibhav - ETA would help us to answer our site users. Could you provide that?

**Comment by shagra-ms** [comment] 2020-02-03 11:41
@asifahmeds The fix for this is in pipeline. It shall be available on list web parts in 2-3 weeks.

**Comment by shagra-ms** [comment] 2020-02-11 04:02
The fix is now available in production tenants. Please let me know if this is still broken for you.

**Comment by furler** [comment] 2020-02-11 05:04
@shagra-ms - working for me. Thanks very much for getting this done.

**Comment by FredrikEkstroem** [comment] 2020-02-11 13:48
@shagra-ms I confirm, in my tenant issue is fixed, tnx

**Comment by gobigfoot** [comment] 2020-02-11 14:17
The issue has been rolled out in GCC High. Thank you.

**Comment by VesaJuvonen** [comment] 2020-02-11 15:34
Closing issue based on the acknowledgements from multiple users. Thanks for your input around this one.

**Closed by VesaJuvonen** 2020-02-11 15:34 UTC
Labels: area:list-formatting, status:fixed-next-drop, type:bug-confirmed
