### ISSUE TITLE
Extension throwing error: Killswitches are not initialized #115

### ISSUE THREAD

**Issue by jcosta3394** [SharePoint/sp-dev-docs#1481] opened 2018-03-16 17:22 UTC
When performing "gulp serve" on a new empty extension (app customizer) an error is thrown:

Killswitches are not initialized. Killswitch requested: aca19dad-e178-47bd-882e-5633af7b7ff0
CALL STACK:
Error: Killswitches are not initialized. Killswitch requested: aca19dad-e178-47bd-882e-5633af7b7ff0
    at Function.e.isActivated (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-03-02.016/sp-core-library_en-us_7572ea1dfcf36c9fe486c603f1fb4180.js:70:14914)
    at t._forEachPropertyWithMetaData (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-03-02.016/sp-webpart-base_en-us_6e989e91f47afa507f7a18d98578f5f8.js:84:25477)
    at t._reInstateServerProcessedData (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-03-02.016/sp-webpart-base_en-us_6e989e91f47afa507f7a18d98578f5f8.js:84:24160)
    at t._deserialize (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-03-02.016/sp-webpart-base_en-us_6e989e91f47afa507f7a18d98578f5f8.js:84:27069)
    at t._internalDeserialize (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-03-02.016/sp-webpart-base_en-us_6e989e91f47afa507f7a18d98578f5f8.js:84:28284)
    at https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-03-02.016/sp-webpart-base_en-us_6e989e91f47afa507f7a18d98578f5f8.js:84:29330
    at new Promise (<anonymous>)
    at t._internalFirstTimeRender (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-03-02.016/sp-webpart-base_en-us_6e989e91f47afa507f7a18d98578f5f8.js:84:28874)
    at e._initializeAndRenderWebPart (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-03-02.016/sp-pages-assembly_en-us_043bdad7f703a3fc5c0880b7c7495359.js:428:73263)
    at https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-03-02.016/sp-pages-assembly_en-us_043bdad7f703a3fc5c0880b7c7495359.js:428:59061

This seems to happen wherever web parts are on the page. It doesn't occur in library pages, for example. In my communication site the error doesn't show up in the console although the web parts don't load. In other pages the error shows on the page itself and is thrown to the console once I try to interact with the page like when attempting to edit it.

On an out of the box Community site an installed extension caused the same issue. Although this error wasn't thrown into the console the web parts wouldn't load, which we found to be the main symptom of this issue.

I'm on Windows 10 using SPFx framework v1.4.1, node v6.13.0, npm v3.10.10.

#### Category
- [ ] Question
- [ X] Bug
- [ ] Enhancement

#### Steps to Reproduce
Instantiate a vanilla extension and serve it, as far as I can tell, on a page that has web parts in it.

**Comment by patmill** [comment] 2018-03-16 21:14
We know the underlying issue and we are working on a fix.

**Comment by mpasarin** [comment] 2018-03-16 21:16
While the issue is not resolved, let me suggest you to test the application customizers on list pages, where this problem doesn't occur. Another alternative would be to install the package in the app catalog and then serve the scripts from you local machine.

This problem is scoped to usage of debug manifests only so there should be no problem when using SPFx web parts/extensions from the app catalog.

**Comment by tdwhite0** [comment] 2018-03-20 14:28
Any timeline on when this will be fixed? I use the debugManifests functionality all the time.

**Comment by patmill** [comment] 2018-03-20 16:16
Can you double check, I believe the fix was rolling out, and should be available everywhere now.  If it isn't working, can you note what version of the code is getting loaded?  If you look at the network tab, many of the files should be coming from https://spoprod-a.akamaihd.net/files/sp-client-prod_******/ 
 What does the path look like?

**Comment by tdwhite0** [comment] 2018-03-20 17:08
Looks like its working for me now, thanks!

**Comment by patmill** [comment] 2018-03-20 22:32
Perfect, sorry for the delay.

**Closed by patmill** 2018-03-20 22:32 UTC
Labels: area:framework, type:bug
