### ISSUE TITLE
Error: ***The value for "hamburgerCallback" must not be undefined

### ISSUE THREAD

**Issue by acksoft** [SharePoint/sp-dev-docs#799] opened 2017-08-23 20:58 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
I would expect that a SPFx web part project that runs in the hosted workbench on a Monday afternoon to continue to work on Tuesday morning if no changes have been made to it by the programmer.

#### Observed Behavior
I have a project that worked last week that I left in an incomplete but testable state.  Yesterday I came back to work on the project and began getting the message that is the title of this item when I tried to run the project in the SP Online hosted workbench.  I am not the only person experiencing this issue -- I am in California and other developers as far away as New Zealand are seeing the same behavior. See this discussion at the SharePoint Developer Workspace: [Error: ***The value for "hamburgerCallback" must not be undefined](https://techcommunity.microsoft.com/t5/SharePoint-Developer/Error-The-value-for-quot-hamburgerCallback-quot-must-not-be/m-p/99719#M3210)

#### Steps to Reproduce
Absolutely no idea.  This happened without my intervention and for no immediately apparent reason.

**Comment by DennisKuhn** [comment] 2017-08-23 21:39
vsCode reckons it's an issue with the debugger extensions, so I created one there. https://github.com/Microsoft/vscode-chrome-debug/issues/481

**Comment by DennisKuhn** [comment] 2017-08-23 22:11
I created a new sharepoint project with `yo @microsoft/sharepoint` version 1.1.3 still same issue.

**Comment by DennisKuhn** [comment] 2017-08-24 04:51
https://github.com/roblourens at vsCode/ChromeDebug, reckons "Is this not just an exception being thrown from the app/library? `https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-08-11.019/sp-webpart-workbench-assembly_en-us_1103575b589894e6f7c32232400ee52c.js` seems to clearly be code loaded on the page.

**Comment by nickpape-msft** [comment] 2017-08-24 19:02
Thanks for reporting this issue. This is definitely a regression which we will be fixing as soon as possible. I'll update the thread once the fix has been deployed.

**Comment by MarcoSimon** [comment] 2017-08-29 11:27
I've got a similar issue: 
> Error: ***The value for "error" must not be undefined
![2017-08-29 13_22_43-webpartbeezyactivities](https://user-images.githubusercontent.com/6904649/29818579-3c17f056-8cbd-11e7-8141-5ed91cf55a0e.png)

It happens with a modern webpart (with react and typescript) on a modern page. On classic pages it works without any errors.

I hope the fix will solve my problem as well.

**Comment by DennisKuhn** [comment] 2017-08-30 00:13
Seems the `hamburgerCallback` exception disappeared yesterday. I still keep getting the `InvalidOperation` exception.

**Comment by OliverZeiser** [comment] 2017-08-31 06:36
Same here, the hamburger issue seems to be resolved, but the InvalidOperation Exceptions are still there. But I think those are coming from the Suitebar...
It is still a pain when debugging SPFX code.
![invalidoperation](https://user-images.githubusercontent.com/8672900/29909689-57840c38-8e27-11e7-8dd9-ddf3540c3a9c.PNG)

**Comment by lahuey** [comment] 2018-03-19 23:16
The InvalidOperation Exception issues seem to be resolved. Please reopen this bug if you are still able to reproduce this issue. Thanks!

**Closed by lahuey** 2018-03-19 23:16 UTC
