### ISSUE TITLE
Selecting a PropertyPaneChoiceGroup option changes other PropertyPaneChoiceGroups to that option

### ISSUE THREAD

**Issue by neilhoff** [SharePoint/sp-dev-docs#730] opened 2017-07-18 15:13 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
When you select an option in a PropertyPaneChoiceGroup it shouldn't select the same option in a second PropertyPaneChoiceGroup

#### Observed Behavior
I have multiple PropertyPaneChoiceGroups that pull their options from an imported constant.
When I select one of the options, it changes the other PropertyPaneOptions as well.

This issue started in the last day or two and is only happening when using the webpart online. **When I test in the local development environment everything works fine.**

#### Steps to Reproduce

**WebPart.ts**

```ts
import { skyShareColors} from './imports/skysharecolorchoicegroupoptions/SkyShareColorOptions';

...

PropertyPaneChoiceGroup('groupTitleColor',{
                  label: strings.FontColorLabel,
                  options: skyShareColors
                })
...

 PropertyPaneChoiceGroup('imageTitleColor',{
                  label: strings.FontColorLabel,
                  options: skyShareColors
                })
...
PropertyPaneChoiceGroup('imageLinkColor',{
                  label: strings.FontColorLabel,
                  options: skyShareColors
                })
```

**SkyShareColorOptions.ts**

```ts
export const skyShareColors: IPropertyPaneChoiceGroupOption[] = [
    {
      key: "#ffffff",
      text: "White",
      imageSize: {
        width: 29,
        height: 29
      },
      imageSrc: 'white.png',
      selectedImageSrc: 'white.png'       
    },
    {
      key: "#333333",
      text: "Black",
      imageSize: {
        width: 29,
        height: 29
      },
      imageSrc: 'black.png',
      selectedImageSrc: 'black.png'       
    },    
    {
      key: "#008EC0",
      text: "Blue",
      imageSize: {
        width: 29,
        height: 29
      },
      imageSrc: 'blue.png',
      selectedImageSrc: 'blue.png'   
    }
    ...
  ];
```

![spfx_options_issue](https://user-images.githubusercontent.com/1918319/28324479-1b77f982-6ba1-11e7-8bc4-d7ea9f0d5b1e.gif)

**Comment by srideshpande** [comment] 2017-07-26 21:08
@neilhoff - Thanks for raising this concern. This seems like a bug, I will take a look at it and get back to you.

**Comment by srideshpande** [comment] 2017-08-01 18:11
@neilhoff - The issue is fixed now and it should be available in the next release.

Please let me know if you think it is still not fixed. I am closing the issue for now, but feel free to re-open or create a new one if you see the issue.

**Closed by srideshpande** 2017-08-01 18:11 UTC
Labels: status:tracked, type:bug

**Comment by neilhoff** [comment] 2017-08-03 21:07
@srideshpande Thanks for looking into this, but it still isn't working for me.

I followed this [post](https://dev.office.com/sharepoint/docs/spfx/toolchain/update-latest-packages) and ran `npm outdated` and none of the `@microsoft/` dependencies were in the list. 

I am not sure how I can verify this without being able to upgrade to the next release.
Any ideas?

**Comment by srideshpande** [comment] 2017-08-11 22:55
@neilhoff - I think that is because the fix hasn't been released yet. My bad, I should have told you to wait until the next release before you check. Please re-check it after a week around next Friday. Thanks for your patience.

As said earlier, if you do not see this issue fixed in the next release. Please re-open or create a new bug.

Thanks,
Srikanth
