### ISSUE TITLE
New Sync to Teams - "The remote server returned an error: (403) Forbidden." error

### ISSUE THREAD

**Issue by Dangerous-Mind** [SharePoint/sp-dev-docs#5573] opened 2020-04-14 15:07 UTC
## Category

- [x] Bug

## Describe the bug

Trying to sync a app to Teams and I'm receiving the message 
"The remote server returned an error: (403) Forbidden." 
from 
https://xxxx.sharepoint.com/sites/Apps/_api/web/tenantappcatalog/SyncSolutionToTeams

## Steps to reproduce

1. Create app.
2. Move to SharePoint apps site
3. Check it in.
4. Click Sync to Teams

## Developer environment

- OS: [Windows 10]
- Framework: [Node.js v10.19.0]
- Browser(s): [Chromium Edge V81.0.416.53]
- Tooling: [VS Code, SPFx v1.10.0] 

### Additional context
The Web app is already deployed and working in a site.
But I can't sync it to teams.

It's not a globally deployed app. 
It has webApiPermissionRequests already granted: 
```
"webApiPermissionRequests": [
      {
        "resource": "Microsoft Graph",
        "scope": "Mail.Send"
      }
    ]
```

**Comment by Dangerous-Mind** [comment] 2020-04-16 18:51
Any news on this issue?

**Comment by andrewconnell** [comment] 2020-04-17 21:27
Looks like a dupe of #5558

**Comment by patmill** [comment] 2022-01-04 19:58
Sorry - this was missed due to issue metadata / tagging.  We have reworked the way sync-to-teams works.  I'm going to close this, but please open a new issue if you are still having problems.

**Closed by patmill** 2022-01-04 19:58 UTC
Labels: type:bug-suspected, area:spfx
