### ISSUE TITLE
Application Customizer Not Loading After 1.16.1

### ISSUE THREAD

**Issue by wadamraby** [SharePoint/sp-dev-docs#8628] opened 2022-12-01 15:06 UTC
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version: chrome 107.0.5304.122
- SPFx version 1.16.1
- Node.js version v16.17.1
- etc

### Describe the bug / error

Hello, I have a new SPFX 1.16.1 project set up as an application extension. The project builds without error, and is deployed to the site collection app catalog. 

The error being received is:
Uncaught (in promise) Error: Failed to create application customizer 'ClientSideExtension.ApplicationCustomizer.XXXXXXXXXX'. Error information is 'Extension failed to load for componentId "XXXXXXXXXXXXXXXXXXX".'.

My previous 1.15 extension worked as expected.

### Steps to reproduce

1. Start a new application customizer extension project from yo @microsoft/sharepoint
2. Deploy to site collection app catalog
3. Add app to site
4. Receive error in console after refreshing home page

### Expected behavior

The extension to load properly.

**Comment by AJIXuMuK** [comment] 2022-12-01 16:25
I believe it's a dupe of #8623

**Closed** 2022-12-01 16:25 UTC
Labels: type:bug-suspected, status:duplicate, Needs: Triage :mag:
