### ISSUE TITLE
Get followed documents not working anymore

### ISSUE THREAD

**Issue by Rafaelki** [SharePoint/sp-dev-docs#5669] opened 2020-05-05 12:40 UTC
The endpoint _/_api/social.following/my/followed_(**types=2**) is returning sites (ActorType=2) instead of documents (ActorType=1).
**types=4** also returns sites only
**types=6** is returning sites **and documents**

According to documentation, types allows bitwise combinations where Users = 1, Documents = 2, Sites = 4, Tags = 8.

This was working fine until 2 weeks ago when something was changed.
Has this change been properly communicated?
Is the /_api/social.following endpoint still supported? 
I am aware of this announcement (https://developer.microsoft.com/en-us/office/blogs/upcoming-api-changes-to-sharepoint-social-feed-apis-and-following/) but it doesn't make sense to mess with this endpoint until there is an alternative (Microsoft Graph doesn't have a way to retrieve followed documents).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10ba3673-5f22-a56d-de66-838d114eb641
* Version Independent ID: 67b35cf8-ea9f-6ac3-2ba0-d936f8e76056
* Content: [Follow documents, sites, and tags by using the REST service in SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-follow-documents-sites-and-tags-by-using-the-rest-service-in-sharepoint-2)
* Content Source: [docs/general-development/how-to-follow-documents-sites-and-tags-by-using-the-rest-service-in-sharepoint-2.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/how-to-follow-documents-sites-and-tags-by-using-the-rest-service-in-sharepoint-2.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by siljemda** [comment] 2020-05-06 06:36
@Rafaelki After looking for alternatives myself yesterday I found that there is a Graph endpoint for following documents, albeit not sites as far as I can see. Maybe you can use /following for sites and graph for documents? I'm hoping to implement this myself.

https://docs.microsoft.com/en-us/graph/api/drive-list-following?view=graph-rest-1.0&tabs=http
https://docs.microsoft.com/en-us/graph/api/driveitem-follow?view=graph-rest-1.0&tabs=http

**Comment by Rafaelki** [comment] 2020-05-06 09:42
Thank you @siljemda for your quick answer. 
At this point, I am only interested in Followed **documents** and I need exactly the same documents that appear under "Docs I'm following" in https://[YOUR TENANT]-my.sharepoint.com/personal/[USER_LOGON]/Social/FollowedContent.aspx.

The endpoint /me/drive/following is not returning any results for me.

I have several clients that are using my megamenu (application customizer for modern sites, control in masterpage for classic sites) which display this information, and they are very upset that suddenly this information is not available.

**Comment by andrewconnell** [comment] 2020-05-09 12:07
@JeremyKelley ... possible change in REST API behavior?

**Comment by andrewconnell** [comment] 2020-05-09 12:40
Dupe of #5630

**Closed** 2020-05-09 12:40 UTC
Labels: area:docs-comment, status:duplicate
