### ISSUE TITLE
spfx extension rc0 is giving error in gulp bundle 

### ISSUE THREAD

**Issue by rajeshkhetarpal** [SharePoint/sp-dev-docs#826] opened 2017-08-31 23:11 UTC
#### Category
- [ ] Question
- [ ] Typo
- [X ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
gulp bundle should work with latest RC0  update for spfx extension 

#### Observed Behavior
Getting error in gulp bundle for application customizer after upgrading to following packages 

gulp bundle error 

![image](https://user-images.githubusercontent.com/1379229/29948993-1fba67b4-8e6f-11e7-80b0-11405b038f4b.png)

mainfest.json file 
![image](https://user-images.githubusercontent.com/1379229/29948976-f7b4be72-8e6e-11e7-9d80-3e70ea17b8d6.png)

npm uninstall -g @microsoft/generator-sharepoint
npm i -g @microsoft/generator-sharepoint@latest

npm i @microsoft/sp-core-library@~1.2.0
npm i @microsoft/sp-webpart-base@~1.2.0

npm i --save @microsoft/sp-build-web@~1.2.0
npm i --save @microsoft/sp-module-interfaces@~1.2.0
npm i --save @microsoft/sp-webpart-workbench@~1.2.0

npm i @microsoft/sp-build-core-tasks@~1.2.0
npm i @microsoft/sp-application-base@~1.2.0

#### Steps to Reproduce

Upgrade following packages and create new project for application customizer and run gulp bundle

npm uninstall -g @microsoft/generator-sharepoint
npm i -g @microsoft/generator-sharepoint@latest

npm i @microsoft/sp-core-library@~1.2.0
npm i @microsoft/sp-webpart-base@~1.2.0
npm i --save @microsoft/sp-build-web@~1.2.0
npm i --save @microsoft/sp-module-interfaces@~1.2.0
npm i --save @microsoft/sp-webpart-workbench@~1.2.0
npm i @microsoft/sp-build-core-tasks@~1.2.0
npm i @microsoft/sp-application-base@~1.2.0

**Comment by Pieter-Veenstra** [comment] 2017-09-01 11:00
Which version of npm have you got installed?

please check with 
   npm -v

**Comment by rajeshkhetarpal** [comment] 2017-09-01 17:02
I am using 5.3.0 npm version

**Comment by mpasarin** [comment] 2017-09-01 20:14
Looking at the manifest, it seems like you are pointing to the wrong schema. Can you try with
`
"$schema": "https://dev.office.com/json-schemas/spfx/client-side-extension-manifest.schema.json"
`

**Comment by waldekmastykarz** [comment] 2017-09-02 13:58
One of the errors says that your alias is too long (47 chars where only 40 are allowed).

**Comment by VesaJuvonen** [comment] 2017-09-04 08:43
@rajeshkhetarpal - like pointed out my Marc and Waldek, you seem to have here two things which are causing you challenges. 

1. Schema reference is wrong - it should be pointing to dev.office.com file - you'd need to do this update manually if you are updating Dev Preview extension code. If you create a clean new extension, this setting is correctly applied.
2. Your alias is indeed also really long with duplicate string around "application customizer". You can fix this manually also in the json file, if needed.

Also, the easiest way to double check, if the issue is in Yeoman templates or in the solution structure, is simply to create a clean new extension and then see if that bundles. If that works fine, then there's something specific in the solution, like in this case. This case you seem to have created the extension with dev preview and are just missing a few more steps to get it fully updated for the 1.2.

We'd also appreciate if you'd come back and confirm the situation so that we can close this issue when the situation has been resolved. thx.

**Comment by rajeshkhetarpal** [comment] 2017-09-05 16:31
It worked after changing the alias to less than 40 character 

Schema reference didn't matter. I tried with both and it worked after changing with alias name  

Thanks for help !!

**Comment by VesaJuvonen** [comment] 2017-09-05 16:45
thx @rajeshkhetarpal for confirming that the issue is resolved. Closing this one.

**Closed by VesaJuvonen** 2017-09-05 16:45 UTC
Labels: status:waiting-for-clarification
