### ISSUE TITLE
RC0 and sp-pnp-js type script issues.

### ISSUE THREAD

**Issue by taykunats** [SharePoint/sp-dev-docs#352] opened 2017-01-16 10:09 UTC
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
Installing sp-pnp-js should allow us to use the pnp core javascript file in our webparts. 

#### Observed Behavior
When installed in the latest RC0, there are conflicts with sp-pnp-js dependencies and dependencies on the spfx framework.

#### Steps to Reproduce
Create a new project using yo
a. yo @microsoft/sharepoint
b. npm install sp-pnp-js --save
c. edit webpart code to add import pnp from 'sp-pnp-js''
c. run gulp serve

The following error will appear:
Error - typescript - node_modules\@types\core-js\index.d.ts(781,11): error TS2300: Duplicate identifier 'Promise'.
Error - typescript - node_modules\@types\core-js\index.d.ts(867,13): error TS2300: Duplicate identifier 'Promise'.
Error - typescript - node_modules\@types\es6-promise\index.d.ts(11,15): error TS
2300: Duplicate identifier 'Promise'.
Error - typescript - node_modules\@types\es6-promise\index.d.ts(42,19): error TS
2300: Duplicate identifier 'Promise'.
Error - typescript - node_modules\sp-pnp-js\lib\net\httpclient.d.ts(5,15): error
 TS2304: Cannot find name 'HeadersInit'.

**Comment by mauricionr** [comment] 2017-01-16 11:58
Check this [Similar issue](https://github.com/SharePoint/PnP-JS-Core/issues/221)

**Comment by taykunats** [comment] 2017-01-16 13:51
Checked it and it doesnt seem to be a problem with TS.

**Comment by patmill** [comment] 2017-01-16 21:08
This likely has to do with the move to using @types vs. typings.  Did you add typings via anything than npm i --save @types/*** ?

**Comment by joelfmrodrigues** [comment] 2017-01-17 19:48
@patmill no, this happens just by following the steps mentioned above. Create new project, import sp-pnp-js package and try to use it. I had the same problem last Friday, although, had no time so far to try to investigate it.
Had a quick look last Friday before leaving the office and it looked like some paths to node_modules references were wrong. Maybe an issue in the build process?

**Comment by patmill** [comment] 2017-01-17 19:56
Looking at the sp-pnp-js code, there are a bunch of typings referenced.  These are probably colliding with the @types included.  @patrick-rodgers - we might need to tweak the package a bit / migrate to @types, or ???

**Comment by joelfmrodrigues** [comment] 2017-01-17 20:35
looking for modules in C:\node_modules
    module variation @microsoft/loader-source-map-loader
      C:\node_modules\@microsoft doesn't exist (module as directory)
    module variation source-map-loader-webpack-loader
      resolve 'file' source-map-loader-webpack-loader in C:\node_modules
        resolve file
          C:\node_modules\source-map-loader-webpack-loader doesn't exist
          C:\node_modules\source-map-loader-webpack-loader.webpack-loader.js doesn't exist
          C:\node_modules\source-map-loader-webpack-loader.web-loader.js doesn't exist
          C:\node_modules\source-map-loader-webpack-loader.loader.js doesn't exist
          C:\node_modules\source-map-loader-webpack-loader.js doesn't exist
      C:\node_modules\source-map-loader-webpack-loader doesn't exist (module as directory)
    module variation source-map-loader-web-loader
      resolve 'file' source-map-loader-web-loader in C:\node_modules
        resolve file
          C:\node_modules\source-map-loader-web-loader doesn't exist
          C:\node_modules\source-map-loader-web-loader.webpack-loader.js doesn't exist
          C:\node_modules\source-map-loader-web-loader.web-loader.js doesn't exist
          C:\node_modules\source-map-loader-web-loader.loader.js doesn't exist
          C:\node_modules\source-map-loader-web-loader.js doesn't exist
      C:\node_modules\source-map-loader-web-loader doesn't exist (module as directory)
    module variation source-map-loader-loader
      resolve 'file' source-map-loader-loader in C:\node_modules
        resolve file
          C:\node_modules\source-map-loader-loader doesn't exist
          C:\node_modules\source-map-loader-loader.webpack-loader.js doesn't exist
          C:\node_modules\source-map-loader-loader.web-loader.js doesn't exist
          C:\node_modules\source-map-loader-loader.loader.js doesn't exist
          C:\node_modules\source-map-loader-loader.js doesn't exist
      C:\node_modules\source-map-loader-loader doesn't exist (module as directory)
    module variation source-map-loader
      resolve 'file' source-map-loader in C:\node_modules
        resolve file
          C:\node_modules\source-map-loader doesn't exist
          C:\node_modules\source-map-loader.webpack-loader.js doesn't exist
          C:\node_modules\source-map-loader.web-loader.js doesn't exist
          C:\node_modules\source-map-loader.loader.js doesn't exist
          C:\node_modules\source-map-loader.js doesn't exist
      C:\node_modules\source-map-loader doesn't exist (module as directory)

**Comment by joelfmrodrigues** [comment] 2017-01-17 21:04
(Sorry fort the spam...)
I wonder if the error is actually caused by sp-pnp-js?
This is also extracted from the errors: "node_modules\source-map-loader-loader doesn't exist"
note the -loader-loader ....doesn't look good to me
Could it be a configuration bug on the SharePoint Framework? This looks like a similar issue: 
[https://github.com/jtangelder/sass-loader/issues/204](url)

**Comment by joelfmrodrigues** [comment] 2017-01-20 22:33
@taykunats have a look on [this](https://github.com/SharePoint/PnP-JS-Core/issues/304) related issue from the PnP-JS-Core repo.
There is a dev branch that works with the SharePoint framework. Just wait for it to be merged into master :)

**Comment by chakkaradeep** [comment] 2017-02-08 14:49
I believe @patrick-rodgers has a pushed a fix to sp-pnp-js on using types. @patrick-rodgers can you confirm if this is handled? Thanks!

**Comment by patrick-rodgers** [comment] 2017-02-21 14:26
Hi all, sorry for some reason I missed that I was tagged here. This should now be fixed and working with >= 2.0.0 of sp-pnp-js and RC0. Is anyone still having issues with the latest or can we close this?

**Comment by patrick-rodgers** [comment] 2017-02-22 18:52
Closing this as fixed. Sorry I didn't see the thread earlier. [ref](https://github.com/SharePoint/PnP-JS-Core/issues/221)

**Closed by patrick-rodgers** 2017-02-22 18:52 UTC
Labels: type:discussion
