### ISSUE TITLE
SPFx ListViewCommandSet iconImageUrl is not rendered in WebParts

### ISSUE THREAD

**Issue by barisbikmaz** [SharePoint/sp-dev-docs#3888] opened 2019-05-06 14:48 UTC
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

The configured iconImageUrl of the ListViewCommandSet should be rendered when inserting a list as WebPart into a page.

#### Observed Behavior

Title of the commandset is rendered but the icon is missing (only in WebParts)
![image](https://user-images.githubusercontent.com/6338132/57233049-33afcd80-701e-11e9-8024-809507cd1256.png)

#### Steps to Reproduce

Spfx 1.8

1. Create a command set for lists with "iconImageUrl": "data:image/png;base64,....."
2. Deploy the solution globally.
3. Create a page
4. Insert a list as WebPart
5. Observe that the icon is missing.

**Comment by andrewconnell** [comment] 2019-05-07 21:50
This (_images in the command set buttons_) is sort of a known issue that MSFT is tracking... see #2684 as just one, as well as base64 encoded ones (#1574, #1834, #2169).

Closing this as a dupe as the issue is being tracked in a few places... suggest you subscribe to those for updates...

**Closed by andrewconnell** 2019-05-07 21:50 UTC
Labels: area:framework, status:duplicate, type:bug
