### ISSUE TITLE
Getting an error on any page where SPFx is used

### ISSUE THREAD

**Issue by shaipetel** [SharePoint/sp-dev-docs#1084] opened 2017-11-24 20:27 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Page should load with no errors

#### Observed Behavior
On any page that I have SPFx web parts, the web part code is working with no errors reported, but in console I always see this error:
Sys.InvalidOperationException: Operation is not valid due to the current state of the object.
Coming from https://r1.res.office365.com/o365/versionless/shellcoreprimeg2m_a17081f3.js
From this trace:
shellcoreprimeg2m_a17081f3.js:20 Uncaught Error: Sys.InvalidOperationException: Operation is not valid due to the current state of the object.
    at Function.Error.create (shellcoreming2am_690f83ae.js:65)
    at Function.Error.invalidOperation (shellcoreming2am_690f83ae.js:137)
    at Function._o365cl.a.b (shellcoreming2am_690f83ae.js:2479)
    at _o365sg2c.s.b.f (shellcoreprimeg2m_a17081f3.js:20)
    at _o365sg2c.s.a (shellcoreprimeg2m_a17081f3.js:20)
    at Function.O365Shell.InvokeSuiteAPILoaded (shellcoreprimeg2m_a17081f3.js:22)
    at _o365sg2p.Loader.h (shellplusg2m_29bf5d35.js:36)

I am just wondering, is it only me? Anyone else getting this error?
Does it have to do with which version my SPFx components were built on?

#### Steps to Reproduce
Visit any modern page and throw any SPFx web part on the page

**Comment by kmarwen** [comment] 2017-11-27 10:18
Since a couple of days I also have this same error on console

**Comment by shaipetel** [comment] 2017-11-27 16:36
@kmarwen Good to know I'm not the only one. Just started one day and we didn't make any changes to our SPFx project.
I am very positive its not from our code, we just started seeing it a few weeks ago and it seems every once in a while there is a different error coming up in the console.

**Comment by kmarwen** [comment] 2017-11-28 09:13
Thank you @VesaJuvonen for adding this to bugs list
but today we have new errors : 

![image](https://user-images.githubusercontent.com/3084807/33311104-0e8c2400-d424-11e7-987d-c72f603df0fc.png)

the blocking part is when adding multiple webparts using jquery in same page, 
one or more of these webparts throw an "uncaught" error for jquery plugin, 

![image](https://user-images.githubusercontent.com/3084807/33311304-ae19e6a6-d424-11e7-9d03-a76f717ccbe0.png)


I tried many options : SPloader, document.ready, ... 

I think it's an issue in spfx and specially in webpack

thx

**Comment by VesaJuvonen** [comment] 2017-11-28 11:33
Hi @kmarwen, since this seems to be a separate bug than what @shaipetel has reported, would recommend opening up a separate issue from tracking perspective. In @shaipetel's case issue was not blocking, but you seem to include that there's a "blocking" part with these errors, so this is clearly a new issue and we would need to understand more detailed on the setup to be able to reproduce the issue.

**Comment by andrewconnell** [comment] 2019-02-01 11:39
Been a long time since this was posted... still an issue or resolved by updates in the last 12mo+?

**Closed** 2019-02-15 13:00 UTC
Labels: Needs: Author Feedback, area:framework, no-recent-activity, status:to-be-reviewed, type:bug
