### ISSUE TITLE
SPFx 1.9.1: Entry point of library component bundle is not /lib/index.js anymore

### ISSUE THREAD

**Issue by vman** [SharePoint/sp-dev-docs#4570] opened 2019-08-31 16:42 UTC
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

For an SPFx library component bundle, the entry point in the `config/config.json` should be the `/lib/index.js` file:

```json
"bundles": {
    "my-custom-library": {
      "components": [
        {
          "entrypoint": "./lib/index.js",
          "manifest": "./src/CustomOfficeUiFabricLibrary.manifest.json"
        }
      ]
    }
  },
```

#### Observed Behavior

In `1.8.2-plusbeta` if a library component was created, the `config/config.json` had the bundle defined as:
```json
"bundles": {
    "my-custom-library": {
      "components": [
        {
          "entrypoint": "./lib/index.js",
          "manifest": "./src/CustomOfficeUiFabricLibrary.manifest.json"
        }
      ]
    }
  },
```

Since `1.9.1` the bundle entrypoint is now the default exported class:

```json
"bundles": {
    "my-custom-library": {
      "components": [
        {
          "entrypoint": "./lib/libraries/customOfficeUiFabric/CustomOfficeUiFabricLibrary.js",
          "manifest": "./src/libraries/customOfficeUiFabric/CustomOfficeUiFabricLibrary.manifest.json"
        }
      ]
    }
  },
```

So if we add any more components to the library like this:

![image](https://user-images.githubusercontent.com/173794/64066727-470e2680-cc15-11e9-9477-d168cc5a3121.png)

and then add the export to the `index.ts` file:
```ts
export { ButtonComponent } from './customFabric/ButtonComponent';
```
The components does not get included in the final bundle because the bundle entry point is pointing to the default class.

#### Steps to Reproduce

Create a library component project with SPFx generator version `1.9.1` and observe the `config/config.json` file

Thanks for your contribution! Sharing is caring.

**Comment by kemesfun** [comment] 2020-01-31 22:47
@vman Have you tried adding this to the index.ts : 
``export { ButtonComponent } from './libraries/customFabric/ButtonComponent'`` 
This seems to be by design that you have to export from from `` ./libraries/<folder-name>/<components>/SomeComponent';``

**Comment by kemesfun** [comment] 2020-02-13 23:22
@vman We have fixed this issue and it will be part of the next release.

**Closed by kemesfun** 2020-02-13 23:22 UTC
Labels: area:spfx-general, status:to-be-reviewed, type:question
