### ISSUE TITLE
SPFX extension are loading slow (flickering )

### ISSUE THREAD

**Issue by spo365** [SharePoint/sp-dev-docs#5637] opened 2020-04-29 06:09 UTC
## Category

- [x] Bug

## Describe the bug

created a SPFx app customizer to hide a certain section in the pages. But due to the delay, the sections load first and then get hidden.
## Steps to reproduce

> **DELETE THIS LINE BEFORE SUBMITTING** - Provide steps to reproduce the behavior:

public onInit(): Promise<void> {
   kept my all logic to hide component in this block.
   }
}

## Expected behavior
Hide the field or add custom without any delay or flickering

**Comment by bcameron1231** [comment] 2020-04-29 14:23
Hi, could you provide a bit more information? Are you trying to use an SPFx Application Customizer to do DOM Manipulation to hide components in the page? If so, this isn't really a _supported_ scenario, and it's not recommended to do so either as the DOM has the ability (and will) change in SharePoint Online.

As far as the timing of the loading, this is by design due to how the page loads the js files. The DOM loads and then the SPFx Extensions are loaded after.

**Comment by spo365** [comment] 2020-04-29 14:40
Hi, 
Thanks for your reply. 
As we are creating custom button in the SharePoint library  Column in order to perform some activity in data. However due to delay issue It loads the custom button after 10 seconds before that column shows blank.

**Comment by bcameron1231** [comment] 2020-04-29 14:54
Alright. Could you please update your original post with your environment details? 

- **OS**: [e.g. Windows 10 | MacOS 10.15.x]
- **Target Environment**: [e.g. SharePoint Server 2016 | SharePoint Server 2019 | SharePoint Online]
- **Framework**: [e.g. .NET Framework v3.x | .NET Core v3.x | Node.js v6/v8/v10/v12]
- **Browser(s)**: [e.g. Chrome v79 | Safari v22 | FireFox v31 | IE v11 | Edge | Chromium Edge v79]
- **Tooling**: [e.g. VS Code | SPFx v1.10.0 | Visual Studio 2019]
- **Additional details**: *The more context you can provide, the easier it is (and therefore quicker) to help.*

Second, could you provide some more details on what you are trying to do? Also, you mentioned you created an **App Customizer.** Are you sure that's what you've built, and you aren't using a **Field Customizer?** Based on what you mentioned above, it sounds like a Field Customizer scenario.

**Comment by spo365** [comment] 2020-04-29 22:35
OS: [e.g. Windows 10 
Target Environment:  SharePoint Online
Framework: Node.js v10
Browser(s): [. Chrome v79 |  IE v11 | Edge ]
Tooling: [ VS Code]
Additional details: We have created both App Customizer & Field  Customizer 
**App Customizer :-** To hide suite-bar-ribbon-on-modern-sharepoint-site and some buttons from sp page.
**Issue :-** Delay and flickering while hiding the ribbon (Approximate 4 second)
**Field  Customizer :-** To show gear option with multiple values in order to trigger power automate process.
**Issue :-** Loading time is 8 second in Field  Customizer in columns.

**Comment by bcameron1231** [comment] 2020-04-29 22:46
Thank you for updating your information. I'd like to address the customizations you are making. 

First, with application customizer. The flicker you are seeing is actually intended behavior. The app customizer loads after the original DOM loaded. Also note, trying to hide the ribbon through this process technically isn't a supported customization. 

To you field customizer, can you expand a little bit more on what you mean by 

> show gear option with multiple values in order to trigger power automate process.

Its a bit unclear as to what you are doing. It shouldn't take 8 seconds for a field customizer to load. If you could expand on what you are doing, that would be helpful. Any source code you could provide would also be helpful. Thanks!

**Comment by spo365** [comment] 2020-04-29 23:18
Apologies, let me explain you in details.
Please refer below image we have created column name :- settings in that we applied extension which give two option in order to trigger two different power automate flow. 
For example : when user will click on workflow 1 form will open after enter values date will be save in item after that it will trigger a flow.

![image](https://user-images.githubusercontent.com/5062256/80655662-979a9400-8ac2-11ea-8350-11a186063f28.png)

**Comment by bcameron1231** [comment] 2020-04-29 23:49
Thanks for the update. That's very curious, is there any logic in your extension that runs before rendering, or does it just output the Gear Icon by default? Are the options for the Workflows options static?

**Comment by spo365** [comment] 2020-04-30 00:03
Yes basically intention of creating this icons bcoz user don't want to navigate under multiple power automate layer to trigger a flow and also they don't like default power automate form due to that we have create extension. 
Basically when user click on gear they select one of workflow option which popup some field when they provide there input and save the form. It trigger flow on document property change.

**Comment by patmill** [comment] 2021-11-10 00:07
The metadata updated brought this up.  I'm going to close it, as the code here (hiding and manipulating DOM elements on the page.) is unsupported.

**Closed** 2021-11-10 19:38 UTC
Labels: area:spfx, Needs: Attention :wave:, area:spfx-extensions, Needs: Context Detail :question:
