### ISSUE TITLE
SPFx Web Part will not compile - lodash errors occur

### ISSUE THREAD

**Issue by TBag** [SharePoint/sp-dev-docs#397] opened 2017-01-31 13:45 UTC
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
Generator creates web part that can successfully compile when No framework is chosen.

#### Observed Behavior
Generator creates web part that cannot successfully compile when No framework is chosen.

#### Steps to Reproduce

Run generator
Create web part with No javascript web framework
gulp serve

Get these errors:

C:\ToddSPFx\SPFxFlowEmail>gulp serve
Build target: DEBUG
[08:33:14] Using gulpfile C:\ToddSPFx\SPFxFlowEmail\gulpfile.js
(node:8588) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[08:33:14] Starting gulp
[08:33:14] Starting 'serve'...
[08:33:14] Starting subtask 'pre-copy'...
[08:33:14] Finished subtask 'pre-copy' after 19 ms
[08:33:14] Starting subtask 'copyStaticAssets'...
[08:33:14] Starting subtask 'sass'...
[08:33:16] Finished subtask 'copyStaticAssets' after 1.79 s
[08:33:16] Finished subtask 'sass' after 1.78 s
[08:33:16] Starting subtask 'tslint'...
[08:33:16] Starting subtask 'typescript'...
[08:33:16] [typescript] Using custom version: 2.0.10
[08:33:20] Error - typescript - node_modules\@types\lodash\index.d.ts(11444,21): error TS1005: ']' expected.
[08:33:20] Error - typescript - node_modules\@types\lodash\index.d.ts(11444,22): error TS1005: ';' expected.
[08:33:20] Error - typescript - node_modules\@types\lodash\index.d.ts(11444,23): error TS1128: Declaration or statement expected.
[08:33:20] Error - typescript - node_modules\@types\lodash\index.d.ts(11444,33): error TS1005: ']' expected.
[08:33:20] Error - typescript - node_modules\@types\lodash\index.d.ts(11444,34): error TS1005: ')' expected.
[08:33:20] Error - typescript - node_modules\@types\lodash\index.d.ts(11444,35): error TS1128: Declaration or statement expected.
[08:33:20] Error - typescript - node_modules\@types\lodash\index.d.ts(11444,37): error TS1128: Declaration or statement expected.
[08:33:20] Error - typescript - node_modules\@types\lodash\index.d.ts(19441,1): error TS1128: Declaration or statement expected.
[08:33:20] Finished subtask 'tslint' after 3.89 s
[08:33:20] Error - 'typescript' sub task errored after 3.89 s
 "TypeScript error(s) occurred."
[08:33:20] 'serve' errored after 5.72 s
[08:33:20]
[08:33:20] ==================[ Finished ]==================
Error - typescript - node_modules\@types\lodash\index.d.ts(11444,21): error TS1005: ']' expected.
Error - typescript - node_modules\@types\lodash\index.d.ts(11444,22): error TS1005: ';' expected.
Error - typescript - node_modules\@types\lodash\index.d.ts(11444,23): error TS1128: Declaration or statement expected.
Error - typescript - node_modules\@types\lodash\index.d.ts(11444,33): error TS1005: ']' expected.
Error - typescript - node_modules\@types\lodash\index.d.ts(11444,34): error TS1005: ')' expected.
Error - typescript - node_modules\@types\lodash\index.d.ts(11444,35): error TS1128: Declaration or statement expected.
Error - typescript - node_modules\@types\lodash\index.d.ts(11444,37): error TS1128: Declaration or statement expected.
Error - typescript - node_modules\@types\lodash\index.d.ts(19441,1): error TS1128: Declaration or statement expected.
Error - 'typescript' sub task errored after 3.89 s
 "TypeScript error(s) occurred."
[08:33:21] Project sp-fx-flow-email version: 0.0.1
[08:33:21] Build tools version: 1.1.0
[08:33:21] Node version: v7.0.0
[08:33:21] Total duration: 11 s
[08:33:21] Task errors: 9

**Comment by andrewconnell** [comment] 2017-01-31 15:34
Dupe... see #394 for temp resolution

**Comment by TBag** [comment] 2017-01-31 17:50
@andrewconnell Thanks, **npm install @types/lodash@4.14.50** fixes this error too.

**Comment by andrewconnell** [comment] 2017-01-31 20:26
Uh… that’s the fix I was referring to ☺

**Comment by TBag** [comment] 2017-01-31 20:30
Yeah, exactly.  I put it in the comments to help other people find it quickly if they hit the same error I reported.

**Comment by chakkaradeep** [comment] 2017-02-01 18:20
Closing this as this is a dupe of #394.

**Closed** 2017-02-01 18:20 UTC
