### ISSUE TITLE
SPFx 1.10 Personal App doesn't load in Teams mobile app

### ISSUE THREAD

**Issue by NickSevens** [SharePoint/sp-dev-docs#5279] opened 2020-02-04 09:44 UTC
## Category

- [x] Bug

## Describe the bug

When adding an SPFx 1.10 webparts as a personal app in Teams, the app doesn't load in the Teams mobile client. (with developer preview enabled)
Instead, the application redirects to the SharePoint homepage, and not the specified component.

**Comment by andrewconnell** [comment] 2020-02-06 22:54
Apparently, this is a known regression in the Teams app & a fix is rolling "soon"... unfortunately, I'm not sure what the exact ETA is.

Since this is not a SharePoint issue, I'm going to close this but if it isn't fixed after a while, feel free to reopen.

**Closed by andrewconnell** 2020-02-06 22:54 UTC
Labels: area:spfx-msteams, status:fixed-next-drop, type:bug-confirmed

**Comment by NickSevens** [comment] 2020-02-07 08:56
Noted. :) Thanks for the update @andrewconnell
