### ISSUE TITLE
React Dialog - OnAfterClose breaks subsequent dialogs

### ISSUE THREAD

**Issue by majidali** [SharePoint/sp-dev-docs#3698] opened 2019-03-28 10:21 UTC
I have implemented custom dialog using documentation here. 

https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/guidance/using-custom-dialogs-with-spfx

Everything works fine in Edge and Chrome however when I tested in IE11 it breaks on submit event with this exception. Further debugging highlighted that it breaks when unmountComponentAtNode(this.domElement) is called. I have pasted snipped below. If I don't use try catch then subsequent dialog doesn't render. Dialog.alert will also not work after the exception is thrown. 

protected onAfterClose(): void {
      super.onAfterClose();
      // Clean up the element for the next dialog
      try{
      ReactDOM.unmountComponentAtNode(this.domElement);
      }
      catch(ex){
        console.log(ex);
      }
    }

Exception: 

NotFoundError
   {
      [functions]: ,
      __proto__: { },
      ABORT_ERR: 20,
      code: 8,
      constructor: { },
      DATA_CLONE_ERR: 25,
      DOMSTRING_SIZE_ERR: 2,
      HIERARCHY_REQUEST_ERR: 3,
      INDEX_SIZE_ERR: 1,
      INUSE_ATTRIBUTE_ERR: 10,
      INVALID_ACCESS_ERR: 15,
      INVALID_CHARACTER_ERR: 5,
      INVALID_MODIFICATION_ERR: 13,
      INVALID_NODE_TYPE_ERR: 24,
      INVALID_STATE_ERR: 11,
      message: "NotFoundError",
      name: "NotFoundError",
      NAMESPACE_ERR: 14,
      NETWORK_ERR: 19,
      NO_DATA_ALLOWED_ERR: 6,
      NO_MODIFICATION_ALLOWED_ERR: 7,
      NOT_FOUND_ERR: 8,
      NOT_SUPPORTED_ERR: 9,
      PARSE_ERR: 81,
      QUOTA_EXCEEDED_ERR: 22,
      SECURITY_ERR: 18,
      SERIALIZE_ERR: 82,
      SYNTAX_ERR: 12,
      TIMEOUT_ERR: 23,
      TYPE_MISMATCH_ERR: 17,
      URL_MISMATCH_ERR: 21,
      VALIDATION_ERR: 16,
      WRONG_DOCUMENT_ERR: 4
   }

The close event works fine!

**Comment by andrewconnell** [comment] 2019-03-29 21:56
Few questions:
- what version of SPFx?
- what version of Fabric React?
- have you tried the dialog outside of an SPFx component? 

This might be specific to Fabric React controls and not SPFx, thus it might be better to post the issue to their issue list: https://github.com/OfficeDev/office-ui-fabric-react/issues

**Comment by majidali** [comment] 2019-04-03 13:52
thanks for getting back! 

version are 
Fabric React: 16.3.2
SPFx: 1.7.1

No , I haven't tried outside of SPFx component.

**Comment by andrewconnell** [comment] 2019-04-03 14:21
@majidali ... please confirm versions... there's no Fabric React v16... I think you referenced React in your response...

Assuming you're in Fabric React v5.* as the version of React & SPFx you're using is not the current version of Fabric React (v6). SPFx v1.8 supports the latest version of Fabric React (v6) which very well may include the fix. 

I think you're best to post the issue to the [OfficeDev/office-ui-fabric-react](https://github.com/OfficeDev/office-ui-fabric-react) repo's issue list to first verify the issue is specific to SharePoint / SharePoint Framework. If it's an IE11 issue, it's likely related to Fabric React... not something the SharePoint team could address... make sense?

**Comment by majidali** [comment] 2019-04-05 12:19
@andrewconnell  fabric react verison is 5.131.0... I have managed to find the work around by not using closing event in submit, instead I process my logic inside component and user clicks close button when the logic is completed.

I simply followed this documentation and tested in IE11, the different in my implementation is that I'm using slightly different html to render along with some public properties in class(to feed back to caller , no longer case though)...

https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api



The reason for my post here was - I simply followed instructions using guideliness

**Comment by andrewconnell** [comment] 2019-04-09 09:55
I'll take a look at the docs to see if we need to get those updated.

There were well-known issues with the Dialog framework in Fabric React v5.* so this wouldn't be surprising. These were fixed in v6 so upgrading to v6 might be a good solution...

Thanks for bringing this to our attention.

**Comment by andrewconnell** [comment] 2019-06-03 22:02
I don't think anything else is needed for this doc. The code in the doc is meant as an example to show command sets and opening a dialog. If there is an exception in the handler of the close event due to more complex code written beyond what's shown in this sample, then a more robust `then{} catch(){}` block should be implemented than what is shown in the current promise implementation.

**Closed by andrewconnell** 2019-06-03 22:02 UTC
Labels: area:docs, area:fabric, area:framework
