### ISSUE TITLE
Issue with Gulp-build for newly added webpart

### ISSUE THREAD

**Issue by kspranesh** [SharePoint/sp-dev-docs#865] opened 2017-09-19 22:10 UTC
#### Expected or Desired Behavior
i execute gulp-build for the SPfx project that i have created and i expect it to build successfully

#### Observed Behavior
 Gulp-build executes for couple of minutes and throws error 

Error - 'tslint' sub task errored after 1.16 s
 FatalError in plugin 'gulp-cache'
Message:

Invalid source file: C:/myproject/src/webparts/estimate/EstimateWebPart.d.ts. Ensure that the files supplied to lint have a .ts,
.tsx, .d.ts, .js or .jsx extension.

Details:
    innerError: undefined

![spfx-issue](https://user-images.githubusercontent.com/12847736/30617647-08a6400c-9d65-11e7-9734-1b1c9b6bb134.jpg)

#### Steps to Reproduce
Create a new SPFX react webpart project
 Open the project in visual studio code
open the powershell console in the visual studio code or open node command prompt
enter gulp build/ gulp bundle/gulp serve
the build process errors out 

**Environment Version Details** 

microsoft/generator-sharepoint@1.2.0
+-- gulp@3.9.1
+-- tslint@5.7.0
+-- typescript@2.5.2
`-- yo@2.0.0

**Comment by iclanton** [comment] 2017-09-19 22:59
@nickpape-msft for more background on TSLint.

Does that file exist? It's a little unusual to have a `*.D.TS` file in your `src` directory. Should it be referenced as a `typeRoot` in your `tsconfig.json` instead?

**Comment by kspranesh** [comment] 2017-09-20 00:58
Yes, the file does exist in the path specified in the error and this file is auto generated with the template.

**Comment by iclanton** [comment] 2017-09-20 19:09
What template engine is autogenerating it?

**Comment by georgemak** [comment] 2017-10-03 10:45
Hello, 
I am having exact same issue, .d.ts file exists and seems to be ok. 

I generated the webpart using yeoman and without editing anything it throws this error.

**Comment by georgemak** [comment] 2017-10-03 11:14
Tested the whole process again and it works now, so possibly some glitch happened during the installation of packages (gulp-cache is the package that threw the error).

**Comment by iclanton** [comment] 2017-10-25 22:57
It sounds like this isn't a problem anymore, so I'm going to close this issue. If you see this again, feel free to reopen this.

**Closed by iclanton** 2017-10-25 22:57 UTC
Labels: status:discussion, status:waiting-for-clarification, type:discussion

**Comment by jasonarden** [comment] 2017-11-15 19:52
Just adding some additional info. This was caused by having declaration: true in the tsconfig.json . No action required, but incase someone else runs into it.  I saw this after playing around with tsc and a watch event.

-J
