### ISSUE TITLE
SiteID now is SiteId ??????????

### ISSUE THREAD

**Issue by MagtheRag** [SharePoint/sp-dev-docs#4785] opened 2019-10-18 11:29 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
When search through the rest api as in '/_api/search' then I expect that the properties of each search row object is presented in the same way and not change casing suddenly so that the code that we have IN PRODUCTION breaks as we do not find the property we are looking for.

#### Observed Behavior
In Target release tenant the response has changed when selecting the SiteID to SiteId.

#### Steps to Reproduce
Do a search in a target release tenant
[tentant]/_api/search/query?querytext=%27*%27&selectproperties=%27SiteID%27

#### Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by andrewconnell** [comment] 2019-10-20 10:33
I'm not clear... what are you seeing that's different? I ran the same query in two tenants, one SR & one TR and the results are the same...

**Comment by CPritch** [comment] 2019-10-21 12:27
I can confirm repro following @MagtheRag repro steps. The response from a developer tenant is that 'SiteID' has now become 'SiteId'. A tenancy not on first-release responds with the key 'SiteID' for the request as described.

**Comment by andrewconnell** [comment] 2019-10-21 13:21
I'm still not clear... sorry, maybe I'm a little dense on this one, but I don't see the difference or what the "error" is as when I run the same query for the same two properties, **SiteID** or **SiteId** on an SR & TR tenant, I'm getting the same response back for both.

I wasn't familiar with the property being `SiteID` previously, but when I query for **SiteID** or **SiteId**, I'm getting the same response... so the casing isn't changing an issue. 

So... what exactly is the issue?

**Comment by CPritch** [comment] 2019-10-21 13:24
Yes the casing is changing. I can get more details on the affected tenants if you need that. SiteID was being returned for our UK production tenants from when I last tested this.

**Comment by andrewconnell** [comment] 2019-10-21 13:28
You're missing the point of my comment: **what is the exact problem**. The OP provides an API to get a property. When you change the query to either of the values, you get the same result. 

So, my impression is that the OP is calling out you get different results based on the casing used. My point: that's not what I'm seeing & thus, can't repro any issue. Thus my "not clear" comment & label on the issue.

If that's not the correct problem, it needs to be restated / explicitly stated.

**Comment by MagtheRag** [comment] 2019-10-21 14:08
The problem is when you have an app that reads from the properties and assume that the property should be SiteID then it does not exist and you will not find that property on the object that is returned. It is not that we are trying to query for the site id. We want to fetch it.
<img width="749" alt="Screenshot 2019-10-21 at 16 00 57" src="https://user-images.githubusercontent.com/7849138/67212569-d9b09200-f41c-11e9-9d81-08d6e1d0e1f7.png">
<img width="738" alt="Screenshot 2019-10-21 at 16 04 11" src="https://user-images.githubusercontent.com/7849138/67212581-dfa67300-f41c-11e9-871e-ea1756d4e38e.png">

**Comment by andrewconnell** [comment] 2019-10-21 14:42
This helps @MagtheRag, thanks. I thought the issue was related to the query you were running.

**Comment by CPritch** [comment] 2019-10-21 14:43
> 
> 
> You're missing the point of my comment: **what is the exact problem**. The OP provides an API to get a property. When you change the query to either of the values, you get the same result.
> 
> So, my impression is that the OP is calling out you get different results based on the casing used. My point: that's not what I'm seeing & thus, can't repro any issue. Thus my "not clear" comment & label on the issue.
> 
> If that's not the correct problem, it needs to be restated / explicitly stated.

I am saying your interpretation is incorrect @andrewconnell . The issue is that in production tenants the key is SiteID. In dev and first-release tenants the key is SiteId. The key has recently changed in first-release tenants. You can confirm this difference by performing the repro steps between a dev tenant and a production tenant.

The answer to prevent this causing issue in production code is to not use first-release for production environments. I still believe that this is an issue as the key should not have changed without being warned of breaking changes.

**Comment by andrewconnell** [comment] 2019-10-21 14:54
@CPritch said
> I am saying your interpretation is incorrect

Yup... I get that now :) But, this isn't true & what was triggering me to keep asking questions:

> You can confirm this difference by performing the repro steps between a dev tenant and a production tenant.

There's no difference between "dev" & "production" tenants... they are all tenants. What does make this different is targetted release / standard release? What I was saying is that I wasn't seen an issue with the difference in the querys I was running among a handful of my tenants, some TR & some SR. 

Regardless, the problem was the issue wasn't clear from the OP, while I thought it was the query results. We're on track now

> The answer to prevent this causing issue in production code is clearly not to use first-release for production environments.

Correct... this has been the guidance from day 1. TR is what you'll see in SR in a few weeks... guidance has been to use TR environments as a test/canary for upcoming changes.

**Comment by wobba** [comment] 2019-10-21 17:58
@MagtheRag I'll try to repro and track this one down.

**Comment by karolikl** [comment] 2019-10-22 08:20
@MagtheRag & @CPritch: 

Thank you for notifying us of this bug! This was not an intentional change, our intention is to keep the casing as it has been all along, but this bug appeared in a flight that was enabled on First Release tenants last week. Standard Release tenants are unaffected.  

Our dev team has checked in a fix for this today and it will roll-out to First Release by end of the week. If this bug is causing major issues for your First Release tenants, please send me an overview of which tenants those are and we will disable the flight for those. Email: karolikl@microsoft.com

**Comment by andrewconnell** [comment] 2019-10-22 20:57
@karolikl / @wobba can you follow up here when the fix has rolled out so we can close this accordingly? Feel free to mention me with the hashtag "please-close"

**Comment by MagtheRag** [comment] 2019-10-23 05:23
I have fixed a work-around in our search abstraction layer if any of these mistakes would happen again. But good that this issue will have your attention and that you ensure that it is not rolled out to the standard release tenants where most of our customer is at.

**Comment by karolikl** [comment] 2019-10-28 08:48
This fix is now fully rolled out, @andrewconnell. Feel free to close this issue.

**Closed** 2019-10-28 09:16 UTC
Labels: area:csom/rest, status:fixed-next-drop, type:bug-confirmed
