### ISSUE TITLE
SPFx 1.10.0, msGraphClient, SharePoint Full Page as a Tab in MS Teams doesn’t work.

### ISSUE THREAD

**Issue by gaikwaduc** [SharePoint/sp-dev-docs#5164] opened 2020-01-18 02:48 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

msGraphClient calls should work when we add SharePoint Page as a Tab in Ms Teams. 

#### Observed Behavior

When we access SharePoint page (having SPFx 1.10.0 and msGraphClient calls) outside the Teams, it works as expected. However, when we add the same page as a Tab in Ms Teams it doesn’t work in the browser as well as in Desktop client.

**Error**:
Refused to display 'https://myorg-app.sharepoint.com/_forms/spfxsinglesignon.aspx... ... ...' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

Token renewal operation failed due to timeout

CALL STACK:
Error: Token renewal operation failed due to timeout
    at Array.<anonymous> (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-10-18.027/teams-web-part-application-assembly_default_c630174accea338c987cda5dc34553ec.js:20:89032)
    at Object._callBackMappedToRenewStates.<computed>._callBackMappedToRenewStates.<computed> (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-10-18.027/chunk.vendors~sp-http-adal_6a29bd503d1db27efc57.js:1:7704)
    at https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-10-18.027/chunk.vendors~sp-http-adal_6a29bd503d1db27efc57.js:1:10166

Ms Teams is blocking some scripts in a process of token renewal operation for SPFx msGraphClient API. I tried by adding valid domains but didn’t succeed.

"validDomains": [
    "*.login.microsoftonline.com",
    "*.sharepoint.com",
    "*.sharepoint-df.com",
    "spoppe-a.akamaihd.net",
    "spoprod-a.akamaihd.net",
    "resourceseng.blob.core.windows.net",
    "msft.spoppe.com",
    "graph.microsoft.com",
    "login.windows.net",
    "static.sharepointonline.com",
    "login.microsoftonline.com",
    "*.outlook.com",
    "*.office365.com"]

**WebPart.Manifest.json**
"supportedHosts": ["SharePointWebPart", "TeamsTab", "**SharePointFullPage**"]
**Package-solution.json**
"isDomainIsolated": false,
    "webApiPermissionRequests": [  
      {  
        "resource": "Microsoft Graph",  
        "scope": "User.ReadBasic.All"  
      },
      {
        "resource": "Microsoft Graph",
        "scope": "User.Read"
      }
    ]

#### Steps to Reproduce

1. Build SPFx 1.10.0 WebPart with any msGraphClient call API.
2. Add supported host "SharePointFullPage"
3. Create App Page
4. Add a page as a Tab in Ms Teams using Postman

Post:  https://graph.microsoft.com/v1.0/teams/team-id/channels/channel-id/tabs
Body: 
{
  "displayName": "Gamify",
  "teamsApp@odata.bind" : "https://graph.microsoft.com/v1.0/appCatalogs/teamsApps('2a527703-1f6f-4559-a332-d8a7d288cd88')",
   "configuration": {
    "entityId": null,
    "contentUrl": "https://myorg.sharepoint.com/sites/sampleSite/SitePages/teamPage.aspx",
    "websiteUrl": null,
    "removeUrl": null
  }
}

Thanks for your contribution! Sharing is caring.

**Comment by andrewconnell** [comment] 2020-01-18 11:04
Believe this is a dupe of #4892 which is ack'd as a known bug from MSFT & they are working on it. As such, I'll close this issue as a dupe as we try to consolidate related issues to a single instance.

**Closed** 2020-01-18 11:04 UTC
Labels: status:duplicate
