### ISSUE TITLE
ClientSideInstance.xml referencing within package-solution.json

### ISSUE THREAD

**Issue by johnnycardy** [SharePoint/sp-dev-docs#6707] opened 2021-02-13 18:43 UTC
With regard to this quote:

> ClientSideInstance.xml file is also referenced in the package-solution.json, so that it's included inside of the *.sppkg file, when you package your solution.

It sounds as though it should be there, by default. In fact, it must be added to the `elementManifests` array.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e41df74-a651-cfa5-a538-9397e6793f52
* Version Independent ID: 9f272325-fdb3-68e3-634b-e7428128f75b
* Content: [Tenant Wide Deployment of SharePoint Framework Extensions](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/basics/tenant-wide-deployment-extensions)
* Content Source: [docs/spfx/extensions/basics/tenant-wide-deployment-extensions.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/extensions/basics/tenant-wide-deployment-extensions.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by andrewconnell** [comment] 2021-02-15 10:52
Can you be more specific when you aren't seeing it? I just tested creating a SPFx extension in a new project (SPFx v1.11) & it's definitely added to that file:

```json
{
  "$schema": "https://developer.microsoft.com/json-schemas/spfx-build/package-solution.schema.json",
  "solution": {
    "name": "test-ext-client-side-solution",
    "id": "5846d90c-83bf-42a8-8246-dce4b9b3f2ec",
    "version": "1.0.0.0",
    "includeClientSideAssets": true,
    "isDomainIsolated": false,
    "developer": {
      "name": "",
      "websiteUrl": "",
      "privacyUrl": "",
      "termsOfUseUrl": "",
      "mpnId": ""
    },
    "features": [
      {
        "title": "Application Extension - Deployment of custom action.",
        "description": "Deploys a custom action with ClientSideComponentId association",
        "id": "2255c8c7-f180-4bbe-a8a9-9aef9d749a45",
        "version": "1.0.0.0",
        "assets": {
          "elementManifests": [
            "elements.xml",
            "ClientSideInstance.xml"
          ]
        }
      }
    ]
  },
  "paths": {
    "zippedPackage": "solution/test-ext.sppkg"
  }
}
```

**Comment by johnnycardy** [comment] 2021-02-16 09:06
Here's what I run:
![image](https://user-images.githubusercontent.com/904610/108040882-c3790d00-7035-11eb-91bd-c0df3a32a7b6.png)

Here's the output:
![image](https://user-images.githubusercontent.com/904610/108040985-e2779f00-7035-11eb-9124-56e6e316588e.png)

**Comment by andrewconnell** [comment] 2021-02-16 13:48
Story story: this is by design... I've submitted a PR that will get merged to add some clarification to the docs. Take a look at the linked PR above if you want to see the specifics...

The reason: you picked SP2019 (that only has SPFx v1.4) as your target env. If you include that file in the **package-solution.json** (which is only used for tenant-wide deployment, introduced in SPFx v1.6), the generated *.sppkg will throw an exception if deployed to SP2019. That's why it isn't added when you pick SP2019 as a target environment. If you pick SP Online, it will be present.

**Closed** 2021-02-16 13:51 UTC
Labels: Needs: Attention :wave:, Needs: Reproduce Steps, area:docs-comment, area:spfx-extensions
