### ISSUE TITLE
SPFx sudden Minified React error #321

### ISSUE THREAD

**Issue by wizneeraj** [SharePoint/sp-dev-docs#8510] opened 2022-10-18 14:18 UTC
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version v100
- SPFx version 1.12
- Node.js version 10

### Describe the bug / error

One of our SPFx Web Part started throwing the below error suddenly on all the pages its being used. It was working until yesterday and no changes have been made to the package recently in last 2 months.

ERROR:
Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

CALL STACK:
Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Object.ao (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_ea3e1b4c1c4e9e32890807c4b77664b2.js:69:64371)
    at Object.t.useRef (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_ea3e1b4c1c4e9e32890807c4b77664b2.js:3:6809)
    at https://res-1.cdn.office.net/files/sp-client/office-ui-fabric-react-bundle_none_441bf6f5d0719b2d3d2a.js:1:40124
    at Yr (https://res-1.cdn.office.net/files/sp-client/react-dom-16-bundle_none_8eaea77e9a62cc734837.js:2:64000)
    at To (https://res-1.cdn.office.net/files/sp-client/react-dom-16-bundle_none_8eaea77e9a62cc734837.js:2:71934)
    at ys (https://res-1.cdn.office.net/files/sp-client/react-dom-16-bundle_none_8eaea77e9a62cc734837.js:2:112131)
    at pc (https://res-1.cdn.office.net/files/sp-client/react-dom-16-bundle_none_8eaea77e9a62cc734837.js:2:102665)
    at uc (https://res-1.cdn.office.net/files/sp-client/react-dom-16-bundle_none_8eaea77e9a62cc734837.js:2:102590)
    at ac (https://res-1.cdn.office.net/files/sp-client/react-dom-16-bundle_none_8eaea77e9a62cc734837.js:2:99620)
    at Zs (https://res-1.cdn.office.net/files/sp-client/react-dom-16-bundle_none_8eaea77e9a62cc734837.js:2:96388)

### Steps to reproduce

N/A

### Expected behavior

WebPart should render as designed

**Comment by AJIXuMuK** [comment] 2022-10-18 15:15
@wizneeraj - could you please check the comments from the issues under "react17" label to check if any is applicable to you (both closed and open): https://github.com/SharePoint/sp-dev-docs/labels/react-17

**Comment by AJIXuMuK** [comment] 2022-10-18 15:54
@wizneeraj - the fix is intended to allow the usage of office-ui-fabric-react-bundle without problems.
But if you've just got the error, I assume there is something else on the plate.
What version of React are you using in your solution?

**Comment by bcameron1231** [comment] 2022-10-18 17:16
@AJIXuMuK  Was the fix rolled out globally, or still in process of rolling out? We're still seeing this issue when using office-ui-fabric-react-bundle.

**Comment by bcameron1231** [comment] 2022-10-18 17:36
@AJIXuMuK  Was this rolled out globally, or in the process still? I'm still seeing this issue when I have references to office-ui-fabric-react in css or imports

**Comment by foxxycodes** [comment] 2022-10-18 20:16
Several customer projects started to break! This is bad!

**Comment by AJIXuMuK** [comment] 2022-10-18 21:53
We found one more issue and will be including it in the next rolled out build.
We will not roll back the current build.
So, if the issue is critical for you - replace the import to `office-ui-fabric-react`.
I recommend doing it anyway as `@microsoft/office-ui-fabric-react-bundle` will be deprecated in the next beta of SPFx.

**Comment by AtDH01** [comment] 2022-10-19 09:50
> We found one more issue and will be including it in the next rolled out build. We will not roll back the current build. So, if the issue is critical for you - replace the import to `office-ui-fabric-react`. I recommend doing it anyway as `@microsoft/office-ui-fabric-react-bundle` will be deprecated in the next beta of SPFx.

Thanks for the suggested fix...

Pretty frustrating that this broke our components that we had in our production environment.

**Comment by andreer1** [comment] 2022-10-19 14:13
This happened to us too.
The solution from AJIXuMuK works fine

**Comment by FangQL** [comment] 2022-10-21 03:44
> We found one more issue and will be including it in the next rolled out build. We will not roll back the current build. So, if the issue is critical for you - replace the import to `office-ui-fabric-react`. I recommend doing it anyway as `@microsoft/office-ui-fabric-react-bundle` will be deprecated in the next beta of SPFx.

@AJIXuMuK Do we have public announcement for the deprecated? Thanks.

**Comment by AJIXuMuK** [comment] 2022-10-24 21:43
the fix has been rolled out to 100% prod.

**Closed by AJIXuMuK** 2022-10-24 21:43 UTC
Labels: type:bug-suspected, area:spfx, Needs: Attention :wave:, react-17
