### ISSUE TITLE
0365 cdn Invalid Referer

### ISSUE THREAD

**Issue by sidjustsid** [SharePoint/sp-dev-docs#662] opened 2017-06-21 16:08 UTC
Hi @waldekmastykarz 
Hope you are doing good!

I have configured cdn to my tenant and when i am trying to access the file from the url im getting below error:
Could you please help in this? Image attached for reference.
![image](https://user-images.githubusercontent.com/26655462/27394479-e7c5f7c4-56c9-11e7-93f4-220b00a90eda.png)

Many Thanks

**Comment by waldekmastykarz** [comment] 2017-06-23 07:51
This is by design as mentioned in the documentation at https://dev.office.com/blogs/office-365-public-cdn-developer-preview-release:

> Notice. You can’t use a browser tab to test the URL returned by this API, due to the referer limitations in the CDN. You can set this URL to an asset hosted in SharePoint to validate the URL and that everything works properly

```
https://contoso.sharepoint.com/ _vti_bin/publiccdn.ashx/url?itemurl=https://contoso.sharepoint.com/siteassets/folder1/folder2/image.jpg
> Output: https://publiccdn.sharepointonline.com/contoso.sharepoint.com/1937006161eeae8fe.../folder2/image.jpg
```

**Comment by sidjustsid** [comment] 2017-06-23 07:54
@waldekmastykarz 

Yes when i have referred the same file from the sharepoint page it is working fine. Also i have observed that few files are not fetched and few files are fetched properly.
Can you suggest that using reference from public cdn will improve the performance?

Thanks
Sid

**Comment by waldekmastykarz** [comment] 2017-06-23 07:57
That depends on which CDN you would use and how it is configured. Whether the performance of that CDN is better than the Office 365 public CDN is something you can only determine by verifying the performance from the same network as used by the users working with the final solutions.

**Comment by sidjustsid** [comment] 2017-06-23 07:58
@waldekmastykarz 
I have used the public cdn and reffered the files frompublic cdn, what i felt is that everytime for a file to be referred, it is waiting for public cdn which is still worse.

**Comment by VesaJuvonen** [comment] 2017-06-27 07:55
Hi @sidjustsid, referer requirements are there since Office 365 CDN is targeted to be used in the context of SharePoint Online, not to host assets which are hosted from any other location. You can find the GA level documentation around the URLs and behavior from following blog post.

* https://dev.office.com/blogs/general-availability-of-office-365-cdn

Since this is by design in the context of the Office 365 public CDN, will close this issue for now. If you do however have any additional questions, we can absolutely re-open the issue or continue the discussion here. Feedback and comments are more than welcome.

**Closed by VesaJuvonen** 2017-06-27 07:55 UTC

**Comment by sidjustsid** [comment] 2017-06-27 07:57
@VesaJuvonen 
Thanks for the Information.
