### ISSUE TITLE
Custom dialog does not work

### ISSUE THREAD

**Issue by SamueleFurnari** [SharePoint/sp-dev-docs#7523] opened 2021-11-22 11:09 UTC
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx version: 1.13.1
- Node.js version: 14.18.1

### Describe the bug / error

I followed the Custom dialog tutorial reported [here](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/guidance/using-custom-dialogs-with-spfx) but the BaseDialog, defined in the sp-dialog package, does not contains close() end show() methods and the domElement property.

Searching on Internet I found [this](https://issueexplorer.com/issue/SharePoint/sp-dev-docs/7431) discussion and even if I've downgraded the sp-dialog version to the 1.12.1, the custom action button does not appear and the code crashes with an uncatchable error sayng:

Uncaught (in promise) Error
    at t [as constructor] (listview-host-assembly_it-it_fd815997ef33cccdfbf8eac235f6f775.js:67)
    at new t (listview-host-assembly_it-it_fd815997ef33cccdfbf8eac235f6f775.js:68)
    at Function.e.buildErrorWithVerboseLog (listview-host-assembly_it-it_fd815997ef33cccdfbf8eac235f6f775.js:68)
    at Function.e.buildLoadComponentError (listview-host-assembly_it-it_fd815997ef33cccdfbf8eac235f6f775.js:68)
    at chunk.systemjs-component-loader_it-it_0e72155ab8ba4215d52d.js:1

I need to open a dialog that opens when the user select one or more file in a document library and allow user to select some information retrieved from external service, and than save the value returned from this service to a custom metadata.

If there is another way that allow me to do this, any suggestion is appreciated.

### Steps to reproduce

1. Create an SPFX 1.13.0 custom action
2. Define a custom dialog
3. Open custom dialog

### Expected behavior

The custom button is shown and, when select one or more documents, the custom dialog are shown

**Comment by AJIXuMuK** [comment] 2021-11-22 14:03
Dupe of #7431

**Closed** 2021-11-22 14:04 UTC
Labels: type:bug-suspected, status:duplicate, Needs: Triage :mag:
