### ISSUE TITLE
Fix for Dev Office.com

### ISSUE THREAD

**Issue by sathiya-io** [SharePoint/sp-dev-docs#5609] opened 2020-04-20 11:13 UTC
I have had accessed 'dev.office.com' before and seems that domain might be migrated to 'developer.office.com', which can be managed to fix it from MS IT [Office UI Fabric to  https://dev.office.com/fabric#/]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f60068c3-4534-a400-350b-fdbcefd684b6
* Version Independent ID: 228accdb-a7de-0671-34ad-60a37866c380
* Content: [Use column formatting to customize SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#feedback)
* Content Source: [docs/declarative-customization/column-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/column-formatting.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by sathiya-io** [comment] 2020-04-20 11:16
update: https://developer.microsoft.com/en-us/fluentui#

**Comment by bcameron1231** [comment] 2020-04-20 13:21
Duplicate of #5597

**Closed** 2020-04-20 15:27 UTC
Labels: area:docs-comment, status:duplicate
