### ISSUE TITLE
.stats.json incorrectly picked up as a manifest by the package-solution gulp task

### ISSUE THREAD

**Issue by waldekmastykarz** [SharePoint/sp-dev-docs#19] opened 2016-08-18 14:06 UTC
The `package-solution` gulp task incorrectly detects the .stats.json file as a Web Part manifest. This results in the following error being thrown while running the task:

```
Warning - [package-solution] Ignoring manifest due to validation error (/Users/clippy/tmp/dist/tmp.stats.json)
```

Adding the `--verbose` flag gives more details about the error:
```
[16:04:14] Warning - [package-solution] Ignoring manifest due to validation error (/Users/clippy/tmp/dist/tmp.stats.json)
[16:04:14] [package-solution] (#/) Data does not match any schemas from 'oneOf'
(#/) Missing required property: description
(#/) Missing required property: manifestVersion
(#/) Missing required property: preconfiguredEntries
```

**Comment by nickpape-msft** [comment] 2016-08-18 18:47
This is by design. It looks for all JSON files and checks to see if it is a manifest. I do think a warning is a bit excessive. I've downgraded this from a warning to a simple log, displaying a list of which files are selected and which are ignored. This will be in the next drop.

**Closed** 2016-08-18 19:30 UTC
Labels: bug, Tooling
