### ISSUE TITLE
SPFx Application Customizers don't scroll on /_layouts/15 pages and list/library pages

### ISSUE THREAD

**Issue by CloudDesignBox** [SharePoint/sp-dev-docs#1598] opened 2018-04-05 09:30 UTC
#### Category
- [ ] Question
- [ ] Typo
- [X ] Bug
- [ ] Additional article idea

I've noticed that application customizers which make use of the header placeholder scroll on SharePoint "site pages" but not on other pages such as site contents or document libraries. You can reproduce this with a standard app customizer https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/using-page-placeholder-with-extensions and then resize the browser window. This issue seems to effect all browsers but my testing has been in Chrome.

Not working in document library:
![documentlibrary](https://user-images.githubusercontent.com/17725046/38357523-cceb1dd4-38ba-11e8-83c4-c5a8817797ff.JPG)

Working on site pages:
![sitepages](https://user-images.githubusercontent.com/17725046/38357540-ddded0d6-38ba-11e8-85e4-9c24255a38c2.JPG)

The issue seems to be the following CSS:
.sp-App-root{
overflow:hidden;
}

This CSS fixes the issue (but i wouldn't want to touch that CSS in app customizers):
.sp-App-root{
overflow-x:hidden;
overflow-y:scroll;
}

I assume this is built like this for a reason but doesn't take into account customizations which might need scrolling ability especially on mobile devices. I just wondered if other people had this issue and how they got around it?

**Comment by AJIXuMuK** [comment] 2021-09-03 20:49
I can confirm that I see the scrolling on Home Page, but don't see on Doc Lib, List, or Site Content

**Comment by patmill** [comment] 2021-09-30 21:38
Hi @CloudDesignBox - sorry for the long delay.  We've taken a good look at this, and we're going to close this without fixing it, mostly because the fix would be to make both experiences "broken" by your definition.  The problem is that the design of the top placeholder is that is sits above the scrollable content region, it isn't a part of it.  In this case, the header is so large that it has pushed all the content out of the viewport, so the scrollable content region can't be seen.  The solution here is to make your header smaller so that it is mobile friendly.

**Closed by patmill** 2021-09-30 21:38 UTC
Labels: area:spfx, status:tracked, type:bug-confirmed

**Comment by CloudDesignBox** [comment] 2021-10-01 07:48
Thank you for the update @patmill. 
Don't you think it is strange that the placeholders only get added after a new item is added to the list?
It wouldn't seem as strange if they were there to begin with. I don't have a problem with them being there, it's just the fact that they only appear after a new item has been added to the list.....

**Comment by AJIXuMuK** [comment] 2021-10-01 12:04
Hi @CloudDesignBox - this bug is about scrolling of application customizers on the pages. 
For the one that you're mentioning - you are correct. We're working on it to make them visible all the time.

**Comment by CloudDesignBox** [comment] 2021-10-01 12:08
Thanks @AJIXuMuK
