### ISSUE TITLE
SharePoint load different versions of the same package

### ISSUE THREAD

**Issue by mgrosperrin** [SharePoint/sp-dev-docs#8519] opened 2022-10-24 10:36 UTC
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version: Edge 106; Chrome 106
- SPFx version: 1.15.2
- Node.js version 16.14

### Describe the bug / error

When we upload a new version of our package (containing WebParts) to a tenant's AppCatalog, SharePoint randomly load old and new version of the associated code.
For some request, we have the old version, and for others the new version (and vice-et-versa). If you upload a third version of the package, we alternate between the three versions.

I attached a HAR file showing the issue (search for `news` in the file list).
[load_multiple_package_versions.zip](https://github.com/SharePoint/sp-dev-docs/files/9850917/load_multiple_package_versions.zip)

### Steps to reproduce

1. Upload a package containing WebPart (with code hosted in a CDN) to an AppCatalog
2. Add the WebPart of the package to a page
3. Upload a new version of the package
4. Refresh the page multiple times

### Expected behavior

After uploading a new version of a package in the AppCatalog, the new version is ALWAYS loaded (even after a delay of few minutes).

**Comment by mgrosperrin** [comment] 2022-10-24 12:48
In addition to this behavior, we have another one:
When we delete the package from the AppCatalog (and the first and second recycle bin), and reload the page, sometimes the WP is displayed and sometimes not...

**Comment by bcameron1231** [comment] 2022-10-24 14:01
Can you confirm if the app package is 'checked-out' in your App Catalog? If so, can you check it in?

**Comment by mgrosperrin** [comment] 2022-10-24 14:57
hello @bcameron1231,
The package is already checked-in (at least, the option I have is to checked-out it):
![image](https://user-images.githubusercontent.com/1014410/197557941-f54947a7-6a66-46a3-a9c2-a768bbcff6d0.png)

**Comment by demyren** [comment] 2022-10-24 17:10
Thank yhou @mgrosperrin for the har file! I can see there that both the 10.24 (1f9a38bda5933a9dac26) version and the 10.7 (6093ab0b21514a820cc5) version are imported on the page - the former with a script preload, though the latter seems to be what is actually being loaded. 

Would it be possible for you next to send me a Fiddler trace of the same request? I want to see in the page .aspx request, in the response, which actual version of the file is sent there. BTW, the one that should be active, is it 10.24?

**Comment by hstuermannfellowmind** [comment] 2022-10-26 14:21
We are having the same issue on different tenants. When we deploy a new version of a SPFX solution it is really hard to get the new version. Even when inserting in a new site collection the old version is loaded. The solution is uploaded over the "new" app catalog. The file is checked in, the version number is updated.
The "old" app catalog is working more reliable.

**Comment by demyren** [comment] 2022-10-26 17:13
@hstuermannfellowmind Thank you for reporting this issue. Are you seeing this working reliably when you bypass the cache using CTRL+F5? If you can provide a Fiddler trace along with information about the expected and unexpected versions, then I can determine from that whether the new or the old version is being sent in the response. 
If you want you could mail this directly to me: demyren@microsoft.com. Thank you!

**Comment by hstuermannfellowmind** [comment] 2022-10-27 07:12
@demyren Clearing cache and CTRL+F5 is not helping. I checked the traffic in browser and checked the solution file. In both files I was getting the old version. As soon as we used the "old" application catalog it worked.
I have no Fiddler here. If we encounter the same problem, we can try to create some logs.

**Comment by mgrosperrin** [comment] 2022-10-27 09:49
Hi @demyren,

> Thank yhou @mgrosperrin for the har file! I can see there that both the 10.24 (1f9a38bda5933a9dac26) version and the 10.7 (6093ab0b21514a820cc5) version are imported on the page - the former with a script preload, though the latter seems to be what is actually being loaded.
> 
> Would it be possible for you next to send me a Fiddler trace of the same request? I want to see in the page .aspx request, in the response, which actual version of the file is sent there. BTW, the one that should be active, is it 10.24?

The expected version in this case is the 10.7 but we have the issue even with "newer" packages. Unfortunately, I am not able to produce a Fiddler trace because as mentionned by @hstuermannfellowmind, since tuesday, it is soooo loooong to have the new version available: previously it was a question of seconds, and now it takes more than an hour.
Even if it seems better because when I come back I only see the new version, this long delay is really frustating because it really slow down our feedback loop (and we have to be really more carrefull when deploying new version to not introduce something that may corrupt data as the rollback take a lot of time).

I will continue my experimentation hoping the delay will be shorter.

**Comment by AJIXuMuK** [comment] 2022-10-27 11:34
@hstuermannfellowmind - this sounds unrelated to the issue (if I understand correctly - you see old versions in `.sppkg` file itself).
Could you please create a separate issue to avoid confusing this one?

**Comment by hstuermannfellowmind** [comment] 2022-10-27 11:50
@AJIXuMuK Oh sorry I was writing something weird. I mean I inspected the package file, and it was containing the "new" version, while the browser was loading the "old" one (even in network tab of debugger with deactivated/cleared cache)
We upload the new version in app catalog, but on the site collection is still the old version.

We tried many things to resolve the issue:
- updating the solution on the site collection
- reactivating the feature on the site collection
- creating a new page 
- creating a new site collection
- using a different browser
- removing the solution from app catalog (-> solution was not really removed, we could still use it on our site collection)
- using the "old" (classic) app catalog (-> worked as expected. Solution got updated all over the tenant)
- waiting (-> after waiting a while, for example deploying the solution in the evening, at the morning the customer had the new version)

Plus: we are having the problems on different tenants (even customer tenants) and different solutions. Sadly, it's not that easy to reproduce.

So, if you say it's a different problem I while create a new issue :)

**Comment by mgrosperrin** [comment] 2022-10-27 12:30
Hello,
after the previous comment I did some other tests.
With the classic app catalog experience, the solution is updated within seconds (which is expected and desired). It also seems to now always take the last version.
With the modern app catalog experience, the solution is updated after a long time.

So the original issue seems to be resolved.
I will create a new issue for the difference of time to "update" the package when we use the modern app catalog experience.

**Comment by mgrosperrin** [comment] 2022-11-03 11:02
Hi @demyren,
We have reproduced the issue this morning!
I joigned the HAR and Fiddler trace.
[load_multiple_pacakge_versions_2022-11-03.zip](https://github.com/SharePoint/sp-dev-docs/files/9927700/load_multiple_pacakge_versions_2022-11-03.zip)

Some informations to understand the issue:
- We deploy a package with the version `2022.11.3.5761` this morning. After few tests, we found some issue so we deploy an older version (`2022.10.28.5623`). This deployments were via the REST API (by using the PnP PowerShell module).
- When we refresh the page containing our WebParts, we saw that both version were loaded (in the HAR, if you look for `news-gallery`, you will see two different files: `news-gallery_06e1bd1920edbf37246c.js` (from the version `2022.11.3.5761`) and `mzk-news-gallery_de41917bf9782882ae0e.js` (from the version `2022.10.28.5623`)).
- In the Fiddler trace, I can only see the `mzk-news-gallery_de41917bf9782882ae0e.js` file (loaded from our CDN `cdn-mozzaik.azureedge.net/webparts/production/<version>`)

**Comment by demyren** [comment] 2022-11-04 17:31
Hi @mgrosperrin, thank you so much for taking the time to collect the traces! I think I know what is going on here. First of all, did the 10.28 version still load fine during that first page load after deploying the older package version? If it did, that is consistent with my understanding of what happens.

The reason you see 11.3 is that we start pre-rendering an initial HTML chunk very early in the rendering process, for performance reasons. This chunk contains script preloads (<link rel"preload">) for all scripts we used *last time* page loaded. Because of this calculated optimization, when a package has changed, and you return to a page you visited before we might see the first page load preloading some of the old package's scripts, in vain. The scripts are only preloaded, but they are not actually compiled or executed. Once we receive the SharePoint navigation response, we determine that the package was updated and we start using it immediately. The previous preloads are then "thrown away". However, upon refreshing once more, you would instead see new package scripts get preloaded, and the reference to the old scripts should be gone.

If you look at the second request in the har file, for the Home-communication-alternative212.aspx page, you can see these preloads at top. However, if you search that HTML source you can also see that in the manifest set further down the page, we include the correct component there and so it should be the one ultimately being loaded and used on the page.

**Comment by demyren** [comment] 2023-01-11 18:18
Hi @mgrosperrin, I just wanted to reach out to you again. Are you still experiencing any issues with regards to deploying new versions of your package?

**Comment by mgrosperrin** [comment] 2023-01-19 09:47
Hi @demyren,
Sorry for the delay to reply.
I am not experiencing this issue anymore.

Thanks for your help.
Matthias

**Closed** 2023-01-19 09:48 UTC
Labels: type:bug-suspected, area:spfx, Needs: Attention :wave:, area:sw

**Comment by AndreiD049** [comment] 2023-01-23 19:45
@demyren Hi, sorry for reopening this issue again, i stumbled upon it while looking for a solution. 
I still see this issue with one of **Form customizer spfx solutions**. Sharepoint is just randomly loading different versions of the spfx package, and when it loads the wrong one the page just remains blank.
![image](https://user-images.githubusercontent.com/52671223/214134357-1e2278fb-9d8a-4cfc-a88e-dff6e3898845.png)

Last version was uploaded more than 4 hours ago, but it still fails.

**Comment by demyren** [comment] 2023-01-26 01:39
Hi @AndreiD049, that must be frustrating. I hope we can learn what is going on and address it. Where is your component hosted, on CDN or on SharePoint? When it serves the wrong version, it would also be interesting to see which version is sent from the server to the service worker. If you can send me (to demyren@microsoft.com) a Fiddler trace or any other means of reading this response, I can investigate it. There is a property called manifests on the .aspx response JSON that should contain the manifest for your component - and the component version sent here _should_ be the one loaded onto the page.
Thank you,
Dennis
