### ISSUE TITLE
Body format displayname should be lowercase

### ISSUE THREAD

**Issue by rdorrani** [SharePoint/sp-dev-docs#6643] opened 2021-01-27 18:26 UTC
In the JSON format for body displayname should be all lowercase else the section name does not show up in the form formatting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f6aeedd-a76d-88b0-7ed5-93e20ac218bc
* Version Independent ID: 64315895-1103-d5f6-0195-9b5b61211132
* Content: [Configure the list form](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/list-form-configuration#configure-custom-body-with-one-or-more-sections)
* Content Source: [docs/declarative-customization/list-form-configuration.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/list-form-configuration.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by gitbrent** [comment] 2021-01-28 18:18
Duplicate of #6637

**Closed** 2021-01-29 16:19 UTC
Labels: Good First Issue 🏆, area:docs, area:docs-comment, area:list-formatting, help wanted
