### ISSUE TITLE
A web part property with async onGetErrorMessage loses its value on blur

### ISSUE THREAD

**Issue by shaipetel** [SharePoint/sp-dev-docs#6482] opened 2020-11-17 18:36 UTC
## Category

- [x] Bug

## Describe the bug

If I have a web part property type text, and I have a onGetErrorMessage validation - the value sometimes get cleared when the text box loses focus.
This ONLY happens if onGetErrorMessage returns a promise that takes more than 300ms to resolve.
If it returns a string or a promise that resolves immediately - this does not happen.
for example return Promise.resolve("") will not have this issue.

## Steps to reproduce

Create a web part with a text property
set this as the validation function:

PropertyPaneTextField("customCss", {
            label: "Custom CSS file:",
            description: "Specify path to a custom CSS file.",
            validateOnFocusOut: true,
            onGetErrorMessage: (newValue) => {
              return new Promise(resolve => {
                if (!helpers.IsNullOrEmptyString(newValue))
                  try {
                    script.Instance.loadCss(newValue);//load it now
                  } catch (e) { }

                window.setTimeout(() => resolve(""), 1000);
              });
            }
          })

## Expected behavior

validation will not lose value.

the reason this property loses value, is that on lose focus the onChange is called with the text box instance element - which gets set to null between the time the validation message comes back.

## Environment details (*development & target environment*)

SPFx 1.8.2

**Comment by andrewconnell** [comment] 2020-11-18 15:23
Appears to be a dupe of #6479

**Closed** 2020-11-18 15:23 UTC
Labels: Needs: Triage :mag:, status:duplicate
