### ISSUE TITLE
Setting background-color of div destroys currency formatting.

### ISSUE THREAD

**Issue by JStein2311** [SharePoint/sp-dev-docs#5496] opened 2020-03-25 13:59 UTC
## Category
- [ ] Question
- [ ] Typo
- [ ] Additional article idea
- [x] Bug

## Expected or Desired Behavior

When applying a column style, using `@currentField` as `txtContent` should show the value of the currency column with the selected formatting set in the column settings.

## Observed Behavior

When applying a background-color to the div section of the column, using `@currentField` as `txtContent` shows the currency value as plain number without thousands- and decimal-seperators and without currency.

## Steps to Reproduce 

Create a list with a currency column, create an item and apply following code to the currency column:
`{
  "$schema": "https://developer.microsoft.com/json-schemas/sp/v2/column-formatting.schema.json",
  "elmType": "div",
  "style": {
    "background-color": "#DAE9F9",
    "margin-left": "-11px",
    "margin-right": "-11px",
    "padding-left": "12px",
    "padding-right": "12px"
   },
  "children": [
{
      "elmType": "span",
      "txtContent": "@currentField"
    }
  ]
}`

## Environment details (if applicable)

- OS: Windows 10
- Framework: /
- Browser(s): Chrome v80
- Tooling: VS Code

**Comment by sudharsank** [comment] 2020-04-07 05:42
Hi, I don't think so the currency column support formatting. Are you sure the field type is **Currency**

**Comment by JStein2311** [comment] 2020-04-15 06:50
Yes, it was a currency column where setting the background color was possible but as soon as that happened, any other formatting was destroyed. It should be possible to at least change the background color without interfering with the way the data itself is displayed.

**Comment by thechriskent** [comment] 2020-05-20 17:27
Currency is a supported field type (although you have to apply formats either using the new dropdown in the formatting window or by visiting the field settings page).

When used in formatting, the value is returned as a number (not a string). This is on purpose so that the value can be evaluated and used in operations such as addition, subtraction, etc. So, from that perspective this behavior is by design and not a bug.

However, SharePoint actually returns both the number value and the formatted value. The formatting logic returns the numeric value parsed as a float. The formatted value is not accessible through formatting. This has been (unfortunately) a known limitation for a long time (see #1070)

![Values as returned by SharePoint](https://user-images.githubusercontent.com/8364109/82477221-2e90b580-9a9d-11ea-8f0d-6cb06dc6407c.png)

What is needed is something similar to how Hyperlink fields work. With Hyperlinks you access the URL value by specifying `@currentField` but can get the description value by using `@currentField.desc`. Something like `@currentField.formatted` would be great to have for Currency and Boolean fields both. Unfortunately, this is not (yet??) part of list formatting.

I think this is a valid need and I'd to see it included but that is a feature request rather than a bug. Thanks for shining more light on this limitation!

**Comment by thechriskent** [comment] 2020-05-20 17:30
Whoops, didn't mean to auto close it.

**Comment by shagra-ms** [comment] 2020-06-10 11:50
We are aware of the current limitation, and are now tracking this in our backlog. Will update this thread, once we have more information to share.

**Comment by shagra-ms** [comment] 2020-10-21 15:46
@JStein2311 @sudharsank @thechriskent 

The currency value now supports [displayValue property](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#displayvalue) and can be used to get the default rendered value, based on the column setting.

And you can also set the column formatting JSON using the modern UI. 😊

**Closed** 2020-10-21 15:47 UTC
Labels: area:list-formatting, status:fixed
