### ISSUE TITLE
New Template with knockout has missing dependency - rimraf

### ISSUE THREAD

**Issue by davros85** [SharePoint/sp-dev-docs#244] opened 2016-10-18 12:35 UTC
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea
#### Expected or Desired Behavior

When running yo @Microsoft/sharepoint, then gulp serve - solution compiles and runs.
#### Observed Behavior

When running gulp serve on a new project, I get 'cannot find module rimraf'. Manually running 'npm install rimraf' fixes things.
#### Steps to Reproduce

Yo a new template using knockout, then run gulp serve

**Comment by patmill** [comment] 2016-10-18 16:57
Hey David - I'm trying this on a couple of machines, and I'm not getting the rimraf error.  Is this a build exception (gulp spits it out) or a runtime exception (it's in the browser)?

**Comment by iclanton** [comment] 2016-10-25 23:32
Are you on a Mac? I've seen this occasionally on my Mac. If you are on a Mac, it might be a Mac-specific issue, which would help us track down the root cause.

**Comment by iclanton** [comment] 2016-11-01 23:08
Are you unblocked? I'm going to close this issue. Feel free to reopen it if you're still stuck.

**Closed by iclanton** 2016-11-01 23:08 UTC
