### ISSUE TITLE
🐞SPFx - Update package-solution.json's schema to include optional properties for `webApiPermissionRequests`

### ISSUE THREAD

**Issue by andrewconnell** [SharePoint/sp-dev-docs#8363] opened 2022-08-10 19:36 UTC
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx v1.15.2 projects

### Describe the bug / error

The schema for **./config/package-solution.json**, `https://developer.microsoft.com/json-schemas/spfx-build/package-solution.schema.json`, is missing optional properties on objects in the `webApiPermissionRequests` array [introduced in SPFx v1.15.2](https://docs.microsoft.com/sharepoint/dev/spfx/release-1.15.2#enable-service-principal-registration-at-permission-scope-approval-time): `appId` & `replyUrl`.

This means developers won't get IntelliSense with included docs when editing this file. In fact, the file will fail validation as it currently contains `additionalProperties: false` which will say the properties aren't allowed:

![Screen Shot 2022-08-10 at 3 37 28 PM](https://user-images.githubusercontent.com/2068657/184005146-6cd44e76-1a9e-44ca-902e-52658f7ab99f.png)

### Steps to reproduce

1. Create new project
1. Use any type of component when prompted
1. Open said project in VSCode
1. Open **./config/package-solution.json**
1. Add the following code after the `developer` property:

    ```json
    "webApiPermissionRequests": [
      {
        "scope": "", "resource": "", "appId": "asd", "replyUrl": "https://foo.com/endpoint"
      }
    ],
    ````

1. Developer curses at VSCode and 😭 in solitude... kittens rush for safety to avoid being kicked by said developer.

### Expected behavior

1. Create new project
1. Use any type of component when prompted
1. Open said project in VSCode
1. Open **./config/package-solution.json**
1. Add the following code after the `developer` property:

    ```json
    "webApiPermissionRequests": [
      {
        "scope": "", "resource": "", "appId": "asd", "replyUrl": "https://foo.com/endpoint"
      }
    ],
    ````

1. Observe IntelliSense when modifying values under the included `webApiPermissionRequests`
1. The Microsoft engineer who took the time to update this file, on their way home from work to enjoy a good streaming movie, when picking up their take-out tacos 🌮, comes to find out someone paid it forward as thanks and now they enjoy free 🌮 for their contribution to developers across the globe.

**Comment by AJIXuMuK** [comment] 2022-08-16 15:43
Thanks @andrewconnell for reporting it!
the issue is now fixed.

**Closed by AJIXuMuK** 2022-08-16 15:43 UTC
Labels: type:bug-suspected, Needs: Triage :mag:
