### ISSUE TITLE
View Formatting schema - hideColumnHeaders function stopped work listview webpart

### ISSUE THREAD

**Issue by amazinjoey** [SharePoint/sp-dev-docs#5226] opened 2020-01-27 10:16 UTC
## Category
- [ ] Question
- [ ] Typo
- [ ] Additional article idea
- [x] Bug

## Question

>  It seems that the  hideColumnHeaders function has decided to stop working in list view webpart. So the flag 'true' does nothing. It was working fine until friday. 

## Environment details (if applicable)

> SharePoint Online

**Comment by PrasadKasireddy** [comment] 2020-01-27 10:19
Related issue - https://github.com/SharePoint/sp-dev-list-formatting/issues/123
https://github.com/SharePoint/sp-dev-docs/issues/5213

**Comment by shagra-ms** [comment] 2020-01-27 18:18
Thank you for reporting this. The issue has been identified and fixed. Fix would be rolled out in upcoming updates.

**Comment by furler** [comment] 2020-01-28 21:38
> Thank you for reporting this. The issue has been identified and fixed. Fix would be rolled out in upcoming updates.

Does the fix also include the related issue of "flexbox like" tiles staggering when embedded on a page via the list view web part? Multiple posts have been created for this recurring issue, I think the one @PrasadKasireddy posted: https://github.com/SharePoint/sp-dev-list-formatting/issues/123 being one of the first.

Note again this has nothing to do with the new tileProps property, which doesn't work at all when lists are embedded because you can't specify the tile view as the default view in the list web part.

Thanks,

**Comment by shagra-ms** [comment] 2020-02-03 11:39
Yes the 'flexbox like' tiles staggering will also be fixed with this fix. Though the fix on the list web part is a bit delayed and would roll out in 2-3 weeks.

We take your feedback on tileProps, and are now tracking this in our backlog.

**Comment by coupalm** [comment] 2020-02-04 02:03
2 to 3 weeks before the fix gets applied is very long. Is there anything that can be done to speed that up?
Thanks!

**Comment by PrasadKasireddy** [comment] 2020-02-04 14:30
Duplicate of #5281

**Comment by shagra-ms** [comment] 2020-02-13 06:16
The fix is now available in production tenants.

**Closed by shagra-ms** 2020-02-13 06:16 UTC
Labels: area:list-formatting, status:fixed-next-drop, type:bug-confirmed
