### ISSUE TITLE
Single Part App Page never receives onDisplayModeChanged when Save is clicked

### ISSUE THREAD

**Issue by trey-miller** [SharePoint/sp-dev-docs#4456] opened 2019-08-10 00:58 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

On a Single Part App Page (web part targeting `supportedHosts.SharePointFullPage`), when in Edit mode and the user clicks the "Save" button on the property pane, the `onDisplayModeChanged` is fired and the `webpart.displayMode` is updated to `DisplayMode.Read`. 

#### Observed Behavior

When the user clicks the Save button, the `onDisplayModeChanged` function is not called, and the `displayMode` remains as `DisplayMode.Edit`.

#### Steps to Reproduce

1. On a Single Part App Page, click the Edit button to open the property pane. Notice the `onDisplayModeChanged` function is fired, and the webpart's displayMode has changed from DisplayMode.Read to DisplayMode.Edit. 
2. (probably optional step) Modify a property, such as changing the page title (built-in field).
3. Click the "Save" button. Notice the `onDisplayModeChanged` function is not fired, and the web part's displayMode remains as DisplayMode.Edit.

#### Additional Info

This is somewhat related to an issue I noticed where the single part app page does not prevent user navigation if there are unsaved changes (maybe I should file a second issue for that one?). When I tried to create a workaround for that by creating my own `beforeunload` event that prevents navigation if there are unsaved changes, I noticed the bug described above. I need to know when Edit mode is complete and the properties have been saved to the server so that I can cancel the `beforeunload` event, but this is not possible because the webpart never leaves Edit mode and the `onDisplayModeChanged` is never called when saving the properties.

I have tried using the `onPropertyPaneConfigurationComplete` function, which does fire on user clicking "Save", but it also fires when the user clicks the "X" button on the property pane, and that button does not cause the properties to be saved to the SP server, so I would want to keep the `beforeunload` event active.

I have also tried the `onAfterPropertyPaneChangesApplied` function, but it does not fire ever.

Another note - I have tried updating to SPFx 1.9.0 to see if issues were fixed since I saw there were release notes for 1.9.0, but the latest release on the npm packages still seems to be 1.8.2 (I did not try the 1.9.0-plusbeta version).

Thank you!

**Comment by andrewconnell** [comment] 2019-08-13 15:40
Confirmed... spoke with engineering that they are aware and working on it...

**Comment by GrahamMcMynn** [comment] 2019-08-14 16:19
The fix for this has been checked in and will be rolling out.  It should reach prod around the 28th of August.  I'm going to close this issue, however, after that time if it is still not working please let us know.

**Comment by trey-miller** [comment] 2019-11-05 00:51
@GrahamMcMynn It looks like this issue is back. Clicking Edit calls `onDisplayModeChanged`, but then clicking Save does not, and afterward the web part still is in `DisplayMode.Edit`.

**Comment by jakecoartney** [comment] 2019-11-05 21:00
Bumping this as I am experiencing this issue now as well. Edit calls `onDisplayModeChanged` but does not get called in an subsequent action to the button until the app is refreshed.

**Comment by trey-miller** [comment] 2019-11-07 22:17
@andrewconnell would you be able to remove the status:fixed tag on this? It seems the issue has come back.

**Comment by GrahamMcMynn** [comment] 2019-12-05 18:25
Our code forked and a flight was turned on which dropped the fix.  I have re-added the same fix and it will roll out soon (might be a bit delayed due to holiday freezes).

**Closed** 2020-04-30 22:00 UTC
Labels: Needs: Author Feedback, area:spfx-general, no-recent-activity, status:fixed-next-drop, type:bug-confirmed
