### ISSUE TITLE
Local gulp not found, try running npm install gulp

### ISSUE THREAD

**Issue by sonorone** [SharePoint/sp-dev-docs#6980] opened 2021-05-04 14:58 UTC
During development environment setup at the [Install Gulp stage](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment#install-gulp) I came across an issue with installing gulp. After installation when running gulp in terminal to accept dev cert it shows "Local gulp not found, try running npm install gulp".

This is because the documentation should ask to install gulp-cli instead of gulp. Installing gulp-cli globally solves the issue but the document requires revision.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bee09a8-022e-1b5a-4aab-d6e7c6216808
* Version Independent ID: 49edce1e-f2be-e989-917f-c6b389363e2f
* Content: [Set up your SharePoint Framework development environment](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment)
* Content Source: [docs/spfx/set-up-your-development-environment.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/set-up-your-development-environment.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by omarelanis** [comment] 2021-05-04 17:17
@sonorone gulp is a dependant of gulp-cli but only gets installed after a scaffold project has been created, as per the documentation it states "Once a project has been created with the Yeoman generator for the SharePoint Framework, execute the following command from within the root folder of the project.
gulp trust-dev-cert

Note
This assumes you have installed all dependencies with npm install after creating the project. This step will install all gulp tasks as part of a project.
"

That is because the gulp module has to be installed in the local project for it to run.

**Comment by bcameron1231** [comment] 2021-05-05 13:04
To add on to @omarelanis , this is a duplicate of #6592 . You need to create a project before running the trust dev cert as he mentions.

**Closed** 2021-05-06 13:23 UTC
Labels: area:docs-comment, status:duplicate
