### ISSUE TITLE
@microsoft/generator-sharepoint updated to @fluentui version 8 which does NOT use scss

### ISSUE THREAD

**Issue by BobFleischman** [SharePoint/sp-dev-docs#8942] opened 2023-05-02 18:37 UTC
[Enter feedback here]
Generate a project today and throws the following error:
[14:21:07] Error - sass - src\webparts\secondChance\components\SecondChance.module.scss(1,9): error Error: Can't find stylesheet to import.
  ╷
1 │ @import '~@fluentui/react/dist/sass/References.scss';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src\webparts\secondChance\components\SecondChance.module.scss 1:9  root stylesheet

after a lot of trying things I found that @fluentui-react is now version 8, which does not use scss.

Used **npm i @fluentui/react@7.204.0** and now the project builds/

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6c25a90e-829c-b436-d8ab-f9c010588ee1
* Version Independent ID: 768fa9a1-2375-fb5a-be58-cb66320cc789
* Content: [Build your first SharePoint client-side web part (Hello World part 1)](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part)
* Content Source: [docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md)
* Service: **sharepoint**
* Sub-service: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by AJIXuMuK** [comment] 2023-05-02 18:42
Dupe of #8939

**Closed** 2023-05-02 18:42 UTC
Labels: status:duplicate, Needs: Triage :mag:
