### ISSUE TITLE
This may be a problem with a HTTPS certificate. Make sure you have the right certificate

### ISSUE THREAD

**Issue by ClausKramer** [SharePoint/sp-dev-docs#3871] opened 2019-05-01 13:39 UTC
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Observed Behavior

We have the same issue as #3342 but unfortunately it was closed.
Any updates on how to fix it ?

![image](https://user-images.githubusercontent.com/20723888/57019559-3463f080-6c27-11e9-89c7-7727f0fc885a.png)

**Comment by ClausKramer** [comment] 2019-05-01 17:16
I realize now that this might be a duplicate, but it seems like non of the reported bugs was solved

**Comment by patmill** [comment] 2019-05-01 22:42
Are you running these from local host, or the public CDN, or your app catalog site, or ?

**Comment by ClausKramer** [comment] 2019-05-02 06:58
the public CDN

**Comment by Saulius-Laurinaitis** [comment] 2019-05-02 08:40
I have the same: https://github.com/SharePoint/sp-dev-docs/issues/3867

**Comment by patmill** [comment] 2019-05-03 16:20
Hi @ClausKramer / @Saulius-Laurinaitis - trying to help another dev diagnose this.  Can you paste the full path to the asset that is failing?  Feel free to change your tenant name in the path to "sharepoint.contoso.com" and your app catalog to "appCatalog"

Also - if you look in the debugging tools, what are the headers / response / etc. for the failed request?

**Comment by rmunasinghe** [comment] 2019-05-06 15:13
I was having this issue in IE only. Removing the following line from my SPFx solution and redeploying resolved the issue for me:
import "core-js/es6/string";

**Comment by patmill** [comment] 2019-05-06 22:30
I'm not sure what that line would have to do with making a call to the CDN and getting a cert error.  That seems strange.

**Comment by Saulius-Laurinaitis** [comment] 2019-05-07 14:38
Hi @patmill,
apologies for late reply, but I cannot reproduce it anymore. It was probably some outage in Office 365.

Thanks
Saulius

**Comment by ClausKramer** [comment] 2019-05-07 21:42
mine is fixed too - had to disable CDN to get to the real error message and realize that it was a problem with polyfills. Fixed the polyfill problem, enabled CDN again and problem solved.

**Comment by patmill** [comment] 2019-05-07 22:08
OK, closing.  Thanks.

**Closed by patmill** 2019-05-07 22:08 UTC
Labels: area:cdn

**Comment by Rajrup-net** [comment] 2019-09-17 08:46
Hi @ClausKramer Can you please tell me how did you fix polyfills issue.. its very urgent for me. For a long time I am searching the solution but no luck. Please help.

**Comment by olemp** [comment] 2019-12-17 11:51
Experiencing the same with one of my SPFx webparts, and can't figure out what's up.

Fails in IE11:

```
[SPLoaderError.loadComponentError]:
Failed to load component "2ef269b2-6370-4841-8b35-2185b7ccb22a" (ResourceAllocationWebPart). Original error: Failed to load URL 'https://publiccdn.sharepointonline.com/tenant.sharepoint.com/sites/app_catalog/ClientSideAssets/00483367-68e2-4977-9cc3-6cf0de623daa/resource-allocation-web-part_821bf477906cf3d1702021c1d70587a4.js' for resource 'resource-allocation-web-part' in component '2ef269b2-6370-4841-8b35-2185b7ccb22a' (ResourceAllocationWebPart). There was a network problem. This may be a problem with a HTTPS certificate. Make sure you have the right certificate.

INNERERROR:
Failed to load URL 'https://publiccdn.sharepointonline.com/tenant.sharepoint.com/sites/app_catalog/ClientSideAssets/00483367-68e2-4977-9cc3-6cf0de623daa/resource-allocation-web-part_821bf477906cf3d1702021c1d70587a4.js' for resource 'resource-allocation-web-part' in component '2ef269b2-6370-4841-8b35-2185b7ccb22a' (ResourceAllocationWebPart). There was a network problem. This may be a problem with a HTTPS certificate. Make sure you have the right certificate.
CALLSTACK:
Error
   at t._generateErrorStackForIE (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_nb-no_a2b78537eead54c03f6f852ce810da7f.js:4:53963)
   at t (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_nb-no_a2b78537eead54c03f6f852ce810da7f.js:4:53499)
   at t (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_nb-no_a2b78537eead54c03f6f852ce810da7f.js:20:118832)
   at e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_nb-no_a2b78537eead54c03f6f852ce810da7f.js:20:128525)
   at e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_nb-no_a2b78537eead54c03f6f852ce810da7f.js:20:124550)
   at Anonymous function (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_nb-no_a2b78537eead54c03f6f852ce810da7f.js:20:115044)
   at Anonymous function (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_nb-no_a2b78537eead54c03f6f852ce810da7f.js:1:16156)
   at F (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_nb-no_a2b78537eead54c03f6f852ce810da7f.js:1:16132)
   at C (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_nb-no_a2b78537eead54c03f6f852ce810da7f.js:1:15977)
   at B (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_nb-no_a2b78537eead54c03f6f852ce810da7f.js:1:15565)
```

cc @patmill
