### ISSUE TITLE
On a failed POST request using the HttpClient the promise is resolved as fulfilled 

### ISSUE THREAD

**Issue by waldekmastykarz** [SharePoint/sp-dev-docs#184] opened 2016-09-14 05:40 UTC
#### Category
[ ] Question
[ ] Typo
[x] Bug
[ ] Enhancement / Suggestion
[ ] Additional article idea

#### Expected or Desired Behavior
If the POST request results in a 4xx status code the promise should resolve as failed.

#### Observed Behavior
For a POST request failed with a 400 Bad Request status, the promise resolves as fulfilled.

#### Steps to Reproduce
Call the /_api/web/list/getbytitle('listname')/items API using httpClient.post with an empty body.

**Comment by patmill** [comment] 2016-09-15 17:05
@pgonzal and I were chatting about this the other day.  It's a bit tricky at times.  A 404 code, for example, doesn't necessarily mean an error occurred.  It could be completely correct and part of the API (If you try and delete an item that isn't present, a 404 should be returned).

**Comment by vman** [comment] 2016-09-15 17:38
I think this is due to the way the fetch API works. It only rejects a promise if there is a network error https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#Checking_that_the_fetch_was_successful

A bit more detail here: https://www.tjvantoll.com/2015/09/13/fetch-and-errors/

**Comment by SteveCurran** [comment] 2016-09-16 02:26
Seems a bit odd to have to do exception handling in both the fulfill and the reject. 90% of rest call problems are 400 Bad Requests due to incorrect payload structures depending whether your doing verbose or minimalmetadata. It is really up to the server code to return the correct error status along with a useful message. So I am assuming 500 status will cause a reject? Many of us have been using JQuery for rest calls which returns 400 in the error callback.

**Comment by pgonzal** [comment] 2016-09-20 21:26
There is an entire spectrum of reasons why we would consider a network operation to have "failed":

1. The JavaScript API was used incorrectly, e.g. a string was passed where a class was expected, a required option was `undefined`, etc.
2. The network call timed out, with no response
3. The network call failed because of a DNS error
4. The network call talked successfully communicated with the server, but was not authorized
5. The network call successfully communicated with the server, but 404 was returned
6. The network call returned a response, and somewhere in the response is an error message indicating that the operation failed

Some of these make a lot of assumptions about the server's protocol.  For example, for # 6 the response may be in JSON or XML format depending on what "Accept" header was specified.  Different REST API's will encode the error object differently.  It is not feasible for `HttpClient` to be aware of all of these details.

The standard **fetch** API takes the approach of only rejecting the promise for case # 1.  For all other types of failures, the promise resolves successfully, and it is up to the user's code to perform error detection.  I believe this is the right design, because if you are implementing your REST protocol class correctly, you probably already need to write special logic for case # 6; the other cases can be handled here as well.

Another way to say this is that `HttpClient` is not trying to be your REST protocol class.  For example, if you are querying an `SPList` in a serious application, you probably will not be using `HttpClient` directly. Instead, you would implement an "SPListDataModel" class that uses `HttpClient` to perform the REST operations. `HttpClient`'s job is authentication, logging, and standardization of headers.

If you define many protocol classes such as SPListDataModel, SPPublishingDataModel, etc, you could probably roll up all of your error handling into a centralized utility.  We are experimenting with doing this for our first party web parts, and if it works out, we will consider incorporating this into the SPFx framework. However, it would not be part of HttpClient.  It would be a separate helper API.

**Comment by pgonzal** [comment] 2016-09-20 21:26
(I'm closing this issue as "by design".  Please reopen it if you have more questions.)

**Closed** 2016-09-20 21:26 UTC
Labels: type:discussion

**Comment by Vinod-Naik** [comment] 2017-05-04 13:52
Issue still present, Wheneve we put any post request using HttpClient (SPHttpClient also in my case) , even if we get 404 or 500 error, HttpClient promise is resolved (Success) handler is executed.
Let us know if this will be fixed or do we have to check response.ok parameter for execption handling.
/Vinod
