### ISSUE TITLE
Application Customizers and library components loaded twice

### ISSUE THREAD

**Issue by poikjo** [SharePoint/sp-dev-docs#5317] opened 2020-02-11 08:53 UTC
## Category

- [x] Bug

## Describe the bug

> Noticed on couple tenants that Application Customizers and Library components are loaded twice. Using Chrome / Edge network tab to check loaded scripts and js files and seeing those loaded by sp-pages-assembly.. and VW.. Verified with Fiddler. Webpart script are only loaded once.

Only difference on these calls is that another uses CORS setting and another doesn't. With CORS call fails when using Azure CDN hosted files (file is accessible by using direct url). 

Azure CDN hosted Library component
![image](https://user-images.githubusercontent.com/17199477/74221458-d9355300-4cba-11ea-83a8-ac47e455cb5c.png)

SP hosted Application Customizer
![image](https://user-images.githubusercontent.com/17199477/74221557-10a3ff80-4cbb-11ea-8466-f930f0f003d0.png)

## Steps to reproduce

> 
1. Create Application Customizer and install it to your site
1. Click F12 to open browser developer tools and select network tab
1. Find your app .js files loaded twice on page

## Expected behavior

> Files should be loaded only once to keep network load as low as possible. CORS configurations should be documented if required.

**Comment by patmill** [comment] 2020-02-12 01:28
Can you look at the network tab and examine the requests?  Are they both get?  Is one of them "options"?

**Comment by poikjo** [comment] 2020-02-12 08:12
Yes, I checked that and it was not options call. It was direct file fetch. 

But now the issue seems to be gone for three tenants at least. So something has changed. Let's check few days more and close this if not occurring anymore.

**Comment by andrewconnell** [comment] 2020-02-13 10:36
Since the issue isn't happening at this time, I'm going to close this issue. Please feel free to submit a new one and reference this issue if it happens again...

**Closed by andrewconnell** 2020-02-13 10:36 UTC
Labels: area:spfx-extensions
