### ISSUE TITLE
I followed this guide to the letter and get the following 

### ISSUE THREAD

**Issue by Ib01** [SharePoint/sp-dev-docs#6968] opened 2021-05-03 00:36 UTC
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bee09a8-022e-1b5a-4aab-d6e7c6216808
* Version Independent ID: 49edce1e-f2be-e989-917f-c6b389363e2f
* Content: [Set up your SharePoint Framework development environment](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment#trusting-the-self-signed-developer-certificate)
* Content Source: [docs/spfx/set-up-your-development-environment.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/set-up-your-development-environment.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by omarelanis** [comment] 2021-05-03 15:30
This needs closing as an accidental duplicate of  #6969 #

**Closed** 2021-05-04 14:35 UTC
Labels: area:docs-comment, type:incomplete-submission
