### ISSUE TITLE
Modern News OOB Webpart not showing image preview with External Users unless you share the root site collection too

### ISSUE THREAD

**Issue by luismanez** [SharePoint/sp-dev-docs#1079] opened 2017-11-23 14:21 UTC
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
External users are able to see News article preview image using the OOB News webpart in any site collection, without the need to share the Root site collection with them too. 

#### Observed Behavior
News webpart is not showing the News article preview image when the site is accessed by an external user.

#### Steps to Reproduce
Create a site collection or use an existing one that is not the root site collection.
Share the site with an external user (i.e: outlook.com account). 
With a contributor account, using the news webpart deployed in a Modern team site home page, create a News article with a header image. If you go back to the home page, you can see the article in the News webpart, including a preview of the article image.
Now, access the site by an external user. You will not see the preview article image in the news webpart.

As far as I can see, the News webpart is getting the preview image using the following Layout page:
https://tenant.sharepoint.com/_layouts/15/getpreview.ashx?....

This is always pointing to the root site collection, instead of the site collection where the user is. I think it should be use the specific site collection getpreview.ashx page.

Thanks!

**Comment by robinmeure** [comment] 2018-01-05 12:57
It's only the News part that is having this issue btw. The other parts are using the site relative URL as opposed to the root sitecollection URL. Please note that this is also an issue if a 'normal' user doesn't have access to the root sitecollection.

**Comment by gruering** [comment] 2018-09-06 08:06
I am facing the same problem. Is there any workaround available?
I have already tried adding external users as Visitors to the root site collection. That resolves the issue but it is impractical if it has to be done manually for every external user. A group like "All external users" would be helpful in this case. How do others deal with this problem? Any ETA for a fix?

**Comment by PaoloPia** [comment] 2019-03-07 10:58
Hi,
It looks like the problem occurs because the items, retrieved by REST API (_api/sitepages/pages/feed), provide the BannerImageUrl property value using the root site collection URL for the getpreview.ashx handler, rather than the local site collection URL. Digging into it, the actual value in the item is relative to the root site collection. So the issue is more on the actual data stored in SharePoint, rather than on the News web part side, IMHO. Thus, the fix has to be made on how the modern client page saves the banner URL field value. I guess that a temporary workaround could be to update the actual field value in the target items.

**Comment by EA12** [comment] 2019-05-13 07:15
I am facing the same Problem with guest users in a communication site.
After more than one year still no fix for this issue?
Any News on this, @VesaJuvonen ?

**Comment by ProjMgrJB** [comment] 2019-05-30 19:35
Same problem here but with internal users, even with an admin account. Is it possible to upvote this issue thread for MS attention somehow?

**Comment by bilalkhan870** [comment] 2019-11-24 05:41
i am facing the same issue with news webpart

**Comment by cwdata** [comment] 2019-12-10 14:04
There's another problem within the news Webpart. 
If the news Webpart is placed on a hub site and configured to display content from all connected sites it's also not showing some images. The weird thing about that is, that not all images are missing. It displays the images from some sites. All images are .jpg, have been placed in the header of the article and have been uploaded from a local computer by the same user. 
If the news Webpart is placed directly on the connected sites it shows all images, but on the hub site some (always the same) are missing.
We have now switched to the highlighted content Webpart for the time being which works perfectly well as stated above. Would be nice to see the news Webpart being usable too because it has a better layout for hub news...

**Comment by bubbleswap** [comment] 2020-01-28 18:35
similar/same issues with modern News web part --
- Thumbnail image will not show if the News web part settings is "Selected site", but post thumbnail will show if News web part is "This site only". **Is this a Hub site issue?**
- Some posts thumbnail will show in News web part roll-up, others won't, it's about 50/50. All images are JPG and **data-sp-originalimgsrc** is /_api/v2.1/
- Posts that are not displaying thumbnails, are instead, displaying this placement image: https://spoprod-a.akamaihd.net/files/sp-client/image_background_stockimage_9fe1b89a.png
- Site permissions are the same for Parent Hub site and associated Hub sites.

Anyone able to get more clarity on this? TIA.

**Comment by Sarah2109** [comment] 2020-03-03 11:02
Do we have a resolve on this yet as we are also experiencing issues?  
I have a site collection which will show news thumbnails on its own news webpart, but when this sites news is selected to show on another site collection news webpart(hub site or not) the thumbnails all disappear leaving me a horrible blurred 'e' image.  Strangely though, there is one 'news link' page thumbnail image which always pulls through no problem(I have tried re-adding this link as a new page and it also breaks on image thumbnail view).  I have tried copying pages, using templates, complete from scratch pages, checked all permissions etc.  Its really frustrating now as the site collection we have the issues with is where we create all our news.

**Closed** 2021-11-01 18:06 UTC
Labels: status:tracked, type:bug-confirmed, type:invalid-not-dev-issue
