### ISSUE TITLE
Path too long

### ISSUE THREAD

**Issue by DavidFatena** [SharePoint/sp-dev-docs#25] opened 2016-08-19 08:09 UTC
Creating project with Yeoman is making too deep structure of files which fires red errors during installation. The structure is so deep, I can't open it with Visual Studio (it freezes trying to load it all). Hack, I can't even delete the created folder (windows alerts something like Path too long, move it so you can delete it).

![error](https://cloud.githubusercontent.com/assets/21120594/17803030/02b1d6b0-65f4-11e6-92f1-07483eaf3a65.png)

**Comment by patmill** [comment] 2016-08-19 14:19
Hi David. Can you add any information about your environment?  What operating system, what version, etc?

**Comment by StfBauer** [comment] 2016-08-19 17:37
@patmill The message simply tells you that node-gyp cannot compile some/all modules.
The problem is a common issue on NodeJS on Windows together with node-gyp. Monitor this for some customer using NodeJS and SharePoint for more than a year now. In most case I was able to solve this.
It is mainly caused by a missing VC++ Build tools or inproper configuration on the client caused by VS installations sometimes.
Microsoft has released a guideline for NodeJS on Windows that should solve some of the problem. Might something for the documentation. 
You will find it on: https://github.com/Microsoft/nodejs-guidelines/blob/master/windows-environment.md#c-and-nodejs-tell-me-more
In addition there is also a documentation on how to solve the Max_Path issue on Windows.

What you are referring to is to enable longer path than 260 character  and how to disable Max Path http://betanews.com/2016/05/29/long-paths-windows-10/

**Comment by DavidFatena** [comment] 2016-08-22 13:02
Windows 10 Pro N 64bit, it is a fresh install since january 2016, so no pre-release version. Not really sure if there was a pre-release version installed in the past.

**Comment by gavinbarron** [comment] 2016-08-22 18:30
Try updating npm. `npm -g install npm@next` 
I found this got me past the problem of paths that were too long on windows.

**Comment by patmill** [comment] 2016-08-22 18:51
Of note - this is also being discussed here - http://sharepoint.stackexchange.com/questions/191289/gulp-serve-error-cannot-find-module-microsoft-sp-build-web

**Comment by patmill** [comment] 2016-08-22 22:28
Fix being discussed is as follows:
During yo @microsoft/sharepoint if we detect npm2 we will write an error message  and not run npm install.  A message will say to run npm install -g npm@3 (or npm install -g npm@next) and to then run npm install in your project.

Separately, we're thinking of writing an environment checker that can be run at any given time to see if there are issues.

**Comment by DavidFatena** [comment] 2016-08-23 07:40
This `npm -g install npm@next ` indeed fixed the issue. Thank you.

**Comment by DAgafitei** [comment] 2016-08-23 10:34
Same here. Upgrading to npm 3 fixed the issue.

**Comment by larslynch** [comment] 2016-08-23 20:55
Can someone add the "`npm install npm -g`" line to the HelloWorld tutorial to ensure that nobody tries to build this on an NPM < 3.0?  

I made the mistake and had the same undeletable hierarchy of "node-modules" folders.

**Comment by patmill** [comment] 2016-08-23 23:23
@larslynch  - I've added it to the machine setup step.  We're also going to detect this state and print a warning.  I've leave this bug open until that gets released.

**Comment by nickpape-msft** [comment] 2016-09-02 22:35
Closing this issue as an NPM v2 issue. Documentation has been updated.

**Closed by nickpape-msft** 2016-09-02 22:35 UTC
Labels: bug, Tooling
