### ISSUE TITLE
ListView Command Set: event.selectedRows returns wrong ID, when there is a pinned document in the library. This already happened before in issue 4868

### ISSUE THREAD

**Issue by oliverlp** [SharePoint/sp-dev-docs#6254] opened 2020-09-09 09:16 UTC
## Category

- [x] Bug

## Describe the bug

ListView Command Set: event.selectedRows returns wrong ID, when there is a pinned document in the library

## Steps to reproduce

In a library with a pinned document, when I selected a document from a view, the Listview Command Set will return the ID of the selected document, and not the ID of the pinned document.

## Environment details (*development & target environment*)

SharePoint Online, standard release.
Browsers: Tested on Chrome and Edge (not Chromium)
Tooling**: VS Code | SPFx v1.9.1

### Additional context
This exact issue had already happened before: https://github.com/SharePoint/sp-dev-docs/issues/4868 "ListView Command Set: event.selectedRows returns wrong ID, when there is a pinned document in the library"

**Comment by oliverlp** [comment] 2020-09-09 09:18
Hi @andrewconnell , this issue has come back. You gave me support back then (#4868), and asked me to keep an eye on #4769. Maybe that one is also affected.

**Comment by andrewconnell** [comment] 2020-09-09 22:13
First thing I'd suggest: upgrade to SPFx v1.11... make sure you're on the latest SPFx as something may have been fixed from the older build you're on...

**Comment by oliverlp** [comment] 2020-09-11 06:15
Hi,
@andrewconnell , thanks a lot for your response. We were “lucky” and the bug was solved in less than a day since detected. It was solved in our tenant without our intervention sometime during yesterday in the morning. So it was active at least a day.
Do you have any idea of why just this type of bug keeps happening? Does it happen now and then? This is the second time my users report it, but I don´t know how often this helps.
It is not possible in my case to update our SPFx solutions utan planing.
Thanks for your support.

**Comment by andrewconnell** [comment] 2020-09-11 13:42
![](https://media.giphy.com/media/w0mylo7p4OXUQ/giphy.gif)

**Comment by Katli95** [comment] 2020-11-20 14:35
Can confirm, this is a problem for a tenant of mine as well :/

**Comment by AJIXuMuK** [comment] 2021-09-07 15:18
Dupe of #6077

**Comment by patmill** [comment] 2021-09-07 18:49
closing, will follow up on #6077

**Closed by patmill** 2021-09-07 18:49 UTC
Labels: type:bug-suspected, status:duplicate, area:spfx, area:spfx-extensions, area:spfx-in-lists
