### ISSUE TITLE
Items Pagination

### ISSUE THREAD

**Issue by DanishIslam07** [SharePoint/sp-dev-docs#2843] opened 2018-10-30 07:31 UTC
How item pagination is handled ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 002a1ee9-dc9f-8dc1-6f3c-ef23297b83d4
* Version Independent ID: 82565c7e-b264-94f5-8708-d4757482e133
* Content: [Use view formatting to customize SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/view-formatting)
* Content Source: [docs/declarative-customization/view-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/view-formatting.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by thechriskent** [comment] 2018-10-30 15:11
I'm closing this one since it is a duplicate of your other issue: #2844 
Thanks!

**Closed by thechriskent** 2018-10-30 15:11 UTC
