### ISSUE TITLE
How to use sp-field-customFormatBackground

### ISSUE THREAD

**Issue by spcrux** [SharePoint/sp-dev-docs#3097] opened 2018-12-12 01:30 UTC
It is not clear how to use sp-field-customFormatBackground predefined class. Please provide some explanation. Also, it would be great to have some examples. 

#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

**Comment by Seiyasu** [comment] 2018-12-12 09:21
Duplicate of #3089

**Closed** 2018-12-12 18:32 UTC
Labels: area:list-formatting
