### ISSUE TITLE
App Customizer navigatedEvent not firing between List View pages

### ISSUE THREAD

**Issue by jivkopetiov** [SharePoint/sp-dev-docs#5990] opened 2020-07-02 15:30 UTC
## Category

- [x] Bug

## Describe the bug

Very simple SPFX Application Customizer that executes code on every page in a modern Team site. This is the code in the onInit() function in the customizer: 

` this.context.application.navigatedEvent.add(this, (_) => {
      console.log("navigatedEvent");
    });`

When navigating between modern SitePages, the code runs normally and the message is printed on the console. When navigating between List View pages (Lists/List1/AllItems.aspx to Lists/List2/AllItems.aspx), the code doesn't run and the browser console shows this error message:
![image](https://user-images.githubusercontent.com/179188/86377898-9daf1b80-bc91-11ea-91fe-be1abdbe9f2a.png)

## Environment details (*development & target environment*)

- **Target Environment**: SharePoint Online, Modern team site
- **Tooling**: SPFX 1.10.0, Node 8.9.4
- **Browser(s)**: All browsers

All aspx pages in the site are modern experience pages. The app is built using --ship parameter.

**Comment by andrewconnell** [comment] 2020-07-02 19:49
Seems like a dupe of #4557 & other [known issues here](https://github.com/SharePoint/sp-dev-docs/issues?q=is%3Aissue+is%3Aopen+navigatedEvent), correct?

**Closed** 2020-07-16 22:00 UTC
Labels: Needs: Author Feedback, area:spfx-extensions, no-recent-activity
