### ISSUE TITLE
🐞 Instances of apps created from packages deployed via Site Collection Scoped App Catalogs aren't upgrading

### ISSUE THREAD

**Issue by andrewconnell** [SharePoint/sp-dev-docs#1146] opened 2017-12-14 10:56 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
- deploy and trust app package to site collection app catalog
  - *solution & feature within the solution that provisions a site column are version 1.0.0.0*
- create an instance of the app in the same site
- make some changes and update the solution number and feature within the solution... update versions to 2.0.0.0
- deploy solution that upgrades the existing package in the site collection scoped app catalog:

![image](https://user-images.githubusercontent.com/2068657/33988784-761f67dc-e093-11e7-8e55-061e95fa2f99.png)

- go to Site Contents page and either... 
  - (a) don't wait 24 hrs [as explained in this doc](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/update-sharepoint-add-ins#ImmediateUpdateNotice), click the "..." to get an **ABOUT** menu item where you can upgrade the instance or
  - (b) wait 24hrs to see the **UPGRADE** option 

#### Observed Behavior
Neither option (a) above is shown...

![image](https://user-images.githubusercontent.com/2068657/33988801-8630c53a-e093-11e7-8937-275d5be0c017.png)

nor option (b) is working (waited over 36 hours).

#### Steps to Reproduce
See **Expected or Desired Behavior** section above.

**Comment by cwdata** [comment] 2017-12-14 11:07
Hi,
I experienced similar issues. It seems though, that the installed App itself is getting automatically upgraded but the displayed version number in Site contents just stays the same forever.
At least for my SPFx Webparts that is the case which is irritating. I don't have a feature upgrade code in my solutions so I don't know if that would be executed or not.

**Comment by VesaJuvonen** [comment] 2017-12-14 13:06
thx @andrewconnell for reporting this. We'll start working on the issue investigation immediately. I have some hunch on what goes wrong, but good to have this reported here, so that others will know about the issue and that we can more easily track as we proceed with the fix for this.

**Comment by VesaJuvonen** [comment] 2017-12-14 13:23
Just to evolve this - first things first always on our side (engineering) is to build a repro... and we have it with the same results as what @andrewconnell reported. I can confirm that this is clearly a bug, which we'll need to get fixed.

**Comment by JeremyKelley** [comment] 2017-12-14 19:26
One thing to note in the short term as we work on the issue is that you can uninstall the app and reinstall it.  Any associated data shouldn't be lost so you should be able to upgrade that way as a last resort.

**Comment by VesaJuvonen** [comment] 2017-12-15 08:37
Like @JeremyKelley noted, doing uninstall/install is the current workaround for this and no data is being lost with the SPFx solution case when that's being done (SP hosted add-in would be a different story). The bug has been now identified and fixed. We will do final verifications and roll out the fix after that. Due however holiday freeze period, fix will be rolling out in January. We'll follow up on this issue when the fix is fully deployed. Thanks again for the detailed issue reporting and contacting us immediately when you noticed this.  

* ETA for fix arrival - mid-Jan.

**Comment by andrewconnell** [comment] 2017-12-15 11:45
Thanks for the additional followup & detail @JeremyKelley & @VesaJuvonen 

As a bit of feedback, [this might be the best issue summary I've ever seen](https://github.com/SharePoint/sp-dev-docs/issues/1146#issuecomment-351945985) on GH. Concise, clear & everyone can know exactly where the issue is at the moment with an expectation of the resolution. Cheers guys... great to see this coming from this team! :)

**Comment by andrewconnell** [comment] 2017-12-19 13:34
@JeremyKelley & @VesaJuvonen - Can I get a clarification on what @JeremyKelley said [here](https://github.com/SharePoint/sp-dev-docs/issues/1146#issuecomment-351811102). When you say:

> you can uninstall the app and reinstall it. Any associated data shouldn't be lost so you should be able to upgrade that way as a last resort

Are you saying I can uninstall the app from the Site Catalog App Catalog & reinstall it once it's been removed & that would apply v2 of my feature? Part of my provisioned feature v2 includes an upgrade action that applies an element manifest (creating a new site column) & adds the column to a content type that should apply to the list the v1 feature provisioned. If I remove the app and reinstall it, I'm getting an error (typical SP error with no details but a correlation ID) which I presume is because it's trying to recreate the list that already exists from the first time I installed the app.

As such, I can't test the feature upgrade actions within a SPSite scoped app catalog. If that's expected and I need to wait until mid-January, that's fine. Just trying to get clarification on the workaround mentioned above as it's not what I'm experiencing.

**Comment by mcmynn83** [comment] 2018-01-18 23:36
This fix has now rolled out to production and you should no longer be seeing the issue.  Please respond if it is still a problem for you.

**Closed by mcmynn83** 2018-01-18 23:36 UTC
Labels: status:fixed-next-drop, status:tracked, type:bug
