### ISSUE TITLE
I unable to build package for SPfx 1.5 version

### ISSUE THREAD

**Issue by rajput9997** [SharePoint/sp-dev-docs#2076] opened 2018-06-20 12:49 UTC
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

I created SPFx webpart solution along with ReactJs framework. while I build the package solution using `gulp bundle --ship`, I unable to finish build successfully and following error showing into logged.

`The build failed because a task wrote output to stderr.`

![image](https://user-images.githubusercontent.com/40427548/41658704-dcba0172-74b4-11e8-9e9f-8f71fef37e66.png)

 I believe due to above screenshot error, i unable to complete `gulp package-solution --ship`. I've used `includeClientSideAssets": true` into package-solution.json file.

My Attempts: 
> I checked all version of packages and all are updated. I've confirmed through `npm updated`.

I executed following command to get clean and again build the solution.

> gulp clean
> gulp build
> gulp build --ship (failed on this case and error shown above screenshot)

Following attached screenshot for package.json file 

![image](https://user-images.githubusercontent.com/40427548/41658973-aab9c22e-74b5-11e8-8220-932e976cecc2.png)

I'm not sure what is missing part from my end?

Thanks!

**Comment by PooLP** [comment] 2018-06-20 12:57
Hi,
React 16 don't work with 1.5.0 Framework, use React 15.

**Comment by rajput9997** [comment] 2018-06-20 13:21
Hi @PooLP , Thanks for your promptly response. I upgraded package solution back to react 15 version and installed into project as well globally but it doesn't resolve my issue yet.

![image](https://user-images.githubusercontent.com/40427548/41660851-df8ead66-74ba-11e8-9a4e-9777715dbd37.png)

**Comment by PooLP** [comment] 2018-06-20 13:27
After downgrading, delete package-lock.json file en node_modules, lib, dist and temp directory and re-run npm install, after, run gulp bundle --ship and gulp package-solution --ship

**Comment by val0o** [comment] 2018-06-20 15:08
Hi folks,
I have same issue after trying to upgrade from 1.4.1 to 1.5.0. I have already removed the package-lock.json and reinstalled all node modules without success.
It does not prevent from having a final package but for instance the styles are not applied to my ApplicationCustomizer extension.
![image](https://user-images.githubusercontent.com/22765276/41667139-8a87009c-74ac-11e8-9f49-43441de82c25.png)

**Comment by PooLP** [comment] 2018-06-20 16:37
which version of node.js/npm you are using ?

**Comment by rajput9997** [comment] 2018-06-20 18:18
The steps doesn't help out to resolve the issue and showing same error. 
nodejs version - v8.5.0
npm version - 6.1.0

**Comment by val0o** [comment] 2018-06-21 06:10
nodejs version - v8.11.2
npm version - 6.1.0

**Comment by PooLP** [comment] 2018-06-21 06:13
This day, I will test this https://github.com/waldekmastykarz/docker-spfx, i don't have your probleme, but I have anothers problems

**Comment by WickedTheToy** [comment] 2018-06-21 13:17
Hello,
I have the same problem.

nodejs version - v8.11.2
npm version - 6.1.0

![capture](https://user-images.githubusercontent.com/40465301/41721421-1bc56ada-7566-11e8-86ac-df4a427c7c48.PNG)

**Comment by waldekmastykarz** [comment] 2018-06-21 18:04
Have you tried creating a new project from scratch and comparing the differences between the new one and yours just to be sure you haven't missed anything?

**Comment by val0o** [comment] 2018-06-22 06:49
@waldekmastykarz Yes I have compared the files in the config folder and gulpfile, tsconfig, .yo-rc.jspackage.json but did not find anything.
Actually it seems to be related to sass in --ship mode, I notice that I can deploy the final package and assets but I don't have the CSS applied to my ApplicationCustomizer extension.
I hope it can give you a clue?

**Comment by waldekmastykarz** [comment] 2018-06-22 06:51
Thanks for the additional info @val0o. Are you getting the same issue with a vanilla SPFx@1.5.0 project?

**Comment by val0o** [comment] 2018-06-22 06:55
@waldekmastykarz  Indeed, I have the same issue with a vanilla SPFx ApplicationCustomizer extension

**Comment by waldekmastykarz** [comment] 2018-06-22 06:58
@val0o that might be worth submitting a separate issue. With SPFx@1.5.1 coming soon it would be good to have it double checked by the engineering

**Comment by rajput9997** [comment] 2018-06-22 09:46
@waldekmastykarz @val0o  - Hi All, I've producing the same error even in new project. When i updated to 1.4.1 version, it seem to working fine.

**Comment by GwSoJ** [comment] 2018-06-25 10:28
I can confirm that the default build of the hello-world webpart also has the --ship error. Same error exaclty as is mentioned above. I have built and packaged multiple solutions with this hardware before so this is new. I also built a brand new machine and ran through the tutorial exactly and I am gettign the same --ship error on that new machine also.

**Comment by nateforsyth** [comment] 2018-06-25 22:56
I as well can confirm that the update from 1.4.1 to 1.5.0 caused the issue encountered by the OP.

I'm pretty new to all of this, thought I'd share my steps to roll back to version 1.4.1.

Firstly, uninstall the sp-* packages.
`npm uninstall @microsoft/sp-dialog`
`npm uninstall @microsoft/sp-application-base`
`npm uninstall @microsoft/decorators`
`npm uninstall @microsoft/sp-core-library`
`npm uninstall @microsoft/sp-listview-extensibility`
`npm uninstall @microsoft/sp-lodash-subset`
`npm uninstall @microsoft/sp-office-ui-fabric-core`
`npm uninstall @microsoft/sp-webpart-base`
`npm uninstall @microsoft/sp-build-web`
`npm uninstall @microsoft/sp-webpart-workbench`
`npm uninstall @microsoft/sp-extension-base`
`npm uninstall @microsoft/sp-http`
`npm uninstall @microsoft/sp-module-interfaces`

Next I reinstalled the desired versions of each.
`npm install @microsoft/decorators@1.4.1 --save`
`npm install @microsoft/sp-office-ui-fabric-core@1.4.1 --save`
`npm install @microsoft/sp-core-library@1.4.1 --save`
`npm install @microsoft/sp-application-base@1.4.1 --save`
`npm install @microsoft/sp-extension-base@1.4.1 --save`
`npm install @microsoft/sp-module-interfaces@1.4.1 --save`
`npm install @microsoft/sp-build-web@1.4.1 --save`
`npm install @microsoft/sp-webpart-base@1.4.1 --save`
`npm install @microsoft/sp-lodash-subset@1.4.1 --save`
`npm install @microsoft/sp-listview-extensibility@1.4.1 --save`
`npm install @microsoft/sp-dialog@1.4.1 --save`
`npm install @microsoft/sp-http@1.4.1 --save`
`npm install @microsoft/sp-webpart-workbench@1.4.1 --save`

I then pruned and cleared the cache.
`npm-prune`
`npm cache clean --force`

Clean, build, and shrinkwrap.
`gulp clean`
`gulp build`
`npm shrinkwrap`

I've then tested in the workbench prior to building a shipping package and deploying to a test tenant.

**Comment by VesaJuvonen** [comment] 2018-06-26 17:51
We are closely looking into fixing this soon. Thanks for reporting.

**Comment by ratnakumarpaleru** [comment] 2018-06-27 17:00
i am also having the same Issue...
is this issue got resolved...
Please suggest any fix

**Comment by mcmynn83** [comment] 2018-06-27 21:07
Could somebody help clarify the issue?  I see the issue:
The build failed because a task wrote output to stderr.
Exiting with exit code: 1
 
That is an extraneous error that doesn't actually affect things.  It is printed because of the following message being written to stderr:
[13:21:52] [typescript] TypeScript version: 2.4.2
Warning: no-duplicate-case rule is deprecated. Replace your usage with the TSLint no-duplicate-switch-case rule.
Warning: valid-typeof rule is deprecated. Replace your usage with the TSLint typeof-compare rule.
 
That being said, you can still package your solution etc.  Is there a scenario that this is blocking somebody from completing?  Sorry if I'm totally missing something.

If that error is bugging you, it is possible to fix your solution by following the instructions in the error.  You can change no-duplicate-case to no-duplicate-switch-case in ./temp/tslint.json as well as remove valid-typeof (typeof-compare has also been deprecated and is redundant in 2.4.1).  
 
All that being said, it does show up as an error and we will fix it, but I want to understand what is currently blocked incase I am missing something.

Thanks!
Graham

**Comment by val0o** [comment] 2018-06-28 06:04
Hi @mcmynn83, in my case I have a mix of extensions and webparts in my project. Indeed despite the error messages I can get a valid package to deploy. However I notice that the sass classes applied to my extension are not applied, which was working with 1.4.1.
I guess it is fixed in 1.5.1 with the following 

> Fixed the issue in the yeoman generator that blocked you from creating different types of components in your package
I did not test yet with this version

**Comment by VesaJuvonen** [comment] 2018-06-28 06:36
HI @val0o, that fix is not actually for fixing anything in the Sass side, so it will not fix this in 1.5.1. That issue clearly got buried in these comments as this issue was around the unnecessary exception message with bundling. If the sass packaging is an issue for you, please do open up a new issue as we cannot track multiple problems in one issue - since they will be also assigned to different persons internally.

sorry for missing that, but having it as the separate report will absolutely help on providing it the needed attention.

**Comment by val0o** [comment] 2018-06-28 06:54
Thanks for your answer @VesaJuvonen , so I open a new ticket for the Sass issue

**Comment by rajput9997** [comment] 2018-06-28 07:01
Hi - I upgraded my package solution to 1.5.1 version and quickly test existing project as well create a new framework project, I've troubleshoot with same error and due to failed of build --ship I unable to see any deployment assets files inside the temp/Deploy folder. I wondering to see to be working fine after downgrading to 1.4.1.
Is it related to package version?
![image](https://user-images.githubusercontent.com/40427548/42018200-f7e76c94-7ace-11e8-9bdb-3148cf7dbb6f.png)

**Comment by gzhou2018** [comment] 2018-06-28 21:59
Have the same issues anyone has the solution?
![image](https://user-images.githubusercontent.com/35809166/42062827-f73b53b8-7afc-11e8-97b1-2295fb658c6a.png)

**Comment by a2life** [comment] 2018-07-04 19:01
I was having the same issue so I  rerouted stderr out to erro file and here is what I saw

gulp --ship 2>error.txt

```
 Warning: no-duplicate-case rule is deprecated. Replace your usage with the TSLint no-duplicate-switch-case rule.
 Warning: valid-typeof rule is deprecated. Replace your usage with the TSLint typeof-compare rule.
 [33mWarning - tslint - src/webparts/helloWorld/HelloWorldWebPart.ts(131,31): error semicolon: Missing semicolon[39m
 [33mWarning - tslint - src/webparts/helloWorld/HelloWorldWebPart.ts(145,11): error semicolon: Missing semicolon[39m
The build failed because a task wrote output to stderr.
```
So all the TSlint output is going to stderr .   If I follow the recommendations in the error output,  it still complained "typeof-compare' is now internally handled by TypeScript 2.2 and above etc.,", so I removed 
the option and added semicolons to the source file.

go to config/tslint.json and modify as follows
"no-duplicate-case" -> "no-duplicate-switch-case"
delete "valid-typeof" line
set "semicolon" to false, or   correct the source file.

save


Now gulp --ship works in my environment.     using version 1.5.1

**Comment by PooLP** [comment] 2018-07-05 06:21
@a2life it work for me and fix this issue : https://github.com/SharePoint/sp-dev-docs/issues/2077

**Comment by WickedTheToy** [comment] 2018-07-05 08:59
@a2life thanks a lot

**Comment by VesaJuvonen** [comment] 2018-07-05 17:53
Closing as a fixed one. Thanks, everyone for confirming and reporting.

**Closed by VesaJuvonen** 2018-07-05 17:53 UTC
Labels: area:framework, status:tracked, type:bug

**Comment by cythomli** [comment] 2018-07-06 17:50
@nateforsyth thanks for the steps. On trying to uninstall the packages, I get the following error:

![image](https://user-images.githubusercontent.com/6519992/42393187-6b432ee4-810a-11e8-923f-dcf5295c6a56.png)

Please let me know if you have encountered the issue.

Thanks!
