### ISSUE TITLE
Allow Debug scripts keeps popping up on production sites

### ISSUE THREAD

**Issue by russgove** [SharePoint/sp-dev-docs#1098] opened 2017-11-30 02:29 UTC
#### Category
- [ x] Question
- [ ] Typo
- [x ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
The 'Allow debug scripts?' popup should not appear on production sites!

#### Observed Behavior
I 've been working on an application customizer on one site collection  and using the query parameters to get it loaded. In SOME cases when I go to a completely unrelated site collection   (the application customizer has never been installed on), with NO query parameters  I get  the popup asking 'Allow debug scripts?'

#### Steps to Reproduce
Not sure???

Can we have the Allow debug scripts popup give some indication of what scripts it is trying to load?

**Comment by waldekmastykarz** [comment] 2017-11-30 06:44
Could it be that the query string parameters loading your local extension are still present in the URL? The popup is explicitly designed to warn users in production tenants from loading scripts that haven't been deployed to the app catalog.

**Comment by luismanez** [comment] 2017-11-30 07:52
Try to "Clear Site Data" from Chrome Dev tools (or Clear cache in other browsers). I´ve seen that behavior sometimes after debugging extensions (even in a different site collection and with no query string). I think is something store in the browser local storage...

**Comment by VesaJuvonen** [comment] 2017-12-02 09:15
This is pretty much by design in the development experience since some debugging information is retained in the cookies of your browser after you do debugging. You can clear the cookie with browser dev tools or by adding ?reset=true to address bar. We are potentially looking into adjusting this behaviour slightly in future, but will close this for now, since this is "by design" experience for developers.

**Closed by VesaJuvonen** 2017-12-02 09:15 UTC
Labels: area:framework, type:question
