### ISSUE TITLE
Office UI Fabric grid fails for sites not on first release for selected users

### ISSUE THREAD

**Issue by wobba** [SharePoint/sp-dev-docs#717] opened 2017-07-11 11:14 UTC
#### Category
- [x] Bug

#### Expected or Desired Behavior
Yesterday my grids worked just fine with this sample code in a tenant without first release:

```html
<div className="ms-Grid">
	<div className="ms-Grid-row">
		<div className="ms-Grid-col ms-u-sm3">
			three
		</div>
		<div className="ms-Grid-col ms-u-sm9">
			nine
		</div>
	</div>
</div>
```

The grid shown fine with two columns with 3/12ths and 9/12ths

#### Observed Behavior
Today, the classes for column widths like `ms-u-sm3` are not available on the page, so columns are rendered incorrectly. The classes for `ms-Grid-row` and `ms-Grid-col` are there.

This happens on both /layouts/15/workbench.aspx and on an actual page, but not on the local workbench.

I have tested via the workbench on other tenants, and on some it works, on others it breaks. Seems to be inconsistent.

#### Steps to Reproduce
Create a new web part, use the above grid in your markup and see if columns are rendering the way they should when testing on _/layouts/15/workbench.aspx.

**Comment by pgonzal** [comment] 2017-07-12 02:00
Thanks for reporting this.  This issue was caused by a recent change in [office-ui-fabric-core](https://github.com/OfficeDev/office-ui-fabric-core/pull/902), which renamed these attributes to remove the "u-" prefix.  We are currently investigating whether there is a way to fix already released web parts that were impacted by this change.

**Comment by wobba** [comment] 2017-07-12 06:19
Thank you, seems it's rolled back and working now. I'm fine enough with a change as long as I know about it :) but then you have to update https://dev.office.com/fabric#/styles/layout as well to reflect the change, or give us controls which wrap the grid css so it renders the same even though the backend switch.

**Comment by patmill** [comment] 2017-07-27 17:18
So currently it is unsupported to use fabric core with SPFX.  Of course, we haven't given a supported way of using it, so it's understandable that it is being used.  We're almost ready to roll out a supported method so that when fabric-core changes, your solutions won't be impacted.  Stay tuned.

**Comment by wobba** [comment] 2017-08-03 11:52
Thank you for the update. So in the mean time I guess bundling your own prefixed fabric css in SPFx is the robust way(?)

**Comment by srideshpande** [comment] 2017-08-07 21:38
Hello @wobba  - yes that's correct. As Pat said, we are working on a better solution and will be out soon. 

And also, since the issue is resolved. I am closing this issue. Please feel free to open a new issue if you think the issue still exists.

Thanks,
Srikanth

**Closed by srideshpande** 2017-08-07 21:38 UTC
