### ISSUE TITLE
Sharepoint framework Dialog not working on classic page

### ISSUE THREAD

**Issue by oOMelon** [SharePoint/sp-dev-docs#2838] opened 2018-10-29 13:16 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Dialog box should open on classic pages.

#### Observed Behavior

I have a DocumentWizard built with SPFX in Sharepoint. We have added it as a CommandSet and as a webpart.

The webpart on classic pages doesn't work anymore, on the CommandSet it works fine. It has worked without problems before, I was just informed by my client today.

When opening the dialog it's just a blank box. I get no error message. What I can see is some logs when running gulp serve:

[DialogManager] New request to show a dialog has been submitted.
[BaseDialog] Dialog state changed from 'New' to 'Pending'.
[BaseDialog] Dialog state changed from 'Pending' to 'Approved'.

Version used is 1.4.1 I also tried updating that to latest 1.6.0 but it didn't make a difference.

In chrome i tried calling another show() and then it works but that brings other problems so I can't use that...

Code: 

```
const dialog: DocumentWizard = new DocumentWizard(false);
		dialog.show().then(() => {
			console.log('Closed!');
		});

export default class DocumentWizard extends BaseDialog {

	private uploadDocument: boolean;

	constructor(uploadDocument: boolean) {
		super({ isBlocking: true });
		this.uploadDocument = uploadDocument;
	}

	public render(): void {
		ReactDOM.render(
			<MainComponent
				close={this._close}
				submit={this._submit}
				uploadDoc={this.uploadDocument} />,
			this.domElement);
	}
}
```

#### Steps to Reproduce

Create a SPFX webpart.
Add a component that opens a dialog box. Use code above for reference :)
Add the webpart to a classic page and check if it works.

**Comment by Seiyasu** [comment] 2018-10-30 02:58
I think it'd better you can provide an minimal reproducible sample product, so other guys can further help you more efficiently.

**Comment by oOMelon** [comment] 2018-10-30 10:56
Of course! I have added reproduce steps in the description above :)

**Comment by oOMelon** [comment] 2018-11-22 14:33
Hi again, kinda of a late update here... It works now, I haven't done anything to the code or configuration it just works again 👍

**Comment by lucaband** [comment] 2018-12-17 21:30
Looks like this now works. Closing it.

**Closed by lucaband** 2018-12-17 21:30 UTC
Labels: area:framework, status:tracked, type:bug
