### ISSUE TITLE
White/Blank Screen On Pages With Custom SPFx 1.5.1 App Added For Logged In External B2B Users

### ISSUE THREAD

**Issue by zwinnie** [SharePoint/sp-dev-docs#2234] opened 2018-07-16 17:22 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I'm having an issue where external B2B users are not able to load a SharePoint page with a custom SPFx app added to the page. Pages that do not have a custom SPFx added work normally and load fine. This includes non-editable admin and settings screens. I'm using SPFx version 1.5.1.

#### Observed Behavior

A white page loads with no content or errors in Chrome. The console has logged the following in Chrome: 
- The resource https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-07-06.014/sp-pages-assembly_en-us_da5eb5a69626f924c4bff00388e14408.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

Edge also has a white page loading with the following console errors:
- CSP14304: Unknown source ''strict-dynamic'' for directive 'script-src' in Content-Security-Policy-Report-Only - source will be ignored.
- CSP14313: Resource violated directive 'script-src 'strict-dynamic' 'unsafe-eval' 'nonce-71be3629-5f39-4b6a-aa39-e3e9c92eaebd'' in Content-Security-Policy-Report-Only: https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-07-06.014/sp-pages-assembly_en-us_da5eb5a69626f924c4bff00388e14408.js. Resource will not be blocked due to policy being report-only.

The behaviors above happen in both normal and private browsing modes. The body tag also has no DOM elements loaded in it.

Non-external users have the page rendering correctly along with the custom SPFx webpart in both Chrome and Edge.

#### Steps to Reproduce

- Add a new team site (example /site/mysite)
- Add an App Catalog to /site/mysite via PowerShell
- Create a new SPFx 1.5.1 webpart
- Bundle, package, and upload the webpart to the site's App Catalog
- Add the custom webpart to a page on /site/mysite
- Login with a B2B user that has been granted permissions to /site/mysite
- The page with the custom SPFx webpart will be white/blank

**Comment by steevinBradlee** [comment] 2018-08-01 18:16
Any update on this issue? I'm also experiencing the same behaviour.

**Comment by SipraMishra** [comment] 2018-09-18 14:15
I am also facing the same issue. Any update?

**Comment by mcmynn83** [comment] 2019-05-10 21:47
Is this still an issue?  We have fixed external sharing as long as you use the CDN which I can see you are already doing.

**Comment by steevinBradlee** [comment] 2019-05-17 22:04
This is still an issue I experience when I'm serving files from local host. I know the issues goes away if the files are served from a CDN, but this still means that if you're debugging an extension in development mode, you cannot see how it acts on the Site Contents page as it is blank. I'd hesitate to call this closed until that issue is fixed. Displaying at least some error in the console would be helpful.

**Comment by mcmynn83** [comment] 2019-05-17 22:29
I'm going to close this issue because the root cause bug and work around can be found in issue #2099.

**Comment by mcmynn83** [comment] 2019-05-17 22:31
Actually, I'm going to leave this open to make sure we validate that it is fixed with the long term solution.  Please try the work around found in #2099 in the meantime.

**Closed by mcmynn83** 2019-05-17 22:31 UTC
Labels: Needs: Author Feedback, area:framework, status:tracked, type:bug
