### ISSUE TITLE
List View Command onListViewUpdated does not fire when you click on a list item itself, not on the checkbox.

### ISSUE THREAD

**Issue by pyliakm** [SharePoint/sp-dev-docs#4836] opened 2019-10-29 20:08 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
I tried last version 1.9.1 and onListViewUpdated must be fired when you click on a list item itself.
![screen](https://user-images.githubusercontent.com/14115379/67807517-9ea60280-fa9d-11e9-872b-71bfd58b82eb.png)

#### Observed Behavior
onListViewUpdated is not firing.

#### Steps to Reproduce
Just click on any column on row not on checkbox.

**Comment by andrewconnell** [comment] 2019-10-30 10:02
I think this is a dupe of #4828, can you look and confirm? If so, we'll consolidate to that issue since it came in first...

**Comment by pyliakm** [comment] 2019-10-30 10:06
Duplicate of #4828

**Closed** 2019-10-30 10:33 UTC
Labels: status:duplicate
