### ISSUE TITLE
SharePoint Designer 2013 workflows wont publish to SharePoint Online

### ISSUE THREAD

**Issue by AdamBilski** [SharePoint/sp-dev-docs#5562] opened 2020-04-09 10:20 UTC
Hi All,

I have an issue that i have not seen before.

When trying to publish workflows on any new subsites i receive following error message.

﻿﻿"Errors were found when compiling the workflow. The workflow files were saved but cannot be run.

Advanced Error:

System.InvalidOperationException: Operation failed with error Microsoft.Workflow.Client.AuthenticationException: Authentication Failed. Valid credentials must be provided for one of the following protocols: Bearer. HTTP headers received from the server - ActivityId: cd30d446-0d8d-42d4-8519-c91ea112ca74. NodeId: WFFE_IN_1. Scope: /spo/f39e137b-1a73-489c-b004-eedc84f361e1/7c3ded29-bc35-4cb1-a473-175e2258abf5/2316cae5-e2b1-444e-9aee-78178d25def7. WWW-Authenticate: Bearer realm="a2b6f772-f7c4-484d-b

I have cleared the cache, tried another new subsite to no avail. One existing subsite allow publishing fine. 

The settings of the working Subsite and all other subsites are exactly the same as they inherit from parent.

I have changed Cache settings in SP designer 2013, installed service packs etc. 

I have been on it for 4 days now and cannot work it out.

Please HELP!

**Comment by AdamBilski** [comment] 2020-04-14 11:28
Anybody ?!

**Comment by michael-n-z** [comment] 2020-04-16 05:53
We have the same problem across our whole SPO tenant.
SP 2013 workflows can be saved, but return the same error as yours when published.
Provider hosted apps with workflows also return the exact same error during deployment.

Have you found a solution?

**Comment by pemate** [comment] 2020-04-16 07:14
Hi all, I would recommend that you raise a separate support ticket to get this issue addressed.

**Comment by AdamBilski** [comment] 2020-04-16 07:37
Hi Michael-n-z, I have not managed to solve this issue yet. However i am scheduled to talk with MS SharePoint Designer specialist today so hopefully we can find a solution to it and if we do i will make sure to post it here. I assume you have tried everything that you can find online, like cache clear, service pack installed, SP designer patch installed etc. if not let me know ill provide some links for you as it may help you even tho it didn't help me. 

Regards,

Adam B.

**Comment by michael-n-z** [comment] 2020-04-16 10:34
Hi Adam, for us, everything was working and then stopped, with no changes to our app and workflows. Because I can replicate the problem with both provider-hosted and SP Designer workflows, I don't think the problem is client side.
I have raised a support ticket and will report back with the outcome.
Regards, Michael.

**Comment by AdamBilski** [comment] 2020-04-17 07:38
Hi Michael,

I agree it does not seem like an issue with client although as i said we can still publish them on one site but not any other which is strange. 
However MS seems to be ignoring this fact.
I shall come back once i have anything specific.

Regards,

Adam B.

**Comment by proce** [comment] 2020-04-17 09:37
Hi All,

We have been experiencing the same issue since Sunday (19th April) whenever we are adding a SharePoint Add-In which contains a 2013 Workflow to a SP Site.

> Correlation ID: f7e50a23-5872-4949-be6b-0dd18d9bfe2d
>
> Common App Deployment
>
> There was an error during the operation.
> Details: Operation failed with error Microsoft.Workflow.Client.AuthenticationException: Authentication Failed. Valid credentials must be provided for one of the following protocols: Bearer. HTTP headers received from the server - ActivityId: 03a9bd6a-adb0-44c9-8dc2-1d4f7809cb41. NodeId: WFFE_IN_0. Scope: /spo/ede49e2d-4af2-4b2c-a136-73fa5045c833/4be1f09e-e601-48a8-8c28-877042669c33/6b59c171-28ef-4475-926b-856c3ef650ca. WWW-Authenticate: Bearer realm="a2b6f772-f7c4-484d-b9a6-1d76301f139f", client_id="00000005-0000-0000-c000-000000000000", trusted_issuers="00000001-0000-0000-c000-000000000000@a2b6f772-f7c4-484d-b9a6-1d76301f139f", scope="/spo",Bearer realm="root", client_id="00000005-0000-0000-c000-000000000000", trusted_issuers="rootissuer@root", scope="/". Client ActivityId : f7e50a23-5872-4949-be6b-0dd18d9bfe2d. ---> System.Net.WebException: The remote server returned an error: (401) Unauthorized. at Microsoft.Workflow.Common.AsyncResult.End[TAsyncResult](IAsyncResult result) at Microsoft.Workflow.Client.HttpGetResponseAsyncResult`1.End(IAsyncResult result) at Microsoft.Workflow.Client.ClientHelpers.SendRequest[T](HttpWebRequest request, T content) --- End of inner exception stack trace --- at Microsoft.Workflow.Client.ClientHelpers.SendRequest[T](HttpWebRequest request, T content) at Microsoft.Workflow.Client.WorkflowManagementClient.SendRequest[T](HttpWebRequest request, T content) at Microsoft.Workflow.Client.ScopeManager.PublishScopeInternal(ScopeDescription description, String[] pathSegments) at Microsoft.Workflow.Client.ScopeManager.PublishChildScope(String childScopeName, ScopeDescription description) at Microsoft.SharePoint.WorkflowServices.SPWebWorkflowSecurityContext.CreateServiceGroup(String scopeAddress, ScopeDescription serviceGroup) at Microsoft.SharePoint.WorkflowServices.SPWebWorkflowSecurityContext.CreateOrUpdateServiceGroup(SPWeb lookupWeb, SPAppPrincipal app) at Microsoft.SharePoint.WorkflowServices.SPWebWorkflowSecurityContext.b__11_0() at Microsoft.SharePoint.Utilities.SecurityContext.RunAsProcess(CodeToRunElevated secureCode) at Microsoft.SharePoint.SPSecurity.RunWithElevatedPrivilegesCore(WaitCallback secureCode, Object param) at Microsoft.SharePoint.SPSecurity.RunWithElevatedPrivileges(WaitCallback secureCode, Object param) at Microsoft.SharePoint.SPSecurity.RunWithElevatedPrivileges(CodeToRunElevated secureCode) at Microsoft.SharePoint.WorkflowServices.SPWebWorkflowSecurityContext.SetupApplicationEcosystem().

We have raised two sperate support requests with MS regarding this. The first didn’t provide any additional insights. The second seemed to think that this issue was related to an existing issue that they were deploying a fix for yesterday. However, after testing today the issue still exists.

Regards,
Colin

**Comment by snoop-y** [comment] 2020-04-17 16:05
> We have raised two sperate support requests with MS regarding this. The first didn’t provide any additional insights. The second seemed to think that this issue was related to an existing issue that they were deploying a fix for yesterday. However, after testing today the issue still exists.
> 
> Regards,
> Colin

Are they treat that as a unique problem related to your site collection or as a "global" issue?

**Comment by michael-n-z** [comment] 2020-04-21 00:16
My support ticket made it to the escalations team, and I can confirm that the issue has been resolved for our tenant. 
Hopefully they provide some feedback later today that I can pass on.

**Comment by proce** [comment] 2020-04-21 06:52
@michael-n-z have you been able to install any provider hosted add-ins with workflows since the issue was resolved?

We were doubling checking that this had been resolved on our side but we are now getting a different error:

> Type: Intermittent (Retry operation)
> Component: Common App Deployment
> Error: The operation took too long.
> Correlation ID: 923fd850-9cfc-4b90-9a44-767bf6bb9a91

Regards,
Colin

**Comment by snoop-y** [comment] 2020-04-21 07:20
It seems like this has an impact on several tenants. Really MS just waiting and if it is not escalated one by one there is no solution? I need to fight myself through our helpdesk hierarchy to even raise a ticket in O365 admin :(

**Comment by michael-n-z** [comment] 2020-04-21 08:58
@proce, 
Okay, I can install provider hosted add-ins with workflows (Azure) with no errors.

I tested if I could deploy from VS to our developer site, and I get the same timeout error as you:
> CorrelationId: 8893db3e-b8e9-44ec-85bc-1d3938a930f6
ErrorDetail: The operation took too long.
ErrorType: Transient
ErrorTypeName: Intermittent
ExceptionMessage: 
Source: Common
SourceName: Common App Deployment

note: we can also publish SP Designer 2013 workflows.

**Comment by AdamBilski** [comment] 2020-04-21 10:03
Snoop-y i feel you.... I've been waiting for them to come back to me for a week now (i am chasing everyday) and they don't seem to care much at the moment.

Today i confronted them with fact that other people had this issue resolved already hence they must know the solution... will see what they come back with.

**Comment by snoop-y** [comment] 2020-04-22 07:16
> Hi Michael,
> 
> I agree it does not seem like an issue with client although as i said we can still publish them on one site but not any other which is strange.
> However MS seems to be ignoring this fact.
> I shall come back once i have anything specific.
> 
> Regards,
> 
> Adam B.

Hi Adam,

Could you please check something? Every site/subsite where we have this problem there is a feature  called **Workflows can use app permissions** which cannot be activated. On sites where we have this activated there is no problem.

**Comment by proce** [comment] 2020-04-23 06:54
Just to let you all know I carried out my now morning ritual test and it worked with NO issues!!

Colin

**Comment by snoop-y** [comment] 2020-04-23 07:18
> Just to let you all know I carried out my now morning ritual test and it worked with NO issues!!
> 
> Colin

Yeahh lucky for you I still have the problem (I logged a ticket though so the ball is on their side now) :)

**Comment by michael-n-z** [comment] 2020-04-23 08:50
Hi all, just reporting that all the issues are fixed on our tenant now:
- SPD workflows and provider hosted add-ins with workflows are installing. (original issue)
- Activation of the **Workflows can use app permissions** feature. (original issue/symptom)
- Time-out errors when running add-ins.

We never did get a detailed explanation other than it was "a back end server issue".

@snoop-y.
It wasn't exactly painless convincing them that we weren't to blame, but keep at it and I hope they fix yours soon.

**Comment by snoop-y** [comment] 2020-04-23 12:03
> @snoop-y.
> It wasn't exactly painless convincing them that we weren't to blame, but keep at it and I hope they fix yours soon.

I am glad finally it worked out for you.
So what was the magic word that you used then? :octocat:

**Comment by snoop-y** [comment] 2020-04-28 15:42
> My support ticket made it to the escalations team, and I can confirm that the issue has been resolved for our tenant.
> Hopefully they provide some feedback later today that I can pass on.

Hi Michel,

Is there any way to tell them others have this issue as well? It looks like MS does not put the pieces together and the different tickets get investigated one by one...

**Comment by michael-n-z** [comment] 2020-04-29 03:44
@snoop-y 
That's not good that your still doing battle with them.

I sent them this thread as part of my efforts, and I know they were reading it.

I don't know for sure how the system works, but my Support Ambassador said that engineering didn't communicate awareness of the problems, and this left the support teams in the dark as to how to proceed. (there were multiple cases).

I can't see any harm in giving you my case number if you think it would help?

**Comment by snoop-y** [comment] 2020-04-29 05:22
@michael-n-z 
I would be ever so grateful if you could do that so I can point them to the right direction :)

**Comment by michael-n-z** [comment] 2020-04-29 07:23
@snoop-y 
cool, its case # 19482426

**Comment by proce** [comment] 2020-04-29 12:00
@snoop-y I asked for a copy of the post incident report after the issue got resolved and I have just received the following message:

> I am afraid there is no post incident report. This is because it was never logged as a service incident and was just brought up by a few agents in my department.
It never made it to the engineers before it self resolved itself am afraid. 

This sounds like they have no idea what the problem was in my case.

**Comment by snoop-y** [comment] 2020-05-04 14:21
Yep that is my feeling as well. They have no idea what is going on...

**Comment by snoop-y** [comment] 2020-05-04 14:23
hey @msft-github-bot would be nice to notify your human owner to read this topic and start to escalate this...

**Comment by snoop-y** [comment] 2020-05-13 08:02
We still have the problem (MS is still investigating) how about on your side @AdamBilski ?

**Comment by snoop-y** [comment] 2020-05-25 12:05
Finally our issue has been escalated to engineer level and after that got resolved very quickly.
Post incident report:
The tenant level **Workflow End Points** got refreshed at back-end which fixed the authentication issues.

**Closed** 2021-12-29 14:55 UTC
Labels: type:question, area:other, Needs: Attention :wave:, Needs: Context Detail :question:, listmaintenance-oldissues
