### ISSUE TITLE
`Dialog.alert` doesn't work in Application Customizer tested on modern page

### ISSUE THREAD

**Issue by waldekmastykarz** [SharePoint/sp-dev-docs#1645] opened 2018-04-12 11:04 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Alert dialog box is displayed on the screen.

#### Observed Behavior

No dialog box is displayed on the screen. No errors in the console.

#### Steps to Reproduce

1. Create new SharePoint Framework project using generator v1.4.1
1. Create new solution using the latest bits (for use with SPO only)
1. Add new extension
1. Add Application Customizer, use default values for name and description
1. Run `gulp serve`, copy the query string parameters and add them to a modern page URL in your tenant
- application customizer is loaded properly, and you can step through its code, but the alert is not displayed.

**Comment by VesaJuvonen** [comment] 2018-04-12 12:08
Can you @waldekmastykarz confirm that this works if you go to a list or library, but does not work on modern pages? - This is what I noticed with initial verification, just looking for confirmation on the behavior also from your tenant. Thx.

**Comment by waldekmastykarz** [comment] 2018-04-12 12:24
Correct: the alert shows as expected on list pages, but doesn't show on modern pages.

**Comment by VesaJuvonen** [comment] 2018-04-12 16:12
This actually works if the code has been deployed and hosted from CDN - but the issue is only there on modern pages if you do debug of extension with Dialog code from localhost. So - luckily not impacting any existing extensions out there, but impacting obviously development time experience as you cannot test the Dialog functionality on modern pages until you have deployed your solution to app catalog. Absolutely something we need to investigate on engineering side still.

**Comment by rishabhymathur** [comment] 2019-04-22 17:26
Based on my testing, once the application customizer is deployed via app catalog, it loads the alert dialog on SPO mobile app the first time you access the site. For the alert to show again, i am having to kill and reload the app. Is this a known behavior or am i missing something? Any workarounds?

**Comment by AJIXuMuK** [comment] 2021-09-03 20:53
Seems to be fixed by now. I see the dialog on both Pages and Lists/Libraries.

**Closed** 2021-09-07 18:58 UTC
Labels: area:spfx, status:tracked, type:bug-confirmed
