### ISSUE TITLE
The requiresCustomScript property (or its predecessor safeWithCustomScriptDisabled) are not in the manifest included in the elements XML file

### ISSUE THREAD

**Issue by waldekmastykarz** [SharePoint/sp-dev-docs#982] opened 2017-10-23 12:06 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
The **requiresCustomScript** property is included in the deployed manifest exactly the way it was defined in the source manifest.

#### Observed Behavior
The **requiresCustomScript** property (as well as its predecessor **safeWithCustomScriptDisabled**) are not included in the deploy version of the manifest.

#### Steps to Reproduce
- scaffold new project using generator v1.3.2 (no matter if online or onprem)
- add web part with defaults
- `$ gulp bundle`
- `$ gulp package-solution`
- confirm that manifest in **dist** has the **requiresCustomScript** property included
- check the manifest in **sharepoint/solution/debug/[guid]/WebPart_[guid].xml**
- 💥 property **requiresCustomScript** is not mentioned in the manifest

The same issue can be reproduced using generator v1.1.0 checking for the **safeWithCustomScriptDisabled** property.

**Comment by nickpape-msft** [comment] 2018-01-11 00:18
Assigning to @lahuey

**Comment by lahuey** [comment] 2018-01-11 01:11
@waldekmastykarz This behavior is by design for server compatibility reasons.

The requiresCustomScript manifest property is equivalent to the inverse of the ReturnIfCustomScriptDisabled xml attribute. The default value for ReturnIfCustomScriptDisabled on the server is true, so the presence of the ReturnIfCustomScriptDisabled property is only necessary in the scenario that requiresCustomScript property is set to true (which results in ReturnIfCustomScriptDisabled .

Feel free to open this issue if the requiresCustomScript property isn't functioning as expected. Thanks!

**Closed by lahuey** 2018-01-11 01:11 UTC
Labels: area:tooling, type:bug

**Comment by waldekmastykarz** [comment] 2018-01-11 10:49
Thank you for the clarification @lahuey. This works indeed as you mentioned. It would be good to have this clarified in the docs @VesaJuvonen.
