### ISSUE TITLE
Error can't find stylesheet to import

### ISSUE THREAD

**Issue by mtspsn** [SharePoint/sp-dev-docs#8939] opened 2023-05-02 11:42 UTC
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version: 112.0.1722.58
- SPFx version: 1.17.1
- Node.js version: v16.10.0

### Describe the bug / error

When using the sharepoint generator 1.17.1 to build a web part the project cannot be built because of following error:

Error - sass - src\webparts\samTest\components\SamTest.module.scss(1,9): error Error: Can't find stylesheet to import.
@import '~@fluentui/react/dist/sass/References.scss';
src\webparts\samTest\components\SamTest.module.scss 1:9  root stylesheet

When checking the package.json dependencies there is no fluentui but "office-ui-fabric-react": "^7.199.1"
When checking the node_modules folder @fluentui/react there is no dist folder

### Steps to reproduce

1. yo @microsoft/sharepoint
2. type client-side component -> WebPart
3. template -> React

### Expected behavior

The default project created by the generator should be built without any errors.

**Comment by AJIXuMuK** [comment] 2023-05-02 13:28
@mtspsn - thank you for reporting the issue.
We are aware of the regression appeared and are working on the fix.
In a meawhile you can replace `@fluentui/react` with `office-ui-fabric-react` - it should resolve the issue.

**Comment by AJIXuMuK** [comment] 2023-05-02 18:29
@mtspsn - just to shed some light - the issue is due to the latest release of Fluent UI React (v8.109.0) that is indirectly referenced in SPFx solutions. This version is missing some JS bits.

**Comment by BobFleischman** [comment] 2023-05-02 22:06
The other fix us just to run **npm i @fluentui/react@7.204.0** on the project and then no changes are needed in the generated code,

**Comment by BobFleischman** [comment] 2023-05-02 22:10
or replace the import statement with 
@import '~office-ui-fabric-react/dist/sass/_References.scss';

Notice the underscore before the term 'References'

**Comment by stevebeauge** [comment] 2023-05-03 21:17
@AJIXuMuK #8945 is not a dupe of this one. This issue targets a regression specific to @fluentui/react dependency, while my issue concerns phantom dependencies. @fluentui/react is only part of the missing dependencies and the focus is not specific to it.

**Comment by AJIXuMuK** [comment] 2023-05-09 13:35
fixed in 1.17.2

**Closed by AJIXuMuK** 2023-05-09 13:35 UTC
Labels: type:bug-suspected, area:spfx, status:tracked
