### ISSUE TITLE
Teams SPFX App context.aadHttpClientFactory.getClient("clientID") fails with AADSTS50058 on Desktop

### ISSUE THREAD

**Issue by tknaller** [SharePoint/sp-dev-docs#9043] opened 2023-06-28 05:23 UTC
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Linux

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [X] other (enter in the "Additional environment details" area below)

### Additional environment details

SPFx Version 1.15.2, also tested with 1.17.4

Error only occurs on Teams Desktop, Version known not to work is 1.6.00.16472 (64-bit). Teams on the web (Firefox, Edge, Chrome, ...) works fine.

### Describe the bug / error

when using context.aadHttpClientFactory.getClient("clientID") to request data from an AzureAD Secured Azure Function, it fails with  either `AADSTS50058: A silent sign-in request was sent but none of the currently signed in user(s) match the requested login hint. `or `AADSTS50058: A silent sign-in request was sent but no user is signed in.`

This happens only on Teams Desktop, not on Web and not when using the SPFX Webpart in SharePoint.

Same issue was described in https://github.com/SharePoint/sp-dev-docs/issues/4840 and https://github.com/SharePoint/sp-dev-docs/issues/4476 and https://github.com/SharePoint/sp-dev-docs/issues/3147

### Steps to reproduce

1. Create SPFX Project
2. Create AzureAD App Registration
3. Create aadHttpClient for that App Registration via context.aadHttpClientFactory.getClient("clientID")
4. Try to use this aadHttpClient on any URL (doesn't matter, it's only about the AzureAD Authentication)
5. Receive Error on Teams Desktop, not on Web ---- and funnily: not on every AzureAD Tenant, tested on multiple, App Registration was configured the same....

### Expected behavior

Successfully making a request to the specified URL

**Comment by lucabandMSFT** [comment] 2023-06-28 15:16
hey @tknaller , thanks for reaching out.

To be sure I understand the issue: that is happening only on Teams desktop and not even on every tenant, is that correct?
For the tenants where it doesn't work, do you have any particular configuration like guest users or users from different tenants?

Thanks

**Comment by tknaller** [comment] 2023-06-28 22:47
hello @lucabandMSFT, thank you for taking the time.

well i suppose there is a difference but i was unable to find out where. i comporaed condititonal access, the app registration, users, userprincipalnames etc. but it all looks the same - I also think there has to be a difference but i have no clue how to pinpoint that. I also unsuccessfully compared the teams admin centers of working vs non-working tenants, looking for any policies. and unfortunately also machine policies are out of question as it happens as well as mac os as on windows and also it works with one tenant and not with the other on the same machine; doesn't matter whether i log out and back in as the other user or even use a different local user on the machine, the behaviour is always the same.

what can affect the silent login on the teams desktop client?

**Comment by tknaller** [comment] 2023-06-30 11:45
i am glad I'm not the only one. i already spent multiple days trying to figure this out and everything on the internet points to me doing exactly what I'm supposed do, but still it doesn't work...

**Comment by lucabandMSFT** [comment] 2023-06-30 15:12
@tknaller @arnoldmatusz, would be possible for us to have access to one tenant where the issue reproes consistently?

**Comment by arnoldmatusz** [comment] 2023-06-30 15:24
> @tknaller @arnoldmatusz, would be possible for us to have access to one tenant where the issue reproes consistently?

Hi, meanwhile I do have an account within our own tenant and I can reproduce the issue consistently. So where do I contact you?

**Comment by arnoldmatusz** [comment] 2023-06-30 20:55
> @tknaller @arnoldmatusz, would be possible for us to have access to one tenant where the issue reproes consistently?

I've just installed the newest version, published just a few hours ago, (You have Microsoft Teams Version 1.6.00.17564 (64-bit). It was last updated on 30.06.2023.) ... and I can't reproduce the issue anymore. Tested in multiple tenants.

@tknaller what about you?

**Comment by lucabandMSFT** [comment] 2023-06-30 21:22
Hey everyone,
I want to provide an update: we found a regression and put a fix in place. The fix is rolling to production tenants and it will take approximately 1 week to reach 100% completeness.

If you see the issue being resolved in your tenant, it means that your tenant got updated. No updated versions of Teams clients are required: all the changes roll out automatically with no action required by administrators or users.

I will keep this issue open until I get confirmation that every tenant is up to date.

Thanks everyone for the help identified this issue.

**Comment by tknaller** [comment] 2023-06-30 21:23
thank you, already working on my side!

**Comment by arnoldmatusz** [comment] 2023-06-30 21:33
> 



> Hey everyone, I want to provide an update: we found a regression and put a fix in place. The fix is rolling to production tenants and it will take approximately 1 week to reach 100% completeness.
> 
> If you see the issue being resolved in your tenant, it means that your tenant got updated. No updated versions of Teams clients are required: all the changes roll out automatically with no action required by administrators or users.
> 
> I will keep this issue open until I get confirmation that every tenant is up to date.
> 
> Thanks everyone for the help identified this issue.

Thanks a lot. I'd be extremely grateful, if you could take a look at #9014  
The issue feels a little similar, calling a web service using the aadHttpClientFactory fails on an iPhone. The call will only work first time after the deployment of the SPFx package. Every time after that it doesn't work anymore.

**Closed** 2023-10-10 20:27 UTC
Labels: area:spfx, status:working-on-it, type:bug-confirmed
