### ISSUE TITLE
Need to update the debugging way to use the serve.json method

### ISSUE THREAD

**Issue by mahmoudhamed** [SharePoint/sp-dev-docs#2144] opened 2018-06-28 13:09 UTC
I think we need to update the debugging method in this article to use the serve.json method mentioned at https://docs.microsoft.com/en-us/sharepoint/dev/spfx/debug-modern-pages

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a6509a7-a5fb-695e-6e1c-e44c42256adf
* Version Independent ID: c65fcc97-888b-eb2a-5b4b-790c85f951d9
* Content: [Tutorial - Migrating from UserCustomAction to SharePoint Framework Extensions](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/guidance/migrate-from-usercustomactions-to-spfx-extensions)
* Content Source: [docs/spfx/extensions/guidance/migrate-from-usercustomactions-to-spfx-extensions.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/extensions/guidance/migrate-from-usercustomactions-to-spfx-extensions.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by thechriskent** [comment] 2018-07-05 15:51
Closing this one since it is a duplicate of #2142

**Comment by thechriskent** [comment] 2018-07-05 15:54
Misunderstood that you were referencing multiple docs with the same issue text, reopening...

**Comment by thechriskent** [comment] 2018-07-05 16:12
Thanks! I have added a note within the debug section to point them towards using serve configurations.

**Closed by thechriskent** 2018-07-05 16:12 UTC
Labels: area:docs
