### ISSUE TITLE
SPFx High Contrast Accessibility setting are not shown in SPFx Teams tabs

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#5530] opened 2020-03-31 10:24 UTC
## Category

- [x] Bug

## Describe the bug
A web part that normally looks like this on a regular SPFx page.

![Screenshot 2020-03-31 at 12 14 42](https://user-images.githubusercontent.com/5503835/78015173-52f7cd80-7349-11ea-98cd-c0f2262dde82.png)

See green border works perfectly on SharePoint in High Contrast mode on an SPFx Page and looks like this.

<img width="755" alt="Screenshot 2020-03-31 at 12 16 36" src="https://user-images.githubusercontent.com/5503835/78015298-876b8980-7349-11ea-8d4f-aaefa5fb03bd.png">

When the same web part gets embedded in Teams the Windows high contrast settings are not properly handled and the web part looks like this.

<img width="571" alt="Screenshot 2020-03-31 at 12 18 01" src="https://user-images.githubusercontent.com/5503835/78015525-ce597f00-7349-11ea-9996-7fde0bc6fc08.png">

## Steps to reproduce

1. Deploy Hello World Web Part as a Teams tab
1. Set Windows Setting to use High Contrast Settings.
1. Add the web part to regular SharePoint Page and see how it behaves there
1. Add the web part to Teams tab in Client (it works in Browser - might an Electron issue?)

## Expected behavior

The Microsoft Teams Client actually recognises the High Contrast settings but the IFrame embedded web part turns the background to black. Shouldn't be the same Windows Settings passed through as it works on a regular SharePoint Page. That's at least my assumption cause it just loads a web site.

**Comment by patmill** [comment] 2021-11-16 19:47
Hey @StfBauer - picking up on this.  After digging in for a while here, the problem is that the teams infrastructure is not surfacing the theme setting / OS setting to the iFrame.  We're seeing if they can surface that information.  Ideally, that will be done, and no change will be required by you or us.  As this is more a fundamental Teams issue, I'm going to close this bug from an SPFx / SharePoint perspective.

**Closed by patmill** 2021-11-16 19:47 UTC
Labels: type:bug-suspected, area:spfx, status:to-be-reviewed, area:other

**Comment by StfBauer** [comment] 2021-11-18 20:33
Thanks, @patmill I thought so!
