### ISSUE TITLE
CSS Theme tokens: Local workbench should support the default theme and the __themeState___ object

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#721] opened 2017-07-12 13:47 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
When I create a web part in the workbench I like to use the theme tokens without specifying the default color.
Instead this definition.
```css
.row {
    background-color: "[theme:themePrimary, default:#0078d7]";
}
```
It should be only required to use:
```css
.row {
    background-color: "[theme:themePrimary]";
}
```

#### Observed Behavior
The second variant works perfectly in the Workbench on Office 365 but not in a local workbenchen because not theme is loaded by default. The local workbench should at least include the default Office UI Fabric theme. The __themeState___ object doesn't currently load a theme in the local workbench.
![screen shot 2017-07-12 at 15 39 53](https://user-images.githubusercontent.com/5503835/28120497-7cea7fba-6718-11e7-867b-18ed2b005383.png)

On the Office 365 Workbench the theme is loaded:

![screen shot 2017-07-12 at 15 41 37](https://user-images.githubusercontent.com/5503835/28120555-a640010a-6718-11e7-9cfe-39be3765149b.png)

#### Steps to Reproduce
Create a default web part and define in the css of the web part the ```.row``` element the following way.

```css
.row {
    background-color: "[theme:themePrimary]";
}
```
This will lead to the following results in the local workbench:

![screen shot 2017-07-12 at 15 44 26](https://user-images.githubusercontent.com/5503835/28120692-0832438c-6719-11e7-9c0a-e6954e76eeb9.png)

The exact same web part in the online workbench will be shown like this. Depending on the theme that has been applied to the site.

![screen shot 2017-07-12 at 15 45 42](https://user-images.githubusercontent.com/5503835/28120739-36cbc2cc-6719-11e7-9261-d6353922cb88.png)

**Comment by andrewconnell** [comment] 2017-07-12 14:22
Dupe of #716 ?

**Comment by StfBauer** [comment] 2017-07-12 14:32
@andrewconnell Nope. It is an offical co-production by @waldekmastykarz and me.
While Waldeks issue is on fixing the default web part and guidance around the css tokens, I'm the blogger and responsible for the practical tips dealing with css tokens. ;)

This addresses the bug that no default them is loaded on local workbench, which should be loaded to avoid defaults as fallback.

**Comment by StfBauer** [comment] 2017-07-12 15:27
On Office 365 sites when no theme or default theme is applied this mechanism doesn't work at all without default values. Should then be at least default values specified?

**Comment by spdevdocs** [comment] 2018-04-29 12:26
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*

**Closed by spdevdocs** 2018-04-29 12:26 UTC
