### ISSUE TITLE
Approve api AadHttpClient

### ISSUE THREAD

**Issue by kezack** [SharePoint/sp-dev-docs#1382] opened 2018-02-20 16:19 UTC
**Category**
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

**Expected or Desired Behavior**

I create a new webpart SPFx 1.4.1, I added the rights on package package-solution.json and package the solution.

![image](https://user-images.githubusercontent.com/2874315/36434209-cbfa391a-165e-11e8-922a-bfeca1236f87.png)

I deploy my application in the catalog app.

When approving the rights in api management, I have this error.

![image](https://user-images.githubusercontent.com/2874315/36434277-f866e9da-165e-11e8-8d6b-287122651cb6.png)

Do you have any solutions ?

**Comment by dgaeta** [comment] 2018-02-20 21:55
@kezack Do you currently have any Approved permissions? (They would show up in the second part of the list in your screenshot)

**Comment by kezack** [comment] 2018-02-20 22:08
@dgaeta yes, i am SharePoint Admin

**Comment by dgaeta** [comment] 2018-02-20 23:15
Are any of the currently approved permissions a different "Microsoft Graph" permission? (i.e. the Name of the API is "Microsoft Graph" and the Permission says something else other than "Files.Read")

**Comment by kezack** [comment] 2018-02-21 07:03
@dgaeta no, there is only one permissions "Microsoft Graph => Files.Read".

**Comment by waldekmastykarz** [comment] 2018-02-21 10:52
@kezack just to eliminate that's it not an issue with your tenant: could you try approve the permission request either using the SPO PowerShell or the Office 365 CLI?

**Comment by kezack** [comment] 2018-02-21 13:26
@waldekmastykarz i use Approve-SPOTenantServicePrincipalPermissionRequest and the ressource "Microsoft Graph" is not reconized.

![image](https://user-images.githubusercontent.com/2874315/36481933-bde17cb8-1711-11e8-961f-f44024646cd7.png)

**Comment by waldekmastykarz** [comment] 2018-02-21 16:21
Could you check in your Azure AD > Enterprise applications if you have an app named GraphAggregatorService in there? (be sure to set the filter to include all apps)

**Comment by kezack** [comment] 2018-02-21 16:32
yes, this app are here

![image](https://user-images.githubusercontent.com/2874315/36492232-f1c72152-172c-11e8-817c-87987d806839.png)

**Comment by dgaeta** [comment] 2018-02-21 18:24
@kezack do you mind screen shotting your entire list from the Web UI page? (that includes the pending requests and the approved requests?) I am working in parallel to repro the bug but to avoid confusion it would be helpful to see your entire list.

**Comment by dgaeta** [comment] 2018-02-21 18:42
@kezack Does your tenant have a service principal for Microsoft Graph ?

**Comment by kezack** [comment] 2018-02-21 18:47
@dgaeta How do I know when a service Microsoft Graph in the tenant ?

**Comment by dgaeta** [comment] 2018-02-21 19:31
@kezack are you the tenant admin?

**Comment by kezack** [comment] 2018-02-21 19:33
@dgaeta yes

**Comment by dgaeta** [comment] 2018-02-21 19:41
@kezack Thanks. So there are powershell commands we can use to manage service principals in the tenant.

1. Set up MSOnline V1 PowerShell module for Azure AD 
    - Install the Azure active Directory Connection library from 
      - http://connect.microsoft.com/site1164/Downloads/DownloadDetails.aspx?DownloadID=59185 
      - Select the AdministrationConfig-V1.166.0-GA.msi (be sure to select the last GA version)  

2. Open PowerShell 
3. Check if your tenant has a Microsoft Graph service principal 
    - Powershell command: `Get-MsolServicePrincipal -AppPrincipalId <Guid>`
    - `<Guid>` is the guid for Microsoft Graph in this case `00000003-0000-0000-c000-000000000000`

**Comment by kezack** [comment] 2018-02-21 19:49
yes.

![image](https://user-images.githubusercontent.com/2874315/36501897-b47ed6fc-1748-11e8-89b4-b85227caf629.png)

**Comment by dgaeta** [comment] 2018-02-21 22:16
@kezack Do you mind running the following command in powershell and letting me know the result?
`Get-MsolServicePrincipal -ServicePrincipalName "Microsoft Graph"`

**Comment by kezack** [comment] 2018-02-21 22:21
@dgaeta no problem, the result in screen 
![image](https://user-images.githubusercontent.com/2874315/36508653-94b3bdaa-175d-11e8-9f97-4b36ec87b692.png)

**Comment by dgaeta** [comment] 2018-02-22 00:41
Thanks @kezack we are looking into the issue.

**Comment by kezack** [comment] 2018-03-08 15:14
@dgaeta did you find a solution ?

**Comment by dgaeta** [comment] 2018-03-19 22:53
Try the following in your package-solution.json

```
"webApiPermissionRequests": [
      {
        "resource": "Microsoft.Azure.AgregatorService",
        "scope": "User.ReadBasic.All"
      }
    ]
```
Duplicate of https://github.com/SharePoint/sp-dev-docs/issues/1401

**Closed** 2018-03-19 22:55 UTC
Labels: status:tracked, type:bug

**Comment by semekhlouf** [comment] 2018-05-24 19:40
have you solved this ? i've the same problem when i call an Azure function from SPFX
