### ISSUE TITLE
Full width zone automatically adds padding on the right

### ISSUE THREAD

**Issue by estruyf** [SharePoint/sp-dev-docs#3856] opened 2019-04-29 13:33 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

SInce a couple of days we are experiencing an issue with the full width zone where there is some extra 8px padding added on the right side when page is in view mode. This causes an styling issue to all web parts that want to use the full width of the page.

#### Observed Behavior

![Screenshot 2019-04-29 15 29 54](https://user-images.githubusercontent.com/2900833/56899563-04381880-6a94-11e9-924d-6982a824c12f.png)

![Screenshot 2019-04-29 15 29 09](https://user-images.githubusercontent.com/2900833/56899632-334e8a00-6a94-11e9-9998-b4b0af811b78.png)

#### Steps to Reproduce

- Use a web part that uses the full width of the page, add it to a full width zone;
- Save or publish the page and notice that the 8px padding gets added to the right side.

**Comment by lucabandMSFT** [comment] 2019-05-09 20:34
closing this as it is a dupe of #3686

**Comment by estruyf** [comment] 2019-05-13 07:36
@lucabandMSFT was mixing up things. This one is not resolved and don't think the other issue is related.

**Comment by iBrooks** [comment] 2019-11-06 21:40
Is this being addressed? Its November now and this is still a problem.

**Comment by lucabandMSFT** [comment] 2019-11-07 12:53
hey @iBrooks, do you know if this issue is happening on multiple environments? or if there's a specific (page/site) template that is causing the issue? I'm trying to repro it but I don't see that happening.

**Comment by estruyf** [comment] 2019-11-12 13:39
@lucabandMSFT issue is still there. When you add a full width web part on the page, it still contains 8px padding on the right side.

![Screenshot 2019-11-12 15 38 05](https://user-images.githubusercontent.com/2900833/68676353-8684b780-0562-11ea-92d2-cfb514b12dd5.png)

**Comment by iBrooks** [comment] 2019-11-12 15:38
@lucabandMSFT extremely consistent for me. Any full-width section I create will have this problem. Just created another new page yesterday and same thing.
![image](https://user-images.githubusercontent.com/7727330/68685627-63451280-0538-11ea-881e-3a30bf5d7fee.png)
![image](https://user-images.githubusercontent.com/7727330/68685730-8e2f6680-0538-11ea-882d-f1a29031a079.png)
![image](https://user-images.githubusercontent.com/7727330/68685740-925b8400-0538-11ea-8213-2c2821d1010d.png)

**Comment by lucabandMSFT** [comment] 2019-11-12 18:19
Ok, thanks guys. We are taking a look at this one.

**Comment by estruyf** [comment] 2019-11-12 21:49
Thanks @lucabandMSFT!

**Comment by patmill** [comment] 2021-10-13 18:47
Sorry for the long delay, this appears to be addressed.

**Closed by patmill** 2021-10-13 18:47 UTC
Labels: type:bug-suspected, area:spfx, Needs: Attention :wave:
