### ISSUE TITLE
Getting below Errors in IE in spfx web part. Its working fine in Chrome.

### ISSUE THREAD

**Issue by virender1164** [SharePoint/sp-dev-docs#1910] opened 2018-05-25 10:00 UTC
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

> For the above list, an empty checkbox is [ ] as in <kbd>[</kbd><kbd>SPACE</kbd><kbd>]</kbd>. A checked checkbox is [x] with no space between the brackets. Use the `PREVIEW` tab at the top right to preview the rendering before submitting your issue.
>
> If you are planning to share a new feature request (enhancement / suggestion), please use SP Dev UserVoice at http://aka.ms/sp-dev-uservoice. (DELETE THIS PARAGRAPH AFTER READING)
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Observed Behavior

[SPLoaderError.loadComponentError]: ***Failed to load component "50c8cfb5-77d0-400b-9a0c-6043997ab14c" (WebPartName).  Original error: ***Failed to load entry point from component "50c8cfb5-77d0-400b-9a0c-6043997ab14c" (WebPartName). Original error: Error loading https://component-id.invalid/50c8cfb5-77d0-400b-9a0c-6043997ab14c_0.0.1 	Object doesn't support property or method 'match'
#### Steps to Reproduce

> If you are reporting a bug please describe the steps to reproduce the bug in sufficient detail to allow testing. Only way to fix things properly, is to have sufficient details to reproduce it. If you are making a suggestion, you can delete this section.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Submission Guidelines

> - All suggestions or bugs are welcome, please let us know what's on your mind.
> - If you are reporting an issue around any of the documents or articles, please ensure that you have clear > reference on the specific file or URL, which should be fixed.
> - If you have technical questions about the framework, we’ll be monitoring #spfx, #spfx-webparts, and > #spfx-tooling on (SharePoint StackExchange)[http://sharepoint.stackexchange.com/]. You can also > alternatively submit your question to (SharePoint Developer group)> [https://network.office.com/t5/SharePoint-Developer/bd-p/SharePointDev] at Office Network.
> - Remember to include sufficient details and context.
> - If you have multiple suggestions or bugs please submit them in separate bugs so we can track resolution.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

Thanks for your contribution! Sharing is caring.

**Comment by Nasicus** [comment] 2018-06-22 07:09
This is the same bug as described here:
https://github.com/SharePoint/sp-dev-docs/issues/2010

You can't do anything about it, since it's very likely that it's a bug on their site.

**Comment by VesaJuvonen** [comment] 2018-06-27 10:49
Closing this one as a duplicate of #2010 as that has more details on the actual issue.

**Closed by VesaJuvonen** 2018-06-27 10:49 UTC
