### ISSUE TITLE
SPFx MSGraphClient sometimes uses different Service principal to authenticate

### ISSUE THREAD

**Issue by manufz** [SharePoint/sp-dev-docs#7369] opened 2021-10-04 15:55 UTC
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx version 1.12.1

### Describe the bug / error

When opening a SharePoint site with an embedded webpart sometimes _SharePoint Online Web Client Extensibility_ is used instead of _SharePoint Online Client Extensibility Web Application Principal_ for the MSGraphClient calls.
If the site is opened in a new tab most of the time the first principal is used (which does not have the approved permissions). After a page refresh the second service principal is used.

### Steps to reproduce

1.
2.
3.

### Expected behavior

MSGraphClient should always use _SharePoint Online Client Extensibility Web Application Principal_ for Graph calls as only this service principal contains the approved permissions from the API access page.

**Comment by patrikhellgren** [comment] 2021-10-04 16:47
@manufz I was seeing the same thing but in a SharePoint hosted personal app in Teams and commented about it in #7307.
Make sure you have done as lucabandMSFT says since I haven't seen this mentioned anywhere else:

> before using the web part in Teams, was a global admin able to go to the API Access page in SPO Tenant Admin? that is a critical step to enable new functionalities.

I haven't heard any complaints from our users after that issue was closed the other day.

**Comment by patmill** [comment] 2021-10-04 18:22
Marking as a duplicate of #7307  for now.  If that is not the case, and there is additional info, please post and reopen.

**Closed by patmill** 2021-10-04 18:22 UTC
Labels: type:bug-suspected, Needs: Triage :mag:
