### ISSUE TITLE
Testing CSS in workbench is severely limited . Do we have any options to replicate the CSS / page layout of my SharePoint site in Workbench ?

### ISSUE THREAD

**Issue by Sohailsayed23** [SharePoint/sp-dev-docs#463] opened 2017-03-02 06:44 UTC
Posting on behalf of a customer 

Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [x] Question
- [x] Bug
- [x] Enhancement / Suggestion

#### Expected or Desired Behavior
I am using bootstrap on my SharePoint site collection. i am developing and testing my web part locally on workbench. I cannot reference the bootstrap in the workbench.html (even if i add references to the CSS manually). In addition the page layout of sharepoint cannot be effectively replicated in work bench. Result is i am doing testing and changes multiple times once i upload my app to SharePoint. 

#### Observed Behavior
Be able to test the UI of my web part once in workbench and have consistent result in sharepoint

#### Steps to Reproduce
Reference boot strap and use a complex page layout in the SharePoint page. Develop a web part and test in workbench. Deploy in SharePoint and see how the UI looks completely different

You can contact me for more information
MS Alias - sasohail

**Comment by patmill** [comment] 2017-03-02 19:31
I'll pivot this a different way, and you can tell me if it seems correct.

You would like a way to test your webpart in the actual code where it will execute, rather than a test host like the workbench.  I can't see us making the workbench mimic every possible modern and classic page configuration.

**Comment by amishra0909** [comment] 2017-05-09 21:46
Since, by design, workbench cannot replace every possible configuration of SharePoint pages, I am closing this issue.

**Closed by amishra0909** 2017-05-09 21:46 UTC
