### ISSUE TITLE
SingleWebPartAppPage not working on SmartPhone

### ISSUE THREAD

**Issue by SmartFlow365** [SharePoint/sp-dev-docs#5349] opened 2020-02-16 19:12 UTC
## Category

- [x] Bug

## Describe the bug

>  If you set LayoutType to SingleWebPartAppPage the page work fine on Desktop, but if you switch to SmartPhone the page is not load. I tried with custom webpart and with SharePoint Standard WebPart (yammer for my test), and the problem is the same.

## Steps to reproduce

> Provide steps to reproduce the behavior:

1. Create page with only one webpart, for example yammer webpart
1. Then set the LayoutType to SingleWebPartAppPage
1. Then try to swith the page to mobile view (developers tool) and refresh the page
1. See error

<img width="858" alt="fullpage" src="https://user-images.githubusercontent.com/32346822/74611022-97f8d500-50f8-11ea-9dce-9bb10a6d4f3f.PNG">
<img width="290" alt="mobile" src="https://user-images.githubusercontent.com/32346822/74611023-992a0200-50f8-11ea-8051-162ab1f43610.PNG">

**Comment by corkindustry** [comment] 2020-02-18 15:46
This is also happening with SPFx solutions deployed as 'SharePointFullPage'. Tested on Android and iOS. Works fine on desktop, but renders a blank page on mobile. Same results when using the device tool bar in Chrome Dev Tools.

**Comment by andrewconnell** [comment] 2020-02-19 11:45
Dupe of #4968

**Closed** 2020-02-19 11:45 UTC
Labels: status:duplicate
