### ISSUE TITLE
setSiteBranding

### ISSUE THREAD

**Issue by RyanCCBS** [SharePoint/sp-dev-docs#4140] opened 2019-06-13 16:43 UTC
I am attempting to use setSiteBranding in a Site Design script. However when I do it says "This action is part of an experimental feature that is not supported in the current environment."

I don't see anything in this documentation that says this feature isn't in general release, I also do not see anything that allows me to track when this feature will become available.

I have checked the roadmap here https://www.microsoft.com/en-ca/microsoft-365/roadmap?ms.url=roadmap&rtc=1&filters= with no luck. 

Is there a way to find out when I can use this feature? If I should be able to now, any way I can find out why I can't?
I have tested in multiple Tenants. One is my demo tenant with targeted release enabled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68267476-ee8d-7b95-446b-711ddb683da2
* Version Independent ID: aa099b9d-48db-5513-11c7-32c49a27e5be
* Content: [Site design JSON schema](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-json-schema#feedback)
* Content Source: [docs/declarative-customization/site-design-json-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-json-schema.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment] 2019-06-13 17:41
I'll let Microsoft confirm... but there appears to be quite a bit of conflicting information in this regard. I believe setSiteBranding was announced at SPCNA as new feature coming.

A PR was added #4091 recently for this documentation...

The JSON  Schema in the documentation https://developer.microsoft.com/json-schemas/sp/site-design-script-actions.schema.json doesn't appear to even include this action... so I'm not sure if the schema is even valid anymore.

I have also tested in my environment and confirmed it does not work. I'm guessing the documentation may have been published a bit too early, before the functionality has been deployed across tenants. I would be interested in knowing more about this as well.

**Comment by TashunkoWitko** [comment] 2019-07-11 12:15
Also excited to get some news on this, we had to fall back to CSOM for our (production) implementation...

**Comment by expiscornovus** [comment] 2019-07-30 13:13
Don't know if it helps. But today I was able to set the header layout to compact via the setSiteBranding site script action in a targeted release tenant.

**Comment by JarbasHorst** [comment] 2019-10-14 09:43
I haven't seen that exception message for this action anymore: "This action is part of an experimental feature that is not supported in the current environment.". I've just applied setSiteBranding to an existing communication site and everything worked properly on my standard release tenant. It looks like setSiteBranding action has been finally released!

**Comment by bcameron1231** [comment] 2019-11-08 17:10
@andrewconnell #please-close This action was deployed previously and comments on ticket, note it's been resolved.

**Closed** 2019-11-10 11:26 UTC
Labels: area:docs-comment, area:site-design, type:question
