### ISSUE TITLE
Valid Node.js versions for 1.15 release should include Node v16 support

### ISSUE THREAD

**Issue by okiehay** [SharePoint/sp-dev-docs#8242] opened 2022-06-28 15:39 UTC
The table detailing compatible software versions should include Node LTS v16 for SPFx v1.15

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25459e4a-2488-302d-9906-cfacfdc4639a
* Version Independent ID: 339fbcec-873c-9c47-fd9c-cf5f505132ac
* Content: [SharePoint Framework development tools and libraries compatibility](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/compatibility)
* Content Source: [docs/spfx/compatibility.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/compatibility.md)
* Service: **sharepoint**
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by AJIXuMuK** [comment] 2022-06-28 20:35
dupe of #8224

**Closed** 2022-06-28 20:35 UTC
Labels: status:duplicate, Needs: Triage :mag:, area:docs-comment
