### ISSUE TITLE
Failed to get accesstoken with AADTokenProvider on SharePoint mobile app

### ISSUE THREAD

**Issue by LeemansBE** [SharePoint/sp-dev-docs#4073] opened 2019-06-03 08:55 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I created a SharePoint Framework 1.7 webpart which uses the AadTokenProviderFactory to generate an accesstoken. We've tested this on all browsers (desktop and mobile) and this is working as expected.

#### Observed Behavior

However, when opening a page containing the webpart on the SharePoint mobile app (Version 3.8.0) the webpart receives an error:

"TypeError: Failed to fetch"

#### Steps to Reproduce

```
this.context.aadTokenProviderFactory
    .getTokenProvider()
    .then((tokenProvider: AadTokenProvider): Promise<string> => {
      // retrieve access token for the enterprise API secured with Azure AD
      return tokenProvider.getToken('[Azure AD app ID]');
    })
    .then((accessToken: string): void => {    
      alert(accessToken);
    }).catch(error => {        
        alert('error: ' + error);      
    });
```

Also tried to update the AD app manifest with
```
"preAuthorizedApplications": [
    {
        "appId": "00000003-0000-0ff1-ce00-000000000000",
        "permissionIds": [
            "[PERMISSION ID]"
        ]
    }
]
```
but still no luck.

Any ideas?

**Comment by andrewconnell** [comment] 2019-06-04 15:09
@LeemansBE said:
> Also tried to update the AD app manifest with

What do you mean by this... where did you do this? Are you saying you're modifying the Azure AD app manifest in the Azure AD Admin Portal? If so, that will not have an impact here...

Where is the error coming from... when you obtain the token provider (the first `then()`) or when you try to get the token?

**Comment by LeemansBE** [comment] 2019-06-04 15:53
Hi @andrewconnell 

Jep that is correct. I've tried to follow the steps described [here](https://github.com/SharePoint/sp-dev-docs/issues/2521#issuecomment-487962439)

Obtaining the token provider seems to be going well. The error is thrown when we try to get the token.
It's actually quite hard to debug as this works well on all browsers (dekstop and mobile) but only fails when rendered in the SharePoint app (Android).

**Comment by CPritch** [comment] 2019-06-06 08:58
We can also confirm we have had issues when using the SharePoint app and using the Graph authentication package. Works fine when in the browser on the same Android/iOS device but fails to auth in the SP app. I will query my team for furhter info and get back to you.

**Comment by andrewconnell** [comment] 2019-06-06 17:44
According to #4013, @lucabandMSFT said this same process should work for the mobile app. 

@lucabandMSFT is it the same AppID for the mobile app?

**Comment by lucabandMSFT** [comment] 2019-06-06 17:57
yes, exactly the same. as we load the SharePoint page in an iFrame in the Mobile app (or Team). it's the page that goes to AAD to fetch the token.. which means that it is the same appID.

**Comment by lucabandMSFT** [comment] 2019-07-01 23:14
closing this as a dupe of #4013

**Closed by lucabandMSFT** 2019-07-01 23:14 UTC
Labels: Needs: Attention :wave:, area:framework-general, status:duplicate, status:working-on-it, type:bug-confirmed
