### ISSUE TITLE
.sppkg support in App Catalog fails in SharePoint 2019

### ISSUE THREAD

**Issue by Isabeletta** [SharePoint/sp-dev-docs#3469] opened 2019-02-19 09:04 UTC
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Steps to Reproduce

I created an App Catalog and I created the solution follow the steps of the next link https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part

When generating the package it does not generate any errors but when I upload it to the App Catalog library it gives me the following errors:

There were errors when validating the App manifest.: Xml Validation Exception: 'The 'IsClientSideSolution' attribute is not declared.' on line '1', position '256'., Xml Validation Exception: 'The element 'Properties' in namespace 'http://schemas.microsoft.com/sharepoint/2012/app/manifest' has incomplete content. List of possible elements expected: 'StartPage' in namespace 'http://schemas.microsoft.com/sharepoint/2012/app/manifest'.' on line '1', position '352'., Xml Validation Exception: 'The element 'App' in namespace 'http://schemas.microsoft.com/sharepoint/2012/app/manifest' has incomplete content. List of possible elements expected: 'AppPrincipal' in namespace 'http://schemas.microsoft.com/sharepoint/2012/app/manifest'.' on line '1', position '365'.

The point is that AppManifest.xml that is generated contains "IsClientSideSolution" and this atribute is not declareted in any place in the project. What is worng in the packaging process using gulp in on premise SharePoint 2019? Also 'StartPage' and 'AppPrincipal' tags are not included in the manifest, I create a new one by hand and I could upload the app, but is not the properly way.

Can someone help me? Thanks a lot.

**Comment by bcameron1231** [comment] 2019-03-01 19:09
For issue maintenance - Duplicate of #3490

**Comment by krishnavandanapu** [comment] 2019-03-06 02:18
Hi Cameron / Andrew,

Please help me with my issue [ #3490](https://github.com/SharePoint/sp-dev-docs/issues/3490) a duplicate of this issue.
I have logged 9 days back but there was no luck !

Thank you,
Krishna

**Comment by VesaJuvonen** [comment] 2019-03-26 17:50
Closing this as duplicate with #3490, which has more context.

**Closed by VesaJuvonen** 2019-03-26 17:50 UTC
Labels: Needs: Triage :mag:, area:framework, area:on-prem
