### ISSUE TITLE
Localization not working in local or sp workbench

### ISSUE THREAD

**Issue by wobba** [SharePoint/sp-dev-docs#858] opened 2017-09-14 11:10 UTC
#### Category
- [x] Bug

#### Expected or Desired Behavior
When specifying debug locale in write-manifest or as --locale switch I expect the right locale files to load.

#### Observed Behavior
When specifying locale files for strings, and following documentation to either set *debugLocale* or using the --locale switch, SPFx always loads *en-us*.

#### Steps to Reproduce
Create a new locale string file for some alternate language. Specify *gulp serve --locale=xx-yy* and *en-us* is still loaded.

**Comment by waldekmastykarz** [comment] 2017-10-06 10:23
It seems like workbench is picking up the language defined in the **node_modules/(at)microsoft/sp-webpart-workbench/lib/api/workbenchInit.js** file in the **currentUICultureName** property. If you'd like to test different languages, you have two options:

1. Change the **currentUICultureName** property value to the locale you want to test
2. Change the **currentUICultureName** property to an non-existent locale such as `ab-CD`. This will force the workbench to fallback to the default locale which is then set to the locale specified in the `--locale` argument or in the `debugLocale` property.

**Comment by wobba** [comment] 2017-10-10 10:38
Thank you.. but this would not work for testing extensions due to no local wb support. Oh well.

**Comment by VesaJuvonen** [comment] 2017-10-10 10:46
@wobba - Let's not close this yet, since it's clearly a bug either in documentation or in the latest SPFx packages. We are currently solving where the issue is and we want to address the core scenario.

**Comment by waldekmastykarz** [comment] 2017-10-10 12:39
@wobba when testing extensions, SPFx should pick up the UI language from the site you're using to test it on. Are you seeing otherwise?

**Comment by wobba** [comment] 2017-10-10 12:45
It's probably working, it's just that I prefer to have my user using English, and need to test Norwegian. A hassle switching it back and forth. But it works fine when deployed so no worries :)

**Comment by VesaJuvonen** [comment] 2017-10-12 06:15
We have the original debugLocale issue now fixed for the next build. Can't share the exact timeline for the following patch release, but coming soon when we get the needed bug fixes tested and included. Thanks, @wobba for reporting this. Let's close this when the new build is out and we have truly verified the status.

**Comment by qz2017** [comment] 2017-10-31 20:33
1.3.4 is just released and has a fix for this issue. Can you please try it and let us know if it fixes your issue?

**Comment by waldekmastykarz** [comment] 2017-11-01 08:45
This seems to be working correctly in v1.3.4

**Closed by waldekmastykarz** 2017-11-01 08:45 UTC
Labels: status:fixed-next-drop, status:tracked

**Comment by wobba** [comment] 2017-11-01 09:53
Tested with --locale switch and works like a charm :D

**Comment by umaknow-francis** [comment] 2017-12-01 15:28
Hi, I tested it with version 1.3.4 with either --locale argument and the debugLocale property and it is not working. I use fr-fr. Are we sure that it is solved? Thanks!

**Comment by Harshagracy** [comment] 2019-12-16 07:38
I am trying for SPFx version 1.9.1 and this is my command:
`gulp serve --locale=nl-nl`

it is still loading en-us. 

Any idea, if this is solved? or a problem with dutch?
