### ISSUE TITLE
Office UI Fabric Grid System was removed from Communication Sites and Online Workbench

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#1287] opened 2018-01-27 11:20 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Observed Behavior
On communication sites, the Office IU Fabric grid system has been recently replaced by a proprietary custom grid system. It is maybe still based on Office UI Fabric but used different class names then Office UI Fabric.

| Office UI Fabric        | Communication site |
| ------------- | ----- |
| .ms-xl12      |  .CanvasSection-xl12 |
| .ms-xl8  |  .CanvasSection-xl8 |
| .ms-xl6  |  .CanvasSection-xl6 |
| .ms-xl4  |  .CanvasSection-xl4 |

This has a lot of negative impact on custom SPFx solution that optimised for the use of different part layouts container. The following screenshot shows the newly introduced columns.

<img width="1072" alt="screen shot 2018-01-27 at 13 14 59 copy" src="https://user-images.githubusercontent.com/5503835/35471477-a29e3f42-0364-11e8-964f-5b5d123c07fe.png">
This change also causes troubles when local developed web parts then will be used in an online environment, because they might behave differently.

For future development, it is even unclear what the actual plan is in case of SharePoint. Will Office UI Fabric still be supported by SharePoint or is there currently a migration ongoing to a new UI Framework.

**Comment by StfBauer** [comment] 2018-01-29 15:26
Meanwhile, I also wrote a blog post on what exactly the issue I ran in and how I was able to solve and adapt to the changed behaviour.
This blog post on '[Major CSS Class changes in Communication Site and Workbench](https://n8d.at/blog/major-css-class-changes-in-communication-site-and-workbench/)'

This links also the original post where I showed how to address the parent web part zone container.

**Comment by andrewconnell** [comment] 2018-01-29 17:32
Related #1279 ?

**Comment by StfBauer** [comment] 2018-01-29 21:02
@andrewconnell 
I don't think so. Cause if the icon is correct formatted they still work with exactly the same classes in Office 365 and local.

Seems to be more a bug by Chris Kent.

**Comment by VesaJuvonen** [comment] 2018-01-30 01:30
@StfBauer - let's try to get this clarified in slightly more detailed level. Unless mistaken, you are directly referencing fabric css styles in the web part html, which will cause potential issues since it's not following up on the fabric usage guidance explained in here - https://docs.microsoft.com/en-us/sharepoint/dev/spfx/office-ui-fabric-integration. 

Could you clarify the issue with an example or provide solution project for easier repro steps? - Would help on getting the issue resolution forward. Thx.

**Comment by wictorwilen** [comment] 2018-01-30 09:47
This is one of the issues with not using "global styles". It makes sense for custom client side web parts, but the grid system on a page is something that we/I would like to be "static" so that we can ensure that our web parts behave nicely and respect the layout of the page.

**Comment by VesaJuvonen** [comment] 2018-01-30 18:00
thx @StfBauer for the additional details, so that we can get this moving internally in engineering. I absolutely agree also on the needs for improving the documentation and we are more than happy to have contributions to this area also from the community.

**Comment by VesaJuvonen** [comment] 2018-01-31 02:41
thx Stefan, your clarification is completely understandable and does make a lot of sense as a structure or ask to be supported. Problem is in your implementation case is that it's dependent on the "dom injection" pattern where you jump outside from the web part boundaries to figure out how the web part should be rendered. This does make sense from the end-to-end requirement perspective, but it breaks the rules of web part development.

Our first party web parts are solving the re-render challenge with this.width and OnResize events, but that's not also that straightforward, so we are looking into adding better support for this in future based on your input. Before that's available, we'll work on sharing a mockup to demonstrate how this is solved with 1st party web parts - which then can be taken into account in your solution.

We really appreciate the input, but since we cannot resolve this as such since it's not a bug, will close this one for now. We will have more insights on the upcoming capability whenever it is available.

**Closed by VesaJuvonen** 2018-01-31 02:41 UTC
Labels: area:framework, status:tracked, type:bug
