### ISSUE TITLE
Graph and AAD client not working in SharePoint APP because pop-ups are blocked

### ISSUE THREAD

**Issue by estruyf** [SharePoint/sp-dev-docs#1656] opened 2018-04-13 12:31 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Opening a page with a web part that uses the Graph or AAD client in the SharePoint APP on Android or iOS doesn't work. The app blocks pop-ups and there doesn't seem to be a way to enable/disable it.

![img_0211](https://user-images.githubusercontent.com/2900833/38734862-5291a742-3f27-11e8-9d51-35e21adebf30.PNG)

#### Steps to Reproduce

Open a page with a webpart that makes use of the Graph / AAD client in the SharePoint app.

**Comment by VesaJuvonen** [comment] 2018-04-19 17:59
This is by design now - unfortunately - we are working on changes in the SharePoint app to enable or bypass this model where suitable. No ETA for now, so closing this "as designed".

**Closed by VesaJuvonen** 2018-04-19 17:59 UTC
Labels: area:framework, status:by-design, type:bug
