### ISSUE TITLE
JQuery Webpart stopped functioning 12/8 on Modern page

### ISSUE THREAD

**Issue by dmcrock** [SharePoint/sp-dev-docs#1136] opened 2017-12-11 15:47 UTC
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
I have built a jquery accordion web part. Everything has been working as indended until Friday 12/8. Nothing changed on our end.

#### Observed Behavior
Thursday 12/7 webpart was working correctly. (has been Nice deployment on November 2), then logged in on 12/8 to our tenant and received this error:

> Something went wrong
> 
> If the problem persists, contact the site administrator and give them the information in Technical Details.
> TECHNICAL DETAILS
> [SPLoaderError.loadComponentError]:
> ***Failed to load component "3c622f98-4dcb-4eb3-b585-d12bfdb7587e" (JQueryAccordionWebPart).
> Original error: ***Failed to load path dependency "jqueryui" from component "3c622f98-4dcb-4eb3-b585-d12bfdb7587e" (JQueryAccordionWebPart).
> Original error: Cannot read property 'ui' of undefined
> 
> ***INNERERROR:
> ***Failed to load path dependency "jqueryui" from component "3c622f98-4dcb-4eb3-b585-d12bfdb7587e" (JQueryAccordionWebPart).
> Original error: Cannot read property 'ui' of undefined
> ***CALLSTACK:
> Error
>     at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-12-01.005/sp-pages-assembly_en-us_5036c5427f6b980d75abba313b73668a.js:314:21697)
>     at new t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-12-01.005/sp-pages-assembly_en-us_5036c5427f6b980d75abba313b73668a.js:876:22799)
>     at Function.e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-12-01.005/sp-pages-assembly_en-us_5036c5427f6b980d75abba313b73668a.js:876:15519)
>     at Function.e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-12-01.005/sp-pages-assembly_en-us_5036c5427f6b980d75abba313b73668a.js:876:11516)
>     at https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-12-01.005/sp-pages-assembly_en-us_5036c5427f6b980d75abba313b73668a.js:876:114716
>     at <anonymous>

#### Steps to Reproduce
deploy web part to any modern page (we do not use classic), error automatically shows up
Additonally it does work correctly still in the local workbench

I am on SPFX 1.4

Thanks for your contribution! Sharing is caring.

**Comment by mcmynn83** [comment] 2017-12-14 17:41
@dmcrock - Just want to ensure the basics are covered.  That error occurs when the framework is not able to fetch the manifest for that feature.  This could happen for multiple reasons including:
1. The app package has been deleted
2.  The app package has been disabled
3.  The add-in has been removed on the site, but there is still a use of the webpart

Could you ensure all 3 of those cases are not true.  If the problem is still occurring after that could you  turn you give the correlation ID of the request by looking at the response header value SPRequestGuid and send that here.

Thanks,
Graham

**Comment by dmcrock** [comment] 2017-12-14 20:35
Hi Graham (@mcmynn83 ),
Thank you for following up. 
1. app package has not been deleted
2. app package has not been disabled
3. add-in has not been removed, nor is it in use anywhere else

The only value I see is this one:

   SPRequestGuid: 758e369e-50ac-4000-f4db-97ab93358d92

Thank you
Doug

**Comment by dmcrock** [comment] 2017-12-14 20:50
This error also made an appearance in the "console" Edge Developer tools
![image](https://user-images.githubusercontent.com/547769/34013715-cc53c5d4-e0d5-11e7-9e82-500f476b4f02.png)

**Comment by mpasarin** [comment] 2017-12-19 11:53
In your web part, are you declaring jQuery as an external?
If so, are you declaring it with a "globalName": "jQuery" ?

**Comment by dmcrock** [comment] 2017-12-19 15:29
Hello @mpasarin ,
I have Jquery and jquery UI declared as externals as such:
"externals":{
"jquery""https://code.jquery.com/jquery-3.2.1.min.js",
"jqueryui":"https://code.jquery.com/ui/1.11.1/jquery-ui.min.js
}
and then in the webpart.ts itself I have:
import * as jQuery from 'jquery';
import 'jqueryui';

**Comment by StfBauer** [comment] 2017-12-19 18:21
@dmcrock 
There is a good article on how to get jQuery accordion running in SPFX.
[Add jQueryUI Accordion to your SharePoint client-side web part](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/add-jqueryui-accordion-to-web-part)

The sad truth about jQuery UI is that it is still widely used but haven't got any update for more than 1.5 years. In web time frames this means it won't be updated and maintained anymore.
The official documentation states it supports:

> jQuery UI 1.12 supports jQuery 1.7 and newer.

Newer, in this case, means the version that was available at this time. This was the version jQuery version 2.
I guess with the documentation above you will get the accordion running. In your case, you need to downgrade from version jQuery version 3.2.1 to jQuery 2.x.x.

**Comment by dmcrock** [comment] 2017-12-19 18:45
@StfBauer 
Thank you Stefan, I will go through that. I had this thing working great from Nov 2 through last thursday and then it just stopped.

**Comment by mpasarin** [comment] 2017-12-20 11:05
This was caused by an internal change in the SPFx loader that was rolled out just to First Release users. Most users are not affected as they declare jQuery to be in the global `jQuery` object, but that is not what the instructions say, certainly. The change will be rolled back everywhere.
I'll close the issue, feel free to re-open if this is not solved in 24/48h.

**Closed by mpasarin** 2017-12-20 11:05 UTC
