### ISSUE TITLE
Navigating between SPFx SingleWebPartAppPage pages doesn't work

### ISSUE THREAD

**Issue by olemp** [SharePoint/sp-dev-docs#5352] opened 2020-02-17 08:49 UTC
## Category

- [x] Bug

## Describe the bug

Navigating between SPFx SingleWebPartAppPage pages doesn't work. 

## Steps to reproduce

Let's say you have a site with 4 different pages each containing a single web part with the `SingleWebPartAppPage` layout and a home page with the `Home` layout. Each page has a link in the `GlobalNavigation`.

1. Go to homepage
2. Click on `Page 1` in navigation (which is a page with `SingleWebPartAppPage` layout)
3. Wait for it to load
4. Click on `Page 2` in navigation (which is a page with `SingleWebPartAppPage` layout)

The url changes to the URL of `Page 2`, but `Page 1` remains rendered on the page.

## Expected behavior
Navigating between different `SingleWebPartAppPage` pages should work.

## Developer environment
Edge Chromium

**Comment by justatheory** [comment] 2020-02-18 01:24
I'm having the exact same problem.

**Comment by PrasadKasireddy** [comment] 2020-02-18 08:52
Duplicate of #5235, #4272 #5277 , #5211 , #5321

**Comment by lemonpowah** [comment] 2020-02-18 08:54
Also this one #5264. I submitted a ticket to Microsoft.

**Comment by PrasadKasireddy** [comment] 2020-02-18 09:06
This issue was already alerted by @andrewconnell to Microsoft Team.

https://github.com/SharePoint/sp-dev-docs/issues/5277#issuecomment-585727453

**Closed** 2020-02-18 11:29 UTC
Labels: status:duplicate

**Comment by kemesfun** [comment] 2020-02-25 00:08
This doesn't issue reproduce in the latest prod. tenant. @olemp  If you are still having this issue, can you let me know the exact steps to repro. this issue.
