### ISSUE TITLE
SPFx WebPart as Teams Desktop tab failed to call Graph API

### ISSUE THREAD

**Issue by AriGunawan** [SharePoint/sp-dev-docs#4520] opened 2019-08-21 15:34 UTC
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

Hi, I created a super simple SPFx (v1.8.2) app that calling Graph api to get the current user's display name.
I also made it as Teams tab [(documentation)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab).

#### Expected or Desired Behavior
The webpart should display the current user's name in a SharePoint page, Teams web tab, and Teams desktop tab.

#### Observed Behavior
The webpart successfully displays the current user's name in a SharePoint page and Teams web tab but it's failed on **Teams desktop tab** - not showing anything.

Please find below the error message when accessing the tab (using fiddler):
`AADSTS65001: The user or administrator has not consented to use the application with ID '00000003-0000-0ff1-ce00-000000000000' named 'Office 365 SharePoint Online'. Send an interactive authorization request for this user and resource`
![2019-08-21 22_05_19-Window](https://user-images.githubusercontent.com/8691985/63445405-7cbb4e80-c462-11e9-80d4-2085da3248e7.png)

Please also find below the webpart code:
```
import { Version } from '@microsoft/sp-core-library';
import { BaseClientSideWebPart } from '@microsoft/sp-webpart-base';
import {
  IPropertyPaneConfiguration,
} from '@microsoft/sp-property-pane';
import { MSGraphClient } from '@microsoft/sp-http';

export interface ISimpleGraphWebPartProps {
}

export default class SimpleGraphWebPart extends BaseClientSideWebPart<ISimpleGraphWebPartProps> {

  public render(): void {
    this.context.msGraphClientFactory
      .getClient()
      .then((client: MSGraphClient): void => {
        // get information about the current user from the Microsoft Graph
        client
          .api('/me')
          .get((error, response: any, rawResponse?: any) => {
            // handle the response
            this.domElement.innerHTML = `
              <div style='text-align: center'>
                <h1>${response.displayName}</h1>
                <span>${response.id}</span>
              </div>
            `
        });
      });
  }

  protected get dataVersion(): Version {
    return Version.parse('1.0');
  }

  protected getPropertyPaneConfiguration(): IPropertyPaneConfiguration {
    return {
      pages: []
    };
  }
}
```

Is there any extra steps to make it works on Teams desktop app?
Thank you.

**Comment by andrewconnell** [comment] 2019-08-24 03:56
@lucabandMSFT @lahuey Is this related to #4013? Thought a fix rolled out for this... or is this different?

**Comment by wobba** [comment] 2019-08-25 06:42
See https://github.com/SharePoint/sp-dev-docs/issues/2521#issuecomment-487962439 for a workaround which should be fixed as well in not too long.

**Comment by andrewconnell** [comment] 2019-08-25 19:03
Cool... thanks @wobba ... that's what I thought. So this is a dupe of #2521 so I'll close this. @AriGunawan keep an eye on that post as we try to not have multiple issues of the same thing.

**Closed by andrewconnell** 2019-08-25 19:03 UTC
Labels: area:auth, area:framework-general, status:duplicate, type:question

**Comment by TheTedAdams** [comment] 2019-08-29 20:58
Just curious, if we are closing new issues because they are dupes of #2521, shouldn't #2521 be re-opened? Not sure it's reasonable to expect people to go through closed issues before opening a new one?
