### ISSUE TITLE
The IODataBatchOptions interface does not extend the RequestInit interface

### ISSUE THREAD

**Issue by vman** [SharePoint/sp-dev-docs#106] opened 2016-08-29 14:04 UTC
This means that right now, there is no way to override the default HTTP headers sent with an OData batch request. Similar issue was discussed in another thread #44 

![iodatabatchoptions](https://cloud.githubusercontent.com/assets/173794/18053392/04350fec-6df7-11e6-9bee-8014d8642b2a.png)

As you can see, the `IODataBatchRequestOptions` does indeed extend the `RequestInit` interface and hence, an individual request in a batch can be set to override the headers. But since the entire batch is sent with an odata-version 4.0 header, the batch request fails and returns malformed data. 

Here is my code for my ODataBatch request:
```
private _makeODataBatchRequest(): void {
    const serviceScope: ServiceScope = ServiceScope.startNewRoot();
    serviceScope.finish();

    const webAbsoluteUrl: string = this.context.pageContext.web.absoluteUrl;
    const batchOpts: IODataBatchOptions = {
        webUrl : webAbsoluteUrl
        //Need a way here to override default options e.g Headers.
    };
    const odataBatch: ODataBatch  = new ODataBatch(serviceScope, batchOpts);

    const getMyProps: Promise<Response> = odataBatch.get(`${webAbsoluteUrl}/_api/SP.UserProfiles.PeopleManager/GetMyProperties`);

    //Overriding the header for a single request in the batch does not work as the entire batch is sent with odata-version:4.0
    const reqHeaders: Headers = new Headers();
    reqHeaders.append('odata-version', '');
    const performSearch: Promise<Response> = odataBatch.get(`${webAbsoluteUrl}/_api/search/query?querytext='sharepoint'`, { headers: reqHeaders });

    odataBatch.execute().then(() => {

      getMyProps.then((response: Response) => {
        response.json().then((responseJSON) => {
          console.log(responseJSON);
        });
      });

      performSearch.then((response: Response) => {
        response.json().then((responseJSON) => {
          console.log(responseJSON);
        });
      });
    });
  }
```

**Comment by manishgarg1** [comment] 2016-08-30 17:44
Tracked as VSO#242882

**Comment by pgonzal** [comment] 2016-09-20 23:05
This is by design:

- It does not make sense to allow you to customize the headers or other request parameters for the overall batch REST call, since it would complicate our algorithm
- It does make sense to allow you to customize the headers for individual REST calls, which is why we provide `IODataBatchRequestOptions`
- However, certain headers are not valid inside a batch.  For example, the ODataBatch uses OData Version 4.0, and SharePoint does not allow you to use OData Version 3.0 requests inside an OData Version 4.0 batch.  Therefore, your "odata-version" header above is not valid.

It would be possible for ODataBatch to detect this mistake and report a validation error, rather than allowing the server to report a protocol error.  This limitation seemed obvious to me, but if you think extra validation would be helpful, feel free to open an issue requesting it (and assign to me).

Otherwise, it's unclear to me what headers would ever be useful here:

```typescript
    const batchOpts: IODataBatchOptions = {
        webUrl : webAbsoluteUrl
        //Need a way here to override default options e.g Headers.
    };
```
It sounds like you want to specify `ODataVersion: 3.0` here, but that would require us to maintain two parallel implementations of the batching algorithm.

**Comment by pgonzal** [comment] 2016-09-20 23:06
I am closing this bug. If you have more questions/clarifications, please reopen it.  Thanks!

**Closed by pgonzal** 2016-09-20 23:06 UTC
Labels: area:framework, status:by-design, type:bug
