### ISSUE TITLE
customRowActions stop working after edit in edit properties panel

### ISSUE THREAD

**Issue by JoeAyre** [SharePoint/sp-dev-docs#4159] opened 2019-06-18 10:42 UTC
All customRowActions stop working if an item is modified using the editProps panel. For instance, if a button that launches a flow has a visibility that is conditional on a certain column value, and you edit an item to make whatever that condition is 'true' (and thus displaying the button that launches a flow), the button won't work until the page is refreshes or reloaded.

A potential fix would be for a refresh to the main page to be called every time an item is edited and the edit properties panel is saved, but the problem is that there is no 'Save' or 'OK' to hook in to.

It's a bit of a guess, but what might be happening here is that because properties are saved whilst actually in the edit properties panel is open (the little 'Saving...' > 'Saved' text and tick pops up), there is no 'OK' or 'Save' button and therefore no action to trigger a page refresh - you just effectively close or cancel the edit properties panel. Maybe a simple fix would be to apply a page refresh when edit properties panel is closed no matter how you close it, or detect a change to the properties and arm the trigger when the edit properties panel is closed.

#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

**Comment by andrewconnell** [comment] 2019-06-18 21:23
Unclear as to what you're referring to... row/column formatting? General UX? Can you provide more details with some context?

**Comment by JoeAyre** [comment] 2019-06-18 23:36
Apologies, this relates to JSON list formatting in SharePoint.

**Comment by JoeAyre** [comment] 2019-10-29 23:51
@andrewconnell Just checking in to see if any progress has been made to fix this bug?

**Comment by shagra-ms** [comment] 2020-01-27 21:41
The scenario works on column formatting but is broken on View formatting. We will work on this and roll out a fix soon. Thanks!

Duplicate of #2397

**Closed** 2020-01-27 21:42 UTC
Labels: area:list-formatting, status:duplicate
