### ISSUE TITLE
Asset Packaging error when the solution name has - in the name 

### ISSUE THREAD

**Issue by joaoferreira** [SharePoint/sp-dev-docs#1130] opened 2017-12-09 15:09 UTC
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Being able to deploy a valid package to the app catalog

#### Observed Behavior
When the solution name has a - in the name the sppkg will throw an error once the web part is added to the app catalog. This behaviour was observed on global app catalog and also in the site collection app catalog. The error messages is **Invalid SharePoint App package. Error: Part URI is not valid per rules defined in the Open Packaging Conventions specification.**
This error is caused by the **assetpackagingwebpartstrings** file located in the **ClientSideAssets** folder inside the package. Instead of using the - the file is created with a space in the name and it breaks the OPC specification.

#### Steps to Reproduce

1. Using yeoman generator create a new web part with a - in the name 
2. Run the command gulp bundle --ship
3. Run the command gulp package-solution --ship 
4. Add the package file to the app catalog

**Comment by jaredbuttars** [comment] 2018-01-20 20:05
I have this same problem, unfortunately - the error persists even after removing the dashes.

**Comment by jaredbuttars** [comment] 2018-01-20 20:18
After some experimenting, It's actually related to the CDN basepath not the package name.
when set to the folllowing to package assets into the sppkg:

`"cdnBasePath": "<!-- PATH TO CDN -->"`

The package is invalid with the error:

 **Invalid SharePoint App package. Error: Part URI is not valid per rules defined in the Open Packaging Conventions specification.**

**Comment by kulkarnichief** [comment] 2018-02-02 10:34
Same problem for me too even after completely updating manifest and package solution files

**Comment by kduenke** [comment] 2018-02-08 18:27
I ran into this too.  It showed up when I added "includeClientSideAssets": true to my package-solution.json file.  The fix for me ended up being to rename the directory that held my git project to remove any spaces from it.  After that, it deployed fine.

**Comment by aslanovsergey** [comment] 2018-03-16 11:15
I get this problem today with SPFx 1.4.1

**Comment by colonelclaypoo** [comment] 2018-03-23 09:19
I can confirm that I have the same issue. I followed the [tutorial ](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part) series but did not opt to enable an O365 or Azure CDN.

**Comment by aslanovsergey** [comment] 2018-03-26 07:41
Very nasty bug, have no idea how deploy my web part. Removing spaces in folder, shortening solution name didn't help...

**Comment by jesusvelasco93** [comment] 2018-04-12 07:16
I can correct that error change the name folder that have the project without dashes ("-") and spaces (" ").

**Comment by mcraiha** [comment] 2018-04-26 10:41
Removing whitespace from path helped in here.

**Comment by aslanovsergey** [comment] 2018-04-26 11:38
What helped me was cleaning temp/deploy folder

**Comment by JLRishe** [comment] 2018-05-29 14:25
This seems to have to do with the way that the string resource files are bundled. The generated .js files seem to be prefixed with the name of the folder containing the solution. If the folder name contains a space, then the file names will contain a space, and SharePoint seems to not like this.

It seems pretty unnecessary to have the file names contain the solution's folder name, and I'm wondering if this is a bug in the gulp bundle procedure. It may be possible to remedy this by modifying said procedure, but being fairly unfamiliar with gulp, I wouldn't know how to go about that.

**Comment by Dangerous-Mind** [comment] 2018-09-24 08:08
Solved removing the space on the name of the folder were the solution was stored and on one of the files.

**Comment by rajamaniperumal** [comment] 2018-10-16 01:28
> What helped me was cleaning temp/deploy folder

Thanks, you have saved my time....

**Comment by kylepdx** [comment] 2018-10-24 05:17
Wicked error message...not helpful.   In my case I had an asset (image file) that had a space in the filename. Once I renamed the file and did a clean, I was able to package and deploy again.

**Comment by ravinleague** [comment] 2018-10-26 01:36
Had to - 
Rename project folder (it had spaces)
Check for dashes in the solution names_(removed, just in case)_
Delete temp/deploy folder
Gulp bundle --ship
Gulp Package-solution --ship

Working fine!!

**Comment by andrewconnell** [comment] 2019-02-01 11:44
Seems like things are resolved by cleaning & rebuilding the project?

**Comment by jonathaneckman** [comment] 2019-02-03 18:33
The solutions above helped me. 
1. Remove spaces from the path.
2. Clean
3. Rebuild and package.

In my case, I found a space in a parent directory my source code was under.

**Comment by joaoferreira** [comment] 2019-02-11 10:46
This still happens, I did a test today and got the same error.
The workaround provided in this thread helped me to get it working 

- Rename project folder (it had spaces)
- Check for dashes in the solution names_(removed, just in case)_
- Delete temp/deploy folder
- Gulp bundle --ship
- Gulp Package-solution --ship

**Comment by andrewconnell** [comment] 2019-02-11 11:47
@joaoferreira I just created 2 new projects and tested the deployment on each:

- project folder with no spaces/hyphens, project name with hyphen = pass
- project folder with no spaces/hyphens, project name with space = fail

So the original reason for the issue, hyphens in the project name, is no longer an problem. However, spaces are a problem. With that being said... it's not really a bug as things are working as expected, but a feature enhancement for the generator could be to not allow spaces for the project name. In that case, it should be submitted as a feature request via UserVoice @ https://aka.ms/sp-dev-uservoice. 

Therefore, I'm going to close this issue since the root reason for the issue is no longer applicable.

**Closed by andrewconnell** 2019-02-11 11:47 UTC
Labels: Needs: Author Feedback, area:framework, no-recent-activity, status:tracked, type:bug

**Comment by JLRishe** [comment] 2019-02-11 16:16
@andrewconnell  _it's not really a bug as things are working as expected_ ... Having certain circumstances where the build process produces packages that are unusable and provide no indication of what's wrong is "working as expected"? Is this documented somewhere outside of this Github issue?

**Comment by andrewconnell** [comment] 2019-02-11 16:22
Honestly, I'm not sure @JLRishe (if it is/isn't documented somewhere). 

Maybe you could call it a bug & I'm wrong... I'll flag it for engineering to decide if it is / isn't a bug and see if they won't comment here.

I do agree... it would be nice if the generator flagged it as an issue at project creation, I'm just not sure if that would be considered a "nice" feature to have, or if that's a "bug". I can't be the judge in that...

**Comment by DonKirkham** [comment] 2019-04-16 10:04
I also ran into this and it was a space in an image file that caused the issue.

I also think the package-solution should have a warning, or better yet, nip it in the bud at build if we know it will be a problem downstream.

@andrewconnell , this would certainly be a great tip for your courses. "NO SPACES IN SPFX!"

**Comment by smit1529** [comment] 2019-12-17 10:26
Hey Guys,

What helped me to resolve the issue is....
Eliminating/Removing the **"clientsideinstance.xml"** attribute from **"package-solution.json"** file.
Please check the below screenshot for the same.

![Untitled](https://user-images.githubusercontent.com/31243665/70987275-8a3db980-208d-11ea-811b-9b5048d61cae.png)

Mark as answer if you find it useful.
Thanks.
