### ISSUE TITLE
Add SPFx WebPart to variation page fails

### ISSUE THREAD

**Issue by corily1810** [SharePoint/sp-dev-docs#731] opened 2017-07-19 16:36 UTC
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
I should be able to add a SPFx webpart on every page after installing it

#### Observed Behavior
i developed a spfx webpart and deployed it to the app catalog and added all CDN files.
The app can be installed on every site collection or subsite but i have massive problems by adding the webpart to a variation page.

#### Steps to Reproduce
1. Create a variaton site with variation labels. I have created en-us and de-de
2. Install the webpart on the source variation page. In my case en-us
3. Try to install the app on a second label site after all variation hierarchies are created. In my case de-de. The webpart cannot be installed, it says that the app is already installed. 
If a change the app version in the webpart config, the app can be installed, but ....
the Problem: 
The webpart is added to the page but is empty. Also in the settings panel the custom SPFx panel is empty.

Has anyone of you made experiences with the variation sites and SPFx.

Thanks a lot

**Comment by patmill** [comment] 2017-07-27 17:12
Hi @corily1810 - I'm going to throw out a bunch of different things to look at.  

If you use another webpart (say a listview webpart) does it work correctly?  

Also, just to confirm, the behaviour you are seeing is that the webpart is added, but the configuration data is empty?

In trying to diagnose, if you create a simple "hello world" webpart where the property is just a string, does it work correctly?

If you override the 
    protected onAfterDeserialize(deserializedObject: any, dataVersion: Version): TProperties;
method (make it simply call the base class), what does your deserializedObject look like?  What does the return value look like?

**Comment by BigEaseGueldi** [comment] 2017-08-08 08:21
Hi @patmill,
This should be related to https://github.com/SharePoint/sp-dev-docs/issues/596. There are double quotes in the loader module's German error text that are not escaped (I've heard of this being a problem in other languages too). So you don't necessarily need a German variation page to reproduce it - just create a (classic) German Site or activate the MUI and switch the browser language to German.

I'm actually waiting for a fix since May since we have customers that use German only. Would it be realistic to plan on a fix within this month? 
Thanks!
Dirk

**Comment by srideshpande** [comment] 2017-08-14 19:29
@BigEaseGueldi - now that #596 is resolved, could you please re-test your scenario and let us know if you still this issue.

Thanks,
Srikanth

**Comment by nickpape-msft** [comment] 2017-08-25 00:39
@corily1810 - could you please re-test your scenario and let us know if you still see this issue?

**Comment by corily1810** [comment] 2017-08-25 07:08
Dear all, thanks a lot for your support.
The issue is solved and the webpart is working for all variation sites.

**Comment by VesaJuvonen** [comment] 2017-11-21 12:53
Based on confirmation from @corily1810, will close this one for now.

**Closed by VesaJuvonen** 2017-11-21 12:53 UTC
