### ISSUE TITLE
Isolated SPFx webparts are not loading in Microsoft Teams Desktop App

### ISSUE THREAD

**Issue by ArunRajiv** [SharePoint/sp-dev-docs#4468] opened 2019-08-14 03:52 UTC
- [x] Question
- [ ] Typo
- [x] Bug
Hi Team,

We created an isolated web part ( Just vanilla hello world web part ) and tried to load it in Microsoft teams. It worked pretty much fine in the Teams web version but not in the Teams desktop version. It just loads blank.

![image](https://user-images.githubusercontent.com/19972139/62993398-c14c5600-be74-11e9-8054-f1e58a110f0c.png)

Here is the screenshot of fiddler trace and how web part is loading in teams (both web and desktop version).

**Web Version**
![image](https://user-images.githubusercontent.com/19972139/62993438-f2c52180-be74-11e9-948b-dc7793b10475.png)

**Desktop Version**
![image](https://user-images.githubusercontent.com/19972139/62993447-fa84c600-be74-11e9-8e41-6ebc1bd0331e.png)

**Fiddler Trace:**
Teams Desktop (vs) Web

![image](https://user-images.githubusercontent.com/19972139/62993469-096b7880-be75-11e9-8b67-8ca58d0a4055.png)

**Comment by ArunRajiv** [comment] 2019-08-14 04:03
@andrewconnell  @VesaJuvonen Please let us know if we are missing something out here..

**Comment by andrewconnell** [comment] 2019-08-14 13:41
Known issue that MSFT is working on. This is a dupe of #3819 so we'll close this issue.

**Closed by andrewconnell** 2019-08-14 13:41 UTC
Labels: area:framework-general, status:duplicate
