### ISSUE TITLE
Isolated Domain webpart and Teams Wrapper/SinglePageApplication layout

### ISSUE THREAD

**Issue by NaveenK-J** [SharePoint/sp-dev-docs#3819] opened 2019-04-22 06:07 UTC
Looks like Isolated Domain webparts do not work in Teams Wrapper and Single Page Application scenarios, webparts render without isolated domain iFrame, hence the AADHttp calls fails. I hope this is a known issue and will be addressed in future?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 364300d9-535e-e105-6c95-8becd00a396c
* Version Independent ID: 31b7e9d2-3c6f-953c-3d18-607d29d3151e
* Content: [Isolated web parts](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/isolated-web-parts#feedback)
* Content Source: [docs/spfx/web-parts/isolated-web-parts.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/isolated-web-parts.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by patmill** [comment] 2019-04-22 17:22
A couple of quick questions.  1 - Did you upload your own manifest to teams, or did you use the "sync with teams" button?  2 - If you look at the target of the iFrame in teams, what is the URL?

**Comment by NewJ123** [comment] 2019-04-22 20:12
Thanks @patmill 
Please let me know when this is fixed

**Comment by wimosh** [comment] 2019-06-12 22:44
I don´t know if is my cenario is related to this issue..
Does isolated web parts works on classic pages? 
I tested a isolated webpart on a modern page and it works just fine (isolated context). But in a classic page the same webpart use the "SharePoint Online Client Extensibility Web Application Principal" app. Am I doing something wrong?
This demo webpart use the webpart context msGraphClientFactory to get some basic information about the user.

![ClassicPage_IsolatedWebPart](https://user-images.githubusercontent.com/26660996/59391309-4c608100-8d4a-11e9-9e96-f5d04273708d.png)
![ModernPage_IsolatedWebPart](https://user-images.githubusercontent.com/26660996/59391310-4cf91780-8d4a-11e9-9a63-ab36e199a1f4.png)
![package-solution](https://user-images.githubusercontent.com/26660996/59391312-4cf91780-8d4a-11e9-812a-f2598c88604b.png)
![token_ClassicPage](https://user-images.githubusercontent.com/26660996/59391313-4cf91780-8d4a-11e9-8e38-2ec786770f6f.png)
![token_ModernPage](https://user-images.githubusercontent.com/26660996/59391314-4cf91780-8d4a-11e9-9e05-7394ffc20e5e.png)
![usingWebPartContext_msGraphClientFactory](https://user-images.githubusercontent.com/26660996/59391315-4d91ae00-8d4a-11e9-8ab1-0ffc98792381.png)

**Comment by NewJ123** [comment] 2019-08-20 18:42
Hi @patmill  - Is there any ETA when this will be fixed/available ?

**Comment by vasanthtt** [comment] 2019-08-26 10:48
Hi @patmill @andrewconnell we have a blocker due to isloated webpart not working on teams.  Any ETA for this fix?

**Comment by andrewconnell** [comment] 2019-08-26 12:48
I believe the workaround explained in this comment https://github.com/SharePoint/sp-dev-docs/issues/2521#issuecomment-487962439 resolves this until the fix is rolled out... can you please confirm?

**Comment by vasanthtt** [comment] 2019-08-29 18:57
@andrewconnell Yes I tried that workaround but still getting "TypeError: Cannot read property 'match' of undefined". I also tried removing **passwordCredentials** array from manifest of SharePoint Online Client Extensibility Web Application Principal. After sometime I am able to see new **passwordCredentials** generated in manifest.
```
"passwordCredentials": [
		{
			"customKeyIdentifier": "krEsgna9oEurplDFRV4GJw==",
			"endDate": "2069-08-29T10:10:19.6856608Z",
			"keyId": "513e439b-f378-4c6b-9c02-9ed17dee0d70",
			"startDate": "2019-08-29T10:10:19.6856608Z",
			"value": null,
			"createdOn": null,
			"hint": null,
			"displayName": null
		}
	],


```

**Comment by andrewconnell** [comment] 2019-08-29 19:05
Uh... I would NOT remove anything from that manifest... that's generated by MSFT. The ONLY thing I'd do is what was mentioned by Luca in that thread. Doing anything else is _very unsupported_.

Until the fix rolls out, there's no real update to provide.

**Comment by vasanthtt** [comment] 2019-08-30 05:15
@andrewconnell First, I did as Luca said, then I applied **passwordCredentials** array fix only after getting the error "TypeError: Cannot read property 'match' of undefined" as recommended in this [comment](https://github.com/SharePoint/sp-dev-docs/issues/4357#issuecomment-515131702).

Do we have any ETA for this real fix? as I need to commit my business. 

Thanks for your wonderful support!

**Comment by andrewconnell** [comment] 2019-08-30 14:04
In that case, this appears to be a dupe of the other issue so I'm going to close this so we can keep fragmentation down... 

@vasanthtt said:
> Do we have any ETA for this real fix? as I need to commit my business.
I can't share an ETA unless Microsoft has stated it... Microsoft has only said they are working on a fix.

**Closed** 2019-08-30 14:05 UTC
Labels: area:docs-comment, area:framework-general, status:duplicate, status:tracked, status:working-on-it, type:bug-confirmed
