### ISSUE TITLE
Adaptive Cards change prevents supplying third-party card views

### ISSUE THREAD

**Issue by Annie-Johnson** [SharePoint/sp-dev-docs#8653] opened 2022-12-15 15:14 UTC
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- Chrome Version 108.0.5359.99 (Official Build) (64-bit)
- SPFx version v1.13
- Node.js version * 14.18.1 (Currently using 64-bit executable)
- etc

### Issue description

A recent change to adaptive cards has rolled out to at least two of my tenants which removes the ability to override the template getter to customize a card view.  We were doing this for cards rendered in the SharePoint experience and rendering a different OOTB card for Teams mobile.  Clients are unhappy with OOTB design limitations.  Is there a safe, advisable way to continue supplying a third party card view?  I see the note on BaseCardView that third party card views should not inherit from that base class.  Is there a best practice way to develop a third party card view?

**Comment by johnguy0** [comment] 2022-12-16 17:47
Unfortunately there is not a supported way to override the templates returned by the provided card views. The `template` methods on `BaseBasicCardView`, `BaseImageCardView`, and `BasePrimaryTextCardView` are marked as `@sealed` to designate they should not (cannot) be overridden. Additionally there is no supported way to create additional card views beyond those provided. 

I understand these may be limiting. However, we want to enforce a coherent design language on the dashboard. We are actively working on expanding the set of out-of-box card views in the future. If there are particular requirements or designs you'd like to see, please feel free to suggest them!

**Comment by AJIXuMuK** [comment] 2022-12-16 17:55
Converting this issue to the discussion as the behavior is by design but we want to learn more about custom templates

**Closed as completed** 2022-12-16 17:55 UTC
Labels: area:spfx, type:discussion, status:by-design
