### ISSUE TITLE
Azure AD Permission Management Not Functional as of 9/6/2018

### ISSUE THREAD

**Issue by jonthenerd** [SharePoint/sp-dev-docs#2485] opened 2018-09-06 16:02 UTC
When accessing the API management screen within a tenant, a dialog appears stating "***Access to Azure Active Directory resources using the SharePoint Framework will be available soon." If the dialog is dismissed, two error messages are shown on the screen which state:"[HTTP]:500 - Internal Server Error [CorrelationId]:881c8c9e-1003-6000-eade-8f45b7e5c355 [Version]:16.0.0.8022 - Insufficient privileges to complete the operation."

I've confirmed this behavior in a company tenant as well as a dev tenant. How soon is "soon"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47b09a1d-5520-82e2-64f5-7aaae817720a
* Version Independent ID: 0e3dcdc4-3a49-b4c7-f525-1c618cf5e21e
* Content: [Connect to Azure AD-secured APIs in SharePoint Framework solutions](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient)
* Content Source: [docs/spfx/use-aadhttpclient.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/use-aadhttpclient.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by jonthenerd** [comment] 2018-09-06 16:07
See #2480 for discussion on issue affecting these instructions

**Comment by eoverfield** [comment] 2018-09-06 19:09
I am suggesting a review of https://github.com/SharePoint/sp-dev-docs/issues/2472 for more information as well.

**Comment by patmill** [comment] 2018-09-06 20:59
Duplicate of https://github.com/SharePoint/sp-dev-docs/issues/2472

**Closed by patmill** 2018-09-06 20:59 UTC
