### ISSUE TITLE
Image Web Part resizes images via JS and not CSS

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#1699] opened 2018-04-19 09:47 UTC
#### Category
- [x] Question

#### Expected or Desired Behavior
An image should have a smooth transition when the page gets resized. Right now the images get squeezed during the resizing of the window. Once the resize of the window is completed, a javascript recalculate the proper size. This cause a small display lag for about 500ms. Enough that user will recognize. In addition, all these listeners for resize on the DOM might cause troubles in performance.
To maintain the proper ratio of an image no additional JS is also needed in CSS3

#### Observed Behavior
In a responsive design, images should only get resized via CSS and not JavaScript. This is possible without any downtime on resizing. Right now when a window gets resized the following result will be displayed.

**Image before the resize**
![800px](https://user-images.githubusercontent.com/5503835/38984387-d37df218-43c6-11e8-8ceb-3f41af00f7bb.jpg)

**Image during resize**
![800px-squeezed](https://user-images.githubusercontent.com/5503835/38984405-df3b22a6-43c6-11e8-83c1-42c4beecee6d.jpg)

**Image after resize**
![400px](https://user-images.githubusercontent.com/5503835/38984421-ea8aac94-43c6-11e8-987d-cd60dc87e983.jpg)

#### Steps to Reproduce
Add an image web part on a modern experience page and resize the window. The squeeze should happen in any browser at least on the one I've observed.

**Comment by VesaJuvonen** [comment] 2018-04-20 17:14
Directly from the people who implemented this - "the primary design goal is to get the media service to resize on the server. If media service is down/unreliable, we fall back to downsizing on the client. At the end of the day, it's achieved via CSS but that JS is involved in calculating the inline styles. So closing by design."

**Closed by VesaJuvonen** 2018-04-20 17:14 UTC
Labels: area:other, status:by-design, type:question

**Comment by StfBauer** [comment] 2018-04-20 17:53
Thank you @VesaJuvonen anyway.
Now we know it is buggy by design cause JS calculation and inline styles is something that has been used pre-responsive web design. In addition, the media service only helps you on the first load after that it is just laggy.
