### ISSUE TITLE
SharePoint Online styling interferers with SPFx based solutions that use Office UI Fabric React

### ISSUE THREAD

**Issue by dev-a11y** [SharePoint/sp-dev-docs#6567] opened 2020-12-16 15:09 UTC
## Category

- [x] Bug

## Describe the bug

We have noticed that below styling has been added to SharePoint Online modern pages:
.ms-ContextualMenu-icon[data-icon-name=Info]{margin-top:2px}

 below is the problem with overflow we observe as a result of that rule:

![image](https://user-images.githubusercontent.com/59690753/102361809-ec3c4200-3fb3-11eb-82a6-730717b7dc58.png)

That rule is not yet present on all our tenants. This may mean that it is some recent development. Looking at latest changes in DOM structure and minified classnames (and the fact that in other rules in that section we see .e_b_ea5ab61a or .j_b_ea5ab61a) it may look like forgotten case or intended global 'hack' for contextual menus - proper way would be providing dedicated wrapper classname in order to customize those (callouts are rendered on separate layer). It seems like some reflection/review has been made over last months and one may have an impression that isolation of styling between components on pages is the goal of SharePoint dev team (at least those changes with minifying classnames may give such impression).

## Steps to reproduce

Create custom component that utilizes [ContextualMenu with icons](https://developer.microsoft.com/en-us/fluentui#/controls/web/contextualmenu) with **last element on the list** containing 'Info' icon

## Expected behavior

No overflow, no interference from internal SharePoint styling alignments (margin top 2px) - such SharePoint scoped alignments shall be 'targeted' with suffixed or wrapper classnames

## Environment details (*development & target environment*)

- **Target Environment**: [SharePoint Online]
- **Browser(s)**: [Chrome]
- **Tooling**: SPFx v1.11.0

*Thanks for your contribution! Sharing is caring.*

**Comment by Amos-MSFT** [comment] 2020-12-17 07:30
I could not reproduce your issue, could you share a demo that can reproduce the problem?
![yyye](https://user-images.githubusercontent.com/56672877/102456799-b6af5b80-407c-11eb-93c6-256fbfd959e1.PNG)
Amos Wu
Microsoft SharePoint Community Support

**Comment by andrewconnell** [comment] 2020-12-21 21:40
@dev-a11y I suggest you go back and update your OP to include details in the environment section to state what version of SPFx you're using.

**Comment by dev-a11y** [comment] 2020-12-22 09:52
@Amos-MSFT  - info icon needs to be set for last not first element (as mentioned in description) to reproduce it (but also please see remark - 'rule is not yet present on all our tenants')
@andrewconnell  - added spfx version in OP section; and here is a bit more context (both extracts are from respective pages on modern communication site):

Site Contents (please notice **.ms-ContextualMenu-icon.ms-Icon--Info{margin-top:2px}** below):
`<style data-load-themed-styles="true">.ms-ContextualMenu-icon{color:#03787c;font-size:16px;width:16px}.ms-ContextualMenu-icon.ms-Icon--Info{margin-top:2px}.ms-ContextualMenu-icon[data-icon-name=ExcelLogo]{color:#217346}.ms-ContextualMenu-icon[data-icon-name=OneNoteLogo]{color:#5c2d91}.ms-ContextualMenu-icon[data-icon-name=PowerPointLogo]{color:#d24726}.ms-ContextualMenu-icon[data-icon-name=WordLogo]{color:#2b579a}.ms-ContextualMenu-icon[data-icon-name=VisioLogo]{color:#3854a2}.ms-ContextualMenu-icon.od-NeedsAttentionViewIcon{color:#a4262c}.ms-ContextualMenu-icon.ms-Icon--CustomIcon,.ms-ContextualMenu-icon.ms-Icon--custom{width:16px;height:36px;background-size:contain}.ContextualMenu-uploadInput{position:absolute;top:0;bottom:0;left:0;right:0;opacity:.0001;cursor:pointer;overflow:hidden;z-index:9999999}.ContextualMenu-uploadInput input{position:absolute;top:0;font-size:200px;height:100px;cursor:pointer;margin:0;padding:0}[dir=ltr] .ContextualMenu-uploadInput input{right:0}[dir=rtl] .ContextualMenu-uploadInput input{left:0}.ContextualMenu-uploadInput-container{box-sizing:border-box;padding:0}.ContextualMenu-uploadInput-Text{display:block}</style>`

empty Site Page (please notice **.ms-ContextualMenu-icon[data-icon-name=Info]{margin-top:2px}** below):
[...]`.j_b_ea5ab61a .ms-DetailsList-headerWrapper i[class*=gripperBarVertical]{display:none}.ms-DetailsRow-cell.detailsListCellDotDotDot{padding:0;overflow:visible}.ms-DetailsRow:hover .od-FieldRenderer-dot,.od-FieldRenderer-dot:focus{opacity:1}.ms-Panel-content .od-FilterSelect-panel .od-FilterSelect-region{padding-top:26px}[dir=ltr] .ms-DetailsHeader-cell .ms-DetailsHeader-filterChevron.ms-Icon{padding-left:8px}[dir=rtl] .ms-DetailsHeader-cell .ms-DetailsHeader-filterChevron.ms-Icon{padding-right:8px}.ms-ContextualMenu-icon{color:#03787c;font-size:16px;width:16px}.ms-ContextualMenu-icon[data-icon-name=Info]{margin-top:2px}.ms-ContextualMenu-icon[data-icon-name=ExcelLogo]{color:#217346}.ms-ContextualMenu-icon[data-icon-name=OneNoteLogo]{color:#5c2d91}.ms-ContextualMenu-icon[data-icon-name=PowerPointLogo]{color:#d24726}.ms-ContextualMenu-icon[data-icon-name=WordLogo]{color:#2b579a}.ms-ContextualMenu-icon[data-icon-name=VisioLogo]{color:#3854a2}.ms-ContextualMenu-icon[data-icon-name=custom],.ms-ContextualMenu-icon[data-icon-name=CustomIcon]{width:16px;height:36px;background-size:contain}</style>`

In my view this is the kind of issue that may require static code analysis and not reproducibility - someone could _just do ctrl+shift+f kind of_ search on top of SharePoin't Online client side codebase and see what is the reason for having that override ;-)
I can confirm that this is not related to SPFx nor office ui fabric/fluent ui package - had served same code on other tenant without reproducing it - that's why I mentioned that it looks like some recent change in SharePoint Online that is currently rolling out.. it may be something with list renderer (those od-FieldRenderer-dot and ms-DetailsHeader-cell that on modern site pages always come before that messy section with icon overrides)..
It's not only about this one thing but in general about isolation of SharePoint's oob styling to avoid interference with client's code... maybe there is a way to 'disable' those generic classnames in ui fabric (to keep only the ones that are suffixed) but that would probably increase bundle size..

**Comment by AJIXuMuK** [comment] 2021-12-15 14:50
Different pages may have different CSS for various reasons.
Currently we're not looking at aligning the styles.

I will close this one.
Please, feel free to open a new issue with details if there is any bug you experience due to the styles.

**Closed by AJIXuMuK** 2021-12-15 14:50 UTC
Labels: type:question, area:spfx, Needs: Context Detail :question:
